var COURSE_NL_AR = [
  {
    title: "Begroeten en afscheid nemen",
    titleNative: "التحيات والوداع",
    focus: "Vandaag leer je eenvoudige begroetingen die je meteen kunt gebruiken in Amman, Caïro of Rabat. Je oefent beleefd beginnen en afsluiten van een kort gesprek.",
    vocab: [
      {ar: "مرحبا", nl: "hallo", ipa: "mar-ha-ban"},
      {ar: "أهلا", nl: "hallo / welkom", ipa: "ah-lan"},
      {ar: "صباح الخير", nl: "goedemorgen", ipa: "sa-baa-h al-khair"},
      {ar: "مساء الخير", nl: "goedenavond", ipa: "ma-saa al-khair"},
      {ar: "وداعا", nl: "tot ziens", ipa: "wa-daa-an"},
      {ar: "نعم", nl: "ja", ipa: "na-am"},
      {ar: "لا", nl: "nee", ipa: "laa"},
      {ar: "شكرا", nl: "bedankt", ipa: "shuk-ran"},
      {ar: "من فضلك", nl: "alstublieft", ipa: "min fad-lik"},
      {ar: "آسف", nl: "sorry", ipa: "aa-sif"},
    ],
    phrases: [
      {ar: "مرحبا، كيف حالك؟", nl: "Hallo, hoe gaat het?", ipa: "mar-ha-ban, kay-fa haa-luk"},
      {ar: "أنا بخير، شكرا", nl: "Het gaat goed, bedankt", ipa: "a-naa bi-khair, shuk-ran"},
      {ar: "صباح الخير", nl: "Goedemorgen", ipa: "sa-baa-h al-khair"},
      {ar: "مساء الخير", nl: "Goedenavond", ipa: "ma-saa al-khair"},
      {ar: "إلى اللقاء", nl: "Tot ziens", ipa: "i-laa al-li-qaa"},
      {ar: "شكرا جزيلا", nl: "Heel erg bedankt", ipa: "shuk-ran ja-zii-lan"},
    ],
    grammar: "Arabisch heeft verschillende begroetingen voor verschillende momenten van de dag, net als het Nederlands. In veel Arabischsprekende landen is beleefd groeten belangrijk, ook bij korte interacties in winkels of taxi’s. Gebruik مرحبا als veilige algemene begroeting.",
    practice: [
      "1. Begroet iemand in het Arabisch en zeg daarna bedankt.",
      "2. Zeg goedemorgen tegen een hotelmedewerker.",
      "3. Reageer op “كيف حالك؟” met “Het gaat goed, bedankt.”",
      "4. Schrijf drie begroetingen over met de uitspraak erbij.",
      "5. Oefen een kort afscheid: hallo, bedankt, tot ziens.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Jezelf voorstellen",
    titleNative: "التعريف بالنفس",
    focus: "Vandaag leer je hoe je je naam zegt en vraagt naar de naam van iemand anders. Dit is handig bij een hostel, taalschool of rondleiding in Beiroet.",
    vocab: [
      {ar: "أنا", nl: "ik", ipa: "a-naa"},
      {ar: "أنت", nl: "jij", ipa: "an-ta"},
      {ar: "اسمي", nl: "mijn naam is", ipa: "is-mii"},
      {ar: "اسمك", nl: "jouw naam", ipa: "is-muk"},
      {ar: "ما", nl: "wat", ipa: "maa"},
      {ar: "هذا", nl: "dit", ipa: "haa-dhaa"},
      {ar: "سعيد", nl: "blij", ipa: "sa-iid"},
      {ar: "لقاء", nl: "ontmoeting", ipa: "li-qaa"},
      {ar: "صديق", nl: "vriend", ipa: "sa-diiq"},
      {ar: "جديد", nl: "nieuw", ipa: "ja-diid"},
    ],
    phrases: [
      {ar: "اسمي يان", nl: "Mijn naam is Jan", ipa: "is-mii yaan"},
      {ar: "ما اسمك؟", nl: "Hoe heet jij?", ipa: "maa is-muk"},
      {ar: "تشرفت بلقائك", nl: "Aangenaam kennis te maken", ipa: "ta-shar-raftu bi-li-qaa-ik"},
      {ar: "أنا من هولندا", nl: "Ik kom uit Nederland", ipa: "a-naa min ho-lan-da"},
      {ar: "هل أنت من هنا؟", nl: "Kom jij hier vandaan?", ipa: "hal an-ta min hu-naa"},
      {ar: "أنا سائح", nl: "Ik ben toerist", ipa: "a-naa saa-ih"},
    ],
    grammar: "Het woord أنا betekent “ik” en wordt vaak gebruikt om jezelf duidelijk voor te stellen. In het Arabisch staat “mijn naam” als اسمي, letterlijk “naam-mijn”. Bezitsvormen worden vaak achter het woord geplakt.",
    practice: [
      "1. Stel jezelf voor met je eigen naam.",
      "2. Vraag iemand hoe hij of zij heet.",
      "3. Zeg dat je uit Nederland komt.",
      "4. Maak een minidialoog van vier regels.",
      "5. Oefen “تشرفت بلقائك” hardop drie keer.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Basisvragen stellen",
    titleNative: "الأسئلة الأساسية",
    focus: "Vandaag leer je korte vraagwoorden voor situaties in een stad zoals Tunis of Doha. Je kunt hiermee hulp vragen zonder lange zinnen te maken.",
    vocab: [
      {ar: "ماذا", nl: "wat", ipa: "maa-dhaa"},
      {ar: "أين", nl: "waar", ipa: "ay-na"},
      {ar: "متى", nl: "wanneer", ipa: "ma-taa"},
      {ar: "كيف", nl: "hoe", ipa: "kay-fa"},
      {ar: "من", nl: "wie / van", ipa: "man / min"},
      {ar: "لماذا", nl: "waarom", ipa: "li-maa-dhaa"},
      {ar: "هل", nl: "vraagwoord voor ja/nee", ipa: "hal"},
      {ar: "هنا", nl: "hier", ipa: "hu-naa"},
      {ar: "هناك", nl: "daar", ipa: "hu-naak"},
      {ar: "الآن", nl: "nu", ipa: "al-aan"},
    ],
    phrases: [
      {ar: "أين الفندق؟", nl: "Waar is het hotel?", ipa: "ay-na al-fun-duq"},
      {ar: "ماذا تريد؟", nl: "Wat wil je?", ipa: "maa-dhaa tu-riid"},
      {ar: "متى يفتح؟", nl: "Wanneer gaat het open?", ipa: "ma-taa yaf-tah"},
      {ar: "كيف أذهب إلى السوق؟", nl: "Hoe ga ik naar de markt?", ipa: "kay-fa adh-hab i-laa as-suuq"},
      {ar: "هل هذا قريب؟", nl: "Is dit dichtbij?", ipa: "hal haa-dhaa qa-riib"},
      {ar: "من هنا؟", nl: "Vanaf hier?", ipa: "min hu-naa"},
    ],
    grammar: "Voor ja/nee-vragen kun je هل aan het begin van de zin zetten. Dat maakt een gewone zin meteen tot een vraag. Vraagwoorden zoals أين en كيف staan meestal vroeg in de zin.",
    practice: [
      "1. Vraag waar het hotel is.",
      "2. Vraag of iets dichtbij is.",
      "3. Maak drie vragen met هل.",
      "4. Vertaal “Waar is de markt?” naar het Arabisch.",
      "5. Oefen de woorden أين, ماذا en كيف met voorbeelden.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Getallen van nul tot tien",
    titleNative: "الأرقام من صفر إلى عشرة",
    focus: "Vandaag leer je tellen tot tien, handig voor prijzen, kamernummers en tafels in een restaurant. In steden als Marrakech of Aqaba hoor je getallen voortdurend.",
    vocab: [
      {ar: "صفر", nl: "nul", ipa: "sifr"},
      {ar: "واحد", nl: "één", ipa: "waa-hid"},
      {ar: "اثنان", nl: "twee", ipa: "ith-naan"},
      {ar: "ثلاثة", nl: "drie", ipa: "tha-laa-tha"},
      {ar: "أربعة", nl: "vier", ipa: "ar-ba-a"},
      {ar: "خمسة", nl: "vijf", ipa: "kham-sa"},
      {ar: "ستة", nl: "zes", ipa: "sit-ta"},
      {ar: "سبعة", nl: "zeven", ipa: "sab-a"},
      {ar: "ثمانية", nl: "acht", ipa: "tha-maa-ni-ya"},
      {ar: "عشرة", nl: "tien", ipa: "a-sha-ra"},
    ],
    phrases: [
      {ar: "واحد من فضلك", nl: "Eén, alstublieft", ipa: "waa-hid min fad-lik"},
      {ar: "اثنان من القهوة", nl: "Twee koffie", ipa: "ith-naan min al-qah-wa"},
      {ar: "كم السعر؟", nl: "Wat is de prijs?", ipa: "kam as-si-r"},
      {ar: "الغرفة رقم خمسة", nl: "Kamer nummer vijf", ipa: "al-ghur-fa ra-qam kham-sa"},
      {ar: "أريد ثلاثة", nl: "Ik wil er drie", ipa: "u-riid tha-laa-tha"},
      {ar: "هل عندك عشرة؟", nl: "Heb je tien?", ipa: "hal in-dak a-sha-ra"},
    ],
    grammar: "Getallen worden in Arabisch vaak gebruikt met رقم voor nummers, zoals kamer- of busnummer. In spreektaal kan de vorm per land verschillen, maar deze standaardvormen worden breed begrepen. Leer eerst verstaan, daarna snel spreken.",
    practice: [
      "1. Tel van nul tot tien hardop.",
      "2. Bestel twee koffie in het Arabisch.",
      "3. Zeg “kamer nummer vijf”.",
      "4. Vraag naar de prijs.",
      "5. Schrijf vijf getallen willekeurig en lees ze hardop.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Beleefdheid en hulp vragen",
    titleNative: "الأدب وطلب المساعدة",
    focus: "Vandaag leer je vriendelijk hulp vragen in drukke situaties, zoals op een station in Caïro. Beleefdheid maakt korte gesprekken veel makkelijker.",
    vocab: [
      {ar: "مساعدة", nl: "hulp", ipa: "mu-saa-a-da"},
      {ar: "أحتاج", nl: "ik heb nodig", ipa: "ah-taa-j"},
      {ar: "أريد", nl: "ik wil", ipa: "u-riid"},
      {ar: "ممكن", nl: "mogelijk / kan het", ipa: "mum-kin"},
      {ar: "لو سمحت", nl: "alstublieft / excuseer", ipa: "law sa-maht"},
      {ar: "عفوا", nl: "pardon / graag gedaan", ipa: "af-wan"},
      {ar: "لحظة", nl: "moment", ipa: "lah-za"},
      {ar: "جيد", nl: "goed", ipa: "jay-yid"},
      {ar: "مشكلة", nl: "probleem", ipa: "mush-ki-la"},
      {ar: "سهل", nl: "makkelijk", ipa: "sahl"},
    ],
    phrases: [
      {ar: "أحتاج مساعدة", nl: "Ik heb hulp nodig", ipa: "ah-taa-j mu-saa-a-da"},
      {ar: "لو سمحت، أين المترو؟", nl: "Pardon, waar is de metro?", ipa: "law sa-maht, ay-na al-met-ro"},
      {ar: "ممكن تساعدني؟", nl: "Kunt u mij helpen?", ipa: "mum-kin tu-saa-id-ni"},
      {ar: "عفوا، لا أفهم", nl: "Pardon, ik begrijp het niet", ipa: "af-wan, laa af-ham"},
      {ar: "لحظة من فضلك", nl: "Een moment alstublieft", ipa: "lah-za min fad-lik"},
      {ar: "لا مشكلة", nl: "Geen probleem", ipa: "laa mush-ki-la"},
    ],
    grammar: "لو سمحت is een zeer nuttige beleefde opener. Je kunt het vóór een vraag zetten om vriendelijker te klinken. In veel situaties werkt het als “excuseer” en “alstublieft” tegelijk.",
    practice: [
      "1. Vraag beleefd om hulp.",
      "2. Zeg dat je het niet begrijpt.",
      "3. Vraag iemand om een moment te wachten.",
      "4. Maak een zin met أحتاج.",
      "5. Oefen een gesprek aan een informatiebalie.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Op het vliegveld",
    titleNative: "في المطار",
    focus: "Vandaag oefen je woorden voor aankomst, bagage en paspoortcontrole. Dit helpt bij aankomst op luchthavens zoals Dubai, Casablanca of Amman.",
    vocab: [
      {ar: "مطار", nl: "vliegveld", ipa: "ma-taar"},
      {ar: "جواز سفر", nl: "paspoort", ipa: "ja-waaz sa-far"},
      {ar: "حقيبة", nl: "tas / koffer", ipa: "ha-qii-ba"},
      {ar: "تذكرة", nl: "ticket", ipa: "tadh-ki-ra"},
      {ar: "رحلة", nl: "vlucht", ipa: "rih-la"},
      {ar: "بوابة", nl: "gate", ipa: "baw-wa-ba"},
      {ar: "وصول", nl: "aankomst", ipa: "wu-suul"},
      {ar: "مغادرة", nl: "vertrek", ipa: "mu-ghaa-da-ra"},
      {ar: "تأخير", nl: "vertraging", ipa: "ta-khiir"},
      {ar: "أمتعة", nl: "bagage", ipa: "am-ti-a"},
    ],
    phrases: [
      {ar: "أين جواز السفر؟", nl: "Waar is het paspoort?", ipa: "ay-na ja-waaz as-sa-far"},
      {ar: "هذه حقيبتي", nl: "Dit is mijn koffer", ipa: "haa-dhihi ha-qii-ba-tii"},
      {ar: "أين بوابة الرحلة؟", nl: "Waar is de gate van de vlucht?", ipa: "ay-na baw-wa-ba ar-rih-la"},
      {ar: "هل الرحلة متأخرة؟", nl: "Is de vlucht vertraagd?", ipa: "hal ar-rih-la mu-ta-akh-khi-ra"},
      {ar: "أريد سيارة أجرة", nl: "Ik wil een taxi", ipa: "u-riid say-yaa-ra uj-ra"},
      {ar: "أنا قادم من أمستردام", nl: "Ik kom uit Amsterdam", ipa: "a-naa qaa-dim min am-ster-daam"},
    ],
    grammar: "In Arabisch wordt bezit vaak met een achtervoegsel gevormd: حقيبتي betekent “mijn tas/koffer”. De uitgang ـي klinkt als “-ii” en betekent vaak “mijn”. Dit is handig bij bagage, kamer en ticket.",
    practice: [
      "1. Zeg “dit is mijn koffer”.",
      "2. Vraag waar de gate is.",
      "3. Vraag of de vlucht vertraagd is.",
      "4. Maak drie zinnen met أين.",
      "5. Oefen een korte aankomstscène bij de bagageband.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Taxi en ritten",
    titleNative: "التاكسي والرحلات",
    focus: "Vandaag leer je een taxi nemen en je bestemming noemen. Dit is praktisch in steden zoals Riyad, Alexandrië en Muscat.",
    vocab: [
      {ar: "تاكسي", nl: "taxi", ipa: "taak-si"},
      {ar: "سيارة أجرة", nl: "taxi", ipa: "say-yaa-ra uj-ra"},
      {ar: "عنوان", nl: "adres", ipa: "un-waan"},
      {ar: "فندق", nl: "hotel", ipa: "fun-duq"},
      {ar: "شارع", nl: "straat", ipa: "shaa-ri"},
      {ar: "يمين", nl: "rechts", ipa: "ya-miin"},
      {ar: "يسار", nl: "links", ipa: "ya-saar"},
      {ar: "مستقيم", nl: "rechtdoor", ipa: "mus-ta-qiim"},
      {ar: "قريب", nl: "dichtbij", ipa: "qa-riib"},
      {ar: "بعيد", nl: "ver", ipa: "ba-iid"},
    ],
    phrases: [
      {ar: "إلى هذا العنوان من فضلك", nl: "Naar dit adres, alstublieft", ipa: "i-laa haa-dhaa al-un-waan min fad-lik"},
      {ar: "كم إلى الفندق؟", nl: "Hoeveel naar het hotel?", ipa: "kam i-laa al-fun-duq"},
      {ar: "من فضلك، اذهب يمين", nl: "Ga rechts, alstublieft", ipa: "min fad-lik, idh-hab ya-miin"},
      {ar: "هل المكان بعيد؟", nl: "Is de plek ver?", ipa: "hal al-ma-kaan ba-iid"},
      {ar: "توقف هنا من فضلك", nl: "Stop hier, alstublieft", ipa: "ta-waq-qaf hu-naa min fad-lik"},
      {ar: "كم الوقت؟", nl: "Hoe lang duurt het?", ipa: "kam al-waqt"},
    ],
    grammar: "Richtingen zijn korte woorden die je vaak los kunt gebruiken: يمين, يسار, مستقيم. In een taxi hoef je niet perfect te spreken; een adres tonen en een paar richtingwoorden kennen is genoeg. من فضلك maakt instructies beleefder.",
    practice: [
      "1. Vraag een taxi naar je hotel.",
      "2. Zeg rechts, links en rechtdoor.",
      "3. Vraag of de bestemming ver is.",
      "4. Zeg “stop hier, alstublieft”.",
      "5. Speel een taxigesprek van zes regels.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Hotel inchecken",
    titleNative: "تسجيل الدخول في الفندق",
    focus: "Vandaag oefen je inchecken bij een hotel in een Arabischsprekend land. Je leert vragen naar je reservering, kamer en ontbijt.",
    vocab: [
      {ar: "حجز", nl: "reservering", ipa: "hajz"},
      {ar: "غرفة", nl: "kamer", ipa: "ghur-fa"},
      {ar: "مفتاح", nl: "sleutel", ipa: "mif-taah"},
      {ar: "استقبال", nl: "receptie", ipa: "is-tiq-baal"},
      {ar: "ليلة", nl: "nacht", ipa: "lay-la"},
      {ar: "إفطار", nl: "ontbijt", ipa: "if-taar"},
      {ar: "مصعد", nl: "lift", ipa: "mis-ad"},
      {ar: "طابق", nl: "verdieping", ipa: "taa-biq"},
      {ar: "حمام", nl: "badkamer", ipa: "ham-maam"},
      {ar: "واي فاي", nl: "wifi", ipa: "wai-fai"},
    ],
    phrases: [
      {ar: "لدي حجز", nl: "Ik heb een reservering", ipa: "la-day-ya hajz"},
      {ar: "اسمي يان دي فريس", nl: "Mijn naam is Jan de Vries", ipa: "is-mii yaan de friis"},
      {ar: "أين غرفتي؟", nl: "Waar is mijn kamer?", ipa: "ay-na ghur-fa-tii"},
      {ar: "هل الإفطار مشمول؟", nl: "Is ontbijt inbegrepen?", ipa: "hal al-if-taar mash-muul"},
      {ar: "ما كلمة سر الواي فاي؟", nl: "Wat is het wifiwachtwoord?", ipa: "maa ka-li-ma-tu sirr al-wai-fai"},
      {ar: "أين المصعد؟", nl: "Waar is de lift?", ipa: "ay-na al-mis-ad"},
    ],
    grammar: "لدي betekent “ik heb” en is heel handig in hotels: لدي حجز, لدي سؤال, لدي مشكلة. Het klinkt beleefd en duidelijk. Gebruik het wanneer je iets bezit of een probleem wilt melden.",
    practice: [
      "1. Zeg dat je een reservering hebt.",
      "2. Vraag naar het wifiwachtwoord.",
      "3. Vraag of ontbijt inbegrepen is.",
      "4. Maak een zin met لدي.",
      "5. Oefen een hotelcheck-in met naam en reservering.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kamerproblemen",
    titleNative: "مشاكل الغرفة",
    focus: "Vandaag leer je praktische zinnen voor problemen in je hotelkamer. Dit is nuttig als de airco, douche of wifi niet werkt.",
    vocab: [
      {ar: "مشكلة", nl: "probleem", ipa: "mush-ki-la"},
      {ar: "المكيف", nl: "airco", ipa: "al-mu-kay-yif"},
      {ar: "لا يعمل", nl: "werkt niet", ipa: "laa ya-mal"},
      {ar: "ماء", nl: "water", ipa: "maa"},
      {ar: "ساخن", nl: "warm", ipa: "saa-khin"},
      {ar: "بارد", nl: "koud", ipa: "baa-rid"},
      {ar: "نظيف", nl: "schoon", ipa: "na-ziif"},
      {ar: "وسخ", nl: "vies", ipa: "wa-sikh"},
      {ar: "ضوء", nl: "licht", ipa: "daw"},
      {ar: "ضوضاء", nl: "lawaai", ipa: "dawd-aa"},
    ],
    phrases: [
      {ar: "لدي مشكلة في الغرفة", nl: "Ik heb een probleem in de kamer", ipa: "la-day-ya mush-ki-la fii al-ghur-fa"},
      {ar: "المكيف لا يعمل", nl: "De airco werkt niet", ipa: "al-mu-kay-yif laa ya-mal"},
      {ar: "لا يوجد ماء ساخن", nl: "Er is geen warm water", ipa: "laa yuu-jad maa saa-khin"},
      {ar: "الغرفة غير نظيفة", nl: "De kamer is niet schoon", ipa: "al-ghur-fa ghayr na-zii-fa"},
      {ar: "هناك ضوضاء كثيرة", nl: "Er is veel lawaai", ipa: "hu-naak dawd-aa ka-thii-ra"},
      {ar: "ممكن غرفة أخرى؟", nl: "Kan ik een andere kamer krijgen?", ipa: "mum-kin ghur-fa ukh-raa"},
    ],
    grammar: "لا betekent “niet” of “geen” en staat vaak vóór het werkwoord. لا يعمل betekent letterlijk “werkt niet”. Voor reizigers is dit een van de nuttigste patronen om problemen duidelijk te maken.",
    practice: [
      "1. Zeg dat de airco niet werkt.",
      "2. Meld dat er geen warm water is.",
      "3. Vraag om een andere kamer.",
      "4. Maak drie zinnen met لا.",
      "5. Oefen een klacht bij de receptie beleefd te zeggen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Eten en drinken bestellen",
    titleNative: "طلب الطعام والشراب",
    focus: "Vandaag leer je bestellen in een café of klein restaurant. Je oefent eenvoudige zinnen voor koffie, water en lokale gerechten.",
    vocab: [
      {ar: "قهوة", nl: "koffie", ipa: "qah-wa"},
      {ar: "شاي", nl: "thee", ipa: "shaay"},
      {ar: "ماء", nl: "water", ipa: "maa"},
      {ar: "عصير", nl: "sap", ipa: "a-siir"},
      {ar: "خبز", nl: "brood", ipa: "khubz"},
      {ar: "دجاج", nl: "kip", ipa: "da-jaaj"},
      {ar: "أرز", nl: "rijst", ipa: "urz"},
      {ar: "سلطة", nl: "salade", ipa: "sa-la-ta"},
      {ar: "حساء", nl: "soep", ipa: "ha-saa"},
      {ar: "حلوى", nl: "dessert", ipa: "hal-waa"},
    ],
    phrases: [
      {ar: "أريد قهوة من فضلك", nl: "Ik wil koffie, alstublieft", ipa: "u-riid qah-wa min fad-lik"},
      {ar: "ماء بدون غاز", nl: "Water zonder prik", ipa: "maa bi-duun ghaaz"},
      {ar: "ماذا تنصح؟", nl: "Wat raadt u aan?", ipa: "maa-dhaa tan-sah"},
      {ar: "أريد هذا الطبق", nl: "Ik wil dit gerecht", ipa: "u-riid haa-dhaa at-ta-baq"},
      {ar: "هل عندكم شاي؟", nl: "Hebben jullie thee?", ipa: "hal in-da-kum shaay"},
      {ar: "الحساب من فضلك", nl: "De rekening, alstublieft", ipa: "al-hi-saab min fad-lik"},
    ],
    grammar: "أريد betekent “ik wil” en is direct maar normaal in servicecontexten. Voeg من فضلك toe om beleefd te klinken. In restaurants kun je vaak wijzen en zeggen: أريد هذا.",
    practice: [
      "1. Bestel koffie en water.",
      "2. Vraag wat de ober aanraadt.",
      "3. Vraag om de rekening.",
      "4. Maak drie bestellingen met أريد.",
      "5. Oefen een caféscène met begroeting, bestelling en betaling.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "In een restaurant",
    titleNative: "في المطعم",
    focus: "Vandaag breid je restauranttaal uit voor tafels, menu’s en voorkeuren. Dit helpt bij eten in Amman, Rabat of Abu Dhabi.",
    vocab: [
      {ar: "مطعم", nl: "restaurant", ipa: "mat-am"},
      {ar: "طاولة", nl: "tafel", ipa: "taa-wi-la"},
      {ar: "قائمة", nl: "menu", ipa: "qaa-i-ma"},
      {ar: "طبق", nl: "gerecht", ipa: "ta-baq"},
      {ar: "لحم", nl: "vlees", ipa: "lahm"},
      {ar: "سمك", nl: "vis", ipa: "sa-mak"},
      {ar: "خضار", nl: "groenten", ipa: "khu-daar"},
      {ar: "حار", nl: "pittig", ipa: "haar"},
      {ar: "لذيذ", nl: "lekker", ipa: "la-dhiidh"},
      {ar: "حساب", nl: "rekening", ipa: "hi-saab"},
    ],
    phrases: [
      {ar: "طاولة لشخصين من فضلك", nl: "Een tafel voor twee, alstublieft", ipa: "taa-wi-la li-shakh-sayn min fad-lik"},
      {ar: "هل عندكم قائمة باللغة الإنجليزية؟", nl: "Heeft u een menu in het Engels?", ipa: "hal in-da-kum qaa-i-ma bil-lugha al-in-glii-ziya"},
      {ar: "لا أريد شيئا حارا", nl: "Ik wil niets pittigs", ipa: "laa u-riid shay-an haar-ran"},
      {ar: "هذا لذيذ جدا", nl: "Dit is heel lekker", ipa: "haa-dhaa la-dhiidh jid-dan"},
      {ar: "نريد الحساب", nl: "Wij willen de rekening", ipa: "nu-riid al-hi-saab"},
      {ar: "هل الخدمة مشمولة؟", nl: "Is service inbegrepen?", ipa: "hal al-khid-ma mash-muu-la"},
    ],
    grammar: "Voor “wij willen” gebruik je نريد in plaats van أريد. Dit is handig als je met iemand reist. In restaurants hoor je vaak عندكم, “hebben jullie”, om naar gerechten of opties te vragen.",
    practice: [
      "1. Vraag om een tafel voor twee.",
      "2. Zeg dat je niets pittigs wilt.",
      "3. Complimenteer het eten.",
      "4. Vraag of service inbegrepen is.",
      "5. Maak een dialoog tussen klant en ober.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Dieetwensen en allergieën",
    titleNative: "الحمية والحساسية",
    focus: "Vandaag leer je belangrijke zinnen voor allergieën en dieetwensen. Dit is cruciaal wanneer je onbekende gerechten probeert.",
    vocab: [
      {ar: "حساسية", nl: "allergie", ipa: "ha-saa-si-ya"},
      {ar: "مكسرات", nl: "noten", ipa: "mu-kas-sa-raat"},
      {ar: "حليب", nl: "melk", ipa: "ha-liib"},
      {ar: "بيض", nl: "ei", ipa: "bayd"},
      {ar: "جلوتين", nl: "gluten", ipa: "glu-tiin"},
      {ar: "نباتي", nl: "vegetarisch", ipa: "na-baa-tii"},
      {ar: "بدون", nl: "zonder", ipa: "bi-duun"},
      {ar: "قليل", nl: "weinig", ipa: "qa-liil"},
      {ar: "كثير", nl: "veel", ipa: "ka-thiir"},
      {ar: "خطر", nl: "gevaarlijk", ipa: "kha-tar"},
    ],
    phrases: [
      {ar: "لدي حساسية من المكسرات", nl: "Ik ben allergisch voor noten", ipa: "la-day-ya ha-saa-si-ya min al-mu-kas-sa-raat"},
      {ar: "بدون حليب من فضلك", nl: "Zonder melk, alstublieft", ipa: "bi-duun ha-liib min fad-lik"},
      {ar: "هل هذا نباتي؟", nl: "Is dit vegetarisch?", ipa: "hal haa-dhaa na-baa-tii"},
      {ar: "لا أستطيع أكل هذا", nl: "Ik kan dit niet eten", ipa: "laa as-ta-tii akl haa-dhaa"},
      {ar: "هل فيه بيض؟", nl: "Zit er ei in?", ipa: "hal fii-hi bayd"},
      {ar: "أريد شيئا بسيطا", nl: "Ik wil iets eenvoudigs", ipa: "u-riid shay-an ba-sii-tan"},
    ],
    grammar: "بدون betekent “zonder” en komt vóór het ingrediënt. Het is kort, duidelijk en zeer bruikbaar: بدون حليب, بدون لحم, بدون مكسرات. Bij allergieën is het beter om langzaam en duidelijk te spreken.",
    practice: [
      "1. Zeg dat je allergisch bent voor noten.",
      "2. Vraag of er ei in zit.",
      "3. Bestel iets zonder melk.",
      "4. Vraag of een gerecht vegetarisch is.",
      "5. Schrijf je eigen dieetwens in het Arabisch.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Boodschappen en markt",
    titleNative: "التسوق في السوق",
    focus: "Vandaag leer je praten op een markt of in een kleine winkel. Je oefent prijzen vragen en hoeveelheden noemen.",
    vocab: [
      {ar: "سوق", nl: "markt", ipa: "suuq"},
      {ar: "محل", nl: "winkel", ipa: "ma-hall"},
      {ar: "سعر", nl: "prijs", ipa: "si-r"},
      {ar: "كيلو", nl: "kilo", ipa: "kii-lo"},
      {ar: "تفاح", nl: "appels", ipa: "tuf-faah"},
      {ar: "برتقال", nl: "sinaasappels", ipa: "bur-tu-qaal"},
      {ar: "تمر", nl: "dadels", ipa: "tamr"},
      {ar: "خضروات", nl: "groenten", ipa: "khu-da-ra-waat"},
      {ar: "طازج", nl: "vers", ipa: "taa-zaj"},
      {ar: "كيس", nl: "tas / zak", ipa: "kiis"},
    ],
    phrases: [
      {ar: "كم سعر هذا؟", nl: "Hoeveel kost dit?", ipa: "kam si-r haa-dhaa"},
      {ar: "أريد كيلو تمر", nl: "Ik wil een kilo dadels", ipa: "u-riid kii-lo tamr"},
      {ar: "هل هذا طازج؟", nl: "Is dit vers?", ipa: "hal haa-dhaa taa-zaj"},
      {ar: "غالي جدا", nl: "Dat is heel duur", ipa: "ghaa-lii jid-dan"},
      {ar: "هل ممكن بسعر أقل؟", nl: "Kan het voor een lagere prijs?", ipa: "hal mum-kin bi-si-r a-qall"},
      {ar: "أحتاج كيسا", nl: "Ik heb een tas nodig", ipa: "ah-taa-j kii-san"},
    ],
    grammar: "كم betekent “hoeveel” en is essentieel bij prijzen. Op markten is vriendelijk onderhandelen in veel landen normaal, maar niet overal. Begin altijd beleefd en glimlachend.",
    practice: [
      "1. Vraag de prijs van een product.",
      "2. Koop een kilo dadels.",
      "3. Zeg dat iets te duur is.",
      "4. Vraag om een lagere prijs.",
      "5. Oefen een marktgesprek met drie producten.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kleding en maten",
    titleNative: "الملابس والمقاسات",
    focus: "Vandaag leer je winkelen voor kleding in een winkelcentrum of souk. Je vraagt naar maten, kleuren en passen.",
    vocab: [
      {ar: "ملابس", nl: "kleding", ipa: "ma-laa-bis"},
      {ar: "قميص", nl: "overhemd / shirt", ipa: "qa-miis"},
      {ar: "بنطال", nl: "broek", ipa: "bin-taal"},
      {ar: "فستان", nl: "jurk", ipa: "fus-taan"},
      {ar: "حذاء", nl: "schoen", ipa: "hi-dhaa"},
      {ar: "مقاس", nl: "maat", ipa: "ma-qaas"},
      {ar: "لون", nl: "kleur", ipa: "lawn"},
      {ar: "أبيض", nl: "wit", ipa: "ab-yad"},
      {ar: "أسود", nl: "zwart", ipa: "as-wad"},
      {ar: "أزرق", nl: "blauw", ipa: "az-raq"},
    ],
    phrases: [
      {ar: "هل عندكم مقاس أكبر؟", nl: "Heeft u een grotere maat?", ipa: "hal in-da-kum ma-qaas ak-bar"},
      {ar: "هل عندكم لون أسود؟", nl: "Heeft u zwart?", ipa: "hal in-da-kum lawn as-wad"},
      {ar: "أريد أن أجربه", nl: "Ik wil het passen", ipa: "u-riid an u-jar-ri-ba-h"},
      {ar: "أين غرفة القياس؟", nl: "Waar is de paskamer?", ipa: "ay-na ghur-fa al-qi-yaas"},
      {ar: "هذا صغير جدا", nl: "Dit is te klein", ipa: "haa-dhaa sa-ghiir jid-dan"},
      {ar: "سآخذه", nl: "Ik neem het", ipa: "sa-a-khu-dhu-h"},
    ],
    grammar: "أكبر betekent “groter” en أصغر betekent “kleiner”. Met هل عندكم kun je makkelijk naar maten en kleuren vragen. In kledingwinkels is wijzen naar het artikel vaak genoeg met هذا.",
    practice: [
      "1. Vraag om een grotere maat.",
      "2. Vraag of er een zwarte kleur is.",
      "3. Zeg dat je iets wilt passen.",
      "4. Zeg “ik neem het”.",
      "5. Maak een winkelgesprek van zes regels.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Openbaar vervoer",
    titleNative: "المواصلات العامة",
    focus: "Vandaag leer je woorden voor bus, metro en treinkaartjes. Dit is handig in steden met openbaar vervoer zoals Caïro, Dubai en Doha.",
    vocab: [
      {ar: "حافلة", nl: "bus", ipa: "haa-fi-la"},
      {ar: "مترو", nl: "metro", ipa: "met-ro"},
      {ar: "قطار", nl: "trein", ipa: "qi-taar"},
      {ar: "تذكرة", nl: "ticket", ipa: "tadh-ki-ra"},
      {ar: "محطة", nl: "station / halte", ipa: "ma-hat-ta"},
      {ar: "خط", nl: "lijn", ipa: "khatt"},
      {ar: "ذهاب", nl: "heenreis", ipa: "dha-haab"},
      {ar: "عودة", nl: "terugreis", ipa: "aw-da"},
      {ar: "خريطة", nl: "kaart / plattegrond", ipa: "kha-rii-ta"},
      {ar: "موعد", nl: "tijd / afspraak", ipa: "maw-id"},
    ],
    phrases: [
      {ar: "أريد تذكرة إلى المركز", nl: "Ik wil een ticket naar het centrum", ipa: "u-riid tadh-ki-ra i-laa al-mar-kaz"},
      {ar: "أين محطة المترو؟", nl: "Waar is het metrostation?", ipa: "ay-na ma-hat-tat al-met-ro"},
      {ar: "أي خط إلى السوق؟", nl: "Welke lijn naar de markt?", ipa: "ay-yu khatt i-laa as-suuq"},
      {ar: "هل هذه الحافلة تذهب إلى الفندق؟", nl: "Gaat deze bus naar het hotel?", ipa: "hal haa-dhihi al-haa-fi-la tadh-hab i-laa al-fun-duq"},
      {ar: "أريد تذكرة ذهاب وعودة", nl: "Ik wil een retourticket", ipa: "u-riid tadh-ki-rat dha-haab wa aw-da"},
      {ar: "متى يصل القطار؟", nl: "Wanneer komt de trein aan?", ipa: "ma-taa ya-sil al-qi-taar"},
    ],
    grammar: "إلى betekent “naar” en is onmisbaar bij vervoer. Je gebruikt het met plaatsen: إلى الفندق, إلى السوق, إلى المركز. Voor een retour zeg je letterlijk “heen en terug”: ذهاب وعودة.",
    practice: [
      "1. Koop een ticket naar het centrum.",
      "2. Vraag welke lijn naar de markt gaat.",
      "3. Vraag waar het metrostation is.",
      "4. Vraag of de bus naar je hotel gaat.",
      "5. Oefen een gesprek bij een loket.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Richtingen vragen",
    titleNative: "السؤال عن الاتجاهات",
    focus: "Vandaag leer je de weg vragen in een oude binnenstad of druk winkelgebied. Je oefent korte, duidelijke routezinnen.",
    vocab: [
      {ar: "طريق", nl: "weg", ipa: "ta-riiq"},
      {ar: "خريطة", nl: "kaart", ipa: "kha-rii-ta"},
      {ar: "قريب", nl: "dichtbij", ipa: "qa-riib"},
      {ar: "بعيد", nl: "ver", ipa: "ba-iid"},
      {ar: "أمام", nl: "voor", ipa: "a-maam"},
      {ar: "خلف", nl: "achter", ipa: "khalf"},
      {ar: "بجانب", nl: "naast", ipa: "bi-jaa-nib"},
      {ar: "بين", nl: "tussen", ipa: "bayn"},
      {ar: "ميدان", nl: "plein", ipa: "may-daan"},
      {ar: "جسر", nl: "brug", ipa: "jisr"},
    ],
    phrases: [
      {ar: "أين المتحف؟", nl: "Waar is het museum?", ipa: "ay-na al-mut-haf"},
      {ar: "هل هو قريب من هنا؟", nl: "Is het dichtbij vanaf hier?", ipa: "hal hu-wa qa-riib min hu-naa"},
      {ar: "اذهب مستقيم ثم يمين", nl: "Ga rechtdoor en dan rechts", ipa: "idh-hab mus-ta-qiim thum-ma ya-miin"},
      {ar: "المطعم بجانب الفندق", nl: "Het restaurant is naast het hotel", ipa: "al-mat-am bi-jaa-nib al-fun-duq"},
      {ar: "المتحف أمام المسجد", nl: "Het museum is voor de moskee", ipa: "al-mut-haf a-maam al-mas-jid"},
      {ar: "هل يمكنك أن تريني على الخريطة؟", nl: "Kunt u het op de kaart laten zien?", ipa: "hal yum-ki-nuk an tu-rii-ni ala al-kha-rii-ta"},
    ],
    grammar: "Voorzetsels zoals أمام, خلف en بجانب helpen je locaties begrijpen. Combineer ze met bekende gebouwen zoals hotel, moskee of museum. Als je de uitleg niet begrijpt, vraag of iemand het op de kaart aanwijst.",
    practice: [
      "1. Vraag waar het museum is.",
      "2. Beschrijf een restaurant naast een hotel.",
      "3. Zeg “rechtdoor en dan rechts”.",
      "4. Vraag of iets dichtbij is.",
      "5. Oefen een route van hotel naar markt.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Tijd en dagen",
    titleNative: "الوقت والأيام",
    focus: "Vandaag leer je praten over openingstijden en dagen. Dit is nuttig voor musea, restaurants en tours.",
    vocab: [
      {ar: "وقت", nl: "tijd", ipa: "waqt"},
      {ar: "ساعة", nl: "uur / klok", ipa: "saa-a"},
      {ar: "اليوم", nl: "vandaag", ipa: "al-yawm"},
      {ar: "غدا", nl: "morgen", ipa: "gha-dan"},
      {ar: "أمس", nl: "gisteren", ipa: "ams"},
      {ar: "صباحا", nl: "’s ochtends", ipa: "sa-baa-han"},
      {ar: "مساء", nl: "’s avonds", ipa: "ma-saa-an"},
      {ar: "مفتوح", nl: "open", ipa: "maf-tuuh"},
      {ar: "مغلق", nl: "gesloten", ipa: "mugh-laq"},
      {ar: "متأخر", nl: "laat / vertraagd", ipa: "mu-ta-akh-khir"},
    ],
    phrases: [
      {ar: "كم الساعة؟", nl: "Hoe laat is het?", ipa: "kam as-saa-a"},
      {ar: "متى يفتح المتحف؟", nl: "Wanneer opent het museum?", ipa: "ma-taa yaf-tah al-mut-haf"},
      {ar: "هل المطعم مفتوح اليوم؟", nl: "Is het restaurant vandaag open?", ipa: "hal al-mat-am maf-tuuh al-yawm"},
      {ar: "إنه مغلق غدا", nl: "Het is morgen gesloten", ipa: "in-na-hu mugh-laq gha-dan"},
      {ar: "في الساعة الثامنة مساء", nl: "Om acht uur ’s avonds", ipa: "fii as-saa-a ath-thaa-mi-na ma-saa-an"},
      {ar: "أنا متأخر", nl: "Ik ben laat", ipa: "a-naa mu-ta-akh-khir"},
    ],
    grammar: "في الساعة betekent “om … uur”. Voor reizigers is het genoeg om het uur te herkennen en صباحا of مساء te gebruiken. Let op: tijden kunnen in spreektaal lokaal anders worden uitgesproken.",
    practice: [
      "1. Vraag hoe laat het is.",
      "2. Vraag wanneer het museum opent.",
      "3. Zeg dat een restaurant vandaag open is.",
      "4. Zeg “om acht uur ’s avonds”.",
      "5. Maak drie vragen over openingstijden.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Reserveringen en afspraken",
    titleNative: "الحجوزات والمواعيد",
    focus: "Vandaag oefen je reserveren voor een restaurant, tour of afspraak. Je leert datum, aantal personen en tijd noemen.",
    vocab: [
      {ar: "حجز", nl: "reservering", ipa: "hajz"},
      {ar: "موعد", nl: "afspraak", ipa: "maw-id"},
      {ar: "اليوم", nl: "vandaag", ipa: "al-yawm"},
      {ar: "غدا", nl: "morgen", ipa: "gha-dan"},
      {ar: "مساء", nl: "avond", ipa: "ma-saa"},
      {ar: "شخص", nl: "persoon", ipa: "shakh-s"},
      {ar: "شخصان", nl: "twee personen", ipa: "shakh-saan"},
      {ar: "مجموعة", nl: "groep", ipa: "maj-muu-a"},
      {ar: "متاح", nl: "beschikbaar", ipa: "mu-taah"},
      {ar: "ممتاز", nl: "uitstekend", ipa: "mum-taaz"},
    ],
    phrases: [
      {ar: "أريد حجزا لشخصين", nl: "Ik wil een reservering voor twee personen", ipa: "u-riid haj-zan li-shakh-sayn"},
      {ar: "هل عندكم طاولة الليلة؟", nl: "Heeft u vanavond een tafel?", ipa: "hal in-da-kum taa-wi-la al-lay-la"},
      {ar: "في الساعة السابعة مساء", nl: "Om zeven uur ’s avonds", ipa: "fii as-saa-a as-saa-bi-a ma-saa-an"},
      {ar: "هل هذا متاح؟", nl: "Is dit beschikbaar?", ipa: "hal haa-dhaa mu-taah"},
      {ar: "أريد تغيير الموعد", nl: "Ik wil de afspraak wijzigen", ipa: "u-riid tagh-yiir al-maw-id"},
      {ar: "ممتاز، شكرا", nl: "Uitstekend, bedankt", ipa: "mum-taaz, shuk-ran"},
    ],
    grammar: "لشخصين betekent “voor twee personen”. Het stukje لـ betekent vaak “voor”. Je ziet dit ook in restaurantzinnen, tickets en reserveringen.",
    practice: [
      "1. Reserveer een tafel voor twee.",
      "2. Vraag of vanavond beschikbaar is.",
      "3. Zeg een tijd in de avond.",
      "4. Vraag om een afspraak te wijzigen.",
      "5. Oefen een telefoongesprek voor een reservering.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Geld en betalen",
    titleNative: "المال والدفع",
    focus: "Vandaag leer je betalen met contant geld of kaart. Dit helpt in cafés, taxi’s, winkels en markten.",
    vocab: [
      {ar: "مال", nl: "geld", ipa: "maal"},
      {ar: "نقدا", nl: "contant", ipa: "naq-dan"},
      {ar: "بطاقة", nl: "kaart", ipa: "bi-taa-qa"},
      {ar: "فاتورة", nl: "factuur / rekening", ipa: "faa-tuu-ra"},
      {ar: "إيصال", nl: "bon", ipa: "ii-saal"},
      {ar: "باقي", nl: "wisselgeld", ipa: "baa-qii"},
      {ar: "دفع", nl: "betaling", ipa: "daf"},
      {ar: "غالي", nl: "duur", ipa: "ghaa-lii"},
      {ar: "رخيص", nl: "goedkoop", ipa: "ra-khiis"},
      {ar: "سعر", nl: "prijs", ipa: "si-r"},
    ],
    phrases: [
      {ar: "هل أستطيع الدفع بالبطاقة؟", nl: "Kan ik met kaart betalen?", ipa: "hal as-ta-tii ad-daf bil-bi-taa-qa"},
      {ar: "سأدفع نقدا", nl: "Ik betaal contant", ipa: "sa-ad-fa naq-dan"},
      {ar: "أريد الإيصال من فضلك", nl: "Ik wil de bon, alstublieft", ipa: "u-riid al-ii-saal min fad-lik"},
      {ar: "هل السعر صحيح؟", nl: "Is de prijs correct?", ipa: "hal as-si-r sa-hiih"},
      {ar: "أين الباقي؟", nl: "Waar is het wisselgeld?", ipa: "ay-na al-baa-qii"},
      {ar: "هذا رخيص", nl: "Dit is goedkoop", ipa: "haa-dhaa ra-khiis"},
    ],
    grammar: "بالـ betekent vaak “met de”, zoals بالبطاقة: met de kaart. Voor betalen is dit patroon heel handig. Je kunt ook zeggen نقدا voor contant zonder extra werkwoord.",
    practice: [
      "1. Vraag of je met kaart kunt betalen.",
      "2. Zeg dat je contant betaalt.",
      "3. Vraag om een bon.",
      "4. Vraag of de prijs klopt.",
      "5. Oefen een betalingsscène in een winkel.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Telefoon en internet",
    titleNative: "الهاتف والإنترنت",
    focus: "Vandaag leer je woorden voor simkaarten, data en wifi. Dit is handig wanneer je aankomt en verbinding nodig hebt.",
    vocab: [
      {ar: "هاتف", nl: "telefoon", ipa: "haa-tif"},
      {ar: "إنترنت", nl: "internet", ipa: "in-ter-net"},
      {ar: "شريحة", nl: "simkaart", ipa: "sha-rii-ha"},
      {ar: "بيانات", nl: "data", ipa: "ba-yaa-naat"},
      {ar: "رصيد", nl: "tegoed", ipa: "ra-siid"},
      {ar: "كلمة سر", nl: "wachtwoord", ipa: "ka-li-mat sirr"},
      {ar: "شبكة", nl: "netwerk", ipa: "sha-ba-ka"},
      {ar: "بطيء", nl: "langzaam", ipa: "ba-tii"},
      {ar: "سريع", nl: "snel", ipa: "sa-rii"},
      {ar: "اتصال", nl: "verbinding", ipa: "it-ti-saal"},
    ],
    phrases: [
      {ar: "أريد شريحة إنترنت", nl: "Ik wil een internetsimkaart", ipa: "u-riid sha-rii-hat in-ter-net"},
      {ar: "كم سعر البيانات؟", nl: "Hoeveel kost data?", ipa: "kam si-r al-ba-yaa-naat"},
      {ar: "ما كلمة السر؟", nl: "Wat is het wachtwoord?", ipa: "maa ka-li-mat as-sirr"},
      {ar: "الإنترنت بطيء", nl: "Het internet is langzaam", ipa: "al-in-ter-net ba-tii"},
      {ar: "لا يوجد اتصال", nl: "Er is geen verbinding", ipa: "laa yuu-jad it-ti-saal"},
      {ar: "هل عندكم واي فاي؟", nl: "Hebben jullie wifi?", ipa: "hal in-da-kum wai-fai"},
    ],
    grammar: "كلمة سر betekent letterlijk “woord van geheim”, dus wachtwoord. In hotels, cafés en winkels kun je vragen: ما كلمة السر؟ Dit is kort en natuurlijk.",
    practice: [
      "1. Vraag om een internetsimkaart.",
      "2. Vraag naar de prijs van data.",
      "3. Vraag naar het wifiwachtwoord.",
      "4. Zeg dat er geen verbinding is.",
      "5. Maak een gesprek in een telefoonwinkel.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Gezondheid en apotheek",
    titleNative: "الصحة والصيدلية",
    focus: "Vandaag leer je basiszinnen voor een apotheek of kleine medische klacht. Dit is belangrijk op reis in elk land.",
    vocab: [
      {ar: "صيدلية", nl: "apotheek", ipa: "say-da-li-ya"},
      {ar: "دواء", nl: "medicijn", ipa: "da-waa"},
      {ar: "طبيب", nl: "dokter", ipa: "ta-biib"},
      {ar: "ألم", nl: "pijn", ipa: "a-lam"},
      {ar: "رأس", nl: "hoofd", ipa: "raas"},
      {ar: "معدة", nl: "maag", ipa: "mi-da"},
      {ar: "حمى", nl: "koorts", ipa: "hum-maa"},
      {ar: "برد", nl: "verkoudheid", ipa: "bard"},
      {ar: "ضمادة", nl: "verband", ipa: "di-maa-da"},
      {ar: "وصفة", nl: "recept", ipa: "was-fa"},
    ],
    phrases: [
      {ar: "أين الصيدلية؟", nl: "Waar is de apotheek?", ipa: "ay-na as-say-da-li-ya"},
      {ar: "لدي ألم في الرأس", nl: "Ik heb hoofdpijn", ipa: "la-day-ya a-lam fii ar-raas"},
      {ar: "لدي ألم في المعدة", nl: "Ik heb maagpijn", ipa: "la-day-ya a-lam fii al-mi-da"},
      {ar: "هل أحتاج وصفة؟", nl: "Heb ik een recept nodig?", ipa: "hal ah-taa-j was-fa"},
      {ar: "أريد دواء للبرد", nl: "Ik wil medicijn tegen verkoudheid", ipa: "u-riid da-waa lil-bard"},
      {ar: "هل يوجد طبيب قريب؟", nl: "Is er een dokter dichtbij?", ipa: "hal yuu-jad ta-biib qa-riib"},
    ],
    grammar: "لدي ألم في betekent “ik heb pijn in”. Daarna noem je het lichaamsdeel. Deze structuur is eenvoudig en duidelijk bij apotheek of arts.",
    practice: [
      "1. Vraag waar de apotheek is.",
      "2. Zeg dat je hoofdpijn hebt.",
      "3. Vraag of je een recept nodig hebt.",
      "4. Vraag naar een dokter dichtbij.",
      "5. Oefen een apotheekgesprek met drie klachten.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Noodsituaties",
    titleNative: "حالات الطوارئ",
    focus: "Vandaag leer je zinnen voor noodsituaties, verlies en veiligheid. Hopelijk heb je ze niet nodig, maar ze zijn belangrijk.",
    vocab: [
      {ar: "طوارئ", nl: "noodgeval", ipa: "ta-waari"},
      {ar: "شرطة", nl: "politie", ipa: "shur-ta"},
      {ar: "إسعاف", nl: "ambulance", ipa: "is-aaf"},
      {ar: "مستشفى", nl: "ziekenhuis", ipa: "mus-tash-faa"},
      {ar: "مساعدة", nl: "hulp", ipa: "mu-saa-a-da"},
      {ar: "ضائع", nl: "kwijt / verdwaald", ipa: "daa-i"},
      {ar: "سرقة", nl: "diefstal", ipa: "sa-ri-qa"},
      {ar: "خطر", nl: "gevaar", ipa: "kha-tar"},
      {ar: "جواز سفر", nl: "paspoort", ipa: "ja-waaz sa-far"},
      {ar: "اتصل", nl: "bel", ipa: "it-ta-sil"},
    ],
    phrases: [
      {ar: "أحتاج مساعدة الآن", nl: "Ik heb nu hulp nodig", ipa: "ah-taa-j mu-saa-a-da al-aan"},
      {ar: "اتصل بالشرطة من فضلك", nl: "Bel de politie, alstublieft", ipa: "it-ta-sil bish-shur-ta min fad-lik"},
      {ar: "أين المستشفى؟", nl: "Waar is het ziekenhuis?", ipa: "ay-na al-mus-tash-faa"},
      {ar: "فقدت جواز سفري", nl: "Ik ben mijn paspoort kwijt", ipa: "fa-qad-tu ja-waaz sa-fa-rii"},
      {ar: "هناك مشكلة خطيرة", nl: "Er is een ernstig probleem", ipa: "hu-naak mush-ki-la kha-tii-ra"},
      {ar: "أنا ضائع", nl: "Ik ben verdwaald", ipa: "a-naa daa-i"},
    ],
    grammar: "In noodsituaties zijn korte zinnen beter dan perfecte zinnen. أحتاج مساعدة الآن is duidelijk en dringend. Gebruik الآن om aan te geven dat het direct nodig is.",
    practice: [
      "1. Zeg dat je nu hulp nodig hebt.",
      "2. Vraag iemand de politie te bellen.",
      "3. Zeg dat je je paspoort kwijt bent.",
      "4. Vraag waar het ziekenhuis is.",
      "5. Oefen langzaam spreken in een noodsituatie.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Bezienswaardigheden",
    titleNative: "المعالم السياحية",
    focus: "Vandaag leer je praten over musea, moskeeën, stranden en historische plekken. Handig voor sightseeing in Fez, Jeruzalem, Cairo of Petra.",
    vocab: [
      {ar: "متحف", nl: "museum", ipa: "mut-haf"},
      {ar: "مسجد", nl: "moskee", ipa: "mas-jid"},
      {ar: "قلعة", nl: "kasteel / fort", ipa: "qal-a"},
      {ar: "شاطئ", nl: "strand", ipa: "shaa-ti"},
      {ar: "حديقة", nl: "park / tuin", ipa: "ha-dii-qa"},
      {ar: "آثار", nl: "ruïnes / oudheden", ipa: "aa-thaar"},
      {ar: "تذكرة", nl: "ticket", ipa: "tadh-ki-ra"},
      {ar: "دليل", nl: "gids", ipa: "da-liil"},
      {ar: "صورة", nl: "foto", ipa: "suu-ra"},
      {ar: "جميل", nl: "mooi", ipa: "ja-miil"},
    ],
    phrases: [
      {ar: "أين المتحف الوطني؟", nl: "Waar is het nationaal museum?", ipa: "ay-na al-mut-haf al-wa-ta-nii"},
      {ar: "هل التصوير مسموح؟", nl: "Is fotograferen toegestaan?", ipa: "hal at-tas-wiir mas-muuh"},
      {ar: "أريد تذكرة واحدة", nl: "Ik wil één ticket", ipa: "u-riid tadh-ki-ra waa-hi-da"},
      {ar: "هل يوجد دليل؟", nl: "Is er een gids?", ipa: "hal yuu-jad da-liil"},
      {ar: "هذا المكان جميل جدا", nl: "Deze plek is heel mooi", ipa: "haa-dhaa al-ma-kaan ja-miil jid-dan"},
      {ar: "متى يغلق؟", nl: "Wanneer sluit het?", ipa: "ma-taa yugh-liq"},
    ],
    grammar: "مسموح betekent “toegestaan”. Je kunt vragen هل التصوير مسموح؟ voordat je foto’s maakt, vooral in religieuze of officiële gebouwen. Dit is beleefd en voorkomt problemen.",
    practice: [
      "1. Vraag of fotograferen toegestaan is.",
      "2. Koop één ticket.",
      "3. Vraag of er een gids is.",
      "4. Zeg dat een plek heel mooi is.",
      "5. Maak een sightseeinggesprek bij een museum.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Strand, weer en natuur",
    titleNative: "الشاطئ والطقس والطبيعة",
    focus: "Vandaag leer je praten over het weer en buitenactiviteiten. Dit is handig aan de Rode Zee, in Oman of aan de Marokkaanse kust.",
    vocab: [
      {ar: "طقس", nl: "weer", ipa: "taqs"},
      {ar: "حار", nl: "warm / heet", ipa: "haar"},
      {ar: "بارد", nl: "koud", ipa: "baa-rid"},
      {ar: "مشمس", nl: "zonnig", ipa: "mush-mis"},
      {ar: "مطر", nl: "regen", ipa: "ma-tar"},
      {ar: "ريح", nl: "wind", ipa: "riih"},
      {ar: "شاطئ", nl: "strand", ipa: "shaa-ti"},
      {ar: "بحر", nl: "zee", ipa: "bahr"},
      {ar: "جبل", nl: "berg", ipa: "ja-bal"},
      {ar: "صحراء", nl: "woestijn", ipa: "sah-raa"},
    ],
    phrases: [
      {ar: "الطقس حار اليوم", nl: "Het weer is warm vandaag", ipa: "at-taqs haar al-yawm"},
      {ar: "هل سيكون هناك مطر؟", nl: "Komt er regen?", ipa: "hal sa-ya-kuun hu-naak ma-tar"},
      {ar: "أريد الذهاب إلى الشاطئ", nl: "Ik wil naar het strand gaan", ipa: "u-riid adh-dha-haab i-laa ash-shaa-ti"},
      {ar: "البحر جميل", nl: "De zee is mooi", ipa: "al-bahr ja-miil"},
      {ar: "هل الطريق إلى الجبل آمن؟", nl: "Is de weg naar de berg veilig?", ipa: "hal at-ta-riiq i-laa al-ja-bal aa-min"},
      {ar: "أحب الصحراء", nl: "Ik hou van de woestijn", ipa: "u-hibb as-sah-raa"},
    ],
    grammar: "أحب betekent “ik hou van” of “ik vind leuk”. Je kunt het gebruiken voor plekken, eten en activiteiten. Bijvoorbeeld: أحب البحر, أحب القهوة, أحب هذا المكان.",
    practice: [
      "1. Beschrijf het weer vandaag.",
      "2. Zeg dat je naar het strand wilt.",
      "3. Vraag of er regen komt.",
      "4. Zeg dat je de zee mooi vindt.",
      "5. Maak drie zinnen met أحب.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Sociale gesprekken",
    titleNative: "الأحاديث الاجتماعية",
    focus: "Vandaag leer je eenvoudige smalltalk met locals. Je oefent vriendelijk praten over land, stad, eten en reizen.",
    vocab: [
      {ar: "بلد", nl: "land", ipa: "ba-lad"},
      {ar: "مدينة", nl: "stad", ipa: "ma-dii-na"},
      {ar: "جميل", nl: "mooi", ipa: "ja-miil"},
      {ar: "لطيف", nl: "aardig", ipa: "la-tiif"},
      {ar: "سفر", nl: "reizen", ipa: "sa-far"},
      {ar: "طعام", nl: "eten", ipa: "ta-aam"},
      {ar: "ثقافة", nl: "cultuur", ipa: "tha-qaa-fa"},
      {ar: "لغة", nl: "taal", ipa: "lu-gha"},
      {ar: "صعب", nl: "moeilijk", ipa: "sa-b"},
      {ar: "سهل", nl: "makkelijk", ipa: "sahl"},
    ],
    phrases: [
      {ar: "مدينتكم جميلة", nl: "Jullie stad is mooi", ipa: "ma-dii-na-tu-kum ja-mii-la"},
      {ar: "أنا أحب الطعام هنا", nl: "Ik hou van het eten hier", ipa: "a-naa u-hibb at-ta-aam hu-naa"},
      {ar: "العربية صعبة قليلا", nl: "Arabisch is een beetje moeilijk", ipa: "al-a-ra-bi-ya sa-ba qa-lii-lan"},
      {ar: "لكنها جميلة", nl: "Maar het is mooi", ipa: "laa-kin-na-haa ja-mii-la"},
      {ar: "هل زرت هولندا؟", nl: "Ben je in Nederland geweest?", ipa: "hal zur-ta ho-lan-da"},
      {ar: "أنا سعيد هنا", nl: "Ik ben hier blij", ipa: "a-naa sa-iid hu-naa"},
    ],
    grammar: "قليلا betekent “een beetje” en verzacht je zin. العربية صعبة قليلا klinkt vriendelijker dan alleen “Arabisch is moeilijk”. Gebruik het om eerlijk maar beleefd te blijven.",
    practice: [
      "1. Zeg dat de stad mooi is.",
      "2. Vertel dat je het eten hier lekker vindt.",
      "3. Zeg dat Arabisch een beetje moeilijk is.",
      "4. Vraag of iemand Nederland heeft bezocht.",
      "5. Oefen een klein praatje van acht regels.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Uitnodigingen en plannen",
    titleNative: "الدعوات والخطط",
    focus: "Vandaag leer je plannen maken met iemand die je ontmoet. Je oefent koffie drinken, wandelen en tijden afspreken.",
    vocab: [
      {ar: "خطة", nl: "plan", ipa: "khit-ta"},
      {ar: "دعوة", nl: "uitnodiging", ipa: "da-wa"},
      {ar: "قهوة", nl: "koffie", ipa: "qah-wa"},
      {ar: "مطعم", nl: "restaurant", ipa: "mat-am"},
      {ar: "اليوم", nl: "vandaag", ipa: "al-yawm"},
      {ar: "غدا", nl: "morgen", ipa: "gha-dan"},
      {ar: "معا", nl: "samen", ipa: "ma-an"},
      {ar: "وقت", nl: "tijd", ipa: "waqt"},
      {ar: "مناسب", nl: "geschikt", ipa: "mu-naa-sib"},
      {ar: "فكرة", nl: "idee", ipa: "fik-ra"},
    ],
    phrases: [
      {ar: "هل تريد قهوة؟", nl: "Wil je koffie?", ipa: "hal tu-riid qah-wa"},
      {ar: "هل عندك وقت غدا؟", nl: "Heb je morgen tijd?", ipa: "hal in-da-ka waqt gha-dan"},
      {ar: "هذا وقت مناسب", nl: "Dit is een geschikt moment", ipa: "haa-dhaa waqt mu-naa-sib"},
      {ar: "فكرة جيدة", nl: "Goed idee", ipa: "fik-ra jay-yi-da"},
      {ar: "نلتقي في المطعم", nl: "We ontmoeten elkaar in het restaurant", ipa: "nal-ta-qii fii al-mat-am"},
      {ar: "إلى اللقاء غدا", nl: "Tot morgen", ipa: "i-laa al-li-qaa gha-dan"},
    ],
    grammar: "هل تريد betekent “wil je?” en is nuttig voor uitnodigingen. Voor “we ontmoeten elkaar” gebruik je نلتقي. Houd plannen simpel: tijd, plaats en bevestiging.",
    practice: [
      "1. Vraag iemand of hij koffie wil.",
      "2. Vraag of iemand morgen tijd heeft.",
      "3. Zeg dat iets een goed idee is.",
      "4. Spreek af bij een restaurant.",
      "5. Maak een kort gesprek om plannen te maken.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Meningen en voorkeuren",
    titleNative: "الآراء والتفضيلات",
    focus: "Vandaag leer je zeggen wat je leuk vindt, niet leuk vindt en liever wilt. Dit helpt bij eten, activiteiten en reizen.",
    vocab: [
      {ar: "أحب", nl: "ik hou van", ipa: "u-hibb"},
      {ar: "لا أحب", nl: "ik hou niet van", ipa: "laa u-hibb"},
      {ar: "أفضل", nl: "ik heb liever", ipa: "u-fad-dil"},
      {ar: "جميل", nl: "mooi", ipa: "ja-miil"},
      {ar: "ممتع", nl: "leuk / interessant", ipa: "mum-ti"},
      {ar: "ممل", nl: "saai", ipa: "mu-mill"},
      {ar: "هادئ", nl: "rustig", ipa: "haa-di"},
      {ar: "مزدحم", nl: "druk", ipa: "muz-da-him"},
      {ar: "سهل", nl: "makkelijk", ipa: "sahl"},
      {ar: "صعب", nl: "moeilijk", ipa: "sa-b"},
    ],
    phrases: [
      {ar: "أحب هذا المكان", nl: "Ik hou van deze plek", ipa: "u-hibb haa-dhaa al-ma-kaan"},
      {ar: "لا أحب الأماكن المزدحمة", nl: "Ik hou niet van drukke plekken", ipa: "laa u-hibb al-a-maa-kin al-muz-da-hi-ma"},
      {ar: "أفضل القهوة", nl: "Ik heb liever koffie", ipa: "u-fad-dil al-qah-wa"},
      {ar: "هذا المطعم هادئ", nl: "Dit restaurant is rustig", ipa: "haa-dhaa al-mat-am haa-di"},
      {ar: "الرحلة ممتعة", nl: "De reis is leuk", ipa: "ar-rih-la mum-ti-a"},
      {ar: "هذا صعب قليلا", nl: "Dit is een beetje moeilijk", ipa: "haa-dhaa sa-b qa-lii-lan"},
    ],
    grammar: "أفضل betekent “ik geef de voorkeur aan” of “ik heb liever”. Het klinkt iets beleefder en preciezer dan أريد. Gebruik het wanneer je tussen twee opties kiest.",
    practice: [
      "1. Zeg dat je deze plek mooi vindt.",
      "2. Zeg dat je niet van drukke plekken houdt.",
      "3. Zeg dat je liever koffie hebt.",
      "4. Beschrijf een restaurant als rustig.",
      "5. Maak vijf zinnen over je voorkeuren.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Dagelijkse routines op reis",
    titleNative: "الروتين اليومي أثناء السفر",
    focus: "Vandaag leer je praten over simpele dagelijkse activiteiten tijdens je reis. Je kunt uitleggen wat je vandaag gaat doen.",
    vocab: [
      {ar: "أستيقظ", nl: "ik word wakker", ipa: "as-tay-qiz"},
      {ar: "آكل", nl: "ik eet", ipa: "aa-kul"},
      {ar: "أشرب", nl: "ik drink", ipa: "ash-rab"},
      {ar: "أذهب", nl: "ik ga", ipa: "adh-hab"},
      {ar: "أزور", nl: "ik bezoek", ipa: "a-zuur"},
      {ar: "أشتري", nl: "ik koop", ipa: "ash-ta-rii"},
      {ar: "أمشي", nl: "ik loop", ipa: "am-shii"},
      {ar: "أعود", nl: "ik keer terug", ipa: "a-uud"},
      {ar: "أنام", nl: "ik slaap", ipa: "a-naam"},
      {ar: "اليوم", nl: "vandaag", ipa: "al-yawm"},
    ],
    phrases: [
      {ar: "اليوم أزور المتحف", nl: "Vandaag bezoek ik het museum", ipa: "al-yawm a-zuur al-mut-haf"},
      {ar: "أشرب القهوة صباحا", nl: "Ik drink koffie in de ochtend", ipa: "ash-rab al-qah-wa sa-baa-han"},
      {ar: "أذهب إلى السوق", nl: "Ik ga naar de markt", ipa: "adh-hab i-laa as-suuq"},
      {ar: "أمشي في المدينة", nl: "Ik loop door de stad", ipa: "am-shii fii al-ma-dii-na"},
      {ar: "أعود إلى الفندق مساء", nl: "Ik keer ’s avonds terug naar het hotel", ipa: "a-uud i-laa al-fun-duq ma-saa-an"},
      {ar: "أنام مبكرا", nl: "Ik slaap vroeg", ipa: "a-naam mu-bak-ki-ran"},
    ],
    grammar: "Veel dagelijkse werkwoorden beginnen in de ik-vorm met أ. Bijvoorbeeld أذهب, أشرب, أزور. Dit patroon helpt je snel herkenbare zinnen te maken over je dag.",
    practice: [
      "1. Vertel wat je vandaag bezoekt.",
      "2. Zeg dat je ’s ochtends koffie drinkt.",
      "3. Zeg dat je naar de markt gaat.",
      "4. Beschrijf je avond in één zin.",
      "5. Maak een reisdagplanning van vijf zinnen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Problemen oplossen",
    titleNative: "حل المشاكل",
    focus: "Vandaag combineer je eerdere taal om praktische problemen op te lossen. Denk aan gemiste afspraken, verkeerde bestellingen of verloren spullen.",
    vocab: [
      {ar: "خطأ", nl: "fout", ipa: "kha-ta"},
      {ar: "صحيح", nl: "correct", ipa: "sa-hiih"},
      {ar: "مفقود", nl: "verloren", ipa: "maf-quud"},
      {ar: "متأخر", nl: "laat / vertraagd", ipa: "mu-ta-akh-khir"},
      {ar: "مختلف", nl: "anders", ipa: "mukh-ta-lif"},
      {ar: "نفس", nl: "hetzelfde", ipa: "nafs"},
      {ar: "أفهم", nl: "ik begrijp", ipa: "af-ham"},
      {ar: "لا أفهم", nl: "ik begrijp niet", ipa: "laa af-ham"},
      {ar: "أشرح", nl: "ik leg uit", ipa: "ash-rah"},
      {ar: "حل", nl: "oplossing", ipa: "hall"},
    ],
    phrases: [
      {ar: "هذا ليس صحيحا", nl: "Dit is niet correct", ipa: "haa-dhaa lay-sa sa-hii-han"},
      {ar: "أعتقد أن هناك خطأ", nl: "Ik denk dat er een fout is", ipa: "a-ta-qid an-na hu-naak kha-ta"},
      {ar: "لا أفهم المشكلة", nl: "Ik begrijp het probleem niet", ipa: "laa af-ham al-mush-ki-la"},
      {ar: "هل يمكنك أن تشرح؟", nl: "Kunt u het uitleggen?", ipa: "hal yum-ki-nuk an tash-rah"},
      {ar: "أريد حلا من فضلك", nl: "Ik wil een oplossing, alstublieft", ipa: "u-riid hal-lan min fad-lik"},
      {ar: "هذا ليس طلبي", nl: "Dit is niet mijn bestelling", ipa: "haa-dhaa lay-sa ta-la-bii"},
    ],
    grammar: "ليس betekent “is niet” en wordt gebruikt om dingen te ontkennen: هذا ليس صحيحا. Het is nuttig bij fouten, rekeningen en bestellingen. Blijf beleefd met من فضلك, zelfs als er iets misgaat.",
    practice: [
      "1. Zeg dat iets niet correct is.",
      "2. Zeg dat je denkt dat er een fout is.",
      "3. Vraag iemand het uit te leggen.",
      "4. Zeg dat dit niet je bestelling is.",
      "5. Oefen een probleemgesprek bij een restaurant of hotel.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Alles combineren voor je reis",
    titleNative: "مراجعة السفر الكاملة",
    focus: "Vandaag combineer je begroeten, vragen stellen, bestellen, betalen en hulp vragen. Je oefent alsof je een dag in een Arabischsprekende stad doorbrengt.",
    vocab: [
      {ar: "رحلة", nl: "reis", ipa: "rih-la"},
      {ar: "مدينة", nl: "stad", ipa: "ma-dii-na"},
      {ar: "فندق", nl: "hotel", ipa: "fun-duq"},
      {ar: "مطعم", nl: "restaurant", ipa: "mat-am"},
      {ar: "سوق", nl: "markt", ipa: "suuq"},
      {ar: "محطة", nl: "station", ipa: "ma-hat-ta"},
      {ar: "مساعدة", nl: "hulp", ipa: "mu-saa-a-da"},
      {ar: "تذكرة", nl: "ticket", ipa: "tadh-ki-ra"},
      {ar: "حساب", nl: "rekening", ipa: "hi-saab"},
      {ar: "شكرا", nl: "bedankt", ipa: "shuk-ran"},
    ],
    phrases: [
      {ar: "مرحبا، أحتاج مساعدة", nl: "Hallo, ik heb hulp nodig", ipa: "mar-ha-ban, ah-taa-j mu-saa-a-da"},
      {ar: "أين أقرب محطة؟", nl: "Waar is het dichtstbijzijnde station?", ipa: "ay-na aq-rab ma-hat-ta"},
      {ar: "أريد تذكرة إلى السوق", nl: "Ik wil een ticket naar de markt", ipa: "u-riid tadh-ki-ra i-laa as-suuq"},
      {ar: "أريد هذا الطبق من فضلك", nl: "Ik wil dit gerecht, alstublieft", ipa: "u-riid haa-dhaa at-ta-baq min fad-lik"},
      {ar: "هل أستطيع الدفع بالبطاقة؟", nl: "Kan ik met kaart betalen?", ipa: "hal as-ta-tii ad-daf bil-bi-taa-qa"},
      {ar: "شكرا، إلى اللقاء", nl: "Bedankt, tot ziens", ipa: "shuk-ran, i-laa al-li-qaa"},
    ],
    grammar: "Je hoeft op reis niet perfecte zinnen te maken. Combineer kernwoorden met beleefde vormen: مرحبا, من فضلك, شكرا. Met أين, أريد, هل en أحتاج kun je al veel echte situaties oplossen.",
    practice: [
      "1. Speel een hele ochtend na: hotel, station, café.",
      "2. Maak vijf vragen met أين.",
      "3. Maak vijf verzoeken met أريد.",
      "4. Gebruik هل om drie ja/nee-vragen te maken.",
      "5. Sluit elk gesprek af met bedankt en tot ziens.",
    ],
    conversationIndex: 0,
    conversationCount: 8,
  },
];

var CONVERSATIONS_NL_AR = [
  {
    setting: "",
    lines: [
      {who: "them", ar: "مرحبا، ماذا تريد؟", nl: "Hallo, wat wilt u?"},
      {who: "you", ar: "مرحبا، أريد قهوة من فضلك", nl: "Hallo, ik wil koffie, alstublieft."},
      {who: "them", ar: "هل تريد قهوة عربية؟", nl: "Wilt u Arabische koffie?"},
      {who: "you", ar: "نعم، قهوة عربية من فضلك", nl: "Ja, Arabische koffie alstublieft."},
      {who: "them", ar: "هل تريد شيئا آخر؟", nl: "Wilt u nog iets anders?"},
      {who: "you", ar: "أريد ماء بدون غاز", nl: "Ik wil water zonder prik."},
      {who: "them", ar: "ممتاز، هل تجلس هنا؟", nl: "Prima, zit u hier?"},
      {who: "you", ar: "نعم، أجلس هنا", nl: "Ja, ik zit hier."},
      {who: "them", ar: "الحساب بعد الطلب", nl: "De rekening komt na de bestelling."},
      {who: "you", ar: "شكرا جزيلا", nl: "Heel erg bedankt."},
      {who: "them", ar: "عفوا", nl: "Graag gedaan."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "مساء الخير، أهلا وسهلا", nl: "Goedenavond, welkom."},
      {who: "you", ar: "مساء الخير، لدي حجز", nl: "Goedenavond, ik heb een reservering."},
      {who: "them", ar: "ما اسمك؟", nl: "Wat is uw naam?"},
      {who: "you", ar: "اسمي يان دي فريس", nl: "Mijn naam is Jan de Vries."},
      {who: "them", ar: "نعم، الغرفة رقم خمسة", nl: "Ja, kamer nummer vijf."},
      {who: "you", ar: "شكرا، أين المصعد؟", nl: "Dank u, waar is de lift?"},
      {who: "them", ar: "المصعد هناك على اليمين", nl: "De lift is daar rechts."},
      {who: "you", ar: "هل الإفطار مشمول؟", nl: "Is ontbijt inbegrepen?"},
      {who: "them", ar: "نعم، الإفطار من السابعة صباحا", nl: "Ja, ontbijt is vanaf zeven uur ’s ochtends."},
      {who: "you", ar: "ما كلمة سر الواي فاي؟", nl: "Wat is het wifiwachtwoord?"},
      {who: "them", ar: "كلمة السر على البطاقة", nl: "Het wachtwoord staat op de kaart."},
      {who: "you", ar: "شكرا، إلى اللقاء", nl: "Bedankt, tot ziens."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", ar: "لو سمحت، أين المتحف الوطني؟", nl: "Pardon, waar is het nationaal museum?"},
      {who: "them", ar: "المتحف قريب من هنا", nl: "Het museum is dichtbij vanaf hier."},
      {who: "you", ar: "هل أذهب مستقيم؟", nl: "Ga ik rechtdoor?"},
      {who: "them", ar: "نعم، اذهب مستقيم ثم يمين", nl: "Ja, ga rechtdoor en dan rechts."},
      {who: "you", ar: "هل هو بجانب المسجد؟", nl: "Is het naast de moskee?"},
      {who: "them", ar: "نعم، بجانب المسجد الكبير", nl: "Ja, naast de grote moskee."},
      {who: "you", ar: "هل يمكنك أن تريني على الخريطة؟", nl: "Kunt u het op de kaart laten zien?"},
      {who: "them", ar: "نعم، هنا المتحف", nl: "Ja, hier is het museum."},
      {who: "you", ar: "شكرا جزيلا", nl: "Heel erg bedankt."},
      {who: "them", ar: "عفوا، رحلة سعيدة", nl: "Graag gedaan, fijne reis."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "أهلا، كم شخصا؟", nl: "Welkom, hoeveel personen?"},
      {who: "you", ar: "شخصان من فضلك", nl: "Twee personen, alstublieft."},
      {who: "them", ar: "تفضل، هذه الطاولة", nl: "Alstublieft, deze tafel."},
      {who: "you", ar: "هل عندكم قائمة باللغة الإنجليزية؟", nl: "Heeft u een menu in het Engels?"},
      {who: "them", ar: "نعم، تفضل", nl: "Ja, alstublieft."},
      {who: "you", ar: "ماذا تنصح؟", nl: "Wat raadt u aan?"},
      {who: "them", ar: "أنصح بالدجاج مع الأرز", nl: "Ik raad kip met rijst aan."},
      {who: "you", ar: "هل هو حار؟", nl: "Is het pittig?"},
      {who: "them", ar: "لا، ليس حارا", nl: "Nee, het is niet pittig."},
      {who: "you", ar: "ممتاز، أريد هذا الطبق", nl: "Prima, ik wil dit gerecht."},
      {who: "them", ar: "وماذا تشرب؟", nl: "En wat drinkt u?"},
      {who: "you", ar: "ماء وشاي من فضلك", nl: "Water en thee, alstublieft."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "مرحبا، إلى أين؟", nl: "Hallo, waarheen?"},
      {who: "you", ar: "أريد تذكرة إلى المركز", nl: "Ik wil een ticket naar het centrum."},
      {who: "them", ar: "تذكرة واحدة؟", nl: "Eén ticket?"},
      {who: "you", ar: "نعم، تذكرة واحدة", nl: "Ja, één ticket."},
      {who: "them", ar: "خذ الخط الثاني", nl: "Neem lijn twee."},
      {who: "you", ar: "أين الخط الثاني؟", nl: "Waar is lijn twee?"},
      {who: "them", ar: "هناك، على اليسار", nl: "Daar, links."},
      {who: "you", ar: "متى يصل المترو؟", nl: "Wanneer komt de metro?"},
      {who: "them", ar: "بعد خمس دقائق", nl: "Over vijf minuten."},
      {who: "you", ar: "هل أستطيع الدفع بالبطاقة؟", nl: "Kan ik met kaart betalen?"},
      {who: "them", ar: "نعم، بالبطاقة أو نقدا", nl: "Ja, met kaart of contant."},
      {who: "you", ar: "شكرا", nl: "Bedankt."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "أهلا، تفضل", nl: "Hallo, kijkt u maar."},
      {who: "you", ar: "مرحبا، كم سعر هذا التمر؟", nl: "Hallo, hoeveel kosten deze dadels?"},
      {who: "them", ar: "الكيلو بعشرة", nl: "Een kilo kost tien."},
      {who: "you", ar: "هل التمر طازج؟", nl: "Zijn de dadels vers?"},
      {who: "them", ar: "نعم، طازج جدا", nl: "Ja, heel vers."},
      {who: "you", ar: "أريد كيلو واحدا", nl: "Ik wil één kilo."},
      {who: "them", ar: "ممتاز، هل تريد شيئا آخر؟", nl: "Prima, wilt u nog iets anders?"},
      {who: "you", ar: "هل ممكن بسعر أقل؟", nl: "Kan het voor een lagere prijs?"},
      {who: "them", ar: "ممكن بتسعة", nl: "Het kan voor negen."},
      {who: "you", ar: "جيد، أحتاج كيسا", nl: "Goed, ik heb een zak nodig."},
      {who: "them", ar: "تفضل", nl: "Alstublieft."},
      {who: "you", ar: "شكرا جزيلا", nl: "Heel erg bedankt."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "مرحبا، كيف أساعدك؟", nl: "Hallo, hoe kan ik u helpen?"},
      {who: "you", ar: "مرحبا، لدي ألم في الرأس", nl: "Hallo, ik heb hoofdpijn."},
      {who: "them", ar: "منذ متى؟", nl: "Sinds wanneer?"},
      {who: "you", ar: "منذ اليوم صباحا", nl: "Sinds vanochtend."},
      {who: "them", ar: "هل لديك حمى؟", nl: "Heeft u koorts?"},
      {who: "you", ar: "لا، لا توجد حمى", nl: "Nee, er is geen koorts."},
      {who: "them", ar: "هل تريد دواء بسيطا؟", nl: "Wilt u een eenvoudig medicijn?"},
      {who: "you", ar: "نعم، من فضلك", nl: "Ja, alstublieft."},
      {who: "them", ar: "خذ هذا مع الماء", nl: "Neem dit met water."},
      {who: "you", ar: "هل أحتاج وصفة؟", nl: "Heb ik een recept nodig?"},
      {who: "them", ar: "لا، لا تحتاج وصفة", nl: "Nee, u heeft geen recept nodig."},
      {who: "you", ar: "شكرا على المساعدة", nl: "Bedankt voor de hulp."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", ar: "مرحبا، هل أنت من هنا؟", nl: "Hallo, komt u hier vandaan?"},
      {who: "them", ar: "نعم، أنا من الدوحة", nl: "Ja, ik kom uit Doha."},
      {who: "you", ar: "مدينتكم جميلة جدا", nl: "Jullie stad is heel mooi."},
      {who: "them", ar: "شكرا، هل هذه زيارتك الأولى؟", nl: "Dank u, is dit uw eerste bezoek?"},
      {who: "you", ar: "نعم، أنا من هولندا", nl: "Ja, ik kom uit Nederland."},
      {who: "them", ar: "أهلا وسهلا بك", nl: "Van harte welkom."},
      {who: "you", ar: "أنا أحب الطعام هنا", nl: "Ik hou van het eten hier."},
      {who: "them", ar: "ما الطبق الذي أحببته؟", nl: "Welk gerecht vond u lekker?"},
      {who: "you", ar: "أحب الدجاج مع الأرز", nl: "Ik hou van kip met rijst."},
      {who: "them", ar: "هل تتعلم العربية؟", nl: "Leert u Arabisch?"},
      {who: "you", ar: "نعم، العربية صعبة قليلا لكنها جميلة", nl: "Ja, Arabisch is een beetje moeilijk, maar mooi."},
      {who: "them", ar: "ممتاز، تتكلم جيدا", nl: "Uitstekend, u spreekt goed."},
    ],
  },
];