var COURSE_NL_PT = [
{
  day: 1,
  title: "Eerste begroetingen in Portugal",
  titleNative: "Primeiros cumprimentos em Portugal",
  focus: "Je leert de basis om iemand vriendelijk te begroeten in Lissabon of Porto. De nadruk ligt op korte, beleefde zinnen die je meteen kunt gebruiken.",
  vocab: [{ pt: "olá", nl: "hallo", ipa: "/oˈla/" }, { pt: "bom dia", nl: "goedemorgen", ipa: "/bõ ˈdi.a/" }, { pt: "boa tarde", nl: "goedemiddag", ipa: "/ˈbo.a ˈtaɾ.dɨ/" }, { pt: "boa noite", nl: "goedenavond / goedenacht", ipa: "/ˈbo.a ˈnoj.tɨ/" }, { pt: "adeus", nl: "vaarwel / dag", ipa: "/aˈdewʃ/" }, { pt: "tchau", nl: "doei", ipa: "/ˈtʃaw/" }, { pt: "por favor", nl: "alstublieft", ipa: "/puɾ faˈvoɾ/" }, { pt: "obrigado", nl: "bedankt, gezegd door man", ipa: "/obɾiˈɡa.du/" }, { pt: "obrigada", nl: "bedankt, gezegd door vrouw", ipa: "/obɾiˈɡa.dɐ/" }, { pt: "sim", nl: "ja", ipa: "/sĩ/" }],
  phrases: [{ pt: "Olá, bom dia.", nl: "Hallo, goedemorgen.", ipa: "/oˈla bõ ˈdi.a/" }, { pt: "Boa tarde, tudo bem?", nl: "Goedemiddag, alles goed?", ipa: "/ˈbo.a ˈtaɾ.dɨ ˈtu.du bẽj/" }, { pt: "Muito obrigado.", nl: "Hartelijk bedankt, gezegd door man.", ipa: "/ˈmũj.tu obɾiˈɡa.du/" }, { pt: "Muito obrigada.", nl: "Hartelijk bedankt, gezegd door vrouw.", ipa: "/ˈmũj.tu obɾiˈɡa.dɐ/" }, { pt: "Até logo.", nl: "Tot straks / tot later.", ipa: "/aˈtɛ ˈlɔ.ɡu/" }, { pt: "Por favor.", nl: "Alstublieft.", ipa: "/puɾ faˈvoɾ/" }],
  grammar: "In het Portugees verandert “bedankt” mee met de spreker: een man zegt “obrigado”, een vrouw zegt “obrigada”. In Portugal hoor je vaak “bom dia” tot de lunch, “boa tarde” na de lunch en “boa noite” in de avond. Begroetingen zijn belangrijk in winkels, cafés en hotels; begin dus altijd met een korte groet.",
  practice: ["Groet iemand ’s ochtends en zeg daarna “bedankt”.", "Kies of je “obrigado” of “obrigada” zou gebruiken.", "Schrijf drie momenten waarop je “boa tarde” kunt zeggen.", "Oefen hardop: “Olá, bom dia. Por favor.”", "Maak een mini-dialoog van twee regels: hallo zeggen en afscheid nemen."]
},
{
  day: 2,
  title: "Jezelf voorstellen in Porto",
  titleNative: "Apresentar-se no Porto",
  focus: "Je leert hoe je je naam zegt en eenvoudig vraagt hoe iemand heet. Dit is handig bij een hotelbalie, rondleiding of ontmoeting met locals.",
  vocab: [{ pt: "nome", nl: "naam", ipa: "/ˈnɔ.mɨ/" }, { pt: "eu", nl: "ik", ipa: "/ew/" }, { pt: "sou", nl: "ik ben", ipa: "/sow/" }, { pt: "chamo-me", nl: "ik heet", ipa: "/ˈʃa.mu mɨ/" }, { pt: "você", nl: "u / jij", ipa: "/voˈse/" }, { pt: "prazer", nl: "aangenaam", ipa: "/pɾaˈzeɾ/" }, { pt: "senhor", nl: "meneer", ipa: "/sɨˈɲoɾ/" }, { pt: "senhora", nl: "mevrouw", ipa: "/sɨˈɲɔ.ɾɐ/" }, { pt: "amigo", nl: "vriend", ipa: "/ɐˈmi.ɡu/" }, { pt: "amiga", nl: "vriendin", ipa: "/ɐˈmi.ɡɐ/" }],
  phrases: [{ pt: "Chamo-me Anna.", nl: "Ik heet Anna.", ipa: "/ˈʃa.mu mɨ ˈa.nɐ/" }, { pt: "Eu sou de Amesterdão.", nl: "Ik kom uit Amsterdam.", ipa: "/ew sow dɨ ɐmʃtɨɾˈdɐ̃w/" }, { pt: "Qual é o seu nome?", nl: "Wat is uw naam?", ipa: "/kwal ɛ u sew ˈnɔ.mɨ/" }, { pt: "Muito prazer.", nl: "Aangenaam.", ipa: "/ˈmũj.tu pɾaˈzeɾ/" }, { pt: "Este é o meu amigo.", nl: "Dit is mijn vriend.", ipa: "/ˈeʃ.tɨ ɛ u mew ɐˈmi.ɡu/" }, { pt: "Esta é a minha amiga.", nl: "Dit is mijn vriendin.", ipa: "/ˈeʃ.tɐ ɛ ɐ ˈmi.ɲɐ ɐˈmi.ɡɐ/" }],
  grammar: "Voor “ik heet” kun je in Portugal vaak “chamo-me” gebruiken. Dat klinkt natuurlijker dan letterlijk “mijn naam is”, al bestaat “o meu nome é” ook. Let op “amigo” voor een mannelijke vriend en “amiga” voor een vrouwelijke vriendin.",
  practice: ["Stel jezelf voor met “Chamo-me...” en je eigen naam.", "Vraag beleefd naar iemands naam met “Qual é o seu nome?”", "Zeg dat je uit Nederland komt: “Eu sou dos Países Baixos.”", "Oefen “muito prazer” alsof je iemand voor het eerst ontmoet.", "Maak een korte introductie van jezelf in drie zinnen."]
},
{
  day: 3,
  title: "Nummers en prijzen in Lissabon",
  titleNative: "Números e preços em Lisboa",
  focus: "Je leert tellen en eenvoudige prijzen begrijpen. Dit helpt bij cafés, markten, metrokaartjes en kleine aankopen.",
  vocab: [{ pt: "um", nl: "één", ipa: "/ũ/" }, { pt: "dois", nl: "twee", ipa: "/dojʃ/" }, { pt: "três", nl: "drie", ipa: "/tɾeʃ/" }, { pt: "quatro", nl: "vier", ipa: "/ˈkwa.tɾu/" }, { pt: "cinco", nl: "vijf", ipa: "/ˈsĩ.ku/" }, { pt: "seis", nl: "zes", ipa: "/sejʃ/" }, { pt: "sete", nl: "zeven", ipa: "/ˈsɛ.tɨ/" }, { pt: "oito", nl: "acht", ipa: "/ˈoj.tu/" }, { pt: "nove", nl: "negen", ipa: "/ˈnɔ.vɨ/" }, { pt: "dez", nl: "tien", ipa: "/dɛʃ/" }],
  phrases: [{ pt: "Quanto custa?", nl: "Hoeveel kost het?", ipa: "/ˈkwɐ̃.tu ˈkuʃ.tɐ/" }, { pt: "Custa cinco euros.", nl: "Het kost vijf euro.", ipa: "/ˈkuʃ.tɐ ˈsĩ.ku ˈew.ɾuʃ/" }, { pt: "Quero dois cafés.", nl: "Ik wil twee koffies.", ipa: "/ˈkɛ.ɾu dojʃ kaˈfɛʃ/" }, { pt: "Só um, por favor.", nl: "Slechts één, alstublieft.", ipa: "/sɔ ũ puɾ faˈvoɾ/" }, { pt: "Tem troco?", nl: "Heeft u wisselgeld?", ipa: "/tẽj ˈtɾɔ.ku/" }, { pt: "São dez euros.", nl: "Het is tien euro.", ipa: "/sɐ̃w dɛʃ ˈew.ɾuʃ/" }],
  grammar: "Portugese cijfers zijn essentieel voor prijzen. In Portugal wordt “euro” vaak in het meervoud “euros” uitgesproken als /ˈew.ɾuʃ/. Bij bestellen gebruik je meestal “quero” voor “ik wil”, maar “queria” klinkt beleefder en leer je later.",
  practice: ["Tel hardop van één tot tien in het Portugees.", "Vraag de prijs van een fles water.", "Zeg dat iets vijf euro kost.", "Bestel twee koffies met “Quero dois cafés.”", "Schrijf drie prijzen op en lees ze hardop in het Portugees."]
},
{
  day: 4,
  title: "Essentiële beleefdheid in een café",
  titleNative: "Cortesia essencial num café",
  focus: "Je leert beleefde woorden gebruiken in een Portugees café. De zinnen zijn kort, maar ze maken je meteen vriendelijker en duidelijker.",
  vocab: [{ pt: "desculpe", nl: "sorry / pardon", ipa: "/dɨʃˈkul.pɨ/" }, { pt: "com licença", nl: "pardon / mag ik erlangs", ipa: "/kõ liˈsẽ.sɐ/" }, { pt: "obrigado", nl: "bedankt", ipa: "/obɾiˈɡa.du/" }, { pt: "nada", nl: "niets", ipa: "/ˈna.dɐ/" }, { pt: "de nada", nl: "graag gedaan", ipa: "/dɨ ˈna.dɐ/" }, { pt: "por favor", nl: "alstublieft", ipa: "/puɾ faˈvoɾ/" }, { pt: "sim", nl: "ja", ipa: "/sĩ/" }, { pt: "não", nl: "nee", ipa: "/nɐ̃w/" }, { pt: "claro", nl: "natuurlijk", ipa: "/ˈkla.ɾu/" }, { pt: "talvez", nl: "misschien", ipa: "/tɐlˈveʃ/" }],
  phrases: [{ pt: "Desculpe, por favor.", nl: "Pardon, alstublieft.", ipa: "/dɨʃˈkul.pɨ puɾ faˈvoɾ/" }, { pt: "Com licença.", nl: "Pardon / mag ik erlangs.", ipa: "/kõ liˈsẽ.sɐ/" }, { pt: "Não, obrigado.", nl: "Nee, bedankt, gezegd door man.", ipa: "/nɐ̃w obɾiˈɡa.du/" }, { pt: "Sim, por favor.", nl: "Ja, graag.", ipa: "/sĩ puɾ faˈvoɾ/" }, { pt: "De nada.", nl: "Graag gedaan.", ipa: "/dɨ ˈna.dɐ/" }, { pt: "Está bem.", nl: "Dat is goed.", ipa: "/ʃta bẽj/" }],
  grammar: "“Desculpe” gebruik je om aandacht te trekken of je te verontschuldigen. “Com licença” gebruik je wanneer je langs iemand wilt of een ruimte binnenkomt. In Portugal klinkt beleefdheid vaak subtiel: een eenvoudige groet plus “por favor” is meestal genoeg.",
  practice: ["Oefen “desculpe” alsof je een ober aanspreekt.", "Reageer op “obrigado” met “de nada”.", "Zeg beleefd nee tegen extra suiker.", "Gebruik “com licença” in een zin.", "Maak vijf korte cafézinnen met “por favor”."]
},
{
  day: 5,
  title: "Eten en drinken bestellen",
  titleNative: "Pedir comida e bebida",
  focus: "Je leert eenvoudige bestellingen plaatsen in een café in Coimbra. Je oefent met koffie, water, broodjes en beleefde verzoeken.",
  vocab: [{ pt: "café", nl: "koffie / espresso", ipa: "/kaˈfɛ/" }, { pt: "água", nl: "water", ipa: "/ˈa.ɡwɐ/" }, { pt: "chá", nl: "thee", ipa: "/ʃa/" }, { pt: "sumo", nl: "sap", ipa: "/ˈsu.mu/" }, { pt: "pão", nl: "brood", ipa: "/pɐ̃w/" }, { pt: "sanduíche", nl: "sandwich", ipa: "/sɐ̃ˈdwiʃ/" }, { pt: "queijo", nl: "kaas", ipa: "/ˈkɐj.ʒu/" }, { pt: "fiambre", nl: "ham", ipa: "/fiˈɐ̃.bɾɨ/" }, { pt: "açúcar", nl: "suiker", ipa: "/ɐˈsu.kaɾ/" }, { pt: "leite", nl: "melk", ipa: "/ˈlɐj.tɨ/" }],
  phrases: [{ pt: "Queria um café, por favor.", nl: "Ik zou graag een koffie willen.", ipa: "/kɨˈɾi.ɐ ũ kaˈfɛ puɾ faˈvoɾ/" }, { pt: "Queria uma água.", nl: "Ik zou graag water willen.", ipa: "/kɨˈɾi.ɐ ˈu.mɐ ˈa.ɡwɐ/" }, { pt: "Tem chá?", nl: "Heeft u thee?", ipa: "/tẽj ʃa/" }, { pt: "Sem açúcar, por favor.", nl: "Zonder suiker, alstublieft.", ipa: "/sẽ ɐˈsu.kaɾ puɾ faˈvoɾ/" }, { pt: "Com leite.", nl: "Met melk.", ipa: "/kõ ˈlɐj.tɨ/" }, { pt: "Para levar.", nl: "Om mee te nemen.", ipa: "/ˈpa.ɾɐ lɨˈvaɾ/" }],
  grammar: "“Queria” betekent letterlijk “ik wilde”, maar in Portugal is het een beleefde manier om iets te bestellen. Het klinkt zachter dan “quero”. Gebruik “um” voor mannelijke woorden zoals “café” en “uma” voor vrouwelijke woorden zoals “água”.",
  practice: ["Bestel een koffie met “Queria um café, por favor.”", "Vraag of ze thee hebben.", "Zeg “zonder suiker” in het Portugees.", "Bestel water om mee te nemen.", "Maak een bestelling met één drankje en één sandwich."]
},
{
  day: 6,
  title: "De weg vragen in Lissabon",
  titleNative: "Pedir direções em Lisboa",
  focus: "Je leert eenvoudige richtingen vragen en begrijpen. Dit is handig rond metrohaltes, pleinen en toeristische wijken zoals Alfama.",
  vocab: [{ pt: "rua", nl: "straat", ipa: "/ˈʁu.ɐ/" }, { pt: "praça", nl: "plein", ipa: "/ˈpɾa.sɐ/" }, { pt: "direita", nl: "rechts", ipa: "/diˈɾɐj.tɐ/" }, { pt: "esquerda", nl: "links", ipa: "/ɨʃˈkeɾ.dɐ/" }, { pt: "em frente", nl: "rechtdoor", ipa: "/ẽ ˈfɾẽ.tɨ/" }, { pt: "perto", nl: "dichtbij", ipa: "/ˈpɛɾ.tu/" }, { pt: "longe", nl: "ver", ipa: "/ˈlõ.ʒɨ/" }, { pt: "aqui", nl: "hier", ipa: "/ɐˈki/" }, { pt: "ali", nl: "daar", ipa: "/ɐˈli/" }, { pt: "mapa", nl: "kaart", ipa: "/ˈma.pɐ/" }],
  phrases: [{ pt: "Onde fica a estação?", nl: "Waar is het station?", ipa: "/ˈõ.dɨ ˈfi.kɐ ɐ ɨʃtɐˈsɐ̃w/" }, { pt: "Vire à direita.", nl: "Sla rechtsaf.", ipa: "/ˈvi.ɾɨ a diˈɾɐj.tɐ/" }, { pt: "Vire à esquerda.", nl: "Sla linksaf.", ipa: "/ˈvi.ɾɨ a ɨʃˈkeɾ.dɐ/" }, { pt: "Siga em frente.", nl: "Ga rechtdoor.", ipa: "/ˈsi.ɡɐ ẽ ˈfɾẽ.tɨ/" }, { pt: "É perto daqui?", nl: "Is het dichtbij hier?", ipa: "/ɛ ˈpɛɾ.tu dɐˈki/" }, { pt: "Pode mostrar no mapa?", nl: "Kunt u het op de kaart laten zien?", ipa: "/ˈpɔ.dɨ muʃˈtɾaɾ nu ˈma.pɐ/" }],
  grammar: "“Ficar” wordt vaak gebruikt voor locaties: “Onde fica...?” betekent “Waar bevindt zich...?” Voor richtingen hoor je vaak de gebiedende vorm, zoals “siga” en “vire”. Je hoeft die nog niet volledig te beheersen; herken ze eerst als praktische instructies.",
  practice: ["Vraag waar het station is.", "Zeg “ga rechtdoor” in het Portugees.", "Vraag of iets dichtbij is.", "Oefen links en rechts met handgebaren.", "Maak een routebeschrijving van drie stappen."]
},
{
  day: 7,
  title: "Inchecken bij een hotel",
  titleNative: "Fazer check-in no hotel",
  focus: "Je leert wat je bij een hotelreceptie in Porto kunt zeggen. Je oefent met reserveringen, paspoort, kamer en sleutel.",
  vocab: [{ pt: "hotel", nl: "hotel", ipa: "/oˈtɛl/" }, { pt: "reserva", nl: "reservering", ipa: "/ʁɨˈzɛɾ.vɐ/" }, { pt: "quarto", nl: "kamer", ipa: "/ˈkwaɾ.tu/" }, { pt: "chave", nl: "sleutel", ipa: "/ˈʃa.vɨ/" }, { pt: "passaporte", nl: "paspoort", ipa: "/pɐ.sɐˈpɔɾ.tɨ/" }, { pt: "receção", nl: "receptie", ipa: "/ʁɨ.sɨˈsɐ̃w/" }, { pt: "noite", nl: "nacht", ipa: "/ˈnoj.tɨ/" }, { pt: "elevador", nl: "lift", ipa: "/ɨ.lɨ.vɐˈdoɾ/" }, { pt: "bagagem", nl: "bagage", ipa: "/bɐˈɡa.ʒɐ̃j/" }, { pt: "pequeno-almoço", nl: "ontbijt", ipa: "/pɨˈke.nu ɐlˈmɔ.su/" }],
  phrases: [{ pt: "Tenho uma reserva.", nl: "Ik heb een reservering.", ipa: "/ˈtɐ.ɲu ˈu.mɐ ʁɨˈzɛɾ.vɐ/" }, { pt: "O meu nome é Cannon.", nl: "Mijn naam is Cannon.", ipa: "/u mew ˈnɔ.mɨ ɛ ˈka.nɔn/" }, { pt: "Aqui está o passaporte.", nl: "Hier is het paspoort.", ipa: "/ɐˈki ʃta u pɐ.sɐˈpɔɾ.tɨ/" }, { pt: "Qual é o número do quarto?", nl: "Wat is het kamernummer?", ipa: "/kwal ɛ u ˈnu.mɨ.ɾu du ˈkwaɾ.tu/" }, { pt: "O pequeno-almoço está incluído?", nl: "Is het ontbijt inbegrepen?", ipa: "/u pɨˈke.nu ɐlˈmɔ.su ʃta ĩ.kluˈi.du/" }, { pt: "Onde fica o elevador?", nl: "Waar is de lift?", ipa: "/ˈõ.dɨ ˈfi.kɐ u ɨ.lɨ.vɐˈdoɾ/" }],
  grammar: "“Incluído” betekent inbegrepen. In Portugal heet ontbijt “pequeno-almoço”, letterlijk “kleine lunch”, wat anders is dan Braziliaans Portugees “café da manhã”. Voor reizen in Portugal is “pequeno-almoço” de handigste vorm.",
  practice: ["Zeg dat je een reservering hebt.", "Vraag naar het kamernummer.", "Vraag of het ontbijt inbegrepen is.", "Vraag waar de lift is.", "Speel een hotelgesprek van vier zinnen na."]
},
{
  day: 8,
  title: "Openbaar vervoer in Portugal",
  titleNative: "Transportes públicos em Portugal",
  focus: "Je leert woorden voor metro, trein, bus en kaartjes. Dit helpt bij reizen door Lissabon, Porto en tussen steden.",
  vocab: [{ pt: "metro", nl: "metro", ipa: "/ˈmɛ.tɾu/" }, { pt: "comboio", nl: "trein", ipa: "/kõˈboj.u/" }, { pt: "autocarro", nl: "bus", ipa: "/ɐw.tuˈka.ʁu/" }, { pt: "bilhete", nl: "kaartje", ipa: "/biˈʎe.tɨ/" }, { pt: "estação", nl: "station", ipa: "/ɨʃtɐˈsɐ̃w/" }, { pt: "paragem", nl: "halte", ipa: "/pɐˈɾa.ʒɐ̃j/" }, { pt: "ida", nl: "heenreis", ipa: "/ˈi.dɐ/" }, { pt: "volta", nl: "terugreis", ipa: "/ˈvɔl.tɐ/" }, { pt: "linha", nl: "lijn", ipa: "/ˈli.ɲɐ/" }, { pt: "horário", nl: "dienstregeling", ipa: "/oˈɾa.ɾju/" }],
  phrases: [{ pt: "Queria um bilhete.", nl: "Ik wil graag een kaartje.", ipa: "/kɨˈɾi.ɐ ũ biˈʎe.tɨ/" }, { pt: "Só ida, por favor.", nl: "Alleen heen, alstublieft.", ipa: "/sɔ ˈi.dɐ puɾ faˈvoɾ/" }, { pt: "Ida e volta.", nl: "Heen en terug.", ipa: "/ˈi.dɐ i ˈvɔl.tɐ/" }, { pt: "Qual é a linha?", nl: "Welke lijn is het?", ipa: "/kwal ɛ ɐ ˈli.ɲɐ/" }, { pt: "Onde é a paragem?", nl: "Waar is de halte?", ipa: "/ˈõ.dɨ ɛ ɐ pɐˈɾa.ʒɐ̃j/" }, { pt: "A que horas sai o comboio?", nl: "Hoe laat vertrekt de trein?", ipa: "/ɐ kɨ ˈɔ.ɾɐʃ saj u kõˈboj.u/" }],
  grammar: "“Comboio” is het Europese Portugese woord voor trein. In Portugal gebruik je vaak “autocarro” voor bus; in Brazilië hoor je eerder “ônibus”. Voor deze cursus richten we ons op Portugees zoals je het in Portugal hoort.",
  practice: ["Vraag om een kaartje heen en terug.", "Vraag hoe laat de trein vertrekt.", "Zeg “alleen heen” in het Portugees.", "Vraag naar de juiste metrolijn.", "Maak een korte dialoog bij een loket."]
},
{
  day: 9,
  title: "Tijden en dagen",
  titleNative: "Horas e dias",
  focus: "Je leert eenvoudige tijden en dagen gebruiken om plannen te maken. Dit is handig voor tours, treinen, restaurantreserveringen en openingstijden.",
  vocab: [{ pt: "hoje", nl: "vandaag", ipa: "/ˈo.ʒɨ/" }, { pt: "amanhã", nl: "morgen", ipa: "/ɐ.mɐˈɲɐ̃/" }, { pt: "ontem", nl: "gisteren", ipa: "/ˈõ.tɐ̃j/" }, { pt: "hora", nl: "uur", ipa: "/ˈɔ.ɾɐ/" }, { pt: "minuto", nl: "minuut", ipa: "/miˈnu.tu/" }, { pt: "segunda-feira", nl: "maandag", ipa: "/sɨˈɡũ.dɐ ˈfɐj.ɾɐ/" }, { pt: "terça-feira", nl: "dinsdag", ipa: "/ˈtɛɾ.sɐ ˈfɐj.ɾɐ/" }, { pt: "quarta-feira", nl: "woensdag", ipa: "/ˈkwaɾ.tɐ ˈfɐj.ɾɐ/" }, { pt: "sábado", nl: "zaterdag", ipa: "/ˈsa.bɐ.du/" }, { pt: "domingo", nl: "zondag", ipa: "/duˈmĩ.ɡu/" }],
  phrases: [{ pt: "Que horas são?", nl: "Hoe laat is het?", ipa: "/kɨ ˈɔ.ɾɐʃ sɐ̃w/" }, { pt: "É uma hora.", nl: "Het is één uur.", ipa: "/ɛ ˈu.mɐ ˈɔ.ɾɐ/" }, { pt: "São três horas.", nl: "Het is drie uur.", ipa: "/sɐ̃w tɾeʃ ˈɔ.ɾɐʃ/" }, { pt: "Hoje à tarde.", nl: "Vanmiddag.", ipa: "/ˈo.ʒɨ a ˈtaɾ.dɨ/" }, { pt: "Amanhã de manhã.", nl: "Morgenochtend.", ipa: "/ɐ.mɐˈɲɐ̃ dɨ mɐˈɲɐ̃/" }, { pt: "Está aberto?", nl: "Is het open?", ipa: "/ʃta ɐˈbɛɾ.tu/" }],
  grammar: "Bij tijden gebruik je “é” voor één uur en “são” voor alle andere uren. “De manhã” betekent in de ochtend, “à tarde” in de middag en “à noite” in de avond. Let op dat weekdagen in het Portugees vaak met “-feira” worden gezegd.",
  practice: ["Vraag hoe laat het is.", "Zeg dat het drie uur is.", "Plan iets voor morgenochtend.", "Vraag of een museum open is.", "Schrijf drie dagen van de week in het Portugees."]
},
{
  day: 10,
  title: "Op de markt in Braga",
  titleNative: "No mercado em Braga",
  focus: "Je leert fruit, hoeveelheden en simpele marktvragen. Je oefent met kopen, aanwijzen en vragen naar prijs.",
  vocab: [{ pt: "mercado", nl: "markt", ipa: "/mɨɾˈka.du/" }, { pt: "maçã", nl: "appel", ipa: "/mɐˈsɐ̃/" }, { pt: "banana", nl: "banaan", ipa: "/bɐˈna.nɐ/" }, { pt: "laranja", nl: "sinaasappel", ipa: "/lɐˈɾɐ̃.ʒɐ/" }, { pt: "tomate", nl: "tomaat", ipa: "/tuˈma.tɨ/" }, { pt: "queijo", nl: "kaas", ipa: "/ˈkɐj.ʒu/" }, { pt: "quilo", nl: "kilo", ipa: "/ˈki.lu/" }, { pt: "meio", nl: "half", ipa: "/ˈmɐj.u/" }, { pt: "fresco", nl: "vers", ipa: "/ˈfɾeʃ.ku/" }, { pt: "saco", nl: "tas / zak", ipa: "/ˈsa.ku/" }],
  phrases: [{ pt: "Queria meio quilo.", nl: "Ik wil graag een halve kilo.", ipa: "/kɨˈɾi.ɐ ˈmɐj.u ˈki.lu/" }, { pt: "Quanto custa o quilo?", nl: "Hoeveel kost de kilo?", ipa: "/ˈkwɐ̃.tu ˈkuʃ.tɐ u ˈki.lu/" }, { pt: "Está fresco?", nl: "Is het vers?", ipa: "/ʃta ˈfɾeʃ.ku/" }, { pt: "Quero estas maçãs.", nl: "Ik wil deze appels.", ipa: "/ˈkɛ.ɾu ˈeʃ.tɐʃ mɐˈsɐ̃jʃ/" }, { pt: "Tem saco?", nl: "Heeft u een tas?", ipa: "/tẽj ˈsa.ku/" }, { pt: "É tudo, obrigado.", nl: "Dat is alles, bedankt.", ipa: "/ɛ ˈtu.du obɾiˈɡa.du/" }],
  grammar: "“Este/esta/estes/estas” betekent deze of dit, afhankelijk van geslacht en meervoud. “Estas maçãs” is “deze appels”, omdat “maçã” vrouwelijk is. Op een markt kun je ook gewoon aanwijzen en “este” of “esta” zeggen.",
  practice: ["Vraag naar de prijs per kilo.", "Bestel een halve kilo tomaten.", "Vraag of het fruit vers is.", "Zeg “dat is alles, bedankt”.", "Maak een marktgesprek van vijf regels."]
},
{
  day: 11,
  title: "In een restaurant in Porto",
  titleNative: "Num restaurante no Porto",
  focus: "Je leert eten bestellen aan tafel. Je oefent met menu, voorgerecht, hoofdgerecht, rekening en dieetwensen.",
  vocab: [{ pt: "restaurante", nl: "restaurant", ipa: "/ʁɨʃ.tɐwˈɾɐ̃.tɨ/" }, { pt: "mesa", nl: "tafel", ipa: "/ˈme.zɐ/" }, { pt: "ementa", nl: "menu", ipa: "/ɨˈmẽ.tɐ/" }, { pt: "entrada", nl: "voorgerecht", ipa: "/ẽˈtɾa.dɐ/" }, { pt: "prato", nl: "gerecht", ipa: "/ˈpɾa.tu/" }, { pt: "peixe", nl: "vis", ipa: "/ˈpɐj.ʃɨ/" }, { pt: "carne", nl: "vlees", ipa: "/ˈkaɾ.nɨ/" }, { pt: "vegetariano", nl: "vegetarisch", ipa: "/vɨ.ʒɨ.tɐˈɾjɐ.nu/" }, { pt: "conta", nl: "rekening", ipa: "/ˈkõ.tɐ/" }, { pt: "gorjeta", nl: "fooi", ipa: "/ɡuɾˈʒe.tɐ/" }],
  phrases: [{ pt: "Tem mesa para dois?", nl: "Heeft u een tafel voor twee?", ipa: "/tẽj ˈme.zɐ ˈpa.ɾɐ dojʃ/" }, { pt: "Pode trazer a ementa?", nl: "Kunt u het menu brengen?", ipa: "/ˈpɔ.dɨ tɾɐˈzeɾ ɐ ɨˈmẽ.tɐ/" }, { pt: "Queria o peixe.", nl: "Ik wil graag de vis.", ipa: "/kɨˈɾi.ɐ u ˈpɐj.ʃɨ/" }, { pt: "Sou vegetariano.", nl: "Ik ben vegetariër, gezegd door man.", ipa: "/sow vɨ.ʒɨ.tɐˈɾjɐ.nu/" }, { pt: "Sou vegetariana.", nl: "Ik ben vegetariër, gezegd door vrouw.", ipa: "/sow vɨ.ʒɨ.tɐˈɾjɐ.nɐ/" }, { pt: "A conta, por favor.", nl: "De rekening, alstublieft.", ipa: "/ɐ ˈkõ.tɐ puɾ faˈvoɾ/" }],
  grammar: "Bij nationaliteiten, beroepen en beschrijvingen verandert vaak de uitgang: “vegetariano” voor een man, “vegetariana” voor een vrouw. “Pode trazer...?” is een beleefde manier om te vragen of iemand iets kan brengen. Het is handig in restaurants en cafés.",
  practice: ["Vraag om een tafel voor twee.", "Vraag om het menu.", "Bestel vis of een vegetarisch gerecht.", "Vraag om de rekening.", "Schrijf een restaurantbestelling van drie gangen."]
},
{
  day: 12,
  title: "Speciale wensen en allergieën",
  titleNative: "Pedidos especiais e alergias",
  focus: "Je leert belangrijke zinnen voor allergieën en dieetwensen. Dit is praktisch en soms noodzakelijk tijdens reizen.",
  vocab: [{ pt: "alergia", nl: "allergie", ipa: "/ɐ.lɨɾˈʒi.ɐ/" }, { pt: "amendoim", nl: "pinda", ipa: "/ɐ.mẽˈdo.ĩ/" }, { pt: "leite", nl: "melk", ipa: "/ˈlɐj.tɨ/" }, { pt: "glúten", nl: "gluten", ipa: "/ˈɡlu.tẽn/" }, { pt: "marisco", nl: "schaaldieren", ipa: "/mɐˈɾiʃ.ku/" }, { pt: "sem", nl: "zonder", ipa: "/sẽ/" }, { pt: "com", nl: "met", ipa: "/kõ/" }, { pt: "molho", nl: "saus", ipa: "/ˈmo.ʎu/" }, { pt: "picante", nl: "pittig", ipa: "/piˈkɐ̃.tɨ/" }, { pt: "ingrediente", nl: "ingrediënt", ipa: "/ĩ.ɡɾɨ.diˈẽ.tɨ/" }],
  phrases: [{ pt: "Tenho alergia a amendoim.", nl: "Ik ben allergisch voor pinda’s.", ipa: "/ˈtɐ.ɲu ɐ.lɨɾˈʒi.ɐ ɐ ɐ.mẽˈdo.ĩ/" }, { pt: "Sem glúten, por favor.", nl: "Zonder gluten, alstublieft.", ipa: "/sẽ ˈɡlu.tẽn puɾ faˈvoɾ/" }, { pt: "Tem leite?", nl: "Zit er melk in?", ipa: "/tẽj ˈlɐj.tɨ/" }, { pt: "Não posso comer marisco.", nl: "Ik kan geen schaaldieren eten.", ipa: "/nɐ̃w ˈpɔ.su kuˈmeɾ mɐˈɾiʃ.ku/" }, { pt: "O molho é picante?", nl: "Is de saus pittig?", ipa: "/u ˈmo.ʎu ɛ piˈkɐ̃.tɨ/" }, { pt: "Pode ser sem molho?", nl: "Kan het zonder saus?", ipa: "/ˈpɔ.dɨ seɾ sẽ ˈmo.ʎu/" }],
  grammar: "“Tenho alergia a...” betekent “ik heb een allergie voor...”. Voor eten is “sem” een krachtig woord: “sem leite”, “sem glúten”, “sem molho”. Als het belangrijk is, spreek langzaam en herhaal de allergie.",
  practice: ["Zeg dat je allergisch bent voor pinda’s.", "Vraag of er melk in zit.", "Vraag om iets zonder saus.", "Zeg dat je geen schaaldieren kunt eten.", "Maak een lijst met drie ingrediënten die je wilt vermijden."]
},
{
  day: 13,
  title: "Winkelen in Chiado",
  titleNative: "Fazer compras no Chiado",
  focus: "Je leert vragen naar maten, kleuren en prijzen in een winkel. De scène speelt zich af in een winkelstraat in Lissabon.",
  vocab: [{ pt: "loja", nl: "winkel", ipa: "/ˈlɔ.ʒɐ/" }, { pt: "camisa", nl: "overhemd / blouse", ipa: "/kɐˈmi.zɐ/" }, { pt: "calças", nl: "broek", ipa: "/ˈkal.sɐʃ/" }, { pt: "sapatos", nl: "schoenen", ipa: "/sɐˈpa.tuʃ/" }, { pt: "tamanho", nl: "maat", ipa: "/tɐˈmɐ.ɲu/" }, { pt: "cor", nl: "kleur", ipa: "/koɾ/" }, { pt: "preço", nl: "prijs", ipa: "/ˈpɾe.su/" }, { pt: "caro", nl: "duur", ipa: "/ˈka.ɾu/" }, { pt: "barato", nl: "goedkoop", ipa: "/bɐˈɾa.tu/" }, { pt: "recibo", nl: "bon", ipa: "/ʁɨˈsi.bu/" }],
  phrases: [{ pt: "Tem este tamanho?", nl: "Heeft u deze maat?", ipa: "/tẽj ˈeʃ.tɨ tɐˈmɐ.ɲu/" }, { pt: "Tem outra cor?", nl: "Heeft u een andere kleur?", ipa: "/tẽj ˈo.tɾɐ koɾ/" }, { pt: "Posso experimentar?", nl: "Mag ik het passen?", ipa: "/ˈpɔ.su ɨʃ.pɨ.ɾi.mẽˈtaɾ/" }, { pt: "É muito caro.", nl: "Het is erg duur.", ipa: "/ɛ ˈmũj.tu ˈka.ɾu/" }, { pt: "Está em promoção?", nl: "Is het in de aanbieding?", ipa: "/ʃta ẽ pɾu.muˈsɐ̃w/" }, { pt: "Queria o recibo.", nl: "Ik wil graag de bon.", ipa: "/kɨˈɾi.ɐ u ʁɨˈsi.bu/" }],
  grammar: "“Posso...” betekent “mag ik” of “kan ik”. Het is heel handig: “Posso experimentar?” in een kledingwinkel, “Posso pagar?” bij de kassa, “Posso entrar?” bij een deur. “Muito” vóór een bijvoeglijk naamwoord betekent “erg” of “heel”.",
  practice: ["Vraag of je iets mag passen.", "Vraag naar een andere kleur.", "Zeg dat iets erg duur is.", "Vraag om de bon.", "Maak een winkelgesprek van zes regels."]
},
{
  day: 14,
  title: "Betalen en geldzaken",
  titleNative: "Pagar e dinheiro",
  focus: "Je leert betalen met kaart of contant geld. Dit helpt in winkels, cafés, taxi’s en bij kleine servicepunten.",
  vocab: [{ pt: "dinheiro", nl: "geld / contant", ipa: "/diˈɲɐj.ɾu/" }, { pt: "cartão", nl: "kaart", ipa: "/kaɾˈtɐ̃w/" }, { pt: "multibanco", nl: "pinautomaat / bankautomaat", ipa: "/mul.tiˈbɐ̃.ku/" }, { pt: "pagar", nl: "betalen", ipa: "/pɐˈɡaɾ/" }, { pt: "troco", nl: "wisselgeld", ipa: "/ˈtɾɔ.ku/" }, { pt: "fatura", nl: "factuur", ipa: "/fɐˈtu.ɾɐ/" }, { pt: "recibo", nl: "bon", ipa: "/ʁɨˈsi.bu/" }, { pt: "contactless", nl: "contactloos", ipa: "/ˈkõ.tak.tlɛʃ/" }, { pt: "código", nl: "code", ipa: "/ˈkɔ.di.ɡu/" }, { pt: "caixa", nl: "kassa", ipa: "/ˈkaj.ʃɐ/" }],
  phrases: [{ pt: "Posso pagar com cartão?", nl: "Kan ik met kaart betalen?", ipa: "/ˈpɔ.su pɐˈɡaɾ kõ kaɾˈtɐ̃w/" }, { pt: "Só tenho dinheiro.", nl: "Ik heb alleen contant geld.", ipa: "/sɔ ˈtɐ.ɲu diˈɲɐj.ɾu/" }, { pt: "Onde fica o multibanco?", nl: "Waar is de pinautomaat?", ipa: "/ˈõ.dɨ ˈfi.kɐ u mul.tiˈbɐ̃.ku/" }, { pt: "Precisa de código?", nl: "Is er een pincode nodig?", ipa: "/pɾɨˈsi.zɐ dɨ ˈkɔ.di.ɡu/" }, { pt: "Pode repetir o valor?", nl: "Kunt u het bedrag herhalen?", ipa: "/ˈpɔ.dɨ ʁɨ.pɨˈtiɾ u vɐˈloɾ/" }, { pt: "Não preciso de fatura.", nl: "Ik heb geen factuur nodig.", ipa: "/nɐ̃w pɾɨˈsi.zu dɨ fɐˈtu.ɾɐ/" }],
  grammar: "“Com” betekent “met”: “com cartão”, “com dinheiro”. “Preciso de...” betekent “ik heb nodig”, en “não preciso de...” betekent “ik heb niet nodig”. In Portugal kan men soms vragen of je een “fatura” wilt, vooral bij officiële aankopen.",
  practice: ["Vraag of je met kaart kunt betalen.", "Vraag waar de pinautomaat is.", "Zeg dat je alleen contant geld hebt.", "Vraag of er een code nodig is.", "Oefen het verschil tussen “recibo” en “fatura”."]
},
{
  day: 15,
  title: "Taxi en ritdelen in Lissabon",
  titleNative: "Táxi e transporte por aplicação em Lisboa",
  focus: "Je leert een bestemming noemen en praktische vragen stellen tijdens een taxirit. Je oefent met adres, duur, prijs en bagage.",
  vocab: [{ pt: "táxi", nl: "taxi", ipa: "/ˈtak.si/" }, { pt: "morada", nl: "adres", ipa: "/muˈɾa.dɐ/" }, { pt: "aeroporto", nl: "luchthaven", ipa: "/ɐ.e.ɾuˈpɔɾ.tu/" }, { pt: "centro", nl: "centrum", ipa: "/ˈsẽ.tɾu/" }, { pt: "bagagem", nl: "bagage", ipa: "/bɐˈɡa.ʒɐ̃j/" }, { pt: "rápido", nl: "snel", ipa: "/ˈʁa.pi.du/" }, { pt: "trânsito", nl: "verkeer", ipa: "/ˈtɾɐ̃.zi.tu/" }, { pt: "viagem", nl: "rit / reis", ipa: "/viˈa.ʒɐ̃j/" }, { pt: "aplicação", nl: "app", ipa: "/ɐ.pli.kɐˈsɐ̃w/" }, { pt: "motorista", nl: "chauffeur", ipa: "/mu.tuˈɾiʃ.tɐ/" }],
  phrases: [{ pt: "Para o aeroporto, por favor.", nl: "Naar de luchthaven, alstublieft.", ipa: "/ˈpa.ɾɐ u ɐ.e.ɾuˈpɔɾ.tu puɾ faˈvoɾ/" }, { pt: "Esta é a morada.", nl: "Dit is het adres.", ipa: "/ˈeʃ.tɐ ɛ ɐ muˈɾa.dɐ/" }, { pt: "Quanto tempo demora?", nl: "Hoe lang duurt het?", ipa: "/ˈkwɐ̃.tu ˈtẽ.pu dɨˈmɔ.ɾɐ/" }, { pt: "Há muito trânsito?", nl: "Is er veel verkeer?", ipa: "/a ˈmũj.tu ˈtɾɐ̃.zi.tu/" }, { pt: "Pode parar aqui?", nl: "Kunt u hier stoppen?", ipa: "/ˈpɔ.dɨ pɐˈɾaɾ ɐˈki/" }, { pt: "Preciso de ajuda com a bagagem.", nl: "Ik heb hulp nodig met de bagage.", ipa: "/pɾɨˈsi.zu dɨ ɐˈʒu.dɐ kõ ɐ bɐˈɡa.ʒɐ̃j/" }],
  grammar: "“Para” betekent “naar” wanneer je een bestemming noemt: “Para o aeroporto”. “Há” betekent “er is” of “er zijn”, zoals in “Há trânsito?” Voor een chauffeur zijn korte zinnen vaak het duidelijkst.",
  practice: ["Zeg dat je naar de luchthaven wilt.", "Toon een adres en zeg “Esta é a morada.”", "Vraag hoe lang de rit duurt.", "Vraag of er veel verkeer is.", "Vraag of de chauffeur hier kan stoppen."]
},
{
  day: 16,
  title: "Reserveringen en plannen maken",
  titleNative: "Reservas e planos",
  focus: "Je leert reserveren en afspraken maken. Dit is handig voor restaurants, tours, musea en activiteiten in Portugal.",
  vocab: [{ pt: "reserva", nl: "reservering", ipa: "/ʁɨˈzɛɾ.vɐ/" }, { pt: "marcação", nl: "afspraak / boeking", ipa: "/mɐɾ.kɐˈsɐ̃w/" }, { pt: "pessoa", nl: "persoon", ipa: "/pɨˈso.ɐ/" }, { pt: "disponível", nl: "beschikbaar", ipa: "/diʃ.puˈni.vɛl/" }, { pt: "cheio", nl: "vol", ipa: "/ˈʃɐj.u/" }, { pt: "livre", nl: "vrij", ipa: "/ˈli.vɾɨ/" }, { pt: "confirmar", nl: "bevestigen", ipa: "/kõ.fiɾˈmaɾ/" }, { pt: "cancelar", nl: "annuleren", ipa: "/kɐ̃.sɨˈlaɾ/" }, { pt: "atrasado", nl: "te laat", ipa: "/ɐ.tɾɐˈza.du/" }, { pt: "cedo", nl: "vroeg", ipa: "/ˈse.du/" }],
  phrases: [{ pt: "Queria fazer uma reserva.", nl: "Ik wil graag een reservering maken.", ipa: "/kɨˈɾi.ɐ fɐˈzeɾ ˈu.mɐ ʁɨˈzɛɾ.vɐ/" }, { pt: "Para duas pessoas.", nl: "Voor twee personen.", ipa: "/ˈpa.ɾɐ ˈdu.ɐʃ pɨˈso.ɐʃ/" }, { pt: "Tem mesa às oito?", nl: "Heeft u een tafel om acht uur?", ipa: "/tẽj ˈme.zɐ aʒ ˈoj.tu/" }, { pt: "Está disponível amanhã?", nl: "Is het morgen beschikbaar?", ipa: "/ʃta diʃ.puˈni.vɛl ɐ.mɐˈɲɐ̃/" }, { pt: "Queria confirmar a reserva.", nl: "Ik wil graag de reservering bevestigen.", ipa: "/kɨˈɾi.ɐ kõ.fiɾˈmaɾ ɐ ʁɨˈzɛɾ.vɐ/" }, { pt: "Preciso cancelar.", nl: "Ik moet annuleren.", ipa: "/pɾɨˈsi.zu kɐ̃.sɨˈlaɾ/" }],
  grammar: "Voor tijden gebruik je “às” met een uur: “às oito” betekent om acht uur. “Para duas pessoas” is een standaardzin bij restaurants. “Queria fazer...” is beleefd en bruikbaar voor reserveringen en afspraken.",
  practice: ["Maak een reservering voor twee personen.", "Vraag of er morgen plek is.", "Bevestig een reservering.", "Zeg dat je moet annuleren.", "Maak een telefoongesprek voor een restaurantreservering."]
},
{
  day: 17,
  title: "Bij de apotheek",
  titleNative: "Na farmácia",
  focus: "Je leert eenvoudige gezondheidsklachten uitleggen bij een apotheek. De focus ligt op veilige, praktische zinnen voor reizigers.",
  vocab: [{ pt: "farmácia", nl: "apotheek", ipa: "/fɐɾˈma.sjɐ/" }, { pt: "dor", nl: "pijn", ipa: "/doɾ/" }, { pt: "cabeça", nl: "hoofd", ipa: "/kɐˈbe.sɐ/" }, { pt: "estômago", nl: "maag", ipa: "/ɨʃˈtɔ.mɐ.ɡu/" }, { pt: "febre", nl: "koorts", ipa: "/ˈfɛ.bɾɨ/" }, { pt: "tosse", nl: "hoest", ipa: "/ˈto.sɨ/" }, { pt: "constipação", nl: "verkoudheid", ipa: "/kõʃ.ti.pɐˈsɐ̃w/" }, { pt: "medicamento", nl: "medicijn", ipa: "/mɨ.di.kɐˈmẽ.tu/" }, { pt: "receita", nl: "recept", ipa: "/ʁɨˈsɐj.tɐ/" }, { pt: "urgente", nl: "dringend", ipa: "/uɾˈʒẽ.tɨ/" }],
  phrases: [{ pt: "Tenho dor de cabeça.", nl: "Ik heb hoofdpijn.", ipa: "/ˈtɐ.ɲu doɾ dɨ kɐˈbe.sɐ/" }, { pt: "Tenho dor de estômago.", nl: "Ik heb buikpijn / maagpijn.", ipa: "/ˈtɐ.ɲu doɾ dɨ ɨʃˈtɔ.mɐ.ɡu/" }, { pt: "Tem algo para a tosse?", nl: "Heeft u iets tegen hoest?", ipa: "/tẽj ˈal.ɡu ˈpa.ɾɐ ɐ ˈto.sɨ/" }, { pt: "Preciso de um medicamento.", nl: "Ik heb een medicijn nodig.", ipa: "/pɾɨˈsi.zu dɨ ũ mɨ.di.kɐˈmẽ.tu/" }, { pt: "Preciso de receita?", nl: "Heb ik een recept nodig?", ipa: "/pɾɨˈsi.zu dɨ ʁɨˈsɐj.tɐ/" }, { pt: "É urgente.", nl: "Het is dringend.", ipa: "/ɛ uɾˈʒẽ.tɨ/" }],
  grammar: "Voor pijn gebruik je “tenho dor de...” gevolgd door het lichaamsdeel. “Tenho” betekent “ik heb”. Bij medische situaties is eenvoud belangrijk: zeg de klacht, vraag om hulp en vermeld allergieën als die er zijn.",
  practice: ["Zeg dat je hoofdpijn hebt.", "Vraag om iets tegen hoest.", "Vraag of je een recept nodig hebt.", "Zeg dat het dringend is.", "Maak een apotheekgesprek van vijf regels."]
},
{
  day: 18,
  title: "Noodgevallen en hulp vragen",
  titleNative: "Emergências e pedir ajuda",
  focus: "Je leert hulp vragen in onverwachte situaties. Deze zinnen zijn belangrijk bij verlies, ziekte, gevaar of verwarring.",
  vocab: [{ pt: "ajuda", nl: "hulp", ipa: "/ɐˈʒu.dɐ/" }, { pt: "polícia", nl: "politie", ipa: "/puˈli.sjɐ/" }, { pt: "hospital", nl: "ziekenhuis", ipa: "/uʃ.piˈtal/" }, { pt: "médico", nl: "dokter", ipa: "/ˈmɛ.di.ku/" }, { pt: "perdido", nl: "verdwaald / verloren", ipa: "/pɨɾˈdi.du/" }, { pt: "roubado", nl: "gestolen", ipa: "/ʁowˈba.du/" }, { pt: "telemóvel", nl: "mobiele telefoon", ipa: "/tɨ.lɨˈmɔ.vɛl/" }, { pt: "carteira", nl: "portemonnee", ipa: "/kaɾˈtɐj.ɾɐ/" }, { pt: "documento", nl: "document", ipa: "/du.kuˈmẽ.tu/" }, { pt: "emergência", nl: "noodgeval", ipa: "/ɨ.mɨɾˈʒẽ.sjɐ/" }],
  phrases: [{ pt: "Preciso de ajuda.", nl: "Ik heb hulp nodig.", ipa: "/pɾɨˈsi.zu dɨ ɐˈʒu.dɐ/" }, { pt: "Chame a polícia.", nl: "Bel de politie.", ipa: "/ˈʃa.mɨ ɐ puˈli.sjɐ/" }, { pt: "Preciso de um médico.", nl: "Ik heb een dokter nodig.", ipa: "/pɾɨˈsi.zu dɨ ũ ˈmɛ.di.ku/" }, { pt: "Estou perdido.", nl: "Ik ben verdwaald, gezegd door man.", ipa: "/ʃtow pɨɾˈdi.du/" }, { pt: "Estou perdida.", nl: "Ik ben verdwaald, gezegd door vrouw.", ipa: "/ʃtow pɨɾˈdi.dɐ/" }, { pt: "Roubaram a minha carteira.", nl: "Mijn portemonnee is gestolen.", ipa: "/ʁowˈba.ɾɐ̃w ɐ ˈmi.ɲɐ kaɾˈtɐj.ɾɐ/" }],
  grammar: "“Estou” betekent “ik ben” voor tijdelijke toestanden: verdwaald, ziek, moe of bezorgd. “Estou perdido/perdida” verandert met de spreker. In een noodgeval hoef je geen perfecte grammatica te gebruiken; duidelijke kernwoorden werken.",
  practice: ["Zeg dat je hulp nodig hebt.", "Vraag iemand de politie te bellen.", "Zeg dat je een dokter nodig hebt.", "Zeg dat je telefoon gestolen is.", "Oefen langzaam spreken in een stressvolle situatie."]
},
{
  day: 19,
  title: "In een museum in Belém",
  titleNative: "Num museu em Belém",
  focus: "Je leert vragen stellen bij een museum of bezienswaardigheid. Je oefent met tickets, openingstijden, kortingen en informatie.",
  vocab: [{ pt: "museu", nl: "museum", ipa: "/muˈzew/" }, { pt: "bilhete", nl: "ticket", ipa: "/biˈʎe.tɨ/" }, { pt: "entrada", nl: "ingang / toegang", ipa: "/ẽˈtɾa.dɐ/" }, { pt: "saída", nl: "uitgang", ipa: "/sɐˈi.dɐ/" }, { pt: "exposição", nl: "tentoonstelling", ipa: "/ɨʃ.pu.ziˈsɐ̃w/" }, { pt: "guia", nl: "gids", ipa: "/ˈɡi.ɐ/" }, { pt: "desconto", nl: "korting", ipa: "/dɨʃˈkõ.tu/" }, { pt: "estudante", nl: "student", ipa: "/ɨʃ.tuˈdɐ̃.tɨ/" }, { pt: "fotografia", nl: "foto", ipa: "/fu.tu.ɡɾɐˈfi.ɐ/" }, { pt: "proibido", nl: "verboden", ipa: "/pɾujˈbi.du/" }],
  phrases: [{ pt: "Queria um bilhete para o museu.", nl: "Ik wil graag een ticket voor het museum.", ipa: "/kɨˈɾi.ɐ ũ biˈʎe.tɨ ˈpa.ɾɐ u muˈzew/" }, { pt: "Há desconto para estudantes?", nl: "Is er studentenkorting?", ipa: "/a dɨʃˈkõ.tu ˈpa.ɾɐ ɨʃ.tuˈdɐ̃.tɨʃ/" }, { pt: "A exposição está aberta?", nl: "Is de tentoonstelling open?", ipa: "/ɐ ɨʃ.pu.ziˈsɐ̃w ʃta ɐˈbɛɾ.tɐ/" }, { pt: "Posso tirar fotografias?", nl: "Mag ik foto’s maken?", ipa: "/ˈpɔ.su tiˈɾaɾ fu.tu.ɡɾɐˈfi.ɐʃ/" }, { pt: "Onde é a saída?", nl: "Waar is de uitgang?", ipa: "/ˈõ.dɨ ɛ ɐ sɐˈi.dɐ/" }, { pt: "Tem guia em inglês?", nl: "Heeft u een gids in het Engels?", ipa: "/tẽj ˈɡi.ɐ ẽ ĩˈɡleʃ/" }],
  grammar: "“Há” is erg nuttig en betekent “er is” of “er zijn”. Je kunt ermee vragen: “Há desconto?”, “Há bilhetes?”, “Há guia?” Voor toestemming gebruik je opnieuw “Posso...?” zoals in “Posso tirar fotografias?”",
  practice: ["Vraag om een museumticket.", "Vraag of er korting is.", "Vraag of je foto’s mag maken.", "Vraag waar de uitgang is.", "Maak een museumgesprek met zes regels."]
},
{
  day: 20,
  title: "Praten over het weer",
  titleNative: "Falar sobre o tempo",
  focus: "Je leert eenvoudige zinnen over het weer. Dit helpt bij smalltalk, dagplanning en kiezen wat je gaat doen.",
  vocab: [{ pt: "tempo", nl: "weer / tijd", ipa: "/ˈtẽ.pu/" }, { pt: "sol", nl: "zon", ipa: "/sɔl/" }, { pt: "chuva", nl: "regen", ipa: "/ˈʃu.vɐ/" }, { pt: "vento", nl: "wind", ipa: "/ˈvẽ.tu/" }, { pt: "calor", nl: "hitte", ipa: "/kɐˈloɾ/" }, { pt: "frio", nl: "kou", ipa: "/ˈfɾi.u/" }, { pt: "nublado", nl: "bewolkt", ipa: "/nuˈbla.du/" }, { pt: "bonito", nl: "mooi", ipa: "/buˈni.tu/" }, { pt: "mau", nl: "slecht", ipa: "/maw/" }, { pt: "praia", nl: "strand", ipa: "/ˈpɾaj.ɐ/" }],
  phrases: [{ pt: "Está sol.", nl: "Het is zonnig.", ipa: "/ʃta sɔl/" }, { pt: "Está a chover.", nl: "Het regent.", ipa: "/ʃta ɐ ʃuˈveɾ/" }, { pt: "Está frio hoje.", nl: "Het is koud vandaag.", ipa: "/ʃta ˈfɾi.u ˈo.ʒɨ/" }, { pt: "Está muito calor.", nl: "Het is erg warm.", ipa: "/ʃta ˈmũj.tu kɐˈloɾ/" }, { pt: "O tempo está bonito.", nl: "Het weer is mooi.", ipa: "/u ˈtẽ.pu ʃta buˈni.tu/" }, { pt: "Vamos à praia?", nl: "Gaan we naar het strand?", ipa: "/ˈvɐ.muʃ a ˈpɾaj.ɐ/" }],
  grammar: "Voor het weer gebruik je vaak “está”: “Está frio”, “Está sol”, “Está a chover”. In Europees Portugees gebruikt men vaak “está a + werkwoord” voor iets dat nu gebeurt. “Está a chover” betekent letterlijk “het is aan het regenen”.",
  practice: ["Zeg dat het vandaag warm is.", "Zeg dat het regent.", "Vraag of iemand naar het strand wil.", "Beschrijf het weer buiten in het Portugees.", "Maak drie smalltalkzinnen over het weer."]
},
{
  day: 21,
  title: "Smalltalk met locals",
  titleNative: "Conversa informal com locais",
  focus: "Je leert eenvoudige sociale vragen stellen. Dit helpt bij vriendelijke gesprekken in cafés, winkels of tijdens een tour.",
  vocab: [{ pt: "local", nl: "local / plaatselijk persoon", ipa: "/luˈkal/" }, { pt: "cidade", nl: "stad", ipa: "/siˈda.dɨ/" }, { pt: "bonita", nl: "mooi, vrouwelijk", ipa: "/buˈni.tɐ/" }, { pt: "interessante", nl: "interessant", ipa: "/ĩ.tɨ.ɾɨˈsɐ̃.tɨ/" }, { pt: "trabalho", nl: "werk", ipa: "/tɾɐˈba.ʎu/" }, { pt: "família", nl: "familie", ipa: "/fɐˈmi.ljɐ/" }, { pt: "viagem", nl: "reis", ipa: "/viˈa.ʒɐ̃j/" }, { pt: "férias", nl: "vakantie", ipa: "/ˈfɛ.ɾjɐʃ/" }, { pt: "gostar", nl: "houden van / leuk vinden", ipa: "/ɡuʃˈtaɾ/" }, { pt: "morar", nl: "wonen", ipa: "/muˈɾaɾ/" }],
  phrases: [{ pt: "Gosto muito de Portugal.", nl: "Ik vind Portugal erg leuk.", ipa: "/ˈɡɔʃ.tu ˈmũj.tu dɨ puɾ.tuˈɡal/" }, { pt: "A cidade é muito bonita.", nl: "De stad is erg mooi.", ipa: "/ɐ siˈda.dɨ ɛ ˈmũj.tu buˈni.tɐ/" }, { pt: "Mora aqui?", nl: "Woont u hier?", ipa: "/ˈmɔ.ɾɐ ɐˈki/" }, { pt: "Estou de férias.", nl: "Ik ben op vakantie.", ipa: "/ʃtow dɨ ˈfɛ.ɾjɐʃ/" }, { pt: "É a minha primeira vez aqui.", nl: "Het is mijn eerste keer hier.", ipa: "/ɛ ɐ ˈmi.ɲɐ pɾiˈmɐj.ɾɐ veʃ ɐˈki/" }, { pt: "Recomenda algum lugar?", nl: "Raadt u een plek aan?", ipa: "/ʁɨ.kuˈmẽ.dɐ ɐlˈɡũ luˈɡaɾ/" }],
  grammar: "“Gosto de...” betekent “ik hou van” of “ik vind leuk”. In het Portugees heb je “de” nodig: “Gosto de Portugal”, “Gosto de café”. “Muito” kan na het werkwoord komen: “Gosto muito de...”",
  practice: ["Zeg dat je Portugal erg leuk vindt.", "Zeg dat je op vakantie bent.", "Vraag of iemand hier woont.", "Vraag om een lokale aanbeveling.", "Maak een smalltalkgesprek van acht korte regels."]
},
{
  day: 22,
  title: "Accommodatieproblemen oplossen",
  titleNative: "Resolver problemas no alojamento",
  focus: "Je leert problemen melden in een hotel of appartement. Je oefent met wifi, airco, geluid en kapotte dingen.",
  vocab: [{ pt: "problema", nl: "probleem", ipa: "/pɾuˈble.mɐ/" }, { pt: "internet", nl: "internet", ipa: "/ĩ.tɨɾˈnɛt/" }, { pt: "wifi", nl: "wifi", ipa: "/ˈwi.fi/" }, { pt: "ar condicionado", nl: "airconditioning", ipa: "/aɾ kõ.di.sjuˈna.du/" }, { pt: "chuveiro", nl: "douche", ipa: "/ʃuˈvɐj.ɾu/" }, { pt: "barulho", nl: "lawaai", ipa: "/bɐˈɾu.ʎu/" }, { pt: "janela", nl: "raam", ipa: "/ʒɐˈnɛ.lɐ/" }, { pt: "cama", nl: "bed", ipa: "/ˈka.mɐ/" }, { pt: "limpo", nl: "schoon", ipa: "/ˈlĩ.pu/" }, { pt: "partido", nl: "kapot", ipa: "/pɐɾˈti.du/" }],
  phrases: [{ pt: "Há um problema no quarto.", nl: "Er is een probleem in de kamer.", ipa: "/a ũ pɾuˈble.mɐ nu ˈkwaɾ.tu/" }, { pt: "O wifi não funciona.", nl: "De wifi werkt niet.", ipa: "/u ˈwi.fi nɐ̃w fũ.siˈo.nɐ/" }, { pt: "O chuveiro está partido.", nl: "De douche is kapot.", ipa: "/u ʃuˈvɐj.ɾu ʃta pɐɾˈti.du/" }, { pt: "Há muito barulho.", nl: "Er is veel lawaai.", ipa: "/a ˈmũj.tu bɐˈɾu.ʎu/" }, { pt: "Pode ajudar-me?", nl: "Kunt u mij helpen?", ipa: "/ˈpɔ.dɨ ɐ.ʒuˈdaɾ mɨ/" }, { pt: "Preciso de outro quarto.", nl: "Ik heb een andere kamer nodig.", ipa: "/pɾɨˈsi.zu dɨ ˈo.tɾu ˈkwaɾ.tu/" }],
  grammar: "“Não funciona” betekent “het werkt niet” en is enorm handig voor apparaten, wifi, kaarten en automaten. “Está partido” betekent dat iets kapot is. In Portugal kun je beleefd maar duidelijk zijn: probleem noemen, dan om hulp vragen.",
  practice: ["Zeg dat de wifi niet werkt.", "Meld dat de douche kapot is.", "Vraag om hulp bij de receptie.", "Vraag om een andere kamer.", "Maak een klacht in drie beleefde zinnen."]
},
{
  day: 23,
  title: "Een dagtocht plannen",
  titleNative: "Planear uma excursão",
  focus: "Je leert praten over dagtochten, tijden en vervoer. De scène past bij een trip naar Sintra, Cascais of de Dourovallei.",
  vocab: [{ pt: "excursão", nl: "excursie / dagtocht", ipa: "/ɨʃ.kuɾˈsɐ̃w/" }, { pt: "passeio", nl: "wandeling / uitstapje", ipa: "/pɐˈsɐj.u/" }, { pt: "castelo", nl: "kasteel", ipa: "/kɐʃˈtɛ.lu/" }, { pt: "praia", nl: "strand", ipa: "/ˈpɾaj.ɐ/" }, { pt: "montanha", nl: "berg", ipa: "/mõˈtɐ.ɲɐ/" }, { pt: "partida", nl: "vertrek", ipa: "/pɐɾˈti.dɐ/" }, { pt: "regresso", nl: "terugkeer", ipa: "/ʁɨˈɡɾe.su/" }, { pt: "incluído", nl: "inbegrepen", ipa: "/ĩ.kluˈi.du/" }, { pt: "guia", nl: "gids", ipa: "/ˈɡi.ɐ/" }, { pt: "grupo", nl: "groep", ipa: "/ˈɡɾu.pu/" }],
  phrases: [{ pt: "Queria reservar uma excursão.", nl: "Ik wil graag een excursie boeken.", ipa: "/kɨˈɾi.ɐ ʁɨ.zɨɾˈvaɾ ˈu.mɐ ɨʃ.kuɾˈsɐ̃w/" }, { pt: "A que horas é a partida?", nl: "Hoe laat is het vertrek?", ipa: "/ɐ kɨ ˈɔ.ɾɐʃ ɛ ɐ pɐɾˈti.dɐ/" }, { pt: "O transporte está incluído?", nl: "Is het vervoer inbegrepen?", ipa: "/u tɾɐ̃ʃˈpɔɾ.tɨ ʃta ĩ.kluˈi.du/" }, { pt: "Há guia em português?", nl: "Is er een gids in het Portugees?", ipa: "/a ˈɡi.ɐ ẽ puɾ.tuˈɡeʃ/" }, { pt: "Quando é o regresso?", nl: "Wanneer is de terugkeer?", ipa: "/ˈkwɐ̃.du ɛ u ʁɨˈɡɾe.su/" }, { pt: "O grupo é grande?", nl: "Is de groep groot?", ipa: "/u ˈɡɾu.pu ɛ ˈɡɾɐ̃.dɨ/" }],
  grammar: "“Quando” betekent “wanneer” en “a que horas” betekent “hoe laat”. Voor reisplanning gebruik je beide vaak. “Está incluído?” is handig om te checken of vervoer, lunch of tickets bij de prijs horen.",
  practice: ["Boek een excursie naar Sintra.", "Vraag hoe laat het vertrek is.", "Vraag of vervoer inbegrepen is.", "Vraag wanneer je terugkomt.", "Maak een reisbureaugesprek van zes regels."]
},
{
  day: 24,
  title: "Op het strand in de Algarve",
  titleNative: "Na praia no Algarve",
  focus: "Je leert woorden voor strand, veiligheid en eenvoudige verzoeken. Dit is handig aan de Algarve of bij stranden rond Cascais.",
  vocab: [{ pt: "praia", nl: "strand", ipa: "/ˈpɾaj.ɐ/" }, { pt: "mar", nl: "zee", ipa: "/maɾ/" }, { pt: "areia", nl: "zand", ipa: "/ɐˈɾɐj.ɐ/" }, { pt: "sol", nl: "zon", ipa: "/sɔl/" }, { pt: "guarda-sol", nl: "parasol", ipa: "/ˈɡwaɾ.dɐ sɔl/" }, { pt: "toalha", nl: "handdoek", ipa: "/tuˈa.ʎɐ/" }, { pt: "nadar", nl: "zwemmen", ipa: "/nɐˈdaɾ/" }, { pt: "perigoso", nl: "gevaarlijk", ipa: "/pɨ.ɾiˈɡo.zu/" }, { pt: "salvador", nl: "badmeester", ipa: "/sal.vɐˈdoɾ/" }, { pt: "protetor solar", nl: "zonnebrandcrème", ipa: "/pɾu.tɨˈtoɾ suˈlaɾ/" }],
  phrases: [{ pt: "A água está fria?", nl: "Is het water koud?", ipa: "/ɐ ˈa.ɡwɐ ʃta ˈfɾi.ɐ/" }, { pt: "É seguro nadar aqui?", nl: "Is het veilig om hier te zwemmen?", ipa: "/ɛ sɨˈɡu.ɾu nɐˈdaɾ ɐˈki/" }, { pt: "Queria alugar um guarda-sol.", nl: "Ik wil graag een parasol huren.", ipa: "/kɨˈɾi.ɐ ɐ.luˈɡaɾ ũ ˈɡwaɾ.dɐ sɔl/" }, { pt: "Onde fica o salvador?", nl: "Waar is de badmeester?", ipa: "/ˈõ.dɨ ˈfi.kɐ u sal.vɐˈdoɾ/" }, { pt: "Preciso de protetor solar.", nl: "Ik heb zonnebrandcrème nodig.", ipa: "/pɾɨˈsi.zu dɨ pɾu.tɨˈtoɾ suˈlaɾ/" }, { pt: "O mar está perigoso.", nl: "De zee is gevaarlijk.", ipa: "/u maɾ ʃta pɨ.ɾiˈɡo.zu/" }],
  grammar: "Voor veiligheid gebruik je “seguro” voor veilig en “perigoso” voor gevaarlijk. “É seguro...?” is een handige vraagvorm: “É seguro nadar aqui?” Je kunt “aqui” toevoegen om “hier” te zeggen.",
  practice: ["Vraag of het veilig is om te zwemmen.", "Vraag waar de badmeester is.", "Huur een parasol.", "Zeg dat de zee gevaarlijk is.", "Maak drie strandzinnen met “aqui”."]
},
{
  day: 25,
  title: "Culturele beleefdheid en uitnodigingen",
  titleNative: "Cortesia cultural e convites",
  focus: "Je leert uitnodigingen accepteren of vriendelijk weigeren. Dit helpt bij sociale situaties met locals, gidsen of nieuwe kennissen.",
  vocab: [{ pt: "convite", nl: "uitnodiging", ipa: "/kõˈvi.tɨ/" }, { pt: "jantar", nl: "diner", ipa: "/ʒɐ̃ˈtaɾ/" }, { pt: "almoço", nl: "lunch", ipa: "/alˈmɔ.su/" }, { pt: "café", nl: "koffie / café", ipa: "/kaˈfɛ/" }, { pt: "hoje", nl: "vandaag", ipa: "/ˈo.ʒɨ/" }, { pt: "amanhã", nl: "morgen", ipa: "/ɐ.mɐˈɲɐ̃/" }, { pt: "talvez", nl: "misschien", ipa: "/tɐlˈveʃ/" }, { pt: "claro", nl: "natuurlijk", ipa: "/ˈkla.ɾu/" }, { pt: "desculpa", nl: "sorry, informeel", ipa: "/dɨʃˈkul.pɐ/" }, { pt: "combinado", nl: "afgesproken", ipa: "/kõ.biˈna.du/" }],
  phrases: [{ pt: "Quer tomar um café?", nl: "Wilt u koffie drinken?", ipa: "/keɾ tuˈmaɾ ũ kaˈfɛ/" }, { pt: "Claro, obrigado.", nl: "Natuurlijk, bedankt.", ipa: "/ˈkla.ɾu obɾiˈɡa.du/" }, { pt: "Hoje não posso.", nl: "Vandaag kan ik niet.", ipa: "/ˈo.ʒɨ nɐ̃w ˈpɔ.su/" }, { pt: "Talvez amanhã.", nl: "Misschien morgen.", ipa: "/tɐlˈveʃ ɐ.mɐˈɲɐ̃/" }, { pt: "Obrigado pelo convite.", nl: "Bedankt voor de uitnodiging.", ipa: "/obɾiˈɡa.du ˈpe.lu kõˈvi.tɨ/" }, { pt: "Combinado.", nl: "Afgesproken.", ipa: "/kõ.biˈna.du/" }],
  grammar: "“Posso” betekent “ik kan” of “ik mag”. “Não posso” is een eenvoudige, beleefde manier om te weigeren zonder lange uitleg. “Combinado” is een natuurlijke manier om te zeggen dat iets is afgesproken.",
  practice: ["Accepteer een uitnodiging voor koffie.", "Weiger beleefd omdat je vandaag niet kunt.", "Stel morgen voor.", "Bedank iemand voor de uitnodiging.", "Maak een sociale dialoog van acht regels."]
},
{
  day: 26,
  title: "Meningen en voorkeuren",
  titleNative: "Opiniões e preferências",
  focus: "Je leert zeggen wat je leuk vindt, niet leuk vindt en liever doet. Dit helpt bij restaurants, plannen maken en gesprekken.",
  vocab: [{ pt: "gostar", nl: "leuk vinden", ipa: "/ɡuʃˈtaɾ/" }, { pt: "preferir", nl: "liever hebben", ipa: "/pɾɨ.fɨˈɾiɾ/" }, { pt: "adorar", nl: "geweldig vinden", ipa: "/ɐ.duˈɾaɾ/" }, { pt: "não gostar", nl: "niet leuk vinden", ipa: "/nɐ̃w ɡuʃˈtaɾ/" }, { pt: "música", nl: "muziek", ipa: "/ˈmu.zi.kɐ/" }, { pt: "comida", nl: "eten", ipa: "/kuˈmi.dɐ/" }, { pt: "vinho", nl: "wijn", ipa: "/ˈvi.ɲu/" }, { pt: "cerveja", nl: "bier", ipa: "/sɨɾˈvɐj.ʒɐ/" }, { pt: "tranquilo", nl: "rustig", ipa: "/tɾɐ̃ˈki.lu/" }, { pt: "animado", nl: "levendig", ipa: "/ɐ.niˈma.du/" }],
  phrases: [{ pt: "Gosto desta comida.", nl: "Ik vind dit eten lekker.", ipa: "/ˈɡɔʃ.tu ˈdeʃ.tɐ kuˈmi.dɐ/" }, { pt: "Não gosto de cerveja.", nl: "Ik hou niet van bier.", ipa: "/nɐ̃w ˈɡɔʃ.tu dɨ sɨɾˈvɐj.ʒɐ/" }, { pt: "Prefiro vinho.", nl: "Ik heb liever wijn.", ipa: "/pɾɨˈfi.ɾu ˈvi.ɲu/" }, { pt: "Adoro esta música.", nl: "Ik vind deze muziek geweldig.", ipa: "/ɐˈdɔ.ɾu ˈeʃ.tɐ ˈmu.zi.kɐ/" }, { pt: "Prefiro um lugar tranquilo.", nl: "Ik heb liever een rustige plek.", ipa: "/pɾɨˈfi.ɾu ũ luˈɡaɾ tɾɐ̃ˈki.lu/" }, { pt: "É muito animado aqui.", nl: "Het is hier erg levendig.", ipa: "/ɛ ˈmũj.tu ɐ.niˈma.du ɐˈki/" }],
  grammar: "Bij “gostar” gebruik je meestal “de”: “Gosto de vinho”, “Não gosto de cerveja”. Bij “preferir” heb je geen “de” nodig: “Prefiro vinho”. Dit verschil hoor je vaak in echte gesprekken.",
  practice: ["Zeg dat je dit eten lekker vindt.", "Zeg dat je niet van bier houdt.", "Zeg dat je liever wijn hebt.", "Beschrijf een plek als rustig of levendig.", "Maak vijf zinnen over je voorkeuren."]
},
{
  day: 27,
  title: "Bellen en berichten sturen",
  titleNative: "Telefonar e enviar mensagens",
  focus: "Je leert basiszinnen voor bellen, appen en contactgegevens delen. Dit is handig voor reserveringen, taxi’s en nieuwe contacten.",
  vocab: [{ pt: "telefone", nl: "telefoon", ipa: "/tɨ.lɨˈfo.nɨ/" }, { pt: "número", nl: "nummer", ipa: "/ˈnu.mɨ.ɾu/" }, { pt: "mensagem", nl: "bericht", ipa: "/mẽˈsa.ʒɐ̃j/" }, { pt: "ligar", nl: "bellen", ipa: "/liˈɡaɾ/" }, { pt: "enviar", nl: "sturen", ipa: "/ẽ.viˈaɾ/" }, { pt: "receber", nl: "ontvangen", ipa: "/ʁɨ.sɨˈbeɾ/" }, { pt: "email", nl: "e-mail", ipa: "/iˈmejl/" }, { pt: "contacto", nl: "contact", ipa: "/kõˈtak.tu/" }, { pt: "bateria", nl: "batterij", ipa: "/bɐ.tɨˈɾi.ɐ/" }, { pt: "carregador", nl: "oplader", ipa: "/kɐ.ʁɨ.ɡɐˈdoɾ/" }],
  phrases: [{ pt: "Qual é o seu número?", nl: "Wat is uw nummer?", ipa: "/kwal ɛ u sew ˈnu.mɨ.ɾu/" }, { pt: "Pode enviar uma mensagem?", nl: "Kunt u een bericht sturen?", ipa: "/ˈpɔ.dɨ ẽ.viˈaɾ ˈu.mɐ mẽˈsa.ʒɐ̃j/" }, { pt: "Vou ligar mais tarde.", nl: "Ik bel later.", ipa: "/vow liˈɡaɾ majʃ ˈtaɾ.dɨ/" }, { pt: "Não recebi o email.", nl: "Ik heb de e-mail niet ontvangen.", ipa: "/nɐ̃w ʁɨ.sɨˈbi u iˈmejl/" }, { pt: "A bateria acabou.", nl: "De batterij is leeg.", ipa: "/ɐ bɐ.tɨˈɾi.ɐ ɐ.kɐˈbow/" }, { pt: "Tem um carregador?", nl: "Heeft u een oplader?", ipa: "/tẽj ũ kɐ.ʁɨ.ɡɐˈdoɾ/" }],
  grammar: "“Vou + werkwoord” betekent “ik ga iets doen”: “Vou ligar” is “ik ga bellen” of “ik zal bellen”. Het is een eenvoudige manier om over de nabije toekomst te praten. Je kunt het gebruiken met veel werkwoorden: “vou pagar”, “vou esperar”, “vou reservar”.",
  practice: ["Vraag naar iemands telefoonnummer.", "Zeg dat je later belt.", "Zeg dat je de e-mail niet hebt ontvangen.", "Vraag om een oplader.", "Maak een korte app-conversatie in het Portugees."]
},
{
  day: 28,
  title: "Klachten en oplossingen",
  titleNative: "Reclamações e soluções",
  focus: "Je leert beleefd aangeven dat iets niet klopt. Dit helpt bij verkeerde bestellingen, kapotte producten of fouten op de rekening.",
  vocab: [{ pt: "erro", nl: "fout", ipa: "/ˈɛ.ʁu/" }, { pt: "errado", nl: "verkeerd", ipa: "/ɨˈʁa.du/" }, { pt: "certo", nl: "juist", ipa: "/ˈsɛɾ.tu/" }, { pt: "frio", nl: "koud", ipa: "/ˈfɾi.u/" }, { pt: "quente", nl: "warm", ipa: "/ˈkẽ.tɨ/" }, { pt: "trocar", nl: "ruilen", ipa: "/tɾuˈkaɾ/" }, { pt: "devolver", nl: "teruggeven", ipa: "/dɨ.vulˈveɾ/" }, { pt: "reembolso", nl: "terugbetaling", ipa: "/ʁɨ.ẽˈbol.su/" }, { pt: "esperar", nl: "wachten", ipa: "/ɨʃ.pɨˈɾaɾ/" }, { pt: "resolver", nl: "oplossen", ipa: "/ʁɨ.zulˈveɾ/" }],
  phrases: [{ pt: "Acho que há um erro.", nl: "Ik denk dat er een fout is.", ipa: "/ˈa.ʃu kɨ a ũ ˈɛ.ʁu/" }, { pt: "Isto está errado.", nl: "Dit is verkeerd.", ipa: "/ˈiʃ.tu ʃta ɨˈʁa.du/" }, { pt: "A comida está fria.", nl: "Het eten is koud.", ipa: "/ɐ kuˈmi.dɐ ʃta ˈfɾi.ɐ/" }, { pt: "Posso trocar isto?", nl: "Kan ik dit ruilen?", ipa: "/ˈpɔ.su tɾuˈkaɾ ˈiʃ.tu/" }, { pt: "Queria um reembolso.", nl: "Ik wil graag een terugbetaling.", ipa: "/kɨˈɾi.ɐ ũ ʁɨ.ẽˈbol.su/" }, { pt: "Pode resolver isto?", nl: "Kunt u dit oplossen?", ipa: "/ˈpɔ.dɨ ʁɨ.zulˈveɾ ˈiʃ.tu/" }],
  grammar: "“Acho que...” betekent “ik denk dat...” en maakt een klacht zachter. In plaats van direct “dit is fout” te zeggen, kun je beginnen met “Acho que há um erro.” Dat klinkt beleefd, maar nog steeds duidelijk.",
  practice: ["Zeg dat je denkt dat er een fout is.", "Meld dat het eten koud is.", "Vraag of je iets kunt ruilen.", "Vraag om een terugbetaling.", "Maak een beleefde klacht van vier zinnen."]
},
{
  day: 29,
  title: "Lokale aanbevelingen vragen",
  titleNative: "Pedir recomendações locais",
  focus: "Je leert vragen naar goede plekken om te eten, drinken of bezoeken. Dit helpt om minder toeristische ervaringen te vinden.",
  vocab: [{ pt: "recomendação", nl: "aanbeveling", ipa: "/ʁɨ.ku.mẽ.dɐˈsɐ̃w/" }, { pt: "lugar", nl: "plek", ipa: "/luˈɡaɾ/" }, { pt: "restaurante", nl: "restaurant", ipa: "/ʁɨʃ.tɐwˈɾɐ̃.tɨ/" }, { pt: "bar", nl: "bar", ipa: "/baɾ/" }, { pt: "miradouro", nl: "uitzichtpunt", ipa: "/mi.ɾɐˈdoɾ.u/" }, { pt: "bairro", nl: "wijk", ipa: "/ˈbaj.ʁu/" }, { pt: "local", nl: "lokaal", ipa: "/luˈkal/" }, { pt: "turístico", nl: "toeristisch", ipa: "/tuˈɾiʃ.ti.ku/" }, { pt: "autêntico", nl: "authentiek", ipa: "/awˈtẽ.ti.ku/" }, { pt: "especial", nl: "bijzonder", ipa: "/ɨʃ.pɨ.siˈal/" }],
  phrases: [{ pt: "Recomenda algum restaurante?", nl: "Raadt u een restaurant aan?", ipa: "/ʁɨ.kuˈmẽ.dɐ ɐlˈɡũ ʁɨʃ.tɐwˈɾɐ̃.tɨ/" }, { pt: "Quero algo local.", nl: "Ik wil iets lokaals.", ipa: "/ˈkɛ.ɾu ˈal.ɡu luˈkal/" }, { pt: "Não muito turístico.", nl: "Niet erg toeristisch.", ipa: "/nɐ̃w ˈmũj.tu tuˈɾiʃ.ti.ku/" }, { pt: "Há um bom miradouro?", nl: "Is er een goed uitzichtpunt?", ipa: "/a ũ bõ mi.ɾɐˈdoɾ.u/" }, { pt: "Qual é o seu lugar favorito?", nl: "Wat is uw favoriete plek?", ipa: "/kwal ɛ u sew luˈɡaɾ fɐ.vuˈɾi.tu/" }, { pt: "Parece especial.", nl: "Het lijkt bijzonder.", ipa: "/pɐˈɾe.sɨ ɨʃ.pɨ.siˈal/" }],
  grammar: "“Algum” betekent “een of ander” of “een”. In vragen klinkt het natuurlijk: “Recomenda algum restaurante?” “Bom” betekent goed, maar vóór een mannelijk zelfstandig naamwoord verandert het vaak naar “bom”: “um bom miradouro”.",
  practice: ["Vraag om een restaurantaanbeveling.", "Zeg dat je iets lokaals wilt.", "Vraag naar een uitzichtpunt.", "Vraag naar iemands favoriete plek.", "Maak een gesprek met een local over verborgen plekken."]
},
{
  day: 30,
  title: "Een volledige reisdag in Portugal",
  titleNative: "Um dia completo de viagem em Portugal",
  focus: "Je combineert alles: groeten, bestellen, reizen, vragen stellen, betalen en smalltalk. Dit is een praktische afsluiting voor een dag in Lissabon, Porto of Coimbra.",
  vocab: [{ pt: "dia", nl: "dag", ipa: "/ˈdi.ɐ/" }, { pt: "plano", nl: "plan", ipa: "/ˈpla.nu/" }, { pt: "viagem", nl: "reis", ipa: "/viˈa.ʒɐ̃j/" }, { pt: "cidade", nl: "stad", ipa: "/siˈda.dɨ/" }, { pt: "café", nl: "café / koffie", ipa: "/kaˈfɛ/" }, { pt: "almoço", nl: "lunch", ipa: "/alˈmɔ.su/" }, { pt: "bilhete", nl: "ticket", ipa: "/biˈʎe.tɨ/" }, { pt: "reserva", nl: "reservering", ipa: "/ʁɨˈzɛɾ.vɐ/" }, { pt: "ajuda", nl: "hulp", ipa: "/ɐˈʒu.dɐ/" }, { pt: "obrigado", nl: "bedankt", ipa: "/obɾiˈɡa.du/" }],
  phrases: [{ pt: "Hoje tenho muitos planos.", nl: "Vandaag heb ik veel plannen.", ipa: "/ˈo.ʒɨ ˈtɐ.ɲu ˈmũj.tuʃ ˈpla.nuʃ/" }, { pt: "Primeiro quero um café.", nl: "Eerst wil ik koffie.", ipa: "/pɾiˈmɐj.ɾu ˈkɛ.ɾu ũ kaˈfɛ/" }, { pt: "Depois vou ao museu.", nl: "Daarna ga ik naar het museum.", ipa: "/dɨˈpojʃ vow aw muˈzew/" }, { pt: "Tenho uma reserva para jantar.", nl: "Ik heb een reservering voor het diner.", ipa: "/ˈtɐ.ɲu ˈu.mɐ ʁɨˈzɛɾ.vɐ ˈpa.ɾɐ ʒɐ̃ˈtaɾ/" }, { pt: "Pode ajudar-me, por favor?", nl: "Kunt u mij helpen, alstublieft?", ipa: "/ˈpɔ.dɨ ɐ.ʒuˈdaɾ mɨ puɾ faˈvoɾ/" }, { pt: "Foi um dia muito bom.", nl: "Het was een erg goede dag.", ipa: "/foj ũ ˈdi.ɐ ˈmũj.tu bõ/" }],
  grammar: "Je kunt de toekomst eenvoudig maken met “vou + werkwoord”: “vou ao museu”, “vou pagar”, “vou reservar”. Voor een hele reisdag zijn verbindingswoorden handig: “primeiro” betekent eerst, “depois” betekent daarna. Met deze structuur kun je simpele maar natuurlijke plannen uitleggen.",
  practice: ["Beschrijf je ochtend in drie Portugese zinnen.", "Bestel koffie en vraag daarna de weg naar een museum.", "Zeg dat je een reservering voor het diner hebt.", "Vraag beleefd om hulp bij een probleem.", "Schrijf een volledige reisdag van vijf korte zinnen in het Portugees."]
}
];

var CONVERSATIONS_NL_PT = [
{ title: "Koffie bestellen in een café", scene: "Je bent in een klein café in Lissabon in de ochtend. De medewerker groet je en je bestelt koffie en iets kleins om te eten.", lines: [{ who: "them", pt: "Bom dia, o que deseja?", nl: "Goedemorgen, wat wenst u?" }, { who: "you", pt: "Bom dia, queria um café, por favor.", nl: "Goedemorgen, ik wil graag een koffie, alstublieft." }, { who: "them", pt: "Claro, quer açúcar?", nl: "Natuurlijk, wilt u suiker?" }, { who: "you", pt: "Não, obrigado.", nl: "Nee, bedankt." }, { who: "them", pt: "Quer mais alguma coisa?", nl: "Wilt u nog iets anders?" }, { who: "you", pt: "Sim, uma sanduíche de queijo, por favor.", nl: "Ja, een sandwich met kaas, alstublieft." }, { who: "them", pt: "Para aqui ou para levar?", nl: "Voor hier of om mee te nemen?" }, { who: "you", pt: "Para aqui.", nl: "Voor hier." }, { who: "them", pt: "São cinco euros.", nl: "Dat is vijf euro." }, { who: "you", pt: "Posso pagar com cartão?", nl: "Kan ik met kaart betalen?" }, { who: "them", pt: "Sim, claro.", nl: "Ja, natuurlijk." }, { who: "you", pt: "Obrigado, tenha um bom dia.", nl: "Bedankt, fijne dag." }] },
{ title: "Inchecken bij het hotel", scene: "Je komt aan bij een hotel in Porto. Je hebt online gereserveerd en wilt weten waar je kamer en het ontbijt zijn.", lines: [{ who: "them", pt: "Boa tarde, bem-vindo ao hotel.", nl: "Goedemiddag, welkom in het hotel." }, { who: "you", pt: "Boa tarde, tenho uma reserva.", nl: "Goedemiddag, ik heb een reservering." }, { who: "them", pt: "Qual é o seu nome?", nl: "Wat is uw naam?" }, { who: "you", pt: "O meu nome é Anna de Vries.", nl: "Mijn naam is Anna de Vries." }, { who: "them", pt: "Pode mostrar o passaporte, por favor?", nl: "Kunt u het paspoort laten zien, alstublieft?" }, { who: "you", pt: "Claro, aqui está.", nl: "Natuurlijk, hier is het." }, { who: "them", pt: "O seu quarto é o número 204.", nl: "Uw kamer is nummer 204." }, { who: "you", pt: "Onde fica o elevador?", nl: "Waar is de lift?" }, { who: "them", pt: "Fica à direita, ao fundo.", nl: "Die is rechts, achterin." }, { who: "you", pt: "O pequeno-almoço está incluído?", nl: "Is het ontbijt inbegrepen?" }, { who: "them", pt: "Sim, das sete às dez.", nl: "Ja, van zeven tot tien." }, { who: "you", pt: "Muito obrigado.", nl: "Hartelijk bedankt." }] },
{ title: "De weg vragen naar het station", scene: "Je bent in Coimbra en zoekt het treinstation. Je spreekt iemand op straat beleefd aan en vraagt om een simpele route.", lines: [{ who: "you", pt: "Desculpe, pode ajudar-me?", nl: "Pardon, kunt u mij helpen?" }, { who: "them", pt: "Claro, diga.", nl: "Natuurlijk, zegt u het maar." }, { who: "you", pt: "Onde fica a estação de comboios?", nl: "Waar is het treinstation?" }, { who: "them", pt: "Fica perto daqui.", nl: "Het is dichtbij hier." }, { who: "you", pt: "É para a direita ou para a esquerda?", nl: "Is het naar rechts of naar links?" }, { who: "them", pt: "Siga em frente e vire à esquerda.", nl: "Ga rechtdoor en sla linksaf." }, { who: "you", pt: "Depois é longe?", nl: "Is het daarna ver?" }, { who: "them", pt: "Não, são cinco minutos a pé.", nl: "Nee, het is vijf minuten lopen." }, { who: "you", pt: "Pode mostrar no mapa?", nl: "Kunt u het op de kaart laten zien?" }, { who: "them", pt: "Sim, está aqui.", nl: "Ja, het is hier." }, { who: "you", pt: "Muito obrigada pela ajuda.", nl: "Hartelijk bedankt voor de hulp." }, { who: "them", pt: "De nada, boa viagem.", nl: "Graag gedaan, goede reis." }] },
{ title: "Eten in een restaurant", scene: "Je zit in een restaurant in Porto. Je vraagt om het menu, bestelt een gerecht en controleert of er melk in de saus zit.", lines: [{ who: "them", pt: "Boa noite, tem reserva?", nl: "Goedenavond, heeft u een reservering?" }, { who: "you", pt: "Sim, tenho uma reserva para duas pessoas.", nl: "Ja, ik heb een reservering voor twee personen." }, { who: "them", pt: "Perfeito, esta é a sua mesa.", nl: "Perfect, dit is uw tafel." }, { who: "you", pt: "Pode trazer a ementa, por favor?", nl: "Kunt u het menu brengen, alstublieft?" }, { who: "them", pt: "Claro, aqui está.", nl: "Natuurlijk, hier is het." }, { who: "you", pt: "Queria o peixe, por favor.", nl: "Ik wil graag de vis, alstublieft." }, { who: "them", pt: "Muito bem, quer entrada?", nl: "Heel goed, wilt u een voorgerecht?" }, { who: "you", pt: "Não, obrigado, mas o molho tem leite?", nl: "Nee, bedankt, maar zit er melk in de saus?" }, { who: "them", pt: "Não, o molho não tem leite.", nl: "Nee, de saus bevat geen melk." }, { who: "you", pt: "Ótimo, então queria esse prato.", nl: "Prima, dan wil ik dat gerecht." }, { who: "them", pt: "Claro, já trago.", nl: "Natuurlijk, ik breng het zo." }, { who: "you", pt: "Obrigado.", nl: "Bedankt." }] },
{ title: "Treinkaartjes kopen", scene: "Je bent op station Santa Apolónia in Lissabon. Je wilt een kaartje naar Porto kopen en vraagt naar vertrektijd en perron.", lines: [{ who: "them", pt: "Bom dia, em que posso ajudar?", nl: "Goedemorgen, waarmee kan ik helpen?" }, { who: "you", pt: "Queria um bilhete para o Porto.", nl: "Ik wil graag een kaartje naar Porto." }, { who: "them", pt: "Só ida ou ida e volta?", nl: "Alleen heen of heen en terug?" }, { who: "you", pt: "Ida e volta, por favor.", nl: "Heen en terug, alstublieft." }, { who: "them", pt: "Para hoje?", nl: "Voor vandaag?" }, { who: "you", pt: "Sim, para hoje de manhã.", nl: "Ja, voor vanochtend." }, { who: "them", pt: "O próximo comboio sai às dez.", nl: "De volgende trein vertrekt om tien uur." }, { who: "you", pt: "De que linha sai?", nl: "Van welk spoor vertrekt hij?" }, { who: "them", pt: "Sai da linha três.", nl: "Hij vertrekt van spoor drie." }, { who: "you", pt: "Quanto custa?", nl: "Hoeveel kost het?" }, { who: "them", pt: "São trinta euros.", nl: "Dat is dertig euro." }, { who: "you", pt: "Posso pagar com cartão?", nl: "Kan ik met kaart betalen?" }] },
{ title: "Winkelen voor kleding", scene: "Je bent in een kledingwinkel in Chiado. Je ziet een overhemd dat je leuk vindt, maar je wilt een andere maat en kleur proberen.", lines: [{ who: "them", pt: "Boa tarde, precisa de ajuda?", nl: "Goedemiddag, heeft u hulp nodig?" }, { who: "you", pt: "Sim, gosto desta camisa.", nl: "Ja, ik vind dit overhemd mooi." }, { who: "them", pt: "Quer experimentar?", nl: "Wilt u het passen?" }, { who: "you", pt: "Sim, posso experimentar?", nl: "Ja, mag ik het passen?" }, { who: "them", pt: "Claro, o provador fica ali.", nl: "Natuurlijk, de paskamer is daar." }, { who: "you", pt: "Tem este tamanho em azul?", nl: "Heeft u deze maat in blauw?" }, { who: "them", pt: "Vou verificar.", nl: "Ik ga het controleren." }, { who: "you", pt: "Obrigado.", nl: "Bedankt." }, { who: "them", pt: "Sim, temos em azul.", nl: "Ja, we hebben het in blauw." }, { who: "you", pt: "Ótimo, quanto custa?", nl: "Geweldig, hoeveel kost het?" }, { who: "them", pt: "Custa vinte euros.", nl: "Het kost twintig euro." }, { who: "you", pt: "Vou levar.", nl: "Ik neem het." }] },
{ title: "Bij de apotheek", scene: "Je voelt je niet goed tijdens je reis in Faro. Je gaat naar een apotheek en legt je klacht eenvoudig uit.", lines: [{ who: "them", pt: "Boa tarde, em que posso ajudar?", nl: "Goedemiddag, waarmee kan ik helpen?" }, { who: "you", pt: "Boa tarde, tenho dor de cabeça.", nl: "Goedemiddag, ik heb hoofdpijn." }, { who: "them", pt: "Tem febre?", nl: "Heeft u koorts?" }, { who: "you", pt: "Não, não tenho febre.", nl: "Nee, ik heb geen koorts." }, { who: "them", pt: "Tem alergias?", nl: "Heeft u allergieën?" }, { who: "you", pt: "Sim, tenho alergia a amendoim.", nl: "Ja, ik ben allergisch voor pinda’s." }, { who: "them", pt: "Entendo, vou recomendar este medicamento.", nl: "Ik begrijp het, ik zal dit medicijn aanbevelen." }, { who: "you", pt: "Preciso de receita?", nl: "Heb ik een recept nodig?" }, { who: "them", pt: "Não, não precisa.", nl: "Nee, dat is niet nodig." }, { who: "you", pt: "Como devo tomar?", nl: "Hoe moet ik het innemen?" }, { who: "them", pt: "Com água, depois de comer.", nl: "Met water, na het eten." }, { who: "you", pt: "Obrigado pela ajuda.", nl: "Bedankt voor de hulp." }] },
{ title: "Smalltalk met een local", scene: "Je zit op een terras in Braga en raakt in gesprek met iemand uit de stad. Je vertelt dat je op vakantie bent en vraagt om een lokale aanbeveling.", lines: [{ who: "you", pt: "Olá, mora aqui em Braga?", nl: "Hallo, woont u hier in Braga?" }, { who: "them", pt: "Sim, moro aqui há muitos anos.", nl: "Ja, ik woon hier al vele jaren." }, { who: "you", pt: "A cidade é muito bonita.", nl: "De stad is erg mooi." }, { who: "them", pt: "Obrigado, gosta de Portugal?", nl: "Dank u, vindt u Portugal leuk?" }, { who: "you", pt: "Sim, gosto muito de Portugal.", nl: "Ja, ik vind Portugal erg leuk." }, { who: "them", pt: "Está de férias?", nl: "Bent u op vakantie?" }, { who: "you", pt: "Sim, é a minha primeira vez aqui.", nl: "Ja, het is mijn eerste keer hier." }, { who: "them", pt: "Que bom, já visitou o centro histórico?", nl: "Wat leuk, heeft u het historische centrum al bezocht?" }, { who: "you", pt: "Ainda não, recomenda algum lugar?", nl: "Nog niet, raadt u een plek aan?" }, { who: "them", pt: "Sim, visite o Bom Jesus do Monte.", nl: "Ja, bezoek Bom Jesus do Monte." }, { who: "you", pt: "Parece especial, obrigado pela recomendação.", nl: "Dat lijkt bijzonder, bedankt voor de aanbeveling." }, { who: "them", pt: "De nada, aproveite a viagem.", nl: "Graag gedaan, geniet van de reis." }] }
];
