// course-sw-pt.js
// Source: Swahili | Target: Portuguese
const COURSE_DATA = {
  src: 'sw',
  tgt: 'pt',
  srcName: 'Swahili',
  tgtName: 'Portuguese',
  srcFlag: '🇰🇪',
  tgtFlag: '🇵🇹',
  days: [
    {
      day: 1,
      title: `Salamu za kwanza`,
      titleNative: `Primeiros cumprimentos`,
      focus: `Leo unajifunza salamu rahisi unazoweza kutumia ukifika Lisbon, Porto, au Maputo. Lengo ni kuanza mazungumzo kwa heshima na kuonyesha urafiki bila kutumia sentensi ndefu.`,
      grammar: `Kwa Kireno, “obrigado” hutumiwa na mwanaume anayesema, na “obrigada” hutumiwa na mwanamke anayesema. Hii haibadiliki kulingana na mtu unayemshukuru, bali kulingana na wewe msemaji. Katika hali nyingi za kusafiri, “por favor” na “desculpe” zinaweza kufanya mazungumzo yawe ya heshima hata ukiwa bado hujui maneno mengi.`,
      vocab: [
        {tgt:`olá`,src:`hujambo`,pron:`o-LA`},
        {tgt:`bom dia`,src:`habari za asubuhi`,pron:`bom JI-a`},
        {tgt:`boa tarde`,src:`habari za mchana/jioni`,pron:`BO-a TAR-dji`},
        {tgt:`boa noite`,src:`habari za usiku`,pron:`BO-a NOI-tshi`},
        {tgt:`tchau`,src:`kwaheri`,pron:`CHAU`},
        {tgt:`por favor`,src:`tafadhali`,pron:`por fa-VOR`},
        {tgt:`obrigado`,src:`asante, msemaji wa kiume`,pron:`o-bri-GA-du`},
        {tgt:`obrigada`,src:`asante, msemaji wa kike`,pron:`o-bri-GA-da`},
        {tgt:`sim`,src:`ndiyo`,pron:`sing`},
        {tgt:`não`,src:`hapana`,pron:`nau`},
        {tgt:`desculpe`,src:`samahani`,pron:`des-KUL-pi`},
      ],
      phrases: [
        {tgt:`Olá, bom dia.`,src:`Hujambo, habari za asubuhi.`,pron:`o-LA, bom JI-a`},
        {tgt:`Boa tarde, tudo bem?`,src:`Habari za mchana, uko sawa?`,pron:`BO-a TAR-dji, TU-du beng`},
        {tgt:`Muito obrigado.`,src:`Asante sana, msemaji wa kiume.`,pron:`MUI-tu o-bri-GA-du`},
        {tgt:`Muito obrigada.`,src:`Asante sana, msemaji wa kike.`,pron:`MUI-tu o-bri-GA-da`},
        {tgt:`Por favor, desculpe.`,src:`Tafadhali, samahani.`,pron:`por fa-VOR, des-KUL-pi`},
        {tgt:`Tchau, boa noite.`,src:`Kwaheri, usiku mwema.`,pron:`CHAU, BO-a NOI-tshi`},
      ],
      conversation: [
      ],
    },
    {
      day: 2,
      title: `Kujitambulisha`,
      titleNative: `Apresentar-se`,
      focus: `Leo unajifunza kusema jina lako na kuuliza jina la mtu mwingine. Hii ni muhimu unapokutana na mwenyeji, dereva, au mfanyakazi wa mapokezi nchini Portugal au Angola.`,
      grammar: `Kireno kina jinsia ya maneno: baadhi ya maneno ni ya kiume, baadhi ya kike. “Nome” ni neno la kiume, hivyo unasema “meu nome,” si “minha nome.” Kwa mtalii, unaweza kutumia “eu sou turista” bila kubadilisha sana kwa sababu “turista” hutumika kwa watu wa jinsia zote.`,
      vocab: [
        {tgt:`nome`,src:`jina`,pron:`NO-mi`},
        {tgt:`meu`,src:`wangu, yangu kwa kiume`,pron:`meu`},
        {tgt:`minha`,src:`wangu, yangu kwa kike`,pron:`MI-nya`},
        {tgt:`eu`,src:`mimi`,pron:`eu`},
        {tgt:`você`,src:`wewe`,pron:`vo-SE`},
        {tgt:`sou`,src:`mimi ni`,pron:`sou`},
        {tgt:`é`,src:`ni`,pron:`e`},
        {tgt:`prazer`,src:`furaha kukutana`,pron:`pra-ZER`},
        {tgt:`amigo`,src:`rafiki wa kiume`,pron:`a-MI-gu`},
        {tgt:`amiga`,src:`rafiki wa kike`,pron:`a-MI-ga`},
      ],
      phrases: [
        {tgt:`Meu nome é João.`,src:`Jina langu ni João.`,pron:`meu NO-mi e zhu-AU`},
        {tgt:`Minha nome não, meu nome.`,src:`Si “minha nome,” ni “meu nome.”`,pron:`MI-nya NO-mi nau, meu NO-mi`},
        {tgt:`Eu sou turista.`,src:`Mimi ni mtalii.`,pron:`eu sou tu-RIS-ta`},
        {tgt:`Qual é o seu nome?`,src:`Jina lako ni nani?`,pron:`kwal e u seu NO-mi`},
        {tgt:`Prazer em conhecer você.`,src:`Furaha kukufahamu.`,pron:`pra-ZER eng ko-nye-SER vo-SE`},
        {tgt:`Você é daqui?`,src:`Wewe ni wa hapa?`,pron:`vo-SE e da-KI`},
      ],
      conversation: [
      ],
    },
    {
      day: 3,
      title: `Maneno ya heshima na kuomba msamaha`,
      titleNative: `Palavras de cortesia e desculpas`,
      focus: `Leo unajifunza maneno ya heshima yatakayokusaidia sokoni, kituo cha basi, au kwenye lifti ya hoteli. Ukarimu na sauti ya heshima ni muhimu sana katika nchi nyingi zinazozungumza Kireno.`,
      grammar: `“Desculpe” ni salama kutumia katika hali nyingi rasmi au unapoongea na mtu usiyemjua. “Desculpa” ni la kawaida zaidi kati ya marafiki au watu wa karibu. Katika mazingira ya kusafiri, tumia “desculpe” kwanza ili kuonekana mwenye heshima.`,
      vocab: [
        {tgt:`com licença`,src:`samahani, naomba kupita`,pron:`kong li-SEN-sa`},
        {tgt:`desculpa`,src:`samahani kwa karibu/kawaida`,pron:`des-KUL-pa`},
        {tgt:`desculpe`,src:`samahani kwa heshima`,pron:`des-KUL-pi`},
        {tgt:`perdão`,src:`samahani, msamaha`,pron:`per-DAU`},
        {tgt:`de nada`,src:`karibu, usijali`,pron:`dji NA-da`},
        {tgt:`obrigado mesmo`,src:`asante sana kweli`,pron:`o-bri-GA-du MEZ-mu`},
        {tgt:`por nada`,src:`hakuna shida`,pron:`por NA-da`},
        {tgt:`claro`,src:`bila shaka`,pron:`KLA-ru`},
        {tgt:`tudo bem`,src:`kila kitu sawa`,pron:`TU-du beng`},
        {tgt:`sem problema`,src:`hakuna tatizo`,pron:`seng pro-BLE-ma`},
      ],
      phrases: [
        {tgt:`Com licença, posso passar?`,src:`Samahani, naweza kupita?`,pron:`kong li-SEN-sa, PO-su pa-SAR`},
        {tgt:`Desculpe, não entendo.`,src:`Samahani, sielewi.`,pron:`des-KUL-pi, nau eng-TEN-du`},
        {tgt:`Muito obrigado pela ajuda.`,src:`Asante sana kwa msaada.`,pron:`MUI-tu o-bri-GA-du PE-la a-ZHU-da`},
        {tgt:`De nada, tudo bem.`,src:`Karibu, kila kitu sawa.`,pron:`dji NA-da, TU-du beng`},
        {tgt:`Sem problema.`,src:`Hakuna tatizo.`,pron:`seng pro-BLE-ma`},
        {tgt:`Claro, por favor.`,src:`Bila shaka, tafadhali.`,pron:`KLA-ru, por fa-VOR`},
      ],
      conversation: [
      ],
    },
    {
      day: 4,
      title: `Nambari 0 hadi 20`,
      titleNative: `Números de zero a vinte`,
      focus: `Leo unajifunza nambari za msingi kwa ajili ya bei, vyumba vya hoteli, muda, na tiketi. Nambari hizi zitakusaidia sana ukiwa kwenye soko la Luanda au café ya Porto.`,
      grammar: `Nambari “um” inaweza kubadilika kuwa “uma” ikiwa kitu ni cha kike, kama “uma mala” kwa begi moja. Lakini kwa mwanzo, unaweza kujifunza kwanza sauti na maana. Kadri unavyoendelea, utaona nambari zikikubaliana na jinsia ya nomino.`,
      vocab: [
        {tgt:`zero`,src:`sifuri`,pron:`ZE-ru`},
        {tgt:`um`,src:`moja`,pron:`ung`},
        {tgt:`dois`,src:`mbili`,pron:`doish`},
        {tgt:`três`,src:`tatu`,pron:`tresh`},
        {tgt:`quatro`,src:`nne`,pron:`KWA-tru`},
        {tgt:`cinco`,src:`tano`,pron:`SIN-ku`},
        {tgt:`seis`,src:`sita`,pron:`seish`},
        {tgt:`sete`,src:`saba`,pron:`SE-tshi`},
        {tgt:`oito`,src:`nane`,pron:`OI-tu`},
        {tgt:`nove`,src:`tisa`,pron:`NO-vi`},
        {tgt:`dez`,src:`kumi`,pron:`dezh`},
        {tgt:`vinte`,src:`ishirini`,pron:`VIN-tshi`},
      ],
      phrases: [
        {tgt:`Um café, por favor.`,src:`Kahawa moja, tafadhali.`,pron:`ung ka-FE, por fa-VOR`},
        {tgt:`Dois bilhetes, por favor.`,src:`Tiketi mbili, tafadhali.`,pron:`doish bi-LYE-tshis, por fa-VOR`},
        {tgt:`Tenho três malas.`,src:`Nina mabegi matatu.`,pron:`TE-nyu tresh MA-lash`},
        {tgt:`O quarto é número cinco.`,src:`Chumba ni nambari tano.`,pron:`u KWAR-tu e NU-me-ru SIN-ku`},
        {tgt:`São dez euros.`,src:`Ni euro kumi.`,pron:`sau dezh EU-rush`},
        {tgt:`Vinte minutos.`,src:`Dakika ishirini.`,pron:`VIN-tshi mi-NU-tush`},
      ],
      conversation: [
      ],
    },
    {
      day: 5,
      title: `Kuuliza bei na kulipa`,
      titleNative: `Perguntar preços e pagar`,
      focus: `Leo unajifunza kuuliza bei dukani au sokoni. Hii ni muhimu unaponunua maji, tiketi, zawadi, au chakula cha haraka Lisbon, Praia, au Maputo.`,
      grammar: `Kwa kuuliza bei, “Quanto custa?” ni swali la moja kwa moja na linafaa karibu kila mahali. Ikiwa unauliza vitu vingi, unaweza kusikia “Quanto custam?” lakini kama mtalii, “Quanto custa?” bado mara nyingi itaeleweka. “Com cartão” humaanisha “kwa kadi.”`,
      vocab: [
        {tgt:`quanto`,src:`kiasi gani`,pron:`KWAN-tu`},
        {tgt:`custa`,src:`inagharimu`,pron:`KUSH-ta`},
        {tgt:`preço`,src:`bei`,pron:`PRE-su`},
        {tgt:`dinheiro`,src:`pesa taslimu`,pron:`dji-NYEI-ru`},
        {tgt:`cartão`,src:`kadi`,pron:`kar-TAU`},
        {tgt:`euro`,src:`euro`,pron:`EU-ru`},
        {tgt:`troco`,src:`chenji`,pron:`TRO-ku`},
        {tgt:`barato`,src:`bei nafuu`,pron:`ba-RA-tu`},
        {tgt:`caro`,src:`ghali`,pron:`KA-ru`},
        {tgt:`recibo`,src:`risiti`,pron:`re-SI-bu`},
      ],
      phrases: [
        {tgt:`Quanto custa?`,src:`Inagharimu kiasi gani?`,pron:`KWAN-tu KUSH-ta`},
        {tgt:`Posso pagar com cartão?`,src:`Naweza kulipa kwa kadi?`,pron:`PO-su pa-GAR kong kar-TAU`},
        {tgt:`Só tenho dinheiro.`,src:`Nina pesa taslimu tu.`,pron:`so TE-nyu dji-NYEI-ru`},
        {tgt:`Tem troco?`,src:`Una chenji?`,pron:`teng TRO-ku`},
        {tgt:`É muito caro.`,src:`Ni ghali sana.`,pron:`e MUI-tu KA-ru`},
        {tgt:`Pode dar recibo?`,src:`Unaweza kutoa risiti?`,pron:`PO-dji dar re-SI-bu`},
      ],
      conversation: [
      ],
    },
    {
      day: 6,
      title: `Maelekezo ya msingi`,
      titleNative: `Direções básicas`,
      focus: `Leo unajifunza kuuliza na kuelewa maelekezo ya msingi mjini Porto au Rio de Janeiro. Utatumia maneno ya kulia, kushoto, mbele, na karibu.`,
      grammar: `“Fica” hutumika sana kuuliza mahali kitu kilipo, kama “Onde fica o hotel?” Hii ni rahisi kuliko kutumia vitenzi vingi tofauti. Kwa maelekezo, “vire” na “siga” ni amri za heshima zinazofaa kwa mgeni.`,
      vocab: [
        {tgt:`onde`,src:`wapi`,pron:`ON-dji`},
        {tgt:`aqui`,src:`hapa`,pron:`a-KI`},
        {tgt:`ali`,src:`pale`,pron:`a-LI`},
        {tgt:`direita`,src:`kulia`,pron:`dji-REI-ta`},
        {tgt:`esquerda`,src:`kushoto`,pron:`es-KER-da`},
        {tgt:`em frente`,src:`mbele moja kwa moja`,pron:`eng FREN-tshi`},
        {tgt:`perto`,src:`karibu`,pron:`PER-tu`},
        {tgt:`longe`,src:`mbali`,pron:`LON-zhi`},
        {tgt:`rua`,src:`barabara`,pron:`RU-a`},
        {tgt:`praça`,src:`uwanja`,pron:`PRA-sa`},
      ],
      phrases: [
        {tgt:`Onde fica o hotel?`,src:`Hoteli iko wapi?`,pron:`ON-dji FI-ka u o-TEL`},
        {tgt:`Vire à direita.`,src:`Geuka kulia.`,pron:`VI-ri a dji-REI-ta`},
        {tgt:`Vire à esquerda.`,src:`Geuka kushoto.`,pron:`VI-ri a es-KER-da`},
        {tgt:`Siga em frente.`,src:`Endelea mbele.`,pron:`SI-ga eng FREN-tshi`},
        {tgt:`É perto daqui?`,src:`Ni karibu na hapa?`,pron:`e PER-tu da-KI`},
        {tgt:`A praça fica ali.`,src:`Uwanja uko pale.`,pron:`a PRA-sa FI-ka a-LI`},
      ],
      conversation: [
      ],
    },
    {
      day: 7,
      title: `Usafiri wa teksi na programu`,
      titleNative: `Táxi e aplicativos`,
      focus: `Leo unajifunza maneno ya kupanda teksi au gari la programu katika São Paulo, Lisbon, au Maputo. Utajifunza kueleza unakoenda na kuuliza muda wa safari.`,
      grammar: `Kwa kusema unakoenda, tumia “para” kabla ya mahali: “para o hotel,” “para o aeroporto.” “Quero ir” humaanisha “nataka kwenda,” na ni muundo muhimu sana kwa safari. Katika Kireno cha Brazil, “ônibus” ni basi; Portugal mara nyingi hutumia “autocarro.”`,
      vocab: [
        {tgt:`táxi`,src:`teksi`,pron:`TAK-si`},
        {tgt:`carro`,src:`gari`,pron:`KA-hu`},
        {tgt:`motorista`,src:`dereva`,pron:`mo-to-RISH-ta`},
        {tgt:`endereço`,src:`anwani`,pron:`en-de-RE-su`},
        {tgt:`aeroporto`,src:`uwanja wa ndege`,pron:`a-e-ro-POR-tu`},
        {tgt:`estação`,src:`kituo`,pron:`es-ta-SAU`},
        {tgt:`hotel`,src:`hoteli`,pron:`o-TEL`},
        {tgt:`rápido`,src:`haraka`,pron:`HA-pi-du`},
        {tgt:`devagar`,src:`polepole`,pron:`dji-va-GAR`},
        {tgt:`chegar`,src:`kufika`,pron:`she-GAR`},
      ],
      phrases: [
        {tgt:`Quero ir para o hotel.`,src:`Nataka kwenda hotelini.`,pron:`KE-ru ir PA-ra u o-TEL`},
        {tgt:`Este é o endereço.`,src:`Hii ndiyo anwani.`,pron:`ESH-tshi e u en-de-RE-su`},
        {tgt:`Quanto tempo demora?`,src:`Inachukua muda gani?`,pron:`KWAN-tu TEN-pu dji-MO-ra`},
        {tgt:`Pode ir mais devagar?`,src:`Unaweza kwenda polepole zaidi?`,pron:`PO-dji ir maish dji-va-GAR`},
        {tgt:`Vamos para o aeroporto.`,src:`Twende uwanja wa ndege.`,pron:`VA-mush PA-ra u a-e-ro-POR-tu`},
        {tgt:`Chegamos?`,src:`Tumefika?`,pron:`she-GA-mush`},
      ],
      conversation: [
      ],
    },
    {
      day: 8,
      title: `Hoteli na mapokezi`,
      titleNative: `Hotel e recepção`,
      focus: `Leo unajifunza kuingia hotelini na kuuliza kuhusu chumba chako. Hii ni muhimu unapowasili Coimbra, Salvador, au Praia baada ya safari ndefu.`,
      grammar: `“Tenho” humaanisha “nina,” na ni muhimu sana hotelini: “Tenho uma reserva,” “Tenho uma mala.” “Preciso de” humaanisha “nahitaji,” na hutumiwa kabla ya kitu unachohitaji. Kumbuka “uma reserva” kwa sababu “reserva” ni neno la kike.`,
      vocab: [
        {tgt:`reserva`,src:`oda ya chumba`,pron:`re-ZER-va`},
        {tgt:`quarto`,src:`chumba`,pron:`KWAR-tu`},
        {tgt:`chave`,src:`ufunguo`,pron:`SHA-vi`},
        {tgt:`recepção`,src:`mapokezi`,pron:`he-sep-SAU`},
        {tgt:`passaporte`,src:`pasipoti`,pron:`pa-sa-POR-tshi`},
        {tgt:`noite`,src:`usiku`,pron:`NOI-tshi`},
        {tgt:`cama`,src:`kitanda`,pron:`KA-ma`},
        {tgt:`banheiro`,src:`bafu/choo`,pron:`ba-NYEI-ru`},
        {tgt:`elevador`,src:`lifti`,pron:`e-le-va-DOR`},
        {tgt:`andar`,src:`ghorofa`,pron:`an-DAR`},
      ],
      phrases: [
        {tgt:`Tenho uma reserva.`,src:`Nina oda ya chumba.`,pron:`TE-nyu U-ma re-ZER-va`},
        {tgt:`Aqui está meu passaporte.`,src:`Hii hapa pasipoti yangu.`,pron:`a-KI es-TA meu pa-sa-POR-tshi`},
        {tgt:`Qual é o número do quarto?`,src:`Nambari ya chumba ni ipi?`,pron:`kwal e u NU-me-ru du KWAR-tu`},
        {tgt:`Onde fica o elevador?`,src:`Lifti iko wapi?`,pron:`ON-dji FI-ka u e-le-va-DOR`},
        {tgt:`Preciso de uma chave.`,src:`Nahitaji ufunguo.`,pron:`pre-SI-zu dji U-ma SHA-vi`},
        {tgt:`Quantas noites?`,src:`Usiku mingapi?`,pron:`KWAN-tash NOI-tshis`},
      ],
      conversation: [
      ],
    },
    {
      day: 9,
      title: `Kahawa na kiamsha kinywa`,
      titleNative: `Café e café da manhã`,
      focus: `Leo unajifunza kuagiza kahawa na chakula cha asubuhi kwenye café ya Lisbon au Rio. Utatumia maneno rahisi ya kuomba, kuchagua, na kulipa.`,
      grammar: `“Com” humaanisha “na,” kama “café com leite.” “Sem” humaanisha “bila,” kama “sem açúcar.” Haya maneno mawili yatakusaidia kubadilisha oda zako bila sentensi ndefu.`,
      vocab: [
        {tgt:`café`,src:`kahawa`,pron:`ka-FE`},
        {tgt:`leite`,src:`maziwa`,pron:`LEI-tshi`},
        {tgt:`pão`,src:`mkate`,pron:`pau`},
        {tgt:`manteiga`,src:`siagi`,pron:`man-TEI-ga`},
        {tgt:`queijo`,src:`jibini`,pron:`KEI-zhu`},
        {tgt:`ovo`,src:`yai`,pron:`O-vu`},
        {tgt:`suco`,src:`juisi`,pron:`SU-ku`},
        {tgt:`água`,src:`maji`,pron:`A-gwa`},
        {tgt:`açúcar`,src:`sukari`,pron:`a-SU-kar`},
        {tgt:`mesa`,src:`meza`,pron:`ME-za`},
      ],
      phrases: [
        {tgt:`Um café com leite, por favor.`,src:`Kahawa moja na maziwa, tafadhali.`,pron:`ung ka-FE kong LEI-tshi, por fa-VOR`},
        {tgt:`Quero pão com manteiga.`,src:`Nataka mkate na siagi.`,pron:`KE-ru pau kong man-TEI-ga`},
        {tgt:`Tem suco de laranja?`,src:`Kuna juisi ya machungwa?`,pron:`teng SU-ku dji la-RAN-zha`},
        {tgt:`Sem açúcar, por favor.`,src:`Bila sukari, tafadhali.`,pron:`seng a-SU-kar, por fa-VOR`},
        {tgt:`Posso sentar aqui?`,src:`Naweza kukaa hapa?`,pron:`PO-su sen-TAR a-KI`},
        {tgt:`A conta, por favor.`,src:`Bili, tafadhali.`,pron:`a KON-ta, por fa-VOR`},
      ],
      conversation: [
      ],
    },
    {
      day: 10,
      title: `Chakula cha mchana na mgahawa`,
      titleNative: `Almoço e restaurante`,
      focus: `Leo unajifunza kuagiza chakula cha mchana katika mgahawa wa kawaida nchini Brazil au Portugal. Utajifunza kuelewa menyu, kuomba maji, na kusema kile unachopenda.`,
      grammar: `“Quero” ni kitenzi chenye nguvu kwa msafiri: “Quero café,” “Quero arroz,” “Quero ver o menu.” Kwa heshima zaidi, ongeza “por favor.” Katika mgahawa, “Tem...?” ni njia rahisi ya kuuliza kama kitu kipo.`,
      vocab: [
        {tgt:`almoço`,src:`chakula cha mchana`,pron:`al-MO-su`},
        {tgt:`jantar`,src:`chakula cha jioni`,pron:`zhan-TAR`},
        {tgt:`menu`,src:`menyu`,pron:`me-NU`},
        {tgt:`prato`,src:`sahani`,pron:`PRA-tu`},
        {tgt:`frango`,src:`kuku`,pron:`FRAN-gu`},
        {tgt:`peixe`,src:`samaki`,pron:`PEI-shi`},
        {tgt:`carne`,src:`nyama`,pron:`KAR-ni`},
        {tgt:`arroz`,src:`wali`,pron:`a-HOZ`},
        {tgt:`salada`,src:`saladi`,pron:`sa-LA-da`},
        {tgt:`conta`,src:`bili`,pron:`KON-ta`},
      ],
      phrases: [
        {tgt:`Tem mesa para dois?`,src:`Kuna meza ya watu wawili?`,pron:`teng ME-za PA-ra doish`},
        {tgt:`Quero ver o menu.`,src:`Nataka kuona menyu.`,pron:`KE-ru ver u me-NU`},
        {tgt:`Eu quero frango com arroz.`,src:`Nataka kuku na wali.`,pron:`eu KE-ru FRAN-gu kong a-HOZ`},
        {tgt:`Tem peixe hoje?`,src:`Kuna samaki leo?`,pron:`teng PEI-shi O-zhi`},
        {tgt:`A comida está boa.`,src:`Chakula ni kizuri.`,pron:`a ko-MI-da es-TA BO-a`},
        {tgt:`Pode trazer a conta?`,src:`Unaweza kuleta bili?`,pron:`PO-dji tra-ZER a KON-ta`},
      ],
      conversation: [
      ],
    },
    {
      day: 11,
      title: `Mahitaji maalum ya chakula`,
      titleNative: `Necessidades alimentares`,
      focus: `Leo unajifunza kueleza vitu usivyokula au unavyopendelea. Hii ni muhimu kwa watu wenye mzio, mboga, au wanaohitaji chakula maalum katika Luanda, Recife, au Lisbon.`,
      grammar: `“Não como...” humaanisha “sili...” na ni muhimu sana kwa chakula. Kwa mzio, tumia “Tenho alergia a...” kabla ya kitu: “Tenho alergia a leite.” Usione aibu kusema mara mbili ikiwa ni suala la afya.`,
      vocab: [
        {tgt:`vegetariano`,src:`mla mboga, mwanaume`,pron:`ve-zhe-ta-ri-A-nu`},
        {tgt:`vegetariana`,src:`mla mboga, mwanamke`,pron:`ve-zhe-ta-ri-A-na`},
        {tgt:`alergia`,src:`mzio`,pron:`a-ler-ZHI-a`},
        {tgt:`leite`,src:`maziwa`,pron:`LEI-tshi`},
        {tgt:`amendoim`,src:`karanga`,pron:`a-men-do-ING`},
        {tgt:`carne`,src:`nyama`,pron:`KAR-ni`},
        {tgt:`porco`,src:`nguruwe`,pron:`POR-ku`},
        {tgt:`sem`,src:`bila`,pron:`seng`},
        {tgt:`picante`,src:`kali`,pron:`pi-KAN-tshi`},
        {tgt:`leve`,src:`nyepesi`,pron:`LE-vi`},
      ],
      phrases: [
        {tgt:`Sou vegetariano.`,src:`Mimi ni mla mboga, mwanaume.`,pron:`sou ve-zhe-ta-ri-A-nu`},
        {tgt:`Sou vegetariana.`,src:`Mimi ni mla mboga, mwanamke.`,pron:`sou ve-zhe-ta-ri-A-na`},
        {tgt:`Tenho alergia a amendoim.`,src:`Nina mzio wa karanga.`,pron:`TE-nyu a-ler-ZHI-a a a-men-do-ING`},
        {tgt:`Sem carne, por favor.`,src:`Bila nyama, tafadhali.`,pron:`seng KAR-ni, por fa-VOR`},
        {tgt:`Não como porco.`,src:`Sili nguruwe.`,pron:`nau KO-mu POR-ku`},
        {tgt:`É muito picante?`,src:`Ni kali sana?`,pron:`e MUI-tu pi-KAN-tshi`},
      ],
      conversation: [
      ],
    },
    {
      day: 12,
      title: `Kununua sokoni`,
      titleNative: `Comprar no mercado`,
      focus: `Leo unajifunza maneno ya soko na mazungumzo ya kununua matunda, maji, na bidhaa ndogo. Mazoezi haya yanafaa katika masoko ya Maputo, Salvador, au Mindelo.`,
      grammar: `“Vou levar” ni njia ya kawaida kusema “nitachukua” unapomaliza kuchagua kitu dukani au sokoni. “Isto” humaanisha “hiki/hii” kwa kitu kilicho karibu nawe. Unaweza kutumia kidole kwa heshima na kusema “Vou levar isto.”`,
      vocab: [
        {tgt:`mercado`,src:`soko`,pron:`mer-KA-du`},
        {tgt:`fruta`,src:`tunda`,pron:`FRU-ta`},
        {tgt:`banana`,src:`ndizi`,pron:`ba-NA-na`},
        {tgt:`maçã`,src:`tufaha`,pron:`ma-SA`},
        {tgt:`laranja`,src:`chungwa`,pron:`la-RAN-zha`},
        {tgt:`garrafa`,src:`chupa`,pron:`ga-HA-fa`},
        {tgt:`água`,src:`maji`,pron:`A-gwa`},
        {tgt:`quilo`,src:`kilo`,pron:`KI-lu`},
        {tgt:`sacola`,src:`mfuko`,pron:`sa-KO-la`},
        {tgt:`fresco`,src:`safi/mpya`,pron:`FRES-ku`},
      ],
      phrases: [
        {tgt:`Quero um quilo de bananas.`,src:`Nataka kilo moja ya ndizi.`,pron:`KE-ru ung KI-lu dji ba-NA-nash`},
        {tgt:`A fruta está fresca?`,src:`Matunda ni mapya?`,pron:`a FRU-ta es-TA FRES-ka`},
        {tgt:`Quanto custa a garrafa de água?`,src:`Chupa ya maji inagharimu kiasi gani?`,pron:`KWAN-tu KUSH-ta a ga-HA-fa dji A-gwa`},
        {tgt:`Tem sacola?`,src:`Una mfuko?`,pron:`teng sa-KO-la`},
        {tgt:`Só estou olhando.`,src:`Ninaangalia tu.`,pron:`so es-TO o-LYAN-du`},
        {tgt:`Vou levar isto.`,src:`Nitachukua hiki.`,pron:`vou le-VAR IS-tu`},
      ],
      conversation: [
      ],
    },
    {
      day: 13,
      title: `Duka la nguo`,
      titleNative: `Loja de roupas`,
      focus: `Leo unajifunza kununua nguo, kuuliza ukubwa, na kuomba kujaribu. Hii itakusaidia katika maduka ya Lisbon, São Paulo, au Luanda.`,
      grammar: `“Esta” hutumika kwa kitu cha kike kilicho karibu, kama “esta camisa.” “Estes” hutumika kwa vitu vingi vya kiume au mchanganyiko, kama “estes sapatos.” Katika duka, ukiwa huna uhakika, unaweza kusema “isto” na bado utaeleweka.`,
      vocab: [
        {tgt:`loja`,src:`duka`,pron:`LO-zha`},
        {tgt:`roupa`,src:`nguo`,pron:`HO-pa`},
        {tgt:`camisa`,src:`shati`,pron:`ka-MI-za`},
        {tgt:`calça`,src:`suruali`,pron:`KAL-sa`},
        {tgt:`vestido`,src:`gauni`,pron:`ves-TI-du`},
        {tgt:`sapato`,src:`kiatu`,pron:`sa-PA-tu`},
        {tgt:`tamanho`,src:`ukubwa`,pron:`ta-MA-nyu`},
        {tgt:`pequeno`,src:`ndogo`,pron:`pe-KE-nu`},
        {tgt:`médio`,src:`ya kati`,pron:`ME-diu`},
        {tgt:`grande`,src:`kubwa`,pron:`GRAN-dji`},
      ],
      phrases: [
        {tgt:`Tem tamanho médio?`,src:`Kuna ukubwa wa kati?`,pron:`teng ta-MA-nyu ME-diu`},
        {tgt:`Posso experimentar?`,src:`Naweza kujaribu?`,pron:`PO-su es-pe-ri-men-TAR`},
        {tgt:`Ficou bom.`,src:`Imenikaa vizuri.`,pron:`fi-KO bong`},
        {tgt:`Ficou pequeno.`,src:`Imenibana/ni ndogo.`,pron:`fi-KO pe-KE-nu`},
        {tgt:`Quanto custa esta camisa?`,src:`Shati hili linagharimu kiasi gani?`,pron:`KWAN-tu KUSH-ta ESH-ta ka-MI-za`},
        {tgt:`Vou comprar estes sapatos.`,src:`Nitanunua viatu hivi.`,pron:`vou kom-PRAR ESH-tshis sa-PA-tush`},
      ],
      conversation: [
      ],
    },
    {
      day: 14,
      title: `Muda na ratiba`,
      titleNative: `Hora e horários`,
      focus: `Leo unajifunza kuuliza muda na kuelewa ratiba za basi, treni, au makumbusho. Hii ni muhimu sana ukisafiri kati ya miji ya Portugal au Brazil.`,
      grammar: `Kwa saa moja, Kireno hutumia “É uma hora,” lakini kwa saa nyingine nyingi hutumia “São.” Neno “às” hutumika kuonyesha saa fulani: “às seis.” Ratiba zinaweza kutumia mfumo wa saa 24, hasa vituo vya usafiri.`,
      vocab: [
        {tgt:`hora`,src:`saa`,pron:`O-ra`},
        {tgt:`minuto`,src:`dakika`,pron:`mi-NU-tu`},
        {tgt:`agora`,src:`sasa`,pron:`a-GO-ra`},
        {tgt:`hoje`,src:`leo`,pron:`O-zhi`},
        {tgt:`amanhã`,src:`kesho`,pron:`a-ma-NYANG`},
        {tgt:`ontem`,src:`jana`,pron:`ON-teng`},
        {tgt:`cedo`,src:`mapema`,pron:`SE-du`},
        {tgt:`tarde`,src:`kuchelewa/jioni`,pron:`TAR-dji`},
        {tgt:`aberto`,src:`wazi/imefunguliwa`,pron:`a-BER-tu`},
        {tgt:`fechado`,src:`imefungwa`,pron:`fe-SHA-du`},
      ],
      phrases: [
        {tgt:`Que horas são?`,src:`Ni saa ngapi?`,pron:`ki O-rash sau`},
        {tgt:`É uma hora.`,src:`Ni saa moja.`,pron:`e U-ma O-ra`},
        {tgt:`São três horas.`,src:`Ni saa tatu.`,pron:`sau tresh O-rash`},
        {tgt:`A que horas abre?`,src:`Inafunguliwa saa ngapi?`,pron:`a ki O-rash A-bri`},
        {tgt:`Fecha às seis.`,src:`Inafungwa saa kumi na mbili/jioni saa sita.`,pron:`FE-sha ash seish`},
        {tgt:`O ônibus sai amanhã.`,src:`Basi linaondoka kesho.`,pron:`u O-ni-bus sai a-ma-NYANG`},
      ],
      conversation: [
      ],
    },
    {
      day: 15,
      title: `Tiketi na usafiri wa umma`,
      titleNative: `Bilhetes e transporte público`,
      focus: `Leo unajifunza kununua tiketi za basi, treni, metro, au kivuko. Maneno haya yanafaa sana Lisbon, Porto, Rio de Janeiro, na Maputo.`,
      grammar: `Maneno ya usafiri hutofautiana kati ya Portugal na Brazil: “comboio” ni treni Portugal, “trem” ni treni Brazil. Kwa basi, Portugal hutumia “autocarro,” Brazil hutumia “ônibus.” Ukisafiri nchi tofauti, kusikia tofauti hizi kutakusaidia sana.`,
      vocab: [
        {tgt:`bilhete`,src:`tiketi`,pron:`bi-LYE-tshi`},
        {tgt:`ônibus`,src:`basi, hasa Brazil`,pron:`O-ni-bus`},
        {tgt:`autocarro`,src:`basi, hasa Portugal`,pron:`au-tu-KA-hu`},
        {tgt:`trem`,src:`treni, hasa Brazil`,pron:`treng`},
        {tgt:`comboio`,src:`treni, hasa Portugal`,pron:`kong-BOI-u`},
        {tgt:`metrô`,src:`metro, hasa Brazil`,pron:`me-TRO`},
        {tgt:`metro`,src:`metro, hasa Portugal`,pron:`ME-tru`},
        {tgt:`ida`,src:`kwenda tu`,pron:`I-da`},
        {tgt:`volta`,src:`kurudi`,pron:`VOL-ta`},
        {tgt:`plataforma`,src:`jukwaa`,pron:`pla-ta-FOR-ma`},
      ],
      phrases: [
        {tgt:`Quero um bilhete de ida.`,src:`Nataka tiketi ya kwenda tu.`,pron:`KE-ru ung bi-LYE-tshi dji I-da`},
        {tgt:`Quero ida e volta.`,src:`Nataka kwenda na kurudi.`,pron:`KE-ru I-da i VOL-ta`},
        {tgt:`Onde fica a plataforma?`,src:`Jukwaa liko wapi?`,pron:`ON-dji FI-ka a pla-ta-FOR-ma`},
        {tgt:`O trem sai agora?`,src:`Treni inaondoka sasa?`,pron:`u treng sai a-GO-ra`},
        {tgt:`Este ônibus vai para o centro?`,src:`Basi hili linaenda mjini kati?`,pron:`ESH-tshi O-ni-bus vai PA-ra u SEN-tru`},
        {tgt:`Preciso trocar de linha?`,src:`Nahitaji kubadili laini?`,pron:`pre-SI-zu tro-KAR dji LI-nya`},
      ],
      conversation: [
      ],
    },
    {
      day: 16,
      title: `Kuuliza msaada`,
      titleNative: `Pedir ajuda`,
      focus: `Leo unajifunza kuomba msaada kwa urahisi na kueleza tatizo dogo. Hii ni muhimu ukipotea, ukipoteza kitu, au ukihitaji kuelewa tangazo.`,
      grammar: `“Estou” humaanisha “niko” au “nipo katika hali fulani.” Tumia “Estou perdido/perdida” kusema umepotea. “Pode me ajudar?” ni sentensi ya heshima na muhimu sana kwa msafiri yeyote.`,
      vocab: [
        {tgt:`ajuda`,src:`msaada`,pron:`a-ZHU-da`},
        {tgt:`ajudar`,src:`kusaidia`,pron:`a-zhu-DAR`},
        {tgt:`perdido`,src:`aliyepotea, mwanaume`,pron:`per-DJI-du`},
        {tgt:`perdida`,src:`aliyepotea, mwanamke`,pron:`per-DJI-da`},
        {tgt:`problema`,src:`tatizo`,pron:`pro-BLE-ma`},
        {tgt:`telefone`,src:`simu`,pron:`te-le-FO-ni`},
        {tgt:`internet`,src:`intaneti`,pron:`in-ter-NET`},
        {tgt:`mapa`,src:`ramani`,pron:`MA-pa`},
        {tgt:`polícia`,src:`polisi`,pron:`po-LI-si-a`},
        {tgt:`embaixada`,src:`ubalozi`,pron:`em-bai-SHA-da`},
      ],
      phrases: [
        {tgt:`Pode me ajudar?`,src:`Unaweza kunisaidia?`,pron:`PO-dji mi a-zhu-DAR`},
        {tgt:`Estou perdido.`,src:`Nimepotea, msemaji wa kiume.`,pron:`es-TO per-DJI-du`},
        {tgt:`Estou perdida.`,src:`Nimepotea, msemaji wa kike.`,pron:`es-TO per-DJI-da`},
        {tgt:`Tenho um problema.`,src:`Nina tatizo.`,pron:`TE-nyu ung pro-BLE-ma`},
        {tgt:`Meu telefone não funciona.`,src:`Simu yangu haifanyi kazi.`,pron:`meu te-le-FO-ni nau fun-si-O-na`},
        {tgt:`Onde fica a polícia?`,src:`Polisi wako wapi?`,pron:`ON-dji FI-ka a po-LI-si-a`},
      ],
      conversation: [
      ],
    },
    {
      day: 17,
      title: `Simu, Wi-Fi na intaneti`,
      titleNative: `Telefone, Wi-Fi e internet`,
      focus: `Leo unajifunza kuuliza kuhusu Wi-Fi, nenosiri, na chaji ya simu. Hii ni muhimu kwenye café, hoteli, au kituo cha usafiri.`,
      grammar: `“Tem” ni neno muhimu sana na linaweza kumaanisha “kuna” au “una” kulingana na muktadha. “Tem Wi-Fi aqui?” ni rahisi na linaeleweka. “Qual é...” hutumika kuuliza kitu maalum, kama nenosiri au nambari.`,
      vocab: [
        {tgt:`Wi-Fi`,src:`Wi-Fi`,pron:`wai-FAI`},
        {tgt:`senha`,src:`nenosiri`,pron:`SEN-ya`},
        {tgt:`internet`,src:`intaneti`,pron:`in-ter-NET`},
        {tgt:`carregador`,src:`chaja`,pron:`ka-he-ga-DOR`},
        {tgt:`tomada`,src:`soketi`,pron:`to-MA-da`},
        {tgt:`bateria`,src:`betri`,pron:`ba-te-RI-a`},
        {tgt:`ligar`,src:`kupiga simu/kuwasha`,pron:`li-GAR`},
        {tgt:`mensagem`,src:`ujumbe`,pron:`men-SA-zheng`},
        {tgt:`número`,src:`nambari`,pron:`NU-me-ru`},
        {tgt:`sinal`,src:`mtandao/signal`,pron:`si-NAL`},
      ],
      phrases: [
        {tgt:`Tem Wi-Fi aqui?`,src:`Kuna Wi-Fi hapa?`,pron:`teng wai-FAI a-KI`},
        {tgt:`Qual é a senha?`,src:`Nenosiri ni lipi?`,pron:`kwal e a SEN-ya`},
        {tgt:`Preciso carregar meu telefone.`,src:`Nahitaji kuchaji simu yangu.`,pron:`pre-SI-zu ka-he-GAR meu te-le-FO-ni`},
        {tgt:`Onde tem uma tomada?`,src:`Kuna soketi wapi?`,pron:`ON-dji teng U-ma to-MA-da`},
        {tgt:`Não tenho sinal.`,src:`Sina mtandao/signal.`,pron:`nau TE-nyu si-NAL`},
        {tgt:`Pode me dar seu número?`,src:`Unaweza kunipa nambari yako?`,pron:`PO-dji mi dar seu NU-me-ru`},
      ],
      conversation: [
      ],
    },
    {
      day: 18,
      title: `Afya na duka la dawa`,
      titleNative: `Saúde e farmácia`,
      focus: `Leo unajifunza kueleza dalili rahisi na kuomba msaada kwenye duka la dawa. Hii ni muhimu ukiwa safarini na unahitaji dawa ya maumivu, kikohozi, au tumbo.`,
      grammar: `Kwa maumivu, tumia “Tenho dor de...” kisha sehemu ya mwili: “cabeça,” “estômago.” Kwa dalili nyingine, tumia “Tenho febre” au “Tenho tosse.” Usitumie Kireno kigumu unapohitaji msaada wa haraka; sentensi fupi ni bora.`,
      vocab: [
        {tgt:`farmácia`,src:`duka la dawa`,pron:`far-MA-si-a`},
        {tgt:`remédio`,src:`dawa`,pron:`he-ME-diu`},
        {tgt:`dor`,src:`maumivu`,pron:`dor`},
        {tgt:`cabeça`,src:`kichwa`,pron:`ka-BE-sa`},
        {tgt:`estômago`,src:`tumbo`,pron:`es-TO-ma-gu`},
        {tgt:`febre`,src:`homa`,pron:`FE-bri`},
        {tgt:`tosse`,src:`kikohozi`,pron:`TO-si`},
        {tgt:`alergia`,src:`mzio`,pron:`a-ler-ZHI-a`},
        {tgt:`médico`,src:`daktari`,pron:`ME-dji-ku`},
        {tgt:`hospital`,src:`hospitali`,pron:`os-pi-TAL`},
      ],
      phrases: [
        {tgt:`Preciso de uma farmácia.`,src:`Nahitaji duka la dawa.`,pron:`pre-SI-zu dji U-ma far-MA-si-a`},
        {tgt:`Tenho dor de cabeça.`,src:`Nina maumivu ya kichwa.`,pron:`TE-nyu dor dji ka-BE-sa`},
        {tgt:`Tenho dor de estômago.`,src:`Nina maumivu ya tumbo.`,pron:`TE-nyu dor dji es-TO-ma-gu`},
        {tgt:`Tenho febre.`,src:`Nina homa.`,pron:`TE-nyu FE-bri`},
        {tgt:`Preciso ver um médico.`,src:`Nahitaji kumuona daktari.`,pron:`pre-SI-zu ver ung ME-dji-ku`},
        {tgt:`Onde fica o hospital?`,src:`Hospitali iko wapi?`,pron:`ON-dji FI-ka u os-pi-TAL`},
      ],
      conversation: [
      ],
    },
    {
      day: 19,
      title: `Hali ya hewa na mipango`,
      titleNative: `Clima e planos`,
      focus: `Leo unajifunza kuzungumzia hali ya hewa na kupanga shughuli za siku. Hii ni muhimu kwa matembezi ya pwani Rio, ziara ya Lisbon, au safari ya kisiwa Cabo Verde.`,
      grammar: `“Está” hutumika kueleza hali ya muda mfupi, kama hali ya hewa: “Está frio,” “Está calor.” Kwa mipango ya kwenda mahali, tumia “Quero ir a...” au “Quero ir à...” kabla ya mahali kama “praia.” “Vai chover” ni njia rahisi ya kusema “itanyesha.”`,
      vocab: [
        {tgt:`tempo`,src:`hali ya hewa/muda`,pron:`TEN-pu`},
        {tgt:`sol`,src:`jua`,pron:`sol`},
        {tgt:`chuva`,src:`mvua`,pron:`SHU-va`},
        {tgt:`vento`,src:`upepo`,pron:`VEN-tu`},
        {tgt:`calor`,src:`joto`,pron:`ka-LOR`},
        {tgt:`frio`,src:`baridi`,pron:`FRI-u`},
        {tgt:`nublado`,src:`mawingu`,pron:`nu-BLA-du`},
        {tgt:`praia`,src:`ufukwe`,pron:`PRAI-a`},
        {tgt:`passeio`,src:`matembezi/ziara`,pron:`pa-SEI-u`},
        {tgt:`guarda-chuva`,src:`mwavuli`,pron:`GWAR-da-SHU-va`},
      ],
      phrases: [
        {tgt:`Como está o tempo?`,src:`Hali ya hewa ikoje?`,pron:`KO-mu es-TA u TEN-pu`},
        {tgt:`Está muito calor.`,src:`Kuna joto sana.`,pron:`es-TA MUI-tu ka-LOR`},
        {tgt:`Vai chover hoje?`,src:`Itanyesha leo?`,pron:`vai sho-VER O-zhi`},
        {tgt:`Quero ir à praia.`,src:`Nataka kwenda ufukweni.`,pron:`KE-ru ir a PRAI-a`},
        {tgt:`Preciso de um guarda-chuva.`,src:`Nahitaji mwavuli.`,pron:`pre-SI-zu dji ung GWAR-da-SHU-va`},
        {tgt:`O passeio é amanhã.`,src:`Ziara ni kesho.`,pron:`u pa-SEI-u e a-ma-NYANG`},
      ],
      conversation: [
      ],
    },
    {
      day: 20,
      title: `Mazungumzo madogo`,
      titleNative: `Conversa informal`,
      focus: `Leo unajifunza mazungumzo madogo na wenyeji. Hii ni nzuri unapokutana na mtu kwenye hosteli, ziara ya mji, au café huko Lisbon, Maputo, au Salvador.`,
      grammar: `“Gosto de...” humaanisha “ninapenda...” lakini lazima utumie “de” kabla ya kitu: “Gosto de música.” Ukiwa unaonyesha kitu maalum, unaweza kusema “Gosto desta cidade,” yaani “ninapenda mji huu.” Mazungumzo madogo mara nyingi huanza kwa kuuliza nchi au mji.`,
      vocab: [
        {tgt:`país`,src:`nchi`,pron:`pa-ISH`},
        {tgt:`cidade`,src:`mji`,pron:`si-DA-dji`},
        {tgt:`bonito`,src:`nzuri, kiume`,pron:`bo-NI-tu`},
        {tgt:`bonita`,src:`nzuri, kike`,pron:`bo-NI-ta`},
        {tgt:`gostar`,src:`kupenda`,pron:`gos-TAR`},
        {tgt:`música`,src:`muziki`,pron:`MU-zi-ka`},
        {tgt:`comida`,src:`chakula`,pron:`ko-MI-da`},
        {tgt:`viagem`,src:`safari`,pron:`vi-A-zheng`},
        {tgt:`família`,src:`familia`,pron:`fa-MI-li-a`},
        {tgt:`trabalho`,src:`kazi`,pron:`tra-BA-lyu`},
      ],
      phrases: [
        {tgt:`De onde você é?`,src:`Wewe unatoka wapi?`,pron:`dji ON-dji vo-SE e`},
        {tgt:`Sou da Tanzânia.`,src:`Ninatoka Tanzania.`,pron:`sou da tan-za-NI-a`},
        {tgt:`Gosto desta cidade.`,src:`Ninapenda mji huu.`,pron:`GOS-tu DESH-ta si-DA-dji`},
        {tgt:`A comida é muito boa.`,src:`Chakula ni kizuri sana.`,pron:`a ko-MI-da e MUI-tu BO-a`},
        {tgt:`Você gosta de música?`,src:`Unapenda muziki?`,pron:`vo-SE GOS-ta dji MU-zi-ka`},
        {tgt:`Minha viagem é curta.`,src:`Safari yangu ni fupi.`,pron:`MI-nya vi-A-zheng e KUR-ta`},
      ],
      conversation: [
      ],
    },
    {
      day: 21,
      title: `Kupanga shughuli na matembezi`,
      titleNative: `Fazer planos e passeios`,
      focus: `Leo unajifunza kupanga ziara, kuuliza muda, na kusema unachotaka kufanya. Hii ni muhimu kwa safari ya makumbusho, ufukwe, au kutembea mjini.`,
      grammar: `Kwa kusema unataka kufanya kitendo, tumia “Quero” pamoja na kitenzi kisichobadilishwa: “Quero visitar,” “Quero comer,” “Quero comprar.” Hii ni muundo rahisi na unafaa kwa mipango mingi ya safari. “Está aberto” na “está fechado” husaidia kuuliza kama sehemu inapatikana.`,
      vocab: [
        {tgt:`plano`,src:`mpango`,pron:`PLA-nu`},
        {tgt:`visitar`,src:`kutembelea`,pron:`vi-zi-TAR`},
        {tgt:`museu`,src:`makumbusho`,pron:`mu-ZEU`},
        {tgt:`igreja`,src:`kanisa`,pron:`i-GRE-zha`},
        {tgt:`castelo`,src:`kasri`,pron:`kash-TE-lu`},
        {tgt:`centro`,src:`mjini kati`,pron:`SEN-tru`},
        {tgt:`tour`,src:`ziara`,pron:`tur`},
        {tgt:`guia`,src:`mwongozo`,pron:`GI-a`},
        {tgt:`entrada`,src:`kiingilio`,pron:`en-TRA-da`},
        {tgt:`horário`,src:`ratiba`,pron:`o-RA-riu`},
      ],
      phrases: [
        {tgt:`Quero visitar o museu.`,src:`Nataka kutembelea makumbusho.`,pron:`KE-ru vi-zi-TAR u mu-ZEU`},
        {tgt:`Tem tour hoje?`,src:`Kuna ziara leo?`,pron:`teng tur O-zhi`},
        {tgt:`Quanto custa a entrada?`,src:`Kiingilio kinagharimu kiasi gani?`,pron:`KWAN-tu KUSH-ta a en-TRA-da`},
        {tgt:`Preciso de um guia.`,src:`Nahitaji mwongozo.`,pron:`pre-SI-zu dji ung GI-a`},
        {tgt:`O castelo está aberto?`,src:`Kasri limefunguliwa?`,pron:`u kash-TE-lu es-TA a-BER-tu`},
        {tgt:`Vamos ao centro amanhã.`,src:`Twende mjini kati kesho.`,pron:`VA-mush au SEN-tru a-ma-NYANG`},
      ],
      conversation: [
      ],
    },
    {
      day: 22,
      title: `Nyumba ya wageni na malalamiko madogo`,
      titleNative: `Hospedagem e pequenos problemas`,
      focus: `Leo unajifunza kueleza matatizo ya kawaida hotelini kama maji, kelele, au Wi-Fi. Lengo ni kuzungumza kwa heshima na kupata suluhisho haraka.`,
      grammar: `Kwa matatizo, “não funciona” ni muhimu sana: unaweza kusema “o telefone não funciona,” “o ar-condicionado não funciona.” “Tem muito...” husaidia kueleza kuna kitu kingi, kama kelele au moshi. Kuongeza “por favor” kunafanya malalamiko yawe ya heshima zaidi.`,
      vocab: [
        {tgt:`barulho`,src:`kelele`,pron:`ba-RU-lyu`},
        {tgt:`limpo`,src:`safi, kiume`,pron:`LIM-pu`},
        {tgt:`limpa`,src:`safi, kike`,pron:`LIM-pa`},
        {tgt:`sujo`,src:`chafu, kiume`,pron:`SU-zhu`},
        {tgt:`suja`,src:`chafu, kike`,pron:`SU-zha`},
        {tgt:`água quente`,src:`maji ya moto`,pron:`A-gwa KEN-tshi`},
        {tgt:`ar-condicionado`,src:`kiyoyozi`,pron:`ar kon-di-si-o-NA-du`},
        {tgt:`toalha`,src:`taulo`,pron:`to-A-lya`},
        {tgt:`trocar`,src:`kubadilisha`,pron:`tro-KAR`},
        {tgt:`funcionar`,src:`kufanya kazi`,pron:`fun-si-o-NAR`},
      ],
      phrases: [
        {tgt:`O Wi-Fi não funciona.`,src:`Wi-Fi haifanyi kazi.`,pron:`u wai-FAI nau fun-si-O-na`},
        {tgt:`Não tem água quente.`,src:`Hakuna maji ya moto.`,pron:`nau teng A-gwa KEN-tshi`},
        {tgt:`O quarto está sujo.`,src:`Chumba ni kichafu.`,pron:`u KWAR-tu es-TA SU-zhu`},
        {tgt:`Pode trocar a toalha?`,src:`Unaweza kubadilisha taulo?`,pron:`PO-dji tro-KAR a to-A-lya`},
        {tgt:`Tem muito barulho.`,src:`Kuna kelele nyingi.`,pron:`teng MUI-tu ba-RU-lyu`},
        {tgt:`Preciso de ajuda no quarto.`,src:`Nahitaji msaada chumbani.`,pron:`pre-SI-zu dji a-ZHU-da nu KWAR-tu`},
      ],
      conversation: [
      ],
    },
    {
      day: 23,
      title: `Benki na ATM`,
      titleNative: `Banco e caixa eletrônico`,
      focus: `Leo unajifunza maneno ya kutumia ATM, kubadilisha pesa, na kuuliza kuhusu ada. Hii ni muhimu katika maeneo ya utalii na miji mikubwa.`,
      grammar: `Brazil hutumia sana “caixa eletrônico” na Portugal hutumia “multibanco.” Kwa kutoa pesa, “sacar” ni kawaida Brazil, na “levantar dinheiro” ni kawaida Portugal. Kwa msafiri, ukitumia mojawapo, mara nyingi watu watakuelewa kutokana na muktadha.`,
      vocab: [
        {tgt:`banco`,src:`benki`,pron:`BAN-ku`},
        {tgt:`caixa eletrônico`,src:`ATM, hasa Brazil`,pron:`KAI-sha e-le-TRO-ni-ku`},
        {tgt:`multibanco`,src:`ATM, hasa Portugal`,pron:`mul-ti-BAN-ku`},
        {tgt:`dinheiro`,src:`pesa taslimu`,pron:`dji-NYEI-ru`},
        {tgt:`sacar`,src:`kutoa pesa`,pron:`sa-KAR`},
        {tgt:`levantar`,src:`kutoa pesa, hasa Portugal`,pron:`le-van-TAR`},
        {tgt:`câmbio`,src:`kubadilisha fedha`,pron:`KAM-biu`},
        {tgt:`taxa`,src:`ada`,pron:`TA-sha`},
        {tgt:`cartão`,src:`kadi`,pron:`kar-TAU`},
        {tgt:`senha`,src:`PIN/nenosiri`,pron:`SEN-ya`},
      ],
      phrases: [
        {tgt:`Onde fica um caixa eletrônico?`,src:`ATM iko wapi?`,pron:`ON-dji FI-ka ung KAI-sha e-le-TRO-ni-ku`},
        {tgt:`Preciso sacar dinheiro.`,src:`Nahitaji kutoa pesa.`,pron:`pre-SI-zu sa-KAR dji-NYEI-ru`},
        {tgt:`Tem taxa?`,src:`Kuna ada?`,pron:`teng TA-sha`},
        {tgt:`Quero trocar dinheiro.`,src:`Nataka kubadilisha pesa.`,pron:`KE-ru tro-KAR dji-NYEI-ru`},
        {tgt:`Meu cartão não funciona.`,src:`Kadi yangu haifanyi kazi.`,pron:`meu kar-TAU nau fun-si-O-na`},
        {tgt:`Esqueci minha senha.`,src:`Nimesahau PIN yangu.`,pron:`es-ke-SI MI-nya SEN-ya`},
      ],
      conversation: [
      ],
    },
    {
      day: 24,
      title: `Usalama na dharura`,
      titleNative: `Segurança e emergência`,
      focus: `Leo unajifunza maneno muhimu ya usalama na dharura. Haya ni maneno ya kutumia ukipoteza pochi, ukihitaji polisi, au ukikutana na hali hatari.`,
      grammar: `Katika dharura, sentensi fupi ni bora. “Chame...” ni amri ya heshima inayomaanisha “ita...” kama “Chame a polícia.” “Perdi” humaanisha “nilipoteza,” na “roubaram” humaanisha “waliiba” bila kuhitaji kujua nani aliiba.`,
      vocab: [
        {tgt:`emergência`,src:`dharura`,pron:`e-mer-ZHEN-si-a`},
        {tgt:`polícia`,src:`polisi`,pron:`po-LI-si-a`},
        {tgt:`ambulância`,src:`ambulansi`,pron:`am-bu-LAN-si-a`},
        {tgt:`socorro`,src:`msaada wa haraka`,pron:`so-KO-hu`},
        {tgt:`roubar`,src:`kuiba`,pron:`ho-BAR`},
        {tgt:`perder`,src:`kupoteza`,pron:`per-DER`},
        {tgt:`carteira`,src:`pochi`,pron:`kar-TEI-ra`},
        {tgt:`documentos`,src:`nyaraka`,pron:`do-ku-MEN-tush`},
        {tgt:`seguro`,src:`salama`,pron:`se-GU-ru`},
        {tgt:`perigoso`,src:`hatari`,pron:`pe-ri-GO-zu`},
      ],
      phrases: [
        {tgt:`Preciso de ajuda agora.`,src:`Nahitaji msaada sasa.`,pron:`pre-SI-zu dji a-ZHU-da a-GO-ra`},
        {tgt:`Chame a polícia.`,src:`Ita polisi.`,pron:`SHA-mi a po-LI-si-a`},
        {tgt:`Chame uma ambulância.`,src:`Ita ambulansi.`,pron:`SHA-mi U-ma am-bu-LAN-si-a`},
        {tgt:`Perdi minha carteira.`,src:`Nimepoteza pochi yangu.`,pron:`PER-dji MI-nya kar-TEI-ra`},
        {tgt:`Roubaram meu telefone.`,src:`Wameiba simu yangu.`,pron:`ho-BA-rang meu te-le-FO-ni`},
        {tgt:`É perigoso aqui?`,src:`Hapa ni hatari?`,pron:`e pe-ri-GO-zu a-KI`},
      ],
      conversation: [
      ],
    },
    {
      day: 25,
      title: `Hisia na maoni`,
      titleNative: `Sentimentos e opiniões`,
      focus: `Leo unajifunza kueleza unavyohisi na kutoa maoni rahisi. Hii inasaidia unapozungumza na wenyeji, mhudumu, au rafiki mpya wa safari.`,
      grammar: `Kwa hisia za muda mfupi, tumia “Estou”: “Estou cansado,” “Estou com fome.” Kwa maoni ya jumla, tumia “é”: “Português é difícil.” Vivumishi vingine hubadilika kulingana na msemaji au kitu, kama “cansado/cansada.”`,
      vocab: [
        {tgt:`feliz`,src:`mwenye furaha`,pron:`fe-LIZ`},
        {tgt:`cansado`,src:`mchovu, mwanaume`,pron:`kan-SA-du`},
        {tgt:`cansada`,src:`mchovu, mwanamke`,pron:`kan-SA-da`},
        {tgt:`com fome`,src:`mwenye njaa`,pron:`kong FO-mi`},
        {tgt:`com sede`,src:`mwenye kiu`,pron:`kong SE-dji`},
        {tgt:`gostoso`,src:`tamu, kiume`,pron:`gos-TO-zu`},
        {tgt:`gostosa`,src:`tamu, kike`,pron:`gos-TO-za`},
        {tgt:`interessante`,src:`ya kuvutia`,pron:`in-te-re-SAN-tshi`},
        {tgt:`difícil`,src:`ngumu`,pron:`dji-FI-sil`},
        {tgt:`fácil`,src:`rahisi`,pron:`FA-sil`},
      ],
      phrases: [
        {tgt:`Estou feliz.`,src:`Nina furaha.`,pron:`es-TO fe-LIZ`},
        {tgt:`Estou cansado.`,src:`Nimechoka, msemaji wa kiume.`,pron:`es-TO kan-SA-du`},
        {tgt:`Estou cansada.`,src:`Nimechoka, msemaji wa kike.`,pron:`es-TO kan-SA-da`},
        {tgt:`Estou com fome.`,src:`Nina njaa.`,pron:`es-TO kong FO-mi`},
        {tgt:`A comida é gostosa.`,src:`Chakula ni kitamu.`,pron:`a ko-MI-da e gos-TO-za`},
        {tgt:`Português é difícil, mas bonito.`,src:`Kireno ni kigumu, lakini kizuri.`,pron:`por-tu-GEZ e dji-FI-sil, mash bo-NI-tu`},
      ],
      conversation: [
      ],
    },
    {
      day: 26,
      title: `Vitenzi muhimu vya kila siku`,
      titleNative: `Verbos úteis do dia a dia`,
      focus: `Leo unajifunza vitenzi vinavyotokea kila siku safarini: kwenda, kuwa, kutaka, kuhitaji, kula, na kununua. Hivi vitakusaidia kujenga sentensi nyingi kwa urahisi.`,
      grammar: `Katika Kireno, unaweza kutumia kitenzi cha kwanza kilichobadilishwa kisha kitenzi cha pili kubaki katika umbo lake la msingi: “Quero comer,” “Preciso beber,” “Posso falar.” Hii ni rahisi kwa wanaoanza kwa sababu unahitaji kubadilisha kitenzi kimoja tu. “Vou comprar” hutumika kusema jambo la karibu la baadaye.`,
      vocab: [
        {tgt:`ir`,src:`kwenda`,pron:`ir`},
        {tgt:`ser`,src:`kuwa, hali ya kudumu`,pron:`ser`},
        {tgt:`estar`,src:`kuwa, hali ya muda/mahali`,pron:`es-TAR`},
        {tgt:`ter`,src:`kuwa na`,pron:`ter`},
        {tgt:`querer`,src:`kutaka`,pron:`ke-RER`},
        {tgt:`precisar`,src:`kuhitaji`,pron:`pre-si-ZAR`},
        {tgt:`comer`,src:`kula`,pron:`ko-MER`},
        {tgt:`beber`,src:`kunywa`,pron:`be-BER`},
        {tgt:`comprar`,src:`kununua`,pron:`kom-PRAR`},
        {tgt:`falar`,src:`kuzungumza`,pron:`fa-LAR`},
      ],
      phrases: [
        {tgt:`Eu quero comer.`,src:`Nataka kula.`,pron:`eu KE-ru ko-MER`},
        {tgt:`Preciso beber água.`,src:`Nahitaji kunywa maji.`,pron:`pre-SI-zu be-BER A-gwa`},
        {tgt:`Vou comprar pão.`,src:`Nitanunua mkate.`,pron:`vou kom-PRAR pau`},
        {tgt:`Posso falar português?`,src:`Naweza kuzungumza Kireno?`,pron:`PO-su fa-LAR por-tu-GESH`},
        {tgt:`Tenho que ir.`,src:`Lazima niende.`,pron:`TE-nyu ki ir`},
        {tgt:`Estou no hotel.`,src:`Niko hotelini.`,pron:`es-TO nu o-TEL`},
      ],
      conversation: [
      ],
    },
    {
      day: 27,
      title: `Kuuliza maswali bora`,
      titleNative: `Fazer perguntas melhores`,
      focus: `Leo unajifunza maneno ya maswali kama nani, nini, wapi, lini, kwa nini, na vipi. Haya yatakusaidia kupata taarifa sahihi ukiwa safarini.`,
      grammar: `Maneno ya maswali mara nyingi huja mwanzo wa sentensi, lakini Kireno cha mazungumzo kinaweza kuwa rahisi. “Onde fica...?” ni muundo wa kuuliza mahali, na “Quanto custa...?” ni wa kuuliza bei. “Como chego...” ni muhimu sana kwa maelekezo.`,
      vocab: [
        {tgt:`quem`,src:`nani`,pron:`keng`},
        {tgt:`o quê`,src:`nini`,pron:`u ke`},
        {tgt:`onde`,src:`wapi`,pron:`ON-dji`},
        {tgt:`quando`,src:`lini`,pron:`KWAN-du`},
        {tgt:`por que`,src:`kwa nini`,pron:`por ke`},
        {tgt:`como`,src:`vipi/jinsi gani`,pron:`KO-mu`},
        {tgt:`qual`,src:`ipi/lipi`,pron:`kwal`},
        {tgt:`quanto`,src:`kiasi gani`,pron:`KWAN-tu`},
        {tgt:`quantos`,src:`ngapi, kiume wingi`,pron:`KWAN-tush`},
        {tgt:`quantas`,src:`ngapi, kike wingi`,pron:`KWAN-tash`},
      ],
      phrases: [
        {tgt:`Quem é você?`,src:`Wewe ni nani?`,pron:`keng e vo-SE`},
        {tgt:`O que é isto?`,src:`Hiki ni nini?`,pron:`u ke e IS-tu`},
        {tgt:`Onde fica a estação?`,src:`Kituo kiko wapi?`,pron:`ON-dji FI-ka a es-ta-SAU`},
        {tgt:`Quando abre?`,src:`Inafunguliwa lini?`,pron:`KWAN-du A-bri`},
        {tgt:`Como chego ao hotel?`,src:`Nafikaje hotelini?`,pron:`KO-mu SHE-gu au o-TEL`},
        {tgt:`Quanto custa o bilhete?`,src:`Tiketi inagharimu kiasi gani?`,pron:`KWAN-tu KUSH-ta u bi-LYE-tshi`},
      ],
      conversation: [
      ],
    },
    {
      day: 28,
      title: `Kuelewa majibu na kuomba kurudiwa`,
      titleNative: `Entender respostas e pedir repetição`,
      focus: `Leo unajifunza kusema huelewi, kuomba mtu arudie, na kuomba aongee polepole. Hii ni moja ya ujuzi muhimu zaidi kwa mtalii anayejifunza Kireno.`,
      grammar: `“Pode...” ni njia yenye heshima ya kuomba kitendo: “Pode repetir?” “Pode escrever?” “Pode mostrar?” Unaweza kutumia muundo huu katika hali nyingi bila kujua sarufi nyingi. Kuomba kurudiwa si udhaifu; ni ujuzi muhimu wa mawasiliano.`,
      vocab: [
        {tgt:`entender`,src:`kuelewa`,pron:`en-ten-DER`},
        {tgt:`repetir`,src:`kurudia`,pron:`he-pe-TIR`},
        {tgt:`devagar`,src:`polepole`,pron:`dji-va-GAR`},
        {tgt:`rápido`,src:`haraka`,pron:`HA-pi-du`},
        {tgt:`mais`,src:`zaidi`,pron:`maish`},
        {tgt:`menos`,src:`kidogo`,pron:`ME-nush`},
        {tgt:`palavra`,src:`neno`,pron:`pa-LA-vra`},
        {tgt:`frase`,src:`sentensi`,pron:`FRA-zi`},
        {tgt:`escrever`,src:`kuandika`,pron:`es-kre-VER`},
        {tgt:`mostrar`,src:`kuonyesha`,pron:`mosh-TRAR`},
      ],
      phrases: [
        {tgt:`Não entendo.`,src:`Sielewi.`,pron:`nau en-TEN-du`},
        {tgt:`Pode repetir?`,src:`Unaweza kurudia?`,pron:`PO-dji he-pe-TIR`},
        {tgt:`Mais devagar, por favor.`,src:`Polepole zaidi, tafadhali.`,pron:`maish dji-va-GAR, por fa-VOR`},
        {tgt:`Pode escrever?`,src:`Unaweza kuandika?`,pron:`PO-dji es-kre-VER`},
        {tgt:`Pode mostrar no mapa?`,src:`Unaweza kuonyesha kwenye ramani?`,pron:`PO-dji mosh-TRAR nu MA-pa`},
        {tgt:`O que significa esta palavra?`,src:`Neno hili lina maana gani?`,pron:`u ke sig-ni-FI-ka ESH-ta pa-LA-vra`},
      ],
      conversation: [
      ],
    },
    {
      day: 29,
      title: `Kutatua matatizo ya safari`,
      titleNative: `Resolver problemas de viagem`,
      focus: `Leo unajifunza kushughulikia kuchelewa, kubadilisha tiketi, na kuuliza suluhisho. Hii ni muhimu vituoni, viwanja vya ndege, na hoteli.`,
      grammar: `Kwa jambo lililotokea tayari, mara nyingi utaona vitenzi vya wakati uliopita kama “foi cancelado” au “perdi.” Hata kama hujui wakati uliopita vizuri, kukariri sentensi hizi za safari kutakusaidia sana. “Qual é a solução?” ni swali la moja kwa moja lakini la heshima ukilitamka kwa utulivu.`,
      vocab: [
        {tgt:`atraso`,src:`kuchelewa`,pron:`a-TRA-zu`},
        {tgt:`cancelado`,src:`imefutwa, kiume`,pron:`kan-se-LA-du`},
        {tgt:`cancelada`,src:`imefutwa, kike`,pron:`kan-se-LA-da`},
        {tgt:`trocar`,src:`kubadilisha`,pron:`tro-KAR`},
        {tgt:`perder`,src:`kupoteza/kukosa`,pron:`per-DER`},
        {tgt:`voo`,src:`safari ya ndege`,pron:`vou`},
        {tgt:`conexão`,src:`muunganiko`,pron:`ko-ne-KSAU`},
        {tgt:`bagagem`,src:`mizigo`,pron:`ba-GA-zheng`},
        {tgt:`reclamação`,src:`malalamiko`,pron:`he-kla-ma-SAU`},
        {tgt:`solução`,src:`suluhisho`,pron:`so-lu-SAU`},
      ],
      phrases: [
        {tgt:`Meu voo foi cancelado.`,src:`Safari yangu ya ndege imefutwa.`,pron:`meu vou foi kan-se-LA-du`},
        {tgt:`O ônibus está atrasado.`,src:`Basi limechelewa.`,pron:`u O-ni-bus es-TA a-tra-ZA-du`},
        {tgt:`Perdi minha conexão.`,src:`Nimekosa muunganiko wangu.`,pron:`PER-dji MI-nya ko-ne-KSAU`},
        {tgt:`Preciso trocar meu bilhete.`,src:`Nahitaji kubadilisha tiketi yangu.`,pron:`pre-SI-zu tro-KAR meu bi-LYE-tshi`},
        {tgt:`Onde está minha bagagem?`,src:`Mizigo yangu iko wapi?`,pron:`ON-dji es-TA MI-nya ba-GA-zheng`},
        {tgt:`Qual é a solução?`,src:`Suluhisho ni lipi?`,pron:`kwal e a so-lu-SAU`},
      ],
      conversation: [
      ],
    },
    {
      day: 30,
      title: `Siku kamili ya safari`,
      titleNative: `Um dia completo de viagem`,
      focus: `Leo unaunganisha kila kitu: kuamka hotelini, kuagiza kahawa, kuuliza maelekezo, kununua tiketi, kula, na kurudi salama. Huu ni muhtasari wa vitendo kwa siku moja katika nchi inayozungumza Kireno.`,
      grammar: `Sasa unaweza kujenga siku nzima kwa kutumia miundo rahisi: “Quero...,” “Preciso...,” “Vou...,” “Onde fica...,” na “Quanto custa...?” Hizi ni nguzo za mawasiliano ya msafiri. Ukiwa huna uhakika, tumia sentensi fupi, tabasamu, na “por favor.”`,
      vocab: [
        {tgt:`manhã`,src:`asubuhi`,pron:`ma-NYANG`},
        {tgt:`tarde`,src:`mchana/jioni`,pron:`TAR-dji`},
        {tgt:`noite`,src:`usiku`,pron:`NOI-tshi`},
        {tgt:`cidade`,src:`mji`,pron:`si-DA-dji`},
        {tgt:`centro`,src:`mjini kati`,pron:`SEN-tru`},
        {tgt:`restaurante`,src:`mgahawa`,pron:`hes-tau-RAN-tshi`},
        {tgt:`hotel`,src:`hoteli`,pron:`o-TEL`},
        {tgt:`bilhete`,src:`tiketi`,pron:`bi-LYE-tshi`},
        {tgt:`ajuda`,src:`msaada`,pron:`a-ZHU-da`},
        {tgt:`voltar`,src:`kurudi`,pron:`vol-TAR`},
      ],
      phrases: [
        {tgt:`Bom dia, quero café.`,src:`Habari za asubuhi, nataka kahawa.`,pron:`bom JI-a, KE-ru ka-FE`},
        {tgt:`Vou ao centro hoje.`,src:`Nitaenda mjini kati leo.`,pron:`vou au SEN-tru O-zhi`},
        {tgt:`Como chego ao museu?`,src:`Nafikaje makumbusho?`,pron:`KO-mu SHE-gu au mu-ZEU`},
        {tgt:`Quero um bilhete, por favor.`,src:`Nataka tiketi moja, tafadhali.`,pron:`KE-ru ung bi-LYE-tshi, por fa-VOR`},
        {tgt:`Preciso voltar ao hotel.`,src:`Nahitaji kurudi hotelini.`,pron:`pre-SI-zu vol-TAR au o-TEL`},
        {tgt:`Obrigado pela ajuda.`,src:`Asante kwa msaada, msemaji wa kiume.`,pron:`o-bri-GA-du PE-la a-ZHU-da`},
      ],
      conversation: [
      ],
    },
  ]
};