var COURSE_FR_NL = [
{
  day: 1,
  title: "Salutations et premiers mots",
  titleNative: "Begroetingen en eerste woorden",
  focus: "Aujourd’hui, vous apprenez à saluer et à prendre congé aux Pays-Bas, par exemple en entrant dans un café à Amsterdam ou une boutique à Utrecht. L’objectif est de pouvoir commencer une interaction simplement et poliment.",
  vocab: [{ nl: "hallo", fr: "bonjour / salut", ipa: "/ˈɦɑ.loː/" }, { nl: "goedemorgen", fr: "bonjour, le matin", ipa: "/ˌɣu.dəˈmɔr.ɣə/" }, { nl: "goedemiddag", fr: "bonjour, l’après-midi", ipa: "/ˌɣu.dəˈmɪ.dɑx/" }, { nl: "goedenavond", fr: "bonsoir", ipa: "/ˌɣu.dəˈnaː.vɔnt/" }, { nl: "dag", fr: "bonjour / au revoir", ipa: "/dɑx/" }, { nl: "doei", fr: "salut / au revoir", ipa: "/dui/" }, { nl: "alsjeblieft", fr: "s’il te plaît", ipa: "/ˌɑl.ʃəˈblift/" }, { nl: "alstublieft", fr: "s’il vous plaît", ipa: "/ˌɑl.styˈblift/" }, { nl: "dank je", fr: "merci", ipa: "/dɑŋk jə/" }, { nl: "bedankt", fr: "merci", ipa: "/bəˈdɑŋkt/" }],
  phrases: [{ nl: "Hallo, hoe gaat het?", fr: "Bonjour, comment ça va ?", ipa: "/ˈɦɑ.loː ɦu ɣaːt ət/" }, { nl: "Goedemorgen!", fr: "Bonjour !", ipa: "/ˌɣu.dəˈmɔr.ɣə/" }, { nl: "Dank je wel.", fr: "Merci beaucoup.", ipa: "/dɑŋk jə ʋɛl/" }, { nl: "Tot ziens.", fr: "Au revoir.", ipa: "/tɔt zins/" }, { nl: "Fijne dag!", fr: "Bonne journée !", ipa: "/ˈfɛi.nə dɑx/" }, { nl: "Sorry.", fr: "Pardon / désolé.", ipa: "/ˈsɔ.ri/" }],
  grammar: "En néerlandais, il existe souvent une forme familière et une forme polie. « Alsjeblieft » s’utilise avec des personnes que l’on tutoie, tandis que « alstublieft » est plus poli ou formel. Pour un voyageur, « alstublieft » est un choix sûr dans les cafés, hôtels et magasins.",
  practice: ["Écrivez trois salutations adaptées à différents moments de la journée.", "Imaginez que vous entrez dans un café à Amsterdam : dites bonjour et merci.", "Répétez « goedemorgen », « goedemiddag » et « goedenavond » à voix haute.", "Choisissez la version polie entre « alsjeblieft » et « alstublieft » pour parler à un serveur.", "Créez une mini-conversation de deux lignes avec « Hallo » et « Tot ziens »."]
},
{
  day: 2,
  title: "Se présenter simplement",
  titleNative: "Jezelf voorstellen",
  focus: "Vous apprenez à dire votre nom, votre origine et quelques informations simples. C’est utile dans une auberge à Rotterdam, lors d’une visite guidée ou en rencontrant quelqu’un dans un train.",
  vocab: [{ nl: "ik", fr: "je / moi", ipa: "/ɪk/" }, { nl: "jij", fr: "tu", ipa: "/jɛi/" }, { nl: "u", fr: "vous", ipa: "/y/" }, { nl: "ben", fr: "suis", ipa: "/bɛn/" }, { nl: "heet", fr: "m’appelle / s’appelle", ipa: "/ɦeːt/" }, { nl: "naam", fr: "nom", ipa: "/naːm/" }, { nl: "Frankrijk", fr: "France", ipa: "/ˈfrɑŋk.rɛik/" }, { nl: "Frans", fr: "français", ipa: "/frɑns/" }, { nl: "Nederland", fr: "Pays-Bas", ipa: "/ˈneː.dər.lɑnt/" }, { nl: "aangenaam", fr: "enchanté", ipa: "/ˌaːn.ɣəˈnaːm/" }],
  phrases: [{ nl: "Ik heet Marie.", fr: "Je m’appelle Marie.", ipa: "/ɪk ɦeːt maːˈri/" }, { nl: "Mijn naam is Paul.", fr: "Mon nom est Paul.", ipa: "/mɛin naːm ɪs pɔl/" }, { nl: "Ik kom uit Frankrijk.", fr: "Je viens de France.", ipa: "/ɪk kɔm œyt ˈfrɑŋk.rɛik/" }, { nl: "Ik ben Frans.", fr: "Je suis français.", ipa: "/ɪk bɛn frɑns/" }, { nl: "Aangenaam.", fr: "Enchanté.", ipa: "/ˌaːn.ɣəˈnaːm/" }, { nl: "Hoe heet u?", fr: "Comment vous appelez-vous ?", ipa: "/ɦu ɦeːt y/" }],
  grammar: "Pour dire « je suis », on utilise « ik ben ». Pour dire « je m’appelle », on peut dire « ik heet » ou « mijn naam is ». Dans une situation polie, utilisez « u » au lieu de « jij ».",
  practice: ["Présentez-vous avec « Ik heet... ».", "Dites que vous venez de France avec « Ik kom uit Frankrijk ».", "Transformez « Hoe heet jij? » en version polie.", "Imaginez que vous rencontrez un guide à La Haye et dites « enchanté ».", "Écrivez trois phrases simples sur vous en néerlandais."]
},
{
  day: 3,
  title: "Oui, non et expressions essentielles",
  titleNative: "Ja, nee en belangrijke woorden",
  focus: "Vous apprenez les mots de survie qui permettent de répondre rapidement dans les situations quotidiennes. Ils servent partout : gare, hôtel, restaurant, musée ou marché.",
  vocab: [{ nl: "ja", fr: "oui", ipa: "/jaː/" }, { nl: "nee", fr: "non", ipa: "/neː/" }, { nl: "misschien", fr: "peut-être", ipa: "/mɪsˈxin/" }, { nl: "goed", fr: "bien / bon", ipa: "/ɣut/" }, { nl: "slecht", fr: "mauvais / mal", ipa: "/slɛxt/" }, { nl: "oké", fr: "d’accord", ipa: "/oːˈkeː/" }, { nl: "geen probleem", fr: "pas de problème", ipa: "/ɣeːn proːˈbleːm/" }, { nl: "natuurlijk", fr: "bien sûr", ipa: "/naːˈtyr.lək/" }, { nl: "sorry", fr: "désolé / pardon", ipa: "/ˈsɔ.ri/" }, { nl: "prima", fr: "très bien", ipa: "/ˈpri.maː/" }],
  phrases: [{ nl: "Ja, graag.", fr: "Oui, volontiers.", ipa: "/jaː ɣraːx/" }, { nl: "Nee, bedankt.", fr: "Non, merci.", ipa: "/neː bəˈdɑŋkt/" }, { nl: "Dat is goed.", fr: "C’est bien.", ipa: "/dɑt ɪs ɣut/" }, { nl: "Geen probleem.", fr: "Pas de problème.", ipa: "/ɣeːn proːˈbleːm/" }, { nl: "Het is oké.", fr: "C’est d’accord.", ipa: "/ɦət ɪs oːˈkeː/" }, { nl: "Natuurlijk.", fr: "Bien sûr.", ipa: "/naːˈtyr.lək/" }],
  grammar: "« Graag » est un mot très utile qui exprime une envie polie, comme « volontiers ». Dans un café, « Ja, graag » est plus naturel que simplement « ja ». Pour refuser poliment, « Nee, bedankt » est parfait.",
  practice: ["Répondez poliment oui à une offre de café.", "Répondez poliment non à une offre de dessert.", "Utilisez « geen probleem » dans une phrase courte.", "Associez « goed », « slecht » et « prima » à des situations de voyage.", "Faites une liste de cinq réponses rapides à mémoriser."]
},
{
  day: 4,
  title: "Les nombres de base",
  titleNative: "Basisnummers",
  focus: "Les nombres sont indispensables pour payer, réserver, prendre un ticket ou donner une adresse. Aujourd’hui, vous apprenez à compter jusqu’à vingt en néerlandais.",
  vocab: [{ nl: "nul", fr: "zéro", ipa: "/nʏl/" }, { nl: "een", fr: "un", ipa: "/eːn/" }, { nl: "twee", fr: "deux", ipa: "/tʋeː/" }, { nl: "drie", fr: "trois", ipa: "/dri/" }, { nl: "vier", fr: "quatre", ipa: "/vir/" }, { nl: "vijf", fr: "cinq", ipa: "/vɛif/" }, { nl: "zes", fr: "six", ipa: "/zɛs/" }, { nl: "zeven", fr: "sept", ipa: "/ˈzeː.və/" }, { nl: "acht", fr: "huit", ipa: "/ɑxt/" }, { nl: "negen", fr: "neuf", ipa: "/ˈneː.ɣə/" }],
  phrases: [{ nl: "Ik wil twee kaartjes.", fr: "Je veux deux billets.", ipa: "/ɪk ʋɪl tʋeː ˈkaːr.cəs/" }, { nl: "Eén koffie, alstublieft.", fr: "Un café, s’il vous plaît.", ipa: "/eːn ˈkɔ.fi ˌɑl.styˈblift/" }, { nl: "Dat kost vijf euro.", fr: "Cela coûte cinq euros.", ipa: "/dɑt kɔst vɛif ˈøː.roː/" }, { nl: "Ik heb drie dagen.", fr: "J’ai trois jours.", ipa: "/ɪk ɦɛp dri ˈdaː.ɣə/" }, { nl: "Nummer acht.", fr: "Numéro huit.", ipa: "/ˈnʏ.mər ɑxt/" }, { nl: "Twee personen.", fr: "Deux personnes.", ipa: "/tʋeː pɛrˈsoː.nə/" }],
  grammar: "En néerlandais, le chiffre « een » peut signifier « un » ou l’article indéfini « un/une ». À l’écrit, « één » avec accents insiste sur le nombre exact. À l’oral, le contexte suffit souvent.",
  practice: ["Comptez de zéro à dix à voix haute.", "Dites que vous voulez deux billets.", "Imaginez une réservation pour trois personnes.", "Écrivez cinq prix simples avec des nombres néerlandais.", "Répétez « vier », « vijf » et « zes » jusqu’à ce que la prononciation soit fluide."]
},
{
  day: 5,
  title: "Plus de nombres et prix",
  titleNative: "Meer nummers en prijzen",
  focus: "Vous apprenez les nombres utiles pour les prix, les chambres d’hôtel et les horaires. Cette leçon vous aide dans les marchés d’Amsterdam, les tramways et les musées.",
  vocab: [{ nl: "tien", fr: "dix", ipa: "/tin/" }, { nl: "elf", fr: "onze", ipa: "/ɛlf/" }, { nl: "twaalf", fr: "douze", ipa: "/tʋaːlf/" }, { nl: "dertien", fr: "treize", ipa: "/ˈdɛr.tin/" }, { nl: "veertien", fr: "quatorze", ipa: "/ˈveːr.tin/" }, { nl: "twintig", fr: "vingt", ipa: "/ˈtʋɪn.təx/" }, { nl: "dertig", fr: "trente", ipa: "/ˈdɛr.təx/" }, { nl: "vijftig", fr: "cinquante", ipa: "/ˈvɛif.təx/" }, { nl: "honderd", fr: "cent", ipa: "/ˈɦɔn.dərt/" }, { nl: "euro", fr: "euro", ipa: "/ˈøː.roː/" }],
  phrases: [{ nl: "Hoeveel kost dit?", fr: "Combien cela coûte-t-il ?", ipa: "/ɦuˈveːl kɔst dɪt/" }, { nl: "Dat is twintig euro.", fr: "Cela fait vingt euros.", ipa: "/dɑt ɪs ˈtʋɪn.təx ˈøː.roː/" }, { nl: "Ik betaal contant.", fr: "Je paie en espèces.", ipa: "/ɪk bəˈtaːl kɔnˈtɑnt/" }, { nl: "Ik betaal met kaart.", fr: "Je paie par carte.", ipa: "/ɪk bəˈtaːl mɛt kaːrt/" }, { nl: "Heeft u wisselgeld?", fr: "Avez-vous de la monnaie ?", ipa: "/ɦeːft y ˈʋɪ.səl.ɣɛlt/" }, { nl: "Dat is te duur.", fr: "C’est trop cher.", ipa: "/dɑt ɪs tə dyr/" }],
  grammar: "Pour demander le prix, utilisez « Hoeveel kost dit? ». Le mot « dit » signifie « ceci » et est très pratique lorsque vous montrez un objet. Dans les magasins néerlandais, le paiement par carte est très courant.",
  practice: ["Demandez le prix d’un souvenir.", "Dites que vous payez par carte.", "Écrivez trois prix en néerlandais.", "Pratiquez les nombres 10, 20, 30, 50 et 100.", "Imaginez une scène au marché Albert Cuyp et demandez le prix d’un fromage."]
},
{
  day: 6,
  title: "Jours, dates et temps",
  titleNative: "Dagen, datums en tijd",
  focus: "Vous apprenez à parler des jours et des moments de la journée. C’est utile pour réserver un billet de musée, planifier un trajet ou fixer un rendez-vous à Utrecht.",
  vocab: [{ nl: "vandaag", fr: "aujourd’hui", ipa: "/vɑnˈdaːx/" }, { nl: "morgen", fr: "demain", ipa: "/ˈmɔr.ɣə/" }, { nl: "gisteren", fr: "hier", ipa: "/ˈɣɪs.tə.rə/" }, { nl: "maandag", fr: "lundi", ipa: "/ˈmaːn.dɑx/" }, { nl: "dinsdag", fr: "mardi", ipa: "/ˈdɪns.dɑx/" }, { nl: "woensdag", fr: "mercredi", ipa: "/ˈʋuns.dɑx/" }, { nl: "donderdag", fr: "jeudi", ipa: "/ˈdɔn.dər.dɑx/" }, { nl: "vrijdag", fr: "vendredi", ipa: "/ˈvrɛi.dɑx/" }, { nl: "zaterdag", fr: "samedi", ipa: "/ˈzaː.tər.dɑx/" }, { nl: "zondag", fr: "dimanche", ipa: "/ˈzɔn.dɑx/" }],
  phrases: [{ nl: "Vandaag is maandag.", fr: "Aujourd’hui, c’est lundi.", ipa: "/vɑnˈdaːx ɪs ˈmaːn.dɑx/" }, { nl: "Ik kom morgen.", fr: "Je viens demain.", ipa: "/ɪk kɔm ˈmɔr.ɣə/" }, { nl: "Tot morgen.", fr: "À demain.", ipa: "/tɔt ˈmɔr.ɣə/" }, { nl: "Op vrijdag.", fr: "Le vendredi.", ipa: "/ɔp ˈvrɛi.dɑx/" }, { nl: "Wanneer is het open?", fr: "Quand est-ce ouvert ?", ipa: "/ʋɑˈneːr ɪs ət ˈoː.pə/" }, { nl: "Het is vandaag gesloten.", fr: "C’est fermé aujourd’hui.", ipa: "/ɦət ɪs vɑnˈdaːx ɣəˈsloː.tə/" }],
  grammar: "Pour les jours, on utilise souvent « op » pour dire « le » dans le sens d’un jour précis : « op vrijdag » signifie « le vendredi ». Les musées peuvent être fermés certains jours, donc « Wanneer is het open? » est une question très pratique.",
  practice: ["Dites quel jour on est aujourd’hui en néerlandais.", "Demandez quand un musée est ouvert.", "Écrivez une phrase avec « morgen ».", "Pratiquez tous les jours de la semaine dans l’ordre.", "Imaginez que vous réservez une visite pour vendredi."]
},
{
  day: 7,
  title: "À l’aéroport",
  titleNative: "Op de luchthaven",
  focus: "Vous apprenez le vocabulaire essentiel pour arriver à Schiphol, l’aéroport d’Amsterdam. Cette leçon couvre les bagages, les passeports et les questions simples à l’arrivée.",
  vocab: [{ nl: "luchthaven", fr: "aéroport", ipa: "/ˈlʏxt.ɦaː.və/" }, { nl: "paspoort", fr: "passeport", ipa: "/ˈpɑs.poːrt/" }, { nl: "bagage", fr: "bagages", ipa: "/baːˈɣaː.ʒə/" }, { nl: "koffer", fr: "valise", ipa: "/ˈkɔ.fər/" }, { nl: "poort", fr: "porte", ipa: "/poːrt/" }, { nl: "vlucht", fr: "vol", ipa: "/vlʏxt/" }, { nl: "aankomst", fr: "arrivée", ipa: "/ˈaːn.kɔmst/" }, { nl: "vertrek", fr: "départ", ipa: "/vərˈtrɛk/" }, { nl: "controle", fr: "contrôle", ipa: "/kɔnˈtroː.lə/" }, { nl: "trein", fr: "train", ipa: "/trɛin/" }],
  phrases: [{ nl: "Waar is de bagage?", fr: "Où sont les bagages ?", ipa: "/ʋaːr ɪs də baːˈɣaː.ʒə/" }, { nl: "Hier is mijn paspoort.", fr: "Voici mon passeport.", ipa: "/ɦir ɪs mɛin ˈpɑs.poːrt/" }, { nl: "Ik heb één koffer.", fr: "J’ai une valise.", ipa: "/ɪk ɦɛp eːn ˈkɔ.fər/" }, { nl: "Waar is de trein naar Amsterdam?", fr: "Où est le train pour Amsterdam ?", ipa: "/ʋaːr ɪs də trɛin naːr ˌɑm.stərˈdɑm/" }, { nl: "Mijn vlucht is laat.", fr: "Mon vol est en retard.", ipa: "/mɛin vlʏxt ɪs laːt/" }, { nl: "Ik zoek de uitgang.", fr: "Je cherche la sortie.", ipa: "/ɪk zuk də ˈœyt.ɣɑŋ/" }],
  grammar: "« Waar is...? » signifie « Où est...? » et fonctionne avec presque tous les lieux ou objets. Pour dire « je cherche », utilisez « ik zoek ». À l’aéroport, ces deux structures couvrent beaucoup de besoins immédiats.",
  practice: ["Demandez où sont les bagages.", "Dites que vous avez une valise.", "Demandez où est le train pour Amsterdam.", "Utilisez « ik zoek » avec trois lieux différents.", "Imaginez que votre vol est en retard et expliquez-le simplement."]
},
{
  day: 8,
  title: "Transports en ville",
  titleNative: "Vervoer in de stad",
  focus: "Vous apprenez à utiliser le tram, le métro, le bus et le train dans des villes comme Amsterdam, Rotterdam et La Haye. Le but est de demander un trajet et de comprendre les directions simples.",
  vocab: [{ nl: "tram", fr: "tramway", ipa: "/trɑm/" }, { nl: "metro", fr: "métro", ipa: "/ˈmeː.troː/" }, { nl: "bus", fr: "bus", ipa: "/bʏs/" }, { nl: "station", fr: "gare / station", ipa: "/stɑˈʃɔn/" }, { nl: "halte", fr: "arrêt", ipa: "/ˈɦɑl.tə/" }, { nl: "kaartje", fr: "billet", ipa: "/ˈkaːr.cə/" }, { nl: "richting", fr: "direction", ipa: "/ˈrɪx.tɪŋ/" }, { nl: "overstappen", fr: "changer", ipa: "/ˈoː.vər.stɑ.pə/" }, { nl: "centrum", fr: "centre-ville", ipa: "/ˈsɛn.trʏm/" }, { nl: "fiets", fr: "vélo", ipa: "/fits/" }],
  phrases: [{ nl: "Waar is de tramhalte?", fr: "Où est l’arrêt de tram ?", ipa: "/ʋaːr ɪs də ˈtrɑm.ɦɑl.tə/" }, { nl: "Ik wil een kaartje.", fr: "Je veux un billet.", ipa: "/ɪk ʋɪl ən ˈkaːr.cə/" }, { nl: "Moet ik overstappen?", fr: "Dois-je changer ?", ipa: "/mut ɪk ˈoː.vər.stɑ.pə/" }, { nl: "Welke richting?", fr: "Quelle direction ?", ipa: "/ˈʋɛl.kə ˈrɪx.tɪŋ/" }, { nl: "Naar het centrum, alstublieft.", fr: "Vers le centre-ville, s’il vous plaît.", ipa: "/naːr ət ˈsɛn.trʏm ˌɑl.styˈblift/" }, { nl: "Is dit de juiste bus?", fr: "Est-ce le bon bus ?", ipa: "/ɪs dɪt də ˈjœys.tə bʏs/" }],
  grammar: "« Naar » signifie « vers » ou « à » pour indiquer une destination. « Naar het centrum » veut dire « vers le centre-ville ». Pour vérifier un transport, « Is dit de juiste...? » est très utile.",
  practice: ["Demandez où se trouve l’arrêt de tram.", "Dites que vous voulez aller au centre-ville.", "Demandez si vous devez changer.", "Utilisez « naar » avec trois destinations.", "Imaginez que vous êtes à Rotterdam Centraal et demandez le bon métro."]
},
{
  day: 9,
  title: "Demander son chemin",
  titleNative: "De weg vragen",
  focus: "Vous apprenez à demander et comprendre des directions simples dans les rues néerlandaises. Cette leçon est utile dans les canaux d’Amsterdam, les ruelles de Delft ou près d’un musée.",
  vocab: [{ nl: "links", fr: "gauche", ipa: "/lɪŋks/" }, { nl: "rechts", fr: "droite", ipa: "/rɛxts/" }, { nl: "rechtdoor", fr: "tout droit", ipa: "/rɛxtˈdoːr/" }, { nl: "straat", fr: "rue", ipa: "/straːt/" }, { nl: "plein", fr: "place", ipa: "/plɛin/" }, { nl: "brug", fr: "pont", ipa: "/brʏx/" }, { nl: "kanaal", fr: "canal", ipa: "/kaːˈnaːl/" }, { nl: "museum", fr: "musée", ipa: "/myˈzeː.ʏm/" }, { nl: "dichtbij", fr: "près", ipa: "/ˈdɪxt.bɛi/" }, { nl: "ver weg", fr: "loin", ipa: "/vɛr ʋɛx/" }],
  phrases: [{ nl: "Waar is het museum?", fr: "Où est le musée ?", ipa: "/ʋaːr ɪs ət myˈzeː.ʏm/" }, { nl: "Ga rechtdoor.", fr: "Allez tout droit.", ipa: "/ɣaː rɛxtˈdoːr/" }, { nl: "Sla linksaf.", fr: "Tournez à gauche.", ipa: "/slaː ˈlɪŋks.ɑf/" }, { nl: "Sla rechtsaf.", fr: "Tournez à droite.", ipa: "/slaː ˈrɛxts.ɑf/" }, { nl: "Is het dichtbij?", fr: "Est-ce près ?", ipa: "/ɪs ət ˈdɪxt.bɛi/" }, { nl: "Het is bij de brug.", fr: "C’est près du pont.", ipa: "/ɦət ɪs bɛi də brʏx/" }],
  grammar: "Pour donner une direction, le néerlandais utilise souvent des verbes courts : « ga » pour « allez » et « sla » pour « tournez ». « Bij » signifie « près de » ou « chez » selon le contexte. Pour un lieu, « bij de brug » veut dire « près du pont ».",
  practice: ["Demandez où se trouve le musée.", "Donnez trois directions : tout droit, gauche, droite.", "Demandez si un lieu est proche.", "Décrivez un endroit près d’un pont.", "Imaginez que vous cherchez la place principale de Delft."]
},
{
  day: 10,
  title: "À l’hôtel",
  titleNative: "In het hotel",
  focus: "Vous apprenez à vous enregistrer dans un hôtel ou une maison d’hôtes aux Pays-Bas. Vous pourrez demander votre chambre, le Wi-Fi, le petit-déjeuner et l’heure de départ.",
  vocab: [{ nl: "hotel", fr: "hôtel", ipa: "/ɦoːˈtɛl/" }, { nl: "kamer", fr: "chambre", ipa: "/ˈkaː.mər/" }, { nl: "reservering", fr: "réservation", ipa: "/reː.zɛrˈveː.rɪŋ/" }, { nl: "sleutel", fr: "clé", ipa: "/ˈsløː.təl/" }, { nl: "ontbijt", fr: "petit-déjeuner", ipa: "/ˈɔnt.bɛit/" }, { nl: "wifi", fr: "Wi-Fi", ipa: "/ˈʋi.fi/" }, { nl: "receptie", fr: "réception", ipa: "/reˈsɛp.si/" }, { nl: "nacht", fr: "nuit", ipa: "/nɑxt/" }, { nl: "uitchecken", fr: "quitter l’hôtel", ipa: "/ˈœyt.tʃɛ.kə/" }, { nl: "lift", fr: "ascenseur", ipa: "/lɪft/" }],
  phrases: [{ nl: "Ik heb een reservering.", fr: "J’ai une réservation.", ipa: "/ɪk ɦɛp ən reː.zɛrˈveː.rɪŋ/" }, { nl: "Op naam van Dubois.", fr: "Au nom de Dubois.", ipa: "/ɔp naːm vɑn dyˈbʋa/" }, { nl: "Waar is mijn kamer?", fr: "Où est ma chambre ?", ipa: "/ʋaːr ɪs mɛin ˈkaː.mər/" }, { nl: "Wat is het wifi-wachtwoord?", fr: "Quel est le mot de passe Wi-Fi ?", ipa: "/ʋɑt ɪs ət ˈʋi.fi ˈʋɑxt.ʋoːrt/" }, { nl: "Is ontbijt inbegrepen?", fr: "Le petit-déjeuner est-il inclus ?", ipa: "/ɪs ˈɔnt.bɛit ˌɪn.bəˈɣreː.pə/" }, { nl: "Hoe laat is uitchecken?", fr: "À quelle heure est le départ ?", ipa: "/ɦu laːt ɪs ˈœyt.tʃɛ.kə/" }],
  grammar: "Pour dire « j’ai », utilisez « ik heb ». C’est essentiel pour les réservations : « Ik heb een reservering ». Pour demander une heure, « hoe laat » signifie « à quelle heure ».",
  practice: ["Dites que vous avez une réservation.", "Demandez le mot de passe Wi-Fi.", "Demandez si le petit-déjeuner est inclus.", "Épelez votre nom comme si vous étiez à la réception.", "Imaginez votre arrivée dans un hôtel à Haarlem."]
},
{
  day: 11,
  title: "Commander au café",
  titleNative: "Bestellen in een café",
  focus: "Vous apprenez à commander une boisson et une petite collation dans un café néerlandais. Cette leçon est pratique pour une pause à Amsterdam, Leiden ou Maastricht.",
  vocab: [{ nl: "koffie", fr: "café", ipa: "/ˈkɔ.fi/" }, { nl: "thee", fr: "thé", ipa: "/teː/" }, { nl: "water", fr: "eau", ipa: "/ˈʋaː.tər/" }, { nl: "melk", fr: "lait", ipa: "/mɛlk/" }, { nl: "suiker", fr: "sucre", ipa: "/ˈsœy.kər/" }, { nl: "taart", fr: "gâteau / tarte", ipa: "/taːrt/" }, { nl: "broodje", fr: "petit sandwich", ipa: "/ˈbroː.cə/" }, { nl: "menukaart", fr: "menu", ipa: "/ˈmeː.ny.kaːrt/" }, { nl: "terras", fr: "terrasse", ipa: "/tɛˈrɑs/" }, { nl: "rekening", fr: "addition", ipa: "/ˈreː.kə.nɪŋ/" }],
  phrases: [{ nl: "Een koffie, alstublieft.", fr: "Un café, s’il vous plaît.", ipa: "/ən ˈkɔ.fi ˌɑl.styˈblift/" }, { nl: "Mag ik de menukaart?", fr: "Puis-je avoir le menu ?", ipa: "/mɑx ɪk də ˈmeː.ny.kaːrt/" }, { nl: "Met melk, graag.", fr: "Avec du lait, s’il vous plaît.", ipa: "/mɛt mɛlk ɣraːx/" }, { nl: "Zonder suiker.", fr: "Sans sucre.", ipa: "/ˈzɔn.dər ˈsœy.kər/" }, { nl: "Voor hier of om mee te nemen?", fr: "Sur place ou à emporter ?", ipa: "/voːr ɦir ɔf ɔm meː tə ˈneː.mə/" }, { nl: "De rekening, alstublieft.", fr: "L’addition, s’il vous plaît.", ipa: "/də ˈreː.kə.nɪŋ ˌɑl.styˈblift/" }],
  grammar: "« Met » signifie « avec » et « zonder » signifie « sans ». Ces deux mots sont très pratiques pour commander exactement ce que vous voulez. « Graag » rend la demande plus polie et naturelle.",
  practice: ["Commandez un café avec du lait.", "Commandez un thé sans sucre.", "Demandez le menu.", "Répondez à la question « Voor hier of om mee te nemen? ».", "Demandez l’addition poliment."]
},
{
  day: 12,
  title: "Au restaurant",
  titleNative: "In het restaurant",
  focus: "Vous apprenez à réserver une table, commander un plat et parler simplement avec le serveur. Cette leçon est utile dans un restaurant à Utrecht ou près des canaux d’Amsterdam.",
  vocab: [{ nl: "restaurant", fr: "restaurant", ipa: "/rɛs.toːˈrɑnt/" }, { nl: "tafel", fr: "table", ipa: "/ˈtaː.fəl/" }, { nl: "menu", fr: "menu", ipa: "/meːˈny/" }, { nl: "gerecht", fr: "plat", ipa: "/ɣəˈrɛxt/" }, { nl: "soep", fr: "soupe", ipa: "/sup/" }, { nl: "vis", fr: "poisson", ipa: "/vɪs/" }, { nl: "vlees", fr: "viande", ipa: "/vleːs/" }, { nl: "groente", fr: "légumes", ipa: "/ˈɣrun.tə/" }, { nl: "dessert", fr: "dessert", ipa: "/dɛˈsɛr/" }, { nl: "fooi", fr: "pourboire", ipa: "/foːi/" }],
  phrases: [{ nl: "Een tafel voor twee, alstublieft.", fr: "Une table pour deux, s’il vous plaît.", ipa: "/ən ˈtaː.fəl voːr tʋeː ˌɑl.styˈblift/" }, { nl: "Heeft u een menu?", fr: "Avez-vous un menu ?", ipa: "/ɦeːft y ən meːˈny/" }, { nl: "Wat raadt u aan?", fr: "Que recommandez-vous ?", ipa: "/ʋɑt raːt y aːn/" }, { nl: "Ik neem de vis.", fr: "Je prends le poisson.", ipa: "/ɪk neːm də vɪs/" }, { nl: "Het was heerlijk.", fr: "C’était délicieux.", ipa: "/ɦət ʋɑs ˈɦeːr.lək/" }, { nl: "Mag ik betalen?", fr: "Puis-je payer ?", ipa: "/mɑx ɪk bəˈtaː.lə/" }],
  grammar: "« Ik neem... » signifie « je prends... » et est très naturel au restaurant. Le verbe « nemen » est souvent utilisé pour commander. Pour demander une recommandation, « Wat raadt u aan? » est une phrase polie et utile.",
  practice: ["Demandez une table pour deux.", "Commandez un plat de poisson.", "Demandez une recommandation au serveur.", "Dites que le repas était délicieux.", "Imaginez que vous payez à la fin du repas."]
},
{
  day: 13,
  title: "Régimes et allergies",
  titleNative: "Diëten en allergieën",
  focus: "Vous apprenez à expliquer des besoins alimentaires importants. Cette leçon peut éviter des problèmes dans les restaurants, marchés et cafés des Pays-Bas.",
  vocab: [{ nl: "allergie", fr: "allergie", ipa: "/ɑ.lɛrˈɣi/" }, { nl: "noten", fr: "noix", ipa: "/ˈnoː.tə/" }, { nl: "pinda’s", fr: "cacahuètes", ipa: "/ˈpɪn.daːs/" }, { nl: "melk", fr: "lait", ipa: "/mɛlk/" }, { nl: "gluten", fr: "gluten", ipa: "/ˈɣly.tə/" }, { nl: "vegetarisch", fr: "végétarien", ipa: "/veː.ɣeːˈtaː.ris/" }, { nl: "veganistisch", fr: "végane", ipa: "/veː.ɣaːˈnɪs.tis/" }, { nl: "zonder", fr: "sans", ipa: "/ˈzɔn.dər/" }, { nl: "gevaarlijk", fr: "dangereux", ipa: "/ɣəˈvaːr.lək/" }, { nl: "ingrediënten", fr: "ingrédients", ipa: "/ɪn.ɣreː.diˈjɛn.tə/" }],
  phrases: [{ nl: "Ik heb een allergie.", fr: "J’ai une allergie.", ipa: "/ɪk ɦɛp ən ɑ.lɛrˈɣi/" }, { nl: "Ik ben allergisch voor noten.", fr: "Je suis allergique aux noix.", ipa: "/ɪk bɛn ɑˈlɛr.ɣis voːr ˈnoː.tə/" }, { nl: "Is dit vegetarisch?", fr: "Est-ce végétarien ?", ipa: "/ɪs dɪt veː.ɣeːˈtaː.ris/" }, { nl: "Zonder melk, alstublieft.", fr: "Sans lait, s’il vous plaît.", ipa: "/ˈzɔn.dər mɛlk ˌɑl.styˈblift/" }, { nl: "Wat zit erin?", fr: "Qu’y a-t-il dedans ?", ipa: "/ʋɑt zɪt ɛrˈɪn/" }, { nl: "Dat is gevaarlijk voor mij.", fr: "C’est dangereux pour moi.", ipa: "/dɑt ɪs ɣəˈvaːr.lək voːr mɛi/" }],
  grammar: "Pour dire « allergique à », on dit « allergisch voor ». Le mot « voor » signifie ici « à » ou « pour ». Si l’allergie est grave, dites clairement « Dat is gevaarlijk voor mij ».",
  practice: ["Dites que vous avez une allergie.", "Demandez si un plat est végétarien.", "Dites « sans lait » et « sans gluten ».", "Demandez ce qu’il y a dans un plat.", "Préparez une phrase d’urgence pour votre allergie personnelle."]
},
{
  day: 14,
  title: "Faire les courses au marché",
  titleNative: "Boodschappen doen op de markt",
  focus: "Vous apprenez à acheter des produits frais sur un marché néerlandais. Cette leçon convient très bien au marché Albert Cuyp à Amsterdam ou au Markthal de Rotterdam.",
  vocab: [{ nl: "markt", fr: "marché", ipa: "/mɑrkt/" }, { nl: "kaas", fr: "fromage", ipa: "/kaːs/" }, { nl: "brood", fr: "pain", ipa: "/broːt/" }, { nl: "appel", fr: "pomme", ipa: "/ˈɑ.pəl/" }, { nl: "aardbei", fr: "fraise", ipa: "/ˈaːrt.bɛi/" }, { nl: "tomaat", fr: "tomate", ipa: "/toːˈmaːt/" }, { nl: "hoeveel", fr: "combien", ipa: "/ɦuˈveːl/" }, { nl: "kilo", fr: "kilo", ipa: "/ˈki.loː/" }, { nl: "zak", fr: "sac", ipa: "/zɑk/" }, { nl: "vers", fr: "frais", ipa: "/vɛrs/" }],
  phrases: [{ nl: "Hoeveel kost een kilo?", fr: "Combien coûte un kilo ?", ipa: "/ɦuˈveːl kɔst ən ˈki.loː/" }, { nl: "Ik wil graag kaas.", fr: "Je voudrais du fromage.", ipa: "/ɪk ʋɪl ɣraːx kaːs/" }, { nl: "Is het vers?", fr: "Est-ce frais ?", ipa: "/ɪs ət vɛrs/" }, { nl: "Mag ik een zak?", fr: "Puis-je avoir un sac ?", ipa: "/mɑx ɪk ən zɑk/" }, { nl: "Een beetje, alstublieft.", fr: "Un peu, s’il vous plaît.", ipa: "/ən ˈbeː.tjə ˌɑl.styˈblift/" }, { nl: "Dat is alles.", fr: "C’est tout.", ipa: "/dɑt ɪs ˈɑ.ləs/" }],
  grammar: "« Ik wil graag... » signifie « je voudrais... » et sonne plus poli que « je veux ». Sur un marché, cette formule est très pratique. Pour une petite quantité, dites « een beetje ».",
  practice: ["Achetez du fromage au marché.", "Demandez le prix d’un kilo de fraises.", "Demandez si le pain est frais.", "Dites que c’est tout.", "Imaginez une conversation courte avec un vendeur à Rotterdam."]
},
{
  day: 15,
  title: "Acheter dans une boutique",
  titleNative: "Winkelen in een winkel",
  focus: "Vous apprenez à acheter des vêtements, souvenirs ou objets pratiques. Cette leçon vous aide dans les boutiques de Maastricht, Amsterdam ou La Haye.",
  vocab: [{ nl: "winkel", fr: "magasin", ipa: "/ˈʋɪŋ.kəl/" }, { nl: "kleding", fr: "vêtements", ipa: "/ˈkleː.dɪŋ/" }, { nl: "schoen", fr: "chaussure", ipa: "/sxun/" }, { nl: "jas", fr: "manteau", ipa: "/jɑs/" }, { nl: "maat", fr: "taille / pointure", ipa: "/maːt/" }, { nl: "kleur", fr: "couleur", ipa: "/kløːr/" }, { nl: "prijs", fr: "prix", ipa: "/prɛis/" }, { nl: "passen", fr: "essayer", ipa: "/ˈpɑ.sə/" }, { nl: "bon", fr: "ticket de caisse", ipa: "/bɔn/" }, { nl: "cadeau", fr: "cadeau", ipa: "/kaːˈdoː/" }],
  phrases: [{ nl: "Mag ik dit passen?", fr: "Puis-je essayer ceci ?", ipa: "/mɑx ɪk dɪt ˈpɑ.sə/" }, { nl: "Heeft u een andere maat?", fr: "Avez-vous une autre taille ?", ipa: "/ɦeːft y ən ˈɑn.də.rə maːt/" }, { nl: "Welke kleuren heeft u?", fr: "Quelles couleurs avez-vous ?", ipa: "/ˈʋɛl.kə ˈkløː.rə ɦeːft y/" }, { nl: "Ik zoek een cadeau.", fr: "Je cherche un cadeau.", ipa: "/ɪk zuk ən kaːˈdoː/" }, { nl: "Ik neem deze.", fr: "Je prends celui-ci / celle-ci.", ipa: "/ɪk neːm ˈdeː.zə/" }, { nl: "Mag ik de bon?", fr: "Puis-je avoir le ticket ?", ipa: "/mɑx ɪk də bɔn/" }],
  grammar: "« Deze » signifie « celui-ci / celle-ci » pour un objet proche. « Dit » signifie « ceci » et fonctionne très bien quand vous montrez un article. Dans une boutique, « Mag ik...? » est une façon polie de demander.",
  practice: ["Demandez à essayer une veste.", "Demandez une autre taille.", "Dites que vous cherchez un cadeau.", "Choisissez un objet avec « Ik neem deze ».", "Demandez le ticket de caisse."]
},
{
  day: 16,
  title: "Couleurs et descriptions",
  titleNative: "Kleuren en beschrijvingen",
  focus: "Vous apprenez à décrire des objets, vêtements et lieux. Cela vous aide à faire du shopping, demander un objet perdu ou expliquer ce que vous cherchez.",
  vocab: [{ nl: "rood", fr: "rouge", ipa: "/roːt/" }, { nl: "blauw", fr: "bleu", ipa: "/blɑu/" }, { nl: "groen", fr: "vert", ipa: "/ɣrun/" }, { nl: "geel", fr: "jaune", ipa: "/ɣeːl/" }, { nl: "zwart", fr: "noir", ipa: "/zʋɑrt/" }, { nl: "wit", fr: "blanc", ipa: "/ʋɪt/" }, { nl: "groot", fr: "grand", ipa: "/ɣroːt/" }, { nl: "klein", fr: "petit", ipa: "/klɛin/" }, { nl: "mooi", fr: "beau / joli", ipa: "/moːi/" }, { nl: "nieuw", fr: "nouveau", ipa: "/niu/" }],
  phrases: [{ nl: "Ik zoek een zwarte jas.", fr: "Je cherche un manteau noir.", ipa: "/ɪk zuk ən ˈzʋɑr.tə jɑs/" }, { nl: "Heeft u dit in blauw?", fr: "Avez-vous ceci en bleu ?", ipa: "/ɦeːft y dɪt ɪn blɑu/" }, { nl: "Het is te groot.", fr: "C’est trop grand.", ipa: "/ɦət ɪs tə ɣroːt/" }, { nl: "Het is te klein.", fr: "C’est trop petit.", ipa: "/ɦət ɪs tə klɛin/" }, { nl: "Dat is mooi.", fr: "C’est joli.", ipa: "/dɑt ɪs moːi/" }, { nl: "Ik wil iets nieuws.", fr: "Je veux quelque chose de nouveau.", ipa: "/ɪk ʋɪl its niu/" }],
  grammar: "Les adjectifs peuvent changer légèrement devant un nom : « zwart » devient souvent « zwarte » dans « een zwarte jas ». Pour voyager, il n’est pas nécessaire de maîtriser toutes les règles immédiatement ; mémorisez quelques expressions utiles comme des blocs.",
  practice: ["Décrivez un manteau avec une couleur.", "Demandez si un article existe en bleu.", "Dites qu’un vêtement est trop grand.", "Choisissez trois objets autour de vous et décrivez-les en néerlandais.", "Écrivez une phrase avec « mooi »."]
},
{
  day: 17,
  title: "À la pharmacie",
  titleNative: "Bij de apotheek",
  focus: "Vous apprenez à expliquer un problème simple de santé dans une pharmacie néerlandaise. Cette leçon est utile pour acheter des médicaments courants ou demander conseil.",
  vocab: [{ nl: "apotheek", fr: "pharmacie", ipa: "/aː.poːˈteːk/" }, { nl: "medicijn", fr: "médicament", ipa: "/meː.diˈsɛin/" }, { nl: "hoofdpijn", fr: "mal de tête", ipa: "/ˈɦoːft.pɛin/" }, { nl: "buikpijn", fr: "mal au ventre", ipa: "/ˈbœyk.pɛin/" }, { nl: "keelpijn", fr: "mal de gorge", ipa: "/ˈkeːl.pɛin/" }, { nl: "koorts", fr: "fièvre", ipa: "/koːrts/" }, { nl: "verkoudheid", fr: "rhume", ipa: "/vərˈkɑut.ɦɛit/" }, { nl: "pleister", fr: "pansement", ipa: "/ˈplɛis.tər/" }, { nl: "dokter", fr: "médecin", ipa: "/ˈdɔk.tər/" }, { nl: "hulp", fr: "aide", ipa: "/ɦʏlp/" }],
  phrases: [{ nl: "Ik heb hoofdpijn.", fr: "J’ai mal à la tête.", ipa: "/ɪk ɦɛp ˈɦoːft.pɛin/" }, { nl: "Ik ben verkouden.", fr: "Je suis enrhumé.", ipa: "/ɪk bɛn vərˈkɑu.də/" }, { nl: "Heeft u iets tegen keelpijn?", fr: "Avez-vous quelque chose contre le mal de gorge ?", ipa: "/ɦeːft y its ˈteː.ɣə ˈkeːl.pɛin/" }, { nl: "Ik heb hulp nodig.", fr: "J’ai besoin d’aide.", ipa: "/ɪk ɦɛp ɦʏlp ˈnoː.dəx/" }, { nl: "Waar is de apotheek?", fr: "Où est la pharmacie ?", ipa: "/ʋaːr ɪs də aː.poːˈteːk/" }, { nl: "Moet ik naar de dokter?", fr: "Dois-je aller chez le médecin ?", ipa: "/mut ɪk naːr də ˈdɔk.tər/" }],
  grammar: "Pour parler d’une douleur, le néerlandais utilise souvent « ik heb » suivi du type de douleur : « ik heb hoofdpijn ». Pour demander un produit, « Heeft u iets tegen...? » signifie « Avez-vous quelque chose contre...? ».",
  practice: ["Dites que vous avez mal à la tête.", "Demandez quelque chose contre le mal de gorge.", "Demandez où est la pharmacie.", "Dites que vous avez besoin d’aide.", "Imaginez une courte interaction avec un pharmacien à Amsterdam."]
},
{
  day: 18,
  title: "Urgences et problèmes",
  titleNative: "Noodgevallen en problemen",
  focus: "Vous apprenez les phrases importantes en cas de problème : objet perdu, urgence, besoin d’aide ou situation stressante. L’objectif est de parler clairement et simplement.",
  vocab: [{ nl: "noodgeval", fr: "urgence", ipa: "/ˈnoːt.ɣə.vɑl/" }, { nl: "politie", fr: "police", ipa: "/poːˈli.tsi/" }, { nl: "ziekenhuis", fr: "hôpital", ipa: "/ˈzi.kə.ɦœys/" }, { nl: "ambulance", fr: "ambulance", ipa: "/ɑm.byˈlɑns/" }, { nl: "verloren", fr: "perdu", ipa: "/vərˈloː.rə/" }, { nl: "gestolen", fr: "volé", ipa: "/ɣəˈstoː.lə/" }, { nl: "tas", fr: "sac", ipa: "/tɑs/" }, { nl: "telefoon", fr: "téléphone", ipa: "/teː.ləˈfoːn/" }, { nl: "help", fr: "aide / au secours", ipa: "/ɦɛlp/" }, { nl: "veilig", fr: "sûr / en sécurité", ipa: "/ˈvɛi.ləx/" }],
  phrases: [{ nl: "Help, alstublieft!", fr: "Aidez-moi, s’il vous plaît !", ipa: "/ɦɛlp ˌɑl.styˈblift/" }, { nl: "Ik ben mijn tas kwijt.", fr: "J’ai perdu mon sac.", ipa: "/ɪk bɛn mɛin tɑs kʋɛit/" }, { nl: "Mijn telefoon is gestolen.", fr: "Mon téléphone a été volé.", ipa: "/mɛin teː.ləˈfoːn ɪs ɣəˈstoː.lə/" }, { nl: "Bel de politie.", fr: "Appelez la police.", ipa: "/bɛl də poːˈli.tsi/" }, { nl: "Waar is het ziekenhuis?", fr: "Où est l’hôpital ?", ipa: "/ʋaːr ɪs ət ˈzi.kə.ɦœys/" }, { nl: "Ik voel me niet veilig.", fr: "Je ne me sens pas en sécurité.", ipa: "/ɪk vul mə nit ˈvɛi.ləx/" }],
  grammar: "« Kwijt zijn » signifie « avoir perdu » dans le sens de ne plus retrouver quelque chose. La phrase « Ik ben mijn tas kwijt » est très naturelle. Pour un objet volé, utilisez « gestolen ».",
  practice: ["Dites que vous avez perdu votre sac.", "Dites que votre téléphone a été volé.", "Demandez où est l’hôpital.", "Pratiquez une phrase pour demander de l’aide rapidement.", "Écrivez deux phrases que vous voudriez mémoriser pour une urgence."]
},
{
  day: 19,
  title: "Parler de soi et de ses goûts",
  titleNative: "Over jezelf en je smaak praten",
  focus: "Vous apprenez à parler de ce que vous aimez ou n’aimez pas. Cette leçon aide à faire connaissance avec des locaux, d’autres voyageurs ou un guide.",
  vocab: [{ nl: "leuk", fr: "sympa / amusant", ipa: "/løːk/" }, { nl: "lekker", fr: "bon, délicieux", ipa: "/ˈlɛ.kər/" }, { nl: "mooi", fr: "beau", ipa: "/moːi/" }, { nl: "interessant", fr: "intéressant", ipa: "/ɪn.tə.rɛˈsɑnt/" }, { nl: "muziek", fr: "musique", ipa: "/myˈzik/" }, { nl: "kunst", fr: "art", ipa: "/kʏnst/" }, { nl: "reizen", fr: "voyager", ipa: "/ˈrɛi.zə/" }, { nl: "eten", fr: "manger / nourriture", ipa: "/ˈeː.tə/" }, { nl: "drinken", fr: "boire", ipa: "/ˈdrɪŋ.kə/" }, { nl: "wandelen", fr: "se promener", ipa: "/ˈʋɑn.də.lə/" }],
  phrases: [{ nl: "Ik hou van muziek.", fr: "J’aime la musique.", ipa: "/ɪk ɦɑu vɑn myˈzik/" }, { nl: "Ik vind dit leuk.", fr: "Je trouve ça sympa.", ipa: "/ɪk vɪnt dɪt løːk/" }, { nl: "Ik vind het lekker.", fr: "Je trouve ça bon.", ipa: "/ɪk vɪnt ət ˈlɛ.kər/" }, { nl: "Ik hou niet van bier.", fr: "Je n’aime pas la bière.", ipa: "/ɪk ɦɑu nit vɑn bir/" }, { nl: "Dat is interessant.", fr: "C’est intéressant.", ipa: "/dɑt ɪs ɪn.tə.rɛˈsɑnt/" }, { nl: "Ik wandel graag.", fr: "J’aime me promener.", ipa: "/ɪk ˈʋɑn.dəl ɣraːx/" }],
  grammar: "« Ik hou van... » signifie « j’aime... » pour des choses générales. « Ik vind... » signifie « je trouve... » et sert à donner une opinion. Pour la nourriture, « lekker » est très important : cela veut dire « bon » ou « délicieux ».",
  practice: ["Dites que vous aimez la musique.", "Dites que vous aimez vous promener.", "Donnez votre opinion sur un café avec « leuk ».", "Dites que quelque chose est délicieux.", "Écrivez trois phrases sur vos goûts de voyage."]
},
{
  day: 20,
  title: "Invitations et socialisation",
  titleNative: "Uitnodigingen en sociaal contact",
  focus: "Vous apprenez à accepter, refuser et proposer une activité simple. Cette leçon est utile si vous rencontrez quelqu’un dans un café, une auberge ou lors d’une visite guidée.",
  vocab: [{ nl: "samen", fr: "ensemble", ipa: "/ˈsaː.mə/" }, { nl: "vandaag", fr: "aujourd’hui", ipa: "/vɑnˈdaːx/" }, { nl: "vanavond", fr: "ce soir", ipa: "/vɑnˈaː.vɔnt/" }, { nl: "tijd", fr: "temps", ipa: "/tɛit/" }, { nl: "drankje", fr: "boisson", ipa: "/ˈdrɑŋ.kjə/" }, { nl: "wandeling", fr: "promenade", ipa: "/ˈʋɑn.də.lɪŋ/" }, { nl: "afspraak", fr: "rendez-vous", ipa: "/ˈɑf.spraːk/" }, { nl: "gezellig", fr: "convivial / agréable", ipa: "/ɣəˈzɛ.ləx/" }, { nl: "later", fr: "plus tard", ipa: "/ˈlaː.tər/" }, { nl: "druk", fr: "occupé", ipa: "/drʏk/" }],
  phrases: [{ nl: "Heb je tijd?", fr: "As-tu le temps ?", ipa: "/ɦɛp jə tɛit/" }, { nl: "Zullen we samen koffie drinken?", fr: "On prend un café ensemble ?", ipa: "/ˈzʏ.lə ʋə ˈsaː.mə ˈkɔ.fi ˈdrɪŋ.kə/" }, { nl: "Dat lijkt me leuk.", fr: "Ça me semble sympa.", ipa: "/dɑt lɛikt mə løːk/" }, { nl: "Sorry, ik ben druk.", fr: "Désolé, je suis occupé.", ipa: "/ˈsɔ.ri ɪk bɛn drʏk/" }, { nl: "Misschien later.", fr: "Peut-être plus tard.", ipa: "/mɪsˈxin ˈlaː.tər/" }, { nl: "Het was gezellig.", fr: "C’était agréable.", ipa: "/ɦət ʋɑs ɣəˈzɛ.ləx/" }],
  grammar: "Le mot « gezellig » est très néerlandais et difficile à traduire exactement. Il décrit une ambiance chaleureuse, conviviale ou agréable. Vous l’entendrez souvent après un café, un dîner ou une soirée réussie.",
  practice: ["Proposez de prendre un café ensemble.", "Acceptez une invitation naturellement.", "Refusez poliment parce que vous êtes occupé.", "Utilisez « gezellig » dans une phrase.", "Imaginez une invitation après une visite guidée à Utrecht."]
},
{
  day: 21,
  title: "Météo et vêtements",
  titleNative: "Weer en kleding",
  focus: "Vous apprenez à parler de la météo, un sujet courant aux Pays-Bas. C’est aussi pratique pour choisir vos vêtements avant une promenade à vélo ou au bord des canaux.",
  vocab: [{ nl: "weer", fr: "météo / temps", ipa: "/ʋeːr/" }, { nl: "regen", fr: "pluie", ipa: "/ˈreː.ɣə/" }, { nl: "zon", fr: "soleil", ipa: "/zɔn/" }, { nl: "wind", fr: "vent", ipa: "/ʋɪnt/" }, { nl: "koud", fr: "froid", ipa: "/kɑut/" }, { nl: "warm", fr: "chaud", ipa: "/ʋɑrm/" }, { nl: "jas", fr: "manteau", ipa: "/jɑs/" }, { nl: "paraplu", fr: "parapluie", ipa: "/paː.raːˈply/" }, { nl: "schoenen", fr: "chaussures", ipa: "/ˈsxu.nə/" }, { nl: "trui", fr: "pull", ipa: "/trœy/" }],
  phrases: [{ nl: "Hoe is het weer?", fr: "Quel temps fait-il ?", ipa: "/ɦu ɪs ət ʋeːr/" }, { nl: "Het regent.", fr: "Il pleut.", ipa: "/ɦət ˈreː.ɣənt/" }, { nl: "Het is koud vandaag.", fr: "Il fait froid aujourd’hui.", ipa: "/ɦət ɪs kɑut vɑnˈdaːx/" }, { nl: "Ik heb een paraplu nodig.", fr: "J’ai besoin d’un parapluie.", ipa: "/ɪk ɦɛp ən paː.raːˈply ˈnoː.dəx/" }, { nl: "De zon schijnt.", fr: "Le soleil brille.", ipa: "/də zɔn sxɛint/" }, { nl: "Het waait hard.", fr: "Il y a beaucoup de vent.", ipa: "/ɦət ʋaːit ɦɑrt/" }],
  grammar: "Pour parler du temps, le néerlandais utilise souvent « het » comme sujet impersonnel : « het regent », « het waait », « het is koud ». Cela ressemble au français « il pleut » ou « il fait froid ».",
  practice: ["Dites qu’il pleut.", "Dites qu’il fait froid aujourd’hui.", "Demandez la météo.", "Dites que vous avez besoin d’un parapluie.", "Décrivez le temps idéal pour une balade à vélo."]
},
{
  day: 22,
  title: "Louer un vélo",
  titleNative: "Een fiets huren",
  focus: "Le vélo fait partie de la vie quotidienne aux Pays-Bas. Vous apprenez à louer un vélo, demander le prix et comprendre les règles de base.",
  vocab: [{ nl: "fiets", fr: "vélo", ipa: "/fits/" }, { nl: "huren", fr: "louer", ipa: "/ˈɦy.rə/" }, { nl: "fietspad", fr: "piste cyclable", ipa: "/ˈfits.pɑt/" }, { nl: "slot", fr: "cadenas", ipa: "/slɔt/" }, { nl: "helm", fr: "casque", ipa: "/ɦɛlm/" }, { nl: "rem", fr: "frein", ipa: "/rɛm/" }, { nl: "uur", fr: "heure", ipa: "/yr/" }, { nl: "dag", fr: "jour", ipa: "/dɑx/" }, { nl: "kaart", fr: "carte / plan", ipa: "/kaːrt/" }, { nl: "veiligheid", fr: "sécurité", ipa: "/ˈvɛi.ləx.ɦɛit/" }],
  phrases: [{ nl: "Ik wil een fiets huren.", fr: "Je veux louer un vélo.", ipa: "/ɪk ʋɪl ən fits ˈɦy.rə/" }, { nl: "Hoeveel kost het per dag?", fr: "Combien cela coûte par jour ?", ipa: "/ɦuˈveːl kɔst ət pɛr dɑx/" }, { nl: "Heeft u een slot?", fr: "Avez-vous un cadenas ?", ipa: "/ɦeːft y ən slɔt/" }, { nl: "Waar is het fietspad?", fr: "Où est la piste cyclable ?", ipa: "/ʋaːr ɪs ət ˈfits.pɑt/" }, { nl: "Is dit veilig?", fr: "Est-ce sûr ?", ipa: "/ɪs dɪt ˈvɛi.ləx/" }, { nl: "Ik breng de fiets morgen terug.", fr: "Je rapporte le vélo demain.", ipa: "/ɪk brɛŋ də fits ˈmɔr.ɣə trʏx/" }],
  grammar: "Le verbe « huren » signifie « louer ». Pour dire « par jour », utilisez « per dag ». Dans les villes néerlandaises, respectez toujours les pistes cyclables et faites attention aux autres cyclistes.",
  practice: ["Dites que vous voulez louer un vélo.", "Demandez le prix par jour.", "Demandez un cadenas.", "Demandez où se trouve la piste cyclable.", "Imaginez que vous rapportez le vélo demain."]
},
{
  day: 23,
  title: "Musées et billets",
  titleNative: "Musea en kaartjes",
  focus: "Vous apprenez à acheter des billets pour un musée ou une attraction. Cette leçon est utile au Rijksmuseum, au Van Gogh Museum ou dans les musées de La Haye.",
  vocab: [{ nl: "museum", fr: "musée", ipa: "/myˈzeː.ʏm/" }, { nl: "kaartje", fr: "billet", ipa: "/ˈkaːr.cə/" }, { nl: "ingang", fr: "entrée", ipa: "/ˈɪn.ɣɑŋ/" }, { nl: "uitgang", fr: "sortie", ipa: "/ˈœyt.ɣɑŋ/" }, { nl: "tentoonstelling", fr: "exposition", ipa: "/tɛnˈtoːn.stɛ.lɪŋ/" }, { nl: "volwassene", fr: "adulte", ipa: "/ˈvɔl.ʋɑ.sə.nə/" }, { nl: "student", fr: "étudiant", ipa: "/styˈdɛnt/" }, { nl: "korting", fr: "réduction", ipa: "/ˈkɔr.tɪŋ/" }, { nl: "open", fr: "ouvert", ipa: "/ˈoː.pə/" }, { nl: "gesloten", fr: "fermé", ipa: "/ɣəˈsloː.tə/" }],
  phrases: [{ nl: "Twee kaartjes, alstublieft.", fr: "Deux billets, s’il vous plaît.", ipa: "/tʋeː ˈkaːr.cəs ˌɑl.styˈblift/" }, { nl: "Is er studentenkorting?", fr: "Y a-t-il une réduction étudiant ?", ipa: "/ɪs ɛr styˈdɛn.tə.kɔr.tɪŋ/" }, { nl: "Waar is de ingang?", fr: "Où est l’entrée ?", ipa: "/ʋaːr ɪs də ˈɪn.ɣɑŋ/" }, { nl: "Hoe laat sluit het museum?", fr: "À quelle heure le musée ferme-t-il ?", ipa: "/ɦu laːt slœyt ət myˈzeː.ʏm/" }, { nl: "Mag ik foto’s maken?", fr: "Puis-je prendre des photos ?", ipa: "/mɑx ɪk ˈfoː.toːs ˈmaː.kə/" }, { nl: "De tentoonstelling is mooi.", fr: "L’exposition est belle.", ipa: "/də tɛnˈtoːn.stɛ.lɪŋ ɪs moːi/" }],
  grammar: "« Er is » signifie « il y a ». Dans une question, cela devient « Is er...? ». C’est très pratique pour demander s’il y a une réduction, une place libre ou une exposition spéciale.",
  practice: ["Demandez deux billets.", "Demandez s’il y a une réduction étudiant.", "Demandez où se trouve l’entrée.", "Demandez si les photos sont autorisées.", "Décrivez une exposition comme belle ou intéressante."]
},
{
  day: 24,
  title: "Téléphone, Internet et technologie",
  titleNative: "Telefoon, internet en technologie",
  focus: "Vous apprenez à résoudre des petits problèmes de téléphone, Wi-Fi et batterie. C’est utile dans un hôtel, un café ou une gare.",
  vocab: [{ nl: "telefoon", fr: "téléphone", ipa: "/teː.ləˈfoːn/" }, { nl: "internet", fr: "Internet", ipa: "/ˈɪn.tər.nɛt/" }, { nl: "wifi", fr: "Wi-Fi", ipa: "/ˈʋi.fi/" }, { nl: "wachtwoord", fr: "mot de passe", ipa: "/ˈʋɑxt.ʋoːrt/" }, { nl: "batterij", fr: "batterie", ipa: "/bɑ.təˈrɛi/" }, { nl: "oplader", fr: "chargeur", ipa: "/ˈɔp.laː.dər/" }, { nl: "stopcontact", fr: "prise électrique", ipa: "/ˈstɔp.kɔn.tɑkt/" }, { nl: "simkaart", fr: "carte SIM", ipa: "/ˈsɪm.kaːrt/" }, { nl: "bericht", fr: "message", ipa: "/bəˈrɪxt/" }, { nl: "kaart", fr: "carte / plan", ipa: "/kaːrt/" }],
  phrases: [{ nl: "Wat is het wifi-wachtwoord?", fr: "Quel est le mot de passe Wi-Fi ?", ipa: "/ʋɑt ɪs ət ˈʋi.fi ˈʋɑxt.ʋoːrt/" }, { nl: "Mijn batterij is leeg.", fr: "Ma batterie est vide.", ipa: "/mɛin bɑ.təˈrɛi ɪs leːx/" }, { nl: "Heeft u een oplader?", fr: "Avez-vous un chargeur ?", ipa: "/ɦeːft y ən ˈɔp.laː.dər/" }, { nl: "Waar is een stopcontact?", fr: "Où est une prise ?", ipa: "/ʋaːr ɪs ən ˈstɔp.kɔn.tɑkt/" }, { nl: "Ik heb geen internet.", fr: "Je n’ai pas Internet.", ipa: "/ɪk ɦɛp ɣeːn ˈɪn.tər.nɛt/" }, { nl: "Ik kan de kaart niet openen.", fr: "Je ne peux pas ouvrir la carte.", ipa: "/ɪk kɑn də kaːrt nit ˈoː.pə.nə/" }],
  grammar: "« Geen » signifie « pas de » ou « aucun » devant un nom : « geen internet », « geen tijd », « geen probleem ». Pour dire que vous ne pouvez pas faire quelque chose, utilisez « ik kan niet ».",
  practice: ["Demandez le mot de passe Wi-Fi.", "Dites que votre batterie est vide.", "Demandez où est une prise.", "Dites que vous n’avez pas Internet.", "Faites une phrase avec « ik kan niet »."]
},
{
  day: 25,
  title: "Banques, argent et paiement",
  titleNative: "Bank, geld en betalen",
  focus: "Vous apprenez à parler d’argent, de distributeurs et de paiements. Cette leçon est utile dans les magasins, restaurants et gares des Pays-Bas.",
  vocab: [{ nl: "geld", fr: "argent", ipa: "/ɣɛlt/" }, { nl: "bank", fr: "banque", ipa: "/bɑŋk/" }, { nl: "pinautomaat", fr: "distributeur automatique", ipa: "/ˈpɪn.ɑu.toː.maːt/" }, { nl: "kaart", fr: "carte bancaire", ipa: "/kaːrt/" }, { nl: "contant", fr: "espèces", ipa: "/kɔnˈtɑnt/" }, { nl: "betalen", fr: "payer", ipa: "/bəˈtaː.lə/" }, { nl: "bon", fr: "reçu", ipa: "/bɔn/" }, { nl: "rekening", fr: "compte / addition", ipa: "/ˈreː.kə.nɪŋ/" }, { nl: "wisselen", fr: "changer", ipa: "/ˈʋɪ.sə.lə/" }, { nl: "bedrag", fr: "montant", ipa: "/bəˈdrɑx/" }],
  phrases: [{ nl: "Kan ik met kaart betalen?", fr: "Puis-je payer par carte ?", ipa: "/kɑn ɪk mɛt kaːrt bəˈtaː.lə/" }, { nl: "Waar is een pinautomaat?", fr: "Où est un distributeur ?", ipa: "/ʋaːr ɪs ən ˈpɪn.ɑu.toː.maːt/" }, { nl: "Ik heb contant geld nodig.", fr: "J’ai besoin d’espèces.", ipa: "/ɪk ɦɛp kɔnˈtɑnt ɣɛlt ˈnoː.dəx/" }, { nl: "Mag ik de bon?", fr: "Puis-je avoir le reçu ?", ipa: "/mɑx ɪk də bɔn/" }, { nl: "Het bedrag klopt niet.", fr: "Le montant n’est pas correct.", ipa: "/ɦət bəˈdrɑx klɔpt nit/" }, { nl: "Kunt u geld wisselen?", fr: "Pouvez-vous changer de l’argent ?", ipa: "/kʏnt y ɣɛlt ˈʋɪ.sə.lə/" }],
  grammar: "« Kan ik...? » signifie « puis-je...? » et est très utile pour demander une possibilité. La forme plus polie « Kunt u...? » signifie « pouvez-vous...? ». Dans les interactions de service, « Kunt u » sonne plus respectueux.",
  practice: ["Demandez si vous pouvez payer par carte.", "Demandez où se trouve un distributeur.", "Dites que vous avez besoin d’espèces.", "Expliquez que le montant n’est pas correct.", "Demandez un reçu."]
},
{
  day: 26,
  title: "À la gare",
  titleNative: "Op het station",
  focus: "Vous apprenez à acheter un billet de train et comprendre les informations de base à la gare. Cette leçon est utile pour voyager entre Amsterdam, Rotterdam, Utrecht et La Haye.",
  vocab: [{ nl: "station", fr: "gare", ipa: "/stɑˈʃɔn/" }, { nl: "trein", fr: "train", ipa: "/trɛin/" }, { nl: "spoor", fr: "voie", ipa: "/spoːr/" }, { nl: "perron", fr: "quai", ipa: "/pɛˈrɔn/" }, { nl: "kaartje", fr: "billet", ipa: "/ˈkaːr.cə/" }, { nl: "retour", fr: "aller-retour", ipa: "/rəˈtur/" }, { nl: "enkele reis", fr: "aller simple", ipa: "/ˈɛŋ.kə.lə rɛis/" }, { nl: "vertraging", fr: "retard", ipa: "/vərˈtraː.ɣɪŋ/" }, { nl: "aankomst", fr: "arrivée", ipa: "/ˈaːn.kɔmst/" }, { nl: "vertrek", fr: "départ", ipa: "/vərˈtrɛk/" }],
  phrases: [{ nl: "Een enkele reis naar Utrecht.", fr: "Un aller simple pour Utrecht.", ipa: "/ən ˈɛŋ.kə.lə rɛis naːr ˈy.trɛxt/" }, { nl: "Een retour naar Amsterdam.", fr: "Un aller-retour pour Amsterdam.", ipa: "/ən rəˈtur naːr ˌɑm.stərˈdɑm/" }, { nl: "Van welk spoor vertrekt de trein?", fr: "De quelle voie part le train ?", ipa: "/vɑn ʋɛlk spoːr vərˈtrɛkt də trɛin/" }, { nl: "Is er vertraging?", fr: "Y a-t-il du retard ?", ipa: "/ɪs ɛr vərˈtraː.ɣɪŋ/" }, { nl: "Waar is perron drie?", fr: "Où est le quai trois ?", ipa: "/ʋaːr ɪs pɛˈrɔn dri/" }, { nl: "Ik moet naar Rotterdam.", fr: "Je dois aller à Rotterdam.", ipa: "/ɪk mut naːr ˌrɔ.tərˈdɑm/" }],
  grammar: "« Moeten » signifie « devoir ». « Ik moet naar Rotterdam » veut dire « je dois aller à Rotterdam ». À la gare, cette phrase est simple et efficace si vous avez besoin d’aide.",
  practice: ["Demandez un aller simple pour Utrecht.", "Demandez de quelle voie part le train.", "Demandez s’il y a du retard.", "Dites que vous devez aller à Rotterdam.", "Imaginez que vous cherchez le quai trois."]
},
{
  day: 27,
  title: "Logement et problèmes pratiques",
  titleNative: "Accommodatie en praktische problemen",
  focus: "Vous apprenez à signaler un problème dans votre chambre ou votre logement. Cette leçon est utile dans un hôtel, Airbnb ou auberge à Amsterdam, Leiden ou Groningen.",
  vocab: [{ nl: "kamer", fr: "chambre", ipa: "/ˈkaː.mər/" }, { nl: "probleem", fr: "problème", ipa: "/proːˈbleːm/" }, { nl: "douche", fr: "douche", ipa: "/duʃ/" }, { nl: "wc", fr: "toilettes", ipa: "/ʋeːˈseː/" }, { nl: "verwarming", fr: "chauffage", ipa: "/vərˈʋɑr.mɪŋ/" }, { nl: "airco", fr: "climatisation", ipa: "/ˈɛir.koː/" }, { nl: "lawaai", fr: "bruit", ipa: "/laːˈʋaːi/" }, { nl: "schoon", fr: "propre", ipa: "/sxoːn/" }, { nl: "vies", fr: "sale", ipa: "/vis/" }, { nl: "repareren", fr: "réparer", ipa: "/reː.paːˈreː.rə/" }],
  phrases: [{ nl: "Er is een probleem met mijn kamer.", fr: "Il y a un problème avec ma chambre.", ipa: "/ɛr ɪs ən proːˈbleːm mɛt mɛin ˈkaː.mər/" }, { nl: "De douche werkt niet.", fr: "La douche ne fonctionne pas.", ipa: "/də duʃ ʋɛrkt nit/" }, { nl: "De kamer is vies.", fr: "La chambre est sale.", ipa: "/də ˈkaː.mər ɪs vis/" }, { nl: "Het is te koud.", fr: "Il fait trop froid.", ipa: "/ɦət ɪs tə kɑut/" }, { nl: "Er is veel lawaai.", fr: "Il y a beaucoup de bruit.", ipa: "/ɛr ɪs veːl laːˈʋaːi/" }, { nl: "Kunt u dit repareren?", fr: "Pouvez-vous réparer cela ?", ipa: "/kʏnt y dɪt reː.paːˈreː.rə/" }],
  grammar: "« Er is » sert à dire « il y a » pour un problème ou une situation. Pour dire qu’un appareil ne fonctionne pas, utilisez « werkt niet ». Ces phrases sont directes sans être impolies.",
  practice: ["Signalez un problème avec votre chambre.", "Dites que la douche ne fonctionne pas.", "Dites qu’il y a beaucoup de bruit.", "Demandez si quelqu’un peut réparer cela.", "Imaginez une conversation avec la réception d’un hôtel."]
},
{
  day: 28,
  title: "Comprendre les panneaux et règles",
  titleNative: "Borden en regels begrijpen",
  focus: "Vous apprenez à comprendre des mots fréquents sur les panneaux dans les gares, musées, rues et magasins. Cela vous aide à vous déplacer sans toujours demander de l’aide.",
  vocab: [{ nl: "ingang", fr: "entrée", ipa: "/ˈɪn.ɣɑŋ/" }, { nl: "uitgang", fr: "sortie", ipa: "/ˈœyt.ɣɑŋ/" }, { nl: "verboden", fr: "interdit", ipa: "/vərˈboː.də/" }, { nl: "open", fr: "ouvert", ipa: "/ˈoː.pə/" }, { nl: "gesloten", fr: "fermé", ipa: "/ɣəˈsloː.tə/" }, { nl: "duwen", fr: "pousser", ipa: "/ˈdy.ʋə/" }, { nl: "trekken", fr: "tirer", ipa: "/ˈtrɛ.kə/" }, { nl: "stilte", fr: "silence", ipa: "/ˈstɪl.tə/" }, { nl: "nooduitgang", fr: "sortie de secours", ipa: "/ˈnoːt.œyt.ɣɑŋ/" }, { nl: "wachtrij", fr: "file d’attente", ipa: "/ˈʋɑxt.rɛi/" }],
  phrases: [{ nl: "Waar is de uitgang?", fr: "Où est la sortie ?", ipa: "/ʋaːr ɪs də ˈœyt.ɣɑŋ/" }, { nl: "Is het open?", fr: "Est-ce ouvert ?", ipa: "/ɪs ət ˈoː.pə/" }, { nl: "Het is gesloten.", fr: "C’est fermé.", ipa: "/ɦət ɪs ɣəˈsloː.tə/" }, { nl: "Dat is verboden.", fr: "C’est interdit.", ipa: "/dɑt ɪs vərˈboː.də/" }, { nl: "Moet ik duwen of trekken?", fr: "Dois-je pousser ou tirer ?", ipa: "/mut ɪk ˈdy.ʋə ɔf ˈtrɛ.kə/" }, { nl: "Waar is de wachtrij?", fr: "Où est la file d’attente ?", ipa: "/ʋaːr ɪs də ˈʋɑxt.rɛi/" }],
  grammar: "Les panneaux utilisent souvent des mots très courts ou des formes impersonnelles. « Verboden » signifie « interdit » et peut être combiné avec d’autres mots. Pour un voyageur, reconnaître ces mots est aussi important que parler.",
  practice: ["Traduisez cinq panneaux possibles dans une gare.", "Demandez où est la sortie.", "Dites qu’un lieu est fermé.", "Pratiquez « duwen » et « trekken » en les associant à une porte.", "Imaginez que vous cherchez la file d’attente dans un musée."]
},
{
  day: 29,
  title: "Conversations plus naturelles",
  titleNative: "Natuurlijkere gesprekken",
  focus: "Vous apprenez à rendre vos conversations plus fluides avec des mots de liaison et des réactions simples. Cela vous aide à paraître plus naturel avec les habitants.",
  vocab: [{ nl: "maar", fr: "mais", ipa: "/maːr/" }, { nl: "en", fr: "et", ipa: "/ɛn/" }, { nl: "of", fr: "ou", ipa: "/ɔf/" }, { nl: "want", fr: "parce que / car", ipa: "/ʋɑnt/" }, { nl: "dus", fr: "donc", ipa: "/dʏs/" }, { nl: "ook", fr: "aussi", ipa: "/oːk/" }, { nl: "echt", fr: "vraiment", ipa: "/ɛxt/" }, { nl: "zeker", fr: "certainement", ipa: "/ˈzeː.kər/" }, { nl: "even", fr: "un instant / rapidement", ipa: "/ˈeː.və/" }, { nl: "klaar", fr: "prêt / terminé", ipa: "/klaːr/" }],
  phrases: [{ nl: "Ik spreek een beetje Nederlands.", fr: "Je parle un peu néerlandais.", ipa: "/ɪk spreːk ən ˈbeː.tjə ˈneː.dər.lɑnts/" }, { nl: "Kunt u langzamer spreken?", fr: "Pouvez-vous parler plus lentement ?", ipa: "/kʏnt y ˈlɑŋ.zaː.mər ˈspreː.kə/" }, { nl: "Ik begrijp het niet.", fr: "Je ne comprends pas.", ipa: "/ɪk bəˈɣrɛip ət nit/" }, { nl: "Dat klopt.", fr: "C’est correct.", ipa: "/dɑt klɔpt/" }, { nl: "Echt waar?", fr: "Vraiment ?", ipa: "/ɛxt ʋaːr/" }, { nl: "Ik ben klaar.", fr: "J’ai terminé / je suis prêt.", ipa: "/ɪk bɛn klaːr/" }],
  grammar: "Les mots comme « maar », « dus » et « want » rendent vos phrases plus naturelles. Même avec un niveau débutant, vous pouvez relier deux idées : « Ik wil koffie, maar zonder suiker ». Demander de parler plus lentement est aussi une vraie compétence de conversation.",
  practice: ["Dites que vous parlez un peu néerlandais.", "Demandez à quelqu’un de parler plus lentement.", "Faites une phrase avec « maar ».", "Réagissez avec « Echt waar? ».", "Écrivez trois phrases liées avec « en », « maar » ou « want »."]
},
{
  day: 30,
  title: "Révision de voyage complète",
  titleNative: "Volledige reisreview",
  focus: "Vous combinez tout ce que vous avez appris pour gérer une journée complète aux Pays-Bas : hôtel, café, transport, musée, restaurant et petite conversation. L’objectif est de parler simplement mais avec confiance.",
  vocab: [{ nl: "reis", fr: "voyage", ipa: "/rɛis/" }, { nl: "stad", fr: "ville", ipa: "/stɑt/" }, { nl: "plan", fr: "plan", ipa: "/plɑn/" }, { nl: "vandaag", fr: "aujourd’hui", ipa: "/vɑnˈdaːx/" }, { nl: "morgen", fr: "demain", ipa: "/ˈmɔr.ɣə/" }, { nl: "kaartje", fr: "billet", ipa: "/ˈkaːr.cə/" }, { nl: "rekening", fr: "addition", ipa: "/ˈreː.kə.nɪŋ/" }, { nl: "hulp", fr: "aide", ipa: "/ɦʏlp/" }, { nl: "gezellig", fr: "agréable / convivial", ipa: "/ɣəˈzɛ.ləx/" }, { nl: "bedankt", fr: "merci", ipa: "/bəˈdɑŋkt/" }],
  phrases: [{ nl: "Ik ben op reis in Nederland.", fr: "Je voyage aux Pays-Bas.", ipa: "/ɪk bɛn ɔp rɛis ɪn ˈneː.dər.lɑnt/" }, { nl: "Ik zoek het station.", fr: "Je cherche la gare.", ipa: "/ɪk zuk ət stɑˈʃɔn/" }, { nl: "Mag ik twee kaartjes?", fr: "Puis-je avoir deux billets ?", ipa: "/mɑx ɪk tʋeː ˈkaːr.cəs/" }, { nl: "Ik wil graag iets eten.", fr: "Je voudrais manger quelque chose.", ipa: "/ɪk ʋɪl ɣraːx its ˈeː.tə/" }, { nl: "Kunt u mij helpen?", fr: "Pouvez-vous m’aider ?", ipa: "/kʏnt y mɛi ˈɦɛl.pə/" }, { nl: "Het was een gezellige dag.", fr: "C’était une journée agréable.", ipa: "/ɦət ʋɑs ən ɣəˈzɛ.lə.ɣə dɑx/" }],
  grammar: "Pour votre révision, concentrez-vous sur les structures les plus utiles : « ik wil graag », « waar is », « kunt u », « ik heb » et « mag ik ». Avec ces blocs, vous pouvez construire de nombreuses phrases de voyage. La précision parfaite viendra plus tard ; en voyage, la clarté compte d’abord.",
  practice: ["Présentez-vous comme voyageur aux Pays-Bas.", "Demandez de l’aide pour trouver la gare.", "Commandez quelque chose à manger et à boire.", "Achetez deux billets pour un musée.", "Décrivez votre journée avec trois phrases simples en néerlandais."]
}
];

var CONVERSATIONS_FR_NL = [
{ title: "Commander dans un café à Amsterdam", scene: "Vous entrez dans un petit café près d’un canal à Amsterdam. Vous voulez commander une boisson chaude et quelque chose de simple à manger.", lines: [{ who: "them", nl: "Goedemorgen, wat wilt u bestellen?", fr: "Bonjour, que voulez-vous commander ?" }, { who: "you", nl: "Goedemorgen, een koffie alstublieft.", fr: "Bonjour, un café s’il vous plaît." }, { who: "them", nl: "Met melk of zonder melk?", fr: "Avec du lait ou sans lait ?" }, { who: "you", nl: "Met melk, graag.", fr: "Avec du lait, s’il vous plaît." }, { who: "them", nl: "Wilt u ook iets eten?", fr: "Voulez-vous aussi manger quelque chose ?" }, { who: "you", nl: "Ja, een broodje kaas, alstublieft.", fr: "Oui, un sandwich au fromage, s’il vous plaît." }, { who: "them", nl: "Voor hier of om mee te nemen?", fr: "Sur place ou à emporter ?" }, { who: "you", nl: "Voor hier, graag.", fr: "Sur place, s’il vous plaît." }, { who: "them", nl: "Dat is acht euro.", fr: "Cela fait huit euros." }, { who: "you", nl: "Kan ik met kaart betalen?", fr: "Puis-je payer par carte ?" }, { who: "them", nl: "Ja, natuurlijk.", fr: "Oui, bien sûr." }, { who: "you", nl: "Dank u wel.", fr: "Merci beaucoup." }] },
{ title: "Arrivée à l’hôtel à Rotterdam", scene: "Vous arrivez à votre hôtel à Rotterdam après un trajet en train. Vous devez vous enregistrer et demander les informations pratiques.", lines: [{ who: "them", nl: "Goedenavond, welkom in ons hotel.", fr: "Bonsoir, bienvenue dans notre hôtel." }, { who: "you", nl: "Goedenavond, ik heb een reservering.", fr: "Bonsoir, j’ai une réservation." }, { who: "them", nl: "Op welke naam?", fr: "À quel nom ?" }, { who: "you", nl: "Op naam van Martin.", fr: "Au nom de Martin." }, { who: "them", nl: "Mag ik uw paspoort zien?", fr: "Puis-je voir votre passeport ?" }, { who: "you", nl: "Ja, hier is mijn paspoort.", fr: "Oui, voici mon passeport." }, { who: "them", nl: "Uw kamer is op de derde verdieping.", fr: "Votre chambre est au troisième étage." }, { who: "you", nl: "Dank u, wat is het wifi-wachtwoord?", fr: "Merci, quel est le mot de passe Wi-Fi ?" }, { who: "them", nl: "Het wachtwoord is welkom2026.", fr: "Le mot de passe est welkom2026." }, { who: "you", nl: "Is ontbijt inbegrepen?", fr: "Le petit-déjeuner est-il inclus ?" }, { who: "them", nl: "Ja, ontbijt is van zeven tot tien.", fr: "Oui, le petit-déjeuner est de sept heures à dix heures." }, { who: "you", nl: "Perfect, bedankt.", fr: "Parfait, merci." }] },
{ title: "Demander son chemin à Utrecht", scene: "Vous êtes dans le centre d’Utrecht et vous cherchez la cathédrale Domtoren. Vous demandez votre chemin à une personne dans la rue.", lines: [{ who: "you", nl: "Sorry, kunt u mij helpen?", fr: "Pardon, pouvez-vous m’aider ?" }, { who: "them", nl: "Ja, natuurlijk.", fr: "Oui, bien sûr." }, { who: "you", nl: "Waar is de Domtoren?", fr: "Où est la tour Dom ?" }, { who: "them", nl: "Ga rechtdoor en dan linksaf.", fr: "Allez tout droit puis tournez à gauche." }, { who: "you", nl: "Is het dichtbij?", fr: "Est-ce proche ?" }, { who: "them", nl: "Ja, ongeveer vijf minuten lopen.", fr: "Oui, environ cinq minutes à pied." }, { who: "you", nl: "Moet ik over de brug?", fr: "Dois-je passer sur le pont ?" }, { who: "them", nl: "Nee, blijf aan deze kant van het kanaal.", fr: "Non, restez de ce côté du canal." }, { who: "you", nl: "Dank u wel.", fr: "Merci beaucoup." }, { who: "them", nl: "Geen probleem, fijne dag.", fr: "Pas de problème, bonne journée." }, { who: "you", nl: "Fijne dag!", fr: "Bonne journée !" }] },
{ title: "Dîner dans un restaurant à La Haye", scene: "Vous êtes dans un restaurant à La Haye et vous voulez une table pour deux. Vous demandez une recommandation et commandez simplement.", lines: [{ who: "them", nl: "Goedenavond, heeft u gereserveerd?", fr: "Bonsoir, avez-vous réservé ?" }, { who: "you", nl: "Nee, heeft u een tafel voor twee?", fr: "Non, avez-vous une table pour deux ?" }, { who: "them", nl: "Ja, natuurlijk, komt u maar mee.", fr: "Oui, bien sûr, suivez-moi." }, { who: "you", nl: "Mag ik de menukaart?", fr: "Puis-je avoir le menu ?" }, { who: "them", nl: "Natuurlijk, hier is de menukaart.", fr: "Bien sûr, voici le menu." }, { who: "you", nl: "Wat raadt u aan?", fr: "Que recommandez-vous ?" }, { who: "them", nl: "De vis is vandaag erg goed.", fr: "Le poisson est très bon aujourd’hui." }, { who: "you", nl: "Dan neem ik de vis.", fr: "Alors je prends le poisson." }, { who: "them", nl: "Wilt u iets drinken?", fr: "Voulez-vous boire quelque chose ?" }, { who: "you", nl: "Water, alstublieft.", fr: "De l’eau, s’il vous plaît." }, { who: "them", nl: "Prima, ik kom zo terug.", fr: "Très bien, je reviens tout de suite." }, { who: "you", nl: "Dank u wel.", fr: "Merci beaucoup." }] },
{ title: "Acheter un billet de train", scene: "Vous êtes à Amsterdam Centraal et vous voulez aller à Rotterdam. Vous demandez un billet et vérifiez la voie de départ.", lines: [{ who: "them", nl: "Goedemiddag, waar wilt u naartoe?", fr: "Bonjour, où voulez-vous aller ?" }, { who: "you", nl: "Ik wil naar Rotterdam, alstublieft.", fr: "Je veux aller à Rotterdam, s’il vous plaît." }, { who: "them", nl: "Enkele reis of retour?", fr: "Aller simple ou aller-retour ?" }, { who: "you", nl: "Een retour, graag.", fr: "Un aller-retour, s’il vous plaît." }, { who: "them", nl: "Dat is vijfentwintig euro.", fr: "Cela fait vingt-cinq euros." }, { who: "you", nl: "Kan ik met kaart betalen?", fr: "Puis-je payer par carte ?" }, { who: "them", nl: "Ja, dat kan.", fr: "Oui, c’est possible." }, { who: "you", nl: "Van welk spoor vertrekt de trein?", fr: "De quelle voie part le train ?" }, { who: "them", nl: "De trein vertrekt van spoor vier.", fr: "Le train part de la voie quatre." }, { who: "you", nl: "Is er vertraging?", fr: "Y a-t-il du retard ?" }, { who: "them", nl: "Nee, de trein is op tijd.", fr: "Non, le train est à l’heure." }, { who: "you", nl: "Bedankt voor uw hulp.", fr: "Merci pour votre aide." }] },
{ title: "Acheter un souvenir dans une boutique", scene: "Vous êtes dans une boutique à Maastricht et vous cherchez un petit cadeau. Vous demandez le prix, une couleur et le ticket de caisse.", lines: [{ who: "them", nl: "Hallo, kan ik u helpen?", fr: "Bonjour, puis-je vous aider ?" }, { who: "you", nl: "Hallo, ik zoek een cadeau.", fr: "Bonjour, je cherche un cadeau." }, { who: "them", nl: "Voor wie is het cadeau?", fr: "Pour qui est le cadeau ?" }, { who: "you", nl: "Voor mijn zus.", fr: "Pour ma sœur." }, { who: "them", nl: "Deze tas is erg mooi.", fr: "Ce sac est très joli." }, { who: "you", nl: "Heeft u deze in blauw?", fr: "L’avez-vous en bleu ?" }, { who: "them", nl: "Ja, hier is de blauwe tas.", fr: "Oui, voici le sac bleu." }, { who: "you", nl: "Hoeveel kost hij?", fr: "Combien coûte-t-il ?" }, { who: "them", nl: "Hij kost dertig euro.", fr: "Il coûte trente euros." }, { who: "you", nl: "Ik neem deze.", fr: "Je prends celui-ci." }, { who: "them", nl: "Wilt u de bon?", fr: "Voulez-vous le ticket ?" }, { who: "you", nl: "Ja, graag.", fr: "Oui, s’il vous plaît." }] },
{ title: "À la pharmacie pour un mal de tête", scene: "Vous êtes à Haarlem et vous avez mal à la tête. Vous entrez dans une pharmacie pour demander quelque chose de simple.", lines: [{ who: "them", nl: "Goedemiddag, waarmee kan ik u helpen?", fr: "Bonjour, comment puis-je vous aider ?" }, { who: "you", nl: "Ik heb hoofdpijn.", fr: "J’ai mal à la tête." }, { who: "them", nl: "Heeft u ook koorts?", fr: "Avez-vous aussi de la fièvre ?" }, { who: "you", nl: "Nee, geen koorts.", fr: "Non, pas de fièvre." }, { who: "them", nl: "Wilt u tabletten?", fr: "Voulez-vous des comprimés ?" }, { who: "you", nl: "Ja, alstublieft.", fr: "Oui, s’il vous plaît." }, { who: "them", nl: "Heeft u allergieën?", fr: "Avez-vous des allergies ?" }, { who: "you", nl: "Nee, ik heb geen allergieën.", fr: "Non, je n’ai pas d’allergies." }, { who: "them", nl: "Neem deze met water.", fr: "Prenez ceux-ci avec de l’eau." }, { who: "you", nl: "Hoeveel kost het?", fr: "Combien cela coûte-t-il ?" }, { who: "them", nl: "Dat is zes euro.", fr: "Cela fait six euros." }, { who: "you", nl: "Dank u wel.", fr: "Merci beaucoup." }] },
{ title: "Petite conversation avec un habitant", scene: "Vous êtes assis sur une terrasse à Leiden. Une personne locale remarque que vous regardez une carte et commence une conversation amicale.", lines: [{ who: "you", nl: "Hallo, is deze stoel vrij?", fr: "Bonjour, cette chaise est-elle libre ?" }, { who: "them", nl: "Ja hoor, ga zitten.", fr: "Oui bien sûr, asseyez-vous." }, { who: "you", nl: "Dank je, ik ben op reis in Nederland.", fr: "Merci, je voyage aux Pays-Bas." }, { who: "them", nl: "Leuk, waar kom je vandaan?", fr: "Sympa, d’où viens-tu ?" }, { who: "you", nl: "Ik kom uit Frankrijk.", fr: "Je viens de France." }, { who: "them", nl: "Spreek je Nederlands?", fr: "Tu parles néerlandais ?" }, { who: "you", nl: "Een beetje, maar niet zo goed.", fr: "Un peu, mais pas très bien." }, { who: "them", nl: "Je spreekt al goed.", fr: "Tu parles déjà bien." }, { who: "you", nl: "Dank je, dat is aardig.", fr: "Merci, c’est gentil." }, { who: "them", nl: "Vind je Leiden mooi?", fr: "Tu trouves Leiden jolie ?" }, { who: "you", nl: "Ja, heel mooi en gezellig.", fr: "Oui, très jolie et agréable." }, { who: "them", nl: "Fijn, geniet van je reis.", fr: "Super, profite de ton voyage." }] }
];
