var COURSE_NL_TR = [
  {
    title: "Begroeten en beleefd zijn",
    titleNative: "Selamlaşma ve nezaket",
    focus: "Je begint in Istanbul met de woorden die je meteen nodig hebt: hallo zeggen, afscheid nemen en beleefd reageren. Deze dag helpt je om vriendelijk over te komen in hotels, cafés en winkels.",
    vocab: [
      {tr: "merhaba", nl: "hallo", ipa: "mer-ha-ba"},
      {tr: "selam", nl: "hoi", ipa: "se-lam"},
      {tr: "günaydın", nl: "goedemorgen", ipa: "guun-ai-dun"},
      {tr: "iyi akşamlar", nl: "goedenavond", ipa: "ie-jie ak-sham-lar"},
      {tr: "iyi geceler", nl: "goedenacht", ipa: "ie-jie ge-dje-ler"},
      {tr: "hoşça kal", nl: "blijf goed / dag", ipa: "hosh-tsja kal"},
      {tr: "güle güle", nl: "dag tegen iemand die vertrekt", ipa: "guu-le guu-le"},
      {tr: "lütfen", nl: "alstublieft", ipa: "luut-fen"},
      {tr: "teşekkürler", nl: "bedankt", ipa: "te-sjek-kuur-ler"},
      {tr: "evet", nl: "ja", ipa: "e-vet"},
    ],
    phrases: [
      {tr: "Merhaba.", nl: "Hallo.", ipa: "mer-ha-ba"},
      {tr: "Günaydın.", nl: "Goedemorgen.", ipa: "guun-ai-dun"},
      {tr: "Teşekkürler.", nl: "Bedankt.", ipa: "te-sjek-kuur-ler"},
      {tr: "Lütfen.", nl: "Alstublieft.", ipa: "luut-fen"},
      {tr: "Evet, teşekkürler.", nl: "Ja, bedankt.", ipa: "e-vet te-sjek-kuur-ler"},
      {tr: "Hoşça kal.", nl: "Dag.", ipa: "hosh-tsja kal"},
    ],
    grammar: "Turks gebruikt vaak beleefde standaardzinnen in dagelijkse situaties. “Merhaba” werkt bijna overal, terwijl “selam” informeler is. “Teşekkürler” is veilig in cafés, winkels en hotels. Let op dat “hoşça kal” meestal wordt gezegd tegen iemand die blijft, terwijl “güle güle” wordt gezegd tegen iemand die weggaat.",
    practice: [
      "1. Begroet een hotelmedewerker met “Merhaba” en bedank daarna.",
      "2. Zeg goedemorgen tegen iemand in een café.",
      "3. Kies tussen “selam” en “merhaba” voor een formele situatie.",
      "4. Schrijf drie korte beleefde zinnen met “lütfen”.",
      "5. Oefen hardop: “Merhaba, teşekkürler, hoşça kal.”",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Jezelf voorstellen",
    titleNative: "Kendini tanıtma",
    focus: "In Ankara leer je jezelf kort voorstellen aan een receptionist, gids of medereiziger. Je gebruikt eenvoudige zinnen met je naam en herkomst.",
    vocab: [
      {tr: "ben", nl: "ik", ipa: "ben"},
      {tr: "sen", nl: "jij", ipa: "sen"},
      {tr: "ad", nl: "naam", ipa: "ad"},
      {tr: "adım", nl: "mijn naam", ipa: "a-dum"},
      {tr: "ne", nl: "wat", ipa: "ne"},
      {tr: "nereli", nl: "waarvandaan", ipa: "ne-re-li"},
      {tr: "Hollandalı", nl: "Nederlands", ipa: "hol-lan-da-lu"},
      {tr: "turist", nl: "toerist", ipa: "toe-rist"},
      {tr: "memnun", nl: "blij / aangenaam", ipa: "mem-noen"},
      {tr: "tanışmak", nl: "kennismaken", ipa: "ta-nush-mak"},
    ],
    phrases: [
      {tr: "Ben Jimmy.", nl: "Ik ben Jimmy.", ipa: "ben jim-mie"},
      {tr: "Adım Jimmy.", nl: "Mijn naam is Jimmy.", ipa: "a-dum jim-mie"},
      {tr: "Senin adın ne?", nl: "Hoe heet jij?", ipa: "se-nin a-dun ne"},
      {tr: "Ben Hollandalıyım.", nl: "Ik ben Nederlander.", ipa: "ben hol-lan-da-lu-jum"},
      {tr: "Memnun oldum.", nl: "Aangenaam.", ipa: "mem-noen ol-doem"},
      {tr: "Ben turistim.", nl: "Ik ben toerist.", ipa: "ben toe-ris-tim"},
    ],
    grammar: "In het Turks zit “zijn” vaak vast aan het woord zelf. “Hollandalıyım” betekent letterlijk “ik-ben-Nederlands”. Voor reizigers is het genoeg om vaste vormen te leren: “Ben turistim” en “Ben Hollandalıyım”. Je kunt “ben” soms weglaten, maar in het begin is het duidelijker om het te gebruiken.",
    practice: [
      "1. Stel jezelf voor met “Adım...”.",
      "2. Vraag iemand hoe hij of zij heet.",
      "3. Zeg dat je Nederlander bent.",
      "4. Maak een korte dialoog met “Merhaba” en “Memnun oldum”.",
      "5. Oefen: “Ben turistim” in een vriendelijke toon.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Ja, nee en basisreacties",
    titleNative: "Evet, hayır ve temel cevaplar",
    focus: "In Izmir leer je korte antwoorden geven wanneer iemand je iets aanbiedt of een vraag stelt. Dit is handig in winkels, taxi’s en restaurants.",
    vocab: [
      {tr: "hayır", nl: "nee", ipa: "ha-jur"},
      {tr: "tamam", nl: "oké", ipa: "ta-mam"},
      {tr: "olur", nl: "dat kan / prima", ipa: "o-loer"},
      {tr: "olmaz", nl: "dat kan niet", ipa: "ol-maz"},
      {tr: "belki", nl: "misschien", ipa: "bel-kie"},
      {tr: "şimdi", nl: "nu", ipa: "shim-die"},
      {tr: "sonra", nl: "later", ipa: "son-ra"},
      {tr: "çok", nl: "heel / veel", ipa: "tsjok"},
      {tr: "az", nl: "weinig", ipa: "az"},
      {tr: "iyi", nl: "goed", ipa: "ie-jie"},
    ],
    phrases: [
      {tr: "Evet, olur.", nl: "Ja, dat kan.", ipa: "e-vet o-loer"},
      {tr: "Hayır, teşekkürler.", nl: "Nee, bedankt.", ipa: "ha-jur te-sjek-kuur-ler"},
      {tr: "Tamam.", nl: "Oké.", ipa: "ta-mam"},
      {tr: "Belki sonra.", nl: "Misschien later.", ipa: "bel-kie son-ra"},
      {tr: "Çok iyi.", nl: "Heel goed.", ipa: "tsjok ie-jie"},
      {tr: "Şimdi olmaz.", nl: "Nu kan het niet.", ipa: "shim-die ol-maz"},
    ],
    grammar: "Veel Turkse korte antwoorden zijn direct maar niet onbeleefd als je “teşekkürler” toevoegt. “Olur” is een heel nuttig woord voor “prima” of “dat is goed”. “Olmaz” betekent dat iets niet kan of niet lukt. In servicegesprekken klinkt “Hayır, teşekkürler” vriendelijker dan alleen “hayır”.",
    practice: [
      "1. Reageer op een aanbod thee met “Evet, olur”.",
      "2. Weiger beleefd een extra tas in een winkel.",
      "3. Gebruik “belki sonra” wanneer je nog niet wilt beslissen.",
      "4. Vertaal: “Nee, bedankt. Misschien later.”",
      "5. Maak vijf korte reacties met “tamam”, “olur” en “olmaz”.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Nummers van nul tot twintig",
    titleNative: "Sıfırdan yirmiye sayılar",
    focus: "In Antalya leer je nummers gebruiken voor prijzen, kamernummers en telefoonnummers. Je begint met nul tot twintig, genoeg voor veel dagelijkse situaties.",
    vocab: [
      {tr: "sıfır", nl: "nul", ipa: "suh-fur"},
      {tr: "bir", nl: "één", ipa: "bier"},
      {tr: "iki", nl: "twee", ipa: "ie-kie"},
      {tr: "üç", nl: "drie", ipa: "uutsj"},
      {tr: "dört", nl: "vier", ipa: "durt"},
      {tr: "beş", nl: "vijf", ipa: "besh"},
      {tr: "altı", nl: "zes", ipa: "al-tuh"},
      {tr: "yedi", nl: "zeven", ipa: "je-die"},
      {tr: "sekiz", nl: "acht", ipa: "se-kiez"},
      {tr: "dokuz", nl: "negen", ipa: "do-koez"},
    ],
    phrases: [
      {tr: "Bir çay lütfen.", nl: "Eén thee alstublieft.", ipa: "bier tsjai luut-fen"},
      {tr: "İki kişi.", nl: "Twee personen.", ipa: "ie-kie kie-shie"},
      {tr: "Üç gece.", nl: "Drie nachten.", ipa: "uutsj ge-dje"},
      {tr: "Beş dakika.", nl: "Vijf minuten.", ipa: "besh da-kie-ka"},
      {tr: "Oda dört.", nl: "Kamer vier.", ipa: "o-da durt"},
      {tr: "Sekiz lira.", nl: "Acht lira.", ipa: "se-kiez lie-ra"},
    ],
    grammar: "Turkse getallen veranderen meestal niet voor enkelvoud of meervoud. Na een getal blijft het zelfstandig naamwoord vaak enkelvoud: “iki kişi” betekent “twee personen”, niet letterlijk “twee personenen”. Dit maakt bestellen en tellen eenvoudiger. Leer getallen hardop, want je hoort ze vaak snel uitgesproken.",
    practice: [
      "1. Bestel één thee.",
      "2. Zeg dat je met twee personen bent.",
      "3. Zeg “drie nachten” voor een hotelboeking.",
      "4. Tel hardop van nul tot negen.",
      "5. Vraag jezelf af: welke nummers hoor je bij prijzen?",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Meer nummers en prijzen",
    titleNative: "Daha fazla sayı ve fiyatlar",
    focus: "In Bursa breid je je nummers uit zodat je prijzen op markten en in cafés beter begrijpt. Je oefent met bedragen en eenvoudige prijsvragen.",
    vocab: [
      {tr: "on", nl: "tien", ipa: "on"},
      {tr: "on bir", nl: "elf", ipa: "on bier"},
      {tr: "on iki", nl: "twaalf", ipa: "on ie-kie"},
      {tr: "on beş", nl: "vijftien", ipa: "on besh"},
      {tr: "yirmi", nl: "twintig", ipa: "jir-mie"},
      {tr: "otuz", nl: "dertig", ipa: "ot-toez"},
      {tr: "kırk", nl: "veertig", ipa: "kurk"},
      {tr: "elli", nl: "vijftig", ipa: "el-lie"},
      {tr: "yüz", nl: "honderd", ipa: "juuz"},
      {tr: "lira", nl: "lira", ipa: "lie-ra"},
    ],
    phrases: [
      {tr: "Bu kaç lira?", nl: "Hoeveel lira is dit?", ipa: "boe katsj lie-ra"},
      {tr: "On lira.", nl: "Tien lira.", ipa: "on lie-ra"},
      {tr: "Yirmi lira mı?", nl: "Twintig lira?", ipa: "jir-mie lie-ra muh"},
      {tr: "Çok pahalı.", nl: "Erg duur.", ipa: "tsjok pa-ha-luh"},
      {tr: "Biraz ucuz mu?", nl: "Is het een beetje goedkoper?", ipa: "bie-raz oe-djoez moe"},
      {tr: "Tamam, alıyorum.", nl: "Oké, ik neem het.", ipa: "ta-mam a-luh-jo-roem"},
    ],
    grammar: "Om een ja-neevraag te maken, gebruik je vaak het vraagdeeltje “mı/mi/mu/mü”. Bij “Yirmi lira mı?” betekent “mı” dat je bevestiging vraagt: “Is het twintig lira?” De vorm van het vraagdeeltje past zich aan de klinkers aan, maar als beginner kun je eerst veelgebruikte vaste zinnen leren.",
    practice: [
      "1. Vraag de prijs van een fles water.",
      "2. Zeg dat iets te duur is.",
      "3. Oefen bedragen: tien, twintig, dertig, vijftig.",
      "4. Maak een vraag met “mı”.",
      "5. Speel marktje: vraag prijs, reageer, koop.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Dagen en tijd",
    titleNative: "Günler ve saat",
    focus: "In Konya leer je praten over dagen, openingstijden en simpele afspraken. Dit helpt bij musea, tours en hotelrecepties.",
    vocab: [
      {tr: "bugün", nl: "vandaag", ipa: "boe-guun"},
      {tr: "yarın", nl: "morgen", ipa: "ja-run"},
      {tr: "dün", nl: "gisteren", ipa: "duun"},
      {tr: "saat", nl: "uur / klok", ipa: "sa-at"},
      {tr: "dakika", nl: "minuut", ipa: "da-kie-ka"},
      {tr: "sabah", nl: "ochtend", ipa: "sa-bah"},
      {tr: "öğle", nl: "middag", ipa: "eu-le"},
      {tr: "akşam", nl: "avond", ipa: "ak-sham"},
      {tr: "gece", nl: "nacht", ipa: "ge-dje"},
      {tr: "açık", nl: "open", ipa: "a-tsjuk"},
    ],
    phrases: [
      {tr: "Bugün açık mı?", nl: "Is het vandaag open?", ipa: "boe-guun a-tsjuk muh"},
      {tr: "Yarın müsait misiniz?", nl: "Bent u morgen beschikbaar?", ipa: "ja-run muu-sa-it mie-sie-niez"},
      {tr: "Saat kaç?", nl: "Hoe laat is het?", ipa: "sa-at katsj"},
      {tr: "Beş dakika lütfen.", nl: "Vijf minuten alstublieft.", ipa: "besh da-kie-ka luut-fen"},
      {tr: "Akşam geliyorum.", nl: "Ik kom ’s avonds.", ipa: "ak-sham ge-lie-jo-roem"},
      {tr: "Sabah görüşürüz.", nl: "We zien elkaar in de ochtend.", ipa: "sa-bah geu-ruu-shuu-ruuz"},
    ],
    grammar: "“Saat kaç?” is de standaardvraag voor “Hoe laat is het?” Het woord “saat” kan zowel “klok”, “uur” als “tijd” betekenen. Voor reizigers is het handig om tijdwoorden vooraan te zetten: “Bugün açık mı?” en “Yarın geliyorum.” Zo maak je je zin meteen duidelijk.",
    practice: [
      "1. Vraag of een museum vandaag open is.",
      "2. Zeg dat je morgen komt.",
      "3. Vraag hoe laat het is.",
      "4. Oefen de woorden voor ochtend, middag, avond en nacht.",
      "5. Maak een zin met “beş dakika”.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Essentiële vragen",
    titleNative: "Temel sorular",
    focus: "In Cappadocië leer je vraagwoorden gebruiken voor tours, toiletten, prijzen en locaties. Je kunt hiermee bijna elk kort gesprek openen.",
    vocab: [
      {tr: "kim", nl: "wie", ipa: "kiem"},
      {tr: "ne", nl: "wat", ipa: "ne"},
      {tr: "nerede", nl: "waar", ipa: "ne-re-de"},
      {tr: "nereye", nl: "waarheen", ipa: "ne-re-je"},
      {tr: "ne zaman", nl: "wanneer", ipa: "ne za-man"},
      {tr: "nasıl", nl: "hoe", ipa: "na-sul"},
      {tr: "kaç", nl: "hoeveel / welk nummer", ipa: "katsj"},
      {tr: "hangi", nl: "welke", ipa: "han-gie"},
      {tr: "neden", nl: "waarom", ipa: "ne-den"},
      {tr: "tuvalet", nl: "toilet", ipa: "toe-va-let"},
    ],
    phrases: [
      {tr: "Tuvalet nerede?", nl: "Waar is het toilet?", ipa: "toe-va-let ne-re-de"},
      {tr: "Bu ne?", nl: "Wat is dit?", ipa: "boe ne"},
      {tr: "Ne zaman başlıyor?", nl: "Wanneer begint het?", ipa: "ne za-man bash-luh-jor"},
      {tr: "Nasıl gidilir?", nl: "Hoe kom je er?", ipa: "na-sul gie-die-lier"},
      {tr: "Hangi otobüs?", nl: "Welke bus?", ipa: "han-gie o-to-buus"},
      {tr: "Kaç kişi?", nl: "Hoeveel personen?", ipa: "katsj kie-shie"},
    ],
    grammar: "Vraagwoorden staan meestal op de plek waar het antwoord zou komen. “Tuvalet nerede?” betekent letterlijk “Toilet waar?” en klinkt natuurlijk in het Turks. “Bu ne?” is kort en heel nuttig bij menus, producten en borden. Gebruik “lütfen” of een vriendelijke toon om vragen zachter te maken.",
    practice: [
      "1. Vraag waar het toilet is.",
      "2. Vraag wanneer een tour begint.",
      "3. Vraag welke bus je nodig hebt.",
      "4. Wijs naar iets en zeg “Bu ne?”",
      "5. Maak vijf vragen met “nerede”, “ne zaman” en “kaç”.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Op het vliegveld",
    titleNative: "Havalimanında",
    focus: "Je landt op Istanbul Airport en moet bagage, paspoortcontrole en vervoer begrijpen. Deze les geeft je woorden voor aankomst en vertrek.",
    vocab: [
      {tr: "havalimanı", nl: "vliegveld", ipa: "ha-va-lie-ma-nuh"},
      {tr: "uçak", nl: "vliegtuig", ipa: "oe-tsjak"},
      {tr: "bilet", nl: "ticket", ipa: "bie-let"},
      {tr: "pasaport", nl: "paspoort", ipa: "pa-sa-port"},
      {tr: "bagaj", nl: "bagage", ipa: "ba-gazj"},
      {tr: "kapı", nl: "gate / deur", ipa: "ka-puh"},
      {tr: "giriş", nl: "ingang", ipa: "gie-riesh"},
      {tr: "çıkış", nl: "uitgang", ipa: "tsjuh-kush"},
      {tr: "kontrol", nl: "controle", ipa: "kon-trol"},
      {tr: "uçuş", nl: "vlucht", ipa: "oe-tsjoesh"},
    ],
    phrases: [
      {tr: "Pasaport lütfen.", nl: "Paspoort alstublieft.", ipa: "pa-sa-port luut-fen"},
      {tr: "Bagaj nerede?", nl: "Waar is de bagage?", ipa: "ba-gazj ne-re-de"},
      {tr: "Çıkış nerede?", nl: "Waar is de uitgang?", ipa: "tsjuh-kush ne-re-de"},
      {tr: "Biletim var.", nl: "Ik heb een ticket.", ipa: "bie-le-tiem var"},
      {tr: "Uçuş kaçta?", nl: "Hoe laat is de vlucht?", ipa: "oe-tsjoesh katsj-ta"},
      {tr: "Kapı nerede?", nl: "Waar is de gate?", ipa: "ka-puh ne-re-de"},
    ],
    grammar: "“Ik heb” vertaal je vaak met “var”: “Biletim var” betekent “Mijn ticket bestaat / ik heb een ticket”. Het bezit zit in “biletim”, mijn ticket. Voor praktische situaties kun je deze structuur onthouden: “[ding]-im var” voor “ik heb mijn ding”. “Pasaportum var” betekent “Ik heb mijn paspoort.”",
    practice: [
      "1. Zeg dat je een ticket hebt.",
      "2. Vraag waar de uitgang is.",
      "3. Vraag waar je bagage is.",
      "4. Maak een zin met “pasaportum var”.",
      "5. Oefen een korte luchthaven-dialoog met een medewerker.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Taxi en ritdelen",
    titleNative: "Taksi ve araç çağırma",
    focus: "In Istanbul neem je een taxi naar je hotel. Je leert bestemmingen zeggen, een prijs vragen en basisinstructies geven.",
    vocab: [
      {tr: "taksi", nl: "taxi", ipa: "tak-sie"},
      {tr: "otel", nl: "hotel", ipa: "o-tel"},
      {tr: "adres", nl: "adres", ipa: "ad-res"},
      {tr: "burada", nl: "hier", ipa: "boe-ra-da"},
      {tr: "orada", nl: "daar", ipa: "o-ra-da"},
      {tr: "sağ", nl: "rechts", ipa: "sa-a"},
      {tr: "sol", nl: "links", ipa: "sol"},
      {tr: "düz", nl: "rechtdoor", ipa: "duuz"},
      {tr: "yakın", nl: "dichtbij", ipa: "ja-kun"},
      {tr: "uzak", nl: "ver", ipa: "oe-zak"},
    ],
    phrases: [
      {tr: "Bu adrese lütfen.", nl: "Naar dit adres alstublieft.", ipa: "boe ad-re-se luut-fen"},
      {tr: "Otele gidiyorum.", nl: "Ik ga naar het hotel.", ipa: "o-te-le gie-die-jo-roem"},
      {tr: "Burada durun lütfen.", nl: "Stop hier alstublieft.", ipa: "boe-ra-da doe-roen luut-fen"},
      {tr: "Sağa dönün.", nl: "Sla rechtsaf.", ipa: "sa-a deu-nuun"},
      {tr: "Sola dönün.", nl: "Sla linksaf.", ipa: "so-la deu-nuun"},
      {tr: "Ne kadar tutar?", nl: "Hoeveel kost het ongeveer?", ipa: "ne ka-dar toe-tar"},
    ],
    grammar: "Richtingen krijgen vaak een uitgang: “sağ” wordt “sağa” voor “naar rechts” en “sol” wordt “sola” voor “naar links”. “Dönün” is een beleefde opdrachtvorm: “draai / sla af”. In taxi’s is “Burada durun lütfen” een heel nuttige, beleefde zin. Je hoeft niet perfect te zijn; korte instructies werken goed.",
    practice: [
      "1. Vraag de taxi naar je hotel te gaan.",
      "2. Zeg dat de chauffeur hier moet stoppen.",
      "3. Oefen links, rechts en rechtdoor.",
      "4. Vraag naar de geschatte prijs.",
      "5. Maak een route met drie korte instructies.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Inchecken in een hotel",
    titleNative: "Otele giriş yapmak",
    focus: "In Bodrum check je in bij een hotel en vraag je naar je kamer, ontbijt en wifi. Je oefent beleefde zinnen voor de receptie.",
    vocab: [
      {tr: "rezervasyon", nl: "reservering", ipa: "re-zer-va-sjon"},
      {tr: "oda", nl: "kamer", ipa: "o-da"},
      {tr: "anahtar", nl: "sleutel", ipa: "a-nah-tar"},
      {tr: "kahvaltı", nl: "ontbijt", ipa: "kah-val-tuh"},
      {tr: "internet", nl: "internet", ipa: "in-ter-net"},
      {tr: "şifre", nl: "wachtwoord", ipa: "shif-re"},
      {tr: "kimlik", nl: "identiteitsbewijs", ipa: "kim-lik"},
      {tr: "gece", nl: "nacht", ipa: "ge-dje"},
      {tr: "resepsiyon", nl: "receptie", ipa: "re-sep-sjon"},
      {tr: "asansör", nl: "lift", ipa: "a-san-seur"},
    ],
    phrases: [
      {tr: "Rezervasyonum var.", nl: "Ik heb een reservering.", ipa: "re-zer-va-sjo-noem var"},
      {tr: "Adım Cannon.", nl: "Mijn naam is Cannon.", ipa: "a-dum ken-non"},
      {tr: "Oda hazır mı?", nl: "Is de kamer klaar?", ipa: "o-da ha-zur muh"},
      {tr: "Kahvaltı saat kaçta?", nl: "Hoe laat is het ontbijt?", ipa: "kah-val-tuh sa-at katsj-ta"},
      {tr: "İnternet şifresi nedir?", nl: "Wat is het wifiwachtwoord?", ipa: "in-ter-net shif-re-sie ne-dier"},
      {tr: "Anahtar lütfen.", nl: "De sleutel alstublieft.", ipa: "a-nah-tar luut-fen"},
    ],
    grammar: "Bezitsvormen zijn heel praktisch in hotels: “rezervasyonum” betekent “mijn reservering”, “odam” betekent “mijn kamer”. Het achtervoegsel verandert afhankelijk van het woord, maar vaste zinnen helpen je snel. “Var” betekent “er is / ik heb”, dus “Rezervasyonum var” is de standaardzin bij de receptie.",
    practice: [
      "1. Zeg dat je een reservering hebt.",
      "2. Vraag of je kamer klaar is.",
      "3. Vraag naar het ontbijt.",
      "4. Vraag naar het internetwachtwoord.",
      "5. Speel een incheckgesprek met vijf korte zinnen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Ontbijt en koffie",
    titleNative: "Kahvaltı ve kahve",
    focus: "In een café in Izmir bestel je ontbijt, koffie en thee. Je leert eenvoudige voorkeuren aangeven en beleefd om iets extra’s vragen.",
    vocab: [
      {tr: "kahve", nl: "koffie", ipa: "kah-ve"},
      {tr: "çay", nl: "thee", ipa: "tsjai"},
      {tr: "su", nl: "water", ipa: "soe"},
      {tr: "ekmek", nl: "brood", ipa: "ek-mek"},
      {tr: "peynir", nl: "kaas", ipa: "pej-nier"},
      {tr: "zeytin", nl: "olijf", ipa: "zej-tien"},
      {tr: "yumurta", nl: "ei", ipa: "joe-moer-ta"},
      {tr: "bal", nl: "honing", ipa: "bal"},
      {tr: "reçel", nl: "jam", ipa: "re-tsjel"},
      {tr: "süt", nl: "melk", ipa: "suut"},
    ],
    phrases: [
      {tr: "Bir kahve lütfen.", nl: "Eén koffie alstublieft.", ipa: "bier kah-ve luut-fen"},
      {tr: "Çay var mı?", nl: "Is er thee?", ipa: "tsjai var muh"},
      {tr: "Sütlü kahve istiyorum.", nl: "Ik wil koffie met melk.", ipa: "suut-luu kah-ve is-tie-jo-roem"},
      {tr: "Su alabilir miyim?", nl: "Mag ik water krijgen?", ipa: "soe a-la-bie-lier mie-jiem"},
      {tr: "Kahvaltı istiyorum.", nl: "Ik wil ontbijt.", ipa: "kah-val-tuh is-tie-jo-roem"},
      {tr: "Ekmek lütfen.", nl: "Brood alstublieft.", ipa: "ek-mek luut-fen"},
    ],
    grammar: "“Istiyorum” betekent “ik wil” en is heel nuttig bij bestellen. Je kunt er eten of drinken vóór zetten: “Çay istiyorum” of “Kahvaltı istiyorum”. Voor beleefder vragen gebruik je “alabilir miyim?”, letterlijk “kan ik krijgen?” In cafés klinkt dat vriendelijker dan alleen “istiyorum”.",
    practice: [
      "1. Bestel koffie met melk.",
      "2. Vraag of er thee is.",
      "3. Vraag om water.",
      "4. Noem drie ontbijtproducten in het Turks.",
      "5. Maak een ontbijtbestelling van drie zinnen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "In een restaurant",
    titleNative: "Restoranda",
    focus: "In Gaziantep bezoek je een restaurant en wil je een tafel, menu en rekening vragen. Je leert basiszinnen voor een complete maaltijd.",
    vocab: [
      {tr: "restoran", nl: "restaurant", ipa: "res-to-ran"},
      {tr: "masa", nl: "tafel", ipa: "ma-sa"},
      {tr: "menü", nl: "menu", ipa: "me-nuu"},
      {tr: "garson", nl: "ober", ipa: "gar-son"},
      {tr: "hesap", nl: "rekening", ipa: "he-sap"},
      {tr: "yemek", nl: "eten / maaltijd", ipa: "je-mek"},
      {tr: "çorba", nl: "soep", ipa: "tsjor-ba"},
      {tr: "tavuk", nl: "kip", ipa: "ta-voek"},
      {tr: "et", nl: "vlees", ipa: "et"},
      {tr: "balık", nl: "vis", ipa: "ba-luk"},
    ],
    phrases: [
      {tr: "İki kişilik masa lütfen.", nl: "Een tafel voor twee alstublieft.", ipa: "ie-kie kie-shie-lik ma-sa luut-fen"},
      {tr: "Menü alabilir miyim?", nl: "Mag ik het menu?", ipa: "me-nuu a-la-bie-lier mie-jiem"},
      {tr: "Ne önerirsiniz?", nl: "Wat raadt u aan?", ipa: "ne eu-ne-rie-rsie-niez"},
      {tr: "Tavuk istiyorum.", nl: "Ik wil kip.", ipa: "ta-voek is-tie-jo-roem"},
      {tr: "Hesap lütfen.", nl: "De rekening alstublieft.", ipa: "he-sap luut-fen"},
      {tr: "Çok lezzetli.", nl: "Erg lekker.", ipa: "tsjok lez-zet-lie"},
    ],
    grammar: "“Ne önerirsiniz?” is een beleefde manier om aanbevelingen te vragen. De uitgang “-siniz” maakt de zin beleefd of formeel. In restaurants kun je simpel blijven: gerecht + “istiyorum”. Complimenten zoals “Çok lezzetli” worden gewaardeerd, vooral in kleinere familierestaurants.",
    practice: [
      "1. Vraag een tafel voor twee.",
      "2. Vraag het menu.",
      "3. Vraag wat de ober aanbeveelt.",
      "4. Bestel soep en kip.",
      "5. Vraag de rekening beleefd.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Dieetwensen en allergieën",
    titleNative: "Beslenme tercihleri ve alerjiler",
    focus: "In Antalya moet je uitleggen wat je wel en niet kunt eten. Je leert zinnen voor vegetarisch eten, allergieën en ingrediënten.",
    vocab: [
      {tr: "alerji", nl: "allergie", ipa: "a-ler-zjie"},
      {tr: "vejetaryen", nl: "vegetarisch", ipa: "ve-zje-tar-jen"},
      {tr: "helal", nl: "halal", ipa: "he-lal"},
      {tr: "domuz eti", nl: "varkensvlees", ipa: "do-moez e-tie"},
      {tr: "fındık", nl: "hazelnoot / noot", ipa: "fun-duk"},
      {tr: "süt ürünü", nl: "zuivelproduct", ipa: "suut uu-ruu-nuu"},
      {tr: "glüten", nl: "gluten", ipa: "glu-ten"},
      {tr: "acı", nl: "pittig", ipa: "a-djuh"},
      {tr: "tuz", nl: "zout", ipa: "toez"},
      {tr: "şeker", nl: "suiker", ipa: "she-ker"},
    ],
    phrases: [
      {tr: "Alerjim var.", nl: "Ik heb een allergie.", ipa: "a-ler-zjiem var"},
      {tr: "Fındık alerjim var.", nl: "Ik heb een notenallergie.", ipa: "fun-duk a-ler-zjiem var"},
      {tr: "Vejetaryen yemek var mı?", nl: "Is er vegetarisch eten?", ipa: "ve-zje-tar-jen je-mek var muh"},
      {tr: "Domuz eti yemiyorum.", nl: "Ik eet geen varkensvlees.", ipa: "do-moez e-tie je-mie-jo-roem"},
      {tr: "Çok acı mı?", nl: "Is het erg pittig?", ipa: "tsjok a-djuh muh"},
      {tr: "Şekersiz lütfen.", nl: "Zonder suiker alstublieft.", ipa: "she-ker-siez luut-fen"},
    ],
    grammar: "Het achtervoegsel “-siz/-sız/-suz/-süz” betekent “zonder”. “Şekersiz” betekent zonder suiker en “tuzsuz” betekent zonder zout. Voor “ik eet niet” gebruik je “yemiyorum”. Deze vorm is handig voor dieetwensen: “Et yemiyorum” betekent “Ik eet geen vlees.”",
    practice: [
      "1. Zeg dat je een allergie hebt.",
      "2. Vraag of iets vegetarisch is.",
      "3. Zeg “zonder suiker” en “zonder zout”.",
      "4. Vraag of een gerecht pittig is.",
      "5. Maak een restaurantzin met “yemiyorum”.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Straateten en snacks",
    titleNative: "Sokak yemeği ve atıştırmalıklar",
    focus: "In Istanbul proef je straateten zoals simit, döner en kumpir. Je leert snel bestellen bij een kraam zonder lang gesprek.",
    vocab: [
      {tr: "simit", nl: "Turks sesambroodje", ipa: "sie-miet"},
      {tr: "döner", nl: "döner", ipa: "deu-ner"},
      {tr: "kumpir", nl: "gevulde gepofte aardappel", ipa: "koem-pier"},
      {tr: "midye", nl: "mossel", ipa: "mid-je"},
      {tr: "lahmacun", nl: "Turkse dunne pizza", ipa: "lah-ma-djoen"},
      {tr: "ayran", nl: "yoghurtdrank", ipa: "ai-ran"},
      {tr: "sos", nl: "saus", ipa: "sos"},
      {tr: "paket", nl: "meenemen / pakket", ipa: "pa-ket"},
      {tr: "sıcak", nl: "warm", ipa: "suh-djak"},
      {tr: "soğuk", nl: "koud", ipa: "so-oek"},
    ],
    phrases: [
      {tr: "Bir simit lütfen.", nl: "Eén simit alstublieft.", ipa: "bier sie-miet luut-fen"},
      {tr: "Döner alabilir miyim?", nl: "Mag ik döner?", ipa: "deu-ner a-la-bie-lier mie-jiem"},
      {tr: "Paket olsun.", nl: "Om mee te nemen graag.", ipa: "pa-ket ol-soen"},
      {tr: "Sos istemiyorum.", nl: "Ik wil geen saus.", ipa: "sos is-te-mie-jo-roem"},
      {tr: "Ayran var mı?", nl: "Is er ayran?", ipa: "ai-ran var muh"},
      {tr: "Sıcak mı?", nl: "Is het warm?", ipa: "suh-djak muh"},
    ],
    grammar: "“İstemiyorum” betekent “ik wil niet”. Dit is handig als je iets wilt weglaten: “Sos istemiyorum.” “Olsun” betekent in bestellingen vaak “laat het zo zijn / graag”: “Paket olsun” betekent “graag om mee te nemen”. Straatverkopers spreken snel, dus korte zinnen zijn normaal.",
    practice: [
      "1. Bestel één simit.",
      "2. Vraag om döner om mee te nemen.",
      "3. Zeg dat je geen saus wilt.",
      "4. Vraag of er ayran is.",
      "5. Oefen een bestelling van twee regels.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Winkelen op de markt",
    titleNative: "Pazarda alışveriş",
    focus: "Op een markt in Izmir koop je fruit, souvenirs en kleine cadeaus. Je leert onderhandelen, vragen naar maten en beleefd kopen.",
    vocab: [
      {tr: "pazar", nl: "markt", ipa: "pa-zar"},
      {tr: "alışveriş", nl: "winkelen", ipa: "a-lush-ve-riesh"},
      {tr: "meyve", nl: "fruit", ipa: "mej-ve"},
      {tr: "elma", nl: "appel", ipa: "el-ma"},
      {tr: "portakal", nl: "sinaasappel", ipa: "por-ta-kal"},
      {tr: "hediye", nl: "cadeau", ipa: "he-die-je"},
      {tr: "çanta", nl: "tas", ipa: "tsjan-ta"},
      {tr: "renk", nl: "kleur", ipa: "renk"},
      {tr: "küçük", nl: "klein", ipa: "kuu-tsjuuk"},
      {tr: "büyük", nl: "groot", ipa: "buu-juuk"},
    ],
    phrases: [
      {tr: "Bu kaç para?", nl: "Hoeveel kost dit?", ipa: "boe katsj pa-ra"},
      {tr: "Bir kilo elma lütfen.", nl: "Eén kilo appels alstublieft.", ipa: "bier kie-lo el-ma luut-fen"},
      {tr: "Daha ucuz olur mu?", nl: "Kan het goedkoper?", ipa: "da-ha oe-djoez o-loer moe"},
      {tr: "Bu renk güzel.", nl: "Deze kleur is mooi.", ipa: "boe renk guu-zel"},
      {tr: "Küçük çanta istiyorum.", nl: "Ik wil een kleine tas.", ipa: "kuu-tsjuuk tsjan-ta is-tie-jo-roem"},
      {tr: "Hediye için.", nl: "Voor een cadeau.", ipa: "he-die-je ie-tsjien"},
    ],
    grammar: "Bij bijvoeglijke naamwoorden komt het beschrijvende woord vóór het zelfstandig naamwoord: “küçük çanta” is “kleine tas” en “büyük çanta” is “grote tas”. “Bu” betekent “deze/dit” en is erg nuttig wanneer je iets aanwijst. Onderhandelen kan op markten, maar doe het vriendelijk met glimlach en “olur mu?”",
    practice: [
      "1. Vraag de prijs van iets op de markt.",
      "2. Koop één kilo appels.",
      "3. Vraag of iets goedkoper kan.",
      "4. Beschrijf een kleine tas en een grote tas.",
      "5. Zeg dat iets voor een cadeau is.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kleding en maten",
    titleNative: "Kıyafetler ve bedenler",
    focus: "In een winkelcentrum in Ankara zoek je kleding en probeert iets aan. Je leert woorden voor kleding, kleuren en maten.",
    vocab: [
      {tr: "kıyafet", nl: "kleding", ipa: "kuh-ja-fet"},
      {tr: "gömlek", nl: "overhemd", ipa: "geum-lek"},
      {tr: "tişört", nl: "T-shirt", ipa: "tie-sjeurt"},
      {tr: "pantolon", nl: "broek", ipa: "pan-to-lon"},
      {tr: "ayakkabı", nl: "schoen", ipa: "a-jak-ka-buh"},
      {tr: "beden", nl: "maat", ipa: "be-den"},
      {tr: "renk", nl: "kleur", ipa: "renk"},
      {tr: "beyaz", nl: "wit", ipa: "be-jaz"},
      {tr: "siyah", nl: "zwart", ipa: "sie-jah"},
      {tr: "mavi", nl: "blauw", ipa: "ma-vie"},
    ],
    phrases: [
      {tr: "Bedenim nedir?", nl: "Wat is mijn maat?", ipa: "be-de-niem ne-dier"},
      {tr: "Bu beden var mı?", nl: "Is deze maat er?", ipa: "boe be-den var muh"},
      {tr: "Deneyebilir miyim?", nl: "Mag ik het passen?", ipa: "de-ne-je-bie-lier mie-jiem"},
      {tr: "Mavi tişört istiyorum.", nl: "Ik wil een blauw T-shirt.", ipa: "ma-vie tie-sjeurt is-tie-jo-roem"},
      {tr: "Daha büyük var mı?", nl: "Is er een grotere?", ipa: "da-ha buu-juuk var muh"},
      {tr: "Daha küçük var mı?", nl: "Is er een kleinere?", ipa: "da-ha kuu-tsjuuk var muh"},
    ],
    grammar: "“Daha” betekent “meer” en maakt vergelijkingen: “daha büyük” is groter, “daha küçük” is kleiner. In winkels kun je met “var mı?” vragen of iets beschikbaar is. “Deneyebilir miyim?” is een beleefde en nuttige zin wanneer je kleding wilt passen.",
    practice: [
      "1. Vraag of jouw maat er is.",
      "2. Vraag of je iets mag passen.",
      "3. Vraag om een grotere maat.",
      "4. Noem drie kledingstukken in het Turks.",
      "5. Maak een zin met kleur + kledingstuk.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Openbaar vervoer",
    titleNative: "Toplu taşıma",
    focus: "In Istanbul gebruik je metro, tram, ferry en bus. Je leert tickets kopen, haltes herkennen en vragen waar je moet uitstappen.",
    vocab: [
      {tr: "metro", nl: "metro", ipa: "met-ro"},
      {tr: "tramvay", nl: "tram", ipa: "tram-vai"},
      {tr: "otobüs", nl: "bus", ipa: "o-to-buus"},
      {tr: "vapur", nl: "ferry", ipa: "va-poer"},
      {tr: "durak", nl: "halte", ipa: "doe-rak"},
      {tr: "bilet", nl: "ticket", ipa: "bie-let"},
      {tr: "kart", nl: "kaart", ipa: "kart"},
      {tr: "hat", nl: "lijn", ipa: "hat"},
      {tr: "istasyon", nl: "station", ipa: "is-ta-sjon"},
      {tr: "aktarma", nl: "overstap", ipa: "ak-tar-ma"},
    ],
    phrases: [
      {tr: "Bir bilet lütfen.", nl: "Eén ticket alstublieft.", ipa: "bier bie-let luut-fen"},
      {tr: "İstanbulkart nereden alınır?", nl: "Waar koop je een Istanbulkart?", ipa: "is-tan-boel-kart ne-re-den a-luh-nur"},
      {tr: "Hangi durakta inmeliyim?", nl: "Bij welke halte moet ik uitstappen?", ipa: "han-gie doe-rak-ta ien-me-lie-jiem"},
      {tr: "Bu metro Taksim’e gider mi?", nl: "Gaat deze metro naar Taksim?", ipa: "boe met-ro tak-siem-e gie-der mie"},
      {tr: "Aktarma var mı?", nl: "Is er een overstap?", ipa: "ak-tar-ma var muh"},
      {tr: "Son durak nerede?", nl: "Waar is de eindhalte?", ipa: "son doe-rak ne-re-de"},
    ],
    grammar: "Richting wordt vaak aangegeven met “-e/-a”: “Taksim’e” betekent “naar Taksim”. Na klinkers of eigennamen zie je soms een apostrof in geschreven Turks. Voor reizen is de vraag “... gider mi?” heel belangrijk: “Gaat dit naar ...?” Je kunt de plaatsnaam invullen.",
    practice: [
      "1. Vraag of de metro naar Taksim gaat.",
      "2. Vraag bij welke halte je moet uitstappen.",
      "3. Koop één ticket.",
      "4. Vraag of er een overstap is.",
      "5. Maak drie zinnen met “gider mi?”",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "De weg vragen",
    titleNative: "Yol tarifi sormak",
    focus: "In de oude stad van Antalya vraag je de weg naar bezienswaardigheden. Je leert plaatswoorden en eenvoudige route-instructies begrijpen.",
    vocab: [
      {tr: "yol", nl: "weg", ipa: "jol"},
      {tr: "cadde", nl: "avenue / grote straat", ipa: "dja-de"},
      {tr: "sokak", nl: "straat", ipa: "so-kak"},
      {tr: "köşe", nl: "hoek", ipa: "keu-she"},
      {tr: "karşı", nl: "tegenover", ipa: "kar-shuh"},
      {tr: "yanında", nl: "naast", ipa: "ja-nun-da"},
      {tr: "arkasında", nl: "achter", ipa: "ar-ka-sun-da"},
      {tr: "önünde", nl: "voor", ipa: "eu-nuun-de"},
      {tr: "yakında", nl: "dichtbij", ipa: "ja-kun-da"},
      {tr: "harita", nl: "kaart", ipa: "ha-rie-ta"},
    ],
    phrases: [
      {tr: "Müze nerede?", nl: "Waar is het museum?", ipa: "muu-ze ne-re-de"},
      {tr: "Haritada gösterebilir misiniz?", nl: "Kunt u het op de kaart laten zien?", ipa: "ha-rie-ta-da geus-te-re-bie-lier mie-sie-niez"},
      {tr: "Düz gidin.", nl: "Ga rechtdoor.", ipa: "duuz gie-dien"},
      {tr: "Köşeden sağa dönün.", nl: "Sla bij de hoek rechtsaf.", ipa: "keu-she-den sa-a deu-nuun"},
      {tr: "Caminin yanında.", nl: "Naast de moskee.", ipa: "dja-mie-nien ja-nun-da"},
      {tr: "Yakın mı?", nl: "Is het dichtbij?", ipa: "ja-kun muh"},
    ],
    grammar: "Veel plaatswoorden krijgen bezitsachtige uitgangen: “yanında” betekent “aan de zijkant ervan / naast”. “Caminin yanında” betekent “naast de moskee”. In route-instructies hoor je vaak gebiedende vormen zoals “gidin” en “dönün”. Dit zijn beleefde instructies, niet hard of onvriendelijk.",
    practice: [
      "1. Vraag waar het museum is.",
      "2. Vraag of iemand het op de kaart kan tonen.",
      "3. Geef een route met rechtdoor en rechtsaf.",
      "4. Vertaal: “naast de moskee”.",
      "5. Maak drie plaatszinnen met “yanında”, “önünde” en “arkasında”.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Bezienswaardigheden en tickets",
    titleNative: "Gezilecek yerler ve biletler",
    focus: "In Cappadocië en Istanbul bezoek je musea, moskeeën en historische plekken. Je leert vragen naar tickets, openingstijden en regels.",
    vocab: [
      {tr: "müze", nl: "museum", ipa: "muu-ze"},
      {tr: "cami", nl: "moskee", ipa: "dja-mie"},
      {tr: "saray", nl: "paleis", ipa: "sa-rai"},
      {tr: "kale", nl: "kasteel / fort", ipa: "ka-le"},
      {tr: "bilet gişesi", nl: "ticketbalie", ipa: "bie-let gie-sje-sie"},
      {tr: "rehber", nl: "gids", ipa: "reh-ber"},
      {tr: "tur", nl: "tour", ipa: "toer"},
      {tr: "fotoğraf", nl: "foto", ipa: "fo-to-raf"},
      {tr: "yasak", nl: "verboden", ipa: "ja-sak"},
      {tr: "ücretsiz", nl: "gratis", ipa: "uu-djret-siez"},
    ],
    phrases: [
      {tr: "Bilet gişesi nerede?", nl: "Waar is de ticketbalie?", ipa: "bie-let gie-sje-sie ne-re-de"},
      {tr: "Giriş ücreti ne kadar?", nl: "Hoeveel is de entree?", ipa: "gie-riesh uu-djre-tie ne ka-dar"},
      {tr: "Fotoğraf çekmek yasak mı?", nl: "Is foto’s maken verboden?", ipa: "fo-to-raf tsjek-mek ja-sak muh"},
      {tr: "Rehberli tur var mı?", nl: "Is er een tour met gids?", ipa: "reh-ber-lie toer var muh"},
      {tr: "Bugün ücretsiz mi?", nl: "Is het vandaag gratis?", ipa: "boe-guun uu-djret-siez mie"},
      {tr: "Ne zaman kapanıyor?", nl: "Wanneer sluit het?", ipa: "ne za-man ka-pa-nuh-jor"},
    ],
    grammar: "Werkwoorden als zelfstandig naamwoord eindigen vaak op “-mek/-mak”: “fotoğraf çekmek” betekent “foto’s maken”. “Yasak mı?” betekent “is het verboden?” Dit is nuttig in moskeeën, musea en historische gebouwen. Vraag liever eerst voordat je foto’s maakt op religieuze of officiële plekken.",
    practice: [
      "1. Vraag waar de ticketbalie is.",
      "2. Vraag hoeveel de entree kost.",
      "3. Vraag of foto’s maken verboden is.",
      "4. Vraag of er een tour met gids is.",
      "5. Maak een vraag over sluitingstijd.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Bij de apotheek",
    titleNative: "Eczanede",
    focus: "In Ankara ga je naar een apotheek omdat je hoofdpijn of maagklachten hebt. Je leert eenvoudige symptomen en hulpvragen.",
    vocab: [
      {tr: "eczane", nl: "apotheek", ipa: "edj-za-ne"},
      {tr: "ilaç", nl: "medicijn", ipa: "ie-latsj"},
      {tr: "ağrı", nl: "pijn", ipa: "a-ruh"},
      {tr: "baş ağrısı", nl: "hoofdpijn", ipa: "bash a-ruh-suh"},
      {tr: "mide", nl: "maag", ipa: "mie-de"},
      {tr: "ateş", nl: "koorts", ipa: "a-tesh"},
      {tr: "öksürük", nl: "hoest", ipa: "euk-suu-ruuk"},
      {tr: "soğuk algınlığı", nl: "verkoudheid", ipa: "so-oek al-gun-luh-uh"},
      {tr: "doktor", nl: "dokter", ipa: "dok-tor"},
      {tr: "reçete", nl: "recept", ipa: "re-tje-te"},
    ],
    phrases: [
      {tr: "Eczane nerede?", nl: "Waar is de apotheek?", ipa: "edj-za-ne ne-re-de"},
      {tr: "Başım ağrıyor.", nl: "Mijn hoofd doet pijn.", ipa: "ba-shum a-ruh-jor"},
      {tr: "Midem ağrıyor.", nl: "Mijn maag doet pijn.", ipa: "mie-dem a-ruh-jor"},
      {tr: "İlaç lazım.", nl: "Ik heb medicijn nodig.", ipa: "ie-latsj la-zum"},
      {tr: "Reçetesiz var mı?", nl: "Is er iets zonder recept?", ipa: "re-tje-te-siez var muh"},
      {tr: "Doktor lazım mı?", nl: "Is een dokter nodig?", ipa: "dok-tor la-zum muh"},
    ],
    grammar: "“Ağrıyor” betekent “doet pijn”. Het lichaamsdeel krijgt vaak een bezitsvorm: “başım” is “mijn hoofd”, “midem” is “mijn maag”. “Lazım” betekent “nodig”; “İlaç lazım” is kort maar duidelijk. Bij ernstige klachten is het beter om om een dokter te vragen.",
    practice: [
      "1. Vraag waar de apotheek is.",
      "2. Zeg dat je hoofdpijn hebt.",
      "3. Zeg dat je maag pijn doet.",
      "4. Vraag of er iets zonder recept is.",
      "5. Vraag of een dokter nodig is.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Noodgevallen en hulp",
    titleNative: "Acil durumlar ve yardım",
    focus: "In een onbekende stad moet je snel hulp kunnen vragen. Je leert noodwoorden voor politie, ziekenhuis en dringende situaties.",
    vocab: [
      {tr: "yardım", nl: "hulp", ipa: "jar-dum"},
      {tr: "acil", nl: "dringend / nood", ipa: "a-djiel"},
      {tr: "polis", nl: "politie", ipa: "po-lies"},
      {tr: "hastane", nl: "ziekenhuis", ipa: "has-ta-ne"},
      {tr: "ambulans", nl: "ambulance", ipa: "am-boe-lans"},
      {tr: "tehlike", nl: "gevaar", ipa: "teh-lie-ke"},
      {tr: "kayboldum", nl: "ik ben verdwaald", ipa: "kai-bol-doem"},
      {tr: "çalındı", nl: "gestolen", ipa: "tsja-lun-duh"},
      {tr: "telefon", nl: "telefoon", ipa: "te-le-fon"},
      {tr: "pasaport", nl: "paspoort", ipa: "pa-sa-port"},
    ],
    phrases: [
      {tr: "Yardım edin lütfen.", nl: "Help mij alstublieft.", ipa: "jar-dum e-dien luut-fen"},
      {tr: "Acil durum.", nl: "Noodgeval.", ipa: "a-djiel doe-roem"},
      {tr: "Polisi arayın.", nl: "Bel de politie.", ipa: "po-lie-sie a-ra-jun"},
      {tr: "Ambulans lazım.", nl: "Er is een ambulance nodig.", ipa: "am-boe-lans la-zum"},
      {tr: "Kayboldum.", nl: "Ik ben verdwaald.", ipa: "kai-bol-doem"},
      {tr: "Pasaportum çalındı.", nl: "Mijn paspoort is gestolen.", ipa: "pa-sa-por-toem tsja-lun-duh"},
    ],
    grammar: "In noodsituaties zijn korte zinnen beter dan perfecte grammatica. “Yardım edin” is een beleefde maar dringende vorm van “help”. “Çalındı” betekent “is gestolen” en kan met bezit gebruikt worden: “Telefonum çalındı.” Leer deze zinnen als vaste noodzinnen.",
    practice: [
      "1. Zeg dat je hulp nodig hebt.",
      "2. Vraag iemand de politie te bellen.",
      "3. Zeg dat je verdwaald bent.",
      "4. Zeg dat je paspoort gestolen is.",
      "5. Oefen drie noodzinnen hardop en duidelijk.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Weer en kledingkeuzes",
    titleNative: "Hava durumu ve kıyafet seçimi",
    focus: "In Trabzon praat je over regen, zon en temperatuur. Je leert weerwoorden die handig zijn voor tours, wandelingen en plannen.",
    vocab: [
      {tr: "hava", nl: "weer / lucht", ipa: "ha-va"},
      {tr: "güneş", nl: "zon", ipa: "guu-nesh"},
      {tr: "yağmur", nl: "regen", ipa: "ja-moer"},
      {tr: "kar", nl: "sneeuw", ipa: "kar"},
      {tr: "rüzgar", nl: "wind", ipa: "ruuz-gar"},
      {tr: "sıcak", nl: "warm", ipa: "suh-djak"},
      {tr: "soğuk", nl: "koud", ipa: "so-oek"},
      {tr: "ılık", nl: "mild / lauw", ipa: "uh-luk"},
      {tr: "şemsiye", nl: "paraplu", ipa: "shem-sie-je"},
      {tr: "mont", nl: "jas", ipa: "mont"},
    ],
    phrases: [
      {tr: "Hava nasıl?", nl: "Hoe is het weer?", ipa: "ha-va na-sul"},
      {tr: "Bugün hava sıcak.", nl: "Het weer is vandaag warm.", ipa: "boe-guun ha-va suh-djak"},
      {tr: "Yağmur yağıyor.", nl: "Het regent.", ipa: "ja-moer ja-uh-jor"},
      {tr: "Şemsiye lazım mı?", nl: "Is een paraplu nodig?", ipa: "shem-sie-je la-zum muh"},
      {tr: "Çok soğuk.", nl: "Het is erg koud.", ipa: "tsjok so-oek"},
      {tr: "Yarın güneşli mi?", nl: "Is het morgen zonnig?", ipa: "ja-run guu-nesh-lie mie"},
    ],
    grammar: "Weerbeschrijvingen zijn vaak simpel: “Hava sıcak” betekent “het weer is warm”. Voor lopende acties gebruik je vaak “-iyor”: “Yağmur yağıyor” betekent “regen valt / het regent”. “Güneşli” betekent zonnig, met “-li” voor “met”. Dus “güneşli hava” is zonnig weer.",
    practice: [
      "1. Vraag hoe het weer is.",
      "2. Zeg dat het regent.",
      "3. Vraag of je een paraplu nodig hebt.",
      "4. Beschrijf vandaag met warm, koud of mild.",
      "5. Vraag of het morgen zonnig is.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Sociale praatjes",
    titleNative: "Sosyal sohbetler",
    focus: "In een theehuis in Eskişehir maak je kort contact met een local. Je leert vragen stellen over werk, wonen en reizen zonder te persoonlijk te worden.",
    vocab: [
      {tr: "nasılsın", nl: "hoe gaat het met je", ipa: "na-sul-sun"},
      {tr: "iyiyim", nl: "het gaat goed met mij", ipa: "ie-jie-jiem"},
      {tr: "siz", nl: "u / jullie", ipa: "siez"},
      {tr: "nerede yaşıyorsunuz", nl: "waar woont u", ipa: "ne-re-de ja-shuh-jor-soe-noez"},
      {tr: "iş", nl: "werk", ipa: "iesh"},
      {tr: "tatil", nl: "vakantie", ipa: "ta-tiel"},
      {tr: "şehir", nl: "stad", ipa: "she-hier"},
      {tr: "güzel", nl: "mooi / fijn", ipa: "guu-zel"},
      {tr: "arkadaş", nl: "vriend", ipa: "ar-ka-dash"},
      {tr: "sohbet", nl: "gesprek / praatje", ipa: "soh-bet"},
    ],
    phrases: [
      {tr: "Nasılsınız?", nl: "Hoe gaat het met u?", ipa: "na-sul-suh-nuz"},
      {tr: "İyiyim, teşekkürler.", nl: "Het gaat goed, bedankt.", ipa: "ie-jie-jiem te-sjek-kuur-ler"},
      {tr: "Siz nerelisiniz?", nl: "Waar komt u vandaan?", ipa: "siez ne-re-lie-sie-niez"},
      {tr: "Bu şehir çok güzel.", nl: "Deze stad is erg mooi.", ipa: "boe she-hier tsjok guu-zel"},
      {tr: "Tatil için geldim.", nl: "Ik ben voor vakantie gekomen.", ipa: "ta-tiel ie-tsjien gel-diem"},
      {tr: "Sohbet için teşekkürler.", nl: "Bedankt voor het gesprek.", ipa: "soh-bet ie-tsjien te-sjek-kuur-ler"},
    ],
    grammar: "“Siz” is de beleefde vorm van “jij/u” en is veilig met onbekenden. Veel beleefde werkwoordsvormen eindigen op “-siniz/-sınız”. “Nasılsınız?” is beleefder dan “Nasılsın?” Voor casual gesprekken met locals begin je beter formeel en wordt het gesprek vanzelf informeler.",
    practice: [
      "1. Vraag beleefd hoe het met iemand gaat.",
      "2. Zeg dat je voor vakantie bent gekomen.",
      "3. Geef een compliment over de stad.",
      "4. Vraag waar iemand vandaan komt.",
      "5. Sluit een praatje netjes af.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Uitnodigingen en afspraken",
    titleNative: "Davetler ve buluşmalar",
    focus: "In Izmir spreek je af met iemand voor thee of een wandeling. Je leert tijden voorstellen, accepteren en beleefd afwijzen.",
    vocab: [
      {tr: "buluşmak", nl: "afspreken / ontmoeten", ipa: "boe-loesh-mak"},
      {tr: "davet", nl: "uitnodiging", ipa: "da-vet"},
      {tr: "çay içmek", nl: "thee drinken", ipa: "tsjai ietsj-mek"},
      {tr: "yürüyüş", nl: "wandeling", ipa: "juu-ruu-juush"},
      {tr: "müsait", nl: "beschikbaar", ipa: "muu-sa-it"},
      {tr: "saat üç", nl: "drie uur", ipa: "sa-at uutsj"},
      {tr: "erken", nl: "vroeg", ipa: "er-ken"},
      {tr: "geç", nl: "laat", ipa: "getsj"},
      {tr: "uygun", nl: "passend / geschikt", ipa: "oe-joen"},
      {tr: "plan", nl: "plan", ipa: "plan"},
    ],
    phrases: [
      {tr: "Çay içelim mi?", nl: "Zullen we thee drinken?", ipa: "tsjai ie-tsje-liem mie"},
      {tr: "Saat üç uygun mu?", nl: "Is drie uur geschikt?", ipa: "sa-at uutsj oe-joen moe"},
      {tr: "Bugün müsait misiniz?", nl: "Bent u vandaag beschikbaar?", ipa: "boe-guun muu-sa-it mie-sie-niez"},
      {tr: "Yarın buluşalım.", nl: "Laten we morgen afspreken.", ipa: "ja-run boe-loe-sha-lum"},
      {tr: "Maalesef gelemem.", nl: "Helaas kan ik niet komen.", ipa: "ma-a-le-sef ge-le-mem"},
      {tr: "Harika, görüşürüz.", nl: "Geweldig, tot ziens.", ipa: "ha-rie-ka geu-ruu-shuu-ruuz"},
    ],
    grammar: "Turks heeft een vriendelijke voorstelvorm met “-elim/-alım”: “içelim” betekent “laten we drinken” en “buluşalım” betekent “laten we afspreken”. “Mi?” maakt er een vraag van: “Çay içelim mi?” Dit klinkt natuurlijk voor sociale uitnodigingen. “Maalesef” verzacht een afwijzing.",
    practice: [
      "1. Stel voor om thee te drinken.",
      "2. Vraag of drie uur geschikt is.",
      "3. Zeg dat je vandaag beschikbaar bent.",
      "4. Wijs beleefd af met “maalesef”.",
      "5. Maak een korte afspraak voor morgen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Aan het strand en ontspanning",
    titleNative: "Plajda ve dinlenme",
    focus: "Aan de kust bij Bodrum huur je een ligstoel, vraagt naar handdoeken en praat over zwemmen. Je leert ontspannen vakantie-Turks.",
    vocab: [
      {tr: "plaj", nl: "strand", ipa: "plazj"},
      {tr: "deniz", nl: "zee", ipa: "de-niez"},
      {tr: "havuz", nl: "zwembad", ipa: "ha-voez"},
      {tr: "şezlong", nl: "ligstoel", ipa: "shez-long"},
      {tr: "havlu", nl: "handdoek", ipa: "hav-loe"},
      {tr: "güneş kremi", nl: "zonnebrandcrème", ipa: "guu-nesh kre-mie"},
      {tr: "yüzmek", nl: "zwemmen", ipa: "juuz-mek"},
      {tr: "dinlenmek", nl: "uitrusten", ipa: "dien-len-mek"},
      {tr: "temiz", nl: "schoon", ipa: "te-miez"},
      {tr: "kalabalık", nl: "druk / vol", ipa: "ka-la-ba-luk"},
    ],
    phrases: [
      {tr: "Şezlong var mı?", nl: "Zijn er ligstoelen?", ipa: "shez-long var muh"},
      {tr: "Havlu alabilir miyim?", nl: "Mag ik een handdoek?", ipa: "hav-loe a-la-bie-lier mie-jiem"},
      {tr: "Deniz çok güzel.", nl: "De zee is erg mooi.", ipa: "de-niez tsjok guu-zel"},
      {tr: "Yüzmek istiyorum.", nl: "Ik wil zwemmen.", ipa: "juuz-mek is-tie-jo-roem"},
      {tr: "Plaj kalabalık mı?", nl: "Is het strand druk?", ipa: "plazj ka-la-ba-luk muh"},
      {tr: "Güneş kremi lazım.", nl: "Ik heb zonnebrandcrème nodig.", ipa: "guu-nesh kre-mie la-zum"},
    ],
    grammar: "Werkwoorden als “yüzmek” en “dinlenmek” kunnen vóór “istiyorum” komen: “Yüzmek istiyorum” betekent “Ik wil zwemmen”. Het achtervoegsel “-mek/-mak” is de woordenboekvorm van het werkwoord. In toeristische gebieden spreekt men soms Engels, maar deze Turkse zinnen helpen je vriendelijker en zelfstandiger te reizen.",
    practice: [
      "1. Vraag of er ligstoelen zijn.",
      "2. Vraag om een handdoek.",
      "3. Zeg dat je wilt zwemmen.",
      "4. Vraag of het strand druk is.",
      "5. Maak een zin met “lazım”.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Geld, pinnen en betalen",
    titleNative: "Para, ATM ve ödeme",
    focus: "In een winkel of restaurant moet je betalen met kaart of contant geld. Je leert vragen naar betaalmethoden, bonnen en geldautomaten.",
    vocab: [
      {tr: "para", nl: "geld", ipa: "pa-ra"},
      {tr: "nakit", nl: "contant", ipa: "na-kiet"},
      {tr: "kart", nl: "kaart", ipa: "kart"},
      {tr: "kredi kartı", nl: "creditcard", ipa: "kre-die kar-tuh"},
      {tr: "ATM", nl: "geldautomaat", ipa: "a-te-me"},
      {tr: "fiş", nl: "bon", ipa: "fiesh"},
      {tr: "ödeme", nl: "betaling", ipa: "eu-de-me"},
      {tr: "bozuk para", nl: "kleingeld", ipa: "boe-zoek pa-ra"},
      {tr: "fatura", nl: "factuur", ipa: "fa-toe-ra"},
      {tr: "toplam", nl: "totaal", ipa: "top-lam"},
    ],
    phrases: [
      {tr: "Kartla ödeyebilir miyim?", nl: "Kan ik met kaart betalen?", ipa: "kart-la eu-de-je-bie-lier mie-jiem"},
      {tr: "Nakit kabul ediyor musunuz?", nl: "Accepteert u contant geld?", ipa: "na-kiet ka-boel e-die-jor moe-soe-noez"},
      {tr: "ATM nerede?", nl: "Waar is een geldautomaat?", ipa: "a-te-me ne-re-de"},
      {tr: "Fiş alabilir miyim?", nl: "Mag ik een bon?", ipa: "fiesh a-la-bie-lier mie-jiem"},
      {tr: "Toplam ne kadar?", nl: "Wat is het totaal?", ipa: "top-lam ne ka-dar"},
      {tr: "Bozuk para var mı?", nl: "Heeft u kleingeld?", ipa: "boe-zoek pa-ra var muh"},
    ],
    grammar: "Met “-la/-le” zeg je “met”: “kartla” betekent “met kaart” en “nakitle” betekent “met contant geld”. “Ödeyebilir miyim?” betekent “kan ik betalen?” en is beleefd. In Turkije worden kaarten vaak geaccepteerd, maar op markten en kleine plekken is contant geld handig.",
    practice: [
      "1. Vraag of je met kaart kunt betalen.",
      "2. Vraag waar een ATM is.",
      "3. Vraag om een bon.",
      "4. Vraag naar het totaal.",
      "5. Maak twee zinnen met “kartla” en “nakit”.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Problemen oplossen",
    titleNative: "Sorun çözmek",
    focus: "In je hotel of bij vervoer gaat iets mis: wifi werkt niet, de kamer is lawaaiig of een ticket klopt niet. Je leert rustig uitleggen wat het probleem is.",
    vocab: [
      {tr: "sorun", nl: "probleem", ipa: "so-ROEN"},
      {tr: "çalışmıyor", nl: "werkt niet", ipa: "tsja-lush-muh-jor"},
      {tr: "bozuk", nl: "kapot", ipa: "boe-zoek"},
      {tr: "gürültülü", nl: "lawaaiig", ipa: "guu-ruul-tuu-luu"},
      {tr: "temiz değil", nl: "niet schoon", ipa: "te-miez de-jiel"},
      {tr: "yanlış", nl: "verkeerd", ipa: "jan-lush"},
      {tr: "beklemek", nl: "wachten", ipa: "bek-le-mek"},
      {tr: "yardımcı", nl: "behulpzaam", ipa: "jar-dum-djuh"},
      {tr: "değiştirmek", nl: "veranderen / ruilen", ipa: "de-jiesh-tier-mek"},
      {tr: "mümkün", nl: "mogelijk", ipa: "muum-kuun"},
    ],
    phrases: [
      {tr: "Bir sorun var.", nl: "Er is een probleem.", ipa: "bier so-ROEN var"},
      {tr: "İnternet çalışmıyor.", nl: "Het internet werkt niet.", ipa: "in-ter-net tsja-lush-muh-jor"},
      {tr: "Oda temiz değil.", nl: "De kamer is niet schoon.", ipa: "o-da te-miez de-jiel"},
      {tr: "Bu yanlış.", nl: "Dit is verkeerd.", ipa: "boe jan-lush"},
      {tr: "Değiştirmek mümkün mü?", nl: "Is ruilen/veranderen mogelijk?", ipa: "de-jiesh-tier-mek muum-kuun muu"},
      {tr: "Yardımcı olabilir misiniz?", nl: "Kunt u helpen?", ipa: "jar-dum-djuh o-la-bie-lier mie-sie-niez"},
    ],
    grammar: "Ontkenning bij bijvoeglijke naamwoorden gaat vaak met “değil”: “temiz değil” betekent “niet schoon”. Bij werkwoorden zie je ontkenning in het werkwoord: “çalışmıyor” betekent “werkt niet”. Voor klachten klinkt “Bir sorun var” rustig en beleefd. Daarna leg je in één korte zin uit wat er mis is.",
    practice: [
      "1. Zeg dat er een probleem is.",
      "2. Zeg dat internet niet werkt.",
      "3. Zeg dat de kamer niet schoon is.",
      "4. Vraag of ruilen mogelijk is.",
      "5. Maak een beleefde klacht in drie zinnen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Telefoneren en berichten",
    titleNative: "Telefon etmek ve mesajlaşmak",
    focus: "Je moet een hotel bellen, een reservering bevestigen of een bericht sturen. Je leert basiszinnen voor telefoon en tekst.",
    vocab: [
      {tr: "telefon", nl: "telefoon", ipa: "te-le-fon"},
      {tr: "aramak", nl: "bellen", ipa: "a-ra-mak"},
      {tr: "mesaj", nl: "bericht", ipa: "me-sazj"},
      {tr: "numara", nl: "nummer", ipa: "noe-ma-ra"},
      {tr: "rezervasyon", nl: "reservering", ipa: "re-zer-va-sjon"},
      {tr: "onaylamak", nl: "bevestigen", ipa: "o-nai-la-mak"},
      {tr: "bekleyin", nl: "wacht", ipa: "bek-le-jien"},
      {tr: "duymak", nl: "horen", ipa: "doej-mak"},
      {tr: "tekrar", nl: "opnieuw", ipa: "tek-rar"},
      {tr: "yavaş", nl: "langzaam", ipa: "ja-vash"},
    ],
    phrases: [
      {tr: "Telefon numaranız nedir?", nl: "Wat is uw telefoonnummer?", ipa: "te-le-fon noe-ma-ra-nuz ne-dier"},
      {tr: "Rezervasyonumu onaylamak istiyorum.", nl: "Ik wil mijn reservering bevestigen.", ipa: "re-zer-va-sjo-noe-moe o-nai-la-mak is-tie-jo-roem"},
      {tr: "Tekrar eder misiniz?", nl: "Kunt u dat herhalen?", ipa: "tek-rar e-der mie-sie-niez"},
      {tr: "Yavaş konuşur musunuz?", nl: "Kunt u langzaam spreken?", ipa: "ja-vash ko-noe-shoer moe-soe-noez"},
      {tr: "Sizi duyamıyorum.", nl: "Ik kan u niet horen.", ipa: "sie-zie doe-ja-muh-jo-roem"},
      {tr: "Mesaj gönderebilir misiniz?", nl: "Kunt u een bericht sturen?", ipa: "me-sazj geun-de-re-bie-lier mie-sie-niez"},
    ],
    grammar: "Beleefde verzoeken eindigen vaak op “misiniz/musunuz”: “Tekrar eder misiniz?” en “Yavaş konuşur musunuz?” In telefoongesprekken is dit extra handig omdat je misschien niet alles verstaat. “-amıyorum/-emiyorum” drukt uit dat iets niet lukt: “duyamıyorum” betekent “ik kan niet horen.”",
    practice: [
      "1. Vraag iemand langzamer te spreken.",
      "2. Vraag om herhaling.",
      "3. Zeg dat je iemand niet kunt horen.",
      "4. Bevestig een reservering per telefoon.",
      "5. Vraag of iemand een bericht kan sturen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Lokale gewoontes en beleefdheid",
    titleNative: "Yerel adetler ve nezaket",
    focus: "In Turkije wil je respectvol omgaan met thee, moskeeën, gasten en beleefde gesprekken. Je leert culturele zinnen die warmte en respect tonen.",
    vocab: [
      {tr: "adet", nl: "gewoonte", ipa: "a-det"},
      {tr: "saygı", nl: "respect", ipa: "sai-guh"},
      {tr: "misafir", nl: "gast", ipa: "mie-sa-fier"},
      {tr: "ikram", nl: "aangeboden traktatie", ipa: "iek-ram"},
      {tr: "çay", nl: "thee", ipa: "tsjai"},
      {tr: "afiyet olsun", nl: "eet smakelijk", ipa: "a-fie-jet ol-soen"},
      {tr: "elinize sağlık", nl: "compliment voor de kok", ipa: "e-lie-nie-ze sa-luk"},
      {tr: "buyurun", nl: "alstublieft / kom binnen / ga uw gang", ipa: "boe-joe-roen"},
      {tr: "rica ederim", nl: "graag gedaan", ipa: "rie-dja e-de-riem"},
      {tr: "estağfurullah", nl: "geen sprake van / bescheiden reactie", ipa: "es-ta-foe-roel-lah"},
    ],
    phrases: [
      {tr: "Afiyet olsun.", nl: "Eet smakelijk.", ipa: "a-fie-jet ol-soen"},
      {tr: "Elinize sağlık.", nl: "Het was heerlijk, complimenten.", ipa: "e-lie-nie-ze sa-luk"},
      {tr: "Buyurun.", nl: "Alstublieft / gaat uw gang.", ipa: "boe-joe-roen"},
      {tr: "Rica ederim.", nl: "Graag gedaan.", ipa: "rie-dja e-de-riem"},
      {tr: "Çok naziksiniz.", nl: "U bent erg vriendelijk.", ipa: "tsjok na-ziek-sie-niez"},
      {tr: "İkram için teşekkürler.", nl: "Bedankt voor de traktatie.", ipa: "iek-ram ie-tsjien te-sjek-kuur-ler"},
    ],
    grammar: "Turkse beleefdheid gebruikt veel vaste uitdrukkingen. “Afiyet olsun” zeg je voor, tijdens of na het eten. “Elinize sağlık” betekent letterlijk iets als “gezondheid aan uw handen” en is een mooi compliment voor iemand die eten heeft gemaakt. “Buyurun” heeft veel betekenissen en hangt af van de situatie, maar klinkt bijna altijd gastvrij.",
    practice: [
      "1. Zeg “eet smakelijk” in het Turks.",
      "2. Complimenteer iemand die eten heeft gemaakt.",
      "3. Bedank voor aangeboden thee.",
      "4. Reageer op bedankt met “rica ederim”.",
      "5. Maak een korte beleefde uitwisseling met drie vaste uitdrukkingen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Alles samen gebruiken",
    titleNative: "Her şeyi birlikte kullanmak",
    focus: "Je brengt een volledige reisdag door in Istanbul: ontbijt, vervoer, museum, restaurant en hotel. Deze laatste les combineert vragen, bestellen, betalen en problemen oplossen.",
    vocab: [
      {tr: "gezi", nl: "uitstap / trip", ipa: "ge-zie"},
      {tr: "plan", nl: "plan", ipa: "plan"},
      {tr: "başlamak", nl: "beginnen", ipa: "bash-la-mak"},
      {tr: "bitmek", nl: "eindigen", ipa: "biet-mek"},
      {tr: "rezervasyon", nl: "reservering", ipa: "re-zer-va-sjon"},
      {tr: "tavsiye", nl: "aanbeveling", ipa: "tav-sie-je"},
      {tr: "hatırlamak", nl: "onthouden", ipa: "ha-tur-la-mak"},
      {tr: "unutmak", nl: "vergeten", ipa: "oe-noet-mak"},
      {tr: "hazır", nl: "klaar", ipa: "ha-zur"},
      {tr: "güvenli", nl: "veilig", ipa: "guu-ven-lie"},
    ],
    phrases: [
      {tr: "Bugün gezi planım var.", nl: "Ik heb vandaag een reisplan.", ipa: "boe-guun ge-zie pla-num var"},
      {tr: "Nereden başlamalıyım?", nl: "Waar moet ik beginnen?", ipa: "ne-re-den bash-la-ma-luh-jum"},
      {tr: "Ne tavsiye edersiniz?", nl: "Wat raadt u aan?", ipa: "ne tav-sie-je e-der-sie-niez"},
      {tr: "Rezervasyonumu unuttum.", nl: "Ik ben mijn reservering vergeten.", ipa: "re-zer-va-sjo-noe-moe oe-noet-toem"},
      {tr: "Hazırım.", nl: "Ik ben klaar.", ipa: "ha-zu-rum"},
      {tr: "Güvenli mi?", nl: "Is het veilig?", ipa: "guu-ven-lie mie"},
    ],
    grammar: "Je kunt nu veel reizen met korte bouwstenen: vraagwoord + onderwerp + beleefde vorm. “Ne tavsiye edersiniz?” werkt in restaurants, hotels en bij locals. “-malıyım/-meliyim” betekent “ik moet”: “başlamalıyım” is “ik moet beginnen”. Gebruik bekende zinnen in combinaties in plaats van te wachten tot je elke regel perfect kunt maken.",
    practice: [
      "1. Maak een ochtendplan met ontbijt en vervoer.",
      "2. Vraag een local om een aanbeveling.",
      "3. Vraag of een plek veilig is.",
      "4. Los een vergeten reservering op met twee zinnen.",
      "5. Schrijf een mini-reisdag van vijf Turkse zinnen.",
    ],
    conversationIndex: 0,
    conversationCount: 8,
  },
];

var CONVERSATIONS_NL_TR = [
  {
    setting: "",
    lines: [
      {who: "them", tr: "Merhaba, buyurun.", nl: "Hallo, gaat uw gang."},
      {who: "you", tr: "Merhaba, bir kahve lütfen.", nl: "Hallo, één koffie alstublieft."},
      {who: "them", tr: "Sade mi, sütlü mü?", nl: "Zwart of met melk?"},
      {who: "you", tr: "Sütlü kahve istiyorum.", nl: "Ik wil koffie met melk."},
      {who: "them", tr: "Başka bir şey ister misiniz?", nl: "Wilt u nog iets anders?"},
      {who: "you", tr: "Bir simit var mı?", nl: "Is er een simit?"},
      {who: "them", tr: "Evet, taze simit var.", nl: "Ja, er is verse simit."},
      {who: "you", tr: "Harika, bir simit de lütfen.", nl: "Geweldig, ook één simit alstublieft."},
      {who: "them", tr: "Burada mı, paket mi?", nl: "Hier of om mee te nemen?"},
      {who: "you", tr: "Burada lütfen.", nl: "Hier alstublieft."},
      {who: "them", tr: "Tamam, hemen geliyor.", nl: "Oké, het komt eraan."},
      {who: "you", tr: "Teşekkürler.", nl: "Bedankt."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", tr: "Merhaba, hoş geldiniz.", nl: "Hallo, welkom."},
      {who: "you", tr: "Merhaba, rezervasyonum var.", nl: "Hallo, ik heb een reservering."},
      {who: "them", tr: "Adınız nedir?", nl: "Wat is uw naam?"},
      {who: "you", tr: "Adım Cannon.", nl: "Mijn naam is Cannon."},
      {who: "them", tr: "Pasaport alabilir miyim?", nl: "Mag ik uw paspoort?"},
      {who: "you", tr: "Evet, buyurun.", nl: "Ja, alstublieft."},
      {who: "them", tr: "Odanız hazır.", nl: "Uw kamer is klaar."},
      {who: "you", tr: "Kahvaltı saat kaçta?", nl: "Hoe laat is het ontbijt?"},
      {who: "them", tr: "Kahvaltı saat yedide başlıyor.", nl: "Het ontbijt begint om zeven uur."},
      {who: "you", tr: "İnternet şifresi nedir?", nl: "Wat is het wifiwachtwoord?"},
      {who: "them", tr: "Şifre resepsiyonda yazıyor.", nl: "Het wachtwoord staat bij de receptie."},
      {who: "you", tr: "Teşekkürler, iyi akşamlar.", nl: "Bedankt, goedenavond."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", tr: "Merhaba, müze nerede?", nl: "Hallo, waar is het museum?"},
      {who: "them", tr: "Merhaba, hangi müze?", nl: "Hallo, welk museum?"},
      {who: "you", tr: "Antalya Müzesi.", nl: "Het Antalya Museum."},
      {who: "them", tr: "Buradan biraz uzak.", nl: "Het is een beetje ver hiervandaan."},
      {who: "you", tr: "Nasıl gidilir?", nl: "Hoe kom je er?"},
      {who: "them", tr: "Düz gidin, sonra sağa dönün.", nl: "Ga rechtdoor en sla daarna rechtsaf."},
      {who: "you", tr: "Hangi durakta inmeliyim?", nl: "Bij welke halte moet ik uitstappen?"},
      {who: "them", tr: "Müze durağında inin.", nl: "Stap uit bij de museumhalte."},
      {who: "you", tr: "Haritada gösterebilir misiniz?", nl: "Kunt u het op de kaart laten zien?"},
      {who: "them", tr: "Evet, burada.", nl: "Ja, hier."},
      {who: "you", tr: "Çok teşekkürler.", nl: "Heel erg bedankt."},
      {who: "them", tr: "Rica ederim.", nl: "Graag gedaan."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", tr: "Hoş geldiniz, kaç kişi?", nl: "Welkom, hoeveel personen?"},
      {who: "you", tr: "İki kişi.", nl: "Twee personen."},
      {who: "them", tr: "Buyurun, menü burada.", nl: "Gaat uw gang, het menu is hier."},
      {who: "you", tr: "Ne önerirsiniz?", nl: "Wat raadt u aan?"},
      {who: "them", tr: "Lahmacun ve çorba çok güzel.", nl: "Lahmacun en soep zijn erg lekker."},
      {who: "you", tr: "Bir çorba ve bir lahmacun istiyorum.", nl: "Ik wil één soep en één lahmacun."},
      {who: "them", tr: "İçecek ister misiniz?", nl: "Wilt u iets te drinken?"},
      {who: "you", tr: "Bir ayran lütfen.", nl: "Eén ayran alstublieft."},
      {who: "them", tr: "Tamam, hemen getiriyorum.", nl: "Oké, ik breng het zo."},
      {who: "you", tr: "Çok lezzetli, teşekkürler.", nl: "Erg lekker, bedankt."},
      {who: "you", tr: "Hesap lütfen.", nl: "De rekening alstublieft."},
      {who: "them", tr: "Tabii, hemen.", nl: "Natuurlijk, meteen."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", tr: "Merhaba, nasıl yardımcı olabilirim?", nl: "Hallo, hoe kan ik helpen?"},
      {who: "you", tr: "Merhaba, Taksim’e gitmek istiyorum.", nl: "Hallo, ik wil naar Taksim gaan."},
      {who: "them", tr: "İstanbulkartınız var mı?", nl: "Heeft u een Istanbulkart?"},
      {who: "you", tr: "Hayır, yok.", nl: "Nee, die heb ik niet."},
      {who: "them", tr: "Buradan alabilirsiniz.", nl: "U kunt die hier kopen."},
      {who: "you", tr: "Bir kart lütfen.", nl: "Eén kaart alstublieft."},
      {who: "them", tr: "Nereye gideceksiniz?", nl: "Waar gaat u heen?"},
      {who: "you", tr: "Taksim’e gideceğim.", nl: "Ik ga naar Taksim."},
      {who: "them", tr: "Bu metro Taksim’e gider.", nl: "Deze metro gaat naar Taksim."},
      {who: "you", tr: "Aktarma var mı?", nl: "Is er een overstap?"},
      {who: "them", tr: "Hayır, direkt.", nl: "Nee, direct."},
      {who: "you", tr: "Teşekkürler.", nl: "Bedankt."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", tr: "Buyurun, bakabilirsiniz.", nl: "Gaat uw gang, u kunt kijken."},
      {who: "you", tr: "Merhaba, bu çanta kaç para?", nl: "Hallo, hoeveel kost deze tas?"},
      {who: "them", tr: "Beş yüz lira.", nl: "Vijfhonderd lira."},
      {who: "you", tr: "Çok güzel ama biraz pahalı.", nl: "Heel mooi, maar een beetje duur."},
      {who: "them", tr: "Hediye için mi?", nl: "Is het voor een cadeau?"},
      {who: "you", tr: "Evet, hediye için.", nl: "Ja, voor een cadeau."},
      {who: "them", tr: "Bu renk çok popüler.", nl: "Deze kleur is erg populair."},
      {who: "you", tr: "Daha ucuz olur mu?", nl: "Kan het goedkoper?"},
      {who: "them", tr: "Dört yüz elli lira olur.", nl: "Vierhonderdvijftig lira kan."},
      {who: "you", tr: "Tamam, alıyorum.", nl: "Oké, ik neem het."},
      {who: "them", tr: "Paket olsun mu?", nl: "Wilt u het ingepakt?"},
      {who: "you", tr: "Evet, lütfen.", nl: "Ja, alstublieft."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", tr: "Merhaba, nasıl yardımcı olabilirim?", nl: "Hallo, hoe kan ik helpen?"},
      {who: "you", tr: "Merhaba, başım ağrıyor.", nl: "Hallo, mijn hoofd doet pijn."},
      {who: "them", tr: "Ateş var mı?", nl: "Heeft u koorts?"},
      {who: "you", tr: "Hayır, ateş yok.", nl: "Nee, geen koorts."},
      {who: "them", tr: "Alerjiniz var mı?", nl: "Heeft u een allergie?"},
      {who: "you", tr: "Evet, fındık alerjim var.", nl: "Ja, ik heb een notenallergie."},
      {who: "them", tr: "Tamam, bu ilacı alabilirsiniz.", nl: "Oké, u kunt dit medicijn nemen."},
      {who: "you", tr: "Reçetesiz mi?", nl: "Is het zonder recept?"},
      {who: "them", tr: "Evet, reçetesiz.", nl: "Ja, zonder recept."},
      {who: "you", tr: "Nasıl kullanmalıyım?", nl: "Hoe moet ik het gebruiken?"},
      {who: "them", tr: "Yemekten sonra alın.", nl: "Neem het na het eten."},
      {who: "you", tr: "Teşekkürler.", nl: "Bedankt."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", tr: "Merhaba, burası boş mu?", nl: "Hallo, is deze plek vrij?"},
      {who: "them", tr: "Evet, buyurun.", nl: "Ja, gaat uw gang."},
      {who: "you", tr: "Teşekkürler, bu şehir çok güzel.", nl: "Bedankt, deze stad is erg mooi."},
      {who: "them", tr: "Teşekkürler, siz nerelisiniz?", nl: "Bedankt, waar komt u vandaan?"},
      {who: "you", tr: "Ben Hollandalıyım.", nl: "Ik ben Nederlander."},
      {who: "them", tr: "Türkiye’ye tatil için mi geldiniz?", nl: "Bent u voor vakantie naar Turkije gekomen?"},
      {who: "you", tr: "Evet, tatil için geldim.", nl: "Ja, ik ben voor vakantie gekomen."},
      {who: "them", tr: "Türk çayı sever misiniz?", nl: "Houdt u van Turkse thee?"},
      {who: "you", tr: "Evet, çok seviyorum.", nl: "Ja, ik vind het erg lekker."},
      {who: "them", tr: "Afiyet olsun.", nl: "Geniet ervan."},
      {who: "you", tr: "Sohbet için teşekkürler.", nl: "Bedankt voor het gesprek."},
      {who: "them", tr: "Rica ederim, iyi geziler.", nl: "Graag gedaan, fijne reis."},
    ],
  },
];