var COURSE_HI_EN = [
{
  day: 1,
  title: "नमस्ते और परिचय",
  titleNative: "Greetings and Introductions",
  focus: "आज आप न्यूयॉर्क जैसे शहर में किसी से पहली बार मिलते समय सरल अभिवादन और अपना नाम बताना सीखेंगे। यह दिन यात्रा की सबसे बुनियादी बातचीत के लिए आधार बनाता है।",
  vocab: [{ en: "hello", hi: "नमस्ते", ipa: "heh-loh" }, { en: "hi", hi: "हाय", ipa: "hai" }, { en: "goodbye", hi: "अलविदा", ipa: "gud-bai" }, { en: "please", hi: "कृपया", ipa: "pleez" }, { en: "thank you", hi: "धन्यवाद", ipa: "thank yoo" }, { en: "yes", hi: "हाँ", ipa: "yes" }, { en: "no", hi: "नहीं", ipa: "noh" }, { en: "name", hi: "नाम", ipa: "naym" }, { en: "friend", hi: "दोस्त", ipa: "frend" }, { en: "welcome", hi: "स्वागत है", ipa: "wel-kum" }],
  phrases: [{ en: "Hello, my name is Ravi.", hi: "नमस्ते, मेरा नाम रवि है।", ipa: "heh-loh, mai naym iz rah-vee" }, { en: "Nice to meet you.", hi: "आपसे मिलकर खुशी हुई।", ipa: "nais too meet yoo" }, { en: "What is your name?", hi: "आपका नाम क्या है?", ipa: "wot iz yor naym" }, { en: "Thank you very much.", hi: "आपका बहुत धन्यवाद।", ipa: "thank yoo veh-ree much" }, { en: "You are welcome.", hi: "आपका स्वागत है।", ipa: "yoo ar wel-kum" }, { en: "Goodbye, see you soon.", hi: "अलविदा, जल्द मिलते हैं।", ipa: "gud-bai, see yoo soon" }],
  grammar: "अंग्रेज़ी में “I am” का प्रयोग अपना परिचय देने के लिए किया जाता है। “I am Ravi” का अर्थ है “मैं रवि हूँ”। बोलचाल में “I am” अक्सर “I’m” बन जाता है। नाम पूछने के लिए “What is your name?” बहुत सामान्य और विनम्र वाक्य है।",
  practice: ["अपना नाम अंग्रेज़ी में बताइए।", "“Nice to meet you” बोलकर अभ्यास कीजिए।", "किसी दोस्त से अंग्रेज़ी में उसका नाम पूछिए।", "“please” और “thank you” का प्रयोग करते हुए दो छोटे वाक्य बनाइए।", "कल्पना कीजिए कि आप एयरपोर्ट पर किसी नए व्यक्ति से मिल रहे हैं।"]
},
{
  day: 2,
  title: "बुनियादी विनम्रता",
  titleNative: "Basic Politeness",
  focus: "आज आप लंदन में दुकानों, स्टेशनों और कैफ़े में इस्तेमाल होने वाले विनम्र शब्द सीखेंगे। छोटे polite expressions यात्रा को आसान और सुखद बनाते हैं।",
  vocab: [{ en: "sorry", hi: "माफ़ कीजिए", ipa: "sor-ee" }, { en: "excuse me", hi: "क्षमा कीजिए / सुनिए", ipa: "eks-kyooz mee" }, { en: "help", hi: "मदद", ipa: "help" }, { en: "okay", hi: "ठीक है", ipa: "oh-kay" }, { en: "fine", hi: "ठीक / अच्छा", ipa: "fain" }, { en: "good", hi: "अच्छा", ipa: "gud" }, { en: "bad", hi: "बुरा", ipa: "bad" }, { en: "morning", hi: "सुबह", ipa: "mor-ning" }, { en: "evening", hi: "शाम", ipa: "eev-ning" }, { en: "night", hi: "रात", ipa: "nait" }],
  phrases: [{ en: "Excuse me, please.", hi: "क्षमा कीजिए, कृपया।", ipa: "eks-kyooz mee, pleez" }, { en: "I am sorry.", hi: "मुझे माफ़ कीजिए।", ipa: "ai am sor-ee" }, { en: "That is okay.", hi: "वह ठीक है।", ipa: "that iz oh-kay" }, { en: "Good morning.", hi: "सुप्रभात।", ipa: "gud mor-ning" }, { en: "Good evening.", hi: "शुभ संध्या।", ipa: "gud eev-ning" }, { en: "Can you help me?", hi: "क्या आप मेरी मदद कर सकते हैं?", ipa: "kan yoo help mee" }],
  grammar: "अंग्रेज़ी में “Can you...” से विनम्र अनुरोध किया जाता है। “Can you help me?” का अर्थ है “क्या आप मेरी मदद कर सकते हैं?” “Excuse me” किसी का ध्यान आकर्षित करने या रास्ता मांगने के लिए उपयोगी है। “Sorry” गलती, असुविधा या टकराने पर तुरंत कहा जा सकता है।",
  practice: ["“Excuse me” बोलकर किसी से रास्ता पूछने का अभ्यास कीजिए।", "“Can you help me?” तीन बार धीरे-धीरे बोलिए।", "सुबह और शाम के अभिवादन लिखिए।", "“Sorry” और “That is okay” के साथ छोटा संवाद बनाइए।", "कल्पना कीजिए कि आप लंदन की दुकान में कर्मचारी से मदद मांग रहे हैं।"]
},
{
  day: 3,
  title: "नंबर और कीमतें",
  titleNative: "Numbers and Prices",
  focus: "आज आप टोरंटो में टिकट, कॉफ़ी और छोटी खरीदारी के लिए नंबर और कीमतें बोलना सीखेंगे। यात्रा में पैसे समझना बहुत ज़रूरी है।",
  vocab: [{ en: "one", hi: "एक", ipa: "wun" }, { en: "two", hi: "दो", ipa: "too" }, { en: "three", hi: "तीन", ipa: "three" }, { en: "four", hi: "चार", ipa: "for" }, { en: "five", hi: "पाँच", ipa: "faiv" }, { en: "six", hi: "छह", ipa: "siks" }, { en: "seven", hi: "सात", ipa: "seh-vun" }, { en: "eight", hi: "आठ", ipa: "ayt" }, { en: "nine", hi: "नौ", ipa: "nain" }, { en: "ten", hi: "दस", ipa: "ten" }],
  phrases: [{ en: "How much is this?", hi: "यह कितने का है?", ipa: "hau much iz this" }, { en: "It is five dollars.", hi: "यह पाँच डॉलर का है।", ipa: "it iz faiv dol-erz" }, { en: "I need two tickets.", hi: "मुझे दो टिकट चाहिए।", ipa: "ai need too tik-its" }, { en: "One coffee, please.", hi: "एक कॉफ़ी, कृपया।", ipa: "wun kaw-fee, pleez" }, { en: "Can I pay now?", hi: "क्या मैं अभी भुगतान कर सकता हूँ?", ipa: "kan ai pay nau" }, { en: "That is too expensive.", hi: "यह बहुत महंगा है।", ipa: "that iz too ik-spen-siv" }],
  grammar: "अंग्रेज़ी में संख्या आमतौर पर noun से पहले आती है, जैसे “two tickets”। एक चीज़ के लिए noun singular रहता है, जैसे “one ticket”। दो या अधिक चीज़ों के लिए अक्सर noun में “s” लगता है, जैसे “two tickets”। कीमत पूछने के लिए “How much is this?” बहुत उपयोगी वाक्य है।",
  practice: ["1 से 10 तक अंग्रेज़ी में बोलिए।", "“I need two tickets” को अपनी आवाज़ में दोहराइए।", "तीन अलग-अलग चीज़ों की कीमत पूछने के वाक्य बनाइए।", "“one coffee” और “two coffees” का अंतर समझाइए।", "कल्पना कीजिए कि आप टोरंटो में बस टिकट खरीद रहे हैं।"]
},
{
  day: 4,
  title: "समय और दिन",
  titleNative: "Time and Days",
  focus: "आज आप सिडनी में ट्रेन, संग्रहालय और टूर के समय समझना सीखेंगे। समय पूछना और बताना हर यात्री के लिए आवश्यक है।",
  vocab: [{ en: "time", hi: "समय", ipa: "taim" }, { en: "today", hi: "आज", ipa: "tuh-day" }, { en: "tomorrow", hi: "कल", ipa: "tuh-mor-oh" }, { en: "yesterday", hi: "कल / बीता हुआ कल", ipa: "yes-ter-day" }, { en: "Monday", hi: "सोमवार", ipa: "mun-day" }, { en: "Tuesday", hi: "मंगलवार", ipa: "tyooz-day" }, { en: "morning", hi: "सुबह", ipa: "mor-ning" }, { en: "afternoon", hi: "दोपहर", ipa: "af-ter-noon" }, { en: "evening", hi: "शाम", ipa: "eev-ning" }, { en: "late", hi: "देर", ipa: "layt" }],
  phrases: [{ en: "What time is it?", hi: "अभी कितने बजे हैं?", ipa: "wot taim iz it" }, { en: "It is three o’clock.", hi: "तीन बजे हैं।", ipa: "it iz three uh-klok" }, { en: "Is it open today?", hi: "क्या यह आज खुला है?", ipa: "iz it oh-pun tuh-day" }, { en: "I am late.", hi: "मुझे देर हो गई है।", ipa: "ai am layt" }, { en: "See you tomorrow.", hi: "कल मिलते हैं।", ipa: "see yoo tuh-mor-oh" }, { en: "The tour starts at ten.", hi: "टूर दस बजे शुरू होता है।", ipa: "theh tor starts at ten" }],
  grammar: "समय बताने के लिए “It is...” का प्रयोग होता है। “at” का प्रयोग किसी खास समय के साथ किया जाता है, जैसे “at ten”। “today,” “tomorrow,” और “yesterday” यात्रा में योजनाओं को साफ़ करने के लिए ज़रूरी हैं। “Is it open today?” दुकान, म्यूज़ियम या रेस्तरां के लिए बहुत उपयोगी प्रश्न है।",
  practice: ["अभी का समय अंग्रेज़ी में बोलने की कोशिश कीजिए।", "“The tour starts at ten” बोलकर अभ्यास कीजिए।", "तीन दिनों के नाम अंग्रेज़ी में लिखिए।", "किसी दुकान के खुलने का समय पूछने वाला वाक्य बनाइए।", "कल्पना कीजिए कि आप सिडनी में नाव टूर के समय की पुष्टि कर रहे हैं।"]
},
{
  day: 5,
  title: "एयरपोर्ट पर",
  titleNative: "At the Airport",
  focus: "आज आप सैन फ्रांसिस्को एयरपोर्ट पर arrival, luggage और immigration से जुड़ी अंग्रेज़ी सीखेंगे। यह पाठ लंबी यात्रा के पहले बड़े पड़ाव के लिए है।",
  vocab: [{ en: "airport", hi: "हवाई अड्डा", ipa: "air-port" }, { en: "flight", hi: "उड़ान", ipa: "flait" }, { en: "passport", hi: "पासपोर्ट", ipa: "pas-port" }, { en: "ticket", hi: "टिकट", ipa: "tik-it" }, { en: "luggage", hi: "सामान", ipa: "lug-ij" }, { en: "gate", hi: "गेट", ipa: "gayt" }, { en: "arrival", hi: "आगमन", ipa: "uh-rai-vul" }, { en: "departure", hi: "प्रस्थान", ipa: "dih-par-cher" }, { en: "security", hi: "सुरक्षा जांच", ipa: "si-kyoor-uh-tee" }, { en: "boarding", hi: "विमान में चढ़ना", ipa: "bor-ding" }],
  phrases: [{ en: "Where is my gate?", hi: "मेरा गेट कहाँ है?", ipa: "wair iz mai gayt" }, { en: "Here is my passport.", hi: "यह मेरा पासपोर्ट है।", ipa: "heer iz mai pas-port" }, { en: "I have one bag.", hi: "मेरे पास एक बैग है।", ipa: "ai hav wun bag" }, { en: "My flight is delayed.", hi: "मेरी उड़ान देर से है।", ipa: "mai flait iz dih-layd" }, { en: "Where is baggage claim?", hi: "सामान लेने की जगह कहाँ है?", ipa: "wair iz bag-ij klaym" }, { en: "I am here for tourism.", hi: "मैं पर्यटन के लिए यहाँ हूँ।", ipa: "ai am heer for toor-iz-um" }],
  grammar: "एयरपोर्ट पर “Where is...” बहुत उपयोगी है क्योंकि आपको जगहें ढूंढनी होती हैं। “Here is...” का प्रयोग कोई दस्तावेज़ या चीज़ दिखाने के लिए होता है। “I have...” से आप अपने पास मौजूद चीज़ बताते हैं। Immigration में छोटे और स्पष्ट वाक्य बोलना सबसे अच्छा रहता है।",
  practice: ["“Here is my passport” बोलकर अभ्यास कीजिए।", "अपने बैग की संख्या अंग्रेज़ी में बताइए।", "गेट पूछने का वाक्य लिखिए।", "“I am here for tourism” को याद कीजिए।", "कल्पना कीजिए कि अधिकारी आपसे यात्रा का उद्देश्य पूछ रहा है।"]
},
{
  day: 6,
  title: "होटल में चेक-इन",
  titleNative: "Hotel Check-In",
  focus: "आज आप डबलिन के होटल में check-in, reservation और room से जुड़े वाक्य सीखेंगे। होटल में स्पष्ट अंग्रेज़ी बोलने से शुरुआत आसान होती है।",
  vocab: [{ en: "hotel", hi: "होटल", ipa: "hoh-tel" }, { en: "reservation", hi: "आरक्षण", ipa: "rez-er-vay-shun" }, { en: "room", hi: "कमरा", ipa: "room" }, { en: "key", hi: "चाबी", ipa: "kee" }, { en: "reception", hi: "रिसेप्शन", ipa: "ri-sep-shun" }, { en: "check-in", hi: "चेक-इन", ipa: "chek-in" }, { en: "check-out", hi: "चेक-आउट", ipa: "chek-aut" }, { en: "breakfast", hi: "नाश्ता", ipa: "brek-fust" }, { en: "elevator", hi: "लिफ्ट", ipa: "el-uh-vay-ter" }, { en: "floor", hi: "मंज़िल", ipa: "flor" }],
  phrases: [{ en: "I have a reservation.", hi: "मेरा आरक्षण है।", ipa: "ai hav uh rez-er-vay-shun" }, { en: "My name is Priya Sharma.", hi: "मेरा नाम प्रिया शर्मा है।", ipa: "mai naym iz pree-yah shar-ma" }, { en: "Can I check in now?", hi: "क्या मैं अभी चेक-इन कर सकता हूँ?", ipa: "kan ai chek in nau" }, { en: "What time is breakfast?", hi: "नाश्ता कितने बजे है?", ipa: "wot taim iz brek-fust" }, { en: "Where is the elevator?", hi: "लिफ्ट कहाँ है?", ipa: "wair iz thee el-uh-vay-ter" }, { en: "Can I have the key, please?", hi: "क्या मुझे चाबी मिल सकती है?", ipa: "kan ai hav thee kee, pleez" }],
  grammar: "“I have a reservation” होटल में सबसे महत्वपूर्ण वाक्यों में से एक है। विनम्र अनुरोध के लिए “Can I have...” का प्रयोग किया जाता है। “What time is...” से आप किसी सेवा का समय पूछ सकते हैं। होटल स्टाफ से बात करते समय “please” और “thank you” ज़रूर जोड़ें।",
  practice: ["अपने नाम के साथ “I have a reservation” बोलिए।", "नाश्ते का समय पूछने वाला वाक्य बनाइए।", "“Where is the elevator?” तीन बार बोलिए।", "कमरे की चाबी मांगने का अभ्यास कीजिए।", "कल्पना कीजिए कि आप डबलिन के होटल रिसेप्शन पर हैं।"]
},
{
  day: 7,
  title: "कमरे की समस्याएँ",
  titleNative: "Room Problems",
  focus: "आज आप ऑकलैंड के होटल में कमरे की छोटी समस्याएँ बताना सीखेंगे। यह पाठ AC, Wi-Fi, पानी और सफ़ाई जैसी यात्रियों की आम ज़रूरतों पर केंद्रित है।",
  vocab: [{ en: "problem", hi: "समस्या", ipa: "prob-lum" }, { en: "Wi-Fi", hi: "वाई-फाई", ipa: "wai-fai" }, { en: "shower", hi: "शॉवर", ipa: "shau-er" }, { en: "water", hi: "पानी", ipa: "waw-ter" }, { en: "hot", hi: "गर्म", ipa: "hot" }, { en: "cold", hi: "ठंडा", ipa: "kohld" }, { en: "towel", hi: "तौलिया", ipa: "tau-ul" }, { en: "clean", hi: "साफ़", ipa: "kleen" }, { en: "broken", hi: "टूटा हुआ", ipa: "broh-kun" }, { en: "noise", hi: "शोर", ipa: "noiz" }],
  phrases: [{ en: "The Wi-Fi is not working.", hi: "वाई-फाई काम नहीं कर रहा है।", ipa: "theh wai-fai iz not wer-king" }, { en: "The shower is cold.", hi: "शॉवर ठंडा है।", ipa: "theh shau-er iz kohld" }, { en: "I need a towel, please.", hi: "मुझे एक तौलिया चाहिए, कृपया।", ipa: "ai need uh tau-ul, pleez" }, { en: "The room is noisy.", hi: "कमरा शोर वाला है।", ipa: "theh room iz noiz-ee" }, { en: "Can you fix it?", hi: "क्या आप इसे ठीक कर सकते हैं?", ipa: "kan yoo fiks it" }, { en: "Can I change rooms?", hi: "क्या मैं कमरा बदल सकता हूँ?", ipa: "kan ai chaynj roomz" }],
  grammar: "समस्या बताने के लिए “The...” से शुरुआत करना आसान है। “The Wi-Fi is not working” सीधे और स्पष्ट तरीके से समस्या बताता है। “I need...” से आप तुरंत अपनी ज़रूरत बता सकते हैं। “Can you fix it?” होटल या अपार्टमेंट में बहुत उपयोगी वाक्य है।",
  practice: ["“The Wi-Fi is not working” बोलकर अभ्यास कीजिए।", "कमरे की एक समस्या अंग्रेज़ी में लिखिए।", "“I need a towel” में towel की जगह दूसरी चीज़ लगाइए।", "“Can you fix it?” को विनम्र आवाज़ में बोलिए।", "कल्पना कीजिए कि आपके होटल कमरे में गर्म पानी नहीं आ रहा है।"]
},
{
  day: 8,
  title: "दिशा पूछना",
  titleNative: "Asking for Directions",
  focus: "आज आप शिकागो में रास्ता पूछना और सरल directions समझना सीखेंगे। शहर में घूमते समय ये वाक्य रोज़ काम आते हैं।",
  vocab: [{ en: "street", hi: "सड़क", ipa: "street" }, { en: "left", hi: "बायाँ", ipa: "left" }, { en: "right", hi: "दायाँ", ipa: "rait" }, { en: "straight", hi: "सीधा", ipa: "strayt" }, { en: "corner", hi: "कोना", ipa: "kor-ner" }, { en: "near", hi: "पास", ipa: "neer" }, { en: "far", hi: "दूर", ipa: "far" }, { en: "map", hi: "नक्शा", ipa: "map" }, { en: "station", hi: "स्टेशन", ipa: "stay-shun" }, { en: "museum", hi: "संग्रहालय", ipa: "myoo-zee-um" }],
  phrases: [{ en: "Where is the station?", hi: "स्टेशन कहाँ है?", ipa: "wair iz thee stay-shun" }, { en: "Go straight.", hi: "सीधे जाइए।", ipa: "goh strayt" }, { en: "Turn left.", hi: "बाएँ मुड़िए।", ipa: "tern left" }, { en: "Turn right.", hi: "दाएँ मुड़िए।", ipa: "tern rait" }, { en: "Is it near here?", hi: "क्या यह यहाँ पास है?", ipa: "iz it neer heer" }, { en: "Can you show me on the map?", hi: "क्या आप मुझे नक्शे पर दिखा सकते हैं?", ipa: "kan yoo show mee on theh map" }],
  grammar: "दिशाओं में command forms जैसे “Go,” “Turn,” और “Stop” बहुत आम हैं। “Where is...” किसी भी जगह के लिए इस्तेमाल किया जा सकता है। “near” पास के लिए और “far” दूर के लिए प्रयोग होता है। नक्शे पर मदद मांगने के लिए “Can you show me on the map?” बहुत अच्छा वाक्य है।",
  practice: ["“Go straight” और “Turn left” बोलकर अभ्यास कीजिए।", "किसी म्यूज़ियम का रास्ता पूछने वाला वाक्य बनाइए।", "“Is it near here?” को याद कीजिए।", "अपने घर से पास की दुकान तक directions अंग्रेज़ी में सोचिए।", "कल्पना कीजिए कि आप शिकागो में ट्रेन स्टेशन ढूंढ रहे हैं।"]
},
{
  day: 9,
  title: "सार्वजनिक परिवहन",
  titleNative: "Public Transportation",
  focus: "आज आप बोस्टन में बस, ट्रेन और subway टिकट से जुड़े वाक्य सीखेंगे। यह पाठ शहर में कम खर्च में घूमने के लिए उपयोगी है।",
  vocab: [{ en: "bus", hi: "बस", ipa: "bus" }, { en: "train", hi: "ट्रेन", ipa: "trayn" }, { en: "subway", hi: "भूमिगत रेल", ipa: "sub-way" }, { en: "ticket", hi: "टिकट", ipa: "tik-it" }, { en: "platform", hi: "प्लेटफ़ॉर्म", ipa: "plat-form" }, { en: "stop", hi: "स्टॉप", ipa: "stop" }, { en: "line", hi: "लाइन", ipa: "lain" }, { en: "card", hi: "कार्ड", ipa: "kard" }, { en: "single", hi: "एकतरफ़ा", ipa: "sing-gul" }, { en: "return", hi: "वापसी", ipa: "ri-tern" }],
  phrases: [{ en: "I need a subway ticket.", hi: "मुझे subway टिकट चाहिए।", ipa: "ai need uh sub-way tik-it" }, { en: "Which line goes downtown?", hi: "कौन सी लाइन downtown जाती है?", ipa: "wich lain gohz daun-taun" }, { en: "Where is the platform?", hi: "प्लेटफ़ॉर्म कहाँ है?", ipa: "wair iz thee plat-form" }, { en: "Does this bus stop here?", hi: "क्या यह बस यहाँ रुकती है?", ipa: "duz this bus stop heer" }, { en: "I want a return ticket.", hi: "मुझे वापसी टिकट चाहिए।", ipa: "ai want uh ri-tern tik-it" }, { en: "How many stops is it?", hi: "यह कितने स्टॉप दूर है?", ipa: "hau meh-nee stops iz it" }],
  grammar: "“Which” का प्रयोग विकल्पों में से सही चीज़ पूछने के लिए होता है। “Which line goes downtown?” में आप सही route पूछ रहे हैं। “Does this bus...” yes/no question है और third person singular के साथ “does” आता है। Transport में “stop” जगह और क्रिया दोनों हो सकता है।",
  practice: ["“Which line goes downtown?” बोलकर अभ्यास कीजिए।", "बस के रुकने का प्रश्न बनाइए।", "“single ticket” और “return ticket” का अंतर समझाइए।", "प्लेटफ़ॉर्म पूछने का वाक्य लिखिए।", "कल्पना कीजिए कि आप बोस्टन subway में टिकट खरीद रहे हैं।"]
},
{
  day: 10,
  title: "टैक्सी और राइड-शेयर",
  titleNative: "Taxi and Ride-Share",
  focus: "आज आप लॉस एंजेलिस में टैक्सी या ride-share लेते समय destination, fare और route बताना सीखेंगे। ड्राइवर से सरल अंग्रेज़ी में बात करना यात्रा को सुरक्षित बनाता है।",
  vocab: [{ en: "taxi", hi: "टैक्सी", ipa: "tak-see" }, { en: "driver", hi: "ड्राइवर", ipa: "drai-ver" }, { en: "address", hi: "पता", ipa: "uh-dres" }, { en: "destination", hi: "मंज़िल", ipa: "des-tuh-nay-shun" }, { en: "fare", hi: "किराया", ipa: "fair" }, { en: "meter", hi: "मीटर", ipa: "mee-ter" }, { en: "traffic", hi: "ट्रैफ़िक", ipa: "traf-ik" }, { en: "fast", hi: "तेज़", ipa: "fast" }, { en: "safe", hi: "सुरक्षित", ipa: "sayf" }, { en: "receipt", hi: "रसीद", ipa: "ri-seet" }],
  phrases: [{ en: "Please take me to this address.", hi: "कृपया मुझे इस पते पर ले चलिए।", ipa: "pleez tayk mee too this uh-dres" }, { en: "How much will it cost?", hi: "इसका कितना खर्च होगा?", ipa: "hau much wil it kost" }, { en: "Is there traffic?", hi: "क्या ट्रैफ़िक है?", ipa: "iz thair traf-ik" }, { en: "Can you go a little slower?", hi: "क्या आप थोड़ा धीरे चला सकते हैं?", ipa: "kan yoo goh uh lit-ul sloh-er" }, { en: "Please stop here.", hi: "कृपया यहाँ रोकिए।", ipa: "pleez stop heer" }, { en: "Can I have a receipt?", hi: "क्या मुझे रसीद मिल सकती है?", ipa: "kan ai hav uh ri-seet" }],
  grammar: "“Please take me to...” destination बताने का सरल तरीका है। “Can you...” से ड्राइवर से विनम्र अनुरोध किया जा सकता है। “a little” का मतलब “थोड़ा” होता है और यह वाक्य को नरम बनाता है। “Please stop here” छोटा लेकिन बहुत उपयोगी वाक्य है।",
  practice: ["अपने होटल का पता बोलने की कल्पना कीजिए।", "“Please take me to this address” तीन बार बोलिए।", "किराया पूछने का वाक्य लिखिए।", "रसीद मांगने का अभ्यास कीजिए।", "कल्पना कीजिए कि आप लॉस एंजेलिस में airport से होटल जा रहे हैं।"]
},
{
  day: 11,
  title: "कैफ़े में ऑर्डर करना",
  titleNative: "Ordering at a Café",
  focus: "आज आप सिएटल के कैफ़े में coffee, tea और snacks ऑर्डर करना सीखेंगे। यह पाठ polite ordering और छोटे customization के लिए है।",
  vocab: [{ en: "coffee", hi: "कॉफ़ी", ipa: "kaw-fee" }, { en: "tea", hi: "चाय", ipa: "tee" }, { en: "milk", hi: "दूध", ipa: "milk" }, { en: "sugar", hi: "चीनी", ipa: "shoo-ger" }, { en: "cup", hi: "कप", ipa: "kup" }, { en: "small", hi: "छोटा", ipa: "smawl" }, { en: "medium", hi: "मध्यम", ipa: "mee-dee-um" }, { en: "large", hi: "बड़ा", ipa: "larj" }, { en: "hot", hi: "गर्म", ipa: "hot" }, { en: "cold", hi: "ठंडा", ipa: "kohld" }],
  phrases: [{ en: "Can I have a coffee, please?", hi: "क्या मुझे एक कॉफ़ी मिल सकती है?", ipa: "kan ai hav uh kaw-fee, pleez" }, { en: "I would like tea.", hi: "मुझे चाय चाहिए।", ipa: "ai wud laik tee" }, { en: "No sugar, please.", hi: "चीनी नहीं, कृपया।", ipa: "noh shoo-ger, pleez" }, { en: "With milk, please.", hi: "दूध के साथ, कृपया।", ipa: "with milk, pleez" }, { en: "For here or to go?", hi: "यहाँ के लिए या ले जाने के लिए?", ipa: "for heer or too goh" }, { en: "To go, please.", hi: "ले जाने के लिए, कृपया।", ipa: "too goh, pleez" }],
  grammar: "ऑर्डर करते समय “Can I have...” बहुत स्वाभाविक और विनम्र है। “I would like...” थोड़ा अधिक formal और साफ़ विकल्प है। “To go” का मतलब है खाना या पेय साथ ले जाना। “For here” का मतलब है वहीं बैठकर खाना या पीना।",
  practice: ["अपनी पसंद की coffee या tea अंग्रेज़ी में ऑर्डर कीजिए।", "“No sugar, please” बोलकर अभ्यास कीजिए।", "small, medium, large को क्रम में बोलिए।", "“for here” और “to go” का अभ्यास कीजिए।", "कल्पना कीजिए कि आप सिएटल में सुबह कैफ़े में हैं।"]
},
{
  day: 12,
  title: "रेस्तरां में खाना",
  titleNative: "Eating at a Restaurant",
  focus: "आज आप मेलबर्न के रेस्तरां में menu, table और bill से जुड़े वाक्य सीखेंगे। बैठकर खाना खाते समय ये expressions बहुत काम आते हैं।",
  vocab: [{ en: "restaurant", hi: "रेस्तरां", ipa: "res-tuh-ront" }, { en: "menu", hi: "मेन्यू", ipa: "men-yoo" }, { en: "table", hi: "टेबल", ipa: "tay-bul" }, { en: "waiter", hi: "वेटर", ipa: "way-ter" }, { en: "water", hi: "पानी", ipa: "waw-ter" }, { en: "starter", hi: "शुरुआत का खाना", ipa: "star-ter" }, { en: "main course", hi: "मुख्य भोजन", ipa: "mayn kors" }, { en: "dessert", hi: "मिठाई", ipa: "dih-zert" }, { en: "bill", hi: "बिल", ipa: "bil" }, { en: "tip", hi: "टिप", ipa: "tip" }],
  phrases: [{ en: "A table for two, please.", hi: "दो लोगों के लिए टेबल, कृपया।", ipa: "uh tay-bul for too, pleez" }, { en: "Can I see the menu?", hi: "क्या मैं मेन्यू देख सकता हूँ?", ipa: "kan ai see theh men-yoo" }, { en: "I would like water.", hi: "मुझे पानी चाहिए।", ipa: "ai wud laik waw-ter" }, { en: "What do you recommend?", hi: "आप क्या सुझाते हैं?", ipa: "wot doo yoo rek-uh-mend" }, { en: "Can we have the bill?", hi: "क्या हमें बिल मिल सकता है?", ipa: "kan wee hav theh bil" }, { en: "The food was delicious.", hi: "खाना स्वादिष्ट था।", ipa: "theh food wuz dih-lish-us" }],
  grammar: "रेस्तरां में “I would like...” से ऑर्डर करना अच्छा लगता है। “What do you recommend?” स्थानीय खाना जानने के लिए उपयोगी है। “The food was...” past tense में feedback देने का तरीका है। “Can we have the bill?” अमेरिका, कनाडा और ऑस्ट्रेलिया जैसे देशों में सामान्य है।",
  practice: ["दो लोगों के लिए टेबल मांगने का अभ्यास कीजिए।", "“What do you recommend?” बोलकर याद कीजिए।", "पानी मांगने वाला वाक्य बनाइए।", "बिल मांगने का विनम्र वाक्य लिखिए।", "कल्पना कीजिए कि आप मेलबर्न में dinner कर रहे हैं।"]
},
{
  day: 13,
  title: "खाने की पसंद और एलर्जी",
  titleNative: "Food Preferences and Allergies",
  focus: "आज आप वैंकूवर में vegetarian food, allergies और dietary needs बताना सीखेंगे। यह पाठ स्वास्थ्य और आराम दोनों के लिए ज़रूरी है।",
  vocab: [{ en: "vegetarian", hi: "शाकाहारी", ipa: "vej-uh-tair-ee-un" }, { en: "vegan", hi: "पूर्ण शाकाहारी", ipa: "vee-gun" }, { en: "allergy", hi: "एलर्जी", ipa: "al-er-jee" }, { en: "nuts", hi: "मेवे", ipa: "nuts" }, { en: "seafood", hi: "समुद्री भोजन", ipa: "see-food" }, { en: "spicy", hi: "तीखा", ipa: "spai-see" }, { en: "mild", hi: "कम तीखा", ipa: "maild" }, { en: "meat", hi: "मांस", ipa: "meet" }, { en: "egg", hi: "अंडा", ipa: "eg" }, { en: "dairy", hi: "दूध से बनी चीज़ें", ipa: "dair-ee" }],
  phrases: [{ en: "I am vegetarian.", hi: "मैं शाकाहारी हूँ।", ipa: "ai am vej-uh-tair-ee-un" }, { en: "I have a nut allergy.", hi: "मुझे मेवों से एलर्जी है।", ipa: "ai hav uh nut al-er-jee" }, { en: "Is this spicy?", hi: "क्या यह तीखा है?", ipa: "iz this spai-see" }, { en: "Can you make it mild?", hi: "क्या आप इसे कम तीखा बना सकते हैं?", ipa: "kan yoo mayk it maild" }, { en: "Does this have egg?", hi: "क्या इसमें अंडा है?", ipa: "duz this hav eg" }, { en: "No meat, please.", hi: "मांस नहीं, कृपया।", ipa: "noh meet, pleez" }],
  grammar: "“I am vegetarian” आपकी food identity या preference बताता है। “I have an allergy” स्वास्थ्य से जुड़ी महत्वपूर्ण जानकारी देता है। “Does this have...” ingredients पूछने का सरल तरीका है। रेस्तरां में allergy साफ़ और जल्दी बताना हमेशा बेहतर है।",
  practice: ["अपनी खाने की पसंद अंग्रेज़ी में बताइए।", "“I have a nut allergy” बोलने का अभ्यास कीजिए।", "किसी dish में egg है या नहीं, पूछिए।", "spicy और mild का अंतर बोलकर समझाइए।", "कल्पना कीजिए कि आप वैंकूवर में भारतीय यात्री के रूप में vegetarian खाना ढूंढ रहे हैं।"]
},
{
  day: 14,
  title: "किराने की दुकान",
  titleNative: "Grocery Shopping",
  focus: "आज आप मैनचेस्टर की grocery store में फल, पानी और basic supplies खरीदना सीखेंगे। रोज़मर्रा की छोटी खरीदारी में ये शब्द बहुत उपयोगी हैं।",
  vocab: [{ en: "grocery store", hi: "किराने की दुकान", ipa: "groh-ser-ee stor" }, { en: "fruit", hi: "फल", ipa: "froot" }, { en: "vegetables", hi: "सब्ज़ियाँ", ipa: "vej-tuh-bulz" }, { en: "bread", hi: "ब्रेड", ipa: "bred" }, { en: "water", hi: "पानी", ipa: "waw-ter" }, { en: "juice", hi: "जूस", ipa: "joos" }, { en: "rice", hi: "चावल", ipa: "rais" }, { en: "bag", hi: "बैग", ipa: "bag" }, { en: "cashier", hi: "कैशियर", ipa: "ka-sheer" }, { en: "price", hi: "कीमत", ipa: "prais" }],
  phrases: [{ en: "Where is the bread?", hi: "ब्रेड कहाँ है?", ipa: "wair iz theh bred" }, { en: "I need a bag, please.", hi: "मुझे एक बैग चाहिए, कृपया।", ipa: "ai need uh bag, pleez" }, { en: "How much are these apples?", hi: "ये सेब कितने के हैं?", ipa: "hau much ar theez ap-ulz" }, { en: "Can I pay by card?", hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?", ipa: "kan ai pay bai kard" }, { en: "Do you have rice?", hi: "क्या आपके पास चावल है?", ipa: "doo yoo hav rais" }, { en: "That is all, thank you.", hi: "बस इतना ही, धन्यवाद।", ipa: "that iz awl, thank yoo" }],
  grammar: "कई चीज़ों के लिए “these” का प्रयोग होता है, जैसे “these apples”। एक चीज़ के लिए “this” और कई चीज़ों के लिए “these” याद रखें। “Can I pay by card?” हर दुकान में काम आने वाला वाक्य है। “Do you have...” किसी चीज़ की उपलब्धता पूछने के लिए प्रयोग करें।",
  practice: ["तीन grocery items अंग्रेज़ी में बोलिए।", "“Do you have rice?” का अभ्यास कीजिए।", "कार्ड से भुगतान पूछने वाला वाक्य लिखिए।", "“this” और “these” से दो वाक्य बनाइए।", "कल्पना कीजिए कि आप मैनचेस्टर में breakfast supplies खरीद रहे हैं।"]
},
{
  day: 15,
  title: "कपड़े और खरीदारी",
  titleNative: "Clothes and Shopping",
  focus: "आज आप मियामी में clothes shopping करते समय size, color और fitting room पूछना सीखेंगे। यह पाठ बाज़ार और mall दोनों में उपयोगी है।",
  vocab: [{ en: "shirt", hi: "शर्ट", ipa: "shert" }, { en: "pants", hi: "पैंट", ipa: "pants" }, { en: "dress", hi: "ड्रेस", ipa: "dres" }, { en: "shoes", hi: "जूते", ipa: "shooz" }, { en: "size", hi: "साइज़", ipa: "saiz" }, { en: "color", hi: "रंग", ipa: "kul-er" }, { en: "blue", hi: "नीला", ipa: "bloo" }, { en: "black", hi: "काला", ipa: "blak" }, { en: "cheap", hi: "सस्ता", ipa: "cheep" }, { en: "expensive", hi: "महंगा", ipa: "ik-spen-siv" }],
  phrases: [{ en: "Do you have this in medium?", hi: "क्या यह medium size में है?", ipa: "doo yoo hav this in mee-dee-um" }, { en: "Can I try this on?", hi: "क्या मैं इसे पहनकर देख सकता हूँ?", ipa: "kan ai trai this on" }, { en: "Where is the fitting room?", hi: "fitting room कहाँ है?", ipa: "wair iz theh fit-ing room" }, { en: "I like this color.", hi: "मुझे यह रंग पसंद है।", ipa: "ai laik this kul-er" }, { en: "It is too small.", hi: "यह बहुत छोटा है।", ipa: "it iz too smawl" }, { en: "I will take it.", hi: "मैं इसे ले लूँगा।", ipa: "ai wil tayk it" }],
  grammar: "कपड़े try करने के लिए “try this on” phrase प्रयोग होता है। Size बताते समय “in medium,” “in large,” या “in small” कहा जाता है। “I will take it” खरीदने का निर्णय बताने का आसान तरीका है। “too small” या “too expensive” में “too” का मतलब “बहुत ज़्यादा” है।",
  practice: ["अपनी shirt size अंग्रेज़ी में बोलने का अभ्यास कीजिए।", "“Can I try this on?” याद कीजिए।", "किसी कपड़े का रंग पसंद बताइए।", "“too small” और “too expensive” से दो वाक्य बनाइए।", "कल्पना कीजिए कि आप मियामी के mall में shoes खरीद रहे हैं।"]
},
{
  day: 16,
  title: "पैसे और भुगतान",
  titleNative: "Money and Payment",
  focus: "आज आप न्यूयॉर्क में card, cash, receipt और change से जुड़ी practical English सीखेंगे। खरीदारी और services में भुगतान की भाषा बहुत ज़रूरी है।",
  vocab: [{ en: "money", hi: "पैसा", ipa: "mun-ee" }, { en: "cash", hi: "नकद", ipa: "kash" }, { en: "card", hi: "कार्ड", ipa: "kard" }, { en: "credit card", hi: "क्रेडिट कार्ड", ipa: "kred-it kard" }, { en: "debit card", hi: "डेबिट कार्ड", ipa: "deb-it kard" }, { en: "change", hi: "छुट्टे पैसे", ipa: "chaynj" }, { en: "receipt", hi: "रसीद", ipa: "ri-seet" }, { en: "total", hi: "कुल राशि", ipa: "toh-tul" }, { en: "tax", hi: "टैक्स", ipa: "taks" }, { en: "payment", hi: "भुगतान", ipa: "pay-munt" }],
  phrases: [{ en: "Can I pay in cash?", hi: "क्या मैं नकद भुगतान कर सकता हूँ?", ipa: "kan ai pay in kash" }, { en: "Can I pay by card?", hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?", ipa: "kan ai pay bai kard" }, { en: "What is the total?", hi: "कुल कितना हुआ?", ipa: "wot iz theh toh-tul" }, { en: "Do you need a receipt?", hi: "क्या आपको रसीद चाहिए?", ipa: "doo yoo need uh ri-seet" }, { en: "Keep the change.", hi: "छुट्टे पैसे रख लीजिए।", ipa: "keep theh chaynj" }, { en: "Is tax included?", hi: "क्या टैक्स शामिल है?", ipa: "iz taks in-kloo-did" }],
  grammar: "भुगतान के लिए “pay in cash” और “pay by card” दोनों अलग expressions हैं। “total” अंतिम राशि के लिए प्रयोग होता है। अमेरिका में price tag पर tax हमेशा शामिल नहीं होता, इसलिए कुल राशि अलग हो सकती है। “Keep the change” taxi या छोटे भुगतान में tip जैसा लग सकता है।",
  practice: ["cash और card से जुड़े दो वाक्य बोलिए।", "“What is the total?” का अभ्यास कीजिए।", "tax included है या नहीं, पूछने का वाक्य बनाइए।", "receipt मांगने वाला वाक्य लिखिए।", "कल्पना कीजिए कि आप न्यूयॉर्क में souvenir खरीद रहे हैं।"]
},
{
  day: 17,
  title: "फोन और इंटरनेट",
  titleNative: "Phone and Internet",
  focus: "आज आप डलास में SIM card, mobile data और Wi-Fi से जुड़े वाक्य सीखेंगे। यात्रा में connected रहना directions, booking और safety के लिए महत्वपूर्ण है।",
  vocab: [{ en: "phone", hi: "फ़ोन", ipa: "fohn" }, { en: "SIM card", hi: "सिम कार्ड", ipa: "sim kard" }, { en: "internet", hi: "इंटरनेट", ipa: "in-ter-net" }, { en: "data", hi: "डेटा", ipa: "day-tuh" }, { en: "charger", hi: "चार्जर", ipa: "char-jer" }, { en: "battery", hi: "बैटरी", ipa: "bat-er-ee" }, { en: "signal", hi: "सिग्नल", ipa: "sig-nul" }, { en: "password", hi: "पासवर्ड", ipa: "pas-werd" }, { en: "message", hi: "संदेश", ipa: "mes-ij" }, { en: "call", hi: "कॉल", ipa: "kawl" }],
  phrases: [{ en: "I need a SIM card.", hi: "मुझे एक SIM card चाहिए।", ipa: "ai need uh sim kard" }, { en: "Do you have mobile data plans?", hi: "क्या आपके पास mobile data plans हैं?", ipa: "doo yoo hav moh-bail day-tuh planz" }, { en: "What is the Wi-Fi password?", hi: "Wi-Fi password क्या है?", ipa: "wot iz theh wai-fai pas-werd" }, { en: "My phone battery is low.", hi: "मेरे फोन की बैटरी कम है।", ipa: "mai fohn bat-er-ee iz loh" }, { en: "Can I charge my phone here?", hi: "क्या मैं अपना फोन यहाँ charge कर सकता हूँ?", ipa: "kan ai charj mai fohn heer" }, { en: "I need to make a call.", hi: "मुझे कॉल करनी है।", ipa: "ai need too mayk uh kawl" }],
  grammar: "“I need to...” किसी काम की ज़रूरत बताने के लिए प्रयोग होता है। “I need to make a call” का अर्थ है “मुझे कॉल करनी है”। “What is the password?” café, hotel और airport में बहुत उपयोगी है। “Can I charge my phone here?” पूछना विनम्र और practical है।",
  practice: ["“I need a SIM card” बोलिए।", "Wi-Fi password पूछने का अभ्यास कीजिए।", "फोन charge करने की अनुमति मांगिए।", "“I need to...” से तीन वाक्य बनाइए।", "कल्पना कीजिए कि आप डलास में mobile shop में हैं।"]
},
{
  day: 18,
  title: "मौसम और कपड़े",
  titleNative: "Weather and Clothing",
  focus: "आज आप एडिनबर्ग में मौसम समझना और उसके अनुसार कपड़ों की ज़रूरत बताना सीखेंगे। मौसम की भाषा day trips और packing में मदद करती है।",
  vocab: [{ en: "weather", hi: "मौसम", ipa: "weth-er" }, { en: "rain", hi: "बारिश", ipa: "rayn" }, { en: "sun", hi: "धूप", ipa: "sun" }, { en: "wind", hi: "हवा", ipa: "wind" }, { en: "cold", hi: "ठंडा", ipa: "kohld" }, { en: "warm", hi: "गरम / सुहाना", ipa: "worm" }, { en: "hot", hi: "गर्म", ipa: "hot" }, { en: "jacket", hi: "जैकेट", ipa: "jak-it" }, { en: "umbrella", hi: "छाता", ipa: "um-brel-uh" }, { en: "forecast", hi: "मौसम पूर्वानुमान", ipa: "for-kast" }],
  phrases: [{ en: "What is the weather like today?", hi: "आज मौसम कैसा है?", ipa: "wot iz theh weth-er laik tuh-day" }, { en: "It is raining.", hi: "बारिश हो रही है।", ipa: "it iz ray-ning" }, { en: "It is cold outside.", hi: "बाहर ठंड है।", ipa: "it iz kohld aut-said" }, { en: "I need an umbrella.", hi: "मुझे छाता चाहिए।", ipa: "ai need an um-brel-uh" }, { en: "Should I wear a jacket?", hi: "क्या मुझे जैकेट पहननी चाहिए?", ipa: "shud ai wair uh jak-it" }, { en: "The forecast says rain.", hi: "forecast में बारिश बताई गई है।", ipa: "theh for-kast sez rayn" }],
  grammar: "मौसम बताने के लिए अंग्रेज़ी में अक्सर “It is...” का प्रयोग होता है। “It is raining” में action अभी चल रहा है। “Should I...” सलाह पूछने का अच्छा तरीका है। यात्रा में मौसम forecast देखना और स्थानीय लोगों से पूछना दोनों उपयोगी हैं।",
  practice: ["आज का मौसम अंग्रेज़ी में बताइए।", "“It is raining” और “It is cold” बोलिए।", "umbrella और jacket से दो वाक्य बनाइए।", "“Should I wear a jacket?” का अभ्यास कीजिए।", "कल्पना कीजिए कि आप एडिनबर्ग में walking tour से पहले मौसम पूछ रहे हैं।"]
},
{
  day: 19,
  title: "स्वास्थ्य और फार्मेसी",
  titleNative: "Health and Pharmacy",
  focus: "आज आप फिलाडेल्फ़िया की pharmacy में सिरदर्द, दवा और basic health needs बताना सीखेंगे। यात्रा में स्वास्थ्य से जुड़े छोटे वाक्य बहुत उपयोगी हो सकते हैं।",
  vocab: [{ en: "pharmacy", hi: "दवा की दुकान", ipa: "far-muh-see" }, { en: "medicine", hi: "दवा", ipa: "med-uh-sin" }, { en: "headache", hi: "सिरदर्द", ipa: "hed-ayk" }, { en: "fever", hi: "बुखार", ipa: "fee-ver" }, { en: "cold", hi: "जुकाम", ipa: "kohld" }, { en: "cough", hi: "खाँसी", ipa: "kawf" }, { en: "pain", hi: "दर्द", ipa: "payn" }, { en: "doctor", hi: "डॉक्टर", ipa: "dok-ter" }, { en: "hospital", hi: "अस्पताल", ipa: "hos-pit-ul" }, { en: "insurance", hi: "बीमा", ipa: "in-shoor-uns" }],
  phrases: [{ en: "I have a headache.", hi: "मुझे सिरदर्द है।", ipa: "ai hav uh hed-ayk" }, { en: "I need medicine.", hi: "मुझे दवा चाहिए।", ipa: "ai need med-uh-sin" }, { en: "Do I need a doctor?", hi: "क्या मुझे डॉक्टर की ज़रूरत है?", ipa: "doo ai need uh dok-ter" }, { en: "Where is the pharmacy?", hi: "pharmacy कहाँ है?", ipa: "wair iz theh far-muh-see" }, { en: "I have a fever.", hi: "मुझे बुखार है।", ipa: "ai hav uh fee-ver" }, { en: "Is this safe to take?", hi: "क्या इसे लेना सुरक्षित है?", ipa: "iz this sayf too tayk" }],
  grammar: "बीमारी बताने के लिए “I have...” बहुत आम है। “I have a headache” और “I have a fever” सीधे वाक्य हैं। दवा के बारे में पूछते समय “Is this safe to take?” उपयोगी है। गंभीर समस्या में हमेशा doctor या emergency service से संपर्क करें।",
  practice: ["headache, fever और cough बोलने का अभ्यास कीजिए।", "“I need medicine” याद कीजिए।", "pharmacy का रास्ता पूछने वाला वाक्य बनाइए।", "दवा सुरक्षित है या नहीं, पूछिए।", "कल्पना कीजिए कि आप फिलाडेल्फ़िया में pharmacy counter पर हैं।"]
},
{
  day: 20,
  title: "आपात स्थिति",
  titleNative: "Emergencies",
  focus: "आज आप लंदन या न्यूयॉर्क जैसी जगह में emergency help मांगने के लिए ज़रूरी अंग्रेज़ी सीखेंगे। ये वाक्य कम इस्तेमाल हों, लेकिन जानना बहुत ज़रूरी है।",
  vocab: [{ en: "emergency", hi: "आपात स्थिति", ipa: "ih-mer-jun-see" }, { en: "help", hi: "मदद", ipa: "help" }, { en: "police", hi: "पुलिस", ipa: "puh-lees" }, { en: "ambulance", hi: "एम्बुलेंस", ipa: "am-byoo-luns" }, { en: "fire", hi: "आग", ipa: "fai-er" }, { en: "lost", hi: "खोया हुआ", ipa: "lost" }, { en: "stolen", hi: "चोरी हुआ", ipa: "stoh-lun" }, { en: "danger", hi: "खतरा", ipa: "dayn-jer" }, { en: "safe", hi: "सुरक्षित", ipa: "sayf" }, { en: "address", hi: "पता", ipa: "uh-dres" }],
  phrases: [{ en: "I need help now.", hi: "मुझे अभी मदद चाहिए।", ipa: "ai need help nau" }, { en: "Please call the police.", hi: "कृपया पुलिस को बुलाइए।", ipa: "pleez kawl theh puh-lees" }, { en: "Call an ambulance.", hi: "एम्बुलेंस बुलाइए।", ipa: "kawl an am-byoo-luns" }, { en: "My bag was stolen.", hi: "मेरा बैग चोरी हो गया।", ipa: "mai bag wuz stoh-lun" }, { en: "I am lost.", hi: "मैं खो गया हूँ।", ipa: "ai am lost" }, { en: "This is my address.", hi: "यह मेरा पता है।", ipa: "this iz mai uh-dres" }],
  grammar: "Emergency में छोटे और सीधे वाक्य सबसे अच्छे होते हैं। “I need help now” urgency साफ़ दिखाता है। Passive form “was stolen” बताता है कि चीज़ चोरी हुई। अपना address लिखकर रखना यात्रा में safety के लिए उपयोगी है।",
  practice: ["“I need help now” तेज़ और साफ़ बोलिए।", "police और ambulance के लिए वाक्य बनाइए।", "“My bag was stolen” का अभ्यास कीजिए।", "अपने hotel address को अंग्रेज़ी में पढ़ने की कोशिश कीजिए।", "कल्पना कीजिए कि आप भीड़ में अपना बैग खो चुके हैं।"]
},
{
  day: 21,
  title: "स्थानीय लोगों से छोटी बातचीत",
  titleNative: "Small Talk with Locals",
  focus: "आज आप ब्रिस्बेन में locals से हल्की-फुल्की बातचीत करना सीखेंगे। small talk दोस्ताना माहौल बनाता है और संस्कृति समझने में मदद करता है।",
  vocab: [{ en: "local", hi: "स्थानीय व्यक्ति", ipa: "loh-kul" }, { en: "weather", hi: "मौसम", ipa: "weth-er" }, { en: "city", hi: "शहर", ipa: "sit-ee" }, { en: "beautiful", hi: "सुंदर", ipa: "byoo-tuh-ful" }, { en: "busy", hi: "व्यस्त", ipa: "biz-ee" }, { en: "quiet", hi: "शांत", ipa: "kwai-et" }, { en: "travel", hi: "यात्रा", ipa: "trav-ul" }, { en: "holiday", hi: "छुट्टी", ipa: "hol-uh-day" }, { en: "first time", hi: "पहली बार", ipa: "ferst taim" }, { en: "favorite", hi: "पसंदीदा", ipa: "fay-vuh-rit" }],
  phrases: [{ en: "Is this your first time here?", hi: "क्या यह आपकी यहाँ पहली बार है?", ipa: "iz this yor ferst taim heer" }, { en: "I like this city.", hi: "मुझे यह शहर पसंद है।", ipa: "ai laik this sit-ee" }, { en: "The weather is nice today.", hi: "आज मौसम अच्छा है।", ipa: "theh weth-er iz nais tuh-day" }, { en: "I am visiting from India.", hi: "मैं भारत से घूमने आया हूँ।", ipa: "ai am viz-it-ing from in-dee-uh" }, { en: "What is your favorite place here?", hi: "यहाँ आपकी पसंदीदा जगह कौन सी है?", ipa: "wot iz yor fay-vuh-rit plays heer" }, { en: "That sounds interesting.", hi: "यह दिलचस्प लगता है।", ipa: "that saundz in-truh-sting" }],
  grammar: "Small talk में weather, city और travel सुरक्षित विषय होते हैं। “I am visiting from...” बताता है कि आप कहाँ से आए हैं। “What is your favorite...” से बातचीत आगे बढ़ती है। English-speaking cultures में friendly लेकिन respectful दूरी रखना अच्छा माना जाता है।",
  practice: ["“I am visiting from India” बोलकर अभ्यास कीजिए।", "अपने शहर के बारे में एक छोटा वाक्य बनाइए।", "मौसम पर small talk का वाक्य लिखिए।", "किसी local से favorite place पूछिए।", "कल्पना कीजिए कि आप ब्रिस्बेन में park में किसी से बात कर रहे हैं।"]
},
{
  day: 22,
  title: "पर्यटन और टिकट",
  titleNative: "Sightseeing and Tickets",
  focus: "आज आप वाशिंगटन, डी.सी. में museums, tours और entry tickets से जुड़ी भाषा सीखेंगे। tourist attractions में यह vocabulary बहुत काम आती है।",
  vocab: [{ en: "museum", hi: "संग्रहालय", ipa: "myoo-zee-um" }, { en: "ticket", hi: "टिकट", ipa: "tik-it" }, { en: "tour", hi: "टूर", ipa: "tor" }, { en: "guide", hi: "गाइड", ipa: "gaid" }, { en: "entrance", hi: "प्रवेश द्वार", ipa: "en-truns" }, { en: "exit", hi: "निकास", ipa: "eg-zit" }, { en: "free", hi: "मुफ्त", ipa: "free" }, { en: "open", hi: "खुला", ipa: "oh-pun" }, { en: "closed", hi: "बंद", ipa: "klohzd" }, { en: "camera", hi: "कैमरा", ipa: "kam-er-uh" }],
  phrases: [{ en: "Is the museum open today?", hi: "क्या museum आज खुला है?", ipa: "iz theh myoo-zee-um oh-pun tuh-day" }, { en: "How much is the ticket?", hi: "टिकट कितने का है?", ipa: "hau much iz theh tik-it" }, { en: "I would like one ticket.", hi: "मुझे एक टिकट चाहिए।", ipa: "ai wud laik wun tik-it" }, { en: "Is photography allowed?", hi: "क्या photography की अनुमति है?", ipa: "iz fuh-tog-ruh-fee uh-lauwd" }, { en: "Where is the entrance?", hi: "प्रवेश द्वार कहाँ है?", ipa: "wair iz thee en-truns" }, { en: "What time does it close?", hi: "यह कितने बजे बंद होता है?", ipa: "wot taim duz it klohz" }],
  grammar: "“allowed” का मतलब है अनुमति होना। “Is photography allowed?” museums और attractions में बहुत उपयोगी है। “What time does it close?” में “does” का प्रयोग third person subject के लिए है। “open” और “closed” adjectives के रूप में भी प्रयोग होते हैं।",
  practice: ["एक museum ticket मांगने का वाक्य बनाइए।", "photography allowed है या नहीं, पूछिए।", "entrance और exit बोलकर अभ्यास कीजिए।", "closing time पूछने वाला वाक्य लिखिए।", "कल्पना कीजिए कि आप वाशिंगटन, डी.सी. में museum जा रहे हैं।"]
},
{
  day: 23,
  title: "लॉन्ड्री और रोज़मर्रा की सेवाएँ",
  titleNative: "Laundry and Daily Services",
  focus: "आज आप पोर्टलैंड में laundry, dry cleaning और everyday services से जुड़े वाक्य सीखेंगे। लंबी यात्रा में ये बातें बहुत practical होती हैं।",
  vocab: [{ en: "laundry", hi: "कपड़े धोना", ipa: "lawn-dree" }, { en: "washing machine", hi: "कपड़े धोने की मशीन", ipa: "wosh-ing muh-sheen" }, { en: "dryer", hi: "सुखाने की मशीन", ipa: "drai-er" }, { en: "detergent", hi: "डिटर्जेंट", ipa: "dih-ter-junt" }, { en: "clothes", hi: "कपड़े", ipa: "klohz" }, { en: "clean", hi: "साफ़", ipa: "kleen" }, { en: "dirty", hi: "गंदे", ipa: "der-tee" }, { en: "service", hi: "सेवा", ipa: "ser-vis" }, { en: "coin", hi: "सिक्का", ipa: "koin" }, { en: "machine", hi: "मशीन", ipa: "muh-sheen" }],
  phrases: [{ en: "Where is the laundry room?", hi: "laundry room कहाँ है?", ipa: "wair iz theh lawn-dree room" }, { en: "I need detergent.", hi: "मुझे detergent चाहिए।", ipa: "ai need dih-ter-junt" }, { en: "How much is one wash?", hi: "एक wash कितने का है?", ipa: "hau much iz wun wosh" }, { en: "The machine is not working.", hi: "मशीन काम नहीं कर रही है।", ipa: "theh muh-sheen iz not wer-king" }, { en: "Are coins required?", hi: "क्या coins चाहिए?", ipa: "ar koinz ri-kwai-erd" }, { en: "When will my clothes be ready?", hi: "मेरे कपड़े कब तैयार होंगे?", ipa: "wen wil mai klohz bee red-ee" }],
  grammar: "लंबी यात्रा में “Where is...” फिर से बहुत उपयोगी बनता है। “not working” किसी मशीन या device की समस्या बताने का आसान तरीका है। “required” का अर्थ है “ज़रूरी”। “When will...” भविष्य की जानकारी पूछने के लिए प्रयोग होता है।",
  practice: ["laundry room पूछने का वाक्य बोलिए।", "detergent खरीदने का वाक्य बनाइए।", "मशीन खराब है, यह अंग्रेज़ी में बताइए।", "“When will my clothes be ready?” का अभ्यास कीजिए।", "कल्पना कीजिए कि आप पोर्टलैंड में hotel laundry इस्तेमाल कर रहे हैं।"]
},
{
  day: 24,
  title: "योजना बनाना",
  titleNative: "Making Plans",
  focus: "आज आप सैन डिएगो में दोस्तों या fellow travelers के साथ plans बनाना सीखेंगे। समय, जगह और पसंद बताना social travel में मदद करता है।",
  vocab: [{ en: "plan", hi: "योजना", ipa: "plan" }, { en: "meet", hi: "मिलना", ipa: "meet" }, { en: "today", hi: "आज", ipa: "tuh-day" }, { en: "tomorrow", hi: "कल", ipa: "tuh-mor-oh" }, { en: "tonight", hi: "आज रात", ipa: "tuh-nait" }, { en: "place", hi: "जगह", ipa: "plays" }, { en: "restaurant", hi: "रेस्तरां", ipa: "res-tuh-ront" }, { en: "beach", hi: "समुद्र तट", ipa: "beech" }, { en: "movie", hi: "फ़िल्म", ipa: "moo-vee" }, { en: "free", hi: "खाली / उपलब्ध", ipa: "free" }],
  phrases: [{ en: "Are you free tonight?", hi: "क्या आप आज रात खाली हैं?", ipa: "ar yoo free tuh-nait" }, { en: "Let’s meet at six.", hi: "चलिए छह बजे मिलते हैं।", ipa: "lets meet at siks" }, { en: "Where should we meet?", hi: "हमें कहाँ मिलना चाहिए?", ipa: "wair shud wee meet" }, { en: "I want to go to the beach.", hi: "मैं beach जाना चाहता हूँ।", ipa: "ai want too goh too theh beech" }, { en: "That sounds good.", hi: "यह अच्छा लगता है।", ipa: "that saundz gud" }, { en: "See you there.", hi: "वहाँ मिलते हैं।", ipa: "see yoo thair" }],
  grammar: "“Let’s...” किसी को साथ में कुछ करने का सुझाव देने के लिए प्रयोग होता है। “Should we...” या “Where should we...” plan तय करने में मदद करता है। “I want to...” अपनी इच्छा बताने का सरल तरीका है। Social plans में समय और जगह दोबारा confirm करना अच्छा होता है।",
  practice: ["“Let’s meet at six” बोलिए।", "किसी से आज रात free होने के बारे में पूछिए।", "beach जाने की इच्छा अंग्रेज़ी में बताइए।", "meeting place पूछने वाला वाक्य बनाइए।", "कल्पना कीजिए कि आप सैन डिएगो में sunset देखने का plan बना रहे हैं।"]
},
{
  day: 25,
  title: "राय और पसंद",
  titleNative: "Opinions and Preferences",
  focus: "आज आप ऑस्टिन में food, music और places के बारे में अपनी पसंद और राय बताना सीखेंगे। यात्रा में opinions साझा करने से बातचीत गहरी होती है।",
  vocab: [{ en: "like", hi: "पसंद करना", ipa: "laik" }, { en: "love", hi: "बहुत पसंद करना", ipa: "luv" }, { en: "prefer", hi: "अधिक पसंद करना", ipa: "pri-fer" }, { en: "think", hi: "सोचना", ipa: "think" }, { en: "interesting", hi: "दिलचस्प", ipa: "in-truh-sting" }, { en: "boring", hi: "उबाऊ", ipa: "bor-ing" }, { en: "beautiful", hi: "सुंदर", ipa: "byoo-tuh-ful" }, { en: "fun", hi: "मज़ेदार", ipa: "fun" }, { en: "music", hi: "संगीत", ipa: "myoo-zik" }, { en: "place", hi: "जगह", ipa: "plays" }],
  phrases: [{ en: "I like this place.", hi: "मुझे यह जगह पसंद है।", ipa: "ai laik this plays" }, { en: "I love live music.", hi: "मुझे live music बहुत पसंद है।", ipa: "ai luv laiv myoo-zik" }, { en: "I prefer quiet restaurants.", hi: "मुझे शांत रेस्तरां अधिक पसंद हैं।", ipa: "ai pri-fer kwai-et res-tuh-ronts" }, { en: "I think it is interesting.", hi: "मुझे लगता है कि यह दिलचस्प है।", ipa: "ai think it iz in-truh-sting" }, { en: "This city is beautiful.", hi: "यह शहर सुंदर है।", ipa: "this sit-ee iz byoo-tuh-ful" }, { en: "It was fun.", hi: "यह मज़ेदार था।", ipa: "it wuz fun" }],
  grammar: "“I like...” और “I love...” पसंद बताने के सबसे सरल तरीके हैं। “I prefer...” दो चीज़ों में से एक को अधिक पसंद करने के लिए है। “I think...” राय देने का नरम और natural तरीका है। Past experience के लिए “It was...” का प्रयोग करें।",
  practice: ["अपनी पसंदीदा जगह के बारे में अंग्रेज़ी में बोलिए।", "“I prefer quiet restaurants” का अभ्यास कीजिए।", "live music के बारे में अपनी राय बताइए।", "“I think...” से दो वाक्य बनाइए।", "कल्पना कीजिए कि आप ऑस्टिन में music venue से बाहर निकल रहे हैं।"]
},
{
  day: 26,
  title: "समस्याएँ और शिकायतें",
  titleNative: "Problems and Complaints",
  focus: "आज आप मॉन्ट्रियल में service, food या booking से जुड़ी समस्या विनम्रता से बताना सीखेंगे। शिकायत करते समय शांत और स्पष्ट भाषा सबसे प्रभावी होती है।",
  vocab: [{ en: "problem", hi: "समस्या", ipa: "prob-lum" }, { en: "mistake", hi: "गलती", ipa: "mis-tayk" }, { en: "wrong", hi: "गलत", ipa: "rong" }, { en: "missing", hi: "गायब / नहीं मिला", ipa: "mis-ing" }, { en: "late", hi: "देर से", ipa: "layt" }, { en: "cold", hi: "ठंडा", ipa: "kohld" }, { en: "dirty", hi: "गंदा", ipa: "der-tee" }, { en: "refund", hi: "पैसा वापसी", ipa: "ree-fund" }, { en: "manager", hi: "मैनेजर", ipa: "man-uh-jer" }, { en: "receipt", hi: "रसीद", ipa: "ri-seet" }],
  phrases: [{ en: "There is a problem.", hi: "एक समस्या है।", ipa: "thair iz uh prob-lum" }, { en: "This is not what I ordered.", hi: "यह वह नहीं है जो मैंने ऑर्डर किया था।", ipa: "this iz not wot ai or-derd" }, { en: "My order is missing.", hi: "मेरा ऑर्डर नहीं मिला है।", ipa: "mai or-der iz mis-ing" }, { en: "Can I speak to the manager?", hi: "क्या मैं manager से बात कर सकता हूँ?", ipa: "kan ai speek too theh man-uh-jer" }, { en: "Can I get a refund?", hi: "क्या मुझे refund मिल सकता है?", ipa: "kan ai get uh ree-fund" }, { en: "I have the receipt.", hi: "मेरे पास रसीद है।", ipa: "ai hav theh ri-seet" }],
  grammar: "शिकायत में “There is a problem” शांत शुरुआत है। “This is not...” गलत चीज़ बताने के लिए उपयोगी है। “Can I speak to...” formal और विनम्र request है। Refund या correction मांगते समय receipt दिखाना मददगार होता है।",
  practice: ["“There is a problem” शांत आवाज़ में बोलिए।", "गलत order के लिए वाक्य बनाइए।", "manager से बात करने का वाक्य लिखिए।", "refund मांगने का अभ्यास कीजिए।", "कल्पना कीजिए कि मॉन्ट्रियल में आपका takeout order गलत है।"]
},
{
  day: 27,
  title: "बैंक और ATM",
  titleNative: "Bank and ATM",
  focus: "आज आप लास वेगास में ATM, cash withdrawal और card problems से जुड़े वाक्य सीखेंगे। यात्रा में पैसे तक सुरक्षित पहुँच बहुत ज़रूरी है।",
  vocab: [{ en: "bank", hi: "बैंक", ipa: "bank" }, { en: "ATM", hi: "एटीएम", ipa: "ay-tee-em" }, { en: "cash", hi: "नकद", ipa: "kash" }, { en: "withdraw", hi: "पैसे निकालना", ipa: "with-draw" }, { en: "deposit", hi: "जमा करना", ipa: "dih-poz-it" }, { en: "balance", hi: "शेष राशि", ipa: "bal-uns" }, { en: "fee", hi: "शुल्क", ipa: "fee" }, { en: "card", hi: "कार्ड", ipa: "kard" }, { en: "PIN", hi: "पिन", ipa: "pin" }, { en: "currency", hi: "मुद्रा", ipa: "kur-un-see" }],
  phrases: [{ en: "Where is the nearest ATM?", hi: "सबसे पास ATM कहाँ है?", ipa: "wair iz theh neer-est ay-tee-em" }, { en: "I need to withdraw cash.", hi: "मुझे cash निकालना है।", ipa: "ai need too with-draw kash" }, { en: "Is there a fee?", hi: "क्या कोई fee है?", ipa: "iz thair uh fee" }, { en: "My card is not working.", hi: "मेरा card काम नहीं कर रहा है।", ipa: "mai kard iz not wer-king" }, { en: "Can I check my balance?", hi: "क्या मैं अपना balance check कर सकता हूँ?", ipa: "kan ai chek mai bal-uns" }, { en: "I need smaller bills.", hi: "मुझे छोटे नोट चाहिए।", ipa: "ai need smaw-ler bilz" }],
  grammar: "“nearest” का मतलब है सबसे पास। “I need to withdraw cash” ATM या bank में उपयोगी है। “Is there a fee?” अतिरिक्त शुल्क पूछने के लिए प्रयोग करें। “not working” फिर से card, machine और phone problems में काम आता है।",
  practice: ["nearest ATM पूछने का वाक्य बोलिए।", "cash निकालने की ज़रूरत बताइए।", "fee के बारे में पूछिए।", "card काम नहीं कर रहा, यह अंग्रेज़ी में कहिए।", "कल्पना कीजिए कि आप लास वेगास में ATM ढूंढ रहे हैं।"]
},
{
  day: 28,
  title: "सीमा और यात्रा दस्तावेज़",
  titleNative: "Border and Travel Documents",
  focus: "आज आप कनाडा या अमेरिका की border control situation में travel documents और purpose of visit बताना सीखेंगे। स्पष्ट और ईमानदार उत्तर सबसे ज़रूरी हैं।",
  vocab: [{ en: "border", hi: "सीमा", ipa: "bor-der" }, { en: "officer", hi: "अधिकारी", ipa: "aw-fi-ser" }, { en: "passport", hi: "पासपोर्ट", ipa: "pas-port" }, { en: "visa", hi: "वीज़ा", ipa: "vee-zuh" }, { en: "purpose", hi: "उद्देश्य", ipa: "pur-pus" }, { en: "tourism", hi: "पर्यटन", ipa: "toor-iz-um" }, { en: "business", hi: "व्यापार", ipa: "biz-nis" }, { en: "address", hi: "पता", ipa: "uh-dres" }, { en: "stay", hi: "ठहरना", ipa: "stay" }, { en: "return ticket", hi: "वापसी टिकट", ipa: "ri-tern tik-it" }],
  phrases: [{ en: "Here is my passport.", hi: "यह मेरा पासपोर्ट है।", ipa: "heer iz mai pas-port" }, { en: "I am here for tourism.", hi: "मैं पर्यटन के लिए यहाँ हूँ।", ipa: "ai am heer for toor-iz-um" }, { en: "I will stay for one week.", hi: "मैं एक सप्ताह रुकूँगा।", ipa: "ai wil stay for wun week" }, { en: "This is my hotel address.", hi: "यह मेरे होटल का पता है।", ipa: "this iz mai hoh-tel uh-dres" }, { en: "I have a return ticket.", hi: "मेरे पास वापसी टिकट है।", ipa: "ai hav uh ri-tern tik-it" }, { en: "I am visiting friends.", hi: "मैं दोस्तों से मिलने आया हूँ।", ipa: "ai am viz-it-ing frendz" }],
  grammar: "Border पर future plans बताने के लिए “I will...” उपयोगी है। “I will stay for one week” अवधि साफ़ बताता है। “purpose of visit” का अर्थ है यात्रा का उद्देश्य। उत्तर छोटे, सटीक और दस्तावेज़ों से मेल खाने चाहिए।",
  practice: ["अपना यात्रा उद्देश्य अंग्रेज़ी में बोलिए।", "hotel address बताने का अभ्यास कीजिए।", "stay duration बताने वाला वाक्य बनाइए।", "return ticket के बारे में वाक्य बोलिए।", "कल्पना कीजिए कि officer आपसे पूछता है कि आप क्यों आए हैं।"]
},
{
  day: 29,
  title: "स्थानीय नियम और संस्कृति",
  titleNative: "Local Rules and Culture",
  focus: "आज आप सिंगापुर, लंदन या न्यूयॉर्क जैसे शहरों में rules, signs और cultural expectations समझना सीखेंगे। नियम समझना सुरक्षित और respectful travel का हिस्सा है।",
  vocab: [{ en: "rule", hi: "नियम", ipa: "rool" }, { en: "sign", hi: "संकेत", ipa: "sain" }, { en: "allowed", hi: "अनुमति है", ipa: "uh-lauwd" }, { en: "not allowed", hi: "अनुमति नहीं है", ipa: "not uh-lauwd" }, { en: "queue", hi: "कतार", ipa: "kyoo" }, { en: "quiet", hi: "शांत", ipa: "kwai-et" }, { en: "public", hi: "सार्वजनिक", ipa: "pub-lik" }, { en: "private", hi: "निजी", ipa: "prai-vit" }, { en: "smoking", hi: "धूम्रपान", ipa: "smoh-king" }, { en: "fine", hi: "जुर्माना", ipa: "fain" }],
  phrases: [{ en: "Is smoking allowed here?", hi: "क्या यहाँ smoking की अनुमति है?", ipa: "iz smoh-king uh-lauwd heer" }, { en: "Where should I queue?", hi: "मुझे कहाँ कतार में लगना चाहिए?", ipa: "wair shud ai kyoo" }, { en: "Is this seat taken?", hi: "क्या यह सीट ली हुई है?", ipa: "iz this seet tay-kun" }, { en: "Please be quiet.", hi: "कृपया शांत रहें।", ipa: "pleez bee kwai-et" }, { en: "What does this sign mean?", hi: "इस sign का क्या मतलब है?", ipa: "wot duz this sain meen" }, { en: "I did not know the rule.", hi: "मुझे नियम नहीं पता था।", ipa: "ai did not noh theh rool" }],
  grammar: "“allowed” और “not allowed” नियम समझने में बहुत उपयोगी हैं। “What does this sign mean?” किसी भी public place में मददगार है। “Should I...” सही व्यवहार पूछने का विनम्र तरीका है। कतार में लगना कई English-speaking देशों में महत्वपूर्ण social rule है।",
  practice: ["smoking allowed है या नहीं, पूछने का अभ्यास कीजिए।", "“What does this sign mean?” बोलिए।", "queue से जुड़ा एक वाक्य बनाइए।", "seat taken है या नहीं, पूछिए।", "कल्पना कीजिए कि आप subway में नियमों वाला sign देख रहे हैं।"]
},
{
  day: 30,
  title: "यात्रा की समीक्षा और आत्मविश्वास",
  titleNative: "Travel Review and Confidence",
  focus: "आज आप पूरे course की भाषा को जोड़कर real travel conversations के लिए confidence बनाएँगे। यह दिन airport, hotel, food, transport और social English को दोहराता है।",
  vocab: [{ en: "confident", hi: "आत्मविश्वासी", ipa: "kon-fi-dent" }, { en: "practice", hi: "अभ्यास", ipa: "prak-tis" }, { en: "remember", hi: "याद रखना", ipa: "ri-mem-ber" }, { en: "understand", hi: "समझना", ipa: "un-der-stand" }, { en: "repeat", hi: "दोहराना", ipa: "ri-peet" }, { en: "slowly", hi: "धीरे-धीरे", ipa: "sloh-lee" }, { en: "again", hi: "फिर से", ipa: "uh-gen" }, { en: "travel", hi: "यात्रा", ipa: "trav-ul" }, { en: "experience", hi: "अनुभव", ipa: "ik-speer-ee-uns" }, { en: "ready", hi: "तैयार", ipa: "red-ee" }],
  phrases: [{ en: "Can you repeat that, please?", hi: "क्या आप वह दोहरा सकते हैं?", ipa: "kan yoo ri-peet that, pleez" }, { en: "Please speak slowly.", hi: "कृपया धीरे बोलिए।", ipa: "pleez speek sloh-lee" }, { en: "I understand.", hi: "मैं समझता हूँ।", ipa: "ai un-der-stand" }, { en: "I do not understand.", hi: "मैं नहीं समझता हूँ।", ipa: "ai doo not un-der-stand" }, { en: "I am ready to travel.", hi: "मैं यात्रा के लिए तैयार हूँ।", ipa: "ai am red-ee too trav-ul" }, { en: "Thank you for your help.", hi: "आपकी मदद के लिए धन्यवाद।", ipa: "thank yoo for yor help" }],
  grammar: "जब समझ न आए, “I do not understand” कहना बिल्कुल ठीक है। “Please speak slowly” बातचीत को आसान बनाता है। “Can you repeat that?” सीखने वालों के लिए सबसे उपयोगी travel phrase में से एक है। Language confidence practice से आता है, perfect grammar से नहीं।",
  practice: ["“Please speak slowly” को स्वाभाविक तरीके से बोलिए।", "“I understand” और “I do not understand” का अभ्यास कीजिए।", "airport, hotel और café के तीन वाक्य दोहराइए।", "अपनी सबसे उपयोगी पाँच phrases लिखिए।", "कल्पना कीजिए कि आप अकेले English-speaking देश में सफलतापूर्वक घूम रहे हैं।"]
}
];

var CONVERSATIONS_HI_EN = [
{ title: "कैफ़े में कॉफ़ी ऑर्डर करना", scene: "आप सिएटल के एक व्यस्त कैफ़े में सुबह कॉफ़ी लेने आए हैं। लाइन तेज़ चल रही है, इसलिए आपको छोटा और स्पष्ट order देना है।", lines: [{ who: "them", en: "Good morning, what can I get for you?", hi: "सुप्रभात, मैं आपके लिए क्या ला सकता हूँ?" }, { who: "you", en: "Good morning, can I have a medium coffee, please?", hi: "सुप्रभात, क्या मुझे medium coffee मिल सकती है?" }, { who: "them", en: "Sure, would you like milk or sugar?", hi: "ज़रूर, क्या आपको दूध या चीनी चाहिए?" }, { who: "you", en: "Milk, please, but no sugar.", hi: "दूध चाहिए, लेकिन चीनी नहीं।" }, { who: "them", en: "Is that for here or to go?", hi: "यह यहाँ के लिए है या ले जाने के लिए?" }, { who: "you", en: "To go, please.", hi: "ले जाने के लिए, कृपया।" }, { who: "them", en: "Anything else today?", hi: "आज और कुछ?" }, { who: "you", en: "No, that is all, thank you.", hi: "नहीं, बस इतना ही, धन्यवाद।" }, { who: "them", en: "That will be four dollars.", hi: "कुल चार डॉलर होंगे।" }, { who: "you", en: "Can I pay by card?", hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?" }, { who: "them", en: "Yes, please tap your card here.", hi: "हाँ, कृपया यहाँ अपना कार्ड tap करें।" }, { who: "you", en: "Thank you very much.", hi: "आपका बहुत धन्यवाद।" }] },
{ title: "होटल में चेक-इन", scene: "आप डबलिन के होटल में शाम को पहुँचे हैं। आपके पास booking है और आप कमरे की जानकारी लेना चाहते हैं।", lines: [{ who: "them", en: "Welcome to the hotel, how can I help you?", hi: "होटल में आपका स्वागत है, मैं आपकी कैसे मदद कर सकता हूँ?" }, { who: "you", en: "Hello, I have a reservation.", hi: "नमस्ते, मेरा आरक्षण है।" }, { who: "them", en: "May I have your name, please?", hi: "कृपया आपका नाम बताइए।" }, { who: "you", en: "My name is Priya Sharma.", hi: "मेरा नाम प्रिया शर्मा है।" }, { who: "them", en: "Thank you, I found your reservation.", hi: "धन्यवाद, मुझे आपका आरक्षण मिल गया।" }, { who: "you", en: "Can I check in now?", hi: "क्या मैं अभी check-in कर सकता हूँ?" }, { who: "them", en: "Yes, your room is ready.", hi: "हाँ, आपका कमरा तैयार है।" }, { who: "you", en: "What time is breakfast?", hi: "नाश्ता कितने बजे है?" }, { who: "them", en: "Breakfast is from seven to ten.", hi: "नाश्ता सात से दस बजे तक है।" }, { who: "you", en: "Where is the elevator?", hi: "लिफ्ट कहाँ है?" }, { who: "them", en: "It is on your left.", hi: "यह आपके बाईं ओर है।" }, { who: "you", en: "Thank you for your help.", hi: "आपकी मदद के लिए धन्यवाद।" }] },
{ title: "रास्ता पूछना", scene: "आप शिकागो में एक museum ढूंढ रहे हैं। आपके फोन का signal कमजोर है, इसलिए आप एक local से directions पूछते हैं।", lines: [{ who: "you", en: "Excuse me, can you help me?", hi: "क्षमा कीजिए, क्या आप मेरी मदद कर सकते हैं?" }, { who: "them", en: "Sure, what do you need?", hi: "ज़रूर, आपको क्या चाहिए?" }, { who: "you", en: "Where is the art museum?", hi: "art museum कहाँ है?" }, { who: "them", en: "Go straight for two blocks.", hi: "दो blocks तक सीधे जाइए।" }, { who: "you", en: "Okay, then what?", hi: "ठीक है, फिर क्या?" }, { who: "them", en: "Turn left at the corner.", hi: "कोने पर बाएँ मुड़िए।" }, { who: "you", en: "Is it near here?", hi: "क्या यह यहाँ पास है?" }, { who: "them", en: "Yes, it is about five minutes away.", hi: "हाँ, यह लगभग पाँच मिनट दूर है।" }, { who: "you", en: "Can you show me on the map?", hi: "क्या आप मुझे नक्शे पर दिखा सकते हैं?" }, { who: "them", en: "Yes, it is right here.", hi: "हाँ, यह यहीं है।" }, { who: "you", en: "Thank you very much.", hi: "आपका बहुत धन्यवाद।" }, { who: "them", en: "You are welcome.", hi: "आपका स्वागत है।" }] },
{ title: "रेस्तरां में डिनर", scene: "आप मेलबर्न के एक रेस्तरां में dinner के लिए बैठे हैं। आप vegetarian option, पानी और bill के बारे में पूछते हैं।", lines: [{ who: "them", en: "Hello, are you ready to order?", hi: "नमस्ते, क्या आप order करने के लिए तैयार हैं?" }, { who: "you", en: "Yes, what do you recommend?", hi: "हाँ, आप क्या सुझाते हैं?" }, { who: "them", en: "The pasta is very popular.", hi: "pasta बहुत लोकप्रिय है।" }, { who: "you", en: "Is it vegetarian?", hi: "क्या यह vegetarian है?" }, { who: "them", en: "Yes, it is vegetarian.", hi: "हाँ, यह vegetarian है।" }, { who: "you", en: "Great, I would like the pasta.", hi: "अच्छा, मुझे pasta चाहिए।" }, { who: "them", en: "Would you like something to drink?", hi: "क्या आप कुछ पीना चाहेंगे?" }, { who: "you", en: "Water, please.", hi: "पानी, कृपया।" }, { who: "them", en: "Of course, I will bring it now.", hi: "ज़रूर, मैं अभी लाता हूँ।" }, { who: "you", en: "Thank you.", hi: "धन्यवाद।" }, { who: "you", en: "Can I have the bill, please?", hi: "क्या मुझे bill मिल सकता है?" }, { who: "them", en: "Certainly, I will bring it.", hi: "बिल्कुल, मैं लाता हूँ।" }] },
{ title: "ट्रेन टिकट खरीदना", scene: "आप बोस्टन में subway station पर downtown जाने के लिए ticket खरीद रहे हैं। आपको सही line और stops की जानकारी चाहिए।", lines: [{ who: "them", en: "Hi, how can I help you?", hi: "हाय, मैं आपकी कैसे मदद कर सकता हूँ?" }, { who: "you", en: "I need a subway ticket, please.", hi: "मुझे subway ticket चाहिए।" }, { who: "them", en: "Where are you going?", hi: "आप कहाँ जा रहे हैं?" }, { who: "you", en: "I am going downtown.", hi: "मैं downtown जा रहा हूँ।" }, { who: "them", en: "Take the blue line.", hi: "blue line लीजिए।" }, { who: "you", en: "How many stops is it?", hi: "यह कितने stops दूर है?" }, { who: "them", en: "It is four stops from here.", hi: "यह यहाँ से चार stops दूर है।" }, { who: "you", en: "I want a return ticket.", hi: "मुझे return ticket चाहिए।" }, { who: "them", en: "That will be six dollars.", hi: "कुल छह डॉलर होंगे।" }, { who: "you", en: "Can I pay by card?", hi: "क्या मैं card से भुगतान कर सकता हूँ?" }, { who: "them", en: "Yes, use the machine on the right.", hi: "हाँ, दाईं ओर वाली machine इस्तेमाल कीजिए।" }, { who: "you", en: "Thank you.", hi: "धन्यवाद।" }] },
{ title: "कपड़ों की दुकान में", scene: "आप मियामी के mall में shirt खरीद रहे हैं। आपको size देखना है और fitting room पूछना है।", lines: [{ who: "them", en: "Hello, can I help you find anything?", hi: "नमस्ते, क्या मैं आपको कुछ ढूंढने में मदद कर सकता हूँ?" }, { who: "you", en: "Yes, do you have this shirt in medium?", hi: "हाँ, क्या यह shirt medium size में है?" }, { who: "them", en: "Let me check for you.", hi: "मैं आपके लिए check करता हूँ।" }, { who: "you", en: "Thank you.", hi: "धन्यवाद।" }, { who: "them", en: "Yes, we have it in medium and large.", hi: "हाँ, हमारे पास medium और large में है।" }, { who: "you", en: "Can I try this on?", hi: "क्या मैं इसे पहनकर देख सकता हूँ?" }, { who: "them", en: "Of course, the fitting room is over there.", hi: "ज़रूर, fitting room वहाँ है।" }, { who: "you", en: "I like this color.", hi: "मुझे यह रंग पसंद है।" }, { who: "them", en: "It looks good.", hi: "यह अच्छा लग रहा है।" }, { who: "you", en: "I will take it.", hi: "मैं इसे ले लूँगा।" }, { who: "them", en: "Great, you can pay at the cashier.", hi: "बढ़िया, आप cashier पर भुगतान कर सकते हैं।" }, { who: "you", en: "Thanks for your help.", hi: "आपकी मदद के लिए धन्यवाद।" }] },
{ title: "फार्मेसी में दवा लेना", scene: "आप फिलाडेल्फ़िया में यात्रा के दौरान सिरदर्द महसूस कर रहे हैं। आप pharmacy में जाकर सुरक्षित दवा के बारे में पूछते हैं।", lines: [{ who: "them", en: "Hello, how can I help you?", hi: "नमस्ते, मैं आपकी कैसे मदद कर सकता हूँ?" }, { who: "you", en: "I have a headache.", hi: "मुझे सिरदर्द है।" }, { who: "them", en: "I am sorry to hear that.", hi: "यह सुनकर दुख हुआ।" }, { who: "you", en: "I need medicine, please.", hi: "मुझे दवा चाहिए, कृपया।" }, { who: "them", en: "Do you have any allergies?", hi: "क्या आपको कोई allergy है?" }, { who: "you", en: "No, I do not have allergies.", hi: "नहीं, मुझे allergy नहीं है।" }, { who: "them", en: "You can take this with water.", hi: "आप इसे पानी के साथ ले सकते हैं।" }, { who: "you", en: "Is this safe to take?", hi: "क्या इसे लेना सुरक्षित है?" }, { who: "them", en: "Yes, follow the instructions on the box.", hi: "हाँ, box पर दिए instructions follow करें।" }, { who: "you", en: "How much is it?", hi: "यह कितने का है?" }, { who: "them", en: "It is eight dollars.", hi: "यह आठ डॉलर का है।" }, { who: "you", en: "Thank you for your help.", hi: "आपकी मदद के लिए धन्यवाद।" }] },
{ title: "स्थानीय व्यक्ति से छोटी बातचीत", scene: "आप ब्रिस्बेन के एक park में बैठे हैं और पास बैठे local से हल्की बातचीत शुरू करते हैं। बातचीत मौसम, शहर और travel पर केंद्रित है।", lines: [{ who: "you", en: "Hi, is this seat taken?", hi: "हाय, क्या यह सीट ली हुई है?" }, { who: "them", en: "No, you can sit here.", hi: "नहीं, आप यहाँ बैठ सकते हैं।" }, { who: "you", en: "Thank you, the weather is nice today.", hi: "धन्यवाद, आज मौसम अच्छा है।" }, { who: "them", en: "Yes, it is a beautiful day.", hi: "हाँ, आज बहुत सुंदर दिन है।" }, { who: "you", en: "I am visiting from India.", hi: "मैं भारत से घूमने आया हूँ।" }, { who: "them", en: "Is this your first time here?", hi: "क्या यह आपकी यहाँ पहली बार है?" }, { who: "you", en: "Yes, it is my first time in Brisbane.", hi: "हाँ, यह मेरी Brisbane में पहली बार है।" }, { who: "them", en: "I hope you like the city.", hi: "आशा है आपको शहर पसंद आएगा।" }, { who: "you", en: "I like it very much.", hi: "मुझे यह बहुत पसंद है।" }, { who: "them", en: "What places have you visited?", hi: "आपने कौन-कौन सी जगहें देखी हैं?" }, { who: "you", en: "I visited the river and the museum.", hi: "मैंने river और museum देखा।" }, { who: "them", en: "That sounds great.", hi: "यह बहुत अच्छा लगता है।" }] }
];
