var COURSE_PT_NL = [
{
  day: 1,
  title: "Cumprimentos e primeiras palavras",
  titleNative: "Begroetingen en eerste woorden",
  focus: "Hoje você aprende a cumprimentar pessoas em Amsterdã, Roterdã ou Utrecht de forma simples e educada. Estas palavras ajudam em hotéis, cafés, lojas e qualquer primeira interação.",
  vocab: [{ nl: "hallo", pt: "olá", ipa: "rá-lo" }, { nl: "goedemorgen", pt: "bom dia", ipa: "rú-du-mór-run" }, { nl: "goedemiddag", pt: "boa tarde", ipa: "rú-du-mí-dákh" }, { nl: "goedenavond", pt: "boa noite", ipa: "rú-du-ná-font" }, { nl: "dag", pt: "oi / tchau", ipa: "dákh" }, { nl: "doei", pt: "tchau", ipa: "dúi" }, { nl: "ja", pt: "sim", ipa: "iá" }, { nl: "nee", pt: "não", ipa: "nêi" }, { nl: "alsjeblieft", pt: "por favor / aqui está", ipa: "ál-shu-blíft" }, { nl: "dank je", pt: "obrigado", ipa: "dánk yu" }],
  phrases: [{ nl: "Hallo, hoe gaat het?", pt: "Olá, como vai?", ipa: "rá-lo, rú ráat rut" }, { nl: "Goedemorgen, meneer.", pt: "Bom dia, senhor.", ipa: "rú-du-mór-run, mu-nêr" }, { nl: "Goedemiddag, mevrouw.", pt: "Boa tarde, senhora.", ipa: "rú-du-mí-dákh, mu-fráu" }, { nl: "Dank je wel.", pt: "Muito obrigado.", ipa: "dánk yu vel" }, { nl: "Tot ziens.", pt: "Até logo.", ipa: "tot zíns" }, { nl: "Ja, graag.", pt: "Sim, por favor.", ipa: "iá, rráakh" }],
  grammar: "Em neerlandês, muitas saudações são curtas e diretas, o que combina com o estilo prático dos Países Baixos. “Goedemorgen”, “goedemiddag” e “goedenavond” mudam conforme a hora do dia. “Dank je” é informal, enquanto “dank u” é mais formal. Para turistas, “dank je wel” funciona bem na maioria das situações.",
  practice: ["Cumprimente um funcionário de hotel pela manhã usando neerlandês.", "Diga “boa tarde” para uma pessoa desconhecida.", "Responda “sim, por favor” como se estivesse aceitando café.", "Diga “muito obrigado” depois de receber ajuda.", "Pratique uma despedida curta ao sair de uma loja."]
},
{
  day: 2,
  title: "Apresentar-se",
  titleNative: "Jezelf voorstellen",
  focus: "Hoje você aprende a dizer quem é, de onde vem e que está visitando os Países Baixos. Isso é útil em hostels, passeios guiados e conversas informais.",
  vocab: [{ nl: "ik", pt: "eu", ipa: "ik" }, { nl: "jij", pt: "você", ipa: "yêi" }, { nl: "u", pt: "o senhor / a senhora", ipa: "ü" }, { nl: "ben", pt: "sou / estou", ipa: "ben" }, { nl: "heet", pt: "chamo-me", ipa: "reit" }, { nl: "naam", pt: "nome", ipa: "nám" }, { nl: "Portugal", pt: "Portugal", ipa: "pór-tu-rál" }, { nl: "Brazilië", pt: "Brasil", ipa: "bra-zí-li-u" }, { nl: "toerist", pt: "turista", ipa: "tu-ríst" }, { nl: "vriend", pt: "amigo", ipa: "frínt" }],
  phrases: [{ nl: "Ik ben Ana.", pt: "Eu sou Ana.", ipa: "ik ben á-na" }, { nl: "Ik heet João.", pt: "Eu me chamo João.", ipa: "ik reit zjo-ão" }, { nl: "Mijn naam is Maria.", pt: "Meu nome é Maria.", ipa: "mein nám is ma-rí-a" }, { nl: "Ik kom uit Portugal.", pt: "Eu venho de Portugal.", ipa: "ik kom aut pór-tu-rál" }, { nl: "Ik kom uit Brazilië.", pt: "Eu venho do Brasil.", ipa: "ik kom aut bra-zí-li-u" }, { nl: "Ik ben toerist.", pt: "Eu sou turista.", ipa: "ik ben tu-ríst" }],
  grammar: "Para dizer seu nome, você pode usar “Ik ben...” ou “Ik heet...”. “Ik ben” é parecido com “eu sou”, enquanto “Ik heet” significa literalmente “eu me chamo”. Para dizer origem, use “Ik kom uit...” seguido do país ou cidade. Em situações formais, use “u” em vez de “jij”.",
  practice: ["Apresente-se com “Ik ben...” usando seu próprio nome.", "Diga que você vem de Portugal ou do Brasil.", "Pergunte mentalmente como você diria “Meu nome é...”.", "Imagine uma conversa em um hostel e diga que é turista.", "Repita “Ik kom uit...” com três nomes de lugares."]
},
{
  day: 3,
  title: "Perguntas essenciais",
  titleNative: "Essentiële vragen",
  focus: "Hoje você aprende perguntas simples para sobreviver em situações de viagem. Em cidades como Amsterdã e Haia, perguntas curtas ajudam muito quando você precisa de informação rápida.",
  vocab: [{ nl: "wie", pt: "quem", ipa: "ví" }, { nl: "wat", pt: "o quê", ipa: "vát" }, { nl: "waar", pt: "onde", ipa: "vár" }, { nl: "wanneer", pt: "quando", ipa: "va-nêr" }, { nl: "waarom", pt: "por quê", ipa: "vá-rom" }, { nl: "hoe", pt: "como", ipa: "rú" }, { nl: "hoeveel", pt: "quanto", ipa: "rú-fêl" }, { nl: "welke", pt: "qual", ipa: "vél-ku" }, { nl: "dit", pt: "isto", ipa: "dit" }, { nl: "dat", pt: "aquilo", ipa: "dát" }],
  phrases: [{ nl: "Waar is het station?", pt: "Onde fica a estação?", ipa: "vár is rut stá-tsion" }, { nl: "Wat is dit?", pt: "O que é isto?", ipa: "vát is dit" }, { nl: "Hoeveel kost het?", pt: "Quanto custa?", ipa: "rú-fêl kost rut" }, { nl: "Wanneer vertrekt de trein?", pt: "Quando o trem parte?", ipa: "va-nêr fer-trékt du trein" }, { nl: "Welke tram gaat naar het centrum?", pt: "Qual bonde vai para o centro?", ipa: "vél-ku tram ráat nár rut sén-trum" }, { nl: "Hoe zeg je dat?", pt: "Como se diz isso?", ipa: "rú zek yu dát" }],
  grammar: "As palavras de pergunta geralmente vêm no início da frase. Depois delas, o verbo costuma aparecer logo em seguida: “Waar is...”, “Wat kost...”, “Hoe zeg...”. Essa ordem pode parecer diferente do português, mas é muito comum em frases curtas. Para viajar, memorizar blocos prontos é mais importante do que analisar cada palavra.",
  practice: ["Pergunte onde fica a estação.", "Pergunte quanto custa um bilhete.", "Pergunte como se diz uma palavra em neerlandês.", "Crie uma pergunta com “waar”.", "Crie uma pergunta com “hoeveel”."]
},
{
  day: 4,
  title: "Números de 0 a 20",
  titleNative: "Cijfers van 0 tot 20",
  focus: "Hoje você aprende números básicos para preços, horários, quartos de hotel e bilhetes. Eles aparecem o tempo todo em mercados, estações e cafés neerlandeses.",
  vocab: [{ nl: "nul", pt: "zero", ipa: "nul" }, { nl: "één", pt: "um", ipa: "ein" }, { nl: "twee", pt: "dois", ipa: "tvei" }, { nl: "drie", pt: "três", ipa: "drí" }, { nl: "vier", pt: "quatro", ipa: "fíer" }, { nl: "vijf", pt: "cinco", ipa: "veif" }, { nl: "zes", pt: "seis", ipa: "zes" }, { nl: "zeven", pt: "sete", ipa: "zêi-fun" }, { nl: "acht", pt: "oito", ipa: "ákh-t" }, { nl: "negen", pt: "nove", ipa: "nêi-run" }],
  phrases: [{ nl: "Ik wil twee kaartjes.", pt: "Quero dois bilhetes.", ipa: "ik vil tvei kár-chus" }, { nl: "Kamer drie, alstublieft.", pt: "Quarto três, por favor.", ipa: "ká-mer drí, ál-stü-blíft" }, { nl: "Het kost vijf euro.", pt: "Custa cinco euros.", ipa: "rut kost veif ôi-ro" }, { nl: "Ik heb één tas.", pt: "Tenho uma bolsa.", ipa: "ik rep ein tas" }, { nl: "Zes personen, graag.", pt: "Seis pessoas, por favor.", ipa: "zes per-sô-nun, rráakh" }, { nl: "Nummer acht.", pt: "Número oito.", ipa: "nú-mer ákh-t" }],
  grammar: "Os números em neerlandês são essenciais para entender preços e instruções. “Één” significa “um”, mas em conversas rápidas pode soar como “ein”. Para pedir quantidade, use “Ik wil...” seguido do número e do item. Em contextos de serviço, adicionar “graag” deixa o pedido mais natural.",
  practice: ["Conte de zero a dez em voz alta.", "Peça dois bilhetes usando “Ik wil...”.", "Diga o número do seu quarto imaginário.", "Pratique preços simples: cinco euros, oito euros, nove euros.", "Escute mentalmente a diferença entre “twee” e “drie”."]
},
{
  day: 5,
  title: "Números maiores, dinheiro e preços",
  titleNative: "Grotere cijfers, geld en prijzen",
  focus: "Hoje você aprende números úteis para compras, contas e transporte. Isso ajuda em supermercados, bilheterias e restaurantes nos Países Baixos.",
  vocab: [{ nl: "tien", pt: "dez", ipa: "tin" }, { nl: "elf", pt: "onze", ipa: "elf" }, { nl: "twaalf", pt: "doze", ipa: "tválf" }, { nl: "dertien", pt: "treze", ipa: "dér-tin" }, { nl: "twintig", pt: "vinte", ipa: "tvín-tukh" }, { nl: "dertig", pt: "trinta", ipa: "dér-tukh" }, { nl: "veertig", pt: "quarenta", ipa: "fêr-tukh" }, { nl: "vijftig", pt: "cinquenta", ipa: "veif-tukh" }, { nl: "euro", pt: "euro", ipa: "ôi-ro" }, { nl: "cent", pt: "centavo", ipa: "sent" }],
  phrases: [{ nl: "Het kost tien euro.", pt: "Custa dez euros.", ipa: "rut kost tin ôi-ro" }, { nl: "Is dat alles?", pt: "É só isso?", ipa: "is dát ál-lus" }, { nl: "Dat is te duur.", pt: "Isso é caro demais.", ipa: "dát is tu dür" }, { nl: "Heeft u wisselgeld?", pt: "O senhor tem troco?", ipa: "reift ü ví-sul-relt" }, { nl: "Kan ik met kaart betalen?", pt: "Posso pagar com cartão?", ipa: "kan ik met kárt bu-tá-lun" }, { nl: "Ik betaal contant.", pt: "Eu pago em dinheiro.", ipa: "ik bu-tál kon-tánt" }],
  grammar: "Nos Países Baixos, pagamentos com cartão são extremamente comuns, então “Kan ik met kaart betalen?” é uma frase muito útil. “Te duur” significa “caro demais”, enquanto “goedkoop” significa barato. O verbo “betalen” significa pagar. Para soar educado, use “Heeft u...” quando falar com atendentes.",
  practice: ["Diga que algo custa dez euros.", "Pergunte se pode pagar com cartão.", "Diga que vai pagar em dinheiro.", "Pratique os números vinte, trinta, quarenta e cinquenta.", "Imagine uma loja e pergunte se há troco."]
},
{
  day: 6,
  title: "Frases de sobrevivência",
  titleNative: "Overlevingszinnen",
  focus: "Hoje você aprende frases para pedir ajuda, repetir informações e lidar com confusão. São frases essenciais para um viajante lusófono em qualquer cidade neerlandesa.",
  vocab: [{ nl: "help", pt: "ajuda", ipa: "relp" }, { nl: "langzaam", pt: "devagar", ipa: "láng-zám" }, { nl: "nogmaals", pt: "novamente", ipa: "nokh-máls" }, { nl: "begrijp", pt: "entendo", ipa: "bu-rrêip" }, { nl: "spreek", pt: "falo", ipa: "spreik" }, { nl: "Nederlands", pt: "neerlandês", ipa: "nêi-der-lants" }, { nl: "Engels", pt: "inglês", ipa: "én-ruls" }, { nl: "sorry", pt: "desculpa", ipa: "só-ri" }, { nl: "probleem", pt: "problema", ipa: "pro-blêm" }, { nl: "alstublieft", pt: "por favor", ipa: "ál-stü-blíft" }],
  phrases: [{ nl: "Kunt u mij helpen?", pt: "O senhor pode me ajudar?", ipa: "kunt ü mei rél-pun" }, { nl: "Ik begrijp het niet.", pt: "Eu não entendo.", ipa: "ik bu-rrêip rut nit" }, { nl: "Spreekt u Engels?", pt: "O senhor fala inglês?", ipa: "spreikt ü én-ruls" }, { nl: "Kunt u dat herhalen?", pt: "Pode repetir isso?", ipa: "kunt ü dát rer-rá-lun" }, { nl: "Langzaam, alstublieft.", pt: "Devagar, por favor.", ipa: "láng-zám, ál-stü-blíft" }, { nl: "Geen probleem.", pt: "Sem problema.", ipa: "rein pro-blêm" }],
  grammar: "A palavra “niet” é usada para negar verbos e frases: “Ik begrijp het niet” significa “eu não entendo”. “Geen” também nega, mas costuma aparecer antes de substantivos, como em “geen probleem”. Em viagem, você pode usar “Kunt u...” para pedir algo com educação. É uma estrutura formal e segura.",
  practice: ["Diga que não entende.", "Peça para alguém falar devagar.", "Pergunte se a pessoa fala inglês.", "Peça ajuda de maneira educada.", "Responda “sem problema” em neerlandês."]
},
{
  day: 7,
  title: "Direções básicas na cidade",
  titleNative: "Basisrichtingen in de stad",
  focus: "Hoje você aprende a se orientar em cidades planas e cheias de canais, como Amsterdã, Leiden e Delft. Saber pedir direções ajuda quando o celular falha ou a bateria acaba.",
  vocab: [{ nl: "links", pt: "esquerda", ipa: "links" }, { nl: "rechts", pt: "direita", ipa: "rekhts" }, { nl: "rechtdoor", pt: "em frente", ipa: "rekht-dôr" }, { nl: "straat", pt: "rua", ipa: "strát" }, { nl: "plein", pt: "praça", ipa: "plein" }, { nl: "brug", pt: "ponte", ipa: "brukh" }, { nl: "kanaal", pt: "canal", ipa: "ka-nál" }, { nl: "centrum", pt: "centro", ipa: "sén-trum" }, { nl: "dichtbij", pt: "perto", ipa: "dikht-bêi" }, { nl: "ver weg", pt: "longe", ipa: "fer vékh" }],
  phrases: [{ nl: "Waar is het centrum?", pt: "Onde fica o centro?", ipa: "vár is rut sén-trum" }, { nl: "Ga rechtdoor.", pt: "Vá em frente.", ipa: "rá rekht-dôr" }, { nl: "Sla linksaf.", pt: "Vire à esquerda.", ipa: "slá links-af" }, { nl: "Sla rechtsaf.", pt: "Vire à direita.", ipa: "slá rekhts-af" }, { nl: "Is het dichtbij?", pt: "É perto?", ipa: "is rut dikht-bêi" }, { nl: "Het is over de brug.", pt: "É depois da ponte.", ipa: "rut is ô-ver du brukh" }],
  grammar: "Para dar direções, o neerlandês usa muitos verbos curtos: “ga” significa vá, “sla” significa vire. “Linksaf” e “rechtsaf” combinam esquerda/direita com a ideia de virar. “Over de brug” significa “sobre/depois da ponte”, algo muito útil em cidades com canais. Em caso de dúvida, repita a direção que ouviu para confirmar.",
  practice: ["Pergunte onde fica o centro.", "Diga “vá em frente” em neerlandês.", "Diga “vire à esquerda”.", "Pergunte se um lugar é perto.", "Imagine atravessar uma ponte e diga onde fica o destino."]
},
{
  day: 8,
  title: "Transporte público",
  titleNative: "Openbaar vervoer",
  focus: "Hoje você aprende vocabulário de trem, bonde, metrô e ônibus. Isso é essencial para viajar entre Amsterdã, Roterdã, Haia, Utrecht e outras cidades.",
  vocab: [{ nl: "trein", pt: "trem", ipa: "trein" }, { nl: "tram", pt: "bonde", ipa: "tram" }, { nl: "metro", pt: "metrô", ipa: "mê-tro" }, { nl: "bus", pt: "ônibus", ipa: "bus" }, { nl: "station", pt: "estação", ipa: "stá-tsion" }, { nl: "halte", pt: "parada", ipa: "rál-tu" }, { nl: "kaartje", pt: "bilhete", ipa: "kár-chu" }, { nl: "perron", pt: "plataforma", ipa: "pe-rón" }, { nl: "vertrek", pt: "partida", ipa: "fer-trek" }, { nl: "aankomst", pt: "chegada", ipa: "án-komst" }],
  phrases: [{ nl: "Ik wil een kaartje naar Utrecht.", pt: "Quero um bilhete para Utrecht.", ipa: "ik vil un kár-chu nár ü-trekht" }, { nl: "Waar is perron twee?", pt: "Onde fica a plataforma dois?", ipa: "vár is pe-rón tvei" }, { nl: "Wanneer vertrekt de trein?", pt: "Quando o trem parte?", ipa: "va-nêr fer-trékt du trein" }, { nl: "Welke halte is dit?", pt: "Que parada é esta?", ipa: "vél-ku rál-tu is dit" }, { nl: "Gaat deze bus naar het centrum?", pt: "Este ônibus vai para o centro?", ipa: "ráat dêi-zu bus nár rut sén-trum" }, { nl: "Ik moet overstappen.", pt: "Preciso fazer baldeação.", ipa: "ik mut ô-ver-stá-pun" }],
  grammar: "Em neerlandês, “naar” indica direção: “naar Utrecht”, “naar het centrum”. A pergunta “Gaat deze bus naar...?” é muito útil porque serve para ônibus, bonde, metrô e trem. “Moet” significa “preciso/devo”. Para conexões, “overstappen” é o verbo-chave.",
  practice: ["Peça um bilhete para Utrecht.", "Pergunte onde fica a plataforma dois.", "Pergunte se o ônibus vai ao centro.", "Diga que precisa fazer baldeação.", "Pratique “trein”, “tram”, “metro” e “bus”."]
},
{
  day: 9,
  title: "Chegada ao hotel",
  titleNative: "Aankomst in het hotel",
  focus: "Hoje você aprende frases para check-in, quarto, reserva e documentos. Essas expressões funcionam em hotéis, hostels e apartamentos turísticos nos Países Baixos.",
  vocab: [{ nl: "hotel", pt: "hotel", ipa: "ro-tel" }, { nl: "reservering", pt: "reserva", ipa: "rê-zer-fê-ring" }, { nl: "kamer", pt: "quarto", ipa: "ká-mer" }, { nl: "sleutel", pt: "chave", ipa: "slôi-tul" }, { nl: "paspoort", pt: "passaporte", ipa: "pás-port" }, { nl: "nacht", pt: "noite", ipa: "nakht" }, { nl: "ontbijt", pt: "café da manhã", ipa: "ont-bêit" }, { nl: "lift", pt: "elevador", ipa: "lift" }, { nl: "bagage", pt: "bagagem", ipa: "ba-rá-zhu" }, { nl: "receptie", pt: "recepção", ipa: "rê-sep-tsi" }],
  phrases: [{ nl: "Ik heb een reservering.", pt: "Tenho uma reserva.", ipa: "ik rep un rê-zer-fê-ring" }, { nl: "Mijn naam is Silva.", pt: "Meu nome é Silva.", ipa: "mein nám is síl-va" }, { nl: "Kan ik inchecken?", pt: "Posso fazer check-in?", ipa: "kan ik in-tché-kun" }, { nl: "Is ontbijt inbegrepen?", pt: "O café da manhã está incluído?", ipa: "is ont-bêit in-bu-rrê-pun" }, { nl: "Waar is de lift?", pt: "Onde fica o elevador?", ipa: "vár is du lift" }, { nl: "Kan ik mijn bagage hier laten?", pt: "Posso deixar minha bagagem aqui?", ipa: "kan ik mein ba-rá-zhu rir lá-tun" }],
  grammar: "“Mijn” significa “meu/minha” e é muito útil para nomes, documentos e bagagem. “Ik heb...” significa “eu tenho” e aparece em “Ik heb een reservering”. Em hotéis, usar “kan ik...” para pedir permissão é natural e educado. “Inbegrepen” significa incluído, muito útil para café da manhã, impostos e serviços.",
  practice: ["Diga que tem uma reserva.", "Pergunte se pode fazer check-in.", "Pergunte se o café da manhã está incluído.", "Peça para deixar a bagagem na recepção.", "Pergunte onde fica o elevador."]
},
{
  day: 10,
  title: "No quarto e problemas simples",
  titleNative: "In de kamer en eenvoudige problemen",
  focus: "Hoje você aprende a explicar pequenos problemas no hotel. Isso ajuda quando há algo errado com a chave, o chuveiro, a internet ou o aquecimento.",
  vocab: [{ nl: "bed", pt: "cama", ipa: "bet" }, { nl: "deur", pt: "porta", ipa: "dör" }, { nl: "raam", pt: "janela", ipa: "rám" }, { nl: "douche", pt: "chuveiro", ipa: "dú-shu" }, { nl: "toilet", pt: "banheiro / vaso", ipa: "tua-lét" }, { nl: "wifi", pt: "wi-fi", ipa: "vái-fái" }, { nl: "verwarming", pt: "aquecimento", ipa: "fer-vár-ming" }, { nl: "airco", pt: "ar-condicionado", ipa: "ér-ko" }, { nl: "kapot", pt: "quebrado", ipa: "ka-pot" }, { nl: "schoon", pt: "limpo", ipa: "skhôn" }],
  phrases: [{ nl: "De sleutel werkt niet.", pt: "A chave não funciona.", ipa: "du slôi-tul werkt nit" }, { nl: "De wifi werkt niet.", pt: "O wi-fi não funciona.", ipa: "du vái-fái werkt nit" }, { nl: "De douche is kapot.", pt: "O chuveiro está quebrado.", ipa: "du dú-shu is ka-pot" }, { nl: "De kamer is niet schoon.", pt: "O quarto não está limpo.", ipa: "du ká-mer is nit skhôn" }, { nl: "Kunt u iemand sturen?", pt: "Pode mandar alguém?", ipa: "kunt ü í-mant stü-run" }, { nl: "Ik heb een probleem met de kamer.", pt: "Tenho um problema com o quarto.", ipa: "ik rep un pro-blêm met du ká-mer" }],
  grammar: "Para dizer que algo não funciona, use “werkt niet”. É uma estrutura muito prática: “De wifi werkt niet”, “De sleutel werkt niet”. Para dizer que algo está quebrado, use “is kapot”. Em serviços, “Kunt u iemand sturen?” é uma forma educada de pedir assistência.",
  practice: ["Diga que o wi-fi não funciona.", "Diga que a chave não funciona.", "Explique que o quarto não está limpo.", "Peça para enviarem alguém.", "Crie uma frase com “kapot”."]
},
{
  day: 11,
  title: "Café e bebidas",
  titleNative: "Café en drankjes",
  focus: "Hoje você aprende a pedir café, chá e bebidas em cafés neerlandeses. É uma habilidade essencial para manhãs em Amsterdã, Utrecht ou Groningen.",
  vocab: [{ nl: "koffie", pt: "café", ipa: "kó-fi" }, { nl: "thee", pt: "chá", ipa: "têi" }, { nl: "water", pt: "água", ipa: "vá-ter" }, { nl: "melk", pt: "leite", ipa: "melk" }, { nl: "suiker", pt: "açúcar", ipa: "sôi-ker" }, { nl: "bier", pt: "cerveja", ipa: "bir" }, { nl: "wijn", pt: "vinho", ipa: "vein" }, { nl: "sap", pt: "suco", ipa: "sap" }, { nl: "kopje", pt: "xícara", ipa: "kóp-yu" }, { nl: "glas", pt: "copo", ipa: "rrlás" }],
  phrases: [{ nl: "Een koffie, alstublieft.", pt: "Um café, por favor.", ipa: "un kó-fi, ál-stü-blíft" }, { nl: "Mag ik een thee?", pt: "Posso tomar um chá?", ipa: "mak ik un têi" }, { nl: "Zonder suiker, graag.", pt: "Sem açúcar, por favor.", ipa: "zón-der sôi-ker, rráakh" }, { nl: "Met melk, alstublieft.", pt: "Com leite, por favor.", ipa: "met melk, ál-stü-blíft" }, { nl: "Een glas water, graag.", pt: "Um copo de água, por favor.", ipa: "un rrlás vá-ter, rráakh" }, { nl: "Kan ik hier zitten?", pt: "Posso sentar aqui?", ipa: "kan ik rir zí-tun" }],
  grammar: "“Met” significa com, e “zonder” significa sem. Essas duas palavras resolvem muitos pedidos de comida e bebida. “Een” significa um/uma, mas soa como “un” em fala rápida. Para pedir algo de forma natural, diga o item e acrescente “graag” ou “alstublieft”.",
  practice: ["Peça um café sem açúcar.", "Peça chá com leite.", "Peça um copo de água.", "Pergunte se pode sentar em uma mesa.", "Crie três pedidos usando “met” e “zonder”."]
},
{
  day: 12,
  title: "Comida simples",
  titleNative: "Eenvoudig eten",
  focus: "Hoje você aprende alimentos básicos e frases para pedir algo rápido. Isso ajuda em padarias, cafés, mercados e lanchonetes nos Países Baixos.",
  vocab: [{ nl: "brood", pt: "pão", ipa: "brôt" }, { nl: "kaas", pt: "queijo", ipa: "kás" }, { nl: "ei", pt: "ovo", ipa: "ei" }, { nl: "soep", pt: "sopa", ipa: "sup" }, { nl: "salade", pt: "salada", ipa: "sa-lá-du" }, { nl: "vis", pt: "peixe", ipa: "vis" }, { nl: "kip", pt: "frango", ipa: "kip" }, { nl: "vlees", pt: "carne", ipa: "fleis" }, { nl: "groente", pt: "legumes / verduras", ipa: "rrun-tu" }, { nl: "fruit", pt: "fruta", ipa: "fraut" }],
  phrases: [{ nl: "Ik wil brood met kaas.", pt: "Quero pão com queijo.", ipa: "ik vil brôt met kás" }, { nl: "Heeft u soep?", pt: "O senhor tem sopa?", ipa: "reift ü sup" }, { nl: "Ik eet geen vlees.", pt: "Eu não como carne.", ipa: "ik eit rein fleis" }, { nl: "Is er vis?", pt: "Há peixe?", ipa: "is er vis" }, { nl: "Een salade, graag.", pt: "Uma salada, por favor.", ipa: "un sa-lá-du, rráakh" }, { nl: "Dat ziet er lekker uit.", pt: "Isso parece gostoso.", ipa: "dát zit er lé-ker aut" }],
  grammar: "“Geen” é usado antes de substantivos quando você quer negar: “geen vlees”, “geen suiker”, “geen probleem”. “Ik eet geen vlees” é uma frase muito útil para restrições alimentares. “Lekker” é uma palavra muito comum em neerlandês e significa gostoso, agradável ou bom. Você ouvirá “lekker” em muitos contextos.",
  practice: ["Diga que não come carne.", "Peça pão com queijo.", "Pergunte se há sopa.", "Elogie algo que parece gostoso.", "Faça um pedido simples usando “graag”."]
},
{
  day: 13,
  title: "No restaurante",
  titleNative: "In het restaurant",
  focus: "Hoje você aprende a pedir mesa, cardápio, prato e conta. Isso é útil em restaurantes de Amsterdã, Maastricht, Haarlem ou qualquer cidade turística.",
  vocab: [{ nl: "restaurant", pt: "restaurante", ipa: "res-to-ránt" }, { nl: "tafel", pt: "mesa", ipa: "tá-fel" }, { nl: "menu", pt: "cardápio", ipa: "mê-nü" }, { nl: "gerecht", pt: "prato", ipa: "ru-rekht" }, { nl: "rekening", pt: "conta", ipa: "rê-ku-ning" }, { nl: "fooi", pt: "gorjeta", ipa: "fói" }, { nl: "ober", pt: "garçom", ipa: "ô-ber" }, { nl: "vegetarisch", pt: "vegetariano", ipa: "vê-ru-tá-ris" }, { nl: "allergie", pt: "alergia", ipa: "a-lér-rí" }, { nl: "reserveren", pt: "reservar", ipa: "rê-zer-fê-run" }],
  phrases: [{ nl: "Een tafel voor twee, alstublieft.", pt: "Uma mesa para dois, por favor.", ipa: "un tá-fel fôr tvei, ál-stü-blíft" }, { nl: "Mag ik het menu?", pt: "Posso ver o cardápio?", ipa: "mak ik rut mê-nü" }, { nl: "Wat raadt u aan?", pt: "O que o senhor recomenda?", ipa: "vát rát ü án" }, { nl: "Ik ben allergisch voor noten.", pt: "Sou alérgico a nozes.", ipa: "ik ben a-lér-ris fôr nô-tun" }, { nl: "De rekening, alstublieft.", pt: "A conta, por favor.", ipa: "du rê-ku-ning, ál-stü-blíft" }, { nl: "Was alles naar wens?", pt: "Estava tudo do seu agrado?", ipa: "vas ál-lus nár vens" }],
  grammar: "“Voor” significa para, mas também pode significar “por” em alguns contextos. Em restaurante, “voor twee” significa para duas pessoas. “Mag ik...” é uma forma comum de pedir algo, parecida com “posso...?”. Para alergias, use “Ik ben allergisch voor...” seguido do alimento.",
  practice: ["Peça uma mesa para duas pessoas.", "Peça o cardápio.", "Pergunte o que o garçom recomenda.", "Diga que é alérgico a nozes.", "Peça a conta de forma educada."]
},
{
  day: 14,
  title: "Compras em lojas",
  titleNative: "Winkelen in winkels",
  focus: "Hoje você aprende frases para comprar roupas, lembranças e itens de viagem. Em cidades turísticas, lojas podem ser movimentadas, então frases curtas ajudam.",
  vocab: [{ nl: "winkel", pt: "loja", ipa: "vín-kul" }, { nl: "prijs", pt: "preço", ipa: "preiss" }, { nl: "maat", pt: "tamanho", ipa: "mát" }, { nl: "kleur", pt: "cor", ipa: "klör" }, { nl: "rood", pt: "vermelho", ipa: "rôt" }, { nl: "blauw", pt: "azul", ipa: "bláu" }, { nl: "zwart", pt: "preto", ipa: "zvárt" }, { nl: "wit", pt: "branco", ipa: "vit" }, { nl: "tas", pt: "bolsa", ipa: "tas" }, { nl: "bon", pt: "recibo", ipa: "bon" }],
  phrases: [{ nl: "Hoeveel kost dit?", pt: "Quanto custa isto?", ipa: "rú-fêl kost dit" }, { nl: "Heeft u een andere maat?", pt: "Tem outro tamanho?", ipa: "reift ü un án-du-ru mát" }, { nl: "Ik zoek een jas.", pt: "Estou procurando um casaco.", ipa: "ik zuk un yas" }, { nl: "Mag ik passen?", pt: "Posso experimentar?", ipa: "mak ik pá-sun" }, { nl: "Ik neem deze.", pt: "Vou levar este.", ipa: "ik neim dêi-zu" }, { nl: "Mag ik de bon?", pt: "Posso ter o recibo?", ipa: "mak ik du bon" }],
  grammar: "“Ik zoek...” significa “estou procurando...”, uma frase muito útil em lojas. “Deze” significa este/esta para algo próximo, enquanto “die” significa aquele/aquela. “Ik neem deze” é a forma natural de dizer “vou levar este”. Para experimentar roupas, use “passen”.",
  practice: ["Pergunte quanto custa um item.", "Diga que procura um casaco.", "Peça outro tamanho.", "Diga que vai levar este item.", "Peça o recibo."]
},
{
  day: 15,
  title: "Mercado e supermercado",
  titleNative: "Markt en supermarkt",
  focus: "Hoje você aprende a comprar comida em mercados e supermercados. Isso é prático para economizar dinheiro e fazer refeições simples durante a viagem.",
  vocab: [{ nl: "markt", pt: "mercado de rua", ipa: "markt" }, { nl: "supermarkt", pt: "supermercado", ipa: "sü-per-markt" }, { nl: "appel", pt: "maçã", ipa: "á-pul" }, { nl: "banaan", pt: "banana", ipa: "ba-nán" }, { nl: "kaas", pt: "queijo", ipa: "kás" }, { nl: "broodje", pt: "sanduíche / pãozinho", ipa: "brô-chu" }, { nl: "fles", pt: "garrafa", ipa: "fles" }, { nl: "zak", pt: "saco / sacola", ipa: "zak" }, { nl: "kassa", pt: "caixa", ipa: "ká-sa" }, { nl: "mandje", pt: "cestinha", ipa: "mán-chu" }],
  phrases: [{ nl: "Waar zijn de appels?", pt: "Onde estão as maçãs?", ipa: "vár zêin du á-puls" }, { nl: "Ik wil een fles water.", pt: "Quero uma garrafa de água.", ipa: "ik vil un fles vá-ter" }, { nl: "Heeft u een zak?", pt: "Tem uma sacola?", ipa: "reift ü un zak" }, { nl: "Is dit vers?", pt: "Isto é fresco?", ipa: "is dit fers" }, { nl: "Ik betaal met kaart.", pt: "Pago com cartão.", ipa: "ik bu-tál met kárt" }, { nl: "Waar is de kassa?", pt: "Onde fica o caixa?", ipa: "vár is du ká-sa" }],
  grammar: "“Waar zijn...” é usado para perguntar onde estão coisas no plural. “Waar is...” é usado para singular. “Vers” significa fresco, muito útil para comida. Em supermercados neerlandeses, muitas vezes você precisa pedir ou pagar por uma sacola, então “Heeft u een zak?” pode ser útil.",
  practice: ["Pergunte onde estão as maçãs.", "Peça uma garrafa de água.", "Pergunte se algo é fresco.", "Diga que paga com cartão.", "Pergunte onde fica o caixa."]
},
{
  day: 16,
  title: "Tempo e clima",
  titleNative: "Tijd en weer",
  focus: "Hoje você aprende a falar sobre horas, dias e clima. Isso ajuda a planejar passeios, trens e atividades ao ar livre nos Países Baixos, onde o tempo muda rápido.",
  vocab: [{ nl: "tijd", pt: "tempo / hora", ipa: "têit" }, { nl: "vandaag", pt: "hoje", ipa: "fan-dákh" }, { nl: "morgen", pt: "amanhã", ipa: "mór-run" }, { nl: "gisteren", pt: "ontem", ipa: "ris-tu-run" }, { nl: "uur", pt: "hora", ipa: "ür" }, { nl: "regen", pt: "chuva", ipa: "rê-run" }, { nl: "zon", pt: "sol", ipa: "zon" }, { nl: "wind", pt: "vento", ipa: "vint" }, { nl: "koud", pt: "frio", ipa: "kaut" }, { nl: "warm", pt: "quente", ipa: "varm" }],
  phrases: [{ nl: "Hoe laat is het?", pt: "Que horas são?", ipa: "rú lát is rut" }, { nl: "Het is drie uur.", pt: "São três horas.", ipa: "rut is drí ür" }, { nl: "Vandaag regent het.", pt: "Hoje está chovendo.", ipa: "fan-dákh rê-runt rut" }, { nl: "Morgen is het koud.", pt: "Amanhã estará frio.", ipa: "mór-run is rut kaut" }, { nl: "Is het ver lopen?", pt: "É longe para ir a pé?", ipa: "is rut fer lô-pun" }, { nl: "Ik heb geen paraplu.", pt: "Não tenho guarda-chuva.", ipa: "ik rep rein pa-ra-plü" }],
  grammar: "Para falar do clima, o neerlandês usa frequentemente “het”: “het regent”, “het is koud”. Isso funciona como o “it” em inglês, sem equivalente direto em português. “Hoe laat is het?” é a pergunta padrão para horas. “Uur” significa hora e também aparece em horários exatos.",
  practice: ["Pergunte que horas são.", "Diga que são três horas.", "Diga que hoje está chovendo.", "Diga que não tem guarda-chuva.", "Comente que amanhã estará frio."]
},
{
  day: 17,
  title: "Dias, horários e reservas",
  titleNative: "Dagen, tijden en reserveringen",
  focus: "Hoje você aprende dias da semana e frases para combinar horários. Isso é útil para reservas de restaurante, museus, passeios e visitas guiadas.",
  vocab: [{ nl: "maandag", pt: "segunda-feira", ipa: "mán-dákh" }, { nl: "dinsdag", pt: "terça-feira", ipa: "dins-dákh" }, { nl: "woensdag", pt: "quarta-feira", ipa: "vuns-dákh" }, { nl: "donderdag", pt: "quinta-feira", ipa: "dón-der-dákh" }, { nl: "vrijdag", pt: "sexta-feira", ipa: "vrêi-dákh" }, { nl: "zaterdag", pt: "sábado", ipa: "zá-ter-dákh" }, { nl: "zondag", pt: "domingo", ipa: "zón-dákh" }, { nl: "avond", pt: "noite", ipa: "á-font" }, { nl: "middag", pt: "tarde", ipa: "mí-dákh" }, { nl: "ochtend", pt: "manhã", ipa: "ókh-tent" }],
  phrases: [{ nl: "Ik wil reserveren voor vrijdag.", pt: "Quero reservar para sexta-feira.", ipa: "ik vil rê-zer-fê-run fôr vrêi-dákh" }, { nl: "Om zeven uur, graag.", pt: "Às sete horas, por favor.", ipa: "om zêi-fun ür, rráakh" }, { nl: "Is er plek vanavond?", pt: "Há lugar hoje à noite?", ipa: "is er plek fan-á-font" }, { nl: "Morgen om twaalf uur.", pt: "Amanhã às doze horas.", ipa: "mór-run om tválf ür" }, { nl: "Welke dag is het vandaag?", pt: "Que dia é hoje?", ipa: "vél-ku dákh is rut fan-dákh" }, { nl: "Tot morgen.", pt: "Até amanhã.", ipa: "tot mór-run" }],
  grammar: "Para horários, use “om” antes da hora: “om zeven uur”. Para dias, “voor vrijdag” pode significar para sexta-feira em contexto de reserva. “Vanavond” significa hoje à noite, uma palavra muito útil para restaurantes. “Tot morgen” é uma despedida comum quando você verá alguém no dia seguinte.",
  practice: ["Faça uma reserva para sexta-feira.", "Diga “às sete horas”.", "Pergunte se há lugar hoje à noite.", "Diga “até amanhã”.", "Pratique os dias da semana em ordem."]
},
{
  day: 18,
  title: "Museu, atrações e bilhetes",
  titleNative: "Museum, attracties en kaartjes",
  focus: "Hoje você aprende vocabulário para museus, atrações e entradas. Isso é ideal para visitar lugares como o Rijksmuseum, Van Gogh Museum ou Madurodam.",
  vocab: [{ nl: "museum", pt: "museu", ipa: "mü-zê-um" }, { nl: "kaartje", pt: "ingresso", ipa: "kár-chu" }, { nl: "ingang", pt: "entrada", ipa: "in-ráng" }, { nl: "uitgang", pt: "saída", ipa: "aut-ráng" }, { nl: "tentoonstelling", pt: "exposição", ipa: "ten-tôn-stel-ling" }, { nl: "gids", pt: "guia", ipa: "rrits" }, { nl: "plattegrond", pt: "mapa do local", ipa: "plá-tu-rront" }, { nl: "rij", pt: "fila", ipa: "rêi" }, { nl: "open", pt: "aberto", ipa: "ô-pun" }, { nl: "gesloten", pt: "fechado", ipa: "ru-slô-tun" }],
  phrases: [{ nl: "Ik wil twee kaartjes.", pt: "Quero dois ingressos.", ipa: "ik vil tvei kár-chus" }, { nl: "Waar is de ingang?", pt: "Onde fica a entrada?", ipa: "vár is du in-ráng" }, { nl: "Is het museum open?", pt: "O museu está aberto?", ipa: "is rut mü-zê-um ô-pun" }, { nl: "Hoe lang is de rij?", pt: "Quanto tempo está a fila?", ipa: "rú láng is du rêi" }, { nl: "Mag ik een plattegrond?", pt: "Posso ter um mapa do local?", ipa: "mak ik un plá-tu-rront" }, { nl: "Wanneer sluit het museum?", pt: "Quando o museu fecha?", ipa: "va-nêr slaut rut mü-zê-um" }],
  grammar: "“Open” e “gesloten” são palavras essenciais para horários de funcionamento. “Waar is de ingang?” e “Waar is de uitgang?” formam um par fácil de memorizar. “Sluit” vem do verbo “sluiten”, fechar. Para atrações turísticas, “kaartje” pode significar bilhete ou ingresso.",
  practice: ["Peça dois ingressos.", "Pergunte onde fica a entrada.", "Pergunte se o museu está aberto.", "Peça um mapa do local.", "Pergunte quando o museu fecha."]
},
{
  day: 19,
  title: "Saúde e farmácia",
  titleNative: "Gezondheid en apotheek",
  focus: "Hoje você aprende frases para explicar sintomas simples e comprar remédios. Isso é importante para lidar com dor, resfriado ou emergências leves durante a viagem.",
  vocab: [{ nl: "apotheek", pt: "farmácia", ipa: "a-po-têk" }, { nl: "dokter", pt: "médico", ipa: "dók-ter" }, { nl: "pijn", pt: "dor", ipa: "péin" }, { nl: "hoofdpijn", pt: "dor de cabeça", ipa: "rôft-péin" }, { nl: "buikpijn", pt: "dor de barriga", ipa: "bauk-péin" }, { nl: "koorts", pt: "febre", ipa: "kôrts" }, { nl: "verkouden", pt: "resfriado", ipa: "fer-kau-dun" }, { nl: "medicijn", pt: "remédio", ipa: "mê-di-sein" }, { nl: "pleister", pt: "curativo", ipa: "plêis-ter" }, { nl: "ziek", pt: "doente", ipa: "zik" }],
  phrases: [{ nl: "Ik heb hoofdpijn.", pt: "Estou com dor de cabeça.", ipa: "ik rep rôft-péin" }, { nl: "Ik voel me ziek.", pt: "Estou me sentindo doente.", ipa: "ik ful mu zik" }, { nl: "Waar is de apotheek?", pt: "Onde fica a farmácia?", ipa: "vár is du a-po-têk" }, { nl: "Heeft u iets tegen pijn?", pt: "Tem algo contra dor?", ipa: "reift ü iets tê-run péin" }, { nl: "Ik heb een dokter nodig.", pt: "Preciso de um médico.", ipa: "ik rep un dók-ter nô-dikh" }, { nl: "Is dit zonder recept?", pt: "Isto é sem receita?", ipa: "is dit zón-der ru-sept" }],
  grammar: "Para sintomas, use “Ik heb...” com o tipo de dor: “Ik heb hoofdpijn”. Para estado geral, use “Ik voel me...” como em “Ik voel me ziek”. “Nodig” significa necessário, então “Ik heb een dokter nodig” é uma frase direta e importante. “Zonder recept” significa sem receita médica.",
  practice: ["Diga que está com dor de cabeça.", "Pergunte onde fica a farmácia.", "Peça algo contra dor.", "Diga que precisa de um médico.", "Pergunte se um remédio é sem receita."]
},
{
  day: 20,
  title: "Emergências e segurança",
  titleNative: "Noodgevallen en veiligheid",
  focus: "Hoje você aprende frases para situações urgentes, perda de documentos ou necessidade de polícia. Espera-se que você não precise delas, mas elas são essenciais.",
  vocab: [{ nl: "noodgeval", pt: "emergência", ipa: "nôt-ru-val" }, { nl: "politie", pt: "polícia", ipa: "po-lí-tsi" }, { nl: "ambulance", pt: "ambulância", ipa: "am-bü-láns" }, { nl: "brandweer", pt: "bombeiros", ipa: "bránt-vêr" }, { nl: "paspoort", pt: "passaporte", ipa: "pás-port" }, { nl: "portemonnee", pt: "carteira", ipa: "por-tu-mo-nêi" }, { nl: "gestolen", pt: "roubado", ipa: "ru-stô-lun" }, { nl: "kwijt", pt: "perdido", ipa: "kvêit" }, { nl: "gevaar", pt: "perigo", ipa: "ru-vár" }, { nl: "veilig", pt: "seguro", ipa: "vêi-likh" }],
  phrases: [{ nl: "Help!", pt: "Socorro!", ipa: "relp" }, { nl: "Bel de politie!", pt: "Chame a polícia!", ipa: "bel du po-lí-tsi" }, { nl: "Ik ben mijn paspoort kwijt.", pt: "Perdi meu passaporte.", ipa: "ik ben mein pás-port kvêit" }, { nl: "Mijn portemonnee is gestolen.", pt: "Minha carteira foi roubada.", ipa: "mein por-tu-mo-nêi is ru-stô-lun" }, { nl: "Ik heb hulp nodig.", pt: "Preciso de ajuda.", ipa: "ik rep rulp nô-dikh" }, { nl: "Is het hier veilig?", pt: "É seguro aqui?", ipa: "is rut rir vêi-likh" }],
  grammar: "“Kwijt” significa perdido, especialmente quando você perdeu algo: “Ik ben mijn paspoort kwijt”. “Gestolen” significa roubado. Para emergências, frases curtas são melhores do que frases perfeitas. “Ik heb hulp nodig” é uma das frases mais importantes para memorizar.",
  practice: ["Diga que perdeu seu passaporte.", "Diga que sua carteira foi roubada.", "Peça ajuda imediatamente.", "Pergunte se o lugar é seguro.", "Pratique “politie”, “ambulance” e “brandweer”."]
},
{
  day: 21,
  title: "Conversa educada e pequenas gentilezas",
  titleNative: "Beleefd praten en kleine vriendelijkheden",
  focus: "Hoje você aprende a soar mais educado em interações comuns. Nos Países Baixos, a comunicação costuma ser direta, mas gentileza ainda faz diferença.",
  vocab: [{ nl: "dank u", pt: "obrigado formal", ipa: "dánk ü" }, { nl: "graag gedaan", pt: "de nada", ipa: "rráakh ru-dán" }, { nl: "sorry", pt: "desculpa", ipa: "só-ri" }, { nl: "excuseer", pt: "com licença", ipa: "eks-kü-zêr" }, { nl: "prima", pt: "ótimo / tudo bem", ipa: "prí-ma" }, { nl: "goed", pt: "bom", ipa: "rút" }, { nl: "slecht", pt: "ruim", ipa: "slekht" }, { nl: "vriendelijk", pt: "gentil", ipa: "frínt-du-lik" }, { nl: "beleefd", pt: "educado", ipa: "bu-lêift" }, { nl: "moment", pt: "momento", ipa: "mo-ment" }],
  phrases: [{ nl: "Dank u wel.", pt: "Muito obrigado formal.", ipa: "dánk ü vel" }, { nl: "Graag gedaan.", pt: "De nada.", ipa: "rráakh ru-dán" }, { nl: "Excuseer, mag ik iets vragen?", pt: "Com licença, posso perguntar algo?", ipa: "eks-kü-zêr, mak ik iets frá-run" }, { nl: "Een moment, alstublieft.", pt: "Um momento, por favor.", ipa: "un mo-ment, ál-stü-blíft" }, { nl: "Dat is heel vriendelijk.", pt: "Isso é muito gentil.", ipa: "dát is rêil frínt-du-lik" }, { nl: "Geen dank.", pt: "De nada.", ipa: "rein dánk" }],
  grammar: "“Dank u” é mais formal que “dank je”. Em lojas, hotéis e com pessoas mais velhas, “u” é uma escolha segura. “Mag ik iets vragen?” significa “posso perguntar algo?” e abre conversas de forma educada. “Heel” significa muito e pode intensificar adjetivos: “heel vriendelijk”.",
  practice: ["Agradeça formalmente a um funcionário.", "Responda “de nada”.", "Peça licença para fazer uma pergunta.", "Diga que algo foi muito gentil.", "Use “een moment” em uma frase imaginária."]
},
{
  day: 22,
  title: "Falar sobre gostos",
  titleNative: "Praten over voorkeuren",
  focus: "Hoje você aprende a dizer o que gosta, não gosta e prefere. Isso ajuda em restaurantes, passeios e conversas com moradores locais.",
  vocab: [{ nl: "leuk", pt: "legal / divertido", ipa: "lök" }, { nl: "mooi", pt: "bonito", ipa: "mói" }, { nl: "lekker", pt: "gostoso", ipa: "lé-ker" }, { nl: "saai", pt: "chato", ipa: "sái" }, { nl: "druk", pt: "cheio / movimentado", ipa: "druk" }, { nl: "rustig", pt: "tranquilo", ipa: "rüs-tikh" }, { nl: "favoriet", pt: "favorito", ipa: "fa-fo-rít" }, { nl: "muziek", pt: "música", ipa: "mü-zík" }, { nl: "kunst", pt: "arte", ipa: "kunst" }, { nl: "stad", pt: "cidade", ipa: "stat" }],
  phrases: [{ nl: "Ik vind het leuk.", pt: "Eu acho legal.", ipa: "ik vint rut lök" }, { nl: "Ik vind Amsterdam mooi.", pt: "Acho Amsterdã bonita.", ipa: "ik vint am-ster-dam mói" }, { nl: "Ik hou van muziek.", pt: "Eu gosto de música.", ipa: "ik ráu fan mü-zík" }, { nl: "Ik hou niet van drukte.", pt: "Não gosto de lugares cheios.", ipa: "ik ráu nit fan druk-tu" }, { nl: "Wat is jouw favoriete stad?", pt: "Qual é sua cidade favorita?", ipa: "vát is yau fa-fo-rí-tu stat" }, { nl: "Ik heb liever iets rustigs.", pt: "Eu prefiro algo tranquilo.", ipa: "ik rep lí-ver iets rüs-tikhs" }],
  grammar: "“Ik vind...” é usado para dar opinião: “Ik vind het leuk”. “Ik hou van...” significa “eu gosto de” em um sentido mais forte ou geral. Para negar, coloque “niet”: “Ik hou niet van...”. “Liever” expressa preferência, como “prefiro”.",
  practice: ["Diga que acha uma cidade bonita.", "Diga que gosta de música.", "Diga que não gosta de lugares cheios.", "Pergunte a cidade favorita de alguém.", "Diga que prefere algo tranquilo."]
},
{
  day: 23,
  title: "Conhecer pessoas",
  titleNative: "Mensen leren kennen",
  focus: "Hoje você aprende frases para conversar com pessoas em bares, passeios, hostels e eventos. O objetivo é iniciar conversa de forma simples e natural.",
  vocab: [{ nl: "waarvandaan", pt: "de onde", ipa: "vár-fan-dán" }, { nl: "werk", pt: "trabalho", ipa: "verk" }, { nl: "studie", pt: "estudo", ipa: "stü-di" }, { nl: "vakantie", pt: "férias", ipa: "va-kán-tsi" }, { nl: "reis", pt: "viagem", ipa: "rêis" }, { nl: "alleen", pt: "sozinho", ipa: "a-lên" }, { nl: "samen", pt: "juntos", ipa: "zá-mun" }, { nl: "vrienden", pt: "amigos", ipa: "frín-dun" }, { nl: "gezellig", pt: "agradável / sociável", ipa: "ru-zé-likh" }, { nl: "interessant", pt: "interessante", ipa: "in-tu-re-sánt" }],
  phrases: [{ nl: "Waar kom je vandaan?", pt: "De onde você vem?", ipa: "vár kom yu fan-dán" }, { nl: "Ben je hier op vakantie?", pt: "Você está aqui de férias?", ipa: "ben yu rir op va-kán-tsi" }, { nl: "Ik reis alleen.", pt: "Estou viajando sozinho.", ipa: "ik rêis a-lên" }, { nl: "Ik ben hier met vrienden.", pt: "Estou aqui com amigos.", ipa: "ik ben rir met frín-dun" }, { nl: "Dat klinkt interessant.", pt: "Isso parece interessante.", ipa: "dát klinkt in-tu-re-sánt" }, { nl: "Het is hier gezellig.", pt: "Aqui é agradável.", ipa: "rut is rir ru-zé-likh" }],
  grammar: "“Je” é uma forma informal de “você”, comum entre pessoas da mesma idade ou em ambientes casuais. “Ben je...?” significa “você está/é...?”. A palavra “gezellig” é muito neerlandesa e difícil de traduzir exatamente; pode significar aconchegante, social, agradável ou divertido. Use-a para elogiar um ambiente.",
  practice: ["Pergunte de onde alguém vem.", "Pergunte se a pessoa está de férias.", "Diga que viaja sozinho.", "Diga que está com amigos.", "Elogie o ambiente com “gezellig”."]
},
{
  day: 24,
  title: "Telefone, internet e tecnologia",
  titleNative: "Telefoon, internet en technologie",
  focus: "Hoje você aprende frases para internet, carregador, chip e problemas digitais. Isso é muito útil para mapas, reservas, pagamentos e comunicação durante a viagem.",
  vocab: [{ nl: "telefoon", pt: "telefone", ipa: "tê-lu-fôn" }, { nl: "oplader", pt: "carregador", ipa: "op-lá-der" }, { nl: "batterij", pt: "bateria", ipa: "ba-tu-rêi" }, { nl: "internet", pt: "internet", ipa: "in-ter-net" }, { nl: "wifi", pt: "wi-fi", ipa: "vái-fái" }, { nl: "simkaart", pt: "chip / cartão SIM", ipa: "sim-kárt" }, { nl: "wachtwoord", pt: "senha", ipa: "vakht-vôrt" }, { nl: "stopcontact", pt: "tomada", ipa: "stop-kon-takt" }, { nl: "scherm", pt: "tela", ipa: "skherm" }, { nl: "bericht", pt: "mensagem", ipa: "bu-rikht" }],
  phrases: [{ nl: "Heeft u wifi?", pt: "Vocês têm wi-fi?", ipa: "reift ü vái-fái" }, { nl: "Wat is het wachtwoord?", pt: "Qual é a senha?", ipa: "vát is rut vakht-vôrt" }, { nl: "Mijn batterij is leeg.", pt: "Minha bateria acabou.", ipa: "mein ba-tu-rêi is lêikh" }, { nl: "Waar is een stopcontact?", pt: "Onde há uma tomada?", ipa: "vár is un stop-kon-takt" }, { nl: "Ik heb een simkaart nodig.", pt: "Preciso de um chip.", ipa: "ik rep un sim-kárt nô-dikh" }, { nl: "Kan ik mijn telefoon opladen?", pt: "Posso carregar meu telefone?", ipa: "kan ik mein tê-lu-fôn op-lá-dun" }],
  grammar: "“Leeg” significa vazio, mas para bateria quer dizer descarregada. “Nodig” continua sendo útil para necessidades: “Ik heb een simkaart nodig”. Para pedir permissão, “Kan ik...” funciona bem. “Wat is het wachtwoord?” é uma frase essencial em cafés, hotéis e coworkings.",
  practice: ["Pergunte qual é a senha do wi-fi.", "Diga que sua bateria acabou.", "Pergunte onde há uma tomada.", "Diga que precisa de um chip.", "Peça para carregar seu telefone."]
},
{
  day: 25,
  title: "Alugar bicicleta",
  titleNative: "Een fiets huren",
  focus: "Hoje você aprende frases para alugar bicicleta, um dos meios de transporte mais típicos nos Países Baixos. Bicicletas são úteis, mas exigem atenção às regras locais.",
  vocab: [{ nl: "fiets", pt: "bicicleta", ipa: "fits" }, { nl: "huren", pt: "alugar", ipa: "rü-run" }, { nl: "slot", pt: "cadeado", ipa: "slot" }, { nl: "helm", pt: "capacete", ipa: "relm" }, { nl: "rem", pt: "freio", ipa: "rem" }, { nl: "licht", pt: "luz", ipa: "likht" }, { nl: "fietspad", pt: "ciclovia", ipa: "fits-pat" }, { nl: "dag", pt: "dia", ipa: "dákh" }, { nl: "uur", pt: "hora", ipa: "ür" }, { nl: "borg", pt: "caução", ipa: "borkh" }],
  phrases: [{ nl: "Ik wil een fiets huren.", pt: "Quero alugar uma bicicleta.", ipa: "ik vil un fits rü-run" }, { nl: "Hoeveel kost het per dag?", pt: "Quanto custa por dia?", ipa: "rú-fêl kost rut per dákh" }, { nl: "Is er een slot bij?", pt: "Vem com cadeado?", ipa: "is er un slot bêi" }, { nl: "Waar is het fietspad?", pt: "Onde fica a ciclovia?", ipa: "vár is rut fits-pat" }, { nl: "De rem werkt niet.", pt: "O freio não funciona.", ipa: "du rem werkt nit" }, { nl: "Moet ik borg betalen?", pt: "Preciso pagar caução?", ipa: "mut ik borkh bu-tá-lun" }],
  grammar: "Nos Países Baixos, “fiets” é uma palavra fundamental. “Huren” significa alugar, e aparece em “een fiets huren”. “Per dag” significa por dia, e “per uur” significa por hora. Se algo não funciona, volte à estrutura “werkt niet”.",
  practice: ["Diga que quer alugar uma bicicleta.", "Pergunte quanto custa por dia.", "Pergunte se vem com cadeado.", "Diga que o freio não funciona.", "Pergunte onde fica a ciclovia."]
},
{
  day: 26,
  title: "Fazer planos",
  titleNative: "Plannen maken",
  focus: "Hoje você aprende a sugerir planos e combinar encontros. Isso ajuda se você conhecer outros viajantes ou moradores locais durante a viagem.",
  vocab: [{ nl: "plan", pt: "plano", ipa: "plan" }, { nl: "afspraak", pt: "encontro / compromisso", ipa: "af-sprák" }, { nl: "samen", pt: "juntos", ipa: "zá-mun" }, { nl: "later", pt: "mais tarde", ipa: "lá-ter" }, { nl: "nu", pt: "agora", ipa: "nü" }, { nl: "straks", pt: "daqui a pouco", ipa: "straks" }, { nl: "misschien", pt: "talvez", ipa: "mi-skhín" }, { nl: "zeker", pt: "com certeza", ipa: "zê-ker" }, { nl: "plaats", pt: "lugar", ipa: "pláts" }, { nl: "tijd", pt: "hora / tempo", ipa: "têit" }],
  phrases: [{ nl: "Zullen we samen eten?", pt: "Vamos comer juntos?", ipa: "zü-lun vu zá-mun êi-tun" }, { nl: "Heb je later tijd?", pt: "Você tem tempo mais tarde?", ipa: "rep yu lá-ter têit" }, { nl: "Misschien morgen.", pt: "Talvez amanhã.", ipa: "mi-skhín mór-run" }, { nl: "Waar spreken we af?", pt: "Onde nos encontramos?", ipa: "vár sprê-kun vu af" }, { nl: "Om acht uur bij het station.", pt: "Às oito horas na estação.", ipa: "om ákh-t ür bêi rut stá-tsion" }, { nl: "Dat klinkt goed.", pt: "Isso parece bom.", ipa: "dát klinkt rút" }],
  grammar: "“Zullen we...?” é usado para sugerir algo, como “vamos...?”. “Afspreken” significa combinar um encontro. “Bij” significa perto de, junto a ou na casa de, dependendo do contexto. Para encontros, “bij het station” significa na estação ou perto dela.",
  practice: ["Sugira comer juntos.", "Pergunte se alguém tem tempo mais tarde.", "Diga “talvez amanhã”.", "Combine um encontro na estação.", "Responda que a ideia parece boa."]
},
{
  day: 27,
  title: "Opiniões e comparações simples",
  titleNative: "Meningen en eenvoudige vergelijkingen",
  focus: "Hoje você aprende a comparar lugares, preços e experiências. Isso é útil para escolher restaurantes, bairros, museus e passeios.",
  vocab: [{ nl: "beter", pt: "melhor", ipa: "bêi-ter" }, { nl: "slechter", pt: "pior", ipa: "slekh-ter" }, { nl: "groter", pt: "maior", ipa: "rrô-ter" }, { nl: "kleiner", pt: "menor", ipa: "klêi-ner" }, { nl: "duurder", pt: "mais caro", ipa: "dür-der" }, { nl: "goedkoper", pt: "mais barato", ipa: "rút-kô-per" }, { nl: "mooier", pt: "mais bonito", ipa: "mói-er" }, { nl: "sneller", pt: "mais rápido", ipa: "sné-ler" }, { nl: "langzamer", pt: "mais lento", ipa: "láng-zá-mer" }, { nl: "makkelijker", pt: "mais fácil", ipa: "má-ku-lu-ker" }],
  phrases: [{ nl: "Deze trein is sneller.", pt: "Este trem é mais rápido.", ipa: "dêi-zu trein is sné-ler" }, { nl: "Dat restaurant is goedkoper.", pt: "Aquele restaurante é mais barato.", ipa: "dát res-to-ránt is rút-kô-per" }, { nl: "Amsterdam is drukker dan Delft.", pt: "Amsterdã é mais movimentada que Delft.", ipa: "am-ster-dam is dru-ker dan delft" }, { nl: "Dit hotel is beter.", pt: "Este hotel é melhor.", ipa: "dit ro-tel is bêi-ter" }, { nl: "Welke optie is makkelijker?", pt: "Qual opção é mais fácil?", ipa: "vél-ku óp-tsi is má-ku-lu-ker" }, { nl: "Ik vind deze straat mooier.", pt: "Acho esta rua mais bonita.", ipa: "ik vint dêi-zu strát mói-er" }],
  grammar: "Muitos comparativos em neerlandês terminam em “-er”, como “sneller”, “mooier” e “goedkoper”. Para dizer “do que”, use “dan”: “drukker dan Delft”. A estrutura é parecida com o português quando você pensa em blocos. Comparações são úteis para tomar decisões rápidas durante a viagem.",
  practice: ["Diga que este trem é mais rápido.", "Diga que aquele restaurante é mais barato.", "Compare Amsterdã e Delft.", "Pergunte qual opção é mais fácil.", "Diga que uma rua é mais bonita."]
},
{
  day: 28,
  title: "Problemas de viagem",
  titleNative: "Reisproblemen",
  focus: "Hoje você aprende a explicar atrasos, cancelamentos e problemas com reservas. Isso ajuda em estações, aeroportos, hotéis e balcões de atendimento.",
  vocab: [{ nl: "vertraging", pt: "atraso", ipa: "fer-trá-ring" }, { nl: "geannuleerd", pt: "cancelado", ipa: "rê-a-nü-lêirt" }, { nl: "ticket", pt: "bilhete", ipa: "tí-ket" }, { nl: "vlucht", pt: "voo", ipa: "vlukht" }, { nl: "trein", pt: "trem", ipa: "trein" }, { nl: "probleem", pt: "problema", ipa: "pro-blêm" }, { nl: "balie", pt: "balcão", ipa: "bá-li" }, { nl: "informatie", pt: "informação", ipa: "in-for-má-tsi" }, { nl: "oplossing", pt: "solução", ipa: "op-ló-sing" }, { nl: "klacht", pt: "reclamação", ipa: "klakht" }],
  phrases: [{ nl: "Mijn trein heeft vertraging.", pt: "Meu trem está atrasado.", ipa: "mein trein reift fer-trá-ring" }, { nl: "Mijn vlucht is geannuleerd.", pt: "Meu voo foi cancelado.", ipa: "mein vlukht is rê-a-nü-lêirt" }, { nl: "Waar is de informatiebalie?", pt: "Onde fica o balcão de informações?", ipa: "vár is du in-for-má-tsi-bá-li" }, { nl: "Ik heb een probleem met mijn ticket.", pt: "Tenho um problema com meu bilhete.", ipa: "ik rep un pro-blêm met mein tí-ket" }, { nl: "Wat is de oplossing?", pt: "Qual é a solução?", ipa: "vát is du op-ló-sing" }, { nl: "Ik wil een klacht indienen.", pt: "Quero fazer uma reclamação.", ipa: "ik vil un klakht in-dêi-nun" }],
  grammar: "“Heeft vertraging” é a forma comum para dizer que algo está atrasado. “Is geannuleerd” significa foi cancelado. Em problemas de viagem, “met mijn ticket” significa com meu bilhete. Para reclamações formais, “een klacht indienen” é uma expressão útil.",
  practice: ["Diga que seu trem está atrasado.", "Diga que seu voo foi cancelado.", "Pergunte onde fica o balcão de informações.", "Explique que há um problema com seu bilhete.", "Pergunte qual é a solução."]
},
{
  day: 29,
  title: "Cultura local e comportamento",
  titleNative: "Lokale cultuur en gedrag",
  focus: "Hoje você aprende palavras e frases para entender costumes locais. Isso ajuda a agir com respeito em espaços públicos, restaurantes, casas e transporte.",
  vocab: [{ nl: "regel", pt: "regra", ipa: "rê-rul" }, { nl: "stil", pt: "silencioso", ipa: "stil" }, { nl: "druk", pt: "movimentado", ipa: "druk" }, { nl: "netjes", pt: "organizado / correto", ipa: "nét-yus" }, { nl: "op tijd", pt: "pontual", ipa: "op têit" }, { nl: "direct", pt: "direto", ipa: "di-rekt" }, { nl: "fietsers", pt: "ciclistas", ipa: "fits-ers" }, { nl: "wachtrij", pt: "fila", ipa: "vakht-rêi" }, { nl: "afval", pt: "lixo", ipa: "af-val" }, { nl: "respect", pt: "respeito", ipa: "res-pekt" }],
  phrases: [{ nl: "Moet ik hier wachten?", pt: "Devo esperar aqui?", ipa: "mut ik rir vákh-tun" }, { nl: "Is dit toegestaan?", pt: "Isto é permitido?", ipa: "is dit tu-ru-stán" }, { nl: "Waar moet het afval?", pt: "Onde vai o lixo?", ipa: "vár mut rut af-val" }, { nl: "Nederlanders zijn vaak direct.", pt: "Os neerlandeses são frequentemente diretos.", ipa: "nêi-der-lan-ders zêin fák di-rekt" }, { nl: "Ik ben op tijd.", pt: "Estou pontual.", ipa: "ik ben op têit" }, { nl: "Pas op voor fietsers.", pt: "Cuidado com os ciclistas.", ipa: "pas op fôr fits-ers" }],
  grammar: "“Moet ik...” significa “devo/preciso...?” e é muito útil para regras. “Toegestaan” significa permitido. Nos Países Baixos, pontualidade e franqueza são valorizadas, mas isso não significa falta de educação. Em cidades com muitas bicicletas, “Pas op voor fietsers” é uma frase culturalmente muito real.",
  practice: ["Pergunte se deve esperar aqui.", "Pergunte se algo é permitido.", "Pergunte onde vai o lixo.", "Diga que está pontual.", "Avise alguém para tomar cuidado com ciclistas."]
},
{
  day: 30,
  title: "Revisão geral para viajar com confiança",
  titleNative: "Algemene herhaling om met vertrouwen te reizen",
  focus: "Hoje você revisa frases essenciais para circular, pedir, resolver problemas e conversar. O objetivo é sair do curso com blocos prontos para situações reais nos Países Baixos.",
  vocab: [{ nl: "reis", pt: "viagem", ipa: "rêis" }, { nl: "stad", pt: "cidade", ipa: "stat" }, { nl: "station", pt: "estação", ipa: "stá-tsion" }, { nl: "hotel", pt: "hotel", ipa: "ro-tel" }, { nl: "restaurant", pt: "restaurante", ipa: "res-to-ránt" }, { nl: "kaartje", pt: "bilhete / ingresso", ipa: "kár-chu" }, { nl: "hulp", pt: "ajuda", ipa: "rulp" }, { nl: "geld", pt: "dinheiro", ipa: "relt" }, { nl: "tijd", pt: "tempo / hora", ipa: "têit" }, { nl: "vriendelijk", pt: "gentil", ipa: "frínt-du-lik" }],
  phrases: [{ nl: "Ik spreek een beetje Nederlands.", pt: "Eu falo um pouco de neerlandês.", ipa: "ik spreik un bêi-chu nêi-der-lants" }, { nl: "Kunt u mij helpen?", pt: "Pode me ajudar?", ipa: "kunt ü mei rél-pun" }, { nl: "Ik wil graag betalen.", pt: "Eu gostaria de pagar.", ipa: "ik vil rráakh bu-tá-lun" }, { nl: "Waar moet ik heen?", pt: "Para onde devo ir?", ipa: "vár mut ik rein" }, { nl: "Ik begrijp het nu.", pt: "Agora eu entendo.", ipa: "ik bu-rrêip rut nü" }, { nl: "Bedankt voor uw hulp.", pt: "Obrigado pela sua ajuda.", ipa: "bu-dánkt fôr üw rulp" }],
  grammar: "Nesta revisão, o mais importante é combinar blocos: “Ik wil...”, “Waar is...”, “Kunt u...”, “Ik heb...”. Com essas estruturas, você consegue criar muitas frases práticas sem dominar toda a gramática. Lembre-se de usar “u” para situações formais e “je” para situações informais. O objetivo em viagem é ser claro, educado e compreensível.",
  practice: ["Diga que fala um pouco de neerlandês.", "Peça ajuda de forma educada.", "Diga que gostaria de pagar.", "Pergunte para onde deve ir.", "Agradeça pela ajuda recebida."]
}
];

var CONVERSATIONS_PT_NL = [
{ title: "Pedindo café em Amsterdã", scene: "Você entra em um café perto de um canal em Amsterdã pela manhã. O atendente cumprimenta você e você faz um pedido simples.", lines: [{ who: "them", nl: "Goedemorgen, wat wilt u drinken?", pt: "Bom dia, o que o senhor gostaria de beber?" }, { who: "you", nl: "Goedemorgen, een koffie, alstublieft.", pt: "Bom dia, um café, por favor." }, { who: "them", nl: "Wilt u melk of suiker?", pt: "Quer leite ou açúcar?" }, { who: "you", nl: "Met melk, maar zonder suiker.", pt: "Com leite, mas sem açúcar." }, { who: "them", nl: "Wilt u er iets bij eten?", pt: "Quer algo para comer junto?" }, { who: "you", nl: "Ja, een broodje kaas, graag.", pt: "Sim, um sanduíche de queijo, por favor." }, { who: "them", nl: "Dat is samen acht euro.", pt: "Isso dá oito euros no total." }, { who: "you", nl: "Kan ik met kaart betalen?", pt: "Posso pagar com cartão?" }, { who: "them", nl: "Ja, natuurlijk.", pt: "Sim, claro." }, { who: "you", nl: "Dank je wel.", pt: "Muito obrigado." }, { who: "them", nl: "Graag gedaan, fijne dag!", pt: "De nada, tenha um bom dia!" }] },
{ title: "Check-in no hotel", scene: "Você chega ao hotel em Utrecht depois de uma viagem de trem. Na recepção, você precisa confirmar a reserva e perguntar sobre o café da manhã.", lines: [{ who: "them", nl: "Goedenavond, welkom in ons hotel.", pt: "Boa noite, bem-vindo ao nosso hotel." }, { who: "you", nl: "Goedenavond, ik heb een reservering.", pt: "Boa noite, tenho uma reserva." }, { who: "them", nl: "Op welke naam?", pt: "Em qual nome?" }, { who: "you", nl: "Mijn naam is Silva.", pt: "Meu nome é Silva." }, { who: "them", nl: "Mag ik uw paspoort zien?", pt: "Posso ver seu passaporte?" }, { who: "you", nl: "Ja, natuurlijk, alstublieft.", pt: "Sim, claro, aqui está." }, { who: "them", nl: "U heeft kamer drie op de tweede verdieping.", pt: "O senhor tem o quarto três no segundo andar." }, { who: "you", nl: "Is ontbijt inbegrepen?", pt: "O café da manhã está incluído?" }, { who: "them", nl: "Ja, ontbijt is van zeven tot tien uur.", pt: "Sim, o café da manhã é das sete às dez." }, { who: "you", nl: "Waar is de lift?", pt: "Onde fica o elevador?" }, { who: "them", nl: "Rechts, naast de receptie.", pt: "À direita, ao lado da recepção." }] },
{ title: "Perguntando direções para a estação", scene: "Você está em Delft e precisa encontrar a estação de trem. Você para uma pessoa na rua e pede ajuda com educação.", lines: [{ who: "you", nl: "Excuseer, mag ik iets vragen?", pt: "Com licença, posso perguntar algo?" }, { who: "them", nl: "Ja, natuurlijk.", pt: "Sim, claro." }, { who: "you", nl: "Waar is het station?", pt: "Onde fica a estação?" }, { who: "them", nl: "Ga rechtdoor en sla dan linksaf.", pt: "Vá em frente e depois vire à esquerda." }, { who: "you", nl: "Is het dichtbij?", pt: "É perto?" }, { who: "them", nl: "Ja, ongeveer vijf minuten lopen.", pt: "Sim, cerca de cinco minutos a pé." }, { who: "you", nl: "Moet ik over de brug?", pt: "Preciso atravessar a ponte?" }, { who: "them", nl: "Ja, over de brug en dan rechts.", pt: "Sim, atravesse a ponte e depois à direita." }, { who: "you", nl: "Dank u wel voor uw hulp.", pt: "Muito obrigado pela sua ajuda." }, { who: "them", nl: "Geen probleem, fijne reis.", pt: "Sem problema, boa viagem." }] },
{ title: "Jantando em um restaurante", scene: "Você está em um restaurante em Maastricht e quer uma mesa, pedir recomendação e pagar a conta. O garçom fala de forma educada e direta.", lines: [{ who: "them", nl: "Goedenavond, heeft u gereserveerd?", pt: "Boa noite, o senhor fez reserva?" }, { who: "you", nl: "Nee, heeft u een tafel voor twee?", pt: "Não, vocês têm uma mesa para dois?" }, { who: "them", nl: "Ja, kom maar mee.", pt: "Sim, venha comigo." }, { who: "you", nl: "Mag ik het menu, alstublieft?", pt: "Posso ver o cardápio, por favor?" }, { who: "them", nl: "Natuurlijk, hier is het menu.", pt: "Claro, aqui está o cardápio." }, { who: "you", nl: "Wat raadt u aan?", pt: "O que o senhor recomenda?" }, { who: "them", nl: "De vis is vandaag erg goed.", pt: "O peixe está muito bom hoje." }, { who: "you", nl: "Dan neem ik de vis.", pt: "Então vou querer o peixe." }, { who: "them", nl: "Wilt u nog iets drinken?", pt: "Quer mais algo para beber?" }, { who: "you", nl: "Een glas water, graag.", pt: "Um copo de água, por favor." }, { who: "them", nl: "Prima.", pt: "Ótimo." }, { who: "you", nl: "De rekening, alstublieft.", pt: "A conta, por favor." }] },
{ title: "Comprando bilhete de trem", scene: "Você está na estação central de Roterdã e quer viajar para Haia. Você fala com um funcionário no balcão de informações.", lines: [{ who: "them", nl: "Goedemiddag, kan ik u helpen?", pt: "Boa tarde, posso ajudar?" }, { who: "you", nl: "Ja, ik wil een kaartje naar Den Haag.", pt: "Sim, quero um bilhete para Haia." }, { who: "them", nl: "Enkele reis of retour?", pt: "Só ida ou ida e volta?" }, { who: "you", nl: "Retour, alstublieft.", pt: "Ida e volta, por favor." }, { who: "them", nl: "Dat is twaalf euro.", pt: "São doze euros." }, { who: "you", nl: "Van welk perron vertrekt de trein?", pt: "De qual plataforma parte o trem?" }, { who: "them", nl: "Van perron vier.", pt: "Da plataforma quatro." }, { who: "you", nl: "Wanneer vertrekt de trein?", pt: "Quando o trem parte?" }, { who: "them", nl: "Over tien minuten.", pt: "Em dez minutos." }, { who: "you", nl: "Moet ik overstappen?", pt: "Preciso fazer baldeação?" }, { who: "them", nl: "Nee, het is een directe trein.", pt: "Não, é um trem direto." }] },
{ title: "Comprando uma jaqueta", scene: "Você entra em uma loja em Haarlem porque precisa de uma jaqueta para o clima frio. O atendente ajuda você com tamanho, cor e pagamento.", lines: [{ who: "them", nl: "Hallo, kan ik u helpen?", pt: "Olá, posso ajudar?" }, { who: "you", nl: "Ja, ik zoek een jas.", pt: "Sim, estou procurando uma jaqueta." }, { who: "them", nl: "Welke maat heeft u?", pt: "Qual tamanho o senhor veste?" }, { who: "you", nl: "Heeft u maat medium?", pt: "Vocês têm tamanho médio?" }, { who: "them", nl: "Ja, in zwart en blauw.", pt: "Sim, em preto e azul." }, { who: "you", nl: "Mag ik de blauwe passen?", pt: "Posso experimentar a azul?" }, { who: "them", nl: "Natuurlijk, de paskamer is daar.", pt: "Claro, o provador é ali." }, { who: "you", nl: "Deze jas is goed.", pt: "Esta jaqueta está boa." }, { who: "them", nl: "Wilt u deze nemen?", pt: "Quer levar esta?" }, { who: "you", nl: "Ja, ik neem deze.", pt: "Sim, vou levar esta." }, { who: "them", nl: "Wilt u de bon?", pt: "Quer o recibo?" }, { who: "you", nl: "Ja, graag.", pt: "Sim, por favor." }] },
{ title: "Na farmácia", scene: "Você está em Leiden e acordou com dor de cabeça. Você entra em uma farmácia para pedir algo simples contra dor.", lines: [{ who: "them", nl: "Goedemorgen, waarmee kan ik u helpen?", pt: "Bom dia, em que posso ajudar?" }, { who: "you", nl: "Ik heb hoofdpijn.", pt: "Estou com dor de cabeça." }, { who: "them", nl: "Heeft u ook koorts?", pt: "Também está com febre?" }, { who: "you", nl: "Nee, geen koorts.", pt: "Não, sem febre." }, { who: "them", nl: "Wilt u iets tegen pijn?", pt: "Quer algo contra dor?" }, { who: "you", nl: "Ja, alstublieft.", pt: "Sim, por favor." }, { who: "them", nl: "Dit medicijn is zonder recept.", pt: "Este remédio é sem receita." }, { who: "you", nl: "Hoe vaak moet ik het nemen?", pt: "Com que frequência devo tomar?" }, { who: "them", nl: "Twee keer per dag met water.", pt: "Duas vezes por dia com água." }, { who: "you", nl: "Dank u wel.", pt: "Muito obrigado." }, { who: "them", nl: "Graag gedaan, beterschap.", pt: "De nada, melhoras." }] },
{ title: "Conversa casual com um morador local", scene: "Você está em um bar tranquilo em Groningen e começa uma conversa com uma pessoa local. A conversa é simples, amigável e natural.", lines: [{ who: "you", nl: "Hallo, is deze plek vrij?", pt: "Olá, este lugar está livre?" }, { who: "them", nl: "Ja, natuurlijk, ga zitten.", pt: "Sim, claro, sente-se." }, { who: "you", nl: "Dank je, het is hier gezellig.", pt: "Obrigado, aqui é agradável." }, { who: "them", nl: "Ja, dit is een leuke bar.", pt: "Sim, este é um bar legal." }, { who: "you", nl: "Kom je uit Groningen?", pt: "Você é de Groningen?" }, { who: "them", nl: "Ja, en jij?", pt: "Sim, e você?" }, { who: "you", nl: "Ik kom uit Portugal, ik ben hier op vakantie.", pt: "Venho de Portugal, estou aqui de férias." }, { who: "them", nl: "Leuk, hoe vind je Nederland?", pt: "Legal, o que você acha dos Países Baixos?" }, { who: "you", nl: "Ik vind het mooi, maar het weer is koud.", pt: "Acho bonito, mas o clima é frio." }, { who: "them", nl: "Dat klopt, het regent vaak.", pt: "É verdade, chove frequentemente." }, { who: "you", nl: "Toch vind ik de stad heel mooi.", pt: "Mesmo assim, acho a cidade muito bonita." }, { who: "them", nl: "Welkom in Groningen!", pt: "Bem-vindo a Groningen!" }] }
];
