var COURSE_TR_AR = [
  {
    title: "Selamlaşma ve temel nezaket",
    titleNative: "التحيات والمجاملة الأساسية",
    focus: "Bugün Kahire’de bir otele girerken, dükkâna girerken veya biriyle ilk kez konuşurken kullanacağın en temel selamları öğreniyorsun. Amaç, kısa ve nazik bir başlangıç yapabilmek.",
    vocab: [
      {ar: "مرحبا", tr: "Merhaba", ipa: "mar-ha-ban"},
      {ar: "أهلا", tr: "Hoş geldin / merhaba", ipa: "ah-lan"},
      {ar: "صباح الخير", tr: "Günaydın", ipa: "sa-bah al-hayr"},
      {ar: "مساء الخير", tr: "İyi akşamlar", ipa: "ma-sa al-hayr"},
      {ar: "شكرا", tr: "Teşekkürler", ipa: "şuk-ran"},
      {ar: "عفوا", tr: "Rica ederim / pardon", ipa: "af-wan"},
      {ar: "نعم", tr: "Evet", ipa: "na-am"},
      {ar: "لا", tr: "Hayır", ipa: "la"},
      {ar: "من فضلك", tr: "Lütfen", ipa: "min fad-lak"},
      {ar: "وداعا", tr: "Hoşça kal", ipa: "wa-da-an"},
    ],
    phrases: [
      {ar: "مرحبا، كيف حالك؟", tr: "Merhaba, nasılsın?", ipa: "mar-ha-ban, ki-fa ha-luk?"},
      {ar: "أنا بخير، شكرا", tr: "İyiyim, teşekkürler", ipa: "a-na bi-hayr, şuk-ran"},
      {ar: "من فضلك", tr: "Lütfen", ipa: "min fad-lak"},
      {ar: "شكرا جزيلا", tr: "Çok teşekkür ederim", ipa: "şuk-ran ja-zi-lan"},
      {ar: "إلى اللقاء", tr: "Görüşmek üzere", ipa: "i-la al-li-ka"},
      {ar: "لا، شكرا", tr: "Hayır, teşekkürler", ipa: "la, şuk-ran"},
    ],
    grammar: "Arapçada “مرحبا” en güvenli selamlardan biridir ve neredeyse her ortamda kullanılabilir. “من فضلك” erkek birine “lütfen” demek için kullanılır; kadın birine daha doğal biçim “من فضلكِ” olur. Seyahatte ilk hedef kusursuz gramer değil, nazik ve anlaşılır olmaktır.",
    practice: [
      "1. “Merhaba” ve “teşekkürler” kelimelerini Arapça söyle.",
      "2. Bir kafeye girerken kullanacağın iki kelime seç.",
      "3. “Hayır, teşekkürler” cümlesini yüksek sesle üç kez tekrar et.",
      "4. “Nasılsın?” sorusuna Arapça kısa cevap ver.",
      "5. Bugünkü kelimelerle iki satırlık mini diyalog yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kendini tanıtma",
    titleNative: "التعريف بالنفس",
    focus: "Bugün Amman’da bir hostel lobisinde veya tur grubunda kendini kısaca tanıtmayı öğreniyorsun. İsmini, nereli olduğunu ve Türk olduğunu söyleyebilmek temel seyahat becerisidir.",
    vocab: [
      {ar: "أنا", tr: "Ben", ipa: "a-na"},
      {ar: "اسمي", tr: "Benim adım", ipa: "is-mi"},
      {ar: "تركيا", tr: "Türkiye", ipa: "tur-ki-ya"},
      {ar: "تركي", tr: "Türk erkek", ipa: "tur-ki"},
      {ar: "تركية", tr: "Türk kadın", ipa: "tur-ki-ya"},
      {ar: "سائح", tr: "Turist erkek", ipa: "sa-ih"},
      {ar: "سائحة", tr: "Turist kadın", ipa: "sa-i-ha"},
      {ar: "صديق", tr: "Arkadaş", ipa: "sa-dik"},
      {ar: "جديد", tr: "Yeni", ipa: "ja-did"},
      {ar: "تشرفت", tr: "Memnun oldum", ipa: "ta-shar-raft"},
    ],
    phrases: [
      {ar: "اسمي علي", tr: "Benim adım Ali", ipa: "is-mi a-li"},
      {ar: "أنا من تركيا", tr: "Ben Türkiye’denim", ipa: "a-na min tur-ki-ya"},
      {ar: "أنا تركي", tr: "Ben Türküm", ipa: "a-na tur-ki"},
      {ar: "أنا سائحة", tr: "Ben turistim", ipa: "a-na sa-i-ha"},
      {ar: "تشرفت بمعرفتك", tr: "Tanıştığıma memnun oldum", ipa: "ta-shar-raft bi-ma-ri-fa-tak"},
      {ar: "ما اسمك؟", tr: "Adın ne?", ipa: "ma is-muk?"},
    ],
    grammar: "“أنا” kelimesi “ben” demektir ve çoğu basit cümlede başa gelir. “من” kelimesi “-den/-dan” anlamındadır: “أنا من تركيا” = “Ben Türkiye’denim.” Arapçada erkek ve kadın formları bazen değişir; turist için erkek “سائح”, kadın “سائحة” kullanılır.",
    practice: [
      "1. “Ben Türkiye’denim” cümlesini Arapça kur.",
      "2. Kendi adınla “Benim adım...” cümlesini yaz.",
      "3. “Tanıştığıma memnun oldum” ifadesini tekrar et.",
      "4. Erkek ve kadın “turist” kelimelerini karşılaştır.",
      "5. Bir yabancıya soracağın “Adın ne?” sorusunu Arapça söyle.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Sayılar 0–20",
    titleNative: "الأرقام من صفر إلى عشرين",
    focus: "Bugün Beyrut’ta pazarda fiyat sorarken veya taksi ücreti anlamaya çalışırken sayılara başlıyorsun. İlk 20 sayı günlük alışverişte çok işine yarar.",
    vocab: [
      {ar: "صفر", tr: "Sıfır", ipa: "sifr"},
      {ar: "واحد", tr: "Bir", ipa: "wa-hid"},
      {ar: "اثنان", tr: "İki", ipa: "ith-nan"},
      {ar: "ثلاثة", tr: "Üç", ipa: "tha-la-tha"},
      {ar: "أربعة", tr: "Dört", ipa: "ar-ba-a"},
      {ar: "خمسة", tr: "Beş", ipa: "ham-sa"},
      {ar: "ستة", tr: "Altı", ipa: "sit-ta"},
      {ar: "سبعة", tr: "Yedi", ipa: "sab-a"},
      {ar: "ثمانية", tr: "Sekiz", ipa: "tha-ma-ni-ya"},
      {ar: "عشرة", tr: "On", ipa: "a-sha-ra"},
    ],
    phrases: [
      {ar: "واحد من فضلك", tr: "Bir tane lütfen", ipa: "wa-hid min fad-lak"},
      {ar: "اثنان من هذا", tr: "Bundan iki tane", ipa: "ith-nan min ha-za"},
      {ar: "كم السعر؟", tr: "Fiyat ne kadar?", ipa: "kam as-si-r?"},
      {ar: "السعر عشرة", tr: "Fiyat on", ipa: "as-si-r a-sha-ra"},
      {ar: "أريد خمسة", tr: "Beş tane istiyorum", ipa: "u-rid ham-sa"},
      {ar: "هل عندك ثلاثة؟", tr: "Üç tane var mı?", ipa: "hal in-dak tha-la-tha?"},
    ],
    grammar: "Arapçada sayılar konuşma dilinde bölgelere göre farklı telaffuz edilebilir, ama Modern Standart Arapça formları çoğu yerde anlaşılır. “كم” soru kelimesi “kaç/ne kadar” anlamına gelir. Fiyat ve miktar sormak için çok pratiktir.",
    practice: [
      "1. 0’dan 10’a kadar Arapça say.",
      "2. “Bir tane lütfen” cümlesini söyle.",
      "3. “Fiyat ne kadar?” sorusunu ezberle.",
      "4. Beş farklı sayı seçip Arapça yaz.",
      "5. Pazarda üç ürün almak için kısa bir cümle kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Evet, hayır ve basit sorular",
    titleNative: "نعم، لا والأسئلة البسيطة",
    focus: "Bugün Dubai’de bir müzede, alışveriş merkezinde veya resepsiyonda kısa sorular sormayı ve cevaplamayı öğreniyorsun. Seyahatte hızlı anlaşmak için “var mı?”, “mümkün mü?”, “tamam mı?” çok önemlidir.",
    vocab: [
      {ar: "هل", tr: "Soru eki / mi", ipa: "hal"},
      {ar: "ممكن", tr: "Mümkün", ipa: "mum-kin"},
      {ar: "تمام", tr: "Tamam", ipa: "ta-mam"},
      {ar: "هنا", tr: "Burada", ipa: "hu-na"},
      {ar: "هناك", tr: "Orada", ipa: "hu-nak"},
      {ar: "الآن", tr: "Şimdi", ipa: "al-an"},
      {ar: "اليوم", tr: "Bugün", ipa: "al-yawm"},
      {ar: "غدا", tr: "Yarın", ipa: "gha-dan"},
      {ar: "مفتوح", tr: "Açık", ipa: "maf-tuh"},
      {ar: "مغلق", tr: "Kapalı", ipa: "mugh-lak"},
    ],
    phrases: [
      {ar: "هل هذا ممكن؟", tr: "Bu mümkün mü?", ipa: "hal ha-za mum-kin?"},
      {ar: "نعم، ممكن", tr: "Evet, mümkün", ipa: "na-am, mum-kin"},
      {ar: "لا، غير ممكن", tr: "Hayır, mümkün değil", ipa: "la, ghayr mum-kin"},
      {ar: "هل المكان مفتوح؟", tr: "Yer açık mı?", ipa: "hal al-ma-kan maf-tuh?"},
      {ar: "هل أنت هنا؟", tr: "Burada mısın?", ipa: "hal anta hu-na?"},
      {ar: "تمام، شكرا", tr: "Tamam, teşekkürler", ipa: "ta-mam, şuk-ran"},
    ],
    grammar: "“هل” cümlenin başına gelerek evet-hayır sorusu yapar. Türkçedeki “mi/mı” gibi düşünebilirsin, ama Arapçada genellikle cümlenin başına yerleşir. “هل هذا ممكن؟” seyahat boyunca çok kullanışlı, güvenli bir kalıptır.",
    practice: [
      "1. “Bu mümkün mü?” cümlesini Arapça söyle.",
      "2. “Yer açık mı?” sorusunu yaz.",
      "3. “Evet, mümkün” ve “Hayır, mümkün değil” cevaplarını karşılaştır.",
      "4. “Burada” ve “orada” kelimeleriyle iki cümle kur.",
      "5. Bugünkü kelimelerle resepsiyonda kısa bir soru hazırla.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Yolculuk için temel ihtiyaçlar",
    titleNative: "الاحتياجات الأساسية للسفر",
    focus: "Bugün Fas’ta Marakeş sokaklarında gezerken su, tuvalet, telefon ve yardım gibi acil temel ihtiyaçları ifade etmeyi öğreniyorsun. Bu ders güvenlik ve rahatlık için tasarlandı.",
    vocab: [
      {ar: "ماء", tr: "Su", ipa: "ma"},
      {ar: "حمام", tr: "Tuvalet", ipa: "ham-mam"},
      {ar: "هاتف", tr: "Telefon", ipa: "ha-tif"},
      {ar: "إنترنت", tr: "İnternet", ipa: "in-ter-net"},
      {ar: "مساعدة", tr: "Yardım", ipa: "mu-sa-a-da"},
      {ar: "مشكلة", tr: "Sorun", ipa: "mush-ki-la"},
      {ar: "حقيبة", tr: "Çanta", ipa: "ha-ki-ba"},
      {ar: "جواز سفر", tr: "Pasaport", ipa: "ja-waz sa-far"},
      {ar: "نقود", tr: "Para", ipa: "nu-kud"},
      {ar: "خريطة", tr: "Harita", ipa: "kha-ri-ta"},
    ],
    phrases: [
      {ar: "أحتاج إلى ماء", tr: "Suya ihtiyacım var", ipa: "ah-taj i-la ma"},
      {ar: "أين الحمام؟", tr: "Tuvalet nerede?", ipa: "ay-na al-ham-mam?"},
      {ar: "أحتاج إلى مساعدة", tr: "Yardıma ihtiyacım var", ipa: "ah-taj i-la mu-sa-a-da"},
      {ar: "عندي مشكلة", tr: "Bir sorunum var", ipa: "in-di mush-ki-la"},
      {ar: "أين جواز السفر؟", tr: "Pasaport nerede?", ipa: "ay-na ja-waz as-sa-far?"},
      {ar: "هل عندك إنترنت؟", tr: "İnternet var mı?", ipa: "hal in-dak in-ter-net?"},
    ],
    grammar: "“أحتاج إلى” kalıbı “... ihtiyacım var” demektir. Ardından isim gelir: “أحتاج إلى ماء” = “Suya ihtiyacım var.” “عندي” ise “bende var / benim var” anlamındadır ve “عندي مشكلة” gibi pratik cümlelerde kullanılır.",
    practice: [
      "1. “Suya ihtiyacım var” cümlesini söyle.",
      "2. “Tuvalet nerede?” sorusunu ezberle.",
      "3. “Bir sorunum var” cümlesini üç kez tekrar et.",
      "4. Pasaport, telefon ve çanta kelimelerini Arapça yaz.",
      "5. Yardım istemek için iki cümlelik bir mini sahne kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Havalimanında",
    titleNative: "في المطار",
    focus: "Bugün Doha Havalimanı’nda iniş yaptıktan sonra bagaj, pasaport kontrolü ve çıkış tabelalarını anlamaya odaklanıyorsun. Büyük havalimanlarında kısa sorular hayat kurtarır.",
    vocab: [
      {ar: "مطار", tr: "Havalimanı", ipa: "ma-tar"},
      {ar: "رحلة", tr: "Uçuş", ipa: "rih-la"},
      {ar: "طائرة", tr: "Uçak", ipa: "ta-i-ra"},
      {ar: "بوابة", tr: "Kapı", ipa: "ba-wa-ba"},
      {ar: "جواز", tr: "Pasaport", ipa: "ja-waz"},
      {ar: "تذكرة", tr: "Bilet", ipa: "taz-ki-ra"},
      {ar: "أمتعة", tr: "Bagaj", ipa: "am-ti-a"},
      {ar: "خروج", tr: "Çıkış", ipa: "khu-ruj"},
      {ar: "دخول", tr: "Giriş", ipa: "du-khul"},
      {ar: "تأخير", tr: "Gecikme", ipa: "ta-khir"},
    ],
    phrases: [
      {ar: "أين بوابة الرحلة؟", tr: "Uçuş kapısı nerede?", ipa: "ay-na ba-wa-bat ar-rih-la?"},
      {ar: "هذه تذكرتي", tr: "Bu benim biletim", ipa: "ha-zi-hi taz-ki-ra-ti"},
      {ar: "أين الأمتعة؟", tr: "Bagaj nerede?", ipa: "ay-na al-am-ti-a?"},
      {ar: "هل الرحلة متأخرة؟", tr: "Uçuş gecikti mi?", ipa: "hal ar-rih-la mu-ta-akh-khi-ra?"},
      {ar: "أين الخروج؟", tr: "Çıkış nerede?", ipa: "ay-na al-khu-ruj?"},
      {ar: "هذا جواز سفري", tr: "Bu benim pasaportum", ipa: "ha-za ja-waz sa-fa-ri"},
    ],
    grammar: "Arapçada “أين” kelimesi “nerede?” anlamındadır ve seyahatte en sık kullanacağın soru kelimelerinden biridir. “هذه” dişil nesneler için “bu”, “هذا” eril nesneler için “bu” demektir. Bilet “تذكرة” dişil olduğu için “هذه تذكرتي” denir.",
    practice: [
      "1. “Çıkış nerede?” sorusunu Arapça söyle.",
      "2. “Bu benim pasaportum” cümlesini yaz.",
      "3. Bagaj ve bilet kelimelerini tekrar et.",
      "4. “Uçuş gecikti mi?” cümlesini ezberle.",
      "5. Havalimanında görevliye soracağın üç kısa soru hazırla.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Taksi ve araç çağırma",
    titleNative: "سيارة الأجرة وطلب سيارة",
    focus: "Bugün Riyad’da taksiye binerken veya uygulamadan araç çağırırken varış yerini söylemeyi, fiyatı sormayı ve kısa yönlendirme yapmayı öğreniyorsun.",
    vocab: [
      {ar: "سيارة أجرة", tr: "Taksi", ipa: "say-ya-rat uj-ra"},
      {ar: "سائق", tr: "Şoför", ipa: "sa-ik"},
      {ar: "عنوان", tr: "Adres", ipa: "un-wan"},
      {ar: "فندق", tr: "Otel", ipa: "fun-duk"},
      {ar: "مركز المدينة", tr: "Şehir merkezi", ipa: "mar-kaz al-ma-di-na"},
      {ar: "يمين", tr: "Sağ", ipa: "ya-min"},
      {ar: "يسار", tr: "Sol", ipa: "ya-sar"},
      {ar: "مستقيم", tr: "Düz", ipa: "mus-ta-kim"},
      {ar: "قريب", tr: "Yakın", ipa: "ka-rib"},
      {ar: "بعيد", tr: "Uzak", ipa: "ba-id"},
    ],
    phrases: [
      {ar: "إلى الفندق من فضلك", tr: "Otele lütfen", ipa: "i-la al-fun-duk min fad-lak"},
      {ar: "كم الأجرة؟", tr: "Ücret ne kadar?", ipa: "kam al-uj-ra?"},
      {ar: "العنوان هنا", tr: "Adres burada", ipa: "al-un-wan hu-na"},
      {ar: "اذهب يمينا", tr: "Sağa gidin", ipa: "iz-hab ya-mi-nan"},
      {ar: "اذهب يسارا", tr: "Sola gidin", ipa: "iz-hab ya-sa-ran"},
      {ar: "توقف هنا من فضلك", tr: "Burada durun lütfen", ipa: "ta-wak-kaf hu-na min fad-lak"},
    ],
    grammar: "Yön tariflerinde kısa emirler kullanmak yeterlidir: “اذهب” = “gidin”, “توقف” = “durun.” Resmî veya nazik ton için sonuna “من فضلك” eklemek iyi olur. Takside uzun cümleler yerine adresi göstermek ve kısa yön kelimeleri kullanmak en pratiktir.",
    practice: [
      "1. “Otele lütfen” cümlesini söyle.",
      "2. “Ücret ne kadar?” sorusunu ezberle.",
      "3. Sağ, sol ve düz kelimelerini Arapça yaz.",
      "4. Şoföre “Burada durun lütfen” demeyi prova et.",
      "5. Otelden şehir merkezine gitmek için iki satırlık diyalog kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Otelde giriş işlemleri",
    titleNative: "تسجيل الدخول في الفندق",
    focus: "Bugün Tunus’ta bir otelde check-in yaparken rezervasyonunu belirtmeyi, pasaport vermeyi ve oda hakkında soru sormayı öğreniyorsun.",
    vocab: [
      {ar: "فندق", tr: "Otel", ipa: "fun-duk"},
      {ar: "حجز", tr: "Rezervasyon", ipa: "hajz"},
      {ar: "غرفة", tr: "Oda", ipa: "ghur-fa"},
      {ar: "مفتاح", tr: "Anahtar", ipa: "mif-tah"},
      {ar: "استقبال", tr: "Resepsiyon", ipa: "is-tik-bal"},
      {ar: "ليلة", tr: "Gece", ipa: "lay-la"},
      {ar: "سرير", tr: "Yatak", ipa: "sa-rir"},
      {ar: "مصعد", tr: "Asansör", ipa: "mis-ad"},
      {ar: "طابق", tr: "Kat", ipa: "ta-bik"},
      {ar: "إفطار", tr: "Kahvaltı", ipa: "if-tar"},
    ],
    phrases: [
      {ar: "عندي حجز", tr: "Rezervasyonum var", ipa: "in-di hajz"},
      {ar: "اسمي جيمس", tr: "Benim adım James", ipa: "is-mi jimz"},
      {ar: "هذه غرفتي؟", tr: "Bu benim odam mı?", ipa: "ha-zi-hi ghur-fa-ti?"},
      {ar: "أين المصعد؟", tr: "Asansör nerede?", ipa: "ay-na al-mis-ad?"},
      {ar: "هل الإفطار مشمول؟", tr: "Kahvaltı dahil mi?", ipa: "hal al-if-tar mash-mul?"},
      {ar: "أحتاج إلى مفتاح", tr: "Anahtara ihtiyacım var", ipa: "ah-taj i-la mif-tah"},
    ],
    grammar: "“عندي” kalıbı otel ve alışveriş durumlarında çok yararlıdır: “عندي حجز” = “Rezervasyonum var.” “مشمول” kelimesi “dahil” anlamında kullanılır. “هل الإفطار مشمول؟” kahvaltının fiyata dahil olup olmadığını sormanın pratik yoludur.",
    practice: [
      "1. Kendi adınla “Rezervasyonum var” cümlesi kur.",
      "2. “Kahvaltı dahil mi?” sorusunu söyle.",
      "3. Oda, anahtar, asansör kelimelerini tekrar et.",
      "4. Resepsiyonda pasaport verirken kullanacağın iki cümle yaz.",
      "5. Otel görevlisiyle 4 satırlık kısa diyalog oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Odada sorun bildirme",
    titleNative: "الإبلاغ عن مشكلة في الغرفة",
    focus: "Bugün Şarm eş-Şeyh’te otel odanda klima, Wi-Fi veya sıcak su sorunu olduğunda bunu nazikçe bildirmeyi öğreniyorsun.",
    vocab: [
      {ar: "الغرفة", tr: "Oda", ipa: "al-ghur-fa"},
      {ar: "المكيف", tr: "Klima", ipa: "al-mu-kay-yif"},
      {ar: "الإنترنت", tr: "İnternet", ipa: "al-in-ter-net"},
      {ar: "الماء الساخن", tr: "Sıcak su", ipa: "al-ma as-sa-khin"},
      {ar: "لا يعمل", tr: "Çalışmıyor", ipa: "la ya-mal"},
      {ar: "بارد", tr: "Soğuk", ipa: "ba-rid"},
      {ar: "ساخن", tr: "Sıcak", ipa: "sa-khin"},
      {ar: "نظيف", tr: "Temiz", ipa: "na-zif"},
      {ar: "وسخ", tr: "Kirli", ipa: "wa-sikh"},
      {ar: "صيانة", tr: "Bakım / teknik servis", ipa: "si-ya-na"},
    ],
    phrases: [
      {ar: "المكيف لا يعمل", tr: "Klima çalışmıyor", ipa: "al-mu-kay-yif la ya-mal"},
      {ar: "الإنترنت ضعيف", tr: "İnternet zayıf", ipa: "al-in-ter-net da-if"},
      {ar: "لا يوجد ماء ساخن", tr: "Sıcak su yok", ipa: "la yu-jad ma sa-khin"},
      {ar: "الغرفة غير نظيفة", tr: "Oda temiz değil", ipa: "al-ghur-fa ghayr na-zi-fa"},
      {ar: "أحتاج إلى صيانة", tr: "Teknik servise ihtiyacım var", ipa: "ah-taj i-la si-ya-na"},
      {ar: "هل يمكنك المساعدة؟", tr: "Yardım edebilir misiniz?", ipa: "hal yum-ki-nuk al-mu-sa-a-da?"},
    ],
    grammar: "“لا يعمل” ifadesi “çalışmıyor” demektir ve cihazlar için çok kullanışlıdır. “غير” kelimesi bir sıfatı olumsuz yapar: “نظيف” temiz, “غير نظيف” temiz değil. Sorun bildirirken sert olmak yerine “هل يمكنك المساعدة؟” gibi nazik bir kapanış eklemek iyi olur.",
    practice: [
      "1. “Klima çalışmıyor” cümlesini söyle.",
      "2. “İnternet zayıf” ifadesini yaz.",
      "3. “Temiz” ve “temiz değil” ifadelerini karşılaştır.",
      "4. Odanda sıcak su olmadığını Arapça bildir.",
      "5. Resepsiyona söylemek için üç cümlelik kısa mesaj hazırla.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kafede sipariş verme",
    titleNative: "الطلب في المقهى",
    focus: "Bugün Beyrut’ta bir kafede kahve, çay veya su sipariş etmeyi öğreniyorsun. Kısa ve kibar sipariş kalıpları seyahatte hemen kullanılır.",
    vocab: [
      {ar: "مقهى", tr: "Kafe", ipa: "maq-ha"},
      {ar: "قهوة", tr: "Kahve", ipa: "qah-wa"},
      {ar: "شاي", tr: "Çay", ipa: "shay"},
      {ar: "ماء", tr: "Su", ipa: "ma"},
      {ar: "حليب", tr: "Süt", ipa: "ha-lib"},
      {ar: "سكر", tr: "Şeker", ipa: "suk-kar"},
      {ar: "كوب", tr: "Bardak", ipa: "kub"},
      {ar: "ساخن", tr: "Sıcak", ipa: "sa-khin"},
      {ar: "بارد", tr: "Soğuk", ipa: "ba-rid"},
      {ar: "فاتورة", tr: "Hesap", ipa: "fa-tu-ra"},
    ],
    phrases: [
      {ar: "أريد قهوة من فضلك", tr: "Kahve istiyorum lütfen", ipa: "u-rid qah-wa min fad-lak"},
      {ar: "شاي بدون سكر", tr: "Şekersiz çay", ipa: "shay bi-du-n suk-kar"},
      {ar: "قهوة مع حليب", tr: "Sütlü kahve", ipa: "qah-wa ma-a ha-lib"},
      {ar: "ماء بارد من فضلك", tr: "Soğuk su lütfen", ipa: "ma ba-rid min fad-lak"},
      {ar: "الحساب من فضلك", tr: "Hesap lütfen", ipa: "al-hi-sab min fad-lak"},
      {ar: "هل عندكم قهوة؟", tr: "Kahveniz var mı?", ipa: "hal in-da-kum qah-wa?"},
    ],
    grammar: "“أريد” kelimesi “istiyorum” demektir ve sipariş verirken en pratik fiildir. “مع” = “ile”, “بدون” = “-siz/-sız” anlamındadır. Böylece “مع حليب” sütlü, “بدون سكر” şekersiz olur.",
    practice: [
      "1. “Kahve istiyorum lütfen” cümlesini söyle.",
      "2. Şekersiz çay siparişi ver.",
      "3. “Sütlü kahve” ifadesini Arapça yaz.",
      "4. “Hesap lütfen” cümlesini ezberle.",
      "5. Bir kafe siparişi için 5 satırlık mini diyalog yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Restoranda yemek seçme",
    titleNative: "اختيار الطعام في المطعم",
    focus: "Bugün Amman’da bir restoranda menü istemeyi, tavsiye sormayı ve temel yemek kelimelerini kullanmayı öğreniyorsun.",
    vocab: [
      {ar: "مطعم", tr: "Restoran", ipa: "mat-am"},
      {ar: "قائمة الطعام", tr: "Menü", ipa: "qa-i-mat at-ta-am"},
      {ar: "طعام", tr: "Yemek", ipa: "ta-am"},
      {ar: "دجاج", tr: "Tavuk", ipa: "da-jaj"},
      {ar: "لحم", tr: "Et", ipa: "lahm"},
      {ar: "سمك", tr: "Balık", ipa: "sa-mak"},
      {ar: "أرز", tr: "Pirinç", ipa: "urz"},
      {ar: "سلطة", tr: "Salata", ipa: "sa-la-ta"},
      {ar: "خبز", tr: "Ekmek", ipa: "khubz"},
      {ar: "لذيذ", tr: "Lezzetli", ipa: "la-ziz"},
    ],
    phrases: [
      {ar: "أريد قائمة الطعام", tr: "Menü istiyorum", ipa: "u-rid qa-i-mat at-ta-am"},
      {ar: "ماذا تنصح؟", tr: "Ne tavsiye edersiniz?", ipa: "ma-za tan-sah?"},
      {ar: "أريد دجاجا مع أرز", tr: "Pirinçli tavuk istiyorum", ipa: "u-rid da-ja-jan ma-a urz"},
      {ar: "هل عندكم سمك؟", tr: "Balığınız var mı?", ipa: "hal in-da-kum sa-mak?"},
      {ar: "الطعام لذيذ", tr: "Yemek lezzetli", ipa: "at-ta-am la-ziz"},
      {ar: "أريد خبزا من فضلك", tr: "Ekmek istiyorum lütfen", ipa: "u-rid khub-zan min fad-lak"},
    ],
    grammar: "Restoranda “أريد” yine ana fiildir. “مع” ile yemekleri birleştirebilirsin: tavuk ile pirinç, et ile salata gibi. “ماذا تنصح؟” tek başına çok doğal bir soru olup “Ne önerirsiniz?” anlamına gelir.",
    practice: [
      "1. “Menü istiyorum” cümlesini Arapça söyle.",
      "2. Tavuk, et, balık kelimelerini tekrar et.",
      "3. Garsona “Ne tavsiye edersiniz?” diye sor.",
      "4. “Yemek lezzetli” cümlesini yaz.",
      "5. Kendi restoran siparişini üç cümleyle oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Özel beslenme ve alerjiler",
    titleNative: "النظام الغذائي والحساسية",
    focus: "Bugün Dubai’de restoranda alerji, vejetaryen seçenek veya içerik sormayı öğreniyorsun. Bu ders sağlık ve rahat yemek seçimi için önemlidir.",
    vocab: [
      {ar: "حساسية", tr: "Alerji", ipa: "ha-sa-si-ya"},
      {ar: "عندي حساسية", tr: "Alerjim var", ipa: "in-di ha-sa-si-ya"},
      {ar: "بدون", tr: "-siz/-sız", ipa: "bi-du-n"},
      {ar: "لحم", tr: "Et", ipa: "lahm"},
      {ar: "حليب", tr: "Süt", ipa: "ha-lib"},
      {ar: "بيض", tr: "Yumurta", ipa: "bayd"},
      {ar: "مكسرات", tr: "Kuruyemiş", ipa: "mu-kas-sa-rat"},
      {ar: "نباتي", tr: "Vejetaryen", ipa: "na-ba-ti"},
      {ar: "حلال", tr: "Helal", ipa: "ha-lal"},
      {ar: "مكونات", tr: "İçindekiler", ipa: "mu-kaw-wi-nat"},
    ],
    phrases: [
      {ar: "عندي حساسية من المكسرات", tr: "Kuruyemiş alerjim var", ipa: "in-di ha-sa-si-ya min al-mu-kas-sa-rat"},
      {ar: "هل هذا نباتي؟", tr: "Bu vejetaryen mi?", ipa: "hal ha-za na-ba-ti?"},
      {ar: "بدون لحم من فضلك", tr: "Etsiz lütfen", ipa: "bi-du-n lahm min fad-lak"},
      {ar: "هل فيه حليب؟", tr: "İçinde süt var mı?", ipa: "hal fi-hi ha-lib?"},
      {ar: "هل الطعام حلال؟", tr: "Yemek helal mi?", ipa: "hal at-ta-am ha-lal?"},
      {ar: "أريد شيئا بسيطا", tr: "Basit bir şey istiyorum", ipa: "u-rid shay-an ba-si-tan"},
    ],
    grammar: "“فيه” günlük konuşmada “içinde var” gibi kullanılır: “هل فيه حليب؟” = “İçinde süt var mı?” “عندي حساسية من...” kalıbı “... alerjim var” demektir. Alerji söz konusu olduğunda cümleyi kısa ve net söylemek en güvenlisidir.",
    practice: [
      "1. “Kuruyemiş alerjim var” cümlesini söyle.",
      "2. “Bu vejetaryen mi?” sorusunu yaz.",
      "3. “Etsiz lütfen” ifadesini tekrar et.",
      "4. Süt, yumurta, et kelimelerini Arapça yaz.",
      "5. Garsona içerik sormak için üç soru oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Pazarda alışveriş",
    titleNative: "التسوق في السوق",
    focus: "Bugün Marakeş çarşısında ürün sormayı, fiyat öğrenmeyi ve basit pazarlık ifadelerini kullanmayı öğreniyorsun. Nazik ama kararlı olmak önemlidir.",
    vocab: [
      {ar: "سوق", tr: "Pazar / çarşı", ipa: "suq"},
      {ar: "كم", tr: "Kaç / ne kadar", ipa: "kam"},
      {ar: "سعر", tr: "Fiyat", ipa: "si-r"},
      {ar: "غالي", tr: "Pahalı", ipa: "gha-li"},
      {ar: "رخيص", tr: "Ucuz", ipa: "ra-khis"},
      {ar: "هذا", tr: "Bu", ipa: "ha-za"},
      {ar: "ذلك", tr: "Şu / o", ipa: "za-lik"},
      {ar: "جميل", tr: "Güzel", ipa: "ja-mil"},
      {ar: "أريد", tr: "İstiyorum", ipa: "u-rid"},
      {ar: "آخر", tr: "Başka", ipa: "a-khar"},
    ],
    phrases: [
      {ar: "كم سعر هذا؟", tr: "Bunun fiyatı ne kadar?", ipa: "kam si-r ha-za?"},
      {ar: "هذا غالي", tr: "Bu pahalı", ipa: "ha-za gha-li"},
      {ar: "هل يوجد سعر أفضل؟", tr: "Daha iyi fiyat var mı?", ipa: "hal yu-jad si-r af-dal?"},
      {ar: "أريد هذا", tr: "Bunu istiyorum", ipa: "u-rid ha-za"},
      {ar: "لا أريد، شكرا", tr: "İstemiyorum, teşekkürler", ipa: "la u-rid, şuk-ran"},
      {ar: "هل عندك لون آخر؟", tr: "Başka renginiz var mı?", ipa: "hal in-dak lawn a-khar?"},
    ],
    grammar: "“هذا” eril veya genel “bu” için kullanılır ve pazarda ürün gösterirken çok işe yarar. Pazarlıkta “غالي” demek doğaldır ama gülümsemek ve “من فضلك” eklemek tonu yumuşatır. “هل يوجد...؟” kalıbı “var mı?” sorusunun daha genel bir yoludur.",
    practice: [
      "1. “Bunun fiyatı ne kadar?” sorusunu söyle.",
      "2. “Bu pahalı” cümlesini yaz.",
      "3. “Daha iyi fiyat var mı?” ifadesini tekrar et.",
      "4. Bir ürünü gösterip “Bunu istiyorum” de.",
      "5. Pazarda 6 satırlık kısa pazarlık diyaloğu yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Renkler ve bedenler",
    titleNative: "الألوان والمقاسات",
    focus: "Bugün Tunus medinasında kıyafet veya hediyelik eşya bakarken renk, beden ve seçenek sormayı öğreniyorsun.",
    vocab: [
      {ar: "لون", tr: "Renk", ipa: "lawn"},
      {ar: "أحمر", tr: "Kırmızı", ipa: "ah-mar"},
      {ar: "أزرق", tr: "Mavi", ipa: "az-rak"},
      {ar: "أخضر", tr: "Yeşil", ipa: "akh-dar"},
      {ar: "أسود", tr: "Siyah", ipa: "as-wad"},
      {ar: "أبيض", tr: "Beyaz", ipa: "ab-yad"},
      {ar: "مقاس", tr: "Beden", ipa: "ma-qas"},
      {ar: "كبير", tr: "Büyük", ipa: "ka-bir"},
      {ar: "صغير", tr: "Küçük", ipa: "sa-ghir"},
      {ar: "مناسب", tr: "Uygun", ipa: "mu-na-sib"},
    ],
    phrases: [
      {ar: "أريد اللون الأزرق", tr: "Mavi rengi istiyorum", ipa: "u-rid al-lawn al-az-rak"},
      {ar: "هل عندك مقاس كبير؟", tr: "Büyük beden var mı?", ipa: "hal in-dak ma-qas ka-bir?"},
      {ar: "هذا صغير جدا", tr: "Bu çok küçük", ipa: "ha-za sa-ghir jid-dan"},
      {ar: "هذا مناسب", tr: "Bu uygun", ipa: "ha-za mu-na-sib"},
      {ar: "أريد شيئا أبيض", tr: "Beyaz bir şey istiyorum", ipa: "u-rid shay-an ab-yad"},
      {ar: "هل يوجد لون آخر؟", tr: "Başka renk var mı?", ipa: "hal yu-jad lawn a-khar?"},
    ],
    grammar: "Arapçada sıfat genellikle isimden sonra gelir: “لون أزرق” = mavi renk. “جدا” kelimesi sıfattan sonra gelir ve “çok” anlamı verir: “صغير جدا” = çok küçük. Alışverişte bu yapı oldukça pratiktir.",
    practice: [
      "1. Beş rengi Arapça söyle.",
      "2. “Büyük beden var mı?” sorusunu yaz.",
      "3. “Bu çok küçük” cümlesini tekrar et.",
      "4. Mavi bir ürün istediğini söyle.",
      "5. Bir kıyafet mağazasında 5 satırlık diyalog kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Toplu taşıma ve biletler",
    titleNative: "المواصلات العامة والتذاكر",
    focus: "Bugün Kahire’de metroya veya otobüse binerken bilet almak, durak sormak ve doğru yönü bulmak üzerine çalışıyorsun.",
    vocab: [
      {ar: "مترو", tr: "Metro", ipa: "mit-ro"},
      {ar: "حافلة", tr: "Otobüs", ipa: "ha-fi-la"},
      {ar: "تذكرة", tr: "Bilet", ipa: "taz-ki-ra"},
      {ar: "محطة", tr: "İstasyon / durak", ipa: "ma-hat-ta"},
      {ar: "خط", tr: "Hat", ipa: "khatt"},
      {ar: "اتجاه", tr: "Yön", ipa: "it-ti-jah"},
      {ar: "ذهاب", tr: "Gidiş", ipa: "za-hab"},
      {ar: "عودة", tr: "Dönüş", ipa: "aw-da"},
      {ar: "قريب", tr: "Yakın", ipa: "qa-rib"},
      {ar: "بعيد", tr: "Uzak", ipa: "ba-id"},
    ],
    phrases: [
      {ar: "أريد تذكرة واحدة", tr: "Bir bilet istiyorum", ipa: "u-rid taz-ki-ra wa-hi-da"},
      {ar: "أين محطة المترو؟", tr: "Metro istasyonu nerede?", ipa: "ay-na ma-hat-tat al-mit-ro?"},
      {ar: "هل هذه الحافلة إلى المركز؟", tr: "Bu otobüs merkeze gider mi?", ipa: "hal ha-zi-hi al-ha-fi-la i-la al-mar-kaz?"},
      {ar: "أي خط أحتاج؟", tr: "Hangi hatta ihtiyacım var?", ipa: "ay-yu khatt ah-taj?"},
      {ar: "هل هذا الاتجاه صحيح؟", tr: "Bu yön doğru mu?", ipa: "hal ha-za al-it-ti-jah sa-hih?"},
      {ar: "أريد تذكرة ذهاب وعودة", tr: "Gidiş-dönüş bilet istiyorum", ipa: "u-rid taz-ki-rat za-hab wa aw-da"},
    ],
    grammar: "“إلى” yön belirtirken “-e/-a” anlamı verir: “إلى المركز” = merkeze. Toplu taşımada “هل هذا صحيح؟” yani “Bu doğru mu?” sorusu çok kullanışlıdır. Bilmediğin yerde yönü doğrulamak hata yapmanı önler.",
    practice: [
      "1. “Bir bilet istiyorum” cümlesini söyle.",
      "2. “Metro istasyonu nerede?” sorusunu yaz.",
      "3. “Bu yön doğru mu?” ifadesini ezberle.",
      "4. Otobüs, metro, durak kelimelerini tekrar et.",
      "5. Merkeze giden otobüsü sormak için kısa bir cümle kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Yol tarifi sorma",
    titleNative: "السؤال عن الاتجاهات",
    focus: "Bugün Eski Şam’da yürürken cami, müze veya pazar yönünü sormayı öğreniyorsun. Harita olsa bile yerel birine kısa soru sormak çok işe yarar.",
    vocab: [
      {ar: "أين", tr: "Nerede", ipa: "ay-na"},
      {ar: "شارع", tr: "Sokak / cadde", ipa: "sha-ri"},
      {ar: "يمين", tr: "Sağ", ipa: "ya-min"},
      {ar: "يسار", tr: "Sol", ipa: "ya-sar"},
      {ar: "مستقيم", tr: "Düz", ipa: "mus-ta-qim"},
      {ar: "قريب", tr: "Yakın", ipa: "qa-rib"},
      {ar: "بعيد", tr: "Uzak", ipa: "ba-id"},
      {ar: "مسجد", tr: "Cami", ipa: "mas-jid"},
      {ar: "متحف", tr: "Müze", ipa: "mat-haf"},
      {ar: "ساحة", tr: "Meydan", ipa: "sa-ha"},
    ],
    phrases: [
      {ar: "أين المسجد؟", tr: "Cami nerede?", ipa: "ay-na al-mas-jid?"},
      {ar: "أين المتحف من فضلك؟", tr: "Müze nerede lütfen?", ipa: "ay-na al-mat-haf min fad-lak?"},
      {ar: "اذهب مستقيما", tr: "Düz gidin", ipa: "iz-hab mus-ta-qi-man"},
      {ar: "ثم إلى اليمين", tr: "Sonra sağa", ipa: "thum-ma i-la al-ya-min"},
      {ar: "هل هو قريب؟", tr: "Yakın mı?", ipa: "hal hu-wa qa-rib?"},
      {ar: "أنا تائه", tr: "Kayboldum", ipa: "a-na ta-ih"},
    ],
    grammar: "Yol tariflerinde “ثم” kelimesi “sonra” demektir ve adımları bağlar. “اذهب مستقيما ثم إلى اليمين” = “Düz gidin, sonra sağa.” “أنا تائه” erkek konuşan için “Kayboldum” demektir; kadın konuşan “أنا تائهة” diyebilir.",
    practice: [
      "1. “Müze nerede lütfen?” cümlesini söyle.",
      "2. Sağ, sol, düz kelimelerini tekrar et.",
      "3. “Kayboldum” cümlesini yaz.",
      "4. Bir camiye yol sormak için iki cümle kur.",
      "5. Birine meydanı tarif eden kısa bir cevap yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Zaman ve saat",
    titleNative: "الوقت والساعة",
    focus: "Bugün Abu Dabi’de tur saatini, restoran rezervasyonunu veya müze kapanışını anlamak için saat ve zaman ifadelerini öğreniyorsun.",
    vocab: [
      {ar: "وقت", tr: "Zaman", ipa: "waqt"},
      {ar: "ساعة", tr: "Saat", ipa: "sa-a"},
      {ar: "اليوم", tr: "Bugün", ipa: "al-yawm"},
      {ar: "غدا", tr: "Yarın", ipa: "gha-dan"},
      {ar: "أمس", tr: "Dün", ipa: "ams"},
      {ar: "صباحا", tr: "Sabah", ipa: "sa-ba-han"},
      {ar: "مساء", tr: "Akşam", ipa: "ma-sa-an"},
      {ar: "الآن", tr: "Şimdi", ipa: "al-an"},
      {ar: "بعد", tr: "Sonra", ipa: "ba-d"},
      {ar: "قبل", tr: "Önce", ipa: "qabl"},
    ],
    phrases: [
      {ar: "كم الساعة؟", tr: "Saat kaç?", ipa: "kam as-sa-a?"},
      {ar: "الساعة واحدة", tr: "Saat bir", ipa: "as-sa-a wa-hi-da"},
      {ar: "الساعة ثلاثة", tr: "Saat üç", ipa: "as-sa-a tha-la-tha"},
      {ar: "متى يفتح؟", tr: "Ne zaman açılıyor?", ipa: "ma-ta yaf-tah?"},
      {ar: "متى يغلق؟", tr: "Ne zaman kapanıyor?", ipa: "ma-ta yugh-lak?"},
      {ar: "أراك غدا", tr: "Yarın görüşürüz", ipa: "a-ra-ka gha-dan"},
    ],
    grammar: "“متى” kelimesi “ne zaman?” anlamına gelir. Açılmak için “يفتح”, kapanmak için “يغلق” kullanılır. Saat söylerken “الساعة” ile başlamak temel ve anlaşılır bir yapıdır.",
    practice: [
      "1. “Saat kaç?” sorusunu Arapça söyle.",
      "2. “Ne zaman açılıyor?” sorusunu yaz.",
      "3. Bugün, yarın, dün kelimelerini tekrar et.",
      "4. “Saat üç” cümlesini söyle.",
      "5. Bir müzenin kapanış saatini sormak için kısa diyalog kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Günler ve plan yapmak",
    titleNative: "الأيام ووضع الخطط",
    focus: "Bugün Doha’da tur, akşam yemeği veya müze ziyareti planlarken günleri ve basit plan cümlelerini kullanmayı öğreniyorsun.",
    vocab: [
      {ar: "السبت", tr: "Cumartesi", ipa: "as-sabt"},
      {ar: "الأحد", tr: "Pazar", ipa: "al-a-had"},
      {ar: "الاثنين", tr: "Pazartesi", ipa: "al-ith-nayn"},
      {ar: "الثلاثاء", tr: "Salı", ipa: "ath-thu-la-tha"},
      {ar: "الأربعاء", tr: "Çarşamba", ipa: "al-ar-bi-a"},
      {ar: "الخميس", tr: "Perşembe", ipa: "al-kha-mis"},
      {ar: "الجمعة", tr: "Cuma", ipa: "al-jum-a"},
      {ar: "موعد", tr: "Randevu", ipa: "maw-id"},
      {ar: "خطة", tr: "Plan", ipa: "khut-ta"},
      {ar: "رحلة", tr: "Gezi / yolculuk", ipa: "rih-la"},
    ],
    phrases: [
      {ar: "عندي موعد يوم الاثنين", tr: "Pazartesi randevum var", ipa: "in-di maw-id yawm al-ith-nayn"},
      {ar: "أريد رحلة يوم الجمعة", tr: "Cuma günü gezi istiyorum", ipa: "u-rid rih-la yawm al-jum-a"},
      {ar: "هل أنت متفرغ غدا؟", tr: "Yarın müsait misin?", ipa: "hal anta mu-ta-far-righ gha-dan?"},
      {ar: "الخطة جيدة", tr: "Plan iyi", ipa: "al-khut-ta jay-yi-da"},
      {ar: "نلتقي مساء الخميس", tr: "Perşembe akşamı buluşuyoruz", ipa: "nal-ta-qi ma-sa al-kha-mis"},
      {ar: "اليوم الأحد", tr: "Bugün pazar", ipa: "al-yawm al-a-had"},
    ],
    grammar: "Gün adlarından önce çoğu zaman “يوم” yani “gün” kelimesi kullanılır: “يوم الجمعة” = cuma günü. “عندي موعد” randevum var demektir. Plan yaparken gün + zaman ifadesi yeterince anlaşılır olur.",
    practice: [
      "1. Haftanın günlerini Arapça sırayla söyle.",
      "2. “Cuma günü gezi istiyorum” cümlesini yaz.",
      "3. “Pazartesi randevum var” cümlesini tekrar et.",
      "4. Bir arkadaşla Perşembe akşamı buluşma cümlesi kur.",
      "5. Yarın müsait olup olmadığını soran bir cümle söyle.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Telefon ve internet",
    titleNative: "الهاتف والإنترنت",
    focus: "Bugün Ürdün’de SIM kart almak, Wi-Fi sormak veya telefonunun şarjını anlatmak için gerekli kelimeleri öğreniyorsun.",
    vocab: [
      {ar: "هاتف", tr: "Telefon", ipa: "ha-tif"},
      {ar: "شاحن", tr: "Şarj aleti", ipa: "sha-hin"},
      {ar: "بطارية", tr: "Pil", ipa: "bat-ta-ri-ya"},
      {ar: "إنترنت", tr: "İnternet", ipa: "in-ter-net"},
      {ar: "واي فاي", tr: "Wi-Fi", ipa: "wai fai"},
      {ar: "شريحة", tr: "SIM kart", ipa: "sha-ri-ha"},
      {ar: "رقم", tr: "Numara", ipa: "ra-qam"},
      {ar: "رسالة", tr: "Mesaj", ipa: "ri-sa-la"},
      {ar: "اتصال", tr: "Arama / bağlantı", ipa: "it-ti-sal"},
      {ar: "كلمة السر", tr: "Şifre", ipa: "ka-li-mat as-sirr"},
    ],
    phrases: [
      {ar: "ما كلمة السر للواي فاي؟", tr: "Wi-Fi şifresi nedir?", ipa: "ma ka-li-mat as-sirr lil-wai fai?"},
      {ar: "أحتاج إلى شاحن", tr: "Şarj aletine ihtiyacım var", ipa: "ah-taj i-la sha-hin"},
      {ar: "أريد شريحة إنترنت", tr: "İnternet SIM kartı istiyorum", ipa: "u-rid sha-ri-hat in-ter-net"},
      {ar: "بطارية هاتفي ضعيفة", tr: "Telefonumun pili zayıf", ipa: "bat-ta-ri-yat ha-ti-fi da-i-fa"},
      {ar: "هل عندك اتصال؟", tr: "Bağlantın var mı?", ipa: "hal in-dak it-ti-sal?"},
      {ar: "هذا رقمي", tr: "Bu benim numaram", ipa: "ha-za ra-qa-mi"},
    ],
    grammar: "“ما” bazen “ne?” anlamında kullanılır: “ما كلمة السر؟” = “Şifre nedir?” Sahiplik için kelimenin sonuna ek gelir: “هاتفي” = telefonum, “رقمي” = numaram. Bu ekleri kalıp olarak öğrenmek yeterlidir.",
    practice: [
      "1. “Wi-Fi şifresi nedir?” sorusunu söyle.",
      "2. “Şarj aletine ihtiyacım var” cümlesini yaz.",
      "3. Telefon, şifre, numara kelimelerini tekrar et.",
      "4. “Bu benim numaram” ifadesini ezberle.",
      "5. SIM kart almak için kısa bir mağaza diyaloğu yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Acil durumlar",
    titleNative: "حالات الطوارئ",
    focus: "Bugün Kahire veya Rabat gibi kalabalık bir şehirde kayıp eşya, hastalık veya güvenlik durumunda yardım istemeyi öğreniyorsun. Kısa, net ve sakin ifadeler kullanmak önemlidir.",
    vocab: [
      {ar: "طوارئ", tr: "Acil durum", ipa: "ta-wa-ri"},
      {ar: "شرطة", tr: "Polis", ipa: "shur-ta"},
      {ar: "مستشفى", tr: "Hastane", ipa: "mus-tash-fa"},
      {ar: "طبيب", tr: "Doktor", ipa: "ta-bib"},
      {ar: "مريض", tr: "Hasta", ipa: "ma-rid"},
      {ar: "مساعدة", tr: "Yardım", ipa: "mu-sa-a-da"},
      {ar: "سرقة", tr: "Hırsızlık", ipa: "sa-ri-qa"},
      {ar: "ضائع", tr: "Kayıp", ipa: "da-i"},
      {ar: "خطر", tr: "Tehlike", ipa: "kha-tar"},
      {ar: "اتصل", tr: "Ara / telefon et", ipa: "it-ta-sil"},
    ],
    phrases: [
      {ar: "أحتاج إلى طبيب", tr: "Doktora ihtiyacım var", ipa: "ah-taj i-la ta-bib"},
      {ar: "اتصل بالشرطة من فضلك", tr: "Lütfen polisi ara", ipa: "it-ta-sil bish-shur-ta min fad-lak"},
      {ar: "أين المستشفى؟", tr: "Hastane nerede?", ipa: "ay-na al-mus-tash-fa?"},
      {ar: "حقيبتي ضائعة", tr: "Çantam kayıp", ipa: "ha-qi-ba-ti da-i-a"},
      {ar: "أنا مريض", tr: "Hastayım", ipa: "a-na ma-rid"},
      {ar: "هذا خطر", tr: "Bu tehlikeli", ipa: "ha-za kha-tar"},
    ],
    grammar: "Acil durumlarda uzun cümle kurmana gerek yoktur. “أحتاج إلى...” ve “أين...؟” kalıpları en hızlı yardım isteme yollarıdır. “حقيبتي” kelimesindeki “ـي” eki “benim” anlamı verir: çantam.",
    practice: [
      "1. “Doktora ihtiyacım var” cümlesini söyle.",
      "2. “Hastane nerede?” sorusunu yaz.",
      "3. “Çantam kayıp” ifadesini tekrar et.",
      "4. Polis, doktor, hastane kelimelerini ezberle.",
      "5. Acil durumda kullanacağın üç kısa cümle hazırla.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Eczanede",
    titleNative: "في الصيدلية",
    focus: "Bugün Beyrut’ta eczaneye gidip baş ağrısı, mide sorunu veya basit ilaç ihtiyacını anlatmayı öğreniyorsun.",
    vocab: [
      {ar: "صيدلية", tr: "Eczane", ipa: "say-da-li-ya"},
      {ar: "دواء", tr: "İlaç", ipa: "da-wa"},
      {ar: "ألم", tr: "Ağrı", ipa: "a-lam"},
      {ar: "رأس", tr: "Baş", ipa: "ras"},
      {ar: "معدة", tr: "Mide", ipa: "mi-da"},
      {ar: "برد", tr: "Soğuk algınlığı", ipa: "bard"},
      {ar: "حمى", tr: "Ateş", ipa: "hum-ma"},
      {ar: "جرعة", tr: "Doz", ipa: "jur-a"},
      {ar: "وصفة", tr: "Reçete", ipa: "was-fa"},
      {ar: "كم مرة", tr: "Kaç kere", ipa: "kam mar-ra"},
    ],
    phrases: [
      {ar: "أين الصيدلية؟", tr: "Eczane nerede?", ipa: "ay-na as-say-da-li-ya?"},
      {ar: "عندي ألم في الرأس", tr: "Başım ağrıyor", ipa: "in-di a-lam fi ar-ras"},
      {ar: "عندي ألم في المعدة", tr: "Midem ağrıyor", ipa: "in-di a-lam fi al-mi-da"},
      {ar: "أحتاج إلى دواء", tr: "İlaca ihtiyacım var", ipa: "ah-taj i-la da-wa"},
      {ar: "هل أحتاج إلى وصفة؟", tr: "Reçeteye ihtiyacım var mı?", ipa: "hal ah-taj i-la was-fa?"},
      {ar: "كم مرة في اليوم؟", tr: "Günde kaç kere?", ipa: "kam mar-ra fi al-yawm?"},
    ],
    grammar: "“في” burada “-de/-da” veya “içinde” anlamındadır. “عندي ألم في...” kalıbı “... ağrım var” demektir. Eczanede ilaç kullanımını mutlaka “كم مرة في اليوم؟” diye sorarak netleştirebilirsin.",
    practice: [
      "1. “Eczane nerede?” sorusunu söyle.",
      "2. “Başım ağrıyor” cümlesini yaz.",
      "3. “Günde kaç kere?” ifadesini tekrar et.",
      "4. Baş, mide, ilaç kelimelerini Arapça söyle.",
      "5. Eczacıyla 6 satırlık kısa diyalog oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Para, ödeme ve kart",
    titleNative: "المال والدفع والبطاقة",
    focus: "Bugün Dubai’de mağazada veya restoranda ödeme yaparken nakit, kart, fiş ve para üstü ifadelerini kullanmayı öğreniyorsun.",
    vocab: [
      {ar: "مال", tr: "Para", ipa: "mal"},
      {ar: "نقود", tr: "Nakit", ipa: "nu-qud"},
      {ar: "بطاقة", tr: "Kart", ipa: "bi-ta-qa"},
      {ar: "دفع", tr: "Ödeme", ipa: "daf"},
      {ar: "فاتورة", tr: "Fatura / hesap", ipa: "fa-tu-ra"},
      {ar: "إيصال", tr: "Fiş", ipa: "i-sal"},
      {ar: "باقي", tr: "Para üstü", ipa: "ba-qi"},
      {ar: "مصرف", tr: "Banka", ipa: "mas-rif"},
      {ar: "صراف آلي", tr: "ATM", ipa: "sar-raf a-li"},
      {ar: "عملة", tr: "Para birimi", ipa: "um-la"},
    ],
    phrases: [
      {ar: "هل أستطيع الدفع بالبطاقة؟", tr: "Kartla ödeyebilir miyim?", ipa: "hal as-ta-ti ad-daf bil-bi-ta-qa?"},
      {ar: "أريد الإيصال من فضلك", tr: "Fiş istiyorum lütfen", ipa: "u-rid al-i-sal min fad-lak"},
      {ar: "هل عندك باقي؟", tr: "Para üstünüz var mı?", ipa: "hal in-dak ba-qi?"},
      {ar: "أين الصراف الآلي؟", tr: "ATM nerede?", ipa: "ay-na as-sar-raf al-a-li?"},
      {ar: "أدفع نقدا", tr: "Nakit ödüyorum", ipa: "ad-fa naq-dan"},
      {ar: "الحساب صحيح", tr: "Hesap doğru", ipa: "al-hi-sab sa-hih"},
    ],
    grammar: "“بالـ” yapısı “ile” anlamı verebilir: “بالبطاقة” = kartla. “هل أستطيع...؟” kalıbı “... yapabilir miyim?” demektir ve kibar isteklerde çok kullanışlıdır. Ödeme anında bu kalıp güvenli ve naziktir.",
    practice: [
      "1. “Kartla ödeyebilir miyim?” cümlesini söyle.",
      "2. “ATM nerede?” sorusunu yaz.",
      "3. “Fiş istiyorum lütfen” ifadesini tekrar et.",
      "4. Nakit ve kart kelimelerini karşılaştır.",
      "5. Restoranda ödeme yapmak için kısa bir diyalog yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Turistik yerler ve bilet gişesi",
    titleNative: "الأماكن السياحية وشباك التذاكر",
    focus: "Bugün Petra, Giza veya Louvre Abu Dhabi gibi turistik bir yerde giriş bileti, saat ve rehberli tur sormayı öğreniyorsun.",
    vocab: [
      {ar: "مكان سياحي", tr: "Turistik yer", ipa: "ma-kan si-ya-hi"},
      {ar: "تذكرة دخول", tr: "Giriş bileti", ipa: "taz-ki-rat du-khul"},
      {ar: "متحف", tr: "Müze", ipa: "mat-haf"},
      {ar: "قلعة", tr: "Kale", ipa: "qal-a"},
      {ar: "آثار", tr: "Tarihi kalıntılar", ipa: "a-thar"},
      {ar: "دليل", tr: "Rehber", ipa: "da-lil"},
      {ar: "جولة", tr: "Tur", ipa: "jaw-la"},
      {ar: "تصوير", tr: "Fotoğraf çekimi", ipa: "tas-wir"},
      {ar: "ممنوع", tr: "Yasak", ipa: "mam-nu"},
      {ar: "مسموح", tr: "İzinli", ipa: "mas-muh"},
    ],
    phrases: [
      {ar: "أريد تذكرة دخول", tr: "Giriş bileti istiyorum", ipa: "u-rid taz-ki-rat du-khul"},
      {ar: "كم سعر الدخول؟", tr: "Giriş ücreti ne kadar?", ipa: "kam si-r ad-du-khul?"},
      {ar: "هل التصوير مسموح؟", tr: "Fotoğraf çekmek serbest mi?", ipa: "hal at-tas-wir mas-muh?"},
      {ar: "هل يوجد دليل؟", tr: "Rehber var mı?", ipa: "hal yu-jad da-lil?"},
      {ar: "متى تبدأ الجولة؟", tr: "Tur ne zaman başlıyor?", ipa: "ma-ta tab-da al-jaw-la?"},
      {ar: "التصوير ممنوع هنا", tr: "Burada fotoğraf yasak", ipa: "at-tas-wir mam-nu hu-na"},
    ],
    grammar: "“Müsaade var” anlamında “مسموح”, “yasak” anlamında “ممنوع” kullanılır. “هل التصوير مسموح؟” çok pratik ve kibar bir sorudur. Turistik yerlerde fotoğraf kurallarını sormak saygılı bir davranıştır.",
    practice: [
      "1. “Giriş bileti istiyorum” cümlesini söyle.",
      "2. “Fotoğraf çekmek serbest mi?” sorusunu yaz.",
      "3. “Tur ne zaman başlıyor?” ifadesini tekrar et.",
      "4. Müze, kale, rehber kelimelerini ezberle.",
      "5. Bilet gişesinde 5 satırlık diyalog oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Yerel insanlarla küçük sohbet",
    titleNative: "محادثة قصيرة مع السكان المحليين",
    focus: "Bugün Amman’da bir taksi şoförüyle, dükkân sahibiyle veya turda tanıştığın biriyle basit küçük sohbet kurmayı öğreniyorsun.",
    vocab: [
      {ar: "جميل", tr: "Güzel", ipa: "ja-mil"},
      {ar: "مدينة", tr: "Şehir", ipa: "ma-di-na"},
      {ar: "بلد", tr: "Ülke", ipa: "ba-lad"},
      {ar: "ناس", tr: "İnsanlar", ipa: "nas"},
      {ar: "طقس", tr: "Hava durumu", ipa: "taqs"},
      {ar: "حار", tr: "Sıcak", ipa: "har"},
      {ar: "بارد", tr: "Soğuk", ipa: "ba-rid"},
      {ar: "أحب", tr: "Seviyorum", ipa: "u-hibb"},
      {ar: "أول مرة", tr: "İlk kez", ipa: "aw-wal mar-ra"},
      {ar: "زيارة", tr: "Ziyaret", ipa: "zi-ya-ra"},
    ],
    phrases: [
      {ar: "هذه المدينة جميلة", tr: "Bu şehir güzel", ipa: "ha-zi-hi al-ma-di-na ja-mi-la"},
      {ar: "الناس لطفاء", tr: "İnsanlar nazik", ipa: "an-nas lu-ta-fa"},
      {ar: "هذه أول مرة لي هنا", tr: "Buraya ilk gelişim", ipa: "ha-zi-hi aw-wal mar-ra li hu-na"},
      {ar: "أحب الطعام العربي", tr: "Arap yemeklerini seviyorum", ipa: "u-hibb at-ta-am al-a-ra-bi"},
      {ar: "الطقس حار اليوم", tr: "Bugün hava sıcak", ipa: "at-taqs har al-yawm"},
      {ar: "أنا أزور البلد", tr: "Ülkeyi ziyaret ediyorum", ipa: "a-na a-zur al-ba-lad"},
    ],
    grammar: "“أحب” fiili “seviyorum” demektir ve ardından isim gelir. “أحب الطعام العربي” seyahatte sıcak bir sohbet başlatır. Yerel kültür hakkında olumlu ve basit cümleler kurmak insanlar üzerinde iyi izlenim bırakır.",
    practice: [
      "1. “Bu şehir güzel” cümlesini söyle.",
      "2. “Arap yemeklerini seviyorum” cümlesini yaz.",
      "3. “Buraya ilk gelişim” ifadesini tekrar et.",
      "4. Hava sıcak veya soğuk demeyi prova et.",
      "5. Yerel biriyle 6 satırlık küçük sohbet yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Davet, öneri ve sosyal plan",
    titleNative: "الدعوة والاقتراح والخطة الاجتماعية",
    focus: "Bugün Beyrut’ta yeni tanıştığın biriyle kahve içmeyi, yürüyüş yapmayı veya tekrar buluşmayı önermeyi öğreniyorsun.",
    vocab: [
      {ar: "دعوة", tr: "Davet", ipa: "da-wa"},
      {ar: "قهوة", tr: "Kahve", ipa: "qah-wa"},
      {ar: "مطعم", tr: "Restoran", ipa: "mat-am"},
      {ar: "نزهة", tr: "Gezinti", ipa: "nuz-ha"},
      {ar: "اليوم", tr: "Bugün", ipa: "al-yawm"},
      {ar: "الليلة", tr: "Bu gece", ipa: "al-lay-la"},
      {ar: "غدا", tr: "Yarın", ipa: "gha-dan"},
      {ar: "ممتاز", tr: "Harika", ipa: "mum-taz"},
      {ar: "فكرة", tr: "Fikir", ipa: "fik-ra"},
      {ar: "مشغول", tr: "Meşgul", ipa: "mash-ghul"},
    ],
    phrases: [
      {ar: "هل تريد قهوة؟", tr: "Kahve ister misin?", ipa: "hal tu-rid qah-wa?"},
      {ar: "نلتقي الليلة؟", tr: "Bu gece buluşalım mı?", ipa: "nal-ta-qi al-lay-la?"},
      {ar: "هذه فكرة ممتازة", tr: "Bu harika bir fikir", ipa: "ha-zi-hi fik-ra mum-ta-za"},
      {ar: "أنا مشغول اليوم", tr: "Bugün meşgulüm", ipa: "a-na mash-ghul al-yawm"},
      {ar: "غدا مناسب", tr: "Yarın uygun", ipa: "gha-dan mu-na-sib"},
      {ar: "نذهب إلى مطعم؟", tr: "Restorana gidelim mi?", ipa: "nazhab i-la mat-am?"},
    ],
    grammar: "Sosyal önerilerde soru tonuyla kısa cümleler yeterlidir: “نلتقي الليلة؟” = “Bu gece buluşalım mı?” “مناسب” uygun demektir ve plan onaylarken kullanılır. Reddederken “أنا مشغول اليوم” deyip “غدا مناسب” eklemek nazik olur.",
    practice: [
      "1. “Kahve ister misin?” sorusunu söyle.",
      "2. “Yarın uygun” cümlesini yaz.",
      "3. “Bu harika bir fikir” ifadesini tekrar et.",
      "4. Bir restoran önerisi yap.",
      "5. Biriyle buluşma planı için 6 satırlık diyalog kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kiralama ve rezervasyon",
    titleNative: "الإيجار والحجز",
    focus: "Bugün Maskat’ta tur, araba, bisiklet veya ekipman kiralamak ve rezervasyon yapmak için gerekli ifadeleri öğreniyorsun.",
    vocab: [
      {ar: "إيجار", tr: "Kiralama", ipa: "i-jar"},
      {ar: "أستأجر", tr: "Kiralıyorum / kiralamak isterim", ipa: "as-ta-jir"},
      {ar: "سيارة", tr: "Araba", ipa: "say-ya-ra"},
      {ar: "دراجة", tr: "Bisiklet", ipa: "dar-ra-ja"},
      {ar: "يوم", tr: "Gün", ipa: "yawm"},
      {ar: "ساعة", tr: "Saat", ipa: "sa-a"},
      {ar: "رخصة", tr: "Ehliyet / lisans", ipa: "rukh-sa"},
      {ar: "تأمين", tr: "Sigorta", ipa: "ta-min"},
      {ar: "حجز", tr: "Rezervasyon", ipa: "hajz"},
      {ar: "متاح", tr: "Müsait / mevcut", ipa: "mu-tah"},
    ],
    phrases: [
      {ar: "أريد أن أستأجر سيارة", tr: "Araba kiralamak istiyorum", ipa: "u-rid an as-ta-jir say-ya-ra"},
      {ar: "هل التأمين مشمول؟", tr: "Sigorta dahil mi?", ipa: "hal at-ta-min mash-mul?"},
      {ar: "أحتاج السيارة ليوم واحد", tr: "Arabaya bir gün ihtiyacım var", ipa: "ah-taj as-say-ya-ra li-yawm wa-hid"},
      {ar: "هل الحجز متاح؟", tr: "Rezervasyon müsait mi?", ipa: "hal al-hajz mu-tah?"},
      {ar: "هذه رخصتي", tr: "Bu benim ehliyetim", ipa: "ha-zi-hi rukh-sa-ti"},
      {ar: "كم السعر في اليوم؟", tr: "Günlük fiyat ne kadar?", ipa: "kam as-si-r fi al-yawm?"},
    ],
    grammar: "“أريد أن...” kalıbı “... yapmak istiyorum” anlamındadır. Fiil ardından gelir: “أريد أن أستأجر” = “kiralamak istiyorum.” Kiralama sırasında “مشمول” yani “dahil” kelimesi ücretleri anlamak için önemlidir.",
    practice: [
      "1. “Araba kiralamak istiyorum” cümlesini söyle.",
      "2. “Sigorta dahil mi?” sorusunu yaz.",
      "3. “Günlük fiyat ne kadar?” ifadesini tekrar et.",
      "4. Araba, bisiklet, ehliyet kelimelerini ezberle.",
      "5. Kiralama ofisinde 6 satırlık diyalog oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Sahilde ve gezi aktivitelerinde",
    titleNative: "على الشاطئ وفي الأنشطة السياحية",
    focus: "Bugün Akabe veya Şarm eş-Şeyh’te sahilde, tekne turunda veya dalış merkezinde aktivite sormayı öğreniyorsun.",
    vocab: [
      {ar: "شاطئ", tr: "Plaj", ipa: "sha-ti"},
      {ar: "بحر", tr: "Deniz", ipa: "bahr"},
      {ar: "سباحة", tr: "Yüzme", ipa: "si-ba-ha"},
      {ar: "قارب", tr: "Tekne", ipa: "qa-rib"},
      {ar: "جولة بحرية", tr: "Tekne turu", ipa: "jaw-la bah-ri-ya"},
      {ar: "غوص", tr: "Dalış", ipa: "ghaws"},
      {ar: "آمن", tr: "Güvenli", ipa: "a-min"},
      {ar: "خطير", tr: "Tehlikeli", ipa: "kha-tir"},
      {ar: "سترة نجاة", tr: "Can yeleği", ipa: "sut-rat na-ja"},
      {ar: "شمس", tr: "Güneş", ipa: "shams"},
    ],
    phrases: [
      {ar: "أين الشاطئ؟", tr: "Plaj nerede?", ipa: "ay-na ash-sha-ti?"},
      {ar: "هل السباحة آمنة؟", tr: "Yüzmek güvenli mi?", ipa: "hal as-si-ba-ha a-mi-na?"},
      {ar: "أريد جولة بحرية", tr: "Tekne turu istiyorum", ipa: "u-rid jaw-la bah-ri-ya"},
      {ar: "هل يوجد سترة نجاة؟", tr: "Can yeleği var mı?", ipa: "hal yu-jad sut-rat na-ja?"},
      {ar: "لا أريد الغوص", tr: "Dalış istemiyorum", ipa: "la u-rid al-ghaws"},
      {ar: "الشمس قوية اليوم", tr: "Bugün güneş güçlü", ipa: "ash-shams qa-wi-ya al-yawm"},
    ],
    grammar: "“Aktivite istiyorum” demek için “أريد” + aktivite adı yeterlidir. Güvenlik için “هل... آمن؟” kalıbını kullanabilirsin. Arapça konuşulan turistik sahil yerlerinde güvenlik soruları sormak çok normaldir.",
    practice: [
      "1. “Plaj nerede?” sorusunu söyle.",
      "2. “Yüzmek güvenli mi?” cümlesini yaz.",
      "3. “Tekne turu istiyorum” ifadesini tekrar et.",
      "4. Can yeleği var mı diye sor.",
      "5. Sahilde 5 satırlık aktivite diyaloğu oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kayıp eşya ve tarif etme",
    titleNative: "الأشياء المفقودة والوصف",
    focus: "Bugün otelde, takside veya kafede bir eşyanı kaybettiğinde onu tarif etmeyi ve yardım istemeyi öğreniyorsun.",
    vocab: [
      {ar: "ضائع", tr: "Kayıp", ipa: "da-i"},
      {ar: "وجدت", tr: "Buldum", ipa: "wa-jad-tu"},
      {ar: "فقدت", tr: "Kaybettim", ipa: "fa-qad-tu"},
      {ar: "حقيبة", tr: "Çanta", ipa: "ha-qi-ba"},
      {ar: "محفظة", tr: "Cüzdan", ipa: "mih-fa-za"},
      {ar: "هاتف", tr: "Telefon", ipa: "ha-tif"},
      {ar: "أسود", tr: "Siyah", ipa: "as-wad"},
      {ar: "صغير", tr: "Küçük", ipa: "sa-ghir"},
      {ar: "كبير", tr: "Büyük", ipa: "ka-bir"},
      {ar: "مهم", tr: "Önemli", ipa: "mu-himm"},
    ],
    phrases: [
      {ar: "فقدت هاتفي", tr: "Telefonumu kaybettim", ipa: "fa-qad-tu ha-ti-fi"},
      {ar: "حقيبتي ضائعة", tr: "Çantam kayıp", ipa: "ha-qi-ba-ti da-i-a"},
      {ar: "المحفظة سوداء", tr: "Cüzdan siyah", ipa: "al-mih-fa-za saw-da"},
      {ar: "إنها مهمة جدا", tr: "O çok önemli", ipa: "in-na-ha mu-him-ma jid-dan"},
      {ar: "هل رأيت حقيبة؟", tr: "Bir çanta gördünüz mü?", ipa: "hal ra-ay-ta ha-qi-ba?"},
      {ar: "أين مكتب المفقودات؟", tr: "Kayıp eşya ofisi nerede?", ipa: "ay-na mak-tab al-maf-qu-dat?"},
    ],
    grammar: "“فقدت” kelimesi “kaybettim” anlamındadır. Eşyanı anlatırken renk ve boyut ekleyebilirsin: “محفظة سوداء صغيرة” = küçük siyah cüzdan. “مكتب المفقودات” kayıp eşya ofisi için kullanışlı bir ifadedir.",
    practice: [
      "1. “Telefonumu kaybettim” cümlesini söyle.",
      "2. “Kayıp eşya ofisi nerede?” sorusunu yaz.",
      "3. Çantanı renk ve boyutla tarif et.",
      "4. “O çok önemli” ifadesini tekrar et.",
      "5. Takside kayıp eşya için kısa bir diyalog kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Görüş belirtme ve tercih yapma",
    titleNative: "التعبير عن الرأي والاختيار",
    focus: "Bugün bir restoranda, tur ofisinde veya arkadaş sohbetinde ne sevdiğini, neyi tercih ettiğini ve ne düşündüğünü söylemeyi öğreniyorsun.",
    vocab: [
      {ar: "أحب", tr: "Seviyorum", ipa: "u-hibb"},
      {ar: "لا أحب", tr: "Sevmiyorum", ipa: "la u-hibb"},
      {ar: "أفضل", tr: "Tercih ederim", ipa: "u-fad-dil"},
      {ar: "أظن", tr: "Sanırım / düşünüyorum", ipa: "a-zunn"},
      {ar: "جيد", tr: "İyi", ipa: "jay-yid"},
      {ar: "سيئ", tr: "Kötü", ipa: "say-yi"},
      {ar: "جميل", tr: "Güzel", ipa: "ja-mil"},
      {ar: "ممتع", tr: "Eğlenceli", ipa: "mum-ti"},
      {ar: "هادئ", tr: "Sakin", ipa: "ha-di"},
      {ar: "مزدحم", tr: "Kalabalık", ipa: "muz-da-him"},
    ],
    phrases: [
      {ar: "أحب هذا المكان", tr: "Bu yeri seviyorum", ipa: "u-hibb ha-za al-ma-kan"},
      {ar: "لا أحب الأماكن المزدحمة", tr: "Kalabalık yerleri sevmiyorum", ipa: "la u-hibb al-a-ma-kin al-muz-da-hi-ma"},
      {ar: "أفضل الطعام البسيط", tr: "Basit yemeği tercih ederim", ipa: "u-fad-dil at-ta-am al-ba-sit"},
      {ar: "أظن أن هذا جيد", tr: "Bence bu iyi", ipa: "a-zunn an-na ha-za jay-yid"},
      {ar: "المكان هادئ وجميل", tr: "Yer sakin ve güzel", ipa: "al-ma-kan ha-di wa ja-mil"},
      {ar: "كان اليوم ممتعا", tr: "Bugün eğlenceliydi", ipa: "ka-na al-yawm mum-ti-an"},
    ],
    grammar: "“أحب” ve “أفضل” seyahatte tercihlerini anlatmak için en kullanışlı fiillerdendir. “لا” fiilin önüne gelerek olumsuz yapar: “لا أحب” = sevmiyorum. “و” bağlacı “ve” demektir ve iki sıfatı kolayca bağlar.",
    practice: [
      "1. “Bu yeri seviyorum” cümlesini söyle.",
      "2. “Kalabalık yerleri sevmiyorum” ifadesini yaz.",
      "3. “Basit yemeği tercih ederim” cümlesini tekrar et.",
      "4. Bir yer için iki sıfat kullanarak görüş belirt.",
      "5. Bugünkü kalıplarla seyahat yorumu yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Seyahat konuşmalarını birleştirme",
    titleNative: "جمع محادثات السفر",
    focus: "Bugün öğrendiğin temel selam, yön, sipariş, ödeme, yardım ve sosyal ifadeleri bir araya getiriyorsun. Artık Arapça konuşulan bir ülkede kısa ama işlevsel iletişim kurabilecek düzeye geldin.",
    vocab: [
      {ar: "أريد", tr: "İstiyorum", ipa: "u-rid"},
      {ar: "أحتاج", tr: "İhtiyacım var", ipa: "ah-taj"},
      {ar: "أين", tr: "Nerede", ipa: "ay-na"},
      {ar: "كم", tr: "Ne kadar / kaç", ipa: "kam"},
      {ar: "متى", tr: "Ne zaman", ipa: "ma-ta"},
      {ar: "ممكن", tr: "Mümkün", ipa: "mum-kin"},
      {ar: "صحيح", tr: "Doğru", ipa: "sa-hih"},
      {ar: "مناسب", tr: "Uygun", ipa: "mu-na-sib"},
      {ar: "مساعدة", tr: "Yardım", ipa: "mu-sa-a-da"},
      {ar: "شكرا", tr: "Teşekkürler", ipa: "shuk-ran"},
    ],
    phrases: [
      {ar: "أريد أن أذهب إلى الفندق", tr: "Otele gitmek istiyorum", ipa: "u-rid an az-hab i-la al-fun-duk"},
      {ar: "أحتاج إلى مساعدة من فضلك", tr: "Yardıma ihtiyacım var lütfen", ipa: "ah-taj i-la mu-sa-a-da min fad-lak"},
      {ar: "أين أقرب محطة؟", tr: "En yakın durak nerede?", ipa: "ay-na aq-rab ma-hat-ta?"},
      {ar: "كم السعر؟", tr: "Fiyat ne kadar?", ipa: "kam as-si-r?"},
      {ar: "متى يبدأ؟", tr: "Ne zaman başlıyor?", ipa: "ma-ta yab-da?"},
      {ar: "هل هذا مناسب؟", tr: "Bu uygun mu?", ipa: "hal ha-za mu-na-sib?"},
    ],
    grammar: "Son günün hedefi tek tek kelime bilmekten çok kalıpları birleştirmektir. “أريد أن...” yapmak istediğini, “أحتاج إلى...” ihtiyacını, “أين/كم/متى” ise temel sorularını kurar. Bu üç yapı seyahat Arapçasının omurgası gibi çalışır.",
    practice: [
      "1. Otel, kafe ve taksi için birer cümle kur.",
      "2. “Yardıma ihtiyacım var lütfen” cümlesini ezberle.",
      "3. “En yakın durak nerede?” sorusunu söyle.",
      "4. Fiyat, zaman ve yön sormak için üç ayrı soru yaz.",
      "5. 10 satırlık tam bir seyahat diyaloğu oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 8,
  },
];

var CONVERSATIONS_TR_AR = [
  {
    setting: "",
    lines: [
      {who: "them", ar: "مرحبا، ماذا تريد؟", tr: "Merhaba, ne istersiniz?"},
      {who: "you", ar: "مرحبا، أريد قهوة من فضلك.", tr: "Merhaba, kahve istiyorum lütfen."},
      {who: "them", ar: "مع حليب أو بدون حليب؟", tr: "Sütlü mü, sütsüz mü?"},
      {who: "you", ar: "مع حليب وبدون سكر.", tr: "Sütlü ve şekersiz."},
      {who: "them", ar: "هل تريد شيئا آخر؟", tr: "Başka bir şey ister misiniz?"},
      {who: "you", ar: "نعم، ماء بارد من فضلك.", tr: "Evet, soğuk su lütfen."},
      {who: "them", ar: "تفضل، القهوة والماء.", tr: "Buyurun, kahve ve su."},
      {who: "you", ar: "شكرا، كم الحساب؟", tr: "Teşekkürler, hesap ne kadar?"},
      {who: "them", ar: "الحساب خمسة دولارات.", tr: "Hesap beş dolar."},
      {who: "you", ar: "تفضل، شكرا جزيلا.", tr: "Buyurun, çok teşekkür ederim."},
      {who: "them", ar: "عفوا، يوم سعيد.", tr: "Rica ederim, iyi günler."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "مساء الخير، أهلا وسهلا.", tr: "İyi akşamlar, hoş geldiniz."},
      {who: "you", ar: "مساء الخير، عندي حجز.", tr: "İyi akşamlar, rezervasyonum var."},
      {who: "them", ar: "ما اسمك من فضلك؟", tr: "Adınız nedir lütfen?"},
      {who: "you", ar: "اسمي جيمس كانون.", tr: "Benim adım James Cannon."},
      {who: "them", ar: "هل عندك جواز السفر؟", tr: "Pasaportunuz var mı?"},
      {who: "you", ar: "نعم، هذا جواز سفري.", tr: "Evet, bu benim pasaportum."},
      {who: "them", ar: "حجزك لثلاث ليال.", tr: "Rezervasyonunuz üç gece için."},
      {who: "you", ar: "هل الإفطار مشمول؟", tr: "Kahvaltı dahil mi?"},
      {who: "them", ar: "نعم، الإفطار من السابعة إلى العاشرة.", tr: "Evet, kahvaltı yediden ona kadar."},
      {who: "you", ar: "ممتاز، أين المصعد؟", tr: "Harika, asansör nerede?"},
      {who: "them", ar: "المصعد على اليمين.", tr: "Asansör sağda."},
      {who: "you", ar: "شكرا جزيلا.", tr: "Çok teşekkür ederim."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", ar: "عفوا، أين محطة المترو؟", tr: "Pardon, metro istasyonu nerede?"},
      {who: "them", ar: "محطة المترو قريبة من هنا.", tr: "Metro istasyonu buraya yakın."},
      {who: "you", ar: "هل أذهب مستقيما؟", tr: "Düz mü gitmeliyim?"},
      {who: "them", ar: "نعم، اذهب مستقيما ثم إلى اليسار.", tr: "Evet, düz gidin sonra sola."},
      {who: "you", ar: "بعد كم دقيقة؟", tr: "Kaç dakika sonra?"},
      {who: "them", ar: "حوالي خمس دقائق.", tr: "Yaklaşık beş dakika."},
      {who: "you", ar: "هل هذا الاتجاه صحيح؟", tr: "Bu yön doğru mu?"},
      {who: "them", ar: "نعم، هذا الاتجاه صحيح.", tr: "Evet, bu yön doğru."},
      {who: "you", ar: "شكرا، أنا تائه قليلا.", tr: "Teşekkürler, biraz kayboldum."},
      {who: "them", ar: "لا مشكلة، أهلا وسهلا.", tr: "Sorun değil, rica ederim."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "أهلا، هل تريد قائمة الطعام؟", tr: "Merhaba, menü ister misiniz?"},
      {who: "you", ar: "نعم، أريد قائمة الطعام من فضلك.", tr: "Evet, menü istiyorum lütfen."},
      {who: "them", ar: "تفضل، ماذا تحب؟", tr: "Buyurun, ne seversiniz?"},
      {who: "you", ar: "أحب الدجاج، ماذا تنصح؟", tr: "Tavuk severim, ne tavsiye edersiniz?"},
      {who: "them", ar: "أنصح بالدجاج مع الأرز.", tr: "Pirinçli tavuğu tavsiye ederim."},
      {who: "you", ar: "ممتاز، أريد دجاجا مع أرز.", tr: "Harika, pirinçli tavuk istiyorum."},
      {who: "them", ar: "هل تريد سلطة أيضا؟", tr: "Salata da ister misiniz?"},
      {who: "you", ar: "نعم، سلطة وخبز من فضلك.", tr: "Evet, salata ve ekmek lütfen."},
      {who: "them", ar: "هل عندك حساسية؟", tr: "Alerjiniz var mı?"},
      {who: "you", ar: "لا، ليس عندي حساسية.", tr: "Hayır, alerjim yok."},
      {who: "them", ar: "تمام، الطعام بعد قليل.", tr: "Tamam, yemek birazdan."},
      {who: "you", ar: "شكرا جزيلا.", tr: "Çok teşekkür ederim."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "مرحبا، كيف أساعدك؟", tr: "Merhaba, size nasıl yardımcı olabilirim?"},
      {who: "you", ar: "أريد تذكرة واحدة إلى مركز المدينة.", tr: "Şehir merkezine bir bilet istiyorum."},
      {who: "them", ar: "ذهاب فقط أو ذهاب وعودة؟", tr: "Sadece gidiş mi, gidiş-dönüş mü?"},
      {who: "you", ar: "ذهاب فقط من فضلك.", tr: "Sadece gidiş lütfen."},
      {who: "them", ar: "السعر ثلاثة ريالات.", tr: "Fiyat üç riyal."},
      {who: "you", ar: "أي خط أحتاج؟", tr: "Hangi hatta ihtiyacım var?"},
      {who: "them", ar: "تحتاج الخط الأحمر.", tr: "Kırmızı hatta ihtiyacınız var."},
      {who: "you", ar: "هل هذا الاتجاه صحيح؟", tr: "Bu yön doğru mu?"},
      {who: "them", ar: "نعم، القطار من هذه الجهة.", tr: "Evet, tren bu taraftan."},
      {who: "you", ar: "شكرا، هذا واضح.", tr: "Teşekkürler, bu açık."},
      {who: "them", ar: "رحلة سعيدة.", tr: "İyi yolculuklar."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "أهلا، تفضل، هذا جميل.", tr: "Merhaba, buyurun, bu güzel."},
      {who: "you", ar: "شكرا، كم سعر هذا؟", tr: "Teşekkürler, bunun fiyatı ne kadar?"},
      {who: "them", ar: "السعر عشرون دولارا.", tr: "Fiyat yirmi dolar."},
      {who: "you", ar: "هذا غالي قليلا.", tr: "Bu biraz pahalı."},
      {who: "them", ar: "ممكن خمسة عشر.", tr: "On beş olabilir."},
      {who: "you", ar: "هل يوجد لون أزرق؟", tr: "Mavi renk var mı?"},
      {who: "them", ar: "نعم، عندي لون أزرق ولون أبيض.", tr: "Evet, mavi ve beyaz renk var."},
      {who: "you", ar: "أريد اللون الأزرق.", tr: "Mavi rengi istiyorum."},
      {who: "them", ar: "ممتاز، هل تريد شيئا آخر؟", tr: "Harika, başka bir şey ister misiniz?"},
      {who: "you", ar: "لا، شكرا، هذا فقط.", tr: "Hayır, teşekkürler, sadece bu."},
      {who: "them", ar: "تفضل.", tr: "Buyurun."},
      {who: "you", ar: "شكرا جزيلا.", tr: "Çok teşekkür ederim."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", ar: "مرحبا، كيف أساعدك؟", tr: "Merhaba, size nasıl yardımcı olabilirim?"},
      {who: "you", ar: "مرحبا، عندي ألم في الرأس.", tr: "Merhaba, başım ağrıyor."},
      {who: "them", ar: "هل عندك حمى؟", tr: "Ateşiniz var mı?"},
      {who: "you", ar: "لا، لا توجد حمى.", tr: "Hayır, ateş yok."},
      {who: "them", ar: "هل تحتاج إلى دواء بسيط؟", tr: "Basit bir ilaca ihtiyacınız var mı?"},
      {who: "you", ar: "نعم، من فضلك.", tr: "Evet, lütfen."},
      {who: "them", ar: "خذ هذا الدواء بعد الطعام.", tr: "Bu ilacı yemekten sonra alın."},
      {who: "you", ar: "كم مرة في اليوم؟", tr: "Günde kaç kere?"},
      {who: "them", ar: "مرتين في اليوم.", tr: "Günde iki kere."},
      {who: "you", ar: "هل أحتاج إلى وصفة؟", tr: "Reçeteye ihtiyacım var mı?"},
      {who: "them", ar: "لا، لا تحتاج إلى وصفة.", tr: "Hayır, reçeteye ihtiyacınız yok."},
      {who: "you", ar: "شكرا على المساعدة.", tr: "Yardım için teşekkürler."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", ar: "مرحبا، هل هذا المكان مفتوح دائما؟", tr: "Merhaba, burası her zaman açık mı?"},
      {who: "them", ar: "نعم، مفتوح كل يوم.", tr: "Evet, her gün açık."},
      {who: "you", ar: "هذه المدينة جميلة جدا.", tr: "Bu şehir çok güzel."},
      {who: "them", ar: "شكرا، هل هذه أول مرة لك هنا؟", tr: "Teşekkürler, buraya ilk gelişiniz mi?"},
      {who: "you", ar: "نعم، هذه أول مرة لي في الأردن.", tr: "Evet, Ürdün’e ilk gelişim."},
      {who: "them", ar: "هل تحب الطعام العربي؟", tr: "Arap yemeklerini seviyor musunuz?"},
      {who: "you", ar: "نعم، أحب الطعام العربي كثيرا.", tr: "Evet, Arap yemeklerini çok seviyorum."},
      {who: "them", ar: "ماذا زرت اليوم؟", tr: "Bugün nereyi ziyaret ettiniz?"},
      {who: "you", ar: "زرت المتحف والسوق.", tr: "Müzeyi ve pazarı ziyaret ettim."},
      {who: "them", ar: "ممتاز، السوق جميل في المساء.", tr: "Harika, pazar akşamları güzeldir."},
      {who: "you", ar: "شكرا على النصيحة.", tr: "Tavsiye için teşekkürler."},
      {who: "them", ar: "أهلا وسهلا بك في الأردن.", tr: "Ürdün’e hoş geldiniz."},
    ],
  },
];