// course-pt-sw.js
// Source: Portuguese | Target: Swahili
const COURSE_DATA = {
  src: 'pt',
  tgt: 'sw',
  srcName: 'Portuguese',
  tgtName: 'Swahili',
  srcFlag: '🇵🇹',
  tgtFlag: '🇰🇪',
  days: [
    {
      day: 1,
      title: `Cumprimentos básicos`,
      titleNative: `Salamu za msingi`,
      focus: `Hoje você aprende a cumprimentar pessoas em Dar es Salaam, Tanzânia, de forma educada e natural. Use estas palavras ao entrar em lojas, hotéis, cafés e ao falar com moradores.`,
      grammar: `Em suaíli, muitos cumprimentos são perguntas sobre bem-estar. “Hujambo?” é uma forma educada de dizer “olá”, e a resposta comum é “Sijambo”. “Habari” significa literalmente “notícias”, mas funciona como “como vai?” em conversas diárias.`,
      vocab: [
        {tgt:`hujambo`,src:`olá / como vai?`,pron:`hu-JAM-bo`},
        {tgt:`sijambo`,src:`estou bem`,pron:`si-JAM-bo`},
        {tgt:`habari`,src:`notícias / como vai?`,pron:`ha-BA-ri`},
        {tgt:`nzuri`,src:`bom / bem`,pron:`NZU-ri`},
        {tgt:`asante`,src:`obrigado/a`,pron:`a-SAN-te`},
        {tgt:`tafadhali`,src:`por favor`,pron:`ta-fa-DHA-li`},
        {tgt:`ndiyo`,src:`sim`,pron:`NDI-yo`},
        {tgt:`hapana`,src:`não`,pron:`ha-PA-na`},
        {tgt:`karibu`,src:`bem-vindo/a`,pron:`ka-RI-bu`},
        {tgt:`kwaheri`,src:`adeus`,pron:`kwa-HE-ri`},
      ],
      phrases: [
        {tgt:`Hujambo?`,src:`Olá, como vai?`,pron:`hu-JAM-bo`},
        {tgt:`Sijambo, asante.`,src:`Estou bem, obrigado/a.`,pron:`si-JAM-bo a-SAN-te`},
        {tgt:`Habari yako?`,src:`Como você está?`,pron:`ha-BA-ri YA-ko`},
        {tgt:`Nzuri sana.`,src:`Muito bem.`,pron:`NZU-ri SA-na`},
        {tgt:`Tafadhali, nisaidie.`,src:`Por favor, ajude-me.`,pron:`ta-fa-DHA-li ni-sa-I-di-e`},
        {tgt:`Kwaheri, tutaonana.`,src:`Adeus, até nos vermos.`,pron:`kwa-HE-ri tu-ta-o-NA-na`},
      ],
      conversation: [
      ],
    },
    {
      day: 2,
      title: `Apresentar-se`,
      titleNative: `Kujitambulisha`,
      focus: `Hoje você aprende a dizer seu nome e perguntar o nome de outra pessoa em Arusha, Tanzânia. Isso é útil ao conhecer guias, anfitriões, motoristas e outros viajantes.`,
      grammar: `“Jina langu ni...” significa “Meu nome é...”. Para perguntar o nome de alguém, use “Unaitwa nani?”, literalmente “Você é chamado quem?”. O verbo “naitwa” é muito prático porque evita precisar explicar a estrutura completa de “eu sou chamado”.`,
      vocab: [
        {tgt:`jina`,src:`nome`,pron:`JI-na`},
        {tgt:`langu`,src:`meu/minha`,pron:`LAN-gu`},
        {tgt:`lako`,src:`seu/sua`,pron:`LA-ko`},
        {tgt:`mimi`,src:`eu`,pron:`MI-mi`},
        {tgt:`wewe`,src:`você`,pron:`WE-we`},
        {tgt:`naitwa`,src:`chamo-me`,pron:`na-I-twa`},
        {tgt:`nani`,src:`quem`,pron:`NA-ni`},
        {tgt:`rafiki`,src:`amigo/a`,pron:`ra-FI-ki`},
        {tgt:`mgeni`,src:`visitante / hóspede`,pron:`m-GE-ni`},
        {tgt:`kutana`,src:`encontrar`,pron:`ku-TA-na`},
      ],
      phrases: [
        {tgt:`Jina langu ni Ana.`,src:`Meu nome é Ana.`,pron:`JI-na LAN-gu ni A-na`},
        {tgt:`Unaitwa nani?`,src:`Como você se chama?`,pron:`u-na-I-twa NA-ni`},
        {tgt:`Naitwa Paulo.`,src:`Chamo-me Paulo.`,pron:`na-I-twa PAU-lo`},
        {tgt:`Mimi ni mgeni.`,src:`Eu sou visitante.`,pron:`MI-mi ni m-GE-ni`},
        {tgt:`Wewe ni rafiki yangu.`,src:`Você é meu amigo.`,pron:`WE-we ni ra-FI-ki YAN-gu`},
        {tgt:`Nimefurahi kukutana nawe.`,src:`Prazer em conhecer você.`,pron:`ni-me-fu-RA-hi ku-ku-TA-na NA-we`},
      ],
      conversation: [
      ],
    },
    {
      day: 3,
      title: `Cortesia e frases essenciais`,
      titleNative: `Heshima na misemo muhimu`,
      focus: `Hoje você aprende frases educadas para situações rápidas em Mombasa, Quênia. Elas ajudam quando você precisa pedir ajuda, agradecer ou chamar atenção sem parecer rude.`,
      grammar: `“Asante” é obrigado/a, e “asante sana” é muito obrigado/a. “Sana” intensifica muitas palavras, como “nzuri sana” e “asante sana”. “Samahani” pode significar tanto “desculpe” quanto “com licença”, dependendo do contexto.`,
      vocab: [
        {tgt:`samahani`,src:`desculpe / com licença`,pron:`sa-ma-HA-ni`},
        {tgt:`pole`,src:`sinto muito / lamento`,pron:`PO-le`},
        {tgt:`sawa`,src:`certo / tudo bem`,pron:`SA-wa`},
        {tgt:`kidogo`,src:`um pouco`,pron:`ki-DO-go`},
        {tgt:`sana`,src:`muito`,pron:`SA-na`},
        {tgt:`msaada`,src:`ajuda`,pron:`m-SA-a-da`},
        {tgt:`subiri`,src:`espere`,pron:`su-BI-ri`},
        {tgt:`haraka`,src:`rápido`,pron:`ha-RA-ka`},
        {tgt:`shida`,src:`problema`,pron:`SHI-da`},
        {tgt:`hakuna`,src:`não há`,pron:`ha-KU-na`},
      ],
      phrases: [
        {tgt:`Samahani.`,src:`Com licença / desculpe.`,pron:`sa-ma-HA-ni`},
        {tgt:`Asante sana.`,src:`Muito obrigado/a.`,pron:`a-SAN-te SA-na`},
        {tgt:`Hakuna shida.`,src:`Não há problema.`,pron:`ha-KU-na SHI-da`},
        {tgt:`Subiri kidogo.`,src:`Espere um pouco.`,pron:`su-BI-ri ki-DO-go`},
        {tgt:`Nahitaji msaada.`,src:`Preciso de ajuda.`,pron:`na-hi-TA-ji m-SA-a-da`},
        {tgt:`Sawa, asante.`,src:`Certo, obrigado/a.`,pron:`SA-wa a-SAN-te`},
      ],
      conversation: [
      ],
    },
    {
      day: 4,
      title: `Números de 0 a 20`,
      titleNative: `Nambari kutoka sifuri hadi ishirini`,
      focus: `Hoje você aprende números básicos para comprar água, pagar transporte e entender preços em Stone Town, Zanzibar. Números aparecem em quase todas as interações de viagem.`,
      grammar: `Para formar números de 11 a 19, diga “kumi na...” mais o número: “kumi na moja” é onze, “kumi na mbili” é doze. “Na” significa “e”. Em compras simples, você pode usar apenas o número com “tafadhali”.`,
      vocab: [
        {tgt:`sifuri`,src:`zero`,pron:`si-FU-ri`},
        {tgt:`moja`,src:`um`,pron:`MO-ja`},
        {tgt:`mbili`,src:`dois`,pron:`MBI-li`},
        {tgt:`tatu`,src:`três`,pron:`TA-tu`},
        {tgt:`nne`,src:`quatro`,pron:`N-ne`},
        {tgt:`tano`,src:`cinco`,pron:`TA-no`},
        {tgt:`sita`,src:`seis`,pron:`SI-ta`},
        {tgt:`saba`,src:`sete`,pron:`SA-ba`},
        {tgt:`nane`,src:`oito`,pron:`NA-ne`},
        {tgt:`tisa`,src:`nove`,pron:`TI-sa`},
        {tgt:`kumi`,src:`dez`,pron:`KU-mi`},
        {tgt:`ishirini`,src:`vinte`,pron:`i-shi-RI-ni`},
      ],
      phrases: [
        {tgt:`Moja, tafadhali.`,src:`Um, por favor.`,pron:`MO-ja ta-fa-DHA-li`},
        {tgt:`Nataka mbili.`,src:`Quero dois.`,pron:`na-TA-ka MBI-li`},
        {tgt:`Bei ni kumi.`,src:`O preço é dez.`,pron:`be-i ni KU-mi`},
        {tgt:`Nina tatu.`,src:`Eu tenho três.`,pron:`NI-na TA-tu`},
        {tgt:`Ni kiasi gani?`,src:`Quanto custa?`,pron:`ni ki-A-si GA-ni`},
        {tgt:`Kumi na moja.`,src:`Onze.`,pron:`KU-mi na MO-ja`},
      ],
      conversation: [
      ],
    },
    {
      day: 5,
      title: `Dias, horários e encontros`,
      titleNative: `Siku, muda na miadi`,
      focus: `Hoje você aprende palavras de tempo para combinar passeios em Nairobi, Quênia. Saber dizer hoje, amanhã e horas aproximadas ajuda com guias, ônibus e reservas.`,
      grammar: `“Saa ngapi?” significa “que horas?”. Em suaíli, “saa” também pode significar “relógio” ou “hora”. Para viajantes iniciantes, é suficiente combinar palavras como “kesho asubuhi” e “leo jioni” antes de aprender o sistema completo de horas.`,
      vocab: [
        {tgt:`leo`,src:`hoje`,pron:`LE-o`},
        {tgt:`kesho`,src:`amanhã`,pron:`KE-sho`},
        {tgt:`jana`,src:`ontem`,pron:`JA-na`},
        {tgt:`sasa`,src:`agora`,pron:`SA-sa`},
        {tgt:`baadaye`,src:`mais tarde`,pron:`ba-a-DA-ye`},
        {tgt:`asubuhi`,src:`manhã`,pron:`a-su-BU-hi`},
        {tgt:`mchana`,src:`meio-dia / tarde inicial`,pron:`m-CHA-na`},
        {tgt:`jioni`,src:`fim da tarde / noite inicial`,pron:`ji-O-ni`},
        {tgt:`usiku`,src:`noite`,pron:`u-SI-ku`},
        {tgt:`saa`,src:`hora`,pron:`SA-a`},
      ],
      phrases: [
        {tgt:`Leo nina safari.`,src:`Hoje tenho uma viagem.`,pron:`LE-o NI-na sa-FA-ri`},
        {tgt:`Kesho asubuhi.`,src:`Amanhã de manhã.`,pron:`KE-sho a-su-BU-hi`},
        {tgt:`Sasa ni saa ngapi?`,src:`Que horas são agora?`,pron:`SA-sa ni SA-a NGA-pi`},
        {tgt:`Tutaonana baadaye.`,src:`Vamos nos ver mais tarde.`,pron:`tu-ta-o-NA-na ba-a-DA-ye`},
        {tgt:`Ninakuja jioni.`,src:`Venho no fim da tarde.`,pron:`ni-na-KU-ja ji-O-ni`},
        {tgt:`Usiku mwema.`,src:`Boa noite.`,pron:`u-SI-ku MWE-ma`},
      ],
      conversation: [
      ],
    },
    {
      day: 6,
      title: `Falar o que você quer`,
      titleNative: `Kusema unachotaka`,
      focus: `Hoje você aprende a dizer “eu quero” e “eu preciso” em Kampala, Uganda, onde o suaíli também pode ser útil em viagens regionais. Essas estruturas ajudam em lojas, hotéis e transportes.`,
      grammar: `“Nataka” significa “eu quero”, e “nahitaji” significa “eu preciso”. Depois dessas palavras, você pode colocar diretamente o objeto: “nataka maji”, “nahitaji tiketi”. Para verbos, muitas vezes aparece “ku-”, como em “kulipa”, pagar.`,
      vocab: [
        {tgt:`nataka`,src:`eu quero`,pron:`na-TA-ka`},
        {tgt:`nahitaji`,src:`eu preciso`,pron:`na-hi-TA-ji`},
        {tgt:`maji`,src:`água`,pron:`MA-ji`},
        {tgt:`chakula`,src:`comida`,pron:`cha-KU-la`},
        {tgt:`kahawa`,src:`café`,pron:`ka-HA-wa`},
        {tgt:`chai`,src:`chá`,pron:`CHAI`},
        {tgt:`tiketi`,src:`bilhete`,pron:`ti-KE-ti`},
        {tgt:`chumba`,src:`quarto`,pron:`CHUM-ba`},
        {tgt:`ramani`,src:`mapa`,pron:`ra-MA-ni`},
        {tgt:`simu`,src:`telefone`,pron:`SI-mu`},
      ],
      phrases: [
        {tgt:`Nataka maji.`,src:`Quero água.`,pron:`na-TA-ka MA-ji`},
        {tgt:`Nahitaji tiketi.`,src:`Preciso de um bilhete.`,pron:`na-hi-TA-ji ti-KE-ti`},
        {tgt:`Nataka kahawa moja.`,src:`Quero um café.`,pron:`na-TA-ka ka-HA-wa MO-ja`},
        {tgt:`Nahitaji chumba.`,src:`Preciso de um quarto.`,pron:`na-hi-TA-ji CHUM-ba`},
        {tgt:`Una ramani?`,src:`Você tem um mapa?`,pron:`U-na ra-MA-ni`},
        {tgt:`Nataka kulipa.`,src:`Quero pagar.`,pron:`na-TA-ka ku-LI-pa`},
      ],
      conversation: [
      ],
    },
    {
      day: 7,
      title: `Perguntas simples`,
      titleNative: `Maswali rahisi`,
      focus: `Hoje você aprende palavras de pergunta para se orientar em Dar es Salaam. Com poucas perguntas, você consegue resolver muitas situações de viagem.`,
      grammar: `Muitas perguntas em suaíli usam a palavra interrogativa no fim da frase: “iko wapi?” significa “está onde?”. “Ni nini?” significa “é o quê?”. Mesmo com gramática simples, essas perguntas são compreensíveis e úteis.`,
      vocab: [
        {tgt:`nini`,src:`o quê`,pron:`NI-ni`},
        {tgt:`wapi`,src:`onde`,pron:`WA-pi`},
        {tgt:`lini`,src:`quando`,pron:`LI-ni`},
        {tgt:`gani`,src:`qual / que tipo`,pron:`GA-ni`},
        {tgt:`kwa nini`,src:`por quê`,pron:`kwa NI-ni`},
        {tgt:`vipi`,src:`como`,pron:`VI-pi`},
        {tgt:`ngapi`,src:`quantos / quanto`,pron:`NGA-pi`},
        {tgt:`nani`,src:`quem`,pron:`NA-ni`},
        {tgt:`hii`,src:`este / isto`,pron:`HI-i`},
        {tgt:`ile`,src:`aquele`,pron:`I-le`},
      ],
      phrases: [
        {tgt:`Hii ni nini?`,src:`O que é isto?`,pron:`HI-i ni NI-ni`},
        {tgt:`Hoteli iko wapi?`,src:`Onde fica o hotel?`,pron:`ho-TE-li I-ko WA-pi`},
        {tgt:`Unaenda lini?`,src:`Quando você vai?`,pron:`u-na-EN-da LI-ni`},
        {tgt:`Ni kiasi gani?`,src:`Quanto custa?`,pron:`ni ki-A-si GA-ni`},
        {tgt:`Wewe ni nani?`,src:`Quem é você?`,pron:`WE-we ni NA-ni`},
        {tgt:`Unaendeleaje?`,src:`Como você está indo?`,pron:`u-na-en-de-LE-a-je`},
      ],
      conversation: [
      ],
    },
    {
      day: 8,
      title: `Chegada ao aeroporto`,
      titleNative: `Kuwasili uwanja wa ndege`,
      focus: `Hoje você pratica frases para chegar ao Aeroporto Internacional Julius Nyerere, em Dar es Salaam. Você vai aprender a falar sobre bagagem, táxi, passaporte e destino.`,
      grammar: `“Yangu” significa “meu/minha” e aparece depois do objeto: “pasipoti yangu”, “mizigo yangu”. Em suaíli, a posse geralmente vem depois do substantivo. Para viajantes, memorizar algumas combinações prontas é mais rápido do que estudar todas as classes nominais de início.`,
      vocab: [
        {tgt:`uwanja wa ndege`,src:`aeroporto`,pron:`u-WAN-ja wa NDE-ge`},
        {tgt:`pasipoti`,src:`passaporte`,pron:`pa-si-PO-ti`},
        {tgt:`mizigo`,src:`bagagem`,pron:`mi-ZI-go`},
        {tgt:`teksi`,src:`táxi`,pron:`TE-ksi`},
        {tgt:`dereva`,src:`motorista`,pron:`de-RE-va`},
        {tgt:`kituo`,src:`estação / ponto`,pron:`ki-TU-o`},
        {tgt:`anwani`,src:`endereço`,pron:`an-WA-ni`},
        {tgt:`hati`,src:`documento`,pron:`HA-ti`},
        {tgt:`ukaguzi`,src:`inspeção`,pron:`u-ka-GU-zi`},
        {tgt:`kuwasili`,src:`chegar`,pron:`ku-wa-SI-li`},
      ],
      phrases: [
        {tgt:`Nimewasili sasa.`,src:`Cheguei agora.`,pron:`ni-me-wa-SI-li SA-sa`},
        {tgt:`Mizigo yangu iko wapi?`,src:`Onde está minha bagagem?`,pron:`mi-ZI-go YAN-gu I-ko WA-pi`},
        {tgt:`Nahitaji teksi.`,src:`Preciso de um táxi.`,pron:`na-hi-TA-ji TE-ksi`},
        {tgt:`Hii ni pasipoti yangu.`,src:`Este é meu passaporte.`,pron:`HI-i ni pa-si-PO-ti YAN-gu`},
        {tgt:`Ninaenda hoteli.`,src:`Vou para o hotel.`,pron:`ni-na-EN-da ho-TE-li`},
        {tgt:`Anwani ni hii.`,src:`O endereço é este.`,pron:`an-WA-ni ni HI-i`},
      ],
      conversation: [
      ],
    },
    {
      day: 9,
      title: `No hotel`,
      titleNative: `Hotelini`,
      focus: `Hoje você aprende frases para fazer check-in em um hotel em Zanzibar. Você vai lidar com reserva, quarto, chave e problemas simples.`,
      grammar: `“Kuna” significa “há/existe”, como em “Kuna tatizo”, há um problema. “Hakuna” é o negativo, como em “Hakuna shida”, não há problema. Essas duas palavras são extremamente úteis em hotéis, restaurantes e transportes.`,
      vocab: [
        {tgt:`hoteli`,src:`hotel`,pron:`ho-TE-li`},
        {tgt:`mapokezi`,src:`recepção`,pron:`ma-po-KE-zi`},
        {tgt:`nafasi`,src:`vaga / espaço`,pron:`na-FA-si`},
        {tgt:`akiba`,src:`reserva`,pron:`a-KI-ba`},
        {tgt:`funguo`,src:`chave`,pron:`fun-GU-o`},
        {tgt:`kitanda`,src:`cama`,pron:`ki-TAN-da`},
        {tgt:`bafu`,src:`banheiro`,pron:`BA-fu`},
        {tgt:`dirisha`,src:`janela`,pron:`di-RI-sha`},
        {tgt:`safi`,src:`limpo`,pron:`SA-fi`},
        {tgt:`tatizo`,src:`problema`,pron:`ta-TI-zo`},
      ],
      phrases: [
        {tgt:`Nina akiba.`,src:`Tenho uma reserva.`,pron:`NI-na a-KI-ba`},
        {tgt:`Nahitaji chumba kimoja.`,src:`Preciso de um quarto.`,pron:`na-hi-TA-ji CHUM-ba ki-MO-ja`},
        {tgt:`Funguo iko wapi?`,src:`Onde está a chave?`,pron:`fun-GU-o I-ko WA-pi`},
        {tgt:`Chumba ni safi.`,src:`O quarto está limpo.`,pron:`CHUM-ba ni SA-fi`},
        {tgt:`Kuna tatizo.`,src:`Há um problema.`,pron:`KU-na ta-TI-zo`},
        {tgt:`Bafu halifanyi kazi.`,src:`O banheiro não funciona.`,pron:`BA-fu ha-li-FAN-yi KA-zi`},
      ],
      conversation: [
      ],
    },
    {
      day: 10,
      title: `Pedir direções`,
      titleNative: `Kuuliza njia`,
      focus: `Hoje você aprende a pedir direções em Stone Town, onde ruas estreitas podem confundir visitantes. Você vai praticar palavras como esquerda, direita, perto e longe.`,
      grammar: `Para dar instruções, usa-se muito o imperativo simples: “nenda” é “vá”, “geuka” é “vire”. “Kushoto” e “kulia” indicam direção. Em conversas reais, moradores também podem apontar ou repetir a instrução com gestos.`,
      vocab: [
        {tgt:`njia`,src:`caminho / estrada`,pron:`NJI-a`},
        {tgt:`kushoto`,src:`esquerda`,pron:`ku-SHO-to`},
        {tgt:`kulia`,src:`direita`,pron:`ku-LI-a`},
        {tgt:`moja kwa moja`,src:`em frente`,pron:`MO-ja kwa MO-ja`},
        {tgt:`karibu`,src:`perto`,pron:`ka-RI-bu`},
        {tgt:`mbali`,src:`longe`,pron:`m-BA-li`},
        {tgt:`soko`,src:`mercado`,pron:`SO-ko`},
        {tgt:`duka`,src:`loja`,pron:`DU-ka`},
        {tgt:`msikiti`,src:`mesquita`,pron:`m-si-KI-ti`},
        {tgt:`bahari`,src:`mar`,pron:`ba-HA-ri`},
      ],
      phrases: [
        {tgt:`Soko liko wapi?`,src:`Onde fica o mercado?`,pron:`SO-ko li-ko WA-pi`},
        {tgt:`Nenda moja kwa moja.`,src:`Vá em frente.`,pron:`NEN-da MO-ja kwa MO-ja`},
        {tgt:`Geuka kushoto.`,src:`Vire à esquerda.`,pron:`GE-u-ka ku-SHO-to`},
        {tgt:`Geuka kulia.`,src:`Vire à direita.`,pron:`GE-u-ka ku-LI-a`},
        {tgt:`Ni karibu?`,src:`É perto?`,pron:`ni ka-RI-bu`},
        {tgt:`Ni mbali sana?`,src:`É muito longe?`,pron:`ni m-BA-li SA-na`},
      ],
      conversation: [
      ],
    },
    {
      day: 11,
      title: `Transporte local`,
      titleNative: `Usafiri wa eneo`,
      focus: `Hoje você aprende palavras para usar táxi, daladala e mototáxi em Dar es Salaam. Saber confirmar destino e preço antes de entrar é essencial.`,
      grammar: `“Naenda” significa “eu vou” ou “estou indo”. “Mji” significa cidade ou centro, e “mjini” quer dizer “na cidade/ao centro”. Para pedir para descer, “Nataka kushuka hapa” é uma frase pronta muito útil.`,
      vocab: [
        {tgt:`usafiri`,src:`transporte`,pron:`u-sa-FI-ri`},
        {tgt:`daladala`,src:`micro-ônibus local`,pron:`da-la-DA-la`},
        {tgt:`boda boda`,src:`mototáxi`,pron:`BO-da BO-da`},
        {tgt:`bei`,src:`preço`,pron:`BE-i`},
        {tgt:`nauli`,src:`tarifa`,pron:`na-U-li`},
        {tgt:`kituo cha basi`,src:`ponto de ônibus`,pron:`ki-TU-o cha BA-si`},
        {tgt:`basi`,src:`ônibus`,pron:`BA-si`},
        {tgt:`safari`,src:`viagem`,pron:`sa-FA-ri`},
        {tgt:`salama`,src:`seguro`,pron:`sa-LA-ma`},
        {tgt:`shuka`,src:`descer`,pron:`SHU-ka`},
      ],
      phrases: [
        {tgt:`Naenda mjini.`,src:`Vou ao centro.`,pron:`na-EN-da m-JI-ni`},
        {tgt:`Nauli ni kiasi gani?`,src:`Quanto é a tarifa?`,pron:`na-U-li ni ki-A-si GA-ni`},
        {tgt:`Nataka kushuka hapa.`,src:`Quero descer aqui.`,pron:`na-TA-ka ku-SHU-ka HA-pa`},
        {tgt:`Je, ni salama?`,src:`É seguro?`,pron:`je ni sa-LA-ma`},
        {tgt:`Kituo cha basi kiko wapi?`,src:`Onde fica o ponto de ônibus?`,pron:`ki-TU-o cha BA-si ki-ko WA-pi`},
        {tgt:`Tafadhali, nenda polepole.`,src:`Por favor, vá devagar.`,pron:`ta-fa-DHA-li NEN-da po-le-PO-le`},
      ],
      conversation: [
      ],
    },
    {
      day: 12,
      title: `Comprar bilhetes`,
      titleNative: `Kununua tiketi`,
      focus: `Hoje você pratica comprar bilhetes de ônibus ou ferry em Dar es Salaam e Zanzibar. Você vai falar sobre ida, volta, horário e destino.`,
      grammar: `“Ya kwenda” significa “para ir a” e é útil em bilhetes: “tiketi ya kwenda Zanzibar”. “Kurudi” é voltar, e “kuondoka” é partir. Verbos no infinitivo frequentemente começam com “ku-”.`,
      vocab: [
        {tgt:`tiketi`,src:`bilhete`,pron:`ti-KE-ti`},
        {tgt:`feri`,src:`ferry`,pron:`FE-ri`},
        {tgt:`treni`,src:`trem`,pron:`TRE-ni`},
        {tgt:`safari ya kwenda`,src:`viagem de ida`,pron:`sa-FA-ri ya KWEN-da`},
        {tgt:`kurudi`,src:`voltar`,pron:`ku-RU-di`},
        {tgt:`kuondoka`,src:`partir`,pron:`ku-on-DO-ka`},
        {tgt:`kufika`,src:`chegar`,pron:`ku-FI-ka`},
        {tgt:`abiria`,src:`passageiro`,pron:`a-BI-ri-a`},
        {tgt:`dirisha`,src:`janela`,pron:`di-RI-sha`},
        {tgt:`nafasi`,src:`assento / espaço`,pron:`na-FA-si`},
      ],
      phrases: [
        {tgt:`Nataka tiketi moja.`,src:`Quero um bilhete.`,pron:`na-TA-ka ti-KE-ti MO-ja`},
        {tgt:`Tiketi ya kwenda Zanzibar.`,src:`Bilhete para Zanzibar.`,pron:`ti-KE-ti ya KWEN-da Zan-zi-BAR`},
        {tgt:`Feri inaondoka saa ngapi?`,src:`A que horas sai o ferry?`,pron:`FE-ri i-na-on-DO-ka SA-a NGA-pi`},
        {tgt:`Nataka kurudi kesho.`,src:`Quero voltar amanhã.`,pron:`na-TA-ka ku-RU-di KE-sho`},
        {tgt:`Kuna nafasi dirishani?`,src:`Há assento na janela?`,pron:`KU-na na-FA-si di-ri-SHA-ni`},
        {tgt:`Nitafika lini?`,src:`Quando vou chegar?`,pron:`ni-ta-FI-ka LI-ni`},
      ],
      conversation: [
      ],
    },
    {
      day: 13,
      title: `No café`,
      titleNative: `Kwenye mkahawa`,
      focus: `Hoje você aprende a pedir café, chá e lanches num café em Nairobi. A cultura do chá é forte na região, e frases simples ajudam a pedir com confiança.`,
      grammar: `“Bila” significa “sem”, como “bila sukari”, sem açúcar. “Na” pode significar “e” ou “com”, dependendo do contexto. Em pedidos, você pode dizer “na maziwa” para pedir “com leite”.`,
      vocab: [
        {tgt:`mkahawa`,src:`café / cafeteria`,pron:`m-ka-HA-wa`},
        {tgt:`kahawa`,src:`café`,pron:`ka-HA-wa`},
        {tgt:`chai`,src:`chá`,pron:`CHAI`},
        {tgt:`maziwa`,src:`leite`,pron:`ma-ZI-wa`},
        {tgt:`sukari`,src:`açúcar`,pron:`su-KA-ri`},
        {tgt:`mkate`,src:`pão`,pron:`m-KA-te`},
        {tgt:`keki`,src:`bolo`,pron:`KE-ki`},
        {tgt:`kikombe`,src:`xícara`,pron:`ki-KOM-be`},
        {tgt:`baridi`,src:`frio`,pron:`ba-RI-di`},
        {tgt:`moto`,src:`quente`,pron:`MO-to`},
      ],
      phrases: [
        {tgt:`Nataka chai moja.`,src:`Quero um chá.`,pron:`na-TA-ka CHAI MO-ja`},
        {tgt:`Kahawa bila sukari.`,src:`Café sem açúcar.`,pron:`ka-HA-wa BI-la su-KA-ri`},
        {tgt:`Na maziwa, tafadhali.`,src:`Com leite, por favor.`,pron:`na ma-ZI-wa ta-fa-DHA-li`},
        {tgt:`Chai ni moto sana.`,src:`O chá está muito quente.`,pron:`CHAI ni MO-to SA-na`},
        {tgt:`Nataka keki kidogo.`,src:`Quero um pouco de bolo.`,pron:`na-TA-ka KE-ki ki-DO-go`},
        {tgt:`Naweza kulipa sasa?`,src:`Posso pagar agora?`,pron:`na-WE-za ku-LI-pa SA-sa`},
      ],
      conversation: [
      ],
    },
    {
      day: 14,
      title: `Comida e sabores`,
      titleNative: `Chakula na ladha`,
      focus: `Hoje você aprende palavras para falar de comida em Mombasa, onde pratos costeiros têm influência suaíli, árabe e indiana. Você vai pedir pratos simples e comentar sabores.`,
      grammar: `“Kitamu” é a forma comum para dizer que comida é saborosa. “Zaidi” significa “mais” e aparece depois do substantivo: “mboga zaidi”. Para restrições alimentares, “Nina mzio wa...” significa “Tenho alergia a...”.`,
      vocab: [
        {tgt:`chakula`,src:`comida`,pron:`cha-KU-la`},
        {tgt:`wali`,src:`arroz`,pron:`WA-li`},
        {tgt:`ugali`,src:`massa de milho`,pron:`u-GA-li`},
        {tgt:`nyama`,src:`carne`,pron:`NYA-ma`},
        {tgt:`samaki`,src:`peixe`,pron:`sa-MA-ki`},
        {tgt:`mboga`,src:`legumes / verduras`,pron:`m-BO-ga`},
        {tgt:`tamu`,src:`saboroso / doce`,pron:`TA-mu`},
        {tgt:`chumvi`,src:`sal`,pron:`CHUM-vi`},
        {tgt:`pilipili`,src:`pimenta`,pron:`pi-li-PI-li`},
        {tgt:`supu`,src:`sopa`,pron:`SU-pu`},
      ],
      phrases: [
        {tgt:`Nataka samaki na wali.`,src:`Quero peixe com arroz.`,pron:`na-TA-ka sa-MA-ki na WA-li`},
        {tgt:`Chakula ni kitamu.`,src:`A comida está saborosa.`,pron:`cha-KU-la ni ki-TA-mu`},
        {tgt:`Bila pilipili, tafadhali.`,src:`Sem pimenta, por favor.`,pron:`BI-la pi-li-PI-li ta-fa-DHA-li`},
        {tgt:`Nataka mboga zaidi.`,src:`Quero mais legumes.`,pron:`na-TA-ka m-BO-ga za-I-di`},
        {tgt:`Kuna nyama?`,src:`Tem carne?`,pron:`KU-na NYA-ma`},
        {tgt:`Nina mzio wa samaki.`,src:`Tenho alergia a peixe.`,pron:`NI-na m-ZI-o wa sa-MA-ki`},
      ],
      conversation: [
      ],
    },
    {
      day: 15,
      title: `No restaurante`,
      titleNative: `Kwenye mgahawa`,
      focus: `Hoje você pratica frases para sentar, pedir, chamar o garçom e pagar em um restaurante em Zanzibar. O foco é ser claro e educado sem precisar de frases longas.`,
      grammar: `“Naomba” é uma forma muito educada de pedir algo, parecida com “eu gostaria de pedir”. Você pode usá-la com objetos: “Naomba bili”, “Naomba menyu”. É uma palavra muito útil para soar respeitoso.`,
      vocab: [
        {tgt:`mgahawa`,src:`restaurante`,pron:`m-ga-HA-wa`},
        {tgt:`mhudumu`,src:`atendente / garçom`,pron:`m-hu-DU-mu`},
        {tgt:`menyu`,src:`cardápio`,pron:`ME-nyu`},
        {tgt:`meza`,src:`mesa`,pron:`ME-za`},
        {tgt:`sahani`,src:`prato`,pron:`sa-HA-ni`},
        {tgt:`kijiko`,src:`colher`,pron:`ki-JI-ko`},
        {tgt:`uma`,src:`garfo`,pron:`U-ma`},
        {tgt:`kisu`,src:`faca`,pron:`KI-su`},
        {tgt:`bili`,src:`conta`,pron:`BI-li`},
        {tgt:`risiti`,src:`recibo`,pron:`ri-SI-ti`},
      ],
      phrases: [
        {tgt:`Tunaweza kukaa hapa?`,src:`Podemos sentar aqui?`,pron:`tu-na-WE-za ku-KA-a HA-pa`},
        {tgt:`Menyu, tafadhali.`,src:`O cardápio, por favor.`,pron:`ME-nyu ta-fa-DHA-li`},
        {tgt:`Niko tayari kuagiza.`,src:`Estou pronto/a para pedir.`,pron:`NI-ko ta-YA-ri ku-a-GI-za`},
        {tgt:`Naomba bili.`,src:`Peço a conta.`,pron:`na-OM-ba BI-li`},
        {tgt:`Naomba risiti.`,src:`Peço o recibo.`,pron:`na-OM-ba ri-SI-ti`},
        {tgt:`Chakula kilikuwa kitamu.`,src:`A comida estava saborosa.`,pron:`cha-KU-la ki-li-KU-wa ki-TA-mu`},
      ],
      conversation: [
      ],
    },
    {
      day: 16,
      title: `Fazer compras no mercado`,
      titleNative: `Kununua sokoni`,
      focus: `Hoje você aprende frases para comprar frutas, lembranças e itens simples no mercado Kariakoo, em Dar es Salaam. Você vai perguntar preço, quantidade e negociar com educação.`,
      grammar: `“Unaweza...?” significa “Você pode...?” e é muito útil para pedidos educados. “Kupunguza bei” significa baixar o preço. Em mercados, negociar pode ser comum, mas mantenha tom leve e respeitoso.`,
      vocab: [
        {tgt:`soko`,src:`mercado`,pron:`SO-ko`},
        {tgt:`matunda`,src:`frutas`,pron:`ma-TUN-da`},
        {tgt:`ndizi`,src:`banana`,pron:`n-DI-zi`},
        {tgt:`embe`,src:`manga`,pron:`EM-be`},
        {tgt:`bei`,src:`preço`,pron:`BE-i`},
        {tgt:`ghali`,src:`caro`,pron:`GHA-li`},
        {tgt:`nafuu`,src:`barato / acessível`,pron:`na-FU-u`},
        {tgt:`pesa`,src:`dinheiro`,pron:`PE-sa`},
        {tgt:`mfuko`,src:`sacola`,pron:`m-FU-ko`},
        {tgt:`nunua`,src:`comprar`,pron:`nu-NU-a`},
      ],
      phrases: [
        {tgt:`Bei gani?`,src:`Qual é o preço?`,pron:`BE-i GA-ni`},
        {tgt:`Hii ni ghali sana.`,src:`Isto é muito caro.`,pron:`HI-i ni GHA-li SA-na`},
        {tgt:`Unaweza kupunguza bei?`,src:`Pode baixar o preço?`,pron:`u-na-WE-za ku-pun-GU-za BE-i`},
        {tgt:`Nataka ndizi tano.`,src:`Quero cinco bananas.`,pron:`na-TA-ka n-DI-zi TA-no`},
        {tgt:`Naomba mfuko.`,src:`Peço uma sacola.`,pron:`na-OM-ba m-FU-ko`},
        {tgt:`Nitalipa kwa pesa taslimu.`,src:`Vou pagar em dinheiro.`,pron:`ni-ta-LI-pa kwa PE-sa tas-LI-mu`},
      ],
      conversation: [
      ],
    },
    {
      day: 17,
      title: `Cores e roupas`,
      titleNative: `Rangi na nguo`,
      focus: `Hoje você aprende palavras para comprar roupas e escolher cores em mercados e lojas de Arusha. Isso ajuda quando você precisa de uma camisa leve, sandálias ou roupa para clima quente.`,
      grammar: `Cores em suaíli podem mudar conforme o tipo de substantivo, mas viajantes podem começar usando formas comuns como “nyeupe”, “nyeusi” e “nyekundu”. Em lojas, gestos e apontar o objeto ajudam muito. “Kubwa” significa grande, e “ndogo” significa pequeno.`,
      vocab: [
        {tgt:`rangi`,src:`cor`,pron:`RAN-gi`},
        {tgt:`nguo`,src:`roupa`,pron:`n-GU-o`},
        {tgt:`shati`,src:`camisa`,pron:`SHA-ti`},
        {tgt:`suruali`,src:`calça`,pron:`su-RU-a-li`},
        {tgt:`viatu`,src:`sapatos`,pron:`vi-A-tu`},
        {tgt:`kofia`,src:`chapéu`,pron:`ko-FI-a`},
        {tgt:`nyeupe`,src:`branco`,pron:`nye-U-pe`},
        {tgt:`nyeusi`,src:`preto`,pron:`nye-U-si`},
        {tgt:`nyekundu`,src:`vermelho`,pron:`nye-KUN-du`},
        {tgt:`bluu`,src:`azul`,pron:`BLU-u`},
      ],
      phrases: [
        {tgt:`Nataka shati jeupe.`,src:`Quero uma camisa branca.`,pron:`na-TA-ka SHA-ti JE-u-pe`},
        {tgt:`Una rangi ya bluu?`,src:`Você tem na cor azul?`,pron:`U-na RAN-gi ya BLU-u`},
        {tgt:`Viatu hivi ni kiasi gani?`,src:`Quanto custam estes sapatos?`,pron:`vi-A-tu HI-vi ni ki-A-si GA-ni`},
        {tgt:`Nahitaji kofia.`,src:`Preciso de um chapéu.`,pron:`na-hi-TA-ji ko-FI-a`},
        {tgt:`Hii ni kubwa sana.`,src:`Isto é grande demais.`,pron:`HI-i ni KU-bwa SA-na`},
        {tgt:`Hii ni ndogo sana.`,src:`Isto é pequeno demais.`,pron:`HI-i ni n-DO-go SA-na`},
      ],
      conversation: [
      ],
    },
    {
      day: 18,
      title: `Dinheiro e pagamento`,
      titleNative: `Pesa na malipo`,
      focus: `Hoje você aprende a falar sobre dinheiro, troco e formas de pagamento em Nairobi. Em muitos lugares, pagamentos móveis são comuns, mas dinheiro ainda é muito usado.`,
      grammar: `“Kulipa” é pagar, e “nitalipa” significa “vou pagar”. A palavra “kwa” pode indicar meio ou modo: “kwa kadi” é com cartão, “kwa pesa taslimu” é em dinheiro vivo. “Yangu” continua sendo muito útil para dizer “meu/minha”.`,
      vocab: [
        {tgt:`pesa`,src:`dinheiro`,pron:`PE-sa`},
        {tgt:`malipo`,src:`pagamento`,pron:`ma-LI-po`},
        {tgt:`lipa`,src:`pagar`,pron:`LI-pa`},
        {tgt:`chenji`,src:`troco`,pron:`CHEN-ji`},
        {tgt:`kadi`,src:`cartão`,pron:`KA-di`},
        {tgt:`benki`,src:`banco`,pron:`BEN-ki`},
        {tgt:`ATM`,src:`caixa eletrônico`,pron:`ei-ti-EM`},
        {tgt:`risiti`,src:`recibo`,pron:`ri-SI-ti`},
        {tgt:`sarafu`,src:`moeda`,pron:`sa-RA-fu`},
        {tgt:`noti`,src:`nota de dinheiro`,pron:`NO-ti`},
      ],
      phrases: [
        {tgt:`Naweza kulipa kwa kadi?`,src:`Posso pagar com cartão?`,pron:`na-WE-za ku-LI-pa kwa KA-di`},
        {tgt:`Nitalipa kwa pesa taslimu.`,src:`Vou pagar em dinheiro.`,pron:`ni-ta-LI-pa kwa PE-sa tas-LI-mu`},
        {tgt:`Chenji yangu iko wapi?`,src:`Onde está meu troco?`,pron:`CHEN-ji YAN-gu I-ko WA-pi`},
        {tgt:`Naomba risiti.`,src:`Peço o recibo.`,pron:`na-OM-ba ri-SI-ti`},
        {tgt:`ATM iko wapi?`,src:`Onde fica o caixa eletrônico?`,pron:`ei-ti-EM I-ko WA-pi`},
        {tgt:`Malipo yamekamilika.`,src:`O pagamento foi concluído.`,pron:`ma-LI-po ya-me-ka-MI-li-ka`},
      ],
      conversation: [
      ],
    },
    {
      day: 19,
      title: `Saúde e farmácia`,
      titleNative: `Afya na duka la dawa`,
      focus: `Hoje você aprende frases para uma farmácia em Dar es Salaam. Você vai explicar sintomas simples e pedir remédios básicos de forma clara.`,
      grammar: `“Nina...” significa “eu tenho”. Para dores, você pode usar “Nina maumivu ya...” mais a parte do corpo, como “kichwa”. Também se usa “linauma” para dizer “dói”, especialmente com partes do corpo como “tumbo”.`,
      vocab: [
        {tgt:`afya`,src:`saúde`,pron:`AF-ya`},
        {tgt:`duka la dawa`,src:`farmácia`,pron:`DU-ka la DA-wa`},
        {tgt:`dawa`,src:`remédio`,pron:`DA-wa`},
        {tgt:`kichwa`,src:`cabeça`,pron:`KI-chwa`},
        {tgt:`tumbo`,src:`barriga / estômago`,pron:`TUM-bo`},
        {tgt:`maumivu`,src:`dor`,pron:`ma-u-MI-vu`},
        {tgt:`homa`,src:`febre`,pron:`HO-ma`},
        {tgt:`baridi`,src:`resfriado / frio`,pron:`ba-RI-di`},
        {tgt:`daktari`,src:`médico/a`,pron:`dak-TA-ri`},
        {tgt:`hospitali`,src:`hospital`,pron:`hos-pi-TA-li`},
      ],
      phrases: [
        {tgt:`Nina maumivu ya kichwa.`,src:`Tenho dor de cabeça.`,pron:`NI-na ma-u-MI-vu ya KI-chwa`},
        {tgt:`Tumbo linauma.`,src:`Minha barriga dói.`,pron:`TUM-bo li-na-U-ma`},
        {tgt:`Nina homa.`,src:`Tenho febre.`,pron:`NI-na HO-ma`},
        {tgt:`Nahitaji dawa.`,src:`Preciso de remédio.`,pron:`na-hi-TA-ji DA-wa`},
        {tgt:`Duka la dawa liko wapi?`,src:`Onde fica a farmácia?`,pron:`DU-ka la DA-wa li-ko WA-pi`},
        {tgt:`Nahitaji daktari.`,src:`Preciso de um médico.`,pron:`na-hi-TA-ji dak-TA-ri`},
      ],
      conversation: [
      ],
    },
    {
      day: 20,
      title: `Emergências`,
      titleNative: `Dharura`,
      focus: `Hoje você aprende frases essenciais para emergências em Mombasa. Estas frases são curtas, diretas e importantes para pedir ajuda rapidamente.`,
      grammar: `Em emergências, frases curtas são melhores. “Nimepotea” pode significar “estou perdido/a” ou “me perdi”. “Imepotea” significa que algo desapareceu ou foi perdido, como em “simu yangu imepotea”.`,
      vocab: [
        {tgt:`dharura`,src:`emergência`,pron:`dha-RU-ra`},
        {tgt:`polisi`,src:`polícia`,pron:`po-LI-si`},
        {tgt:`moto`,src:`fogo`,pron:`MO-to`},
        {tgt:`hatari`,src:`perigo`,pron:`ha-TA-ri`},
        {tgt:`wizi`,src:`roubo`,pron:`WI-zi`},
        {tgt:`potea`,src:`perder-se`,pron:`po-TE-a`},
        {tgt:`saidia`,src:`ajudar`,pron:`sa-I-di-a`},
        {tgt:`haraka`,src:`rápido`,pron:`ha-RA-ka`},
        {tgt:`simu`,src:`telefone`,pron:`SI-mu`},
        {tgt:`balozi`,src:`embaixador / consulado`,pron:`ba-LO-zi`},
      ],
      phrases: [
        {tgt:`Ni dharura.`,src:`É uma emergência.`,pron:`ni dha-RU-ra`},
        {tgt:`Saidia, tafadhali!`,src:`Ajude, por favor!`,pron:`sa-I-di-a ta-fa-DHA-li`},
        {tgt:`Nahitaji polisi.`,src:`Preciso da polícia.`,pron:`na-hi-TA-ji po-LI-si`},
        {tgt:`Kuna moto!`,src:`Há fogo!`,pron:`KU-na MO-to`},
        {tgt:`Nimepotea.`,src:`Estou perdido/a.`,pron:`ni-me-po-TE-a`},
        {tgt:`Simu yangu imepotea.`,src:`Meu telefone desapareceu.`,pron:`SI-mu YAN-gu i-me-po-TE-a`},
      ],
      conversation: [
      ],
    },
    {
      day: 21,
      title: `Clima e natureza`,
      titleNative: `Hali ya hewa na mazingira`,
      focus: `Hoje você aprende a falar sobre clima durante um passeio em Arusha ou perto do Kilimanjaro. Isso ajuda a planejar roupas, transporte e atividades ao ar livre.`,
      grammar: `Para falar do tempo, “kuna” aparece de novo: “kuna jua”, há sol; “kuna baridi”, está frio. “Mvua inanyesha” é uma frase fixa para “está chovendo”. Em contextos de viagem, essas frases ajudam a confirmar se um passeio deve acontecer.`,
      vocab: [
        {tgt:`hali ya hewa`,src:`clima / tempo`,pron:`HA-li ya HE-wa`},
        {tgt:`jua`,src:`sol`,pron:`JU-a`},
        {tgt:`mvua`,src:`chuva`,pron:`m-VU-a`},
        {tgt:`upepo`,src:`vento`,pron:`u-PE-po`},
        {tgt:`baridi`,src:`frio`,pron:`ba-RI-di`},
        {tgt:`joto`,src:`calor`,pron:`JO-to`},
        {tgt:`mawingu`,src:`nuvens`,pron:`ma-WIN-gu`},
        {tgt:`mlima`,src:`montanha`,pron:`m-LI-ma`},
        {tgt:`ziwa`,src:`lago`,pron:`ZI-wa`},
        {tgt:`msitu`,src:`floresta`,pron:`m-SI-tu`},
      ],
      phrases: [
        {tgt:`Leo kuna jua.`,src:`Hoje há sol.`,pron:`LE-o KU-na JU-a`},
        {tgt:`Mvua inanyesha.`,src:`Está chovendo.`,pron:`m-VU-a i-na-NYE-sha`},
        {tgt:`Kuna baridi sana.`,src:`Está muito frio.`,pron:`KU-na ba-RI-di SA-na`},
        {tgt:`Kuna joto.`,src:`Está calor.`,pron:`KU-na JO-to`},
        {tgt:`Mlima uko karibu?`,src:`A montanha fica perto?`,pron:`m-LI-ma U-ko ka-RI-bu`},
        {tgt:`Nahitaji koti.`,src:`Preciso de um casaco.`,pron:`na-hi-TA-ji KO-ti`},
      ],
      conversation: [
      ],
    },
    {
      day: 22,
      title: `Turismo e passeios`,
      titleNative: `Utalii na matembezi`,
      focus: `Hoje você aprende frases para reservar passeios em Zanzibar ou safáris perto de Arusha. Você vai perguntar duração, preço, guia e horário de saída.`,
      grammar: `“Kufanya” significa fazer, e aparece em muitas expressões: “kufanya matembezi”, fazer um passeio. “Naweza...” significa “posso...?”, uma forma essencial para pedir permissão. “Kupiga picha” significa literalmente “bater foto”, ou seja, tirar foto.`,
      vocab: [
        {tgt:`utalii`,src:`turismo`,pron:`u-ta-LI-i`},
        {tgt:`matembezi`,src:`passeio / caminhada`,pron:`ma-tem-BE-zi`},
        {tgt:`mwongozo`,src:`guia / orientação`,pron:`m-won-GO-zo`},
        {tgt:`kiongozi`,src:`guia / líder`,pron:`ki-on-GO-zi`},
        {tgt:`hifadhi`,src:`parque / reserva`,pron:`hi-FA-dhi`},
        {tgt:`wanyama`,src:`animais`,pron:`wa-NYA-ma`},
        {tgt:`picha`,src:`foto`,pron:`PI-cha`},
        {tgt:`kamera`,src:`câmera`,pron:`KA-me-ra`},
        {tgt:`muda`,src:`tempo / duração`,pron:`MU-da`},
        {tgt:`gharama`,src:`custo`,pron:`gha-RA-ma`},
      ],
      phrases: [
        {tgt:`Nataka kufanya matembezi.`,src:`Quero fazer um passeio.`,pron:`na-TA-ka ku-FAN-ya ma-tem-BE-zi`},
        {tgt:`Gharama ni kiasi gani?`,src:`Quanto é o custo?`,pron:`gha-RA-ma ni ki-A-si GA-ni`},
        {tgt:`Safari itachukua muda gani?`,src:`Quanto tempo a viagem vai levar?`,pron:`sa-FA-ri i-ta-CHU-ku-a MU-da GA-ni`},
        {tgt:`Kiongozi yuko wapi?`,src:`Onde está o guia?`,pron:`ki-on-GO-zi YU-ko WA-pi`},
        {tgt:`Naweza kupiga picha?`,src:`Posso tirar foto?`,pron:`na-WE-za ku-PI-ga PI-cha`},
        {tgt:`Tunaanza saa ngapi?`,src:`A que horas começamos?`,pron:`tu-na-AN-za SA-a NGA-pi`},
      ],
      conversation: [
      ],
    },
    {
      day: 23,
      title: `Pequena conversa com moradores`,
      titleNative: `Mazungumzo mafupi na wenyeji`,
      focus: `Hoje você aprende frases para conversar com moradores em cafés, lojas ou passeios em Lamu, Quênia. O objetivo é soar amigável sem invadir demais.`,
      grammar: `“Ninatoka...” significa “eu venho de...” ou “sou de...”. “Hapa” significa “aqui”, e “cha hapa” significa “daqui”. Dizer “Ninasema Kiswahili kidogo” costuma gerar simpatia, pois mostra esforço.`,
      vocab: [
        {tgt:`mwenyeji`,src:`morador/local`,pron:`m-we-NYE-ji`},
        {tgt:`mji`,src:`cidade`,pron:`m-JI`},
        {tgt:`nchi`,src:`país`,pron:`n-CHI`},
        {tgt:`familia`,src:`família`,pron:`fa-MI-li-a`},
        {tgt:`kazi`,src:`trabalho`,pron:`KA-zi`},
        {tgt:`lugha`,src:`língua`,pron:`LU-gha`},
        {tgt:`kidogo`,src:`um pouco`,pron:`ki-DO-go`},
        {tgt:`napenda`,src:`eu gosto`,pron:`na-PEN-da`},
        {tgt:`nzuri`,src:`bom / bonito`,pron:`NZU-ri`},
        {tgt:`karimu`,src:`generoso / acolhedor`,pron:`ka-RI-mu`},
      ],
      phrases: [
        {tgt:`Mji huu ni mzuri.`,src:`Esta cidade é bonita.`,pron:`m-JI hu-u ni m-ZU-ri`},
        {tgt:`Watu ni wakarimu.`,src:`As pessoas são acolhedoras.`,pron:`WA-tu ni wa-ka-RI-mu`},
        {tgt:`Ninasema Kiswahili kidogo.`,src:`Falo um pouco de suaíli.`,pron:`ni-na-SE-ma Ki-swa-HI-li ki-DO-go`},
        {tgt:`Unatoka wapi?`,src:`De onde você é?`,pron:`u-na-TO-ka WA-pi`},
        {tgt:`Ninatoka Ureno.`,src:`Sou de Portugal.`,pron:`ni-na-TO-ka u-RE-no`},
        {tgt:`Napenda chakula cha hapa.`,src:`Gosto da comida daqui.`,pron:`na-PEN-da cha-KU-la cha HA-pa`},
      ],
      conversation: [
      ],
    },
    {
      day: 24,
      title: `Convites e planos sociais`,
      titleNative: `Mialiko na mipango ya kijamii`,
      focus: `Hoje você aprende frases para aceitar ou recusar convites em Nairobi. Use-as quando alguém sugerir chá, almoço, música ao vivo ou um passeio.`,
      grammar: `“Naweza” é “posso”, e “siwezi” é “não posso”. Para recusar de forma educada, combine “Siwezi leo” com “Asante kwa mwaliko”. “Tunywe chai?” é uma forma natural de sugerir “Vamos tomar chá?”.`,
      vocab: [
        {tgt:`mwaliko`,src:`convite`,pron:`m-wa-LI-ko`},
        {tgt:`karamu`,src:`festa / celebração`,pron:`ka-RA-mu`},
        {tgt:`muziki`,src:`música`,pron:`mu-ZI-ki`},
        {tgt:`chakula cha mchana`,src:`almoço`,pron:`cha-KU-la cha m-CHA-na`},
        {tgt:`chakula cha jioni`,src:`jantar`,pron:`cha-KU-la cha ji-O-ni`},
        {tgt:`leo`,src:`hoje`,pron:`LE-o`},
        {tgt:`kesho`,src:`amanhã`,pron:`KE-sho`},
        {tgt:`naweza`,src:`posso`,pron:`na-WE-za`},
        {tgt:`siwezi`,src:`não posso`,pron:`si-WE-zi`},
        {tgt:`labda`,src:`talvez`,pron:`LAB-da`},
      ],
      phrases: [
        {tgt:`Una mpango leo?`,src:`Você tem planos hoje?`,pron:`U-na m-PAN-go LE-o`},
        {tgt:`Tunywe chai?`,src:`Vamos tomar chá?`,pron:`TU-nywe CHAI`},
        {tgt:`Ningependa sana.`,src:`Eu gostaria muito.`,pron:`nin-ge-PEN-da SA-na`},
        {tgt:`Siwezi leo.`,src:`Não posso hoje.`,pron:`si-WE-zi LE-o`},
        {tgt:`Labda kesho.`,src:`Talvez amanhã.`,pron:`LAB-da KE-sho`},
        {tgt:`Asante kwa mwaliko.`,src:`Obrigado/a pelo convite.`,pron:`a-SAN-te kwa m-wa-LI-ko`},
      ],
      conversation: [
      ],
    },
    {
      day: 25,
      title: `Telefone e internet`,
      titleNative: `Simu na intaneti`,
      focus: `Hoje você aprende frases para comprar chip local, pedir Wi-Fi e resolver problemas de internet em Dar es Salaam. Isso é essencial para mapas, transporte e reservas.`,
      grammar: `“Haina” significa “não tem” para muitos objetos, como “simu haina chaji”, o telefone não tem carga. “Zaidi” novamente significa “mais”. “Nenosiri” é literalmente “palavra secreta”, usada para senha.`,
      vocab: [
        {tgt:`simu`,src:`telefone`,pron:`SI-mu`},
        {tgt:`intaneti`,src:`internet`,pron:`in-ta-NE-ti`},
        {tgt:`Wi-Fi`,src:`Wi-Fi`,pron:`WAI-fai`},
        {tgt:`nenosiri`,src:`senha`,pron:`ne-no-SI-ri`},
        {tgt:`chaji`,src:`carga / carregamento`,pron:`CHA-ji`},
        {tgt:`betri`,src:`bateria`,pron:`BE-tri`},
        {tgt:`kadi ya simu`,src:`chip / cartão SIM`,pron:`KA-di ya SI-mu`},
        {tgt:`data`,src:`dados móveis`,pron:`DA-ta`},
        {tgt:`haraka`,src:`rápido`,pron:`ha-RA-ka`},
        {tgt:`polepole`,src:`devagar`,pron:`po-le-PO-le`},
      ],
      phrases: [
        {tgt:`Nahitaji kadi ya simu.`,src:`Preciso de um chip.`,pron:`na-hi-TA-ji KA-di ya SI-mu`},
        {tgt:`Wi-Fi iko?`,src:`Tem Wi-Fi?`,pron:`WAI-fai I-ko`},
        {tgt:`Nenosiri ni nini?`,src:`Qual é a senha?`,pron:`ne-no-SI-ri ni NI-ni`},
        {tgt:`Intaneti ni polepole.`,src:`A internet está lenta.`,pron:`in-ta-NE-ti ni po-le-PO-le`},
        {tgt:`Simu yangu haina chaji.`,src:`Meu telefone está sem bateria.`,pron:`SI-mu YAN-gu ha-I-na CHA-ji`},
        {tgt:`Nahitaji data zaidi.`,src:`Preciso de mais dados.`,pron:`na-hi-TA-ji DA-ta za-I-di`},
      ],
      conversation: [
      ],
    },
    {
      day: 26,
      title: `Lavanderia e serviços`,
      titleNative: `Kufua na huduma`,
      focus: `Hoje você aprende frases para serviços práticos em hotéis e bairros de Zanzibar. Você vai pedir lavanderia, conserto simples, limpeza e informações de horário.`,
      grammar: `“Hizi” significa “estes/estas” para muitos objetos plurais, como “nguo hizi”. “Tayari” significa “pronto”. A pergunta “Zitakuwa tayari lini?” é muito útil para lavanderia, consertos e pedidos que precisam ficar prontos.`,
      vocab: [
        {tgt:`huduma`,src:`serviço`,pron:`hu-DU-ma`},
        {tgt:`kufua`,src:`lavar roupa`,pron:`ku-FU-a`},
        {tgt:`nguo chafu`,src:`roupa suja`,pron:`n-GU-o CHA-fu`},
        {tgt:`nguo safi`,src:`roupa limpa`,pron:`n-GU-o SA-fi`},
        {tgt:`saa`,src:`hora`,pron:`SA-a`},
        {tgt:`leo`,src:`hoje`,pron:`LE-o`},
        {tgt:`kesho`,src:`amanhã`,pron:`KE-sho`},
        {tgt:`gharama`,src:`custo`,pron:`gha-RA-ma`},
        {tgt:`haraka`,src:`rápido`,pron:`ha-RA-ka`},
        {tgt:`tayari`,src:`pronto`,pron:`ta-YA-ri`},
      ],
      phrases: [
        {tgt:`Nahitaji kufua nguo.`,src:`Preciso lavar roupa.`,pron:`na-hi-TA-ji ku-FU-a n-GU-o`},
        {tgt:`Nguo hizi ni chafu.`,src:`Estas roupas estão sujas.`,pron:`n-GU-o HI-zi ni CHA-fu`},
        {tgt:`Zitakuwa tayari lini?`,src:`Quando ficarão prontas?`,pron:`zi-ta-KU-wa ta-YA-ri LI-ni`},
        {tgt:`Gharama ni kiasi gani?`,src:`Quanto custa?`,pron:`gha-RA-ma ni ki-A-si GA-ni`},
        {tgt:`Naweza kupata leo?`,src:`Posso receber hoje?`,pron:`na-WE-za ku-PA-ta LE-o`},
        {tgt:`Asante kwa huduma.`,src:`Obrigado/a pelo serviço.`,pron:`a-SAN-te kwa hu-DU-ma`},
      ],
      conversation: [
      ],
    },
    {
      day: 27,
      title: `Segurança e limites`,
      titleNative: `Usalama na mipaka`,
      focus: `Hoje você aprende a falar sobre segurança pessoal em mercados, ruas e transportes em cidades como Nairobi e Dar es Salaam. O foco é ser firme, educado e claro.`,
      grammar: `“Sitaki” é o negativo de “nataka”: eu não quero. “Acha” é uma palavra direta para “pare” ou “deixe”. Em situações desconfortáveis, uma frase curta como “Hapana, asante” pode ser repetida com firmeza.`,
      vocab: [
        {tgt:`usalama`,src:`segurança`,pron:`u-sa-LA-ma`},
        {tgt:`salama`,src:`seguro`,pron:`sa-LA-ma`},
        {tgt:`hapana`,src:`não`,pron:`ha-PA-na`},
        {tgt:`acha`,src:`pare / deixe`,pron:`A-cha`},
        {tgt:`tafadhali`,src:`por favor`,pron:`ta-fa-DHA-li`},
        {tgt:`peke yangu`,src:`sozinho/a`,pron:`PE-ke YAN-gu`},
        {tgt:`sitaki`,src:`não quero`,pron:`si-TA-ki`},
        {tgt:`naogopa`,src:`estou com medo`,pron:`na-o-GO-pa`},
        {tgt:`rafiki`,src:`amigo/a`,pron:`ra-FI-ki`},
        {tgt:`msaada`,src:`ajuda`,pron:`m-SA-a-da`},
      ],
      phrases: [
        {tgt:`Hapana, asante.`,src:`Não, obrigado/a.`,pron:`ha-PA-na a-SAN-te`},
        {tgt:`Sitaki, tafadhali.`,src:`Não quero, por favor.`,pron:`si-TA-ki ta-fa-DHA-li`},
        {tgt:`Acha, tafadhali.`,src:`Pare, por favor.`,pron:`A-cha ta-fa-DHA-li`},
        {tgt:`Niko peke yangu.`,src:`Estou sozinho/a.`,pron:`NI-ko PE-ke YAN-gu`},
        {tgt:`Nahitaji msaada.`,src:`Preciso de ajuda.`,pron:`na-hi-TA-ji m-SA-a-da`},
        {tgt:`Hapa ni salama?`,src:`Aqui é seguro?`,pron:`HA-pa ni sa-LA-ma`},
      ],
      conversation: [
      ],
    },
    {
      day: 28,
      title: `Contar experiências`,
      titleNative: `Kusimulia uzoefu`,
      focus: `Hoje você aprende a falar sobre o que fez durante a viagem em Zanzibar, Arusha ou Mombasa. Isso ajuda em conversas com guias, anfitriões e outros viajantes.`,
      grammar: `O passado em muitas frases usa “li” dentro do verbo: “nilikwenda”, eu fui; “nilikula”, eu comi; “niliona”, eu vi. Você não precisa dominar tudo de uma vez, mas reconhecer “nili-” ajuda a falar sobre ontem e experiências recentes.`,
      vocab: [
        {tgt:`nilikwenda`,src:`eu fui`,pron:`ni-li-KWEN-da`},
        {tgt:`niliona`,src:`eu vi`,pron:`ni-li-O-na`},
        {tgt:`nilikula`,src:`eu comi`,pron:`ni-li-KU-la`},
        {tgt:`nilipenda`,src:`eu gostei`,pron:`ni-li-PEN-da`},
        {tgt:`bahari`,src:`mar`,pron:`ba-HA-ri`},
        {tgt:`mlima`,src:`montanha`,pron:`m-LI-ma`},
        {tgt:`safari`,src:`safári / viagem`,pron:`sa-FA-ri`},
        {tgt:`jana`,src:`ontem`,pron:`JA-na`},
        {tgt:`leo`,src:`hoje`,pron:`LE-o`},
        {tgt:`nzuri`,src:`bom / bonito`,pron:`NZU-ri`},
      ],
      phrases: [
        {tgt:`Jana nilikwenda sokoni.`,src:`Ontem fui ao mercado.`,pron:`JA-na ni-li-KWEN-da SO-ko-ni`},
        {tgt:`Niliona bahari.`,src:`Vi o mar.`,pron:`ni-li-O-na ba-HA-ri`},
        {tgt:`Nilikula samaki.`,src:`Comi peixe.`,pron:`ni-li-KU-la sa-MA-ki`},
        {tgt:`Nilipenda sana.`,src:`Gostei muito.`,pron:`ni-li-PEN-da SA-na`},
        {tgt:`Safari ilikuwa nzuri.`,src:`O safári foi bom.`,pron:`sa-FA-ri i-li-KU-wa NZU-ri`},
        {tgt:`Leo ninapumzika.`,src:`Hoje estou descansando.`,pron:`LE-o ni-na-pum-ZI-ka`},
      ],
      conversation: [
      ],
    },
    {
      day: 29,
      title: `Planos futuros`,
      titleNative: `Mipango ya baadaye`,
      focus: `Hoje você aprende a falar sobre o que fará amanhã ou depois em uma viagem pela Tanzânia ou Quênia. Isso ajuda a organizar passeios, transporte e encontros.`,
      grammar: `O futuro geralmente usa “ta” dentro do verbo: “nitaenda”, eu irei; “nitakula”, eu comerei. “Nitakaa” pode significar “ficarei” ou “morarei”, dependendo do contexto. Para viagens, combine futuro com palavras de tempo como “kesho” e “baadaye”.`,
      vocab: [
        {tgt:`nitaenda`,src:`eu irei`,pron:`ni-ta-EN-da`},
        {tgt:`nitakula`,src:`eu comerei`,pron:`ni-ta-KU-la`},
        {tgt:`nitaona`,src:`eu verei`,pron:`ni-ta-O-na`},
        {tgt:`nitakaa`,src:`eu ficarei`,pron:`ni-ta-KA-a`},
        {tgt:`kesho`,src:`amanhã`,pron:`KE-sho`},
        {tgt:`baadaye`,src:`mais tarde`,pron:`ba-a-DA-ye`},
        {tgt:`wiki`,src:`semana`,pron:`WI-ki`},
        {tgt:`mwezi`,src:`mês`,pron:`MWE-zi`},
        {tgt:`mpango`,src:`plano`,pron:`m-PAN-go`},
        {tgt:`mapema`,src:`cedo`,pron:`ma-PE-ma`},
      ],
      phrases: [
        {tgt:`Kesho nitaenda Zanzibar.`,src:`Amanhã irei a Zanzibar.`,pron:`KE-sho ni-ta-EN-da Zan-zi-BAR`},
        {tgt:`Nitakula chakula cha hapa.`,src:`Comerei comida local.`,pron:`ni-ta-KU-la cha-KU-la cha HA-pa`},
        {tgt:`Nitaona mlima.`,src:`Verei a montanha.`,pron:`ni-ta-O-na m-LI-ma`},
        {tgt:`Nitakaa hapa siku mbili.`,src:`Ficarei aqui dois dias.`,pron:`ni-ta-KA-a HA-pa SI-ku MBI-li`},
        {tgt:`Nitaondoka mapema.`,src:`Partirei cedo.`,pron:`ni-ta-on-DO-ka ma-PE-ma`},
        {tgt:`Mpango wangu ni rahisi.`,src:`Meu plano é simples.`,pron:`m-PAN-go WAN-gu ni ra-HI-si`},
      ],
      conversation: [
      ],
    },
    {
      day: 30,
      title: `Revisão para viajar com confiança`,
      titleNative: `Marudio ya kusafiri kwa ujasiri`,
      focus: `Hoje você revisa frases essenciais para viajar por países onde o suaíli é falado, especialmente Tanzânia e Quênia. O objetivo é combinar cumprimentos, pedidos, perguntas e respostas em interações completas.`,
      grammar: `“Sielewi” é uma frase essencial: “não entendo”. Em vez de trocar imediatamente para outra língua, você pode dizer “Tafadhali, sema polepole” ou “Rudia, tafadhali”. Isso mantém a conversa em suaíli e mostra respeito pelo idioma local.`,
      vocab: [
        {tgt:`safari`,src:`viagem`,pron:`sa-FA-ri`},
        {tgt:`ujasiri`,src:`confiança / coragem`,pron:`u-ja-SI-ri`},
        {tgt:`swali`,src:`pergunta`,pron:`SWA-li`},
        {tgt:`jibu`,src:`resposta`,pron:`JI-bu`},
        {tgt:`elewa`,src:`entender`,pron:`e-LE-wa`},
        {tgt:`sema`,src:`falar`,pron:`SE-ma`},
        {tgt:`polepole`,src:`devagar`,pron:`po-le-PO-le`},
        {tgt:`rudia`,src:`repetir`,pron:`ru-DI-a`},
        {tgt:`tayari`,src:`pronto`,pron:`ta-YA-ri`},
        {tgt:`karibu`,src:`bem-vindo/a`,pron:`ka-RI-bu`},
      ],
      phrases: [
        {tgt:`Sielewi.`,src:`Não entendo.`,pron:`si-e-LE-wi`},
        {tgt:`Tafadhali, sema polepole.`,src:`Por favor, fale devagar.`,pron:`ta-fa-DHA-li SE-ma po-le-PO-le`},
        {tgt:`Rudia, tafadhali.`,src:`Repita, por favor.`,pron:`ru-DI-a ta-fa-DHA-li`},
        {tgt:`Niko tayari.`,src:`Estou pronto/a.`,pron:`NI-ko ta-YA-ri`},
        {tgt:`Nina swali.`,src:`Tenho uma pergunta.`,pron:`NI-na SWA-li`},
        {tgt:`Asante kwa msaada wako.`,src:`Obrigado/a pela sua ajuda.`,pron:`a-SAN-te kwa m-SA-a-da WA-ko`},
      ],
      conversation: [
      ],
    },
  ]
};