var COURSE_NL_HI = [
  {
    title: "Begroeten en afscheid nemen",
    titleNative: "नमस्ते और अलविदा",
    focus: "Je begint met beleefde begroetingen die je meteen kunt gebruiken in Delhi, Jaipur of Varanasi. Je leert hoe je iemand vriendelijk aanspreekt zonder te informeel te klinken.",
    vocab: [
      {hi: "नमस्ते", nl: "hallo / dag", ipa: "nə-məs-tee"},
      {hi: "धन्यवाद", nl: "dank u / bedankt", ipa: "dhən-yə-vaad"},
      {hi: "कृपया", nl: "alstublieft", ipa: "krip-yaa"},
      {hi: "हाँ", nl: "ja", ipa: "haan"},
      {hi: "नहीं", nl: "nee", ipa: "nə-heen"},
      {hi: "जी", nl: "beleefdheidswoord", ipa: "djee"},
      {hi: "अलविदा", nl: "tot ziens", ipa: "əl-vi-daa"},
      {hi: "माफ़ कीजिए", nl: "sorry / excuseer", ipa: "maaf kie-djie-je"},
      {hi: "दोस्त", nl: "vriend", ipa: "dost"},
    ],
    phrases: [
      {hi: "नमस्ते जी।", nl: "Hallo.", ipa: "nə-məs-tee djee"},
      {hi: "धन्यवाद।", nl: "Dank u.", ipa: "dhən-yə-vaad"},
      {hi: "कृपया फिर से कहिए।", nl: "Zeg het alstublieft nog een keer.", ipa: "krip-yaa phir see kə-hi-je"},
      {hi: "माफ़ कीजिए।", nl: "Excuseer mij.", ipa: "maaf kie-djie-je"},
      {hi: "अलविदा, फिर मिलेंगे।", nl: "Tot ziens, we zien elkaar weer.", ipa: "əl-vi-daa, phir mi-len-gee"},
    ],
    grammar: "In Hindi voeg je vaak जी toe om beleefd te klinken, vooral tegen onbekenden, ouderen of personeel. नमस्ते जी klinkt vriendelijker dan alleen नमस्ते. In India wordt beleefdheid vaak gewaardeerd in dagelijkse situaties zoals winkels, hotels en taxi’s.",
    practice: [
      "1. Zeg in het Hindi beleefd hallo tegen een hotelmedewerker.",
      "2. Zeg bedankt tegen iemand die je helpt.",
      "3. Vraag iemand beleefd om iets te herhalen.",
      "4. Combineer नमस्ते met जी.",
      "5. Oefen het verschil tussen हाँ en नहीं hardop.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Jezelf voorstellen",
    titleNative: "अपना परिचय देना",
    focus: "Vandaag leer je jezelf kort voorstellen in Mumbai of Delhi. Dit helpt bij hotels, rondleidingen en gesprekken met locals.",
    vocab: [
      {hi: "मैं", nl: "ik", ipa: "main"},
      {hi: "आप", nl: "u / jij beleefd", ipa: "aap"},
      {hi: "नाम", nl: "naam", ipa: "naam"},
      {hi: "मेरा", nl: "mijn", ipa: "mee-raa"},
      {hi: "आपका", nl: "uw / jouw", ipa: "aap-kaa"},
      {hi: "है", nl: "is / ben", ipa: "hai"},
      {hi: "से", nl: "uit / vandaan", ipa: "see"},
      {hi: "नीदरलैंड", nl: "Nederland", ipa: "nie-dər-lənd"},
      {hi: "यात्री", nl: "reiziger", ipa: "yaa-trie"},
      {hi: "खुशी", nl: "plezier", ipa: "khoe-shie"},
    ],
    phrases: [
      {hi: "मेरा नाम जान है।", nl: "Mijn naam is Jan.", ipa: "mee-raa naam djaan hai"},
      {hi: "आपका नाम क्या है?", nl: "Hoe heet u?", ipa: "aap-kaa naam kyaa hai"},
      {hi: "मैं नीदरलैंड से हूँ।", nl: "Ik kom uit Nederland.", ipa: "main nie-dər-lənd see hoen"},
      {hi: "आपसे मिलकर खुशी हुई।", nl: "Leuk u te ontmoeten.", ipa: "aap-see mil-kər khoe-shie hoe-ie"},
      {hi: "मैं यात्री हूँ।", nl: "Ik ben een reiziger.", ipa: "main yaa-trie hoen"},
    ],
    grammar: "De basiszin in Hindi heeft vaak de volgorde onderwerp-object-werkwoord. Waar je in het Nederlands zegt “Mijn naam is Jan”, zeg je in Hindi letterlijk “Mijn naam Jan is”: मेरा नाम जान है. Het werkwoord staat vaak aan het einde van de zin.",
    practice: [
      "1. Stel jezelf voor met मेरा नाम.",
      "2. Vraag iemand beleefd naar zijn of haar naam.",
      "3. Zeg dat je uit Nederland komt.",
      "4. Maak een korte begroeting met नमस्ते en je naam.",
      "5. Oefen de zin आपसे मिलकर खुशी हुई drie keer langzaam.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Essentiële beleefde vragen",
    titleNative: "ज़रूरी विनम्र सवाल",
    focus: "Je leert korte vragen die handig zijn in bijna elke reissituatie in Noord-India. Deze zinnen helpen wanneer je iets niet begrijpt of hulp nodig hebt.",
    vocab: [
      {hi: "क्या", nl: "wat / vraagwoord", ipa: "kyaa"},
      {hi: "कहाँ", nl: "waar", ipa: "kə-haan"},
      {hi: "कौन", nl: "wie", ipa: "kaun"},
      {hi: "कब", nl: "wanneer", ipa: "kəb"},
      {hi: "कैसे", nl: "hoe", ipa: "kai-see"},
      {hi: "ठीक", nl: "goed / oké", ipa: "thiek"},
      {hi: "मदद", nl: "hulp", ipa: "mə-dəd"},
      {hi: "समस्या", nl: "probleem", ipa: "sə-məs-yaa"},
      {hi: "धीरे", nl: "langzaam", ipa: "dhie-ree"},
      {hi: "समझ", nl: "begrip", ipa: "sə-mədj"},
    ],
    phrases: [
      {hi: "क्या आप मेरी मदद कर सकते हैं?", nl: "Kunt u mij helpen?", ipa: "kyaa aap mee-rie mə-dəd kər sək-tee hain"},
      {hi: "यह क्या है?", nl: "Wat is dit?", ipa: "yəh kyaa hai"},
      {hi: "कहाँ है?", nl: "Waar is het?", ipa: "kə-haan hai"},
      {hi: "धीरे बोलिए।", nl: "Spreek langzaam alstublieft.", ipa: "dhie-ree bo-lie-je"},
      {hi: "मुझे समझ नहीं आया।", nl: "Ik heb het niet begrepen.", ipa: "moe-djhee sə-mədj nə-heen aa-yaa"},
    ],
    grammar: "क्या aan het begin van een zin maakt vaak een ja/nee-vraag. क्या आप मेरी मदद कर सकते हैं? betekent letterlijk “Kunt u mijn hulp doen?”, maar natuurlijk zeg je in het Nederlands “Kunt u mij helpen?” Leer deze zin als vaste reiszin.",
    practice: [
      "1. Vraag iemand of die u kan helpen.",
      "2. Zeg dat u iets niet begrepen hebt.",
      "3. Vraag waar iets is met कहाँ है.",
      "4. Maak een vraag met क्या.",
      "5. Oefen langzaam spreken vragen met धीरे बोलिए.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Getallen van 0 tot 20",
    titleNative: "शून्य से बीस तक संख्या",
    focus: "Getallen zijn nodig voor prijzen, kamernummers, tickets en telefoonnummers. Vandaag leer je de basisgetallen die je vaak hoort in markten en stations.",
    vocab: [
      {hi: "शून्य", nl: "nul", ipa: "shoen-yə"},
      {hi: "एक", nl: "één", ipa: "eek"},
      {hi: "दो", nl: "twee", ipa: "do"},
      {hi: "तीन", nl: "drie", ipa: "tien"},
      {hi: "चार", nl: "vier", ipa: "tsjaar"},
      {hi: "पाँच", nl: "vijf", ipa: "paantsj"},
      {hi: "छह", nl: "zes", ipa: "tsjəh"},
      {hi: "सात", nl: "zeven", ipa: "saat"},
      {hi: "आठ", nl: "acht", ipa: "aath"},
      {hi: "दस", nl: "tien", ipa: "dəs"},
    ],
    phrases: [
      {hi: "एक टिकट चाहिए।", nl: "Ik wil één ticket.", ipa: "eek ti-kət tsjaa-hi-je"},
      {hi: "दो चाय, कृपया।", nl: "Twee thee, alstublieft.", ipa: "do tsjaai, krip-yaa"},
      {hi: "कितने रुपये?", nl: "Hoeveel roepies?", ipa: "kit-nee roe-pə-je"},
      {hi: "मेरा कमरा पाँच है।", nl: "Mijn kamer is vijf.", ipa: "mee-raa kəm-raa paantsj hai"},
      {hi: "तीन लोग हैं।", nl: "We zijn met drie personen.", ipa: "tien log hain"},
    ],
    grammar: "Hindi-getallen hebben vaste vormen die je veel in prijzen hoort. रुपये betekent roepies en komt vaak na het getal of de prijs. Let op dat लोग “mensen/personen” betekent en handig is voor restaurant- of hotelvragen.",
    practice: [
      "1. Tel hardop van één tot tien in Hindi.",
      "2. Bestel twee thee met दो चाय.",
      "3. Vraag hoeveel iets kost.",
      "4. Zeg dat er drie personen zijn.",
      "5. Maak drie korte zinnen met een getal.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Getallen, prijzen en geld",
    titleNative: "संख्या, दाम और पैसे",
    focus: "In winkels en op markten in Jaipur of Delhi moet je prijzen kunnen herkennen. Je leert vragen naar de prijs en betalen in roepies.",
    vocab: [
      {hi: "ग्यारह", nl: "elf", ipa: "gyaa-rəh"},
      {hi: "बारह", nl: "twaalf", ipa: "baa-rəh"},
      {hi: "तेरह", nl: "dertien", ipa: "tee-rəh"},
      {hi: "बीस", nl: "twintig", ipa: "bees"},
      {hi: "तीस", nl: "dertig", ipa: "tees"},
      {hi: "पचास", nl: "vijftig", ipa: "pə-tsjaas"},
      {hi: "सौ", nl: "honderd", ipa: "sau"},
      {hi: "रुपये", nl: "roepies", ipa: "roe-pə-je"},
      {hi: "पैसे", nl: "geld", ipa: "pai-see"},
      {hi: "महंगा", nl: "duur", ipa: "mə-hən-gaa"},
    ],
    phrases: [
      {hi: "यह कितने का है?", nl: "Hoeveel kost dit?", ipa: "yəh kit-nee kaa hai"},
      {hi: "बहुत महंगा है।", nl: "Het is erg duur.", ipa: "bə-hoet mə-hən-gaa hai"},
      {hi: "थोड़ा कम करिए।", nl: "Maak het iets goedkoper.", ipa: "tho-raa kəm kə-rie-je"},
      {hi: "मेरे पास पैसे हैं।", nl: "Ik heb geld bij me.", ipa: "mee-ree paas pai-see hain"},
      {hi: "पचास रुपये ठीक है।", nl: "Vijftig roepies is goed.", ipa: "pə-tsjaas roe-pə-je thiek hai"},
    ],
    grammar: "Bij onderhandelen op markten kun je beleefd blijven met करिए, een nette gebiedende vorm. थोड़ा कम करिए is een zachte manier om korting te vragen. In vaste winkels of moderne malls onderhandel je meestal niet.",
    practice: [
      "1. Vraag de prijs van een souvenir.",
      "2. Zeg dat iets te duur is.",
      "3. Vraag beleefd om een lagere prijs.",
      "4. Oefen पचास, सौ en रुपये samen.",
      "5. Speel een korte marktsituatie na.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Richtingen en plaatsen",
    titleNative: "दिशा और जगह",
    focus: "Vandaag leer je woorden om plaatsen te vinden in een stad als Delhi, Lucknow of Jaipur. Je kunt eenvoudige routevragen stellen.",
    vocab: [
      {hi: "कहाँ", nl: "waar", ipa: "kə-haan"},
      {hi: "यहाँ", nl: "hier", ipa: "yə-haan"},
      {hi: "वहाँ", nl: "daar", ipa: "və-haan"},
      {hi: "दाएँ", nl: "rechts", ipa: "daa-en"},
      {hi: "बाएँ", nl: "links", ipa: "baa-en"},
      {hi: "सीधा", nl: "rechtdoor", ipa: "sie-dhaa"},
      {hi: "पास", nl: "dichtbij / bij", ipa: "paas"},
      {hi: "दूर", nl: "ver", ipa: "door"},
      {hi: "सड़क", nl: "straat", ipa: "sə-rək"},
      {hi: "मोड़", nl: "bocht", ipa: "mor"},
    ],
    phrases: [
      {hi: "स्टेशन कहाँ है?", nl: "Waar is het station?", ipa: "stee-shən kə-haan hai"},
      {hi: "सीधा जाइए।", nl: "Ga rechtdoor.", ipa: "sie-dhaa djaa-ie-je"},
      {hi: "दाएँ मुड़िए।", nl: "Sla rechtsaf.", ipa: "daa-en mo-rie-je"},
      {hi: "बाएँ मुड़िए।", nl: "Sla linksaf.", ipa: "baa-en mo-rie-je"},
      {hi: "क्या यह पास है?", nl: "Is dit dichtbij?", ipa: "kyaa yəh paas hai"},
    ],
    grammar: "De beleefde instructievorm eindigt vaak op -इए, zoals जाइए en मुड़िए. Deze vorm hoor je veel wanneer iemand uitleg geeft. Je hoeft niet elk werkwoord te beheersen; leer reisroutes als vaste brokken.",
    practice: [
      "1. Vraag waar het station is.",
      "2. Geef iemand de instructie om rechtdoor te gaan.",
      "3. Zeg rechtsaf en linksaf in Hindi.",
      "4. Vraag of iets dichtbij is.",
      "5. Teken een kleine route en beschrijf die met drie Hindi-woorden.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Taxi, riksja en vervoer",
    titleNative: "टैक्सी, रिक्शा और यात्रा",
    focus: "In veel Indiase steden gebruik je taxi’s, autoriksja’s of appvervoer. Vandaag leer je instappen, een bestemming noemen en naar de prijs vragen.",
    vocab: [
      {hi: "टैक्सी", nl: "taxi", ipa: "tek-sie"},
      {hi: "रिक्शा", nl: "riksja", ipa: "rik-shaa"},
      {hi: "ऑटो", nl: "autoriksja", ipa: "au-to"},
      {hi: "मीटर", nl: "meter", ipa: "mie-tər"},
      {hi: "किराया", nl: "ritprijs", ipa: "ki-raa-yaa"},
      {hi: "चलना", nl: "gaan / rijden", ipa: "tsjəl-naa"},
      {hi: "हवाई अड्डा", nl: "luchthaven", ipa: "hə-vaai ə-ddaa"},
      {hi: "स्टेशन", nl: "station", ipa: "stee-shən"},
      {hi: "होटल", nl: "hotel", ipa: "ho-təl"},
      {hi: "जल्दी", nl: "snel", ipa: "djəl-die"},
    ],
    phrases: [
      {hi: "मुझे होटल जाना है।", nl: "Ik moet naar het hotel.", ipa: "moe-djhee ho-təl djaa-naa hai"},
      {hi: "मीटर से चलिए।", nl: "Rijd alstublieft op de meter.", ipa: "mie-tər see tsjə-lie-je"},
      {hi: "किराया कितना है?", nl: "Hoeveel is de ritprijs?", ipa: "ki-raa-yaa kit-naa hai"},
      {hi: "हवाई अड्डा चलिए।", nl: "Naar de luchthaven, alstublieft.", ipa: "hə-vaai ə-ddaa tsjə-lie-je"},
      {hi: "क्या आप जल्दी जा सकते हैं?", nl: "Kunt u snel gaan?", ipa: "kyaa aap djəl-die djaa sək-tee hain"},
    ],
    grammar: "मुझे ... जाना है betekent “Ik moet/wil naar ... gaan.” Je zet de bestemming tussen मुझे en जाना है. Dit is een zeer nuttige constructie voor taxi’s, metro’s en wandelroutes.",
    practice: [
      "1. Zeg dat je naar je hotel moet.",
      "2. Vraag naar de ritprijs.",
      "3. Vraag de chauffeur om op de meter te rijden.",
      "4. Zeg dat je naar het vliegveld wilt.",
      "5. Vervang होटल door स्टेशन in de zin.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Hotel en accommodatie",
    titleNative: "होटल और ठहरना",
    focus: "Je leert inchecken bij een hotel in Agra of Delhi. Je kunt je reservering noemen en vragen naar kamer, sleutel en wifi.",
    vocab: [
      {hi: "होटल", nl: "hotel", ipa: "ho-təl"},
      {hi: "कमरा", nl: "kamer", ipa: "kəm-raa"},
      {hi: "बुकिंग", nl: "boeking", ipa: "boek-ing"},
      {hi: "चाबी", nl: "sleutel", ipa: "tsjaa-bie"},
      {hi: "पासपोर्ट", nl: "paspoort", ipa: "paas-port"},
      {hi: "वाई-फाई", nl: "wifi", ipa: "vaai-faai"},
      {hi: "नाश्ता", nl: "ontbijt", ipa: "naash-taa"},
      {hi: "रात", nl: "nacht", ipa: "raat"},
      {hi: "आज", nl: "vandaag", ipa: "aadj"},
      {hi: "कल", nl: "morgen / gisteren", ipa: "kəl"},
    ],
    phrases: [
      {hi: "मेरी बुकिंग है।", nl: "Ik heb een boeking.", ipa: "mee-rie boek-ing hai"},
      {hi: "मेरा पासपोर्ट यहाँ है।", nl: "Mijn paspoort is hier.", ipa: "mee-raa paas-port yə-haan hai"},
      {hi: "कमरा नंबर क्या है?", nl: "Wat is het kamernummer?", ipa: "kəm-raa nəm-bər kyaa hai"},
      {hi: "वाई-फाई पासवर्ड क्या है?", nl: "Wat is het wifiwachtwoord?", ipa: "vaai-faai paas-vərd kyaa hai"},
      {hi: "नाश्ता कितने बजे है?", nl: "Hoe laat is het ontbijt?", ipa: "naash-taa kit-nee bə-djee hai"},
    ],
    grammar: "मेरी en मेरा betekenen allebei “mijn”, maar ze veranderen met het zelfstandig naamwoord. मेरी hoort bij vrouwelijke woorden zoals बुकिंग, en मेरा bij mannelijke woorden zoals पासपोर्ट. Als reiziger kun je de vaste combinaties gewoon uit je hoofd leren.",
    practice: [
      "1. Zeg dat je een boeking hebt.",
      "2. Vraag naar het wifiwachtwoord.",
      "3. Vraag naar je kamernummer.",
      "4. Zeg dat je paspoort hier is.",
      "5. Vraag hoe laat het ontbijt is.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Tijd en dagen",
    titleNative: "समय और दिन",
    focus: "Vandaag leer je tijden en dagen gebruiken voor treinen, tours en hotelafspraken. Dit is nuttig bij reserveringen in steden als Jaipur en Varanasi.",
    vocab: [
      {hi: "समय", nl: "tijd", ipa: "sə-məj"},
      {hi: "बजे", nl: "uur", ipa: "bə-djee"},
      {hi: "सुबह", nl: "ochtend", ipa: "soe-bəh"},
      {hi: "दोपहर", nl: "middag", ipa: "do-pə-hər"},
      {hi: "शाम", nl: "avond", ipa: "shaam"},
      {hi: "रात", nl: "nacht", ipa: "raat"},
      {hi: "आज", nl: "vandaag", ipa: "aadj"},
      {hi: "कल", nl: "morgen / gisteren", ipa: "kəl"},
      {hi: "सोमवार", nl: "maandag", ipa: "som-vaar"},
      {hi: "रविवार", nl: "zondag", ipa: "rə-vi-vaar"},
    ],
    phrases: [
      {hi: "कितने बजे?", nl: "Hoe laat?", ipa: "kit-nee bə-djee"},
      {hi: "सुबह नौ बजे।", nl: "Om negen uur ’s ochtends.", ipa: "soe-bəh nau bə-djee"},
      {hi: "आज शाम को।", nl: "Vanavond.", ipa: "aadj shaam ko"},
      {hi: "कल सुबह मिलते हैं।", nl: "We zien elkaar morgenochtend.", ipa: "kəl soe-bəh mil-tee hain"},
      {hi: "ट्रेन कब है?", nl: "Wanneer is de trein?", ipa: "treen kəb hai"},
    ],
    grammar: "को wordt vaak gebruikt om tijd aan te geven, zoals शाम को: in de avond. बजे gebruik je bij kloktijden. कल kan zowel morgen als gisteren betekenen; de context maakt duidelijk welke betekenis bedoeld wordt.",
    practice: [
      "1. Vraag hoe laat iets is.",
      "2. Zeg “om negen uur ’s ochtends”.",
      "3. Vraag wanneer de trein is.",
      "4. Zeg dat je iemand morgenmorgen ziet.",
      "5. Maak drie zinnen met सुबह, शाम en रात.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Eten en drinken bestellen",
    titleNative: "खाना और पीना मंगवाना",
    focus: "Je leert eten en drinken bestellen in een café in Delhi of Mumbai. Je gebruikt beleefde zinnen voor thee, water en eenvoudige gerechten.",
    vocab: [
      {hi: "खाना", nl: "eten", ipa: "khaa-naa"},
      {hi: "पीना", nl: "drinken", ipa: "pie-naa"},
      {hi: "पानी", nl: "water", ipa: "paa-nie"},
      {hi: "चाय", nl: "thee", ipa: "tsjaai"},
      {hi: "कॉफी", nl: "koffie", ipa: "ko-fie"},
      {hi: "दूध", nl: "melk", ipa: "doedh"},
      {hi: "चीनी", nl: "suiker", ipa: "tsjie-nie"},
      {hi: "रोटी", nl: "platbrood", ipa: "ro-tie"},
      {hi: "चावल", nl: "rijst", ipa: "tsjaa-vəl"},
      {hi: "सब्ज़ी", nl: "groentegerecht", ipa: "səb-zie"},
    ],
    phrases: [
      {hi: "मुझे चाय चाहिए।", nl: "Ik wil thee.", ipa: "moe-djhee tsjaai tsjaa-hi-je"},
      {hi: "पानी दीजिए।", nl: "Geef water alstublieft.", ipa: "paa-nie die-djie-je"},
      {hi: "बिना चीनी की चाय।", nl: "Thee zonder suiker.", ipa: "bi-naa tsjie-nie kie tsjaai"},
      {hi: "क्या खाना मिलेगा?", nl: "Welk eten is er?", ipa: "kyaa khaa-naa mi-lee-gaa"},
      {hi: "रोटी और सब्ज़ी चाहिए।", nl: "Ik wil roti en groente.", ipa: "ro-tie aur səb-zie tsjaa-hi-je"},
    ],
    grammar: "मुझे ... चाहिए betekent “Ik wil / ik heb ... nodig.” Dit is beleefd en heel bruikbaar in restaurants, winkels en stations. Zet het gewenste woord tussen मुझे en चाहिए.",
    practice: [
      "1. Bestel thee.",
      "2. Vraag om water.",
      "3. Vraag om thee zonder suiker.",
      "4. Bestel roti en groente.",
      "5. Maak drie zinnen met मुझे ... चाहिए.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Restaurantzinnen",
    titleNative: "रेस्टोरेंट के वाक्य",
    focus: "Vandaag leer je handige zinnen voor een restaurant in Lucknow of Jaipur. Je vraagt om een tafel, menu, rekening en vegetarische opties.",
    vocab: [
      {hi: "रेस्टोरेंट", nl: "restaurant", ipa: "res-to-rent"},
      {hi: "मेज़", nl: "tafel", ipa: "meez"},
      {hi: "कुर्सी", nl: "stoel", ipa: "koer-sie"},
      {hi: "मेन्यू", nl: "menu", ipa: "mee-njoe"},
      {hi: "बिल", nl: "rekening", ipa: "bil"},
      {hi: "स्वादिष्ट", nl: "lekker", ipa: "svaad-isht"},
      {hi: "शाकाहारी", nl: "vegetarisch", ipa: "shaa-kaa-haa-rie"},
      {hi: "मसालेदार", nl: "pittig", ipa: "mə-saa-lee-daar"},
      {hi: "कम", nl: "minder", ipa: "kəm"},
      {hi: "ज़्यादा", nl: "meer", ipa: "zyaa-daa"},
    ],
    phrases: [
      {hi: "दो लोगों के लिए मेज़ चाहिए।", nl: "Een tafel voor twee personen, graag.", ipa: "do lo-gon kee li-je meez tsjaa-hi-je"},
      {hi: "मेन्यू दीजिए।", nl: "Mag ik het menu?", ipa: "mee-njoe die-djie-je"},
      {hi: "क्या यह शाकाहारी है?", nl: "Is dit vegetarisch?", ipa: "kyaa yəh shaa-kaa-haa-rie hai"},
      {hi: "कम मसालेदार चाहिए।", nl: "Ik wil het minder pittig.", ipa: "kəm mə-saa-lee-daar tsjaa-hi-je"},
      {hi: "बिल दीजिए।", nl: "De rekening, alstublieft.", ipa: "bil die-djie-je"},
    ],
    grammar: "के लिए betekent “voor”. दो लोगों के लिए betekent “voor twee personen”. In restaurants kun je veel zinnen bouwen met चाहिए en दीजिए, zonder ingewikkelde werkwoordsvormen.",
    practice: [
      "1. Vraag om een tafel voor twee.",
      "2. Vraag of een gerecht vegetarisch is.",
      "3. Vraag om minder pittig eten.",
      "4. Vraag om de rekening.",
      "5. Maak een zin met के लिए.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Smaken en voorkeuren",
    titleNative: "स्वाद और पसंद",
    focus: "Je leert zeggen wat je lekker vindt en wat je liever niet wilt. Dit helpt wanneer je eten probeert in een Indiaas restaurant of bij een lokale familie.",
    vocab: [
      {hi: "पसंद", nl: "voorkeur / leuk vinden", ipa: "pə-sənd"},
      {hi: "नापसंद", nl: "niet leuk vinden", ipa: "naa-pə-sənd"},
      {hi: "मीठा", nl: "zoet", ipa: "mie-thaa"},
      {hi: "नमकीन", nl: "zoutig", ipa: "nəm-kien"},
      {hi: "खट्टा", nl: "zuur", ipa: "khət-taa"},
      {hi: "गरम", nl: "warm / heet", ipa: "gə-rəm"},
      {hi: "ठंडा", nl: "koud", ipa: "thən-daa"},
      {hi: "ताज़ा", nl: "vers", ipa: "taa-zaa"},
      {hi: "हल्का", nl: "licht / mild", ipa: "həl-kaa"},
      {hi: "भूख", nl: "honger", ipa: "bhoekh"},
    ],
    phrases: [
      {hi: "मुझे यह पसंद है।", nl: "Ik vind dit lekker/leuk.", ipa: "moe-djhee yəh pə-sənd hai"},
      {hi: "मुझे मसालेदार खाना पसंद है।", nl: "Ik hou van pittig eten.", ipa: "moe-djhee mə-saa-lee-daar khaa-naa pə-sənd hai"},
      {hi: "मुझे बहुत भूख लगी है।", nl: "Ik heb veel honger.", ipa: "moe-djhee bə-hoet bhoekh lə-gie hai"},
      {hi: "ठंडा पानी चाहिए।", nl: "Ik wil koud water.", ipa: "thən-daa paa-nie tsjaa-hi-je"},
      {hi: "कुछ हल्का चाहिए।", nl: "Ik wil iets lichts.", ipa: "koetsj həl-kaa tsjaa-hi-je"},
    ],
    grammar: "मुझे ... पसंद है betekent “Ik hou van ...” of “Ik vind ... leuk/lekker.” De ervaring ligt in Hindi vaak bij “aan mij is het aangenaam”, daarom begin je met मुझे. Gebruik deze structuur voor eten, plekken en activiteiten.",
    practice: [
      "1. Zeg dat je pittig eten lekker vindt.",
      "2. Vraag om koud water.",
      "3. Zeg dat je veel honger hebt.",
      "4. Zeg dat je iets lichts wilt.",
      "5. Noem drie smaken in Hindi.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Winkelen en souvenirs",
    titleNative: "खरीदारी और यादगार चीज़ें",
    focus: "Vandaag leer je shoppen op een markt in Jaipur of Delhi. Je vraagt naar maten, kleuren, prijzen en souvenirs.",
    vocab: [
      {hi: "दुकान", nl: "winkel", ipa: "doe-kaan"},
      {hi: "बाज़ार", nl: "markt", ipa: "baa-zaar"},
      {hi: "कीमत", nl: "prijs", ipa: "kie-mət"},
      {hi: "रंग", nl: "kleur", ipa: "rəng"},
      {hi: "कपड़ा", nl: "stof / kleding", ipa: "kəp-raa"},
      {hi: "छोटा", nl: "klein", ipa: "tsjo-taa"},
      {hi: "बड़ा", nl: "groot", ipa: "bə-raa"},
      {hi: "यादगार", nl: "souvenir", ipa: "yaad-gaar"},
      {hi: "सस्ता", nl: "goedkoop", ipa: "səs-taa"},
      {hi: "अच्छा", nl: "goed / mooi", ipa: "ə-tsjaa"},
    ],
    phrases: [
      {hi: "यह अच्छा है।", nl: "Dit is mooi/goed.", ipa: "yəh ə-tsjaa hai"},
      {hi: "कीमत क्या है?", nl: "Wat is de prijs?", ipa: "kie-mət kyaa hai"},
      {hi: "मुझे छोटा चाहिए।", nl: "Ik wil een kleinere.", ipa: "moe-djhee tsjo-taa tsjaa-hi-je"},
      {hi: "क्या दूसरा रंग है?", nl: "Is er een andere kleur?", ipa: "kyaa doe-sraa rəng hai"},
      {hi: "यह यादगार के लिए है।", nl: "Dit is als souvenir.", ipa: "yəh yaad-gaar kee li-je hai"},
    ],
    grammar: "अच्छा kan “goed”, “mooi” of “lekker” betekenen, afhankelijk van de context. In winkels is het een handig positief woord. छोटा en बड़ा veranderen soms met het zelfstandig naamwoord, maar als vaste reiszinnen zijn deze vormen begrijpelijk.",
    practice: [
      "1. Vraag naar de prijs.",
      "2. Vraag om een andere kleur.",
      "3. Zeg dat iets mooi is.",
      "4. Vraag om een kleinere versie.",
      "5. Speel een souvenirgesprek van vijf zinnen.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kleding en maten",
    titleNative: "कपड़े और साइज़",
    focus: "Je leert kleding kopen en passen in een Indiase winkel. Je kunt zeggen of iets te groot, te klein of precies goed is.",
    vocab: [
      {hi: "कपड़े", nl: "kleding", ipa: "kəp-ree"},
      {hi: "कमीज़", nl: "shirt", ipa: "kə-miez"},
      {hi: "पैंट", nl: "broek", ipa: "pent"},
      {hi: "जूते", nl: "schoenen", ipa: "djoe-tee"},
      {hi: "साइज़", nl: "maat", ipa: "saa-iz"},
      {hi: "लंबा", nl: "lang", ipa: "ləm-baa"},
      {hi: "छोटा", nl: "klein / kort", ipa: "tsjo-taa"},
      {hi: "ढीला", nl: "los", ipa: "dhie-laa"},
      {hi: "तंग", nl: "strak", ipa: "təng"},
      {hi: "बदलना", nl: "ruilen", ipa: "bəd-lə-naa"},
    ],
    phrases: [
      {hi: "क्या मैं इसे पहन सकता हूँ?", nl: "Kan ik dit passen?", ipa: "kyaa main i-see pə-hən sək-taa hoen"},
      {hi: "यह बहुत बड़ा है।", nl: "Dit is te groot.", ipa: "yəh bə-hoet bə-raa hai"},
      {hi: "यह बहुत छोटा है।", nl: "Dit is te klein.", ipa: "yəh bə-hoet tsjo-taa hai"},
      {hi: "दूसरा साइज़ है?", nl: "Is er een andere maat?", ipa: "doe-sraa saa-iz hai"},
      {hi: "मैं इसे खरीदना चाहता हूँ।", nl: "Ik wil dit kopen.", ipa: "main i-see khə-ried-naa tsjaah-taa hoen"},
    ],
    grammar: "चाहता हूँ betekent “ik wil” wanneer de spreker mannelijk is; चाहती हूँ wordt gebruikt door een vrouwelijke spreker. In reiscontexten kun je ook veilig मुझे ... चाहिए gebruiken, wat minder persoonsgebonden is.",
    practice: [
      "1. Vraag of je iets mag passen.",
      "2. Zeg dat iets te groot is.",
      "3. Vraag om een andere maat.",
      "4. Zeg dat je iets wilt kopen.",
      "5. Vervang बड़ा door छोटा in een zin.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Openbaar vervoer",
    titleNative: "सार्वजनिक परिवहन",
    focus: "Vandaag oefen je trein-, metro- en bustaal voor steden zoals Delhi en Mumbai. Je leert tickets kopen en perroninformatie vragen.",
    vocab: [
      {hi: "बस", nl: "bus", ipa: "bəs"},
      {hi: "ट्रेन", nl: "trein", ipa: "treen"},
      {hi: "मेट्रो", nl: "metro", ipa: "mee-tro"},
      {hi: "टिकट", nl: "ticket", ipa: "ti-kət"},
      {hi: "प्लेटफॉर्म", nl: "perron", ipa: "plet-form"},
      {hi: "स्टॉप", nl: "halte", ipa: "stop"},
      {hi: "लाइन", nl: "lijn", ipa: "lain"},
      {hi: "सीट", nl: "zitplaats", ipa: "siet"},
      {hi: "देरी", nl: "vertraging", ipa: "dee-rie"},
      {hi: "समय-सारणी", nl: "dienstregeling", ipa: "sə-məj saa-rə-nie"},
    ],
    phrases: [
      {hi: "एक मेट्रो टिकट चाहिए।", nl: "Ik wil één metroticket.", ipa: "eek mee-tro ti-kət tsjaa-hi-je"},
      {hi: "यह ट्रेन कहाँ जाती है?", nl: "Waar gaat deze trein heen?", ipa: "yəh treen kə-haan djaa-tie hai"},
      {hi: "प्लेटफॉर्म नंबर क्या है?", nl: "Wat is het perronnummer?", ipa: "plet-form nəm-bər kyaa hai"},
      {hi: "बस स्टॉप कहाँ है?", nl: "Waar is de bushalte?", ipa: "bəs stop kə-haan hai"},
      {hi: "क्या ट्रेन देर से है?", nl: "Heeft de trein vertraging?", ipa: "kyaa treen deer see hai"},
    ],
    grammar: "जाती है betekent “gaat” voor vrouwelijke zelfstandige naamwoorden zoals ट्रेन. Je hoeft de grammaticale geslachten niet perfect te kennen om begrepen te worden. Belangrijke woorden zoals टिकट, प्लेटफॉर्म en स्टॉप lijken op Engelse woorden en zijn makkelijk te herkennen.",
    practice: [
      "1. Koop één metroticket.",
      "2. Vraag waar de trein heen gaat.",
      "3. Vraag het perronnummer.",
      "4. Vraag waar de bushalte is.",
      "5. Vraag of de trein vertraagd is.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Op het vliegveld",
    titleNative: "हवाई अड्डे पर",
    focus: "Je leert praktische taal voor aankomst, bagage en vertrek op luchthavens zoals Delhi of Mumbai. Dit helpt bij balies, veiligheidscontrole en taxi’s.",
    vocab: [
      {hi: "हवाई अड्डा", nl: "luchthaven", ipa: "hə-vaai ə-ddaa"},
      {hi: "उड़ान", nl: "vlucht", ipa: "oe-raan"},
      {hi: "सामान", nl: "bagage", ipa: "saa-maan"},
      {hi: "पासपोर्ट", nl: "paspoort", ipa: "paas-port"},
      {hi: "वीज़ा", nl: "visum", ipa: "vie-zaa"},
      {hi: "गेट", nl: "gate", ipa: "geet"},
      {hi: "चेक-इन", nl: "check-in", ipa: "tsjek-in"},
      {hi: "बोर्डिंग", nl: "boarding", ipa: "bor-ding"},
      {hi: "देरी", nl: "vertraging", ipa: "dee-rie"},
      {hi: "आगमन", nl: "aankomst", ipa: "aa-gə-mən"},
    ],
    phrases: [
      {hi: "मेरी उड़ान कहाँ है?", nl: "Waar is mijn vlucht?", ipa: "mee-rie oe-raan kə-haan hai"},
      {hi: "मेरा सामान नहीं मिला।", nl: "Mijn bagage is niet aangekomen.", ipa: "mee-raa saa-maan nə-heen mi-laa"},
      {hi: "गेट नंबर क्या है?", nl: "Wat is het gatenummer?", ipa: "geet nəm-bər kyaa hai"},
      {hi: "चेक-इन कहाँ है?", nl: "Waar is de check-in?", ipa: "tsjek-in kə-haan hai"},
      {hi: "मेरी उड़ान देर से है।", nl: "Mijn vlucht is vertraagd.", ipa: "mee-rie oe-raan deer see hai"},
    ],
    grammar: "मिला betekent “gevonden / ontvangen”. सामान नहीं मिला is een handige zin bij kwijtgeraakte bagage. In luchthavens worden veel Engelse leenwoorden gebruikt, maar de Hindi-zinsstructuur helpt je om vragen duidelijk te maken.",
    practice: [
      "1. Vraag waar de check-in is.",
      "2. Vraag naar je gate.",
      "3. Zeg dat je bagage niet is aangekomen.",
      "4. Zeg dat je vlucht vertraagd is.",
      "5. Maak een korte zin met उड़ान.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Gezondheid en apotheek",
    titleNative: "स्वास्थ्य और दवा की दुकान",
    focus: "Vandaag leer je basiszinnen voor een apotheek of kleine kliniek. Je kunt uitleggen dat je pijn hebt of medicijnen nodig hebt.",
    vocab: [
      {hi: "दवा", nl: "medicijn", ipa: "də-vaa"},
      {hi: "दवा की दुकान", nl: "apotheek", ipa: "də-vaa kie doe-kaan"},
      {hi: "डॉक्टर", nl: "dokter", ipa: "dok-tər"},
      {hi: "दर्द", nl: "pijn", ipa: "dərd"},
      {hi: "सिर", nl: "hoofd", ipa: "sir"},
      {hi: "पेट", nl: "buik", ipa: "peet"},
      {hi: "बुखार", nl: "koorts", ipa: "boe-khaar"},
      {hi: "खाँसी", nl: "hoest", ipa: "khaan-sie"},
      {hi: "एलर्जी", nl: "allergie", ipa: "e-lər-djie"},
      {hi: "मदद", nl: "hulp", ipa: "mə-dəd"},
    ],
    phrases: [
      {hi: "मुझे दवा चाहिए।", nl: "Ik heb medicijn nodig.", ipa: "moe-djhee də-vaa tsjaa-hi-je"},
      {hi: "मेरे सिर में दर्द है।", nl: "Ik heb hoofdpijn.", ipa: "mee-ree sir men dərd hai"},
      {hi: "मेरे पेट में दर्द है।", nl: "Ik heb buikpijn.", ipa: "mee-ree peet men dərd hai"},
      {hi: "मुझे बुखार है।", nl: "Ik heb koorts.", ipa: "moe-djhee boe-khaar hai"},
      {hi: "क्या डॉक्टर पास में है?", nl: "Is er een dokter dichtbij?", ipa: "kyaa dok-tər paas men hai"},
    ],
    grammar: "में betekent “in”. मेरे सिर में दर्द है is letterlijk “In mijn hoofd is pijn.” Dit patroon gebruik je voor lichaamsdelen: मेरे पेट में दर्द है, मेरे पैर में दर्द है.",
    practice: [
      "1. Zeg dat je medicijn nodig hebt.",
      "2. Zeg dat je hoofdpijn hebt.",
      "3. Zeg dat je buikpijn hebt.",
      "4. Vraag of er een dokter dichtbij is.",
      "5. Maak een zin met दर्द.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Noodsituaties en veiligheid",
    titleNative: "आपात स्थिति और सुरक्षा",
    focus: "Je leert duidelijke noodzinnen voor situaties waarin je snel hulp nodig hebt. Deze zinnen zijn kort en praktisch voor drukke plekken of transport.",
    vocab: [
      {hi: "मदद", nl: "hulp", ipa: "mə-dəd"},
      {hi: "पुलिस", nl: "politie", ipa: "poe-lies"},
      {hi: "खतरा", nl: "gevaar", ipa: "khə-traa"},
      {hi: "आपात स्थिति", nl: "noodgeval", ipa: "aa-paat sthi-tie"},
      {hi: "अस्पताल", nl: "ziekenhuis", ipa: "əs-pə-taal"},
      {hi: "चोरी", nl: "diefstal", ipa: "tsjo-rie"},
      {hi: "खो गया", nl: "kwijtgeraakt", ipa: "kho gə-yaa"},
      {hi: "रुको", nl: "stop", ipa: "roe-ko"},
      {hi: "जल्दी", nl: "snel", ipa: "djəl-die"},
      {hi: "सुरक्षित", nl: "veilig", ipa: "soe-rək-shit"},
    ],
    phrases: [
      {hi: "मदद कीजिए!", nl: "Help alstublieft!", ipa: "mə-dəd kie-djie-je"},
      {hi: "पुलिस को बुलाइए।", nl: "Bel de politie.", ipa: "poe-lies ko boe-laa-ie-je"},
      {hi: "मेरा बैग खो गया।", nl: "Mijn tas is kwijt.", ipa: "mee-raa beg kho gə-yaa"},
      {hi: "मुझे अस्पताल जाना है।", nl: "Ik moet naar het ziekenhuis.", ipa: "moe-djhee əs-pə-taal djaa-naa hai"},
      {hi: "यह सुरक्षित नहीं है।", nl: "Dit is niet veilig.", ipa: "yəh soe-rək-shit nə-heen hai"},
    ],
    grammar: "को kan betekenen “naar/aan/voor” afhankelijk van de zin. पुलिस को बुलाइए betekent “roep/bel de politie”. In noodzinnen is duidelijkheid belangrijker dan perfecte grammatica.",
    practice: [
      "1. Roep om hulp in Hindi.",
      "2. Zeg dat je tas kwijt is.",
      "3. Vraag iemand de politie te bellen.",
      "4. Zeg dat je naar het ziekenhuis moet.",
      "5. Zeg dat iets niet veilig is.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Familie en persoonlijke gegevens",
    titleNative: "परिवार और निजी जानकारी",
    focus: "Vandaag leer je praten over familie en simpele persoonlijke informatie. Dit helpt bij sociale gesprekken of formulieren in hotels.",
    vocab: [
      {hi: "परिवार", nl: "familie", ipa: "pə-ri-vaar"},
      {hi: "माँ", nl: "moeder", ipa: "maan"},
      {hi: "पिता", nl: "vader", ipa: "pi-taa"},
      {hi: "भाई", nl: "broer", ipa: "bhaai"},
      {hi: "बहन", nl: "zus", ipa: "bə-hən"},
      {hi: "पति", nl: "echtgenoot", ipa: "pə-tie"},
      {hi: "पत्नी", nl: "echtgenote", ipa: "pət-nie"},
      {hi: "बच्चा", nl: "kind", ipa: "bə-tsjaa"},
      {hi: "उम्र", nl: "leeftijd", ipa: "oemr"},
      {hi: "घर", nl: "huis", ipa: "ghər"},
    ],
    phrases: [
      {hi: "मेरा परिवार नीदरलैंड में है।", nl: "Mijn familie is in Nederland.", ipa: "mee-raa pə-ri-vaar nie-dər-lənd men hai"},
      {hi: "मेरे दो भाई हैं।", nl: "Ik heb twee broers.", ipa: "mee-ree do bhaai hain"},
      {hi: "मेरी एक बहन है।", nl: "Ik heb één zus.", ipa: "mee-rie eek bə-hən hai"},
      {hi: "आपका घर कहाँ है?", nl: "Waar is uw huis?", ipa: "aap-kaa ghər kə-haan hai"},
      {hi: "मेरी उम्र तीस साल है।", nl: "Ik ben dertig jaar oud.", ipa: "mee-rie oemr tees saal hai"},
    ],
    grammar: "Hindi gebruikt vaak “bij mij zijn” voor bezit: मेरे दो भाई हैं betekent letterlijk “Bij mij zijn twee broers.” Voor familieleden is dit natuurlijk: “Ik heb twee broers.” मेरे en मेरी hangen af van het woord dat volgt.",
    practice: [
      "1. Zeg dat je familie in Nederland is.",
      "2. Zeg hoeveel broers of zussen je hebt.",
      "3. Vraag waar iemands huis is.",
      "4. Zeg je leeftijd met उम्र.",
      "5. Maak twee zinnen over familie.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Sociaal praten met locals",
    titleNative: "स्थानीय लोगों से बातचीत",
    focus: "Je leert korte smalltalkzinnen voor gesprekken met locals in cafés, treinen of guesthouses. Het doel is vriendelijk en nieuwsgierig klinken.",
    vocab: [
      {hi: "कैसे", nl: "hoe", ipa: "kai-see"},
      {hi: "अच्छे", nl: "goed", ipa: "ə-tsjee"},
      {hi: "मौसम", nl: "weer", ipa: "mau-səm"},
      {hi: "शहर", nl: "stad", ipa: "shə-hər"},
      {hi: "सुंदर", nl: "mooi", ipa: "soen-dər"},
      {hi: "दिलचस्प", nl: "interessant", ipa: "dil-tsjasp"},
      {hi: "काम", nl: "werk", ipa: "kaam"},
      {hi: "यात्रा", nl: "reis", ipa: "yaa-traa"},
      {hi: "फोटो", nl: "foto", ipa: "fo-to"},
      {hi: "भाषा", nl: "taal", ipa: "bhaa-shaa"},
    ],
    phrases: [
      {hi: "आप कैसे हैं?", nl: "Hoe gaat het met u?", ipa: "aap kai-see hain"},
      {hi: "मैं ठीक हूँ।", nl: "Het gaat goed met mij.", ipa: "main thiek hoen"},
      {hi: "यह शहर सुंदर है।", nl: "Deze stad is mooi.", ipa: "yəh shə-hər soen-dər hai"},
      {hi: "मौसम अच्छा है।", nl: "Het weer is goed.", ipa: "mau-səm ə-tsjaa hai"},
      {hi: "क्या मैं फोटो ले सकता हूँ?", nl: "Mag ik een foto maken?", ipa: "kyaa main fo-to lee sək-taa hoen"},
    ],
    grammar: "आप कैसे हैं? is beleefd en geschikt voor onbekenden. Tegen vrienden hoor je soms तुम कैसे हो?, maar als reiziger is आप veiliger. Voor toestemming vragen gebruik je क्या मैं ... सकता हूँ?",
    practice: [
      "1. Vraag hoe het met iemand gaat.",
      "2. Zeg dat het goed met je gaat.",
      "3. Zeg dat een stad mooi is.",
      "4. Vraag toestemming om een foto te maken.",
      "5. Maak een smalltalkzin over het weer.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Weer en kledingkeuzes",
    titleNative: "मौसम और कपड़ों का चुनाव",
    focus: "Vandaag praat je over het weer, vooral handig in hete steden zoals Delhi of vochtige plaatsen zoals Mumbai. Je leert ook eenvoudige kledingkeuzes uitleggen.",
    vocab: [
      {hi: "मौसम", nl: "weer", ipa: "mau-səm"},
      {hi: "गरमी", nl: "hitte", ipa: "gər-mie"},
      {hi: "ठंड", nl: "kou", ipa: "thənd"},
      {hi: "बारिश", nl: "regen", ipa: "baa-rish"},
      {hi: "धूप", nl: "zonneschijn", ipa: "dhoep"},
      {hi: "हवा", nl: "wind", ipa: "hə-vaa"},
      {hi: "छाता", nl: "paraplu", ipa: "tsjaa-taa"},
      {hi: "हल्का", nl: "licht", ipa: "həl-kaa"},
      {hi: "कपड़े", nl: "kleding", ipa: "kəp-ree"},
      {hi: "आज", nl: "vandaag", ipa: "aadj"},
    ],
    phrases: [
      {hi: "आज बहुत गरमी है।", nl: "Het is vandaag erg warm.", ipa: "aadj bə-hoet gər-mie hai"},
      {hi: "क्या बारिश होगी?", nl: "Gaat het regenen?", ipa: "kyaa baa-rish ho-gie"},
      {hi: "मुझे छाता चाहिए।", nl: "Ik heb een paraplu nodig.", ipa: "moe-djhee tsjaa-taa tsjaa-hi-je"},
      {hi: "ठंड है।", nl: "Het is koud.", ipa: "thənd hai"},
      {hi: "हल्के कपड़े चाहिए।", nl: "Ik heb lichte kleding nodig.", ipa: "həl-kee kəp-ree tsjaa-hi-je"},
    ],
    grammar: "होगी betekent “zal zijn/gebeuren” voor vrouwelijke woorden zoals बारिश. Je kunt vragen क्या बारिश होगी? wanneer je een tour plant. Het weer wordt vaak zonder onderwerp gezegd: गरमी है betekent simpelweg “Het is warm.”",
    practice: [
      "1. Zeg dat het vandaag erg warm is.",
      "2. Vraag of het gaat regenen.",
      "3. Vraag om een paraplu.",
      "4. Zeg dat het koud is.",
      "5. Maak een zin over kleding voor warm weer.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Tours en bezienswaardigheden",
    titleNative: "यात्रा और दर्शनीय स्थल",
    focus: "Je leert praten over tours, gidsen en bezienswaardigheden in plaatsen zoals Agra, Jaipur en Varanasi. Je kunt vragen naar tijden, tickets en foto’s.",
    vocab: [
      {hi: "यात्रा", nl: "reis / tour", ipa: "yaa-traa"},
      {hi: "गाइड", nl: "gids", ipa: "gaid"},
      {hi: "मंदिर", nl: "tempel", ipa: "mən-dir"},
      {hi: "किला", nl: "fort", ipa: "ki-laa"},
      {hi: "संग्रहालय", nl: "museum", ipa: "sən-gra-haa-ləj"},
      {hi: "टिकट", nl: "ticket", ipa: "ti-kət"},
      {hi: "प्रवेश", nl: "toegang", ipa: "prə-veesh"},
      {hi: "फोटो", nl: "foto", ipa: "fo-to"},
      {hi: "इतिहास", nl: "geschiedenis", ipa: "i-ti-haas"},
      {hi: "सुंदर", nl: "mooi", ipa: "soen-dər"},
    ],
    phrases: [
      {hi: "गाइड कहाँ है?", nl: "Waar is de gids?", ipa: "gaid kə-haan hai"},
      {hi: "टिकट कहाँ मिलेगा?", nl: "Waar kan ik een ticket krijgen?", ipa: "ti-kət kə-haan mi-lee-gaa"},
      {hi: "क्या फोटो लेना मना है?", nl: "Is foto’s maken verboden?", ipa: "kyaa fo-to lee-naa mə-naa hai"},
      {hi: "यह किला बहुत सुंदर है।", nl: "Dit fort is erg mooi.", ipa: "yəh ki-laa bə-hoet soen-dər hai"},
      {hi: "प्रवेश कितने बजे है?", nl: "Hoe laat is de toegang?", ipa: "prə-veesh kit-nee bə-djee hai"},
    ],
    grammar: "मना है betekent “is verboden”. Dit is handig bij tempels, musea en heilige plekken. Vraag liever vooraf of foto’s mogen, want regels verschillen per locatie.",
    practice: [
      "1. Vraag waar de gids is.",
      "2. Vraag waar je tickets kunt krijgen.",
      "3. Vraag of foto’s verboden zijn.",
      "4. Zeg dat een fort mooi is.",
      "5. Maak een zin met मंदिर of संग्रहालय.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Reserveringen maken",
    titleNative: "आरक्षण करना",
    focus: "Je leert een reservering maken voor een restaurant, tour of taxi. Dit is handig wanneer je in drukke steden of toeristische gebieden reist.",
    vocab: [
      {hi: "आरक्षण", nl: "reservering", ipa: "aa-rək-shən"},
      {hi: "बुकिंग", nl: "boeking", ipa: "boek-ing"},
      {hi: "समय", nl: "tijd", ipa: "sə-məj"},
      {hi: "लोग", nl: "personen", ipa: "log"},
      {hi: "आज", nl: "vandaag", ipa: "aadj"},
      {hi: "कल", nl: "morgen / gisteren", ipa: "kəl"},
      {hi: "नाम", nl: "naam", ipa: "naam"},
      {hi: "फोन", nl: "telefoon", ipa: "fon"},
      {hi: "पक्का", nl: "bevestigd / zeker", ipa: "pək-kaa"},
      {hi: "रद्द", nl: "geannuleerd", ipa: "rədd"},
    ],
    phrases: [
      {hi: "मुझे आरक्षण करना है।", nl: "Ik wil een reservering maken.", ipa: "moe-djhee aa-rək-shən kər-naa hai"},
      {hi: "चार लोगों के लिए।", nl: "Voor vier personen.", ipa: "tsjaar lo-gon kee li-je"},
      {hi: "आज रात के लिए।", nl: "Voor vanavond.", ipa: "aadj raat kee li-je"},
      {hi: "मेरे नाम से बुकिंग है।", nl: "Er is een boeking op mijn naam.", ipa: "mee-ree naam see boek-ing hai"},
      {hi: "क्या बुकिंग पक्की है?", nl: "Is de boeking bevestigd?", ipa: "kyaa boek-ing pək-kie hai"},
    ],
    grammar: "के लिए betekent opnieuw “voor” en is essentieel bij reserveringen: चार लोगों के लिए, आज रात के लिए. से kan “op naam van” betekenen in mijn boeking: मेरे नाम से. Leer deze combinatie als vaste zin.",
    practice: [
      "1. Maak een reservering voor vier personen.",
      "2. Zeg dat je voor vanavond wilt reserveren.",
      "3. Zeg dat de boeking op jouw naam staat.",
      "4. Vraag of de boeking bevestigd is.",
      "5. Maak een reservatiezin met समय.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Telefoon, internet en verbinding",
    titleNative: "फोन, इंटरनेट और कनेक्शन",
    focus: "Vandaag leer je praten over simkaarten, wifi en internetproblemen. Dit is handig in hotels, cafés en telefoonwinkels.",
    vocab: [
      {hi: "फोन", nl: "telefoon", ipa: "fon"},
      {hi: "सिम कार्ड", nl: "simkaart", ipa: "sim kaard"},
      {hi: "इंटरनेट", nl: "internet", ipa: "in-tər-net"},
      {hi: "वाई-फाई", nl: "wifi", ipa: "vaai-faai"},
      {hi: "पासवर्ड", nl: "wachtwoord", ipa: "paas-vərd"},
      {hi: "नेटवर्क", nl: "netwerk", ipa: "net-vərk"},
      {hi: "धीमा", nl: "langzaam", ipa: "dhie-maa"},
      {hi: "तेज़", nl: "snel", ipa: "teez"},
      {hi: "काम", nl: "werk", ipa: "kaam"},
      {hi: "चार्जर", nl: "oplader", ipa: "tsjaar-djər"},
    ],
    phrases: [
      {hi: "वाई-फाई पासवर्ड क्या है?", nl: "Wat is het wifiwachtwoord?", ipa: "vaai-faai paas-vərd kyaa hai"},
      {hi: "इंटरनेट काम नहीं कर रहा है।", nl: "Het internet werkt niet.", ipa: "in-tər-net kaam nə-heen kər rə-haa hai"},
      {hi: "मुझे सिम कार्ड चाहिए।", nl: "Ik wil een simkaart.", ipa: "moe-djhee sim kaard tsjaa-hi-je"},
      {hi: "नेटवर्क बहुत धीमा है।", nl: "Het netwerk is erg langzaam.", ipa: "net-vərk bə-hoet dhie-maa hai"},
      {hi: "क्या आपके पास चार्जर है?", nl: "Heeft u een oplader?", ipa: "kyaa aap-kee paas tsjaar-djər hai"},
    ],
    grammar: "काम नहीं कर रहा है betekent “werkt niet” of letterlijk “is niet aan het werk.” Deze uitdrukking is nuttig voor internet, telefoon, airco of betaalautomaat. Voor vrouwelijke sprekers verandert कर रहा soms in कर रही, maar als reiziger word je meestal begrepen.",
    practice: [
      "1. Vraag naar het wifiwachtwoord.",
      "2. Zeg dat internet niet werkt.",
      "3. Vraag om een simkaart.",
      "4. Zeg dat het netwerk langzaam is.",
      "5. Vraag of iemand een oplader heeft.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Bank, pinnen en betalen",
    titleNative: "बैंक, एटीएम और भुगतान",
    focus: "Je leert geld opnemen en vragen naar betaalmogelijkheden. Dit helpt bij restaurants, winkels, hotels en geldautomaten.",
    vocab: [
      {hi: "बैंक", nl: "bank", ipa: "baink"},
      {hi: "एटीएम", nl: "geldautomaat", ipa: "ee-tie-em"},
      {hi: "कार्ड", nl: "kaart", ipa: "kaard"},
      {hi: "नकद", nl: "contant", ipa: "nə-kəd"},
      {hi: "भुगतान", nl: "betaling", ipa: "bhoeg-taan"},
      {hi: "रसीद", nl: "bon", ipa: "rə-sied"},
      {hi: "खाता", nl: "rekening", ipa: "khaa-taa"},
      {hi: "रुपये", nl: "roepies", ipa: "roe-pə-je"},
      {hi: "पिन", nl: "pincode", ipa: "pin"},
      {hi: "मशीन", nl: "machine", ipa: "mə-shien"},
    ],
    phrases: [
      {hi: "एटीएम कहाँ है?", nl: "Waar is een geldautomaat?", ipa: "ee-tie-em kə-haan hai"},
      {hi: "क्या कार्ड चलेगा?", nl: "Kan ik met kaart betalen?", ipa: "kyaa kaard tsjə-lee-gaa"},
      {hi: "नकद भुगतान कर सकता हूँ।", nl: "Ik kan contant betalen.", ipa: "nə-kəd bhoeg-taan kər sək-taa hoen"},
      {hi: "रसीद दीजिए।", nl: "Geef de bon alstublieft.", ipa: "rə-sied die-djie-je"},
      {hi: "मशीन काम नहीं कर रही है।", nl: "De machine werkt niet.", ipa: "mə-shien kaam nə-heen kər rə-hie hai"},
    ],
    grammar: "चलेगा betekent letterlijk “zal lopen”, maar in betaalcontext betekent het “werkt / wordt geaccepteerd”. क्या कार्ड चलेगा? is een natuurlijke manier om te vragen of kaartbetaling mogelijk is.",
    practice: [
      "1. Vraag waar een geldautomaat is.",
      "2. Vraag of je met kaart kunt betalen.",
      "3. Zeg dat je contant kunt betalen.",
      "4. Vraag om een bon.",
      "5. Zeg dat de machine niet werkt.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Problemen oplossen",
    titleNative: "समस्याएँ हल करना",
    focus: "Vandaag leer je uitleggen dat er iets mis is met je kamer, ticket, boeking of bestelling. Je blijft beleefd maar duidelijk.",
    vocab: [
      {hi: "समस्या", nl: "probleem", ipa: "sə-məs-yaa"},
      {hi: "गलत", nl: "verkeerd", ipa: "gə-lət"},
      {hi: "सही", nl: "correct", ipa: "sə-hie"},
      {hi: "टूटा हुआ", nl: "kapot", ipa: "toe-taa hoe-aa"},
      {hi: "गंदा", nl: "vies", ipa: "gən-daa"},
      {hi: "आवाज़", nl: "geluid", ipa: "aa-vaaz"},
      {hi: "बदलना", nl: "veranderen / ruilen", ipa: "bəd-lə-naa"},
      {hi: "रद्द करना", nl: "annuleren", ipa: "rədd kər-naa"},
      {hi: "देरी", nl: "vertraging", ipa: "dee-rie"},
      {hi: "शिकायत", nl: "klacht", ipa: "shi-kaa-jət"},
    ],
    phrases: [
      {hi: "एक समस्या है।", nl: "Er is een probleem.", ipa: "eek sə-məs-yaa hai"},
      {hi: "यह गलत है।", nl: "Dit is verkeerd.", ipa: "yəh gə-lət hai"},
      {hi: "कमरा गंदा है।", nl: "De kamer is vies.", ipa: "kəm-raa gən-daa hai"},
      {hi: "मुझे कमरा बदलना है।", nl: "Ik wil van kamer veranderen.", ipa: "moe-djhee kəm-raa bəd-lə-naa hai"},
      {hi: "मैं शिकायत करना चाहता हूँ।", nl: "Ik wil een klacht indienen.", ipa: "main shi-kaa-jət kər-naa tsjaah-taa hoen"},
    ],
    grammar: "मुझे ... करना है betekent “Ik moet/wil ... doen.” Deze vorm is direct maar niet onbeleefd. Gebruik hem voor praktische problemen: मुझे कमरा बदलना है, मुझे बुकिंग रद्द करनी है.",
    practice: [
      "1. Zeg dat er een probleem is.",
      "2. Zeg dat iets verkeerd is.",
      "3. Zeg dat je kamer vies is.",
      "4. Vraag om een kamerwissel.",
      "5. Maak een zin met शिकायत.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Uitnodigingen en afspraken",
    titleNative: "निमंत्रण और मुलाक़ात",
    focus: "Je leert eenvoudige afspraken maken met locals, gidsen of medereizigers. Je kunt tijd, plek en beschikbaarheid bespreken.",
    vocab: [
      {hi: "मिलना", nl: "ontmoeten", ipa: "mil-naa"},
      {hi: "मुलाक़ात", nl: "afspraak / ontmoeting", ipa: "moe-laa-kaat"},
      {hi: "आना", nl: "komen", ipa: "aa-naa"},
      {hi: "जाना", nl: "gaan", ipa: "djaa-naa"},
      {hi: "समय", nl: "tijd", ipa: "sə-məj"},
      {hi: "जगह", nl: "plaats", ipa: "djə-gəh"},
      {hi: "आज", nl: "vandaag", ipa: "aadj"},
      {hi: "कल", nl: "morgen / gisteren", ipa: "kəl"},
      {hi: "ठीक", nl: "oké", ipa: "thiek"},
      {hi: "ज़रूर", nl: "zeker", ipa: "zə-roer"},
    ],
    phrases: [
      {hi: "क्या हम कल मिल सकते हैं?", nl: "Kunnen we morgen afspreken?", ipa: "kyaa həm kəl mil sək-tee hain"},
      {hi: "कहाँ मिलना है?", nl: "Waar spreken we af?", ipa: "kə-haan mil-naa hai"},
      {hi: "कितने बजे मिलें?", nl: "Hoe laat spreken we af?", ipa: "kit-nee bə-djee mi-len"},
      {hi: "यह समय ठीक है।", nl: "Deze tijd is goed.", ipa: "yəh sə-məj thiek hai"},
      {hi: "ज़रूर, मैं आऊँगा।", nl: "Zeker, ik zal komen.", ipa: "zə-roer, main aa-oen-gaa"},
    ],
    grammar: "हम betekent “wij” en is handig wanneer je samen iets plant. मिल सकते हैं betekent “kunnen ontmoeten”. In afspraken is het heel normaal om tijd en plek expliciet te bevestigen.",
    practice: [
      "1. Vraag of je morgen kunt afspreken.",
      "2. Vraag waar jullie afspreken.",
      "3. Vraag hoe laat jullie afspreken.",
      "4. Zeg dat de tijd goed is.",
      "5. Maak een korte afspraakdialoog.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Meningen en ervaringen",
    titleNative: "राय और अनुभव",
    focus: "Vandaag leer je zeggen wat je van een plek, maaltijd of ervaring vindt. Dit helpt in gesprekken en reviews tijdens je reis.",
    vocab: [
      {hi: "राय", nl: "mening", ipa: "raai"},
      {hi: "अनुभव", nl: "ervaring", ipa: "ə-noe-bhəv"},
      {hi: "अच्छा", nl: "goed", ipa: "ə-tsjaa"},
      {hi: "बुरा", nl: "slecht", ipa: "boe-raa"},
      {hi: "सुंदर", nl: "mooi", ipa: "soen-dər"},
      {hi: "दिलचस्प", nl: "interessant", ipa: "dil-tsjasp"},
      {hi: "मज़ेदार", nl: "leuk / plezierig", ipa: "mə-zee-daar"},
      {hi: "शांत", nl: "rustig", ipa: "shaant"},
      {hi: "भीड़", nl: "drukte", ipa: "bhier"},
      {hi: "पसंद", nl: "voorkeur", ipa: "pə-sənd"},
    ],
    phrases: [
      {hi: "यह जगह बहुत सुंदर है।", nl: "Deze plek is erg mooi.", ipa: "yəh djə-gəh bə-hoet soen-dər hai"},
      {hi: "मेरा अनुभव अच्छा था।", nl: "Mijn ervaring was goed.", ipa: "mee-raa ə-noe-bhəv ə-tsjaa thaa"},
      {hi: "यह बहुत भीड़ वाला है।", nl: "Het is hier erg druk.", ipa: "yəh bə-hoet bhier vaa-laa hai"},
      {hi: "मुझे यह खाना पसंद आया।", nl: "Ik vond dit eten lekker.", ipa: "moe-djhee yəh khaa-naa pə-sənd aa-yaa"},
      {hi: "यात्रा मज़ेदार थी।", nl: "De reis was leuk.", ipa: "yaa-traa mə-zee-daar thie"},
    ],
    grammar: "था en थी betekenen “was”. था gebruik je met mannelijke woorden, थी met vrouwelijke woorden zoals यात्रा. Als je het niet zeker weet, wordt je boodschap meestal toch begrepen door context.",
    practice: [
      "1. Zeg dat een plek mooi is.",
      "2. Zeg dat je ervaring goed was.",
      "3. Zeg dat het ergens druk is.",
      "4. Zeg dat je het eten lekker vond.",
      "5. Maak een zin met मज़ेदार.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Beleefd onderhandelen en grenzen stellen",
    titleNative: "विनम्र मोलभाव और सीमाएँ",
    focus: "Je leert vriendelijk maar duidelijk reageren op verkopers, chauffeurs of straatverkopers. Dit is nuttig in drukke markten en toeristische gebieden.",
    vocab: [
      {hi: "मोलभाव", nl: "onderhandelen", ipa: "mol-bhaav"},
      {hi: "दाम", nl: "prijs", ipa: "daam"},
      {hi: "कम", nl: "minder", ipa: "kəm"},
      {hi: "ज़्यादा", nl: "meer", ipa: "zyaa-daa"},
      {hi: "नहीं चाहिए", nl: "niet nodig", ipa: "nə-heen tsjaa-hi-je"},
      {hi: "बस", nl: "genoeg", ipa: "bəs"},
      {hi: "ठीक", nl: "oké", ipa: "thiek"},
      {hi: "सस्ता", nl: "goedkoop", ipa: "səs-taa"},
      {hi: "महंगा", nl: "duur", ipa: "mə-hən-gaa"},
      {hi: "धन्यवाद", nl: "bedankt", ipa: "dhən-yə-vaad"},
    ],
    phrases: [
      {hi: "नहीं, धन्यवाद।", nl: "Nee, bedankt.", ipa: "nə-heen, dhən-yə-vaad"},
      {hi: "मुझे नहीं चाहिए।", nl: "Ik heb het niet nodig.", ipa: "moe-djhee nə-heen tsjaa-hi-je"},
      {hi: "दाम थोड़ा कम करिए।", nl: "Maak de prijs iets lager.", ipa: "daam tho-raa kəm kə-rie-je"},
      {hi: "यह मेरे लिए महंगा है।", nl: "Dit is duur voor mij.", ipa: "yəh mee-ree li-je mə-hən-gaa hai"},
      {hi: "ठीक है, मैं लेता हूँ।", nl: "Oké, ik neem het.", ipa: "thiek hai, main lee-taa hoen"},
    ],
    grammar: "नहीं चाहिए is een beleefde en duidelijke manier om iets af te wijzen. Het is minder hard dan alleen नहीं. In toeristische gebieden is vriendelijk herhalen vaak genoeg: नहीं, धन्यवाद.",
    practice: [
      "1. Wijs een aanbod beleefd af.",
      "2. Vraag om een lagere prijs.",
      "3. Zeg dat iets duur voor je is.",
      "4. Zeg dat je iets neemt.",
      "5. Oefen een kort onderhandelingsgesprek.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Alles samen gebruiken",
    titleNative: "सब कुछ साथ में इस्तेमाल करना",
    focus: "Je combineert begroeten, bestellen, vragen, betalen en afscheid nemen. Dit is je praktische reisdialoogdag voor Hindi in echte situaties.",
    vocab: [
      {hi: "नमस्ते", nl: "hallo", ipa: "nə-məs-tee"},
      {hi: "कृपया", nl: "alstublieft", ipa: "krip-yaa"},
      {hi: "मुझे", nl: "mij / aan mij", ipa: "moe-djhee"},
      {hi: "चाहिए", nl: "nodig / willen", ipa: "tsjaa-hi-je"},
      {hi: "कहाँ", nl: "waar", ipa: "kə-haan"},
      {hi: "कितना", nl: "hoeveel", ipa: "kit-naa"},
      {hi: "ठीक", nl: "oké", ipa: "thiek"},
      {hi: "बिल", nl: "rekening", ipa: "bil"},
      {hi: "मदद", nl: "hulp", ipa: "mə-dəd"},
      {hi: "फिर मिलेंगे", nl: "tot later", ipa: "phir mi-len-gee"},
    ],
    phrases: [
      {hi: "नमस्ते, मुझे मदद चाहिए।", nl: "Hallo, ik heb hulp nodig.", ipa: "nə-məs-tee, moe-djhee mə-dəd tsjaa-hi-je"},
      {hi: "मुझे स्टेशन जाना है।", nl: "Ik moet naar het station.", ipa: "moe-djhee stee-shən djaa-naa hai"},
      {hi: "कितना समय लगेगा?", nl: "Hoeveel tijd duurt het?", ipa: "kit-naa sə-məj lə-gee-gaa"},
      {hi: "बिल दीजिए, कृपया।", nl: "De rekening, alstublieft.", ipa: "bil die-djie-je, krip-yaa"},
      {hi: "धन्यवाद, फिर मिलेंगे।", nl: "Bedankt, tot later.", ipa: "dhən-yə-vaad, phir mi-len-gee"},
    ],
    grammar: "Je hebt nu genoeg vaste patronen om veel situaties te overleven: मुझे ... चाहिए, कहाँ है, कितना है, en दीजिए. Combineer korte zinnen liever dan één lange zin te maken. In reis-Hindi zijn duidelijkheid, beleefdheid en herhaling belangrijker dan perfecte grammatica.",
    practice: [
      "1. Maak een volledige zin waarin je om hulp vraagt.",
      "2. Vraag de route naar het station.",
      "3. Vraag hoe lang iets duurt.",
      "4. Vraag om de rekening.",
      "5. Sluit een gesprek beleefd af met bedankt en tot later.",
    ],
    conversationIndex: 0,
    conversationCount: 8,
  },
];

var CONVERSATIONS_NL_HI = [
  {
    setting: "",
    lines: [
      {who: "them", hi: "नमस्ते, आप क्या लेंगे?", nl: "Hallo, wat wilt u nemen?"},
      {who: "you", hi: "नमस्ते, मुझे एक चाय चाहिए।", nl: "Hallo, ik wil één thee."},
      {who: "them", hi: "चीनी के साथ या बिना चीनी?", nl: "Met suiker of zonder suiker?"},
      {who: "you", hi: "बिना चीनी की चाय, कृपया।", nl: "Thee zonder suiker, alstublieft."},
      {who: "them", hi: "कुछ खाने के लिए चाहिए?", nl: "Wilt u iets te eten?"},
      {who: "you", hi: "हाँ, कुछ हल्का चाहिए।", nl: "Ja, ik wil iets lichts."},
      {who: "them", hi: "हमारे पास समोसा और सैंडविच है।", nl: "We hebben samosa en sandwich."},
      {who: "you", hi: "एक सैंडविच दीजिए।", nl: "Geef één sandwich alstublieft."},
      {who: "them", hi: "और पानी चाहिए?", nl: "Wilt u ook water?"},
      {who: "you", hi: "हाँ, ठंडा पानी दीजिए।", nl: "Ja, geef koud water alstublieft."},
      {who: "them", hi: "ठीक है, अभी लाता हूँ।", nl: "Oké, ik breng het meteen."},
      {who: "you", hi: "धन्यवाद।", nl: "Dank u."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", hi: "नमस्ते, आपका स्वागत है।", nl: "Hallo, welkom."},
      {who: "you", hi: "नमस्ते, मेरी बुकिंग है।", nl: "Hallo, ik heb een boeking."},
      {who: "them", hi: "बुकिंग किस नाम से है?", nl: "Op welke naam is de boeking?"},
      {who: "you", hi: "मेरे नाम से बुकिंग है, जान।", nl: "De boeking staat op mijn naam, Jan."},
      {who: "them", hi: "आपका पासपोर्ट दीजिए।", nl: "Geef uw paspoort alstublieft."},
      {who: "you", hi: "मेरा पासपोर्ट यहाँ है।", nl: "Mijn paspoort is hier."},
      {who: "them", hi: "आप दो रात रुकेंगे?", nl: "Blijft u twee nachten?"},
      {who: "you", hi: "हाँ, दो रात।", nl: "Ja, twee nachten."},
      {who: "them", hi: "कमरा नंबर पाँच है।", nl: "Kamernummer vijf."},
      {who: "you", hi: "वाई-फाई पासवर्ड क्या है?", nl: "Wat is het wifiwachtwoord?"},
      {who: "them", hi: "पासवर्ड रिसेप्शन पर लिखा है।", nl: "Het wachtwoord staat bij de receptie geschreven."},
      {who: "you", hi: "धन्यवाद, बहुत अच्छा।", nl: "Dank u, heel goed."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", hi: "माफ़ कीजिए, स्टेशन कहाँ है?", nl: "Excuseer, waar is het station?"},
      {who: "them", hi: "स्टेशन यहाँ से पास है।", nl: "Het station is dichtbij vanaf hier."},
      {who: "you", hi: "कैसे जाना है?", nl: "Hoe moet ik gaan?"},
      {who: "them", hi: "सीधा जाइए।", nl: "Ga rechtdoor."},
      {who: "you", hi: "फिर दाएँ या बाएँ?", nl: "Daarna rechts of links?"},
      {who: "them", hi: "पहले दाएँ मुड़िए, फिर सीधा जाइए।", nl: "Sla eerst rechtsaf en ga daarna rechtdoor."},
      {who: "you", hi: "कितना समय लगेगा?", nl: "Hoeveel tijd duurt het?"},
      {who: "them", hi: "लगभग दस मिनट।", nl: "Ongeveer tien minuten."},
      {who: "you", hi: "क्या वहाँ रिक्शा मिलेगा?", nl: "Kan ik daar een riksja krijgen?"},
      {who: "them", hi: "हाँ, स्टेशन के पास ऑटो मिलेंगे।", nl: "Ja, bij het station zijn autoriksja’s."},
      {who: "you", hi: "बहुत धन्यवाद।", nl: "Hartelijk dank."},
      {who: "them", hi: "कोई बात नहीं।", nl: "Geen probleem."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", hi: "नमस्ते, मेन्यू चाहिए?", nl: "Hallo, wilt u het menu?"},
      {who: "you", hi: "हाँ, मेन्यू दीजिए।", nl: "Ja, geef het menu alstublieft."},
      {who: "them", hi: "आप क्या खाना चाहेंगे?", nl: "Wat zou u willen eten?"},
      {who: "you", hi: "क्या यह शाकाहारी है?", nl: "Is dit vegetarisch?"},
      {who: "them", hi: "हाँ, यह शाकाहारी है।", nl: "Ja, dit is vegetarisch."},
      {who: "you", hi: "मुझे कम मसालेदार चाहिए।", nl: "Ik wil het minder pittig."},
      {who: "them", hi: "ठीक है, कम मसालेदार बना देंगे।", nl: "Oké, we maken het minder pittig."},
      {who: "you", hi: "रोटी और चावल भी चाहिए।", nl: "Ik wil ook roti en rijst."},
      {who: "them", hi: "पीने के लिए क्या लेंगे?", nl: "Wat neemt u te drinken?"},
      {who: "you", hi: "ठंडा पानी दीजिए।", nl: "Geef koud water alstublieft."},
      {who: "them", hi: "ठीक है, आपका खाना जल्दी आएगा।", nl: "Oké, uw eten komt snel."},
      {who: "you", hi: "धन्यवाद।", nl: "Dank u."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", hi: "कहाँ जाना है?", nl: "Waar moet u heen?"},
      {who: "you", hi: "मुझे राजीव चौक जाना है।", nl: "Ik moet naar Rajiv Chowk."},
      {who: "them", hi: "एक टिकट चाहिए?", nl: "Wilt u één ticket?"},
      {who: "you", hi: "हाँ, एक मेट्रो टिकट चाहिए।", nl: "Ja, ik wil één metroticket."},
      {who: "them", hi: "बीस रुपये।", nl: "Twintig roepies."},
      {who: "you", hi: "यह लीजिए।", nl: "Alstublieft, hier is het."},
      {who: "them", hi: "टिकट और रसीद लीजिए।", nl: "Neem het ticket en de bon."},
      {who: "you", hi: "कौन सी लाइन है?", nl: "Welke lijn is het?"},
      {who: "them", hi: "ब्लू लाइन लीजिए।", nl: "Neem de blauwe lijn."},
      {who: "you", hi: "प्लेटफॉर्म कहाँ है?", nl: "Waar is het perron?"},
      {who: "them", hi: "सीढ़ियों से नीचे जाइए।", nl: "Ga via de trap naar beneden."},
      {who: "you", hi: "धन्यवाद।", nl: "Dank u."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", hi: "नमस्ते, आइए, यह बहुत अच्छा है।", nl: "Hallo, kom kijken, dit is heel mooi."},
      {who: "you", hi: "नमस्ते, यह कितने का है?", nl: "Hallo, hoeveel kost dit?"},
      {who: "them", hi: "पाँच सौ रुपये।", nl: "Vijfhonderd roepies."},
      {who: "you", hi: "यह मेरे लिए महंगा है।", nl: "Dit is duur voor mij."},
      {who: "them", hi: "आप कितना देंगे?", nl: "Hoeveel wilt u geven?"},
      {who: "you", hi: "तीन सौ रुपये ठीक है?", nl: "Is driehonderd roepies goed?"},
      {who: "them", hi: "नहीं, चार सौ दीजिए।", nl: "Nee, geef vierhonderd."},
      {who: "you", hi: "थोड़ा कम करिए।", nl: "Maak het iets goedkoper."},
      {who: "them", hi: "ठीक है, साढ़े तीन सौ।", nl: "Oké, driehonderdvijftig."},
      {who: "you", hi: "ठीक है, मैं लेता हूँ।", nl: "Oké, ik neem het."},
      {who: "them", hi: "धन्यवाद।", nl: "Dank u."},
      {who: "you", hi: "धन्यवाद, अलविदा।", nl: "Dank u, tot ziens."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", hi: "नमस्ते, आपको क्या चाहिए?", nl: "Hallo, wat heeft u nodig?"},
      {who: "you", hi: "नमस्ते, मुझे दवा चाहिए।", nl: "Hallo, ik heb medicijn nodig."},
      {who: "them", hi: "किस चीज़ के लिए?", nl: "Waarvoor?"},
      {who: "you", hi: "मेरे सिर में दर्द है।", nl: "Ik heb hoofdpijn."},
      {who: "them", hi: "बुखार भी है?", nl: "Heeft u ook koorts?"},
      {who: "you", hi: "नहीं, बुखार नहीं है।", nl: "Nee, ik heb geen koorts."},
      {who: "them", hi: "यह दवा दिन में दो बार लीजिए।", nl: "Neem dit medicijn twee keer per dag."},
      {who: "you", hi: "इसे खाने के बाद लेना है?", nl: "Moet ik dit na het eten nemen?"},
      {who: "them", hi: "हाँ, खाने के बाद।", nl: "Ja, na het eten."},
      {who: "you", hi: "कितने रुपये?", nl: "Hoeveel roepies?"},
      {who: "them", hi: "अस्सी रुपये।", nl: "Tachtig roepies."},
      {who: "you", hi: "धन्यवाद।", nl: "Dank u."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", hi: "नमस्ते, आप कहाँ से हैं?", nl: "Hallo, waar komt u vandaan?"},
      {who: "you", hi: "नमस्ते, मैं नीदरलैंड से हूँ।", nl: "Hallo, ik kom uit Nederland."},
      {who: "them", hi: "आप भारत पहली बार आए हैं?", nl: "Bent u voor het eerst in India?"},
      {who: "you", hi: "हाँ, पहली बार।", nl: "Ja, voor het eerst."},
      {who: "them", hi: "आपको भारत कैसा लगा?", nl: "Hoe vindt u India?"},
      {who: "you", hi: "बहुत दिलचस्प और सुंदर।", nl: "Heel interessant en mooi."},
      {who: "them", hi: "आप कहाँ जा रहे हैं?", nl: "Waar gaat u heen?"},
      {who: "you", hi: "मैं आगरा जा रहा हूँ।", nl: "Ik ga naar Agra."},
      {who: "them", hi: "ताज महल देखने?", nl: "Om de Taj Mahal te zien?"},
      {who: "you", hi: "हाँ, मैं बहुत उत्साहित हूँ।", nl: "Ja, ik ben erg enthousiast."},
      {who: "them", hi: "आपकी यात्रा अच्छी हो।", nl: "Ik wens u een goede reis."},
      {who: "you", hi: "धन्यवाद, आपसे मिलकर खुशी हुई।", nl: "Dank u, leuk u te ontmoeten."},
    ],
  },
];