var COURSE_HI_NL = [
  {
    title: "नमस्ते और परिचय",
    titleNative: "Hallo en kennismaken",
    focus: "आज आप एम्स्टर्डम में किसी से पहली बार मिलने की बुनियादी भाषा सीखेंगे। लक्ष्य है नमस्ते कहना, अपना नाम बताना, और विनम्र तरीके से बातचीत शुरू करना।",
    vocab: [
      {nl: "hallo", hi: "नमस्ते", ipa: "हा-लो"},
      {nl: "goedemorgen", hi: "सुप्रभात", ipa: "खू-दु-मोर-खुन"},
      {nl: "goedemiddag", hi: "नमस्कार / शुभ दोपहर", ipa: "खू-दु-मि-दाख"},
      {nl: "goedenavond", hi: "शुभ संध्या", ipa: "खू-दु-ना-वोंत"},
      {nl: "dag", hi: "नमस्ते / अलविदा", ipa: "दाख"},
      {nl: "ik", hi: "मैं", ipa: "इक"},
      {nl: "jij", hi: "तुम", ipa: "यै"},
      {nl: "naam", hi: "नाम", ipa: "नाम"},
      {nl: "Nederland", hi: "नीदरलैंड", ipa: "ने-दर-लांत"},
      {nl: "India", hi: "भारत", ipa: "इन-दि-या"},
    ],
    phrases: [
      {nl: "Hallo!", hi: "नमस्ते!", ipa: "हा-लो"},
      {nl: "Ik ben Ravi.", hi: "मैं रवि हूँ।", ipa: "इक बेन रा-वी"},
      {nl: "Wat is jouw naam?", hi: "तुम्हारा नाम क्या है?", ipa: "वात इस याउ नाम"},
      {nl: "Aangenaam.", hi: "आपसे मिलकर खुशी हुई।", ipa: "आन-खु-नाम"},
      {nl: "Ik kom uit India.", hi: "मैं भारत से आया हूँ।", ipa: "इक कोम आउट इन-दि-या"},
      {nl: "Tot ziens.", hi: "फिर मिलेंगे।", ipa: "तोत ज़ीन्स"},
    ],
    grammar: "डच में “ik ben” का मतलब “मैं हूँ” होता है। अपना नाम बताने के लिए “Ik ben + नाम” बहुत आसान और उपयोगी संरचना है। “jij” अनौपचारिक “तुम” है, जबकि औपचारिक स्थिति में “u” का प्रयोग किया जाता है। शुरुआत में मुस्कान और “Hallo” बहुत काम आता है।",
    practice: [
      "1. अपना नाम डच में लिखें: “Ik ben ___.”",
      "2. किसी साथी से पूछें: “Wat is jouw naam?”",
      "3. “Ik kom uit India” तीन बार बोलकर अभ्यास करें।",
      "4. सुबह, दोपहर और शाम के अभिवादन अलग-अलग बोलें।",
      "5. “Aangenaam” का उपयोग करके एक छोटा परिचय बनाइए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "विनम्र शब्द और बुनियादी जवाब",
    titleNative: "Beleefde woorden en basisantwoorden",
    focus: "आज आप रॉटरडैम के किसी दुकान या कैफ़े में विनम्रता से बात करना सीखेंगे। “कृपया”, “धन्यवाद”, “हाँ”, “नहीं” जैसे शब्द यात्रा में हर दिन काम आते हैं।",
    vocab: [
      {nl: "ja", hi: "हाँ", ipa: "या"},
      {nl: "nee", hi: "नहीं", ipa: "ने"},
      {nl: "alsjeblieft", hi: "कृपया / लो", ipa: "आल्श-यु-ब्लीफ्ट"},
      {nl: "alstublieft", hi: "कृपया", ipa: "आल्स-तु-ब्लीफ्ट"},
      {nl: "dank je", hi: "धन्यवाद", ipa: "दांक यु"},
      {nl: "dank u", hi: "धन्यवाद", ipa: "दांक ऊ"},
      {nl: "sorry", hi: "माफ़ कीजिए", ipa: "सो-री"},
      {nl: "geen probleem", hi: "कोई बात नहीं", ipa: "खेन प्रो-ब्लेम"},
      {nl: "goed", hi: "अच्छा", ipa: "खू트"},
      {nl: "slecht", hi: "बुरा", ipa: "स्लेख्ट"},
    ],
    phrases: [
      {nl: "Ja, graag.", hi: "हाँ, कृपया।", ipa: "या, ख्राख"},
      {nl: "Nee, dank je.", hi: "नहीं, धन्यवाद।", ipa: "ने, दांक यु"},
      {nl: "Dank u wel.", hi: "बहुत धन्यवाद।", ipa: "दांक ऊ वेल"},
      {nl: "Sorry, ik begrijp het niet.", hi: "माफ़ कीजिए, मैं समझा नहीं।", ipa: "सो-री, इक बु-ख्रैप हट नीत"},
      {nl: "Geen probleem.", hi: "कोई बात नहीं।", ipa: "खेन प्रो-ब्लेम"},
      {nl: "Dat is goed.", hi: "यह ठीक है।", ipa: "दात इस खू트"},
    ],
    grammar: "“dank je” अनौपचारिक है और “dank u” अधिक विनम्र या औपचारिक है। डच में “graag” का मतलब “खुशी से” या “कृपया” जैसा होता है, खासकर जब आप कुछ लेना चाहते हैं। “Ja, graag” यात्रा में बहुत उपयोगी छोटा जवाब है।",
    practice: [
      "1. “हाँ, कृपया” और “नहीं, धन्यवाद” डच में बोलें।",
      "2. किसी कैफ़े में कॉफ़ी लेते समय “alstublieft” का प्रयोग करें।",
      "3. “Sorry, ik begrijp het niet” याद करें।",
      "4. “dank je” और “dank u” में अंतर बताइए।",
      "5. पाँच छोटे जवाब लिखिए: ja, nee, goed, slecht, geen probleem।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "आप कैसे हैं?",
    titleNative: "Hoe gaat het?",
    focus: "आज आप उट्रेख्ट में नए लोगों से हल्की बातचीत करना सीखेंगे। यह पाठ छोटे सामाजिक संवादों और सामान्य प्रतिक्रियाओं पर केंद्रित है।",
    vocab: [
      {nl: "hoe", hi: "कैसे", ipa: "हू"},
      {nl: "gaat", hi: "जाता / चलता", ipa: "खात"},
      {nl: "het", hi: "यह", ipa: "हट"},
      {nl: "prima", hi: "बढ़िया", ipa: "प्री-मा"},
      {nl: "goed", hi: "अच्छा", ipa: "खू트"},
      {nl: "moe", hi: "थका हुआ", ipa: "मू"},
      {nl: "druk", hi: "व्यस्त", ipa: "द्रुक"},
      {nl: "vandaag", hi: "आज", ipa: "वान-दाख"},
      {nl: "ook", hi: "भी", ipa: "ओक"},
      {nl: "fijn", hi: "अच्छा / सुखद", ipa: "फैन"},
    ],
    phrases: [
      {nl: "Hoe gaat het?", hi: "आप कैसे हैं?", ipa: "हू खात हट"},
      {nl: "Het gaat goed.", hi: "मैं ठीक हूँ।", ipa: "हट खात खू트"},
      {nl: "Prima, dank je.", hi: "बढ़िया, धन्यवाद।", ipa: "प्री-मा, दांक यु"},
      {nl: "Ik ben moe.", hi: "मैं थका हुआ हूँ।", ipa: "इक बेन मू"},
      {nl: "Ik ben druk vandaag.", hi: "मैं आज व्यस्त हूँ।", ipa: "इक बेन द्रुक वान-दाख"},
      {nl: "En met jou?", hi: "और तुम्हारे साथ?", ipa: "एन मेट याउ"},
    ],
    grammar: "डच में हाल पूछने के लिए “Hoe gaat het?” बहुत सामान्य है। जवाब में “Het gaat goed” कहा जाता है, जिसका शाब्दिक अर्थ है “यह अच्छा चल रहा है।” “Ik ben” के बाद आप अपनी स्थिति बता सकते हैं, जैसे “moe” या “druk।”",
    practice: [
      "1. “Hoe gaat het?” पूछकर तीन अलग-अलग जवाब दीजिए।",
      "2. “Ik ben moe” और “Ik ben druk” बोलकर अभ्यास करें।",
      "3. किसी दोस्त से “En met jou?” पूछें।",
      "4. “vandaag” का उपयोग करके एक वाक्य बनाइए।",
      "5. छोटी बातचीत लिखिए: नमस्ते, हाल पूछना, जवाब, धन्यवाद।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "नंबर और कीमतें",
    titleNative: "Nummers en prijzen",
    focus: "आज आप हेग में बाज़ार या टिकट काउंटर पर नंबर और कीमतें समझना सीखेंगे। यात्रा में पैसे, टिकट और समय पूछने के लिए यह आधार ज़रूरी है।",
    vocab: [
      {nl: "nul", hi: "शून्य", ipa: "नुल"},
      {nl: "een", hi: "एक", ipa: "एन"},
      {nl: "twee", hi: "दो", ipa: "त्वे"},
      {nl: "drie", hi: "तीन", ipa: "द्री"},
      {nl: "vier", hi: "चार", ipa: "फीर"},
      {nl: "vijf", hi: "पाँच", ipa: "फैफ"},
      {nl: "zes", hi: "छह", ipa: "ज़ेस"},
      {nl: "zeven", hi: "सात", ipa: "ज़े-वुन"},
      {nl: "acht", hi: "आठ", ipa: "आख्त"},
      {nl: "tien", hi: "दस", ipa: "तीन"},
    ],
    phrases: [
      {nl: "Hoeveel kost het?", hi: "इसकी कीमत कितनी है?", ipa: "हू-फेल कोस्त हट"},
      {nl: "Het kost vijf euro.", hi: "इसकी कीमत पाँच यूरो है।", ipa: "हट कोस्त फैफ ओय-रो"},
      {nl: "Ik wil twee tickets.", hi: "मुझे दो टिकट चाहिए।", ipa: "इक विल त्वे टिक-ट्स"},
      {nl: "Eén koffie, alstublieft.", hi: "एक कॉफ़ी, कृपया।", ipa: "एन को-फी, आल्स-तु-ब्लीफ्ट"},
      {nl: "Is dat alles?", hi: "क्या बस इतना ही?", ipa: "इस दात आलुस"},
      {nl: "Dat is tien euro.", hi: "यह दस यूरो है।", ipa: "दात इस तीन ओय-रो"},
    ],
    grammar: "डच में “hoeveel” का मतलब “कितना” या “कितने” है। कीमत पूछने के लिए “Hoeveel kost het?” सीधा और उपयोगी वाक्य है। यूरो बोलते समय “euro” अक्सर एकवचन जैसा ही सुनाई देता है, चाहे राशि पाँच हो या दस।",
    practice: [
      "1. 0 से 10 तक डच में बोलें।",
      "2. “Ik wil twee tickets” को अपनी ज़रूरत के हिसाब से बदलें।",
      "3. पाँच नकली कीमतें डच में लिखें।",
      "4. “Hoeveel kost het?” तीन बार अभ्यास करें।",
      "5. बाज़ार में खरीदारी का चार-लाइन संवाद बनाइए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "जरूरी वाक्य और मदद माँगना",
    titleNative: "Noodzinnen en hulp vragen",
    focus: "आज आप आइंधोवन स्टेशन या सड़क पर मदद माँगने के लिए उपयोगी वाक्य सीखेंगे। यह पाठ तब काम आएगा जब आप भाषा न समझें या रास्ता भूल जाएँ।",
    vocab: [
      {nl: "hulp", hi: "मदद", ipa: "हुल्प"},
      {nl: "spreken", hi: "बोलना", ipa: "स्प्रे-कुन"},
      {nl: "Engels", hi: "अंग्रेज़ी", ipa: "एंग-ल्स"},
      {nl: "Hindi", hi: "हिंदी", ipa: "हिन-दी"},
      {nl: "langzaam", hi: "धीरे", ipa: "लांग-ज़ाम"},
      {nl: "begrijpen", hi: "समझना", ipa: "बु-ख्रै-पुन"},
      {nl: "waar", hi: "कहाँ", ipa: "वार"},
      {nl: "toilet", hi: "शौचालय", ipa: "त्वा-लेट"},
      {nl: "politie", hi: "पुलिस", ipa: "पो-ली-त्सी"},
      {nl: "dokter", hi: "डॉक्टर", ipa: "दोक-तर"},
    ],
    phrases: [
      {nl: "Kunt u mij helpen?", hi: "क्या आप मेरी मदद कर सकते हैं?", ipa: "कुंट ऊ मै हेल-पुन"},
      {nl: "Spreekt u Engels?", hi: "क्या आप अंग्रेज़ी बोलते हैं?", ipa: "स्प्रेक्ट ऊ एंग-ल्स"},
      {nl: "Ik spreek geen Nederlands.", hi: "मैं डच नहीं बोलता।", ipa: "इक स्प्रेक खेन ने-दर-लांट्स"},
      {nl: "Kunt u langzaam spreken?", hi: "क्या आप धीरे बोल सकते हैं?", ipa: "कुंट ऊ लांग-ज़ाम स्प्रे-कुन"},
      {nl: "Waar is het toilet?", hi: "शौचालय कहाँ है?", ipa: "वार इस हट त्वा-लेट"},
      {nl: "Ik heb een dokter nodig.", hi: "मुझे डॉक्टर चाहिए।", ipa: "इक हेब एन दोक-तर नो-दिख"},
    ],
    grammar: "औपचारिक मदद माँगने के लिए “Kunt u…” बहुत उपयोगी है। “u” सम्मानजनक “आप” है, जिसे होटल, स्टेशन, दुकान या अजनबी से बात करते समय प्रयोग करें। “geen” का अर्थ “नहीं/कोई नहीं” है और इसे संज्ञा के साथ नकारात्मक अर्थ देने के लिए लगाया जाता है।",
    practice: [
      "1. “Kunt u mij helpen?” याद करें और बोलें।",
      "2. “Ik spreek geen Nederlands” में “Nederlands” की जगह “Engels” लगाकर अर्थ समझें।",
      "3. शौचालय पूछने का वाक्य बोलें।",
      "4. “langzaam” शब्द का उच्चारण पाँच बार करें।",
      "5. मदद माँगने की स्थिति पर पाँच वाक्य लिखिए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "शहर में दिशा पूछना",
    titleNative: "De weg vragen in de stad",
    focus: "आज आप एम्स्टर्डम की गलियों में दिशा पूछना और समझना सीखेंगे। म्यूज़ियम, स्टेशन और कैफ़े खोजते समय ये वाक्य बहुत काम आएँगे।",
    vocab: [
      {nl: "links", hi: "बाएँ", ipa: "लिंक्‍स"},
      {nl: "rechts", hi: "दाएँ", ipa: "रेख्त्स"},
      {nl: "rechtdoor", hi: "सीधे", ipa: "रेख्त-दोर"},
      {nl: "straat", hi: "सड़क", ipa: "स्त्रात"},
      {nl: "plein", hi: "चौक", ipa: "प्लैन"},
      {nl: "station", hi: "स्टेशन", ipa: "sta-स्योन"},
      {nl: "museum", hi: "संग्रहालय", ipa: "म्यू-ज़े-उम"},
      {nl: "brug", hi: "पुल", ipa: "ब्रुख"},
      {nl: "dichtbij", hi: "पास", ipa: "दिख्त-बै"},
      {nl: "ver weg", hi: "दूर", ipa: "फेर वेख"},
    ],
    phrases: [
      {nl: "Waar is het station?", hi: "स्टेशन कहाँ है?", ipa: "वार इस हट sta-स्योन"},
      {nl: "Ga rechtdoor.", hi: "सीधे जाइए।", ipa: "खा रेख्त-दोर"},
      {nl: "Sla linksaf.", hi: "बाएँ मुड़िए।", ipa: "स्ला लिंक्‍स-आफ"},
      {nl: "Sla rechtsaf.", hi: "दाएँ मुड़िए।", ipa: "स्ला रेख्त्स-आफ"},
      {nl: "Is het dichtbij?", hi: "क्या यह पास है?", ipa: "इस हट दिख्त-बै"},
      {nl: "Het is ver weg.", hi: "यह दूर है।", ipa: "हट इस फेर वेख"},
    ],
    grammar: "दिशा बताते समय डच में क्रिया अक्सर वाक्य की शुरुआत में आती है: “Ga rechtdoor” यानी “सीधे जाइए।” “linksaf” और “rechtsaf” मुड़ने के लिए प्रयोग होते हैं। “Waar is…” किसी स्थान को पूछने का सरल तरीका है।",
    practice: [
      "1. अपने घर से किसी दुकान तक दिशा डच शब्दों में बताइए।",
      "2. “links”, “rechts”, “rechtdoor” को हाथ के इशारे के साथ बोलें।",
      "3. “Waar is het museum?” बोलकर अभ्यास करें।",
      "4. दो जगहों के लिए “dichtbij” और “ver weg” का उपयोग करें।",
      "5. दिशा पूछने और जवाब देने का छोटा संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "कैफ़े में ऑर्डर करना",
    titleNative: "Bestellen in een café",
    focus: "आज आप रॉटरडैम के एक कैफ़े में पेय और हल्का खाना ऑर्डर करना सीखेंगे। आप विनम्र तरीके से मेनू माँगेंगे और कीमत पूछेंगे।",
    vocab: [
      {nl: "koffie", hi: "कॉफ़ी", ipa: "को-फी"},
      {nl: "thee", hi: "चाय", ipa: "ते"},
      {nl: "water", hi: "पानी", ipa: "वा-तर"},
      {nl: "melk", hi: "दूध", ipa: "मेल्क"},
      {nl: "suiker", hi: "चीनी", ipa: "साउ-कर"},
      {nl: "broodje", hi: "सैंडविच / ब्रेड रोल", ipa: "ब्रो-च्ये"},
      {nl: "menu", hi: "मेनू", ipa: "मे-न्यू"},
      {nl: "rekening", hi: "बिल", ipa: "रे-कु-निंग"},
      {nl: "kopje", hi: "कप", ipa: "कोप-यु"},
      {nl: "lekker", hi: "स्वादिष्ट", ipa: "ले-कर"},
    ],
    phrases: [
      {nl: "Ik wil graag koffie.", hi: "मुझे कॉफ़ी चाहिए।", ipa: "इक विल ख्राख को-फी"},
      {nl: "Een thee, alstublieft.", hi: "एक चाय, कृपया।", ipa: "एन ते, आल्स-तु-ब्लीफ्ट"},
      {nl: "Heeft u een menu?", hi: "क्या आपके पास मेनू है?", ipa: "हेफ्ट ऊ एन मे-न्यू"},
      {nl: "Zonder suiker, graag.", hi: "बिना चीनी के, कृपया।", ipa: "ज़ोन-दर साउ-कर, ख्राख"},
      {nl: "Mag ik de rekening?", hi: "क्या मुझे बिल मिल सकता है?", ipa: "माख इक दु रे-कु-निंग"},
      {nl: "Het is lekker.", hi: "यह स्वादिष्ट है।", ipa: "हट इस ले-कर"},
    ],
    grammar: "ऑर्डर करते समय “Ik wil graag…” विनम्र और प्राकृतिक लगता है। “zonder” का मतलब “बिना” है, जैसे “zonder suiker” यानी “बिना चीनी।” “Mag ik…” का उपयोग अनुमति या अनुरोध के लिए किया जाता है।",
    practice: [
      "1. अपने पसंदीदा पेय के साथ “Ik wil graag…” बोलें।",
      "2. “zonder suiker” और “met melk” का अभ्यास करें।",
      "3. कैफ़े में बिल माँगने का वाक्य बोलें।",
      "4. मेनू माँगने का एक विनम्र वाक्य लिखें।",
      "5. दो लोगों के बीच कैफ़े ऑर्डर संवाद बनाइए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "रेस्टोरेंट में खाना",
    titleNative: "Eten in een restaurant",
    focus: "आज आप उट्रेख्ट के एक रेस्टोरेंट में टेबल माँगना, खाना ऑर्डर करना और पसंद बताना सीखेंगे। यह पाठ बैठकर खाने की स्थिति पर केंद्रित है।",
    vocab: [
      {nl: "tafel", hi: "मेज़", ipa: "ता-फल"},
      {nl: "eten", hi: "खाना", ipa: "ए-तुन"},
      {nl: "drinken", hi: "पीना", ipa: "द्रिंक-कुन"},
      {nl: "soep", hi: "सूप", ipa: "सूप"},
      {nl: "salade", hi: "सलाद", ipa: "सा-ला-दु"},
      {nl: "vis", hi: "मछली", ipa: "फिस"},
      {nl: "kip", hi: "चिकन", ipa: "किप"},
      {nl: "vegetarisch", hi: "शाकाहारी", ipa: "वे-खु-ता-रीस"},
      {nl: "vlees", hi: "मांस", ipa: "फ्लेस"},
      {nl: "nagerecht", hi: "मिठाई / डेज़र्ट", ipa: "ना-खु-रेख्त"},
    ],
    phrases: [
      {nl: "Heeft u een tafel voor twee?", hi: "क्या दो लोगों के लिए मेज़ है?", ipa: "हेफ्ट ऊ एन ता-फल फोर त्वे"},
      {nl: "Ik ben vegetarisch.", hi: "मैं शाकाहारी हूँ।", ipa: "इक बेन वे-खु-ता-रीस"},
      {nl: "Wat raadt u aan?", hi: "आप क्या सुझाते हैं?", ipa: "वात रात ऊ आन"},
      {nl: "Ik neem de soep.", hi: "मैं सूप लूँगा।", ipa: "इक नेम दु सूप"},
      {nl: "Dat was heerlijk.", hi: "वह बहुत स्वादिष्ट था।", ipa: "दात वास हेर-लुक"},
      {nl: "Mag ik betalen?", hi: "क्या मैं भुगतान कर सकता हूँ?", ipa: "माख इक बु-ता-लुन"},
    ],
    grammar: "डच में “Ik neem…” का मतलब है “मैं लूँगा/लूँगी,” और रेस्टोरेंट में ऑर्डर के लिए यह बहुत सामान्य है। “voor twee” का अर्थ “दो लोगों के लिए” है। यदि आप शाकाहारी हैं तो “Ik ben vegetarisch” साफ़ और उपयोगी वाक्य है।",
    practice: [
      "1. “Heeft u een tafel voor twee?” बोलकर अभ्यास करें।",
      "2. तीन खाने की चीज़ें “Ik neem…” के साथ बोलें।",
      "3. “Wat raadt u aan?” का अर्थ समझाएँ।",
      "4. शाकाहारी विकल्प पूछने के लिए एक वाक्य बनाइए।",
      "5. रेस्टोरेंट में 6 लाइन का संवाद लिखिए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "होटल में चेक-इन",
    titleNative: "Inchecken in een hotel",
    focus: "आज आप द हेग के होटल में चेक-इन करना सीखेंगे। आप बुकिंग, पासपोर्ट, कमरा और नाश्ते के बारे में पूछेंगे।",
    vocab: [
      {nl: "hotel", hi: "होटल", ipa: "हो-टेल"},
      {nl: "reservering", hi: "आरक्षण", ipa: "रे-ज़र-वे-रिंग"},
      {nl: "kamer", hi: "कमरा", ipa: "का-मर"},
      {nl: "paspoort", hi: "पासपोर्ट", ipa: "पास-पोर्ट"},
      {nl: "sleutel", hi: "चाबी", ipa: "स्लोय-तल"},
      {nl: "ontbijt", hi: "नाश्ता", ipa: "ओंट-बैत"},
      {nl: "nacht", hi: "रात", ipa: "नाख्त"},
      {nl: "lift", hi: "लिफ्ट", ipa: "लिफ्ट"},
      {nl: "bagage", hi: "सामान", ipa: "बा-खा-झु"},
      {nl: "receptie", hi: "रिसेप्शन", ipa: "रे-सेप-त्सी"},
    ],
    phrases: [
      {nl: "Ik heb een reservering.", hi: "मेरा आरक्षण है।", ipa: "इक हेब एन रे-ज़र-वे-रिंग"},
      {nl: "Mijn naam is Ravi Sharma.", hi: "मेरा नाम रवि शर्मा है।", ipa: "मैन नाम इस रा-वी शर-मा"},
      {nl: "Hier is mijn paspoort.", hi: "यह मेरा पासपोर्ट है।", ipa: "हीर इस मैन पास-पोर्ट"},
      {nl: "Waar is mijn kamer?", hi: "मेरा कमरा कहाँ है?", ipa: "वार इस मैन का-मर"},
      {nl: "Is ontbijt inbegrepen?", hi: "क्या नाश्ता शामिल है?", ipa: "इस ओंट-बैत इन-बु-ख्रे-पुन"},
      {nl: "Kan ik mijn bagage hier laten?", hi: "क्या मैं अपना सामान यहाँ छोड़ सकता हूँ?", ipa: "कान इक मैन बा-खा-झु हीर ला-तुन"},
    ],
    grammar: "“mijn” का मतलब “मेरा/मेरी” है। होटल में “mijn kamer,” “mijn paspoort,” और “mijn bagage” बहुत काम आते हैं। “Ik heb…” का मतलब “मेरे पास है” या “मेरा है” के रूप में उपयोग होता है।",
    practice: [
      "1. अपने नाम से “Mijn naam is…” बोलें।",
      "2. होटल में चेक-इन के लिए तीन जरूरी वाक्य लिखें।",
      "3. “Is ontbijt inbegrepen?” याद करें।",
      "4. “mijn” के साथ पाँच शब्द जोड़ें।",
      "5. होटल रिसेप्शन संवाद का अभ्यास करें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "ट्रेन और सार्वजनिक परिवहन",
    titleNative: "Trein en openbaar vervoer",
    focus: "आज आप एम्स्टर्डम सेंट्रल स्टेशन से ट्रेन, ट्राम या मेट्रो लेने की भाषा सीखेंगे। टिकट खरीदना, प्लेटफ़ॉर्म पूछना और समय समझना मुख्य लक्ष्य है।",
    vocab: [
      {nl: "trein", hi: "ट्रेन", ipa: "ट्रेन"},
      {nl: "tram", hi: "ट्राम", ipa: "ट्राम"},
      {nl: "metro", hi: "मेट्रो", ipa: "मे-त्रो"},
      {nl: "bus", hi: "बस", ipa: "बस"},
      {nl: "ticket", hi: "टिकट", ipa: "टिकिट"},
      {nl: "perron", hi: "प्लेटफ़ॉर्म", ipa: "पे-रोन"},
      {nl: "vertrek", hi: "प्रस्थान", ipa: "फेर-त्रेक"},
      {nl: "aankomst", hi: "आगमन", ipa: "आन-कोम्स्त"},
      {nl: "tijd", hi: "समय", ipa: "तैद"},
      {nl: "kaart", hi: "कार्ड / टिकट", ipa: "कार्ट"},
    ],
    phrases: [
      {nl: "Waar is het perron?", hi: "प्लेटफ़ॉर्म कहाँ है?", ipa: "वार इस हट पे-रोन"},
      {nl: "Ik wil een ticket naar Utrecht.", hi: "मुझे उट्रेख्ट का टिकट चाहिए।", ipa: "इक विल एन टिकिट नार ऊ-त्रेख्त"},
      {nl: "Hoe laat vertrekt de trein?", hi: "ट्रेन कितने बजे निकलती है?", ipa: "हू लात फेर-त्रेक्ट दु ट्रेन"},
      {nl: "Is dit de trein naar Amsterdam?", hi: "क्या यह एम्स्टर्डम जाने वाली ट्रेन है?", ipa: "इस दित दु ट्रेन नार आम्स-तर-दम"},
      {nl: "Ik heb een OV-chipkaart.", hi: "मेरे पास ओवी-चिपकार्ट है।", ipa: "इक हेब एन ओ-वे-चिप-कार्ट"},
      {nl: "De tram is te laat.", hi: "ट्राम देर से है।", ipa: "दु ट्राम इस तु लात"},
    ],
    grammar: "स्थान की दिशा बताने के लिए “naar” का उपयोग होता है, जैसे “naar Utrecht” यानी “उट्रेख्ट की ओर/के लिए।” समय पूछने में “Hoe laat…” बहुत उपयोगी है। डच सार्वजनिक परिवहन में “OV-chipkaart” या डिजिटल भुगतान आम है।",
    practice: [
      "1. “Ik wil een ticket naar…” में शहर का नाम बदलें।",
      "2. “Waar is het perron?” बोलें।",
      "3. ट्रेन के समय के लिए एक सवाल बनाइए।",
      "4. “naar Amsterdam,” “naar Rotterdam,” “naar Utrecht” बोलकर अभ्यास करें।",
      "5. स्टेशन पर टिकट खरीदने का संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "समय और दैनिक योजना",
    titleNative: "Tijd en dagplanning",
    focus: "आज आप लाइडेन में दिन की योजना बनाना और समय पूछना सीखेंगे। म्यूज़ियम, ट्रेन और मुलाकातों के लिए समय बताना जरूरी है।",
    vocab: [
      {nl: "uur", hi: "बजे / घंटा", ipa: "ऊर"},
      {nl: "minuut", hi: "मिनट", ipa: "मी-नूट"},
      {nl: "vandaag", hi: "आज", ipa: "वान-दाख"},
      {nl: "morgen", hi: "कल", ipa: "मोर-खुन"},
      {nl: "gisteren", hi: "कल / बीता कल", ipa: "खिस-तरुन"},
      {nl: "ochtend", hi: "सुबह", ipa: "ओख-तेंट"},
      {nl: "middag", hi: "दोपहर", ipa: "मि-दाख"},
      {nl: "avond", hi: "शाम", ipa: "आ-वोंत"},
      {nl: "laat", hi: "देर", ipa: "लात"},
      {nl: "vroeg", hi: "जल्दी", ipa: "फ्रूख"},
    ],
    phrases: [
      {nl: "Hoe laat is het?", hi: "कितने बजे हैं?", ipa: "हू लात इस हट"},
      {nl: "Het is drie uur.", hi: "तीन बजे हैं।", ipa: "हट इस द्री ऊर"},
      {nl: "Ik kom om tien uur.", hi: "मैं दस बजे आऊँगा।", ipa: "इक कोम ओम तीन ऊर"},
      {nl: "Morgen ga ik naar Leiden.", hi: "कल मैं लाइडेन जाऊँगा।", ipa: "मोर-खुन खा इक नार लै-दुन"},
      {nl: "Ik ben te laat.", hi: "मैं देर से हूँ।", ipa: "इक बेन तु लात"},
      {nl: "Tot morgen!", hi: "कल मिलते हैं!", ipa: "तोत मोर-खुन"},
    ],
    grammar: "समय बताने में “om” का अर्थ “पर” होता है, जैसे “om tien uur” यानी “दस बजे।” “morgen” का मतलब आने वाला कल है, जबकि “gisteren” बीता हुआ कल है। “te laat” का अर्थ है “बहुत देर से” या “लेट।”",
    practice: [
      "1. अभी का समय डच में बोलें।",
      "2. “Ik kom om…” से तीन वाक्य बनाइए।",
      "3. सुबह, दोपहर और शाम के शब्द याद करें।",
      "4. “morgen” और “gisteren” में फर्क बताइए।",
      "5. अपने यात्रा दिन की योजना पाँच वाक्यों में लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "बाज़ार और खरीदारी",
    titleNative: "Markt en winkelen",
    focus: "आज आप अल्कमार या एम्स्टर्डम के बाज़ार में खरीदारी करना सीखेंगे। आप कीमत, मात्रा, आकार और पसंद बताने का अभ्यास करेंगे।",
    vocab: [
      {nl: "winkel", hi: "दुकान", ipa: "विंकल"},
      {nl: "markt", hi: "बाज़ार", ipa: "मार्क्ट"},
      {nl: "prijs", hi: "कीमत", ipa: "प्रैस"},
      {nl: "goedkoop", hi: "सस्ता", ipa: "खूट-कोप"},
      {nl: "duur", hi: "महंगा", ipa: "ड्यूर"},
      {nl: "groot", hi: "बड़ा", ipa: "ख्रोत"},
      {nl: "klein", hi: "छोटा", ipa: "क्लैन"},
      {nl: "maat", hi: "साइज़", ipa: "मात"},
      {nl: "kleur", hi: "रंग", ipa: "क्लर"},
      {nl: "tas", hi: "बैग", ipa: "तास"},
    ],
    phrases: [
      {nl: "Hoeveel kost deze tas?", hi: "इस बैग की कीमत कितनी है?", ipa: "हू-फेल कोस्त डे-ज़ु तास"},
      {nl: "Dat is te duur.", hi: "यह बहुत महंगा है।", ipa: "दात इस तु ड्यूर"},
      {nl: "Heeft u een kleinere maat?", hi: "क्या आपके पास छोटा साइज़ है?", ipa: "हेफ्ट ऊ एन क्लै-नु-रु मात"},
      {nl: "Ik kijk alleen.", hi: "मैं सिर्फ देख रहा हूँ।", ipa: "इक कैक आल-एन"},
      {nl: "Ik neem deze.", hi: "मैं यह लूँगा।", ipa: "इक नेम डे-ज़ु"},
      {nl: "Kan ik met kaart betalen?", hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?", ipa: "कान इक मेट कार्ट बु-ता-लुन"},
    ],
    grammar: "“deze” का मतलब “यह” है और यह पास की चीज़ के लिए इस्तेमाल होता है। “Ik neem deze” खरीदारी में बहुत सामान्य वाक्य है। “te” किसी विशेषण से पहले आकर “बहुत ज़्यादा” अर्थ दे सकता है, जैसे “te duur।”",
    practice: [
      "1. तीन चीज़ों की कीमत पूछने का अभ्यास करें।",
      "2. “Ik neem deze” को अलग-अलग वस्तुओं के साथ बोलें।",
      "3. “goedkoop” और “duur” के अर्थ लिखें।",
      "4. कार्ड से भुगतान पूछने का वाक्य बोलें।",
      "5. बाज़ार में खरीदारी का 6 लाइन संवाद बनाइए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "कपड़े और रंग",
    titleNative: "Kleding en kleuren",
    focus: "आज आप मास्ट्रिख्ट की दुकानों में कपड़े खरीदने की भाषा सीखेंगे। रंग, साइज़ और पसंद-नापसंद बताना इस पाठ का लक्ष्य है।",
    vocab: [
      {nl: "shirt", hi: "शर्ट", ipa: "शर्ट"},
      {nl: "broek", hi: "पैंट", ipa: "ब्रूक"},
      {nl: "jas", hi: "जैकेट / कोट", ipa: "यास"},
      {nl: "schoenen", hi: "जूते", ipa: "स्कू-नुन"},
      {nl: "wit", hi: "सफेद", ipa: "वित"},
      {nl: "zwart", hi: "काला", ipa: "ज़्वार्ट"},
      {nl: "blauw", hi: "नीला", ipa: "ब्लाउ"},
      {nl: "rood", hi: "लाल", ipa: "रोत"},
      {nl: "groen", hi: "हरा", ipa: "ख्रून"},
      {nl: "passen", hi: "फिट होना / ट्राय करना", ipa: "पा-सुन"},
    ],
    phrases: [
      {nl: "Ik zoek een jas.", hi: "मैं जैकेट ढूँढ रहा हूँ।", ipa: "इक ज़ूक एन यास"},
      {nl: "Heeft u dit in blauw?", hi: "क्या यह नीले रंग में है?", ipa: "हेफ्ट ऊ दित इन ब्लाउ"},
      {nl: "Mag ik dit passen?", hi: "क्या मैं इसे ट्राय कर सकता हूँ?", ipa: "माख इक दित पा-सुन"},
      {nl: "Het past goed.", hi: "यह अच्छी तरह फिट है।", ipa: "हट पास्ट खू트"},
      {nl: "Het is te klein.", hi: "यह बहुत छोटा है।", ipa: "हट इस तु क्लैन"},
      {nl: "Ik vind rood mooi.", hi: "मुझे लाल रंग सुंदर लगता है।", ipa: "इक फिंट रोत मोय"},
    ],
    grammar: "“ik zoek” का मतलब “मैं ढूँढ रहा हूँ” है। कपड़ों की दुकान में “Mag ik dit passen?” बहुत उपयोगी है। पसंद बताने के लिए “Ik vind… mooi” कह सकते हैं, जिसका अर्थ है “मुझे … सुंदर लगता है।”",
    practice: [
      "1. तीन रंग डच में बोलें।",
      "2. अपने कपड़े के लिए “Ik zoek…” वाक्य बनाइए।",
      "3. “te klein” और “te groot” का अभ्यास करें।",
      "4. “Mag ik dit passen?” बोलें।",
      "5. दुकान में कपड़े ट्राय करने का छोटा संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "मौसम और बाहर घूमना",
    titleNative: "Weer en buiten wandelen",
    focus: "आज आप डेल्फ़्ट में मौसम की बात करना और बाहर जाने की योजना बनाना सीखेंगे। नीदरलैंड में मौसम जल्दी बदल सकता है, इसलिए यह शब्दावली उपयोगी है।",
    vocab: [
      {nl: "weer", hi: "मौसम", ipa: "वीर"},
      {nl: "regen", hi: "बारिश", ipa: "रे-खुन"},
      {nl: "zon", hi: "सूरज", ipa: "ज़ोन"},
      {nl: "wind", hi: "हवा", ipa: "विंट"},
      {nl: "koud", hi: "ठंडा", ipa: "काउट"},
      {nl: "warm", hi: "गर्म", ipa: "वार्म"},
      {nl: "bewolkt", hi: "बादलों वाला", ipa: "बु-वोल्क्ट"},
      {nl: "paraplu", hi: "छाता", ipa: "पा-रा-प्लू"},
      {nl: "jas", hi: "जैकेट", ipa: "यास"},
      {nl: "wandelen", hi: "टहलना", ipa: "वान-दु-लुन"},
    ],
    phrases: [
      {nl: "Hoe is het weer?", hi: "मौसम कैसा है?", ipa: "हू इस हट वीर"},
      {nl: "Het regent.", hi: "बारिश हो रही है।", ipa: "हट रे-खुन्त"},
      {nl: "Het is koud vandaag.", hi: "आज ठंड है।", ipa: "हट इस काउट वान-दाख"},
      {nl: "Ik heb een paraplu nodig.", hi: "मुझे छाता चाहिए।", ipa: "इक हेब एन पा-रा-प्लू नो-दिख"},
      {nl: "Zullen we wandelen?", hi: "क्या हम टहलें?", ipa: "ज़ु-लुन वु वान-दु-लुन"},
      {nl: "De zon schijnt.", hi: "सूरज चमक रहा है।", ipa: "दु ज़ोन स्कैन्त"},
    ],
    grammar: "मौसम के लिए डच में अक्सर “Het is…” या “Het regent” जैसी संरचना आती है। “Het” यहाँ सामान्य “यह” जैसा है और मौसम बताने में प्रयोग होता है। “Zullen we…” सुझाव देने का अच्छा तरीका है।",
    practice: [
      "1. आज का मौसम डच में बताइए।",
      "2. “Het is koud” और “Het is warm” का अभ्यास करें।",
      "3. बारिश के लिए एक वाक्य बोलें।",
      "4. “Zullen we wandelen?” का उपयोग करके योजना बनाइए।",
      "5. मौसम पर दो लोगों की छोटी बातचीत लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "परिवार और लोग",
    titleNative: "Familie en mensen",
    focus: "आज आप ग्रोनिंगन में किसी स्थानीय व्यक्ति से परिवार और लोगों के बारे में हल्की बातचीत करना सीखेंगे। यह सामाजिक बातचीत को थोड़ा गहरा बनाता है।",
    vocab: [
      {nl: "familie", hi: "परिवार", ipa: "फा-मी-ली"},
      {nl: "moeder", hi: "माँ", ipa: "मू-दर"},
      {nl: "vader", hi: "पिता", ipa: "फा-दर"},
      {nl: "broer", hi: "भाई", ipa: "ब्रूर"},
      {nl: "zus", hi: "बहन", ipa: "ज़ुस"},
      {nl: "vriend", hi: "दोस्त / पुरुष मित्र", ipa: "फ्रिंट"},
      {nl: "vriendin", hi: "दोस्त / महिला मित्र", ipa: "फ्रिन-दिन"},
      {nl: "kind", hi: "बच्चा", ipa: "किंट"},
      {nl: "mensen", hi: "लोग", ipa: "में-सुन"},
      {nl: "samen", hi: "साथ", ipa: "सा-मुन"},
    ],
    phrases: [
      {nl: "Dit is mijn familie.", hi: "यह मेरा परिवार है।", ipa: "दित इस मैन फा-मी-ली"},
      {nl: "Ik heb een broer.", hi: "मेरा एक भाई है।", ipa: "इक हेब एन ब्रूर"},
      {nl: "Heb jij kinderen?", hi: "क्या तुम्हारे बच्चे हैं?", ipa: "हेब यै किं-दु-रुन"},
      {nl: "Mijn vriendin is in Amsterdam.", hi: "मेरी दोस्त एम्स्टर्डम में है।", ipa: "मैन फ्रिन-दिन इस इन आम्स-तर-दम"},
      {nl: "Wij reizen samen.", hi: "हम साथ यात्रा कर रहे हैं।", ipa: "वै रै-ज़ुन सा-मुन"},
      {nl: "Dat is mijn vriend.", hi: "वह मेरा दोस्त है।", ipa: "दात इस मैन फ्रिंट"},
    ],
    grammar: "“mijn” यानी “मेरा/मेरी” और “jouw” यानी “तुम्हारा/तुम्हारी।” डच में “vriend” पुरुष मित्र या बॉयफ्रेंड दोनों हो सकता है, और “vriendin” महिला मित्र या गर्लफ्रेंड दोनों। संदर्भ से अर्थ स्पष्ट होता है।",
    practice: [
      "1. अपने परिवार के दो सदस्यों को डच में बताइए।",
      "2. “Ik heb…” से तीन वाक्य बनाइए।",
      "3. “Wij reizen samen” बोलें।",
      "4. “vriend” और “vriendin” के अर्थ समझें।",
      "5. परिवार पर पाँच लाइन की बातचीत लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "पसंद और नापसंद",
    titleNative: "Voorkeuren en afkeer",
    focus: "आज आप हार्लेम में भोजन, जगहों और गतिविधियों के बारे में अपनी पसंद बताना सीखेंगे। यात्रियों के लिए सुझाव लेते समय यह उपयोगी है।",
    vocab: [
      {nl: "houden van", hi: "पसंद करना / प्यार करना", ipa: "हाउ-दुन फान"},
      {nl: "leuk", hi: "अच्छा / मज़ेदार", ipa: "लूक"},
      {nl: "mooi", hi: "सुंदर", ipa: "मोय"},
      {nl: "saai", hi: "उबाऊ", ipa: "साय"},
      {nl: "druk", hi: "भीड़भाड़ वाला", ipa: "द्रुक"},
      {nl: "rustig", hi: "शांत", ipa: "रुस-तिख"},
      {nl: "muziek", hi: "संगीत", ipa: "म्यू-ज़ीक"},
      {nl: "kunst", hi: "कला", ipa: "कुंस्ट"},
      {nl: "film", hi: "फ़िल्म", ipa: "फिल्म"},
      {nl: "stad", hi: "शहर", ipa: "स्तात"},
    ],
    phrases: [
      {nl: "Ik hou van muziek.", hi: "मुझे संगीत पसंद है।", ipa: "इक हाउ फान म्यू-ज़ीक"},
      {nl: "Ik vind deze stad mooi.", hi: "मुझे यह शहर सुंदर लगता है।", ipa: "इक फिंट डे-ज़ु स्तात मोय"},
      {nl: "Dat vind ik leuk.", hi: "मुझे वह अच्छा लगता है।", ipa: "दात फिंट इक लूक"},
      {nl: "Ik hou niet van drukke plekken.", hi: "मुझे भीड़भाड़ वाली जगहें पसंद नहीं हैं।", ipa: "इक हाउ नीत फान द्रु-कु प्ले-कुन"},
      {nl: "Het museum is interessant.", hi: "संग्रहालय रोचक है।", ipa: "हट म्यू-ज़े-उम इस इन-तु-रे-सांत"},
      {nl: "Ik wil iets rustigs.", hi: "मुझे कुछ शांत चाहिए।", ipa: "इक विल ईत्स रुस-तिख्स"},
    ],
    grammar: "पसंद बताने के दो आम तरीके हैं: “Ik hou van…” और “Ik vind… leuk/mooi.” “niet” नकारात्मकता के लिए प्रयोग होता है, जैसे “Ik hou niet van…” यानी “मुझे पसंद नहीं।” यात्रा में अपनी पसंद बताने से बेहतर सुझाव मिलते हैं।",
    practice: [
      "1. तीन चीज़ें बताइए जो आपको पसंद हैं।",
      "2. “Ik vind…” से शहर या जगह के बारे में वाक्य बनाइए।",
      "3. “Ik hou niet van…” से एक नापसंद बताइए।",
      "4. “rustig” और “druk” के साथ जगहों का वर्णन करें।",
      "5. किसी स्थानीय से सुझाव माँगने की बातचीत लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "स्वास्थ्य और फार्मेसी",
    titleNative: "Gezondheid en apotheek",
    focus: "आज आप ब्रसेल्स या एम्स्टर्डम की फार्मेसी में मदद माँगना सीखेंगे। सिरदर्द, दवा और एलर्जी जैसे जरूरी विषयों पर बात करेंगे।",
    vocab: [
      {nl: "apotheek", hi: "फार्मेसी", ipa: "आ-पो-तेक"},
      {nl: "medicijn", hi: "दवा", ipa: "मे-दी-सैन"},
      {nl: "hoofdpijn", hi: "सिरदर्द", ipa: "होफ्ट-पैन"},
      {nl: "buikpijn", hi: "पेट दर्द", ipa: "बाउक-पैन"},
      {nl: "koorts", hi: "बुखार", ipa: "कोर्त्स"},
      {nl: "allergie", hi: "एलर्जी", ipa: "आ-लेर-खी"},
      {nl: "pleister", hi: "पट्टी", ipa: "प्लै-स्तर"},
      {nl: "ziek", hi: "बीमार", ipa: "ज़ीक"},
      {nl: "pijn", hi: "दर्द", ipa: "पैन"},
      {nl: "water", hi: "पानी", ipa: "वा-तर"},
    ],
    phrases: [
      {nl: "Ik ben ziek.", hi: "मैं बीमार हूँ।", ipa: "इक बेन ज़ीक"},
      {nl: "Ik heb hoofdpijn.", hi: "मुझे सिरदर्द है।", ipa: "इक हेब होफ्ट-पैन"},
      {nl: "Heeft u medicijnen?", hi: "क्या आपके पास दवाएँ हैं?", ipa: "हेफ्ट ऊ मे-दी-सै-नुन"},
      {nl: "Ik heb een allergie.", hi: "मुझे एलर्जी है।", ipa: "इक हेब एन आ-लेर-खी"},
      {nl: "Waar is de apotheek?", hi: "फार्मेसी कहाँ है?", ipa: "वार इस दु आ-पो-तेक"},
      {nl: "Ik heb hulp nodig.", hi: "मुझे मदद चाहिए।", ipa: "इक हेब हुल्प नो-दिख"},
    ],
    grammar: "बीमारी या दर्द बताने के लिए “Ik heb…” का उपयोग करें: “Ik heb hoofdpijn,” “Ik heb koorts।” “pijn” का अर्थ दर्द है और इसे शरीर के हिस्सों के साथ जोड़ा जा सकता है। फार्मेसी में “Heeft u…” से दवा माँगना विनम्र है।",
    practice: [
      "1. तीन स्वास्थ्य समस्याएँ डच में बोलें।",
      "2. “Ik heb…” से दर्द बताने के वाक्य बनाइए।",
      "3. फार्मेसी का रास्ता पूछें।",
      "4. एलर्जी बताने का वाक्य याद करें।",
      "5. फार्मेसी में मदद माँगने का छोटा संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "फोन, इंटरनेट और कनेक्शन",
    titleNative: "Telefoon, internet en verbinding",
    focus: "आज आप एयरपोर्ट या शहर में सिम कार्ड, वाई-फाई और इंटरनेट के बारे में पूछना सीखेंगे। आधुनिक यात्रा में यह बहुत व्यावहारिक विषय है।",
    vocab: [
      {nl: "telefoon", hi: "फ़ोन", ipa: "ते-ले-फोन"},
      {nl: "internet", hi: "इंटरनेट", ipa: "इन-तर-नेट"},
      {nl: "wifi", hi: "वाई-फाई", ipa: "वै-फाइ"},
      {nl: "simkaart", hi: "सिम कार्ड", ipa: "सिम-कार्ट"},
      {nl: "oplader", hi: "चार्जर", ipa: "ओप-ला-दर"},
      {nl: "batterij", hi: "बैटरी", ipa: "बा-तु-रै"},
      {nl: "wachtwoord", hi: "पासवर्ड", ipa: "वाख्त-वोर्त"},
      {nl: "verbinding", hi: "कनेक्शन", ipa: "फेर-बिन-दिंग"},
      {nl: "werken", hi: "काम करना", ipa: "वेर-कुन"},
      {nl: "nummer", hi: "नंबर", ipa: "नु-मर"},
    ],
    phrases: [
      {nl: "Heeft u wifi?", hi: "क्या यहाँ वाई-फाई है?", ipa: "हेफ्ट ऊ वै-फाइ"},
      {nl: "Wat is het wachtwoord?", hi: "पासवर्ड क्या है?", ipa: "वात इस हट वाख्त-वोर्त"},
      {nl: "Mijn telefoon werkt niet.", hi: "मेरा फ़ोन काम नहीं कर रहा।", ipa: "मैन ते-ले-फोन वेर्क्ट नीत"},
      {nl: "Ik wil een simkaart kopen.", hi: "मुझे सिम कार्ड खरीदना है।", ipa: "इक विल एन सिम-कार्ट को-पुन"},
      {nl: "Heeft u een oplader?", hi: "क्या आपके पास चार्जर है?", ipa: "हेफ्ट ऊ एन ओप-ला-दर"},
      {nl: "Ik heb geen verbinding.", hi: "मेरा कनेक्शन नहीं है।", ipa: "इक हेब खेन फेर-बिन-दिंग"},
    ],
    grammar: "“werkt niet” का मतलब “काम नहीं कर रहा” है। “geen” संज्ञा के साथ “कोई नहीं/नहीं” देता है, जैसे “geen verbinding।” तकनीकी समस्या में छोटे और स्पष्ट वाक्य बहुत बेहतर होते हैं।",
    practice: [
      "1. वाई-फाई पासवर्ड पूछने का वाक्य बोलें।",
      "2. फ़ोन समस्या के लिए “werkt niet” का प्रयोग करें।",
      "3. “Ik wil een simkaart kopen” याद करें।",
      "4. “geen verbinding” के साथ वाक्य बनाइए।",
      "5. एयरपोर्ट सिम कार्ड काउंटर का संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "पर्यटन और आकर्षण",
    titleNative: "Toerisme en bezienswaardigheden",
    focus: "आज आप एम्स्टर्डम, ब्रुग्स या एंटवर्प जैसे शहरों में पर्यटन स्थलों के बारे में पूछना सीखेंगे। टिकट, खुलने का समय और फोटो लेने की अनुमति पर ध्यान रहेगा।",
    vocab: [
      {nl: "toerist", hi: "पर्यटक", ipa: "तू-रिस्ट"},
      {nl: "kaartje", hi: "टिकट", ipa: "कार-च्ये"},
      {nl: "museum", hi: "संग्रहालय", ipa: "म्यू-ज़े-उम"},
      {nl: "kerk", hi: "चर्च", ipa: "केर्क"},
      {nl: "rondleiding", hi: "गाइडेड टूर", ipa: "रोंट-लै-दिंग"},
      {nl: "foto", hi: "फोटो", ipa: "फो-तो"},
      {nl: "open", hi: "खुला", ipa: "ओ-पुन"},
      {nl: "gesloten", hi: "बंद", ipa: "खु-स्लो-तुन"},
      {nl: "gratis", hi: "मुफ्त", ipa: "ख्रा-तिस"},
      {nl: "ingang", hi: "प्रवेश द्वार", ipa: "इन-खांग"},
    ],
    phrases: [
      {nl: "Hoe laat gaat het museum open?", hi: "संग्रहालय कितने बजे खुलता है?", ipa: "हू लात खात हट म्यू-ज़े-उम ओ-पुन"},
      {nl: "Is de ingang hier?", hi: "क्या प्रवेश द्वार यहाँ है?", ipa: "इस दु इन-खांग हीर"},
      {nl: "Mag ik foto’s maken?", hi: "क्या मैं फोटो ले सकता हूँ?", ipa: "माख इक फो-तोस मा-कुन"},
      {nl: "Is er een rondleiding?", hi: "क्या कोई गाइडेड टूर है?", ipa: "इस एर एन रोंट-लै-दिंग"},
      {nl: "Het is gratis.", hi: "यह मुफ्त है।", ipa: "हट इस ख्रा-तिस"},
      {nl: "Ik wil twee kaartjes.", hi: "मुझे दो टिकट चाहिए।", ipa: "इक विल त्वे कार-च्यस"},
    ],
    grammar: "“Is er…” का अर्थ “क्या वहाँ है” होता है। किसी सुविधा या विकल्प के बारे में पूछने के लिए यह बहुत उपयोगी है। “Mag ik…” अनुमति माँगने के लिए है, जैसे फोटो लेना या अंदर जाना।",
    practice: [
      "1. संग्रहालय के खुलने का समय पूछें।",
      "2. फोटो लेने की अनुमति माँगें।",
      "3. “Is er…” से तीन सवाल बनाइए।",
      "4. “gratis” और “gesloten” के अर्थ लिखें।",
      "5. पर्यटन स्थल पर टिकट खरीदने का संवाद बनाइए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "टैक्सी और राइड शेयर",
    titleNative: "Taxi en ritdelen",
    focus: "आज आप एयरपोर्ट से होटल या शहर के भीतर टैक्सी लेने की भाषा सीखेंगे। गंतव्य, कीमत और समय पूछना इस पाठ का मुख्य भाग है।",
    vocab: [
      {nl: "taxi", hi: "टैक्सी", ipa: "tak-सी"},
      {nl: "chauffeur", hi: "ड्राइवर", ipa: "शो-फर"},
      {nl: "adres", hi: "पता", ipa: "आ-द्रेस"},
      {nl: "hotel", hi: "होटल", ipa: "हो-टेल"},
      {nl: "centrum", hi: "शहर केंद्र", ipa: "सेन-त्रम"},
      {nl: "rit", hi: "सवारी", ipa: "रित"},
      {nl: "contant", hi: "नकद", ipa: "कोन-तांत"},
      {nl: "kaart", hi: "कार्ड", ipa: "कार्ट"},
      {nl: "snel", hi: "जल्दी", ipa: "स्नेल"},
      {nl: "veilig", hi: "सुरक्षित", ipa: "वे-लिख"},
    ],
    phrases: [
      {nl: "Kunt u mij naar dit adres brengen?", hi: "क्या आप मुझे इस पते पर ले जा सकते हैं?", ipa: "कुंट ऊ मै नार दित आ-द्रेस ब्रें-खुन"},
      {nl: "Hoeveel kost de rit?", hi: "सवारी की कीमत कितनी है?", ipa: "हू-फेल कोस्त दु रित"},
      {nl: "Ik wil naar het centrum.", hi: "मुझे शहर केंद्र जाना है।", ipa: "इक विल नार हट सेन-त्रम"},
      {nl: "Kunt u hier stoppen?", hi: "क्या आप यहाँ रोक सकते हैं?", ipa: "कुंट ऊ हीर स्तो-पुन"},
      {nl: "Kan ik met kaart betalen?", hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?", ipa: "कान इक मेट कार्ट बु-ता-लुन"},
      {nl: "Is het ver?", hi: "क्या यह दूर है?", ipa: "इस हट फेर"},
    ],
    grammar: "“brengen” का मतलब “ले जाना/पहुँचाना” है। टैक्सी में “naar dit adres” यानी “इस पते पर” कहना उपयोगी है। “Kunt u…” औपचारिक और विनम्र अनुरोध के लिए सबसे सुरक्षित संरचना है।",
    practice: [
      "1. अपने होटल का नाम लगाकर “Ik wil naar…” बोलें।",
      "2. टैक्सी की कीमत पूछने का वाक्य याद करें।",
      "3. “Kunt u hier stoppen?” बोलें।",
      "4. कार्ड से भुगतान पूछने का अभ्यास करें।",
      "5. टैक्सी ड्राइवर के साथ 6 लाइन का संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "किराना और रोज़मर्रा की चीज़ें",
    titleNative: "Boodschappen en dagelijkse dingen",
    focus: "आज आप नीदरलैंड के सुपरमार्केट में रोज़मर्रा की चीज़ें खरीदना सीखेंगे। पानी, फल, ब्रेड और भुगतान से जुड़ी भाषा पर ध्यान रहेगा।",
    vocab: [
      {nl: "supermarkt", hi: "सुपरमार्केट", ipa: "सू-पर-मार्क्ट"},
      {nl: "brood", hi: "ब्रेड", ipa: "ब्रोट"},
      {nl: "kaas", hi: "चीज़", ipa: "कास"},
      {nl: "fruit", hi: "फल", ipa: "फ्राउट"},
      {nl: "appel", hi: "सेब", ipa: "आ-पल"},
      {nl: "banaan", hi: "केला", ipa: "बा-नान"},
      {nl: "fles", hi: "बोतल", ipa: "फ्लेस"},
      {nl: "melk", hi: "दूध", ipa: "मेल्क"},
      {nl: "bon", hi: "रसीद", ipa: "बोन"},
      {nl: "kassa", hi: "कैश काउंटर", ipa: "का-सा"},
    ],
    phrases: [
      {nl: "Waar is de supermarkt?", hi: "सुपरमार्केट कहाँ है?", ipa: "वार इस दु सू-पर-मार्क्ट"},
      {nl: "Ik zoek water.", hi: "मैं पानी ढूँढ रहा हूँ।", ipa: "इक ज़ूक वा-तर"},
      {nl: "Heeft u brood?", hi: "क्या आपके पास ब्रेड है?", ipa: "हेफ्ट ऊ ब्रोट"},
      {nl: "Ik wil een fles water.", hi: "मुझे पानी की एक बोतल चाहिए।", ipa: "इक विल एन फ्लेस वा-तर"},
      {nl: "Wilt u de bon?", hi: "क्या आपको रसीद चाहिए?", ipa: "विल्ट ऊ दु बोन"},
      {nl: "Ja, graag.", hi: "हाँ, कृपया।", ipa: "या, ख्राख"},
    ],
    grammar: "डच दुकानों में कैशियर अक्सर “Wilt u de bon?” पूछ सकता है। “Wilt u…” का मतलब “क्या आप चाहते हैं?” है। “Ik zoek…” किसी चीज़ को ढूँढने के लिए बहुत प्राकृतिक वाक्य है।",
    practice: [
      "1. पाँच किराना वस्तुएँ डच में बोलें।",
      "2. “Ik zoek…” से तीन वाक्य बनाइए।",
      "3. रसीद लेने या न लेने का जवाब दें।",
      "4. “een fles water” याद करें।",
      "5. सुपरमार्केट में खरीदारी का छोटा संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "आपातकाल और सुरक्षा",
    titleNative: "Noodgeval en veiligheid",
    focus: "आज आप किसी आपात स्थिति में मदद माँगना सीखेंगे। यह पाठ पुलिस, डॉक्टर, खोया सामान और सुरक्षा से जुड़े जरूरी वाक्यों पर केंद्रित है।",
    vocab: [
      {nl: "noodgeval", hi: "आपातकाल", ipa: "नोड-खु-फाल"},
      {nl: "politie", hi: "पुलिस", ipa: "पो-ली-त्सी"},
      {nl: "ambulance", hi: "एम्बुलेंस", ipa: "आम-बू-लांस"},
      {nl: "brand", hi: "आग", ipa: "ब्रांत"},
      {nl: "veilig", hi: "सुरक्षित", ipa: "वे-लिख"},
      {nl: "gevaarlijk", hi: "खतरनाक", ipa: "खु-फार-लुक"},
      {nl: "gestolen", hi: "चोरी हुआ", ipa: "खु-स्तो-लुन"},
      {nl: "tas", hi: "बैग", ipa: "तास"},
      {nl: "paspoort", hi: "पासपोर्ट", ipa: "पास-पोर्ट"},
      {nl: "help", hi: "मदद", ipa: "हेल्प"},
    ],
    phrases: [
      {nl: "Help!", hi: "मदद!", ipa: "हेल्प"},
      {nl: "Bel de politie!", hi: "पुलिस को कॉल करें!", ipa: "बेल दु पो-ली-त्सी"},
      {nl: "Ik ben mijn tas kwijt.", hi: "मेरा बैग खो गया है।", ipa: "इक बेन मैन तास क्वैत"},
      {nl: "Mijn paspoort is gestolen.", hi: "मेरा पासपोर्ट चोरी हो गया है।", ipa: "मैन पास-पोर्ट इस खु-स्तो-लुन"},
      {nl: "Is het hier veilig?", hi: "क्या यहाँ सुरक्षित है?", ipa: "इस हट हीर वे-लिख"},
      {nl: "Ik heb een noodgeval.", hi: "मेरे पास आपात स्थिति है।", ipa: "इक हेब एन नोड-खु-फाल"},
    ],
    grammar: "“kwijt” का अर्थ “खोया हुआ” है और “gestolen” का अर्थ “चोरी हुआ।” “Ik ben mijn tas kwijt” डच में सामान्य तरीका है कहने का कि मेरा बैग खो गया है। आपात स्थिति में छोटे, साफ़ वाक्य सबसे उपयोगी होते हैं।",
    practice: [
      "1. “Help!” और “Bel de politie!” जोर से बोलकर अभ्यास करें।",
      "2. खोया बैग बताने का वाक्य याद करें।",
      "3. पासपोर्ट चोरी होने का वाक्य लिखें।",
      "4. “veilig” और “gevaarlijk” का अर्थ बताइए।",
      "5. आपात स्थिति पर 5 लाइन का संवाद बनाइए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "आवास में समस्याएँ",
    titleNative: "Problemen met accommodatie",
    focus: "आज आप होटल या अपार्टमेंट में समस्या बताना सीखेंगे। कमरे की चाबी, गर्म पानी, वाई-फाई और शोर जैसी स्थितियों पर ध्यान रहेगा।",
    vocab: [
      {nl: "probleem", hi: "समस्या", ipa: "प्रो-ब्लेम"},
      {nl: "kamer", hi: "कमरा", ipa: "का-मर"},
      {nl: "sleutel", hi: "चाबी", ipa: "स्लोय-तल"},
      {nl: "douche", hi: "शॉवर", ipa: "दूश"},
      {nl: "warm water", hi: "गर्म पानी", ipa: "वार्म वा-तर"},
      {nl: "koud water", hi: "ठंडा पानी", ipa: "काउट वा-तर"},
      {nl: "lawaai", hi: "शोर", ipa: "ला-वाय"},
      {nl: "airco", hi: "ए.सी.", ipa: "एर-को"},
      {nl: "repareren", hi: "ठीक करना", ipa: "रे-पा-रे-रुन"},
      {nl: "schoon", hi: "साफ़", ipa: "स्कोन"},
    ],
    phrases: [
      {nl: "Er is een probleem.", hi: "एक समस्या है।", ipa: "एर इस एन प्रो-ब्लेम"},
      {nl: "Mijn sleutel werkt niet.", hi: "मेरी चाबी काम नहीं कर रही।", ipa: "मैन स्लोय-तल वेर्क्ट नीत"},
      {nl: "Er is geen warm water.", hi: "गर्म पानी नहीं है।", ipa: "एर इस खेन वार्म वा-तर"},
      {nl: "De kamer is niet schoon.", hi: "कमरा साफ़ नहीं है।", ipa: "दु का-मर इस नीत स्कोन"},
      {nl: "Het is te lawaaiig.", hi: "बहुत शोर है।", ipa: "हट इस तु ला-वाय-ख"},
      {nl: "Kunt u dit repareren?", hi: "क्या आप इसे ठीक कर सकते हैं?", ipa: "कुंट ऊ दित रे-पा-रे-रुन"},
    ],
    grammar: "“Er is…” का अर्थ “वहाँ है” या “एक … है” होता है। समस्या बताने में यह बहुत काम आता है: “Er is een probleem,” “Er is geen warm water।” “werkt niet” फिर से उपकरण या चीज़ के काम न करने के लिए प्रयोग होता है।",
    practice: [
      "1. होटल की तीन समस्याएँ डच में बताइए।",
      "2. “Er is geen…” से दो वाक्य बनाइए।",
      "3. “Kunt u dit repareren?” बोलें।",
      "4. “niet schoon” और “te lawaaiig” याद करें।",
      "5. रिसेप्शन पर शिकायत का संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "निमंत्रण और योजना बनाना",
    titleNative: "Uitnodigen en plannen maken",
    focus: "आज आप किसी स्थानीय दोस्त या साथी यात्री के साथ योजना बनाना सीखेंगे। कॉफ़ी, म्यूज़ियम या शाम की मुलाकात के लिए निमंत्रण देना सीखेंगे।",
    vocab: [
      {nl: "plan", hi: "योजना", ipa: "प्लान"},
      {nl: "afspraak", hi: "मुलाकात / अपॉइंटमेंट", ipa: "आफ-स्प्राक"},
      {nl: "samen", hi: "साथ", ipa: "सा-मुन"},
      {nl: "vanavond", hi: "आज शाम", ipa: "फान-आ-वोंत"},
      {nl: "morgen", hi: "कल", ipa: "मोर-खुन"},
      {nl: "tijd", hi: "समय", ipa: "तैद"},
      {nl: "vrij", hi: "खाली / स्वतंत्र", ipa: "फ्रै"},
      {nl: "bezig", hi: "व्यस्त", ipa: "बे-ज़िख"},
      {nl: "café", hi: "कैफ़े", ipa: "का-फे"},
      {nl: "misschien", hi: "शायद", ipa: "मिस-खीन"},
    ],
    phrases: [
      {nl: "Heb je vanavond tijd?", hi: "क्या तुम्हारे पास आज शाम समय है?", ipa: "हेब यु फान-आ-वोंत तैद"},
      {nl: "Zullen we koffie drinken?", hi: "क्या हम कॉफ़ी पिएँ?", ipa: "ज़ु-लुन वु को-फी द्रिंक-कुन"},
      {nl: "Ik ben morgen vrij.", hi: "मैं कल खाली हूँ।", ipa: "इक बेन मोर-खुन फ्रै"},
      {nl: "Ik ben nu bezig.", hi: "मैं अभी व्यस्त हूँ।", ipa: "इक बेन नू बे-ज़िख"},
      {nl: "Misschien later.", hi: "शायद बाद में।", ipa: "मिस-खीन ला-तर"},
      {nl: "Dat klinkt goed.", hi: "यह अच्छा लगता है।", ipa: "दात क्लिंक्त खू트"},
    ],
    grammar: "दोस्ताना सुझाव के लिए “Zullen we…” बहुत स्वाभाविक है। “Heb je tijd?” अनौपचारिक है, दोस्तों या समान उम्र के लोगों से बात करते समय ठीक है। औपचारिक स्थिति में “Heeft u tijd?” कहना बेहतर है।",
    practice: [
      "1. कॉफ़ी के लिए निमंत्रण दीजिए।",
      "2. “Ik ben morgen vrij” से अपनी उपलब्धता बताइए।",
      "3. “Misschien later” का उपयोग करके विनम्र मना करें।",
      "4. “Dat klinkt goed” बोलकर अभ्यास करें।",
      "5. शाम की योजना का छोटा संवाद बनाइए।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "स्थानीय संस्कृति और शिष्टाचार",
    titleNative: "Lokale cultuur en beleefdheid",
    focus: "आज आप नीदरलैंड और बेल्जियम में सामान्य शिष्टाचार और सांस्कृतिक भाषा सीखेंगे। सीधे लेकिन विनम्र बोलना, धन्यवाद कहना और व्यक्तिगत स्थान समझना महत्वपूर्ण है।",
    vocab: [
      {nl: "beleefd", hi: "विनम्र", ipa: "बु-लेफ्ट"},
      {nl: "direct", hi: "सीधा", ipa: "दी-रेक्ट"},
      {nl: "respect", hi: "सम्मान", ipa: "रे-स्पेक्ट"},
      {nl: "wachtrij", hi: "कतार", ipa: "वाख्त-रै"},
      {nl: "stil", hi: "शांत", ipa: "स्तिल"},
      {nl: "druk", hi: "व्यस्त / भीड़", ipa: "द्रुक"},
      {nl: "fiets", hi: "साइकिल", ipa: "फीत्स"},
      {nl: "fietspad", hi: "साइकिल लेन", ipa: "फीत्स-पात"},
      {nl: "regels", hi: "नियम", ipa: "रे-खुल्स"},
      {nl: "cultuur", hi: "संस्कृति", ipa: "कुल-तूर"},
    ],
    phrases: [
      {nl: "Waar is de wachtrij?", hi: "कतार कहाँ है?", ipa: "वार इस दु वाख्त-रै"},
      {nl: "Mag ik hier zitten?", hi: "क्या मैं यहाँ बैठ सकता हूँ?", ipa: "माख इक हीर ज़ि-तुन"},
      {nl: "Sorry, is dit uw fiets?", hi: "माफ़ कीजिए, क्या यह आपकी साइकिल है?", ipa: "सो-री, इस दित ऊ फीत्स"},
      {nl: "Ik begrijp de regels niet.", hi: "मैं नियम नहीं समझता।", ipa: "इक बु-ख्रैप दु रे-खुल्स नीत"},
      {nl: "Dank u voor uw hulp.", hi: "आपकी मदद के लिए धन्यवाद।", ipa: "दांक ऊ फोर ऊ हुल्प"},
      {nl: "Geen zorgen.", hi: "चिंता मत कीजिए।", ipa: "खेन ज़ोर-खुन"},
    ],
    grammar: "डच लोग अक्सर सीधे बोलते हैं, लेकिन इसका मतलब असभ्यता नहीं होता। “Mag ik…” अनुमति माँगने का विनम्र तरीका है। साइकिल लेन पर चलते समय सावधान रहें, क्योंकि “fietspad” पैदल चलने के लिए नहीं होता।",
    practice: [
      "1. बैठने की अनुमति माँगें।",
      "2. कतार कहाँ है, पूछें।",
      "3. “Dank u voor uw hulp” बोलें।",
      "4. “fietspad” का अर्थ याद करें।",
      "5. किसी सांस्कृतिक गलती को विनम्रता से समझने का संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "डाकघर और सेवाएँ",
    titleNative: "Postkantoor en diensten",
    focus: "आज आप पोस्टकार्ड भेजना, स्टैम्प खरीदना और सेवा काउंटर पर बात करना सीखेंगे। यात्रा में छोटी सेवाओं के लिए यह भाषा उपयोगी है।",
    vocab: [
      {nl: "postkantoor", hi: "डाकघर", ipa: "पोस्ट-कान-तोर"},
      {nl: "postkaart", hi: "पोस्टकार्ड", ipa: "पोस्ट-कार्ट"},
      {nl: "zegel", hi: "स्टैम्प", ipa: "ज़े-खुल"},
      {nl: "pakket", hi: "पैकेट", ipa: "पा-केट"},
      {nl: "adres", hi: "पता", ipa: "आ-द्रेस"},
      {nl: "formulier", hi: "फॉर्म", ipa: "फोर-म्यू-लीर"},
      {nl: "sturen", hi: "भेजना", ipa: "स्तू-रुन"},
      {nl: "ontvangen", hi: "प्राप्त करना", ipa: "ओंट-फांग-उन"},
      {nl: "handtekening", hi: "हस्ताक्षर", ipa: "हांत-ते-के-निंग"},
      {nl: "loket", hi: "काउंटर", ipa: "लो-केट"},
    ],
    phrases: [
      {nl: "Ik wil een postkaart sturen.", hi: "मैं पोस्टकार्ड भेजना चाहता हूँ।", ipa: "इक विल एन पोस्ट-कार्ट स्तू-रुन"},
      {nl: "Heeft u zegels?", hi: "क्या आपके पास स्टैम्प हैं?", ipa: "हेफ्ट ऊ ज़े-खुल्स"},
      {nl: "Waar is het postkantoor?", hi: "डाकघर कहाँ है?", ipa: "वार इस हट पोस्ट-कान-तोर"},
      {nl: "Moet ik dit formulier invullen?", hi: "क्या मुझे यह फॉर्म भरना है?", ipa: "मूट इक दित फोर-म्यू-लीर इन-फु-लुन"},
      {nl: "Ik heb een pakket.", hi: "मेरे पास एक पैकेट है।", ipa: "इक हेब एन पा-केट"},
      {nl: "Is een handtekening nodig?", hi: "क्या हस्ताक्षर जरूरी है?", ipa: "इस एन हांत-ते-के-निंग नो-दिख"},
    ],
    grammar: "“moet” का मतलब “चाहिए/करना होगा” है। “Moet ik…?” से आप पूछते हैं कि क्या मुझे कुछ करना है। सेवा काउंटर पर यह बहुत उपयोगी है, खासकर फॉर्म, भुगतान या पहचान पत्र के लिए।",
    practice: [
      "1. पोस्टकार्ड भेजने का वाक्य बोलें।",
      "2. स्टैम्प माँगने का अभ्यास करें।",
      "3. “Moet ik…” से तीन सवाल बनाइए।",
      "4. “adres” और “formulier” याद करें।",
      "5. डाकघर में 6 लाइन का संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "बैंक, पैसे और भुगतान",
    titleNative: "Bank, geld en betalen",
    focus: "आज आप एटीएम, कार्ड भुगतान और नकद पैसे से जुड़ी भाषा सीखेंगे। यात्रा में भुगतान की समस्या को समझना और बताना जरूरी है।",
    vocab: [
      {nl: "bank", hi: "बैंक", ipa: "बांक"},
      {nl: "geld", hi: "पैसा", ipa: "खेल्ट"},
      {nl: "pinnen", hi: "कार्ड से भुगतान / एटीएम से निकालना", ipa: "पिन-नुन"},
      {nl: "automaat", hi: "मशीन / एटीएम", ipa: "आउ-तो-मात"},
      {nl: "contant", hi: "नकद", ipa: "कोन-तांत"},
      {nl: "kaart", hi: "कार्ड", ipa: "कार्ट"},
      {nl: "wisselen", hi: "बदलना", ipa: "विस-लुन"},
      {nl: "rekening", hi: "खाता / बिल", ipa: "रे-कु-निंग"},
      {nl: "betaling", hi: "भुगतान", ipa: "बु-ता-लिंग"},
      {nl: "bon", hi: "रसीद", ipa: "बोन"},
    ],
    phrases: [
      {nl: "Waar is een geldautomaat?", hi: "एटीएम कहाँ है?", ipa: "वार इस एन खेल्ट-आउ-तो-मात"},
      {nl: "Kan ik hier pinnen?", hi: "क्या मैं यहाँ कार्ड से भुगतान कर सकता हूँ?", ipa: "कान इक हीर पिन-नुन"},
      {nl: "Ik heb contant geld nodig.", hi: "मुझे नकद पैसा चाहिए।", ipa: "इक हेब कोन-तांत खेल्ट नो-दिख"},
      {nl: "Mijn kaart werkt niet.", hi: "मेरा कार्ड काम नहीं कर रहा।", ipa: "मैन कार्ट वेर्क्ट नीत"},
      {nl: "Kan ik geld wisselen?", hi: "क्या मैं पैसे बदल सकता हूँ?", ipa: "कान इक खेल्ट विस-लुन"},
      {nl: "Mag ik de bon?", hi: "क्या मुझे रसीद मिल सकती है?", ipa: "माख इक दु बोन"},
    ],
    grammar: "नीदरलैंड में “pinnen” बहुत आम शब्द है और इसका मतलब कार्ड से भुगतान करना या एटीएम से पैसा निकालना हो सकता है। “Kan ik hier pinnen?” दुकान में बहुत उपयोगी प्रश्न है। “werkt niet” फिर से समस्या बताने के लिए इस्तेमाल करें।",
    practice: [
      "1. एटीएम पूछने का वाक्य बोलें।",
      "2. कार्ड से भुगतान का प्रश्न याद करें।",
      "3. “Mijn kaart werkt niet” का अभ्यास करें।",
      "4. नकद पैसे की ज़रूरत बताइए।",
      "5. भुगतान समस्या पर छोटा संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "राय देना और समस्या समझाना",
    titleNative: "Mening geven en probleem uitleggen",
    focus: "आज आप अनुभव, राय और छोटी शिकायतें बताना सीखेंगे। होटल, रेस्टोरेंट या यात्रा सेवा में यह भाषा बहुत उपयोगी है।",
    vocab: [
      {nl: "mening", hi: "राय", ipa: "मे-निंग"},
      {nl: "ervaring", hi: "अनुभव", ipa: "एर-फा-रिंग"},
      {nl: "goed", hi: "अच्छा", ipa: "खू트"},
      {nl: "slecht", hi: "बुरा", ipa: "स्लेख्ट"},
      {nl: "beter", hi: "बेहतर", ipa: "बे-तर"},
      {nl: "probleem", hi: "समस्या", ipa: "प्रो-ब्लेम"},
      {nl: "oplossing", hi: "समाधान", ipa: "ओप-लो-सिंग"},
      {nl: "lang", hi: "लंबा", ipa: "लांग"},
      {nl: "kort", hi: "छोटा", ipa: "कोर्ट"},
      {nl: "vriendelijk", hi: "मित्रवत", ipa: "फ्रींट-लुक"},
    ],
    phrases: [
      {nl: "Ik vind het goed.", hi: "मुझे यह अच्छा लगता है।", ipa: "इक फिंट हट खू트"},
      {nl: "Ik vind het niet goed.", hi: "मुझे यह अच्छा नहीं लगता।", ipa: "इक फिंट हट नीत खू트"},
      {nl: "De service is vriendelijk.", hi: "सेवा मित्रवत है।", ipa: "दु सेर-विस इस फ्रींट-लुक"},
      {nl: "Er is een klein probleem.", hi: "एक छोटी समस्या है।", ipa: "एर इस एन क्लैन प्रो-ब्लेम"},
      {nl: "Kunt u een oplossing vinden?", hi: "क्या आप समाधान ढूँढ सकते हैं?", ipa: "कुंट ऊ एन ओप-लो-सिंग फिन-दुन"},
      {nl: "Dat is beter.", hi: "यह बेहतर है।", ipa: "दात इस बे-तर"},
    ],
    grammar: "राय देने के लिए “Ik vind…” बहुत महत्वपूर्ण है। “Ik vind het goed” या “Ik vind het niet goed” से आप स्पष्ट लेकिन विनम्र प्रतिक्रिया दे सकते हैं। समस्या बताकर समाधान माँगना “Kunt u een oplossing vinden?” से किया जा सकता है।",
    practice: [
      "1. किसी होटल या कैफ़े पर राय दें।",
      "2. “Ik vind…” से तीन वाक्य बनाइए।",
      "3. छोटी समस्या बताने का वाक्य बोलें।",
      "4. “beter” का उपयोग करके सुधार बताइए।",
      "5. ग्राहक सेवा से समाधान माँगने का संवाद लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "बातचीत को जारी रखना",
    titleNative: "Een gesprek gaande houden",
    focus: "आज आप स्थानीय व्यक्ति से बातचीत जारी रखने के तरीके सीखेंगे। प्रश्न पूछना, प्रतिक्रिया देना और रुचि दिखाना इस पाठ का लक्ष्य है।",
    vocab: [
      {nl: "waarom", hi: "क्यों", ipa: "वार-ओम"},
      {nl: "wanneer", hi: "कब", ipa: "वा-नेर"},
      {nl: "wie", hi: "कौन", ipa: "वी"},
      {nl: "wat", hi: "क्या", ipa: "वात"},
      {nl: "waar", hi: "कहाँ", ipa: "वार"},
      {nl: "interessant", hi: "रोचक", ipa: "इन-तु-रे-सांत"},
      {nl: "echt", hi: "सच में", ipa: "एख्त"},
      {nl: "natuurlijk", hi: "बिल्कुल / स्वाभाविक रूप से", ipa: "ना-तूर-लुक"},
      {nl: "misschien", hi: "शायद", ipa: "मिस-खीन"},
      {nl: "verhaal", hi: "कहानी", ipa: "फर-हाल"},
    ],
    phrases: [
      {nl: "Dat is interessant.", hi: "यह रोचक है।", ipa: "दात इस इन-तु-रे-सांत"},
      {nl: "Echt waar?", hi: "सच में?", ipa: "एख्त वार"},
      {nl: "Waarom niet?", hi: "क्यों नहीं?", ipa: "वार-ओम नीत"},
      {nl: "Wanneer ga je?", hi: "तुम कब जा रहे हो?", ipa: "वा-नेर खा यु"},
      {nl: "Wat bedoel je?", hi: "तुम्हारा मतलब क्या है?", ipa: "वात बु-दूल यु"},
      {nl: "Vertel me meer.", hi: "मुझे और बताओ।", ipa: "फेर-टेल मु मेर"},
    ],
    grammar: "खुले सवाल बातचीत को आगे बढ़ाते हैं। “wat,” “waar,” “wanneer,” “waarom,” और “wie” सबसे जरूरी प्रश्न शब्द हैं। “Echt waar?” और “Dat is interessant” जैसे छोटे जवाब बातचीत को प्राकृतिक बनाते हैं।",
    practice: [
      "1. पाँच प्रश्न शब्दों से पाँच सवाल बनाइए।",
      "2. “Echt waar?” का उच्चारण करें।",
      "3. “Vertel me meer” का प्रयोग करके बातचीत बढ़ाएँ।",
      "4. किसी यात्रा कहानी पर प्रतिक्रिया लिखें।",
      "5. स्थानीय व्यक्ति से छोटी बातचीत लिखें।",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "यात्रा समीक्षा और आत्मविश्वास",
    titleNative: "Reisoverzicht en vertrouwen",
    focus: "आज आप पूरी यात्रा भाषा को जोड़ेंगे: परिचय, दिशा, भोजन, होटल, परिवहन और मदद। उद्देश्य है डच-भाषी देश में आत्मविश्वास से बुनियादी संवाद करना।",
    vocab: [
      {nl: "reis", hi: "यात्रा", ipa: "रैस"},
      {nl: "vertrouwen", hi: "आत्मविश्वास", ipa: "फेर-त्राउ-वुन"},
      {nl: "herhalen", hi: "दोहराना", ipa: "हे-रा-लुन"},
      {nl: "oefenen", hi: "अभ्यास करना", ipa: "ऊ-फु-नुन"},
      {nl: "vragen", hi: "पूछना", ipa: "फ्रा-खुन"},
      {nl: "antwoorden", hi: "जवाब देना", ipa: "आंट-वोर-दुन"},
      {nl: "begrijpen", hi: "समझना", ipa: "बु-ख्रै-पुन"},
      {nl: "spreken", hi: "बोलना", ipa: "स्प्रे-कुन"},
      {nl: "luisteren", hi: "सुनना", ipa: "लाउस-तु-रुन"},
      {nl: "klaar", hi: "तैयार", ipa: "क्लार"},
    ],
    phrases: [
      {nl: "Ik ben klaar voor mijn reis.", hi: "मैं अपनी यात्रा के लिए तैयार हूँ।", ipa: "इक बेन क्लार फोर मैन रैस"},
      {nl: "Ik kan eenvoudige zinnen spreken.", hi: "मैं सरल वाक्य बोल सकता हूँ।", ipa: "इक कान ऐन-फाउ-दु-खु ज़िन-नुन स्प्रे-कुन"},
      {nl: "Kunt u dat herhalen?", hi: "क्या आप वह दोहरा सकते हैं?", ipa: "कुंट ऊ दात हे-रा-लुन"},
      {nl: "Ik begrijp een beetje Nederlands.", hi: "मैं थोड़ा डच समझता हूँ।", ipa: "इक बु-ख्रैप एन बु-टीयु ने-दर-लांट्स"},
      {nl: "Ik wil blijven oefenen.", hi: "मैं अभ्यास जारी रखना चाहता हूँ।", ipa: "इक विल ब्लै-वुन ऊ-फु-नुन"},
      {nl: "Bedankt voor uw hulp.", hi: "आपकी मदद के लिए धन्यवाद।", ipa: "बु-दांक्त फोर ऊ हुल्प"},
    ],
    grammar: "अब आपके पास यात्रा के लिए सबसे जरूरी संरचनाएँ हैं: “Ik ben,” “Ik heb,” “Ik wil,” “Mag ik,” “Kan ik,” और “Kunt u।” इनसे आप परिचय, ज़रूरत, अनुमति, भुगतान, मदद और समस्या लगभग हर स्थिति में व्यक्त कर सकते हैं। गलती होना सामान्य है; विनम्रता और स्पष्टता सबसे ज्यादा मदद करती है।",
    practice: [
      "1. अपने बारे में पाँच डच वाक्य बोलें।",
      "2. होटल, कैफ़े और स्टेशन के लिए एक-एक वाक्य लिखें।",
      "3. “Kunt u dat herhalen?” याद करें।",
      "4. अपनी सबसे उपयोगी दस डच पंक्तियाँ दोहराएँ।",
      "5. पूरे यात्रा दिन का 10 लाइन संवाद बनाइए।",
    ],
    conversationIndex: 0,
    conversationCount: 8,
  },
];

var CONVERSATIONS_HI_NL = [
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedemorgen, wat wilt u drinken?", hi: "सुप्रभात, आप क्या पीना चाहेंगे?"},
      {who: "you", nl: "Goedemorgen, ik wil graag een koffie.", hi: "सुप्रभात, मुझे एक कॉफ़ी चाहिए।"},
      {who: "them", nl: "Met melk en suiker?", hi: "दूध और चीनी के साथ?"},
      {who: "you", nl: "Met melk, maar zonder suiker, graag.", hi: "दूध के साथ, लेकिन बिना चीनी के, कृपया।"},
      {who: "them", nl: "Natuurlijk, wilt u ook iets eten?", hi: "बिल्कुल, क्या आप कुछ खाना भी चाहेंगे?"},
      {who: "you", nl: "Ja, een broodje kaas, alstublieft.", hi: "हाँ, एक चीज़ सैंडविच, कृपया।"},
      {who: "them", nl: "Prima, dat is samen zeven euro.", hi: "ठीक है, कुल सात यूरो होंगे।"},
      {who: "you", nl: "Kan ik met kaart betalen?", hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?"},
      {who: "them", nl: "Ja, u kunt hier pinnen.", hi: "हाँ, आप यहाँ कार्ड से भुगतान कर सकते हैं।"},
      {who: "you", nl: "Dank u wel.", hi: "बहुत धन्यवाद।"},
      {who: "them", nl: "Graag gedaan, fijne dag!", hi: "आपका स्वागत है, आपका दिन अच्छा हो!"},
      {who: "you", nl: "Dank u, tot ziens.", hi: "धन्यवाद, फिर मिलेंगे।"},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedenavond, welkom in ons hotel.", hi: "शुभ संध्या, हमारे होटल में आपका स्वागत है।"},
      {who: "you", nl: "Goedenavond, ik heb een reservering.", hi: "शुभ संध्या, मेरा आरक्षण है।"},
      {who: "them", nl: "Op welke naam is de reservering?", hi: "आरक्षण किस नाम पर है?"},
      {who: "you", nl: "Mijn naam is Ravi Sharma.", hi: "मेरा नाम रवि शर्मा है।"},
      {who: "them", nl: "Mag ik uw paspoort zien?", hi: "क्या मैं आपका पासपोर्ट देख सकता हूँ?"},
      {who: "you", nl: "Ja, hier is mijn paspoort.", hi: "हाँ, यह मेरा पासपोर्ट है।"},
      {who: "them", nl: "Dank u, u heeft kamer 204.", hi: "धन्यवाद, आपका कमरा 204 है।"},
      {who: "you", nl: "Is ontbijt inbegrepen?", hi: "क्या नाश्ता शामिल है?"},
      {who: "them", nl: "Ja, ontbijt is van zeven tot tien uur.", hi: "हाँ, नाश्ता सात से दस बजे तक है।"},
      {who: "you", nl: "Waar is de lift?", hi: "लिफ्ट कहाँ है?"},
      {who: "them", nl: "De lift is rechts, naast de receptie.", hi: "लिफ्ट दाएँ है, रिसेप्शन के पास।"},
      {who: "you", nl: "Dank u voor uw hulp.", hi: "आपकी मदद के लिए धन्यवाद।"},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", nl: "Sorry, kunt u mij helpen?", hi: "माफ़ कीजिए, क्या आप मेरी मदद कर सकते हैं?"},
      {who: "them", nl: "Ja natuurlijk, wat zoekt u?", hi: "हाँ बिल्कुल, आप क्या ढूँढ रहे हैं?"},
      {who: "you", nl: "Waar is het museum?", hi: "संग्रहालय कहाँ है?"},
      {who: "them", nl: "Ga rechtdoor en sla dan linksaf.", hi: "सीधे जाइए और फिर बाएँ मुड़िए।"},
      {who: "you", nl: "Is het dichtbij?", hi: "क्या यह पास है?"},
      {who: "them", nl: "Ja, ongeveer tien minuten lopen.", hi: "हाँ, लगभग दस मिनट पैदल।"},
      {who: "you", nl: "Moet ik over de brug?", hi: "क्या मुझे पुल पार करना होगा?"},
      {who: "them", nl: "Ja, de brug is voor het museum.", hi: "हाँ, पुल संग्रहालय से पहले है।"},
      {who: "you", nl: "Kunt u dat herhalen?", hi: "क्या आप वह दोहरा सकते हैं?"},
      {who: "them", nl: "Rechtdoor, linksaf, en dan over de brug.", hi: "सीधे, बाएँ, और फिर पुल पार।"},
      {who: "you", nl: "Dank u wel.", hi: "बहुत धन्यवाद।"},
      {who: "them", nl: "Geen probleem, fijne dag.", hi: "कोई बात नहीं, आपका दिन अच्छा हो।"},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedenavond, heeft u gereserveerd?", hi: "शुभ संध्या, क्या आपने आरक्षण किया है?"},
      {who: "you", nl: "Nee, heeft u een tafel voor twee?", hi: "नहीं, क्या दो लोगों के लिए मेज़ है?"},
      {who: "them", nl: "Ja, volgt u mij maar.", hi: "हाँ, कृपया मेरे साथ आइए।"},
      {who: "you", nl: "Heeft u vegetarische gerechten?", hi: "क्या आपके पास शाकाहारी व्यंजन हैं?"},
      {who: "them", nl: "Ja, we hebben salade, soep en pasta.", hi: "हाँ, हमारे पास सलाद, सूप और पास्ता है।"},
      {who: "you", nl: "Ik neem de pasta, alstublieft.", hi: "मैं पास्ता लूँगा, कृपया।"},
      {who: "them", nl: "Wilt u iets drinken?", hi: "क्या आप कुछ पीना चाहेंगे?"},
      {who: "you", nl: "Een glas water, graag.", hi: "एक गिलास पानी, कृपया।"},
      {who: "them", nl: "Was alles naar wens?", hi: "क्या सब आपकी पसंद के अनुसार था?"},
      {who: "you", nl: "Ja, het was heerlijk.", hi: "हाँ, यह बहुत स्वादिष्ट था।"},
      {who: "you", nl: "Mag ik de rekening?", hi: "क्या मुझे बिल मिल सकता है?"},
      {who: "them", nl: "Natuurlijk, ik breng de rekening meteen.", hi: "बिल्कुल, मैं अभी बिल लाता हूँ।"},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedemiddag, waarmee kan ik u helpen?", hi: "नमस्कार, मैं आपकी किस तरह मदद कर सकता हूँ?"},
      {who: "you", nl: "Ik wil een ticket naar Leiden.", hi: "मुझे लाइडेन का टिकट चाहिए।"},
      {who: "them", nl: "Enkele reis of retour?", hi: "एक तरफ़ा या वापसी टिकट?"},
      {who: "you", nl: "Retour, alstublieft.", hi: "वापसी टिकट, कृपया।"},
      {who: "them", nl: "Dat is achttien euro.", hi: "यह अठारह यूरो है।"},
      {who: "you", nl: "Kan ik met kaart betalen?", hi: "क्या मैं कार्ड से भुगतान कर सकता हूँ?"},
      {who: "them", nl: "Ja, dat kan.", hi: "हाँ, कर सकते हैं।"},
      {who: "you", nl: "Hoe laat vertrekt de trein?", hi: "ट्रेन कितने बजे निकलती है?"},
      {who: "them", nl: "De trein vertrekt om twee uur.", hi: "ट्रेन दो बजे निकलती है।"},
      {who: "you", nl: "Waar is het perron?", hi: "प्लेटफ़ॉर्म कहाँ है?"},
      {who: "them", nl: "Perron vijf, aan de linkerkant.", hi: "प्लेटफ़ॉर्म पाँच, बाईं तरफ।"},
      {who: "you", nl: "Dank u wel.", hi: "बहुत धन्यवाद।"},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Hallo, kan ik u helpen?", hi: "नमस्ते, क्या मैं आपकी मदद कर सकता हूँ?"},
      {who: "you", nl: "Ja, ik zoek een jas.", hi: "हाँ, मैं एक जैकेट ढूँढ रहा हूँ।"},
      {who: "them", nl: "Welke kleur wilt u?", hi: "आप कौन सा रंग चाहते हैं?"},
      {who: "you", nl: "Heeft u dit in blauw?", hi: "क्या यह नीले रंग में है?"},
      {who: "them", nl: "Ja, hier is een blauwe jas.", hi: "हाँ, यह नीली जैकेट है।"},
      {who: "you", nl: "Mag ik dit passen?", hi: "क्या मैं इसे ट्राय कर सकता हूँ?"},
      {who: "them", nl: "Natuurlijk, de paskamer is rechts.", hi: "बिल्कुल, ट्रायल रूम दाएँ है।"},
      {who: "you", nl: "Het is te klein.", hi: "यह बहुत छोटा है।"},
      {who: "them", nl: "Ik haal een grotere maat.", hi: "मैं बड़ा साइज़ लाता हूँ।"},
      {who: "you", nl: "Dank u, deze past goed.", hi: "धन्यवाद, यह अच्छी तरह फिट है।"},
      {who: "them", nl: "Wilt u deze nemen?", hi: "क्या आप इसे लेना चाहेंगे?"},
      {who: "you", nl: "Ja, ik neem deze.", hi: "हाँ, मैं यह लूँगा।"},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedemiddag, wat heeft u nodig?", hi: "नमस्कार, आपको क्या चाहिए?"},
      {who: "you", nl: "Ik heb hoofdpijn.", hi: "मुझे सिरदर्द है।"},
      {who: "them", nl: "Heeft u koorts?", hi: "क्या आपको बुखार है?"},
      {who: "you", nl: "Nee, alleen hoofdpijn.", hi: "नहीं, सिर्फ सिरदर्द है।"},
      {who: "them", nl: "Heeft u een allergie?", hi: "क्या आपको कोई एलर्जी है?"},
      {who: "you", nl: "Ja, ik heb een allergie voor penicilline.", hi: "हाँ, मुझे पेनिसिलिन से एलर्जी है।"},
      {who: "them", nl: "Dan raad ik deze medicijnen aan.", hi: "तब मैं ये दवाएँ सुझाता हूँ।"},
      {who: "you", nl: "Hoe vaak moet ik ze nemen?", hi: "मुझे इन्हें कितनी बार लेना है?"},
      {who: "them", nl: "Twee keer per dag met water.", hi: "दिन में दो बार पानी के साथ।"},
      {who: "you", nl: "Heeft u ook water?", hi: "क्या आपके पास पानी भी है?"},
      {who: "them", nl: "Ja, naast de kassa.", hi: "हाँ, कैश काउंटर के पास।"},
      {who: "you", nl: "Dank u voor uw hulp.", hi: "आपकी मदद के लिए धन्यवाद।"},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", nl: "Hallo, mag ik hier zitten?", hi: "नमस्ते, क्या मैं यहाँ बैठ सकता हूँ?"},
      {who: "them", nl: "Ja hoor, deze stoel is vrij.", hi: "हाँ बिल्कुल, यह कुर्सी खाली है।"},
      {who: "you", nl: "Dank je, ik ben hier voor het eerst.", hi: "धन्यवाद, मैं यहाँ पहली बार आया हूँ।"},
      {who: "them", nl: "Welkom, vind je Haarlem leuk?", hi: "स्वागत है, क्या तुम्हें हार्लेम अच्छा लग रहा है?"},
      {who: "you", nl: "Ja, ik vind de stad heel mooi.", hi: "हाँ, मुझे शहर बहुत सुंदर लगता है।"},
      {who: "them", nl: "Het centrum is klein maar gezellig.", hi: "शहर केंद्र छोटा है लेकिन आरामदायक है।"},
      {who: "you", nl: "Echt waar, en het weer is vandaag goed.", hi: "सच में, और आज मौसम अच्छा है।"},
      {who: "them", nl: "Ja, gelukkig regent het niet.", hi: "हाँ, अच्छा है कि बारिश नहीं हो रही।"},
      {who: "you", nl: "Wat raad je hier aan?", hi: "तुम यहाँ क्या सुझाते हो?"},
      {who: "them", nl: "Bezoek het museum en wandel langs de kerk.", hi: "संग्रहालय देखो और चर्च के पास टहलो।"},
      {who: "you", nl: "Dat klinkt goed, dank je.", hi: "यह अच्छा लगता है, धन्यवाद।"},
      {who: "them", nl: "Graag gedaan, veel plezier!", hi: "आपका स्वागत है, खूब मज़े करो!"},
    ],
  },
];