// course-it-sw.js
// Source: Italian | Target: Swahili
const COURSE_DATA = {
  src: 'it',
  tgt: 'sw',
  srcName: 'Italian',
  tgtName: 'Swahili',
  srcFlag: '🇮🇹',
  tgtFlag: '🇰🇪',
  days: [
    {
      day: 1,
      title: `Saluti e prime parole`,
      titleNative: `Salamu na maneno ya kwanza`,
      focus: `Inizi a parlare appena arrivi a Dar es Salaam, salutando in modo semplice e rispettoso. Impari le parole essenziali per aprire una conversazione.`,
      grammar: `In swahili i saluti sono molto importanti e spesso precedono qualsiasi richiesta. “Habari?” significa letteralmente “notizie?”, ma si usa come “come va?”. La risposta più comune e semplice è “Nzuri”, cioè “bene”.`,
      vocab: [
        {tgt:`jambo`,src:`ciao`,pron:`[dʒàm-bo]`},
        {tgt:`habari`,src:`notizie, come va`,pron:`[ha-bà-ri]`},
        {tgt:`nzuri`,src:`bene`,pron:`[n-zù-ri]`},
        {tgt:`asante`,src:`grazie`,pron:`[a-sàn-te]`},
        {tgt:`tafadhali`,src:`per favore`,pron:`[ta-fa-dhà-li]`},
        {tgt:`samahani`,src:`mi scusi`,pron:`[sa-ma-hà-ni]`},
        {tgt:`ndiyo`,src:`sì`,pron:`[n-dì-yo]`},
        {tgt:`hapana`,src:`no`,pron:`[ha-pà-na]`},
        {tgt:`karibu`,src:`benvenuto, prego`,pron:`[ka-rì-bu]`},
        {tgt:`kwaheri`,src:`arrivederci`,pron:`[kwa-hè-ri]`},
      ],
      phrases: [
        {tgt:`Jambo.`,src:`Ciao.`,pron:`[dʒàm-bo]`},
        {tgt:`Habari?`,src:`Come va?`,pron:`[ha-bà-ri]`},
        {tgt:`Nzuri, asante.`,src:`Bene, grazie.`,pron:`[n-zù-ri a-sàn-te]`},
        {tgt:`Tafadhali.`,src:`Per favore.`,pron:`[ta-fa-dhà-li]`},
        {tgt:`Samahani.`,src:`Mi scusi.`,pron:`[sa-ma-hà-ni]`},
        {tgt:`Kwaheri.`,src:`Arrivederci.`,pron:`[kwa-hè-ri]`},
      ],
      conversation: [
      ],
    },
    {
      day: 2,
      title: `Presentarsi`,
      titleNative: `Kujitambulisha`,
      focus: `A Nairobi o Zanzibar, presentarti chiaramente aiuta in hotel, tour e incontri informali. Oggi impari nome, provenienza e formule cortesi.`,
      grammar: `“Ni” significa “è/sono/sei” e si usa in frasi semplici di identità. “Mimi ni Mtaliano” vuol dire “io sono italiano”. Spesso “mimi” può essere omesso, ma all’inizio è utile per chiarezza.`,
      vocab: [
        {tgt:`jina`,src:`nome`,pron:`[dʒì-na]`},
        {tgt:`naitwa`,src:`mi chiamo`,pron:`[na-ì-twa]`},
        {tgt:`wewe`,src:`tu`,pron:`[wè-we]`},
        {tgt:`mimi`,src:`io`,pron:`[mì-mi]`},
        {tgt:`Italia`,src:`Italia`,pron:`[i-tà-li-a]`},
        {tgt:`Mtaliano`,src:`italiano`,pron:`[m-ta-li-à-no]`},
        {tgt:`rafiki`,src:`amico`,pron:`[ra-fì-ki]`},
        {tgt:`kukutana`,src:`incontrare`,pron:`[ku-ku-tà-na]`},
        {tgt:`furaha`,src:`piacere, gioia`,pron:`[fu-rà-ha]`},
        {tgt:`sana`,src:`molto`,pron:`[sà-na]`},
      ],
      phrases: [
        {tgt:`Naitwa Marco.`,src:`Mi chiamo Marco.`,pron:`[na-ì-twa màr-ko]`},
        {tgt:`Jina lako nani?`,src:`Come ti chiami?`,pron:`[dʒì-na là-ko nà-ni]`},
        {tgt:`Mimi ni Mtaliano.`,src:`Sono italiano.`,pron:`[mì-mi ni m-ta-li-à-no]`},
        {tgt:`Ninatoka Italia.`,src:`Vengo dall’Italia.`,pron:`[ni-na-tò-ka i-tà-li-a]`},
        {tgt:`Nimefurahi kukutana nawe.`,src:`Piacere di conoscerti.`,pron:`[ni-me-fu-rà-hi ku-ku-tà-na nà-we]`},
        {tgt:`Wewe ni nani?`,src:`Chi sei tu?`,pron:`[wè-we ni nà-ni]`},
      ],
      conversation: [
      ],
    },
    {
      day: 3,
      title: `Cortesia quotidiana`,
      titleNative: `Heshima ya kila siku`,
      focus: `Nei mercati, nei taxi e nei piccoli negozi di Mombasa, la cortesia rende tutto più facile. Impari parole per ringraziare, scusarti e rispondere educatamente.`,
      grammar: `“Sana” intensifica il significato: “asante” è grazie, “asante sana” è grazie mille. “Kidogo” significa “un po’” o “poco” ed è molto utile quando non capisci tutto. “Subiri kidogo” è una richiesta cortese e pratica.`,
      vocab: [
        {tgt:`pole`,src:`mi dispiace, piano`,pron:`[pò-le]`},
        {tgt:`sawa`,src:`va bene`,pron:`[sà-wa]`},
        {tgt:`shukrani`,src:`ringraziamenti`,pron:`[ʃu-krà-ni]`},
        {tgt:`tafadhali`,src:`per favore`,pron:`[ta-fa-dhà-li]`},
        {tgt:`samahani`,src:`scusi`,pron:`[sa-ma-hà-ni]`},
        {tgt:`karibu`,src:`prego`,pron:`[ka-rì-bu]`},
        {tgt:`haina shida`,src:`nessun problema`,pron:`[hà-i-na ʃì-da]`},
        {tgt:`subiri`,src:`aspetta`,pron:`[su-bì-ri]`},
        {tgt:`kidogo`,src:`un po’`,pron:`[ki-dò-go]`},
        {tgt:`sijui`,src:`non so`,pron:`[si-dʒù-i]`},
      ],
      phrases: [
        {tgt:`Asante sana.`,src:`Grazie mille.`,pron:`[a-sàn-te sà-na]`},
        {tgt:`Karibu sana.`,src:`Prego, benvenuto.`,pron:`[ka-rì-bu sà-na]`},
        {tgt:`Pole sana.`,src:`Mi dispiace molto.`,pron:`[pò-le sà-na]`},
        {tgt:`Haina shida.`,src:`Nessun problema.`,pron:`[hà-i-na ʃì-da]`},
        {tgt:`Subiri kidogo.`,src:`Aspetta un momento.`,pron:`[su-bì-ri ki-dò-go]`},
        {tgt:`Sawa, asante.`,src:`Va bene, grazie.`,pron:`[sà-wa a-sàn-te]`},
      ],
      conversation: [
      ],
    },
    {
      day: 4,
      title: `Numeri da 1 a 20`,
      titleNative: `Namba moja hadi ishirini`,
      focus: `I numeri servono per pagare, prendere autobus e capire prezzi a Stone Town. Oggi impari i numeri più usati dal viaggiatore.`,
      grammar: `I numeri swahili spesso seguono il nome: “tiketi moja” significa “un biglietto”. Per chiedere un prezzo, la formula pratica è “Bei ni ngapi?”. Nei mercati sentirai spesso numeri mescolati a parole inglesi o locali.`,
      vocab: [
        {tgt:`moja`,src:`uno`,pron:`[mò-dʒa]`},
        {tgt:`mbili`,src:`due`,pron:`[m-bì-li]`},
        {tgt:`tatu`,src:`tre`,pron:`[tà-tu]`},
        {tgt:`nne`,src:`quattro`,pron:`[n-nè]`},
        {tgt:`tano`,src:`cinque`,pron:`[tà-no]`},
        {tgt:`sita`,src:`sei`,pron:`[sì-ta]`},
        {tgt:`saba`,src:`sette`,pron:`[sà-ba]`},
        {tgt:`nane`,src:`otto`,pron:`[nà-ne]`},
        {tgt:`tisa`,src:`nove`,pron:`[tì-sa]`},
        {tgt:`kumi`,src:`dieci`,pron:`[kù-mi]`},
      ],
      phrases: [
        {tgt:`Moja, tafadhali.`,src:`Uno, per favore.`,pron:`[mò-dʒa ta-fa-dhà-li]`},
        {tgt:`Nataka mbili.`,src:`Voglio due.`,pron:`[na-tà-ka m-bì-li]`},
        {tgt:`Ni shilingi kumi.`,src:`Sono dieci scellini.`,pron:`[ni ʃi-lìn-gi kù-mi]`},
        {tgt:`Nambari yangu ni tano.`,src:`Il mio numero è cinque.`,pron:`[nam-bà-ri yà-ngu ni tà-no]`},
        {tgt:`Tiketi moja, tafadhali.`,src:`Un biglietto, per favore.`,pron:`[ti-kè-ti mò-dʒa ta-fa-dhà-li]`},
        {tgt:`Bei ni ngapi?`,src:`Quanto costa?`,pron:`[bè-i ni ŋ-gà-pi]`},
      ],
      conversation: [
      ],
    },
    {
      day: 5,
      title: `Frasi essenziali per sopravvivere`,
      titleNative: `Sentensi muhimu za kusafiri`,
      focus: `Quando sei appena arrivato in Tanzania o Kenya, poche frasi possono risolvere molte situazioni. Oggi impari a dire cosa vuoi, cosa non capisci e cosa ti serve.`,
      grammar: `Il prefisso “na-” indica spesso il presente: “nataka” significa “voglio”, “nahitaji” significa “ho bisogno”. Non serve tradurre ogni parola italiana: memorizza l’intera frase come blocco pratico. “Wapi?” significa “dove?”.`,
      vocab: [
        {tgt:`nataka`,src:`voglio`,pron:`[na-tà-ka]`},
        {tgt:`nahitaji`,src:`ho bisogno`,pron:`[na-hi-tà-dʒi]`},
        {tgt:`sielewi`,src:`non capisco`,pron:`[si-e-lè-wi]`},
        {tgt:`naelewa`,src:`capisco`,pron:`[na-e-lè-wa]`},
        {tgt:`polepole`,src:`piano piano`,pron:`[pò-le pò-le]`},
        {tgt:`haraka`,src:`veloce`,pron:`[ha-rà-ka]`},
        {tgt:`msaada`,src:`aiuto`,pron:`[m-sà-a-da]`},
        {tgt:`maji`,src:`acqua`,pron:`[mà-dʒi]`},
        {tgt:`chakula`,src:`cibo`,pron:`[tʃa-kù-la]`},
        {tgt:`choo`,src:`bagno`,pron:`[tʃò-o]`},
      ],
      phrases: [
        {tgt:`Sielewi.`,src:`Non capisco.`,pron:`[si-e-lè-wi]`},
        {tgt:`Naelewa kidogo.`,src:`Capisco un po’.`,pron:`[na-e-lè-wa ki-dò-go]`},
        {tgt:`Nahitaji msaada.`,src:`Ho bisogno di aiuto.`,pron:`[na-hi-tà-dʒi m-sà-a-da]`},
        {tgt:`Nataka maji.`,src:`Voglio acqua.`,pron:`[na-tà-ka mà-dʒi]`},
        {tgt:`Choo kiko wapi?`,src:`Dov’è il bagno?`,pron:`[tʃò-o kì-ko wà-pi]`},
        {tgt:`Sema polepole, tafadhali.`,src:`Parla lentamente, per favore.`,pron:`[sè-ma pò-le pò-le ta-fa-dhà-li]`},
      ],
      conversation: [
      ],
    },
    {
      day: 6,
      title: `In aeroporto`,
      titleNative: `Uwanja wa ndege`,
      focus: `All’aeroporto di Dar es Salaam o Nairobi devi seguire indicazioni, ritirare bagagli e trovare un taxi. Oggi impari parole utili per l’arrivo.`,
      grammar: `“Yangu” significa “mio/mia/miei” ed è molto utile con oggetti personali: “pasipoti yangu”, “mizigo yangu”. “Iko wapi?” si usa per chiedere dove si trova qualcosa. In swahili la posizione è spesso espressa con “iko”, cioè “si trova”.`,
      vocab: [
        {tgt:`uwanja wa ndege`,src:`aeroporto`,pron:`[u-wàn-dʒa wa ndè-ge]`},
        {tgt:`pasipoti`,src:`passaporto`,pron:`[pa-si-pò-ti]`},
        {tgt:`mizigo`,src:`bagagli`,pron:`[mi-zì-go]`},
        {tgt:`tiketi`,src:`biglietto`,pron:`[ti-kè-ti]`},
        {tgt:`ndege`,src:`aereo`,pron:`[ndè-ge]`},
        {tgt:`kuwasili`,src:`arrivo`,pron:`[ku-wa-sì-li]`},
        {tgt:`kuondoka`,src:`partenza`,pron:`[ku-on-dò-ka]`},
        {tgt:`forodha`,src:`dogana`,pron:`[fo-rò-dha]`},
        {tgt:`dereva`,src:`autista`,pron:`[de-rè-va]`},
        {tgt:`teksi`,src:`taxi`,pron:`[tèk-si]`},
      ],
      phrases: [
        {tgt:`Pasipoti yangu iko hapa.`,src:`Il mio passaporto è qui.`,pron:`[pa-si-pò-ti yà-ngu ì-ko hà-pa]`},
        {tgt:`Mizigo yangu iko wapi?`,src:`Dove sono i miei bagagli?`,pron:`[mi-zì-go yà-ngu ì-ko wà-pi]`},
        {tgt:`Nahitaji teksi.`,src:`Ho bisogno di un taxi.`,pron:`[na-hi-tà-dʒi tèk-si]`},
        {tgt:`Ninatoka Italia.`,src:`Vengo dall’Italia.`,pron:`[ni-na-tò-ka i-tà-li-a]`},
        {tgt:`Nina tiketi.`,src:`Ho un biglietto.`,pron:`[nì-na ti-kè-ti]`},
        {tgt:`Hoteli iko wapi?`,src:`Dov’è l’hotel?`,pron:`[ho-tè-li ì-ko wà-pi]`},
      ],
      conversation: [
      ],
    },
    {
      day: 7,
      title: `Taxi e prime destinazioni`,
      titleNative: `Teksi na maeneo ya kwanza`,
      focus: `Appena fuori dall’aeroporto o dal porto, devi spiegare dove andare e chiedere il prezzo. Oggi ti prepari per una corsa in taxi.`,
      grammar: `“Nataka kwenda...” significa “voglio andare...”. Per dire “a/in un luogo”, spesso il swahili aggiunge “-ni”: “hotelini” significa “all’hotel”, “sokoni” significa “al mercato”. È una forma molto comune nelle indicazioni.`,
      vocab: [
        {tgt:`teksi`,src:`taxi`,pron:`[tèk-si]`},
        {tgt:`bei`,src:`prezzo`,pron:`[bè-i]`},
        {tgt:`ghali`,src:`caro`,pron:`[ghà-li]`},
        {tgt:`nafuu`,src:`economico`,pron:`[na-fù-u]`},
        {tgt:`hoteli`,src:`hotel`,pron:`[ho-tè-li]`},
        {tgt:`soko`,src:`mercato`,pron:`[sò-ko]`},
        {tgt:`bandari`,src:`porto`,pron:`[ban-dà-ri]`},
        {tgt:`kituo`,src:`stazione, fermata`,pron:`[ki-tù-o]`},
        {tgt:`hapa`,src:`qui`,pron:`[hà-pa]`},
        {tgt:`pale`,src:`lì`,pron:`[pà-le]`},
      ],
      phrases: [
        {tgt:`Nataka kwenda hotelini.`,src:`Voglio andare in hotel.`,pron:`[na-tà-ka kwè-nda ho-te-lì-ni]`},
        {tgt:`Bei ni ngapi?`,src:`Quanto costa?`,pron:`[bè-i ni ŋ-gà-pi]`},
        {tgt:`Ni ghali sana.`,src:`È molto caro.`,pron:`[ni ghà-li sà-na]`},
        {tgt:`Unaweza kunipeleka sokoni?`,src:`Puoi portarmi al mercato?`,pron:`[u-na-wè-za ku-ni-pe-lè-ka so-kò-ni]`},
        {tgt:`Simama hapa, tafadhali.`,src:`Fermati qui, per favore.`,pron:`[si-mà-ma hà-pa ta-fa-dhà-li]`},
        {tgt:`Ninahitaji risiti.`,src:`Ho bisogno di una ricevuta.`,pron:`[ni-na-hi-tà-dʒi ri-sì-ti]`},
      ],
      conversation: [
      ],
    },
    {
      day: 8,
      title: `In hotel`,
      titleNative: `Hotelini`,
      focus: `Al check-in a Zanzibar o Arusha devi confermare la prenotazione e chiedere servizi. Oggi impari frasi da reception.`,
      grammar: `“Changu” significa “mia/mio” per parole come “chumba”. “Nitakaa” usa “nita-”, un segnale del futuro: “resterò”. La parola “saa” indica l’ora, ma anche “orologio” in alcuni contesti.`,
      vocab: [
        {tgt:`chumba`,src:`camera`,pron:`[tʃù-mba]`},
        {tgt:`ufunguo`,src:`chiave`,pron:`[u-fùn-gu-o]`},
        {tgt:`mapokezi`,src:`reception`,pron:`[ma-po-kè-zi]`},
        {tgt:`kitanda`,src:`letto`,pron:`[ki-tàn-da]`},
        {tgt:`bafu`,src:`bagno`,pron:`[bà-fu]`},
        {tgt:`intaneti`,src:`internet`,pron:`[in-ta-nè-ti]`},
        {tgt:`wi-fi`,src:`wi-fi`,pron:`[wài-fai]`},
        {tgt:`usiku`,src:`notte`,pron:`[u-sì-ku]`},
        {tgt:`leo`,src:`oggi`,pron:`[lè-o]`},
        {tgt:`kesho`,src:`domani`,pron:`[kè-ʃo]`},
      ],
      phrases: [
        {tgt:`Nina nafasi ya chumba.`,src:`Ho una prenotazione per una camera.`,pron:`[nì-na na-fà-si ya tʃù-mba]`},
        {tgt:`Chumba changu kiko wapi?`,src:`Dov’è la mia camera?`,pron:`[tʃù-mba tʃà-ngu kì-ko wà-pi]`},
        {tgt:`Wi-fi iko wapi?`,src:`Dov’è il wi-fi?`,pron:`[wài-fai ì-ko wà-pi]`},
        {tgt:`Nahitaji ufunguo.`,src:`Ho bisogno della chiave.`,pron:`[na-hi-tà-dʒi u-fùn-gu-o]`},
        {tgt:`Nitakaa usiku mbili.`,src:`Resterò due notti.`,pron:`[ni-ta-kà-a u-sì-ku m-bì-li]`},
        {tgt:`Kiamsha kinywa ni saa ngapi?`,src:`A che ora è la colazione?`,pron:`[ki-àm-ʃa kì-nwa ni sà-a ŋ-gà-pi]`},
      ],
      conversation: [
      ],
    },
    {
      day: 9,
      title: `Cibo e bevande`,
      titleNative: `Chakula na vinywaji`,
      focus: `In un caffè di Stone Town o in un chiosco di Dar es Salaam, devi ordinare in modo semplice. Oggi impari cibo, acqua, tè e richieste base.`,
      grammar: `“Na” significa “e” ma anche “con”: “wali na nyama” è “riso con carne”. “Bila” significa “senza” ed è molto utile per allergie o preferenze. “Gani?” significa “quale/che tipo?”.`,
      vocab: [
        {tgt:`chakula`,src:`cibo`,pron:`[tʃa-kù-la]`},
        {tgt:`kinywaji`,src:`bevanda`,pron:`[ki-nwà-dʒi]`},
        {tgt:`maji`,src:`acqua`,pron:`[mà-dʒi]`},
        {tgt:`chai`,src:`tè`,pron:`[tʃài]`},
        {tgt:`kahawa`,src:`caffè`,pron:`[ka-hà-wa]`},
        {tgt:`sukari`,src:`zucchero`,pron:`[su-kà-ri]`},
        {tgt:`maziwa`,src:`latte`,pron:`[ma-zì-wa]`},
        {tgt:`mkate`,src:`pane`,pron:`[m-kà-te]`},
        {tgt:`wali`,src:`riso`,pron:`[wà-li]`},
        {tgt:`nyama`,src:`carne`,pron:`[ɲà-ma]`},
      ],
      phrases: [
        {tgt:`Nataka chai.`,src:`Voglio un tè.`,pron:`[na-tà-ka tʃài]`},
        {tgt:`Nataka kahawa bila sukari.`,src:`Voglio caffè senza zucchero.`,pron:`[na-tà-ka ka-hà-wa bì-la su-kà-ri]`},
        {tgt:`Maji ya chupa, tafadhali.`,src:`Acqua in bottiglia, per favore.`,pron:`[mà-dʒi ya tʃù-pa ta-fa-dhà-li]`},
        {tgt:`Una chakula gani?`,src:`Che cibo avete?`,pron:`[ù-na tʃa-kù-la gà-ni]`},
        {tgt:`Nataka wali na nyama.`,src:`Voglio riso con carne.`,pron:`[na-tà-ka wà-li na ɲà-ma]`},
        {tgt:`Ni tamu sana.`,src:`È molto buono.`,pron:`[ni tà-mu sà-na]`},
      ],
      conversation: [
      ],
    },
    {
      day: 10,
      title: `Al ristorante`,
      titleNative: `Mkahawani`,
      focus: `In un ristorante a Mombasa o Lamu, impari a chiedere il menù, ordinare e pagare. Usi frasi naturali e cortesi.`,
      grammar: `“Naomba” è una forma molto educata per dire “chiedo/vorrei”. È spesso più gentile di “nataka”, che significa “voglio”. Per viaggiare, “Naomba...” è una frase fondamentale nei ristoranti e negli hotel.`,
      vocab: [
        {tgt:`menyu`,src:`menù`,pron:`[mè-nyu]`},
        {tgt:`sahani`,src:`piatto`,pron:`[sa-hà-ni]`},
        {tgt:`kijiko`,src:`cucchiaio`,pron:`[ki-dʒì-ko]`},
        {tgt:`uma`,src:`forchetta`,pron:`[ù-ma]`},
        {tgt:`kisu`,src:`coltello`,pron:`[kì-su]`},
        {tgt:`bili`,src:`conto`,pron:`[bì-li]`},
        {tgt:`ladha`,src:`sapore`,pron:`[là-dha]`},
        {tgt:`tamu`,src:`buono, dolce`,pron:`[tà-mu]`},
        {tgt:`moto`,src:`caldo`,pron:`[mò-to]`},
        {tgt:`baridi`,src:`freddo`,pron:`[ba-rì-di]`},
      ],
      phrases: [
        {tgt:`Naomba menyu, tafadhali.`,src:`Vorrei il menù, per favore.`,pron:`[na-òm-ba mè-nyu ta-fa-dhà-li]`},
        {tgt:`Nataka sahani hii.`,src:`Voglio questo piatto.`,pron:`[na-tà-ka sa-hà-ni hì-i]`},
        {tgt:`Chakula hiki ni moto.`,src:`Questo cibo è caldo.`,pron:`[tʃa-kù-la hì-ki ni mò-to]`},
        {tgt:`Naomba bili.`,src:`Vorrei il conto.`,pron:`[na-òm-ba bì-li]`},
        {tgt:`Ninalipa kwa kadi.`,src:`Pago con carta.`,pron:`[ni-na-lì-pa kwa kà-di]`},
        {tgt:`Ninalipa kwa pesa taslimu.`,src:`Pago in contanti.`,pron:`[ni-na-lì-pa kwa pè-sa tas-lì-mu]`},
      ],
      conversation: [
      ],
    },
    {
      day: 11,
      title: `Gusti, allergie e preferenze`,
      titleNative: `Ladha, mzio na mapendeleo`,
      focus: `Quando mangi fuori, devi spiegare cosa puoi o non puoi mangiare. Oggi impari a parlare di allergie, vegetariano e piccante.`,
      grammar: `Per dire “non mangio”, usa “sili”. È una forma negativa molto pratica: “Sili nyama” significa “non mangio carne”. “Kuna?” significa “c’è/ci sono?” ed è utile per chiedere ingredienti.`,
      vocab: [
        {tgt:`mzio`,src:`allergia`,pron:`[m-zì-o]`},
        {tgt:`samaki`,src:`pesce`,pron:`[sa-mà-ki]`},
        {tgt:`mayai`,src:`uova`,pron:`[ma-yài]`},
        {tgt:`karanga`,src:`arachidi`,pron:`[ka-rà-nga]`},
        {tgt:`mboga`,src:`verdure`,pron:`[m-bò-ga]`},
        {tgt:`pilipili`,src:`peperoncino`,pron:`[pi-li-pì-li]`},
        {tgt:`chumvi`,src:`sale`,pron:`[tʃù-mvi]`},
        {tgt:`bila`,src:`senza`,pron:`[bì-la]`},
        {tgt:`kidogo`,src:`poco`,pron:`[ki-dò-go]`},
        {tgt:`sana`,src:`molto`,pron:`[sà-na]`},
      ],
      phrases: [
        {tgt:`Nina mzio wa karanga.`,src:`Sono allergico alle arachidi.`,pron:`[nì-na m-zì-o wa ka-rà-nga]`},
        {tgt:`Bila pilipili, tafadhali.`,src:`Senza peperoncino, per favore.`,pron:`[bì-la pi-li-pì-li ta-fa-dhà-li]`},
        {tgt:`Pilipili kidogo tu.`,src:`Solo poco peperoncino.`,pron:`[pi-li-pì-li ki-dò-go tu]`},
        {tgt:`Sili nyama.`,src:`Non mangio carne.`,pron:`[sì-li ɲà-ma]`},
        {tgt:`Ninakula mboga.`,src:`Mangio verdure.`,pron:`[ni-na-kù-la m-bò-ga]`},
        {tgt:`Kuna mayai?`,src:`Ci sono uova?`,pron:`[kù-na ma-yài]`},
      ],
      conversation: [
      ],
    },
    {
      day: 12,
      title: `Mercato e acquisti`,
      titleNative: `Sokoni na manunuzi`,
      focus: `Nei mercati di Kariakoo o Stone Town devi chiedere prezzi, quantità e colori. Oggi impari a comprare in modo semplice.`,
      grammar: `“Hii” significa “questo” per molti oggetti comuni, ma in swahili i dimostrativi cambiano secondo la classe del nome. Per viaggiare puoi usare “hii” indicando l’oggetto: il contesto aiuta. “Nyingine” significa “altro”.`,
      vocab: [
        {tgt:`soko`,src:`mercato`,pron:`[sò-ko]`},
        {tgt:`duka`,src:`negozio`,pron:`[dù-ka]`},
        {tgt:`bei`,src:`prezzo`,pron:`[bè-i]`},
        {tgt:`pesa`,src:`soldi`,pron:`[pè-sa]`},
        {tgt:`nguo`,src:`vestiti`,pron:`[ŋ-gù-o]`},
        {tgt:`mfuko`,src:`borsa, sacchetto`,pron:`[m-fù-ko]`},
        {tgt:`rangi`,src:`colore`,pron:`[rà-ngi]`},
        {tgt:`kubwa`,src:`grande`,pron:`[kù-bwa]`},
        {tgt:`ndogo`,src:`piccolo`,pron:`[n-dò-go]`},
        {tgt:`hii`,src:`questo`,pron:`[hì-i]`},
      ],
      phrases: [
        {tgt:`Bei ya hii ni ngapi?`,src:`Quanto costa questo?`,pron:`[bè-i ya hì-i ni ŋ-gà-pi]`},
        {tgt:`Nataka hii.`,src:`Voglio questo.`,pron:`[na-tà-ka hì-i]`},
        {tgt:`Una rangi nyingine?`,src:`Hai un altro colore?`,pron:`[ù-na rà-ngi nyì-ngi-ne]`},
        {tgt:`Ni kubwa sana.`,src:`È troppo grande.`,pron:`[ni kù-bwa sà-na]`},
        {tgt:`Ni ndogo sana.`,src:`È troppo piccolo.`,pron:`[ni n-dò-go sà-na]`},
        {tgt:`Naomba mfuko.`,src:`Vorrei un sacchetto.`,pron:`[na-òm-ba m-fù-ko]`},
      ],
      conversation: [
      ],
    },
    {
      day: 13,
      title: `Contrattare con rispetto`,
      titleNative: `Kujadiliana kwa heshima`,
      focus: `Nei mercati turistici la contrattazione può essere normale, ma va fatta con sorriso e rispetto. Oggi impari frasi per negoziare senza sembrare scortese.`,
      grammar: `“Nitachukua” significa “lo prenderò” o “lo prendo” nel contesto dell’acquisto. “Labda baadaye” è una frase gentile per rifiutare senza chiudere bruscamente. La cortesia è più importante dello sconto.`,
      vocab: [
        {tgt:`ghali`,src:`caro`,pron:`[ghà-li]`},
        {tgt:`nafuu`,src:`economico`,pron:`[na-fù-u]`},
        {tgt:`punguza`,src:`abbassa, riduci`,pron:`[pu-ngù-za]`},
        {tgt:`tafadhali`,src:`per favore`,pron:`[ta-fa-dhà-li]`},
        {tgt:`mwisho`,src:`ultimo, finale`,pron:`[mwì-ʃo]`},
        {tgt:`sawa`,src:`va bene`,pron:`[sà-wa]`},
        {tgt:`nunua`,src:`comprare`,pron:`[nu-nù-a]`},
        {tgt:`uza`,src:`vendere`,pron:`[ù-za]`},
        {tgt:`pesa`,src:`soldi`,pron:`[pè-sa]`},
        {tgt:`kidogo`,src:`un po’`,pron:`[ki-dò-go]`},
      ],
      phrases: [
        {tgt:`Ni ghali kidogo.`,src:`È un po’ caro.`,pron:`[ni ghà-li ki-dò-go]`},
        {tgt:`Punguza bei, tafadhali.`,src:`Abbassi il prezzo, per favore.`,pron:`[pu-ngù-za bè-i ta-fa-dhà-li]`},
        {tgt:`Bei ya mwisho ni ngapi?`,src:`Qual è il prezzo finale?`,pron:`[bè-i ya mwì-ʃo ni ŋ-gà-pi]`},
        {tgt:`Nina pesa kidogo.`,src:`Ho pochi soldi.`,pron:`[nì-na pè-sa ki-dò-go]`},
        {tgt:`Sawa, nitachukua.`,src:`Va bene, lo prendo.`,pron:`[sà-wa ni-ta-tʃù-ku-a]`},
        {tgt:`Asante, labda baadaye.`,src:`Grazie, forse più tardi.`,pron:`[a-sàn-te làb-da ba-a-dà-ye]`},
      ],
      conversation: [
      ],
    },
    {
      day: 14,
      title: `Direzioni in città`,
      titleNative: `Maelekezo mjini`,
      focus: `Camminando a Kigali, Dar es Salaam o Mombasa, devi chiedere dove andare. Oggi impari destra, sinistra, avanti e vicino.`,
      grammar: `Gli imperativi semplici sono spesso brevi: “nenda” significa “vai”, “geuka” significa “gira”. “Iko wapi?” resta una delle forme più utili per chiedere luoghi. Quando non capisci, puoi mostrare una mappa e dire “hapa?”.`,
      vocab: [
        {tgt:`wapi`,src:`dove`,pron:`[wà-pi]`},
        {tgt:`kulia`,src:`destra`,pron:`[ku-lì-a]`},
        {tgt:`kushoto`,src:`sinistra`,pron:`[ku-ʃò-to]`},
        {tgt:`moja kwa moja`,src:`dritto`,pron:`[mò-dʒa kwa mò-dʒa]`},
        {tgt:`karibu`,src:`vicino`,pron:`[ka-rì-bu]`},
        {tgt:`mbali`,src:`lontano`,pron:`[m-bà-li]`},
        {tgt:`barabara`,src:`strada`,pron:`[ba-ra-bà-ra]`},
        {tgt:`kona`,src:`angolo`,pron:`[kò-na]`},
        {tgt:`ramani`,src:`mappa`,pron:`[ra-mà-ni]`},
        {tgt:`hapa`,src:`qui`,pron:`[hà-pa]`},
      ],
      phrases: [
        {tgt:`Benki iko wapi?`,src:`Dov’è la banca?`,pron:`[bèn-ki ì-ko wà-pi]`},
        {tgt:`Nenda moja kwa moja.`,src:`Vai dritto.`,pron:`[nè-nda mò-dʒa kwa mò-dʒa]`},
        {tgt:`Geuka kulia.`,src:`Gira a destra.`,pron:`[gè-u-ka ku-lì-a]`},
        {tgt:`Geuka kushoto.`,src:`Gira a sinistra.`,pron:`[gè-u-ka ku-ʃò-to]`},
        {tgt:`Ni karibu?`,src:`È vicino?`,pron:`[ni ka-rì-bu]`},
        {tgt:`Ni mbali sana?`,src:`È molto lontano?`,pron:`[ni m-bà-li sà-na]`},
      ],
      conversation: [
      ],
    },
    {
      day: 15,
      title: `Trasporti pubblici`,
      titleNative: `Usafiri wa umma`,
      focus: `Per muoverti tra quartieri o città, puoi usare autobus, dala dala o traghetti. Oggi impari parole pratiche per biglietti e fermate.`,
      grammar: `I verbi al presente spesso hanno “-na-”: “linaenda” significa “va”, “ninashuka” significa “scendo”. Le classi dei nomi cambiano i prefissi, ma all’inizio concentrati sulle frasi intere. Nei mezzi pubblici, parla in modo chiaro e breve.`,
      vocab: [
        {tgt:`basi`,src:`autobus`,pron:`[bà-si]`},
        {tgt:`dala dala`,src:`minibus locale`,pron:`[dà-la dà-la]`},
        {tgt:`kituo`,src:`fermata, stazione`,pron:`[ki-tù-o]`},
        {tgt:`tiketi`,src:`biglietto`,pron:`[ti-kè-ti]`},
        {tgt:`nauli`,src:`tariffa`,pron:`[nà-u-li]`},
        {tgt:`treni`,src:`treno`,pron:`[trè-ni]`},
        {tgt:`feri`,src:`traghetto`,pron:`[fè-ri]`},
        {tgt:`abiria`,src:`passeggero`,pron:`[a-bì-ri-a]`},
        {tgt:`safari`,src:`viaggio`,pron:`[sa-fà-ri]`},
        {tgt:`shuka`,src:`scendi`,pron:`[ʃù-ka]`},
      ],
      phrases: [
        {tgt:`Kituo kiko wapi?`,src:`Dov’è la fermata?`,pron:`[ki-tù-o kì-ko wà-pi]`},
        {tgt:`Nauli ni ngapi?`,src:`Quanto costa la tariffa?`,pron:`[nà-u-li ni ŋ-gà-pi]`},
        {tgt:`Nataka tiketi moja.`,src:`Voglio un biglietto.`,pron:`[na-tà-ka ti-kè-ti mò-dʒa]`},
        {tgt:`Basi linaenda wapi?`,src:`Dove va l’autobus?`,pron:`[bà-si li-na-è-nda wà-pi]`},
        {tgt:`Ninashuka hapa.`,src:`Scendo qui.`,pron:`[ni-na-ʃù-ka hà-pa]`},
        {tgt:`Feri inaondoka saa ngapi?`,src:`A che ora parte il traghetto?`,pron:`[fè-ri i-na-on-dò-ka sà-a ŋ-gà-pi]`},
      ],
      conversation: [
      ],
    },
    {
      day: 16,
      title: `Orari e giorni`,
      titleNative: `Saa na siku`,
      focus: `Per tour, traghetti e colazioni devi capire ore e giorni. Oggi impari a chiedere quando qualcosa apre, parte o arriva.`,
      grammar: `“Nita-” indica il futuro per “io”, mentre “tuta-” indica il futuro per “noi”. “Nitarudi” significa “tornerò”, “tutaenda” significa “andremo”. Le parole del tempo come “leo” e “kesho” di solito stanno vicino al verbo o alla fine della frase.`,
      vocab: [
        {tgt:`saa`,src:`ora`,pron:`[sà-a]`},
        {tgt:`leo`,src:`oggi`,pron:`[lè-o]`},
        {tgt:`kesho`,src:`domani`,pron:`[kè-ʃo]`},
        {tgt:`jana`,src:`ieri`,pron:`[dʒà-na]`},
        {tgt:`asubuhi`,src:`mattina`,pron:`[a-su-bù-hi]`},
        {tgt:`mchana`,src:`giorno, mezzogiorno`,pron:`[m-tʃà-na]`},
        {tgt:`jioni`,src:`sera`,pron:`[dʒi-ò-ni]`},
        {tgt:`usiku`,src:`notte`,pron:`[u-sì-ku]`},
        {tgt:`dakika`,src:`minuto`,pron:`[da-kì-ka]`},
        {tgt:`siku`,src:`giorno`,pron:`[sì-ku]`},
      ],
      phrases: [
        {tgt:`Ni saa ngapi?`,src:`Che ore sono?`,pron:`[ni sà-a ŋ-gà-pi]`},
        {tgt:`Inafungua saa ngapi?`,src:`A che ora apre?`,pron:`[i-na-fu-ngù-a sà-a ŋ-gà-pi]`},
        {tgt:`Inafunga saa ngapi?`,src:`A che ora chiude?`,pron:`[i-na-fù-nga sà-a ŋ-gà-pi]`},
        {tgt:`Tutaenda kesho.`,src:`Andremo domani.`,pron:`[tu-ta-è-nda kè-ʃo]`},
        {tgt:`Nitarudi jioni.`,src:`Tornerò la sera.`,pron:`[ni-ta-rù-di dʒi-ò-ni]`},
        {tgt:`Dakika tano, tafadhali.`,src:`Cinque minuti, per favore.`,pron:`[da-kì-ka tà-no ta-fa-dhà-li]`},
      ],
      conversation: [
      ],
    },
    {
      day: 17,
      title: `Spiaggia e tempo libero`,
      titleNative: `Ufukwe na burudani`,
      focus: `A Zanzibar, Diani o Lamu puoi parlare di spiaggia, mare e attività. Oggi impari frasi per relax, escursioni e sicurezza.`,
      grammar: `“Naweza...” significa “posso...”. Dopo questa forma, il verbo spesso resta all’infinito con “ku-”, come “kuogelea”. “Kupiga picha” significa letteralmente “colpire foto”, ma si usa per “fare una foto”.`,
      vocab: [
        {tgt:`ufukwe`,src:`spiaggia`,pron:`[u-fù-kwe]`},
        {tgt:`bahari`,src:`mare`,pron:`[ba-hà-ri]`},
        {tgt:`jua`,src:`sole`,pron:`[dʒù-a]`},
        {tgt:`kuogelea`,src:`nuotare`,pron:`[ku-o-ge-lè-a]`},
        {tgt:`mashua`,src:`barca`,pron:`[ma-ʃù-a]`},
        {tgt:`ziara`,src:`escursione`,pron:`[zi-à-ra]`},
        {tgt:`picha`,src:`foto`,pron:`[pì-tʃa]`},
        {tgt:`kivuli`,src:`ombra`,pron:`[ki-vù-li]`},
        {tgt:`salama`,src:`sicuro`,pron:`[sa-là-ma]`},
        {tgt:`hatari`,src:`pericolo`,pron:`[ha-tà-ri]`},
      ],
      phrases: [
        {tgt:`Ufukwe uko wapi?`,src:`Dov’è la spiaggia?`,pron:`[u-fù-kwe ù-ko wà-pi]`},
        {tgt:`Naweza kuogelea hapa?`,src:`Posso nuotare qui?`,pron:`[na-wè-za ku-o-ge-lè-a hà-pa]`},
        {tgt:`Ni salama?`,src:`È sicuro?`,pron:`[ni sa-là-ma]`},
        {tgt:`Nataka kupiga picha.`,src:`Voglio fare una foto.`,pron:`[na-tà-ka ku-pì-ga pì-tʃa]`},
        {tgt:`Kuna kivuli?`,src:`C’è ombra?`,pron:`[kù-na ki-vù-li]`},
        {tgt:`Ziara inaanza saa ngapi?`,src:`A che ora inizia l’escursione?`,pron:`[zi-à-ra i-na-àn-za sà-a ŋ-gà-pi]`},
      ],
      conversation: [
      ],
    },
    {
      day: 18,
      title: `Salute e farmacia`,
      titleNative: `Afya na duka la dawa`,
      focus: `In viaggio può capitare di cercare una farmacia o spiegare un sintomo. Oggi impari parole semplici per salute e necessità mediche.`,
      grammar: `“Nina” significa “ho” ed è essenziale per parlare di sintomi: “nina homa”, “nina maumivu”. “Ya” collega spesso due nomi: “maumivu ya kichwa” significa “dolore della testa”. In farmacia, usa frasi brevi e mostra il sintomo se necessario.`,
      vocab: [
        {tgt:`afya`,src:`salute`,pron:`[à-fya]`},
        {tgt:`duka la dawa`,src:`farmacia`,pron:`[dù-ka la dà-wa]`},
        {tgt:`dawa`,src:`medicina`,pron:`[dà-wa]`},
        {tgt:`maumivu`,src:`dolore`,pron:`[ma-u-mì-vu]`},
        {tgt:`kichwa`,src:`testa`,pron:`[kì-tʃwa]`},
        {tgt:`tumbo`,src:`stomaco`,pron:`[tù-mbo]`},
        {tgt:`homa`,src:`febbre`,pron:`[hò-ma]`},
        {tgt:`mgonjwa`,src:`malato`,pron:`[m-gòn-dʒwa]`},
        {tgt:`daktari`,src:`medico`,pron:`[dak-tà-ri]`},
        {tgt:`hospitali`,src:`ospedale`,pron:`[hos-pi-tà-li]`},
      ],
      phrases: [
        {tgt:`Duka la dawa liko wapi?`,src:`Dov’è la farmacia?`,pron:`[dù-ka la dà-wa li-ko wà-pi]`},
        {tgt:`Nina maumivu ya kichwa.`,src:`Ho mal di testa.`,pron:`[nì-na ma-u-mì-vu ya kì-tʃwa]`},
        {tgt:`Nina maumivu ya tumbo.`,src:`Ho mal di stomaco.`,pron:`[nì-na ma-u-mì-vu ya tù-mbo]`},
        {tgt:`Nina homa.`,src:`Ho la febbre.`,pron:`[nì-na hò-ma]`},
        {tgt:`Nahitaji daktari.`,src:`Ho bisogno di un medico.`,pron:`[na-hi-tà-dʒi dak-tà-ri]`},
        {tgt:`Dawa hii ni ya nini?`,src:`A cosa serve questa medicina?`,pron:`[dà-wa hì-i ni ya nì-ni]`},
      ],
      conversation: [
      ],
    },
    {
      day: 19,
      title: `Emergenze e sicurezza`,
      titleNative: `Dharura na usalama`,
      focus: `In caso di problema serio, devi chiedere aiuto in modo chiaro. Oggi impari frasi per polizia, emergenze e oggetti smarriti.`,
      grammar: `“Ni-me-” indica spesso un’azione completata: “nimepotea” significa “mi sono perso” o “sono perso”. “Imepotea” significa “è sparito” per un oggetto singolare come “simu”. In emergenza, non preoccuparti della grammatica perfetta: punta alla chiarezza.`,
      vocab: [
        {tgt:`dharura`,src:`emergenza`,pron:`[dha-rù-ra]`},
        {tgt:`msaada`,src:`aiuto`,pron:`[m-sà-a-da]`},
        {tgt:`polisi`,src:`polizia`,pron:`[po-lì-si]`},
        {tgt:`mwizi`,src:`ladro`,pron:`[mwì-zi]`},
        {tgt:`potea`,src:`perdersi`,pron:`[po-tè-a]`},
        {tgt:`simu`,src:`telefono`,pron:`[sì-mu]`},
        {tgt:`hatari`,src:`pericolo`,pron:`[ha-tà-ri]`},
        {tgt:`salama`,src:`sicuro`,pron:`[sa-là-ma]`},
        {tgt:`haraka`,src:`veloce`,pron:`[ha-rà-ka]`},
        {tgt:`nyaraka`,src:`documenti`,pron:`[ɲa-rà-ka]`},
      ],
      phrases: [
        {tgt:`Nahitaji msaada haraka.`,src:`Ho bisogno di aiuto subito.`,pron:`[na-hi-tà-dʒi m-sà-a-da ha-rà-ka]`},
        {tgt:`Piga polisi, tafadhali.`,src:`Chiami la polizia, per favore.`,pron:`[pì-ga po-lì-si ta-fa-dhà-li]`},
        {tgt:`Nimepotea.`,src:`Mi sono perso.`,pron:`[ni-me-po-tè-a]`},
        {tgt:`Simu yangu imepotea.`,src:`Il mio telefono è sparito.`,pron:`[sì-mu yà-ngu i-me-po-tè-a]`},
        {tgt:`Nyaraka zangu zimepotea.`,src:`I miei documenti sono spariti.`,pron:`[ɲa-rà-ka zà-ngu zi-me-po-tè-a]`},
        {tgt:`Hapa si salama.`,src:`Qui non è sicuro.`,pron:`[hà-pa si sa-là-ma]`},
      ],
      conversation: [
      ],
    },
    {
      day: 20,
      title: `Telefonare e internet`,
      titleNative: `Simu na intaneti`,
      focus: `Per mappe, messaggi e prenotazioni, hai bisogno di connessione. Oggi impari a chiedere SIM, dati, credito e wi-fi.`,
      grammar: `“Sina” significa “non ho”, il contrario di “nina”. È utilissimo: “sina salio” significa “non ho credito”. “Naweza...” resta la formula comoda per chiedere permesso: “Naweza kuchaji simu hapa?”.`,
      vocab: [
        {tgt:`simu`,src:`telefono`,pron:`[sì-mu]`},
        {tgt:`lain`,src:`SIM, linea`,pron:`[là-in]`},
        {tgt:`intaneti`,src:`internet`,pron:`[in-ta-nè-ti]`},
        {tgt:`wi-fi`,src:`wi-fi`,pron:`[wài-fai]`},
        {tgt:`nenosiri`,src:`password`,pron:`[ne-no-sì-ri]`},
        {tgt:`data`,src:`dati`,pron:`[dà-ta]`},
        {tgt:`salio`,src:`credito residuo`,pron:`[sa-lì-o]`},
        {tgt:`chaji`,src:`carica`,pron:`[tʃà-dʒi]`},
        {tgt:`kuchaji`,src:`caricare`,pron:`[ku-tʃà-dʒi]`},
        {tgt:`ujumbe`,src:`messaggio`,pron:`[u-dʒù-mbe]`},
      ],
      phrases: [
        {tgt:`Nahitaji lain ya simu.`,src:`Ho bisogno di una SIM.`,pron:`[na-hi-tà-dʒi là-in ya sì-mu]`},
        {tgt:`Wi-fi ina nenosiri?`,src:`Il wi-fi ha una password?`,pron:`[wài-fai i-na ne-no-sì-ri]`},
        {tgt:`Nenosiri ni nini?`,src:`Qual è la password?`,pron:`[ne-no-sì-ri ni nì-ni]`},
        {tgt:`Nataka data.`,src:`Voglio dati internet.`,pron:`[na-tà-ka dà-ta]`},
        {tgt:`Naweza kuchaji simu hapa?`,src:`Posso caricare il telefono qui?`,pron:`[na-wè-za ku-tʃà-dʒi sì-mu hà-pa]`},
        {tgt:`Sina salio.`,src:`Non ho credito.`,pron:`[sì-na sa-lì-o]`},
      ],
      conversation: [
      ],
    },
    {
      day: 21,
      title: `Descrivere persone e cose`,
      titleNative: `Kueleza watu na vitu`,
      focus: `Per ritrovare un amico, descrivere un oggetto o parlare con una guida, servono aggettivi semplici. Oggi impari grande, piccolo, nuovo, vecchio e colori.`,
      grammar: `Gli aggettivi in swahili possono cambiare prefisso secondo il nome, ma molte parole restano riconoscibili. Per il viaggiatore, frasi come “ni nzuri” e “ni mpya” funzionano bene in contesti semplici. Ascolta come i locali adattano gli aggettivi.`,
      vocab: [
        {tgt:`mtu`,src:`persona`,pron:`[m-tù]`},
        {tgt:`mrefu`,src:`alto, lungo`,pron:`[m-rè-fu]`},
        {tgt:`mfupi`,src:`basso, corto`,pron:`[m-fù-pi]`},
        {tgt:`mpya`,src:`nuovo`,pron:`[m-pyà]`},
        {tgt:`zamani`,src:`vecchio, antico`,pron:`[za-mà-ni]`},
        {tgt:`nzuri`,src:`bello, buono`,pron:`[n-zù-ri]`},
        {tgt:`mbaya`,src:`cattivo, brutto`,pron:`[m-bà-ya]`},
        {tgt:`nyeupe`,src:`bianco`,pron:`[ɲe-ù-pe]`},
        {tgt:`nyeusi`,src:`nero`,pron:`[ɲe-ù-si]`},
        {tgt:`nyekundu`,src:`rosso`,pron:`[ɲe-kùn-du]`},
      ],
      phrases: [
        {tgt:`Ni mtu mrefu.`,src:`È una persona alta.`,pron:`[ni m-tù m-rè-fu]`},
        {tgt:`Gari ni nyeupe.`,src:`La macchina è bianca.`,pron:`[gà-ri ni ɲe-ù-pe]`},
        {tgt:`Hoteli ni nzuri.`,src:`L’hotel è bello.`,pron:`[ho-tè-li ni n-zù-ri]`},
        {tgt:`Chumba ni kidogo.`,src:`La camera è piccola.`,pron:`[tʃù-mba ni ki-dò-go]`},
        {tgt:`Hii ni mpya?`,src:`Questo è nuovo?`,pron:`[hì-i ni m-pyà]`},
        {tgt:`Soko la zamani liko wapi?`,src:`Dov’è il mercato vecchio?`,pron:`[sò-ko la za-mà-ni li-ko wà-pi]`},
      ],
      conversation: [
      ],
    },
    {
      day: 22,
      title: `Parlare del tempo`,
      titleNative: `Hali ya hewa`,
      focus: `Il clima influenza safari, spiagge e traghetti. Oggi impari a parlare di sole, pioggia, caldo e freddo in modo naturale.`,
      grammar: `“Kuna” significa “c’è/ci sono” ed è molto usato per il tempo: “kuna mvua”, “kuna jua”. “Kutakuwa na...” significa “ci sarà”. Anche se la struttura sembra diversa dall’italiano, memorizzala come frase intera.`,
      vocab: [
        {tgt:`hali ya hewa`,src:`tempo atmosferico`,pron:`[hà-li ya hè-wa]`},
        {tgt:`jua`,src:`sole`,pron:`[dʒù-a]`},
        {tgt:`mvua`,src:`pioggia`,pron:`[m-vù-a]`},
        {tgt:`upepo`,src:`vento`,pron:`[u-pè-po]`},
        {tgt:`joto`,src:`caldo`,pron:`[dʒò-to]`},
        {tgt:`baridi`,src:`freddo`,pron:`[ba-rì-di]`},
        {tgt:`mawingu`,src:`nuvole`,pron:`[ma-wì-ngu]`},
        {tgt:`leo`,src:`oggi`,pron:`[lè-o]`},
        {tgt:`kesho`,src:`domani`,pron:`[kè-ʃo]`},
        {tgt:`msimu`,src:`stagione`,pron:`[m-sì-mu]`},
      ],
      phrases: [
        {tgt:`Leo kuna jua.`,src:`Oggi c’è sole.`,pron:`[lè-o kù-na dʒù-a]`},
        {tgt:`Kuna mvua.`,src:`Piove, c’è pioggia.`,pron:`[kù-na m-vù-a]`},
        {tgt:`Ni joto sana.`,src:`Fa molto caldo.`,pron:`[ni dʒò-to sà-na]`},
        {tgt:`Ni baridi kidogo.`,src:`Fa un po’ freddo.`,pron:`[ni ba-rì-di ki-dò-go]`},
        {tgt:`Kesho kutakuwa na mvua?`,src:`Domani pioverà?`,pron:`[kè-ʃo ku-ta-kù-wa na m-vù-a]`},
        {tgt:`Upepo ni mkali.`,src:`Il vento è forte.`,pron:`[u-pè-po ni m-kà-li]`},
      ],
      conversation: [
      ],
    },
    {
      day: 23,
      title: `Safari e natura`,
      titleNative: `Safari na mazingira`,
      focus: `In Tanzania o Kenya, un safari richiede parole per animali, guida e sicurezza. Oggi impari frasi per parchi, tour e osservazione.`,
      grammar: `“Kuona” significa “vedere”. Dopo “nataka”, puoi usare un verbo con “ku-”: “nataka kuona”. “Lini?” significa “quando?” ed è utile per orari, partenze e aperture.`,
      vocab: [
        {tgt:`safari`,src:`viaggio, safari`,pron:`[sa-fà-ri]`},
        {tgt:`wanyama`,src:`animali`,pron:`[wa-ɲà-ma]`},
        {tgt:`simba`,src:`leone`,pron:`[sìm-ba]`},
        {tgt:`tembo`,src:`elefante`,pron:`[tèm-bo]`},
        {tgt:`twiga`,src:`giraffa`,pron:`[twì-ga]`},
        {tgt:`kifaru`,src:`rinoceronte`,pron:`[ki-fà-ru]`},
        {tgt:`ndege`,src:`uccello, aereo`,pron:`[ndè-ge]`},
        {tgt:`mwongozo`,src:`guida`,pron:`[mw-on-gò-zo]`},
        {tgt:`hifadhi`,src:`parco, riserva`,pron:`[hi-fà-dhi]`},
        {tgt:`kamera`,src:`macchina fotografica`,pron:`[kà-me-ra]`},
      ],
      phrases: [
        {tgt:`Tunaenda safari.`,src:`Andiamo in safari.`,pron:`[tu-na-è-nda sa-fà-ri]`},
        {tgt:`Nataka kuona simba.`,src:`Voglio vedere un leone.`,pron:`[na-tà-ka ku-ò-na sìm-ba]`},
        {tgt:`Usalama ni muhimu.`,src:`La sicurezza è importante.`,pron:`[u-sa-là-ma ni mu-hì-mu]`},
        {tgt:`Naweza kupiga picha?`,src:`Posso fare una foto?`,pron:`[na-wè-za ku-pì-ga pì-tʃa]`},
        {tgt:`Mwongozo yuko wapi?`,src:`Dov’è la guida?`,pron:`[mw-on-gò-zo yu-ko wà-pi]`},
        {tgt:`Hifadhi inafunguliwa lini?`,src:`Quando apre il parco?`,pron:`[hi-fà-dhi i-na-fu-ngù-li-wa lì-ni]`},
      ],
      conversation: [
      ],
    },
    {
      day: 24,
      title: `Fare amicizia`,
      titleNative: `Kupata marafiki`,
      focus: `Durante un tour o in un caffè, puoi parlare con persone locali in modo semplice. Oggi impari domande leggere su lavoro, famiglia e interessi.`,
      grammar: `“Una-” indica spesso “tu” al presente: “unaishi” è “vivi”, “unapenda” è “ti piace”. “Napenda” significa “mi piace” o “amo”. In conversazioni informali, domande semplici e sorridenti funzionano molto bene.`,
      vocab: [
        {tgt:`rafiki`,src:`amico`,pron:`[ra-fì-ki]`},
        {tgt:`familia`,src:`famiglia`,pron:`[fa-mì-li-a]`},
        {tgt:`kazi`,src:`lavoro`,pron:`[kà-zi]`},
        {tgt:`mji`,src:`città`,pron:`[m-dʒì]`},
        {tgt:`nyumbani`,src:`a casa`,pron:`[ɲum-bà-ni]`},
        {tgt:`kupenda`,src:`amare, piacere`,pron:`[ku-pè-nda]`},
        {tgt:`muziki`,src:`musica`,pron:`[mu-zì-ki]`},
        {tgt:`mpira`,src:`calcio, palla`,pron:`[m-pì-ra]`},
        {tgt:`soma`,src:`studiare, leggere`,pron:`[sò-ma]`},
        {tgt:`ongea`,src:`parlare`,pron:`[o-ngè-a]`},
      ],
      phrases: [
        {tgt:`Unaishi wapi?`,src:`Dove vivi?`,pron:`[u-na-ì-ʃi wà-pi]`},
        {tgt:`Unafanya kazi gani?`,src:`Che lavoro fai?`,pron:`[u-na-fà-nya kà-zi gà-ni]`},
        {tgt:`Napenda muziki.`,src:`Mi piace la musica.`,pron:`[na-pè-nda mu-zì-ki]`},
        {tgt:`Unapenda mpira?`,src:`Ti piace il calcio?`,pron:`[u-na-pè-nda m-pì-ra]`},
        {tgt:`Familia yako iko hapa?`,src:`La tua famiglia è qui?`,pron:`[fa-mì-li-a yà-ko ì-ko hà-pa]`},
        {tgt:`Tunaweza kuongea kidogo?`,src:`Possiamo parlare un po’?`,pron:`[tu-na-wè-za ku-o-ngè-a ki-dò-go]`},
      ],
      conversation: [
      ],
    },
    {
      day: 25,
      title: `Inviti e programmi`,
      titleNative: `Mialiko na mipango`,
      focus: `Se conosci persone durante il viaggio, potresti organizzare un caffè, una passeggiata o un tour. Oggi impari a proporre e rispondere.`,
      grammar: `“Twende” significa “andiamo” ed è molto naturale per proporre qualcosa. “Tukutane” significa “incontriamoci”. Per rispondere con gentilezza, “labda baadaye” è utile se non vuoi accettare subito.`,
      vocab: [
        {tgt:`mpango`,src:`programma, piano`,pron:`[m-pà-ngo]`},
        {tgt:`leo`,src:`oggi`,pron:`[lè-o]`},
        {tgt:`kesho`,src:`domani`,pron:`[kè-ʃo]`},
        {tgt:`baadaye`,src:`più tardi`,pron:`[ba-a-dà-ye]`},
        {tgt:`sasa`,src:`adesso`,pron:`[sà-sa]`},
        {tgt:`kutana`,src:`incontrare`,pron:`[ku-tà-na]`},
        {tgt:`kahawa`,src:`caffè`,pron:`[ka-hà-wa]`},
        {tgt:`chakula cha jioni`,src:`cena`,pron:`[tʃa-kù-la tʃa dʒi-ò-ni]`},
        {tgt:`twende`,src:`andiamo`,pron:`[twè-nde]`},
        {tgt:`karibu`,src:`benvenuto, prego`,pron:`[ka-rì-bu]`},
      ],
      phrases: [
        {tgt:`Tukutane kesho.`,src:`Incontriamoci domani.`,pron:`[tu-ku-tà-ne kè-ʃo]`},
        {tgt:`Twende kunywa kahawa.`,src:`Andiamo a bere un caffè.`,pron:`[twè-nde ku-ɲwa ka-hà-wa]`},
        {tgt:`Una mpango leo?`,src:`Hai programmi oggi?`,pron:`[ù-na m-pà-ngo lè-o]`},
        {tgt:`Labda baadaye.`,src:`Forse più tardi.`,pron:`[làb-da ba-a-dà-ye]`},
        {tgt:`Sina mpango.`,src:`Non ho programmi.`,pron:`[sì-na m-pà-ngo]`},
        {tgt:`Ni wazo nzuri.`,src:`È una buona idea.`,pron:`[ni wà-zo n-zù-ri]`},
      ],
      conversation: [
      ],
    },
    {
      day: 26,
      title: `Lavanderia e servizi quotidiani`,
      titleNative: `Kufua na huduma za kila siku`,
      focus: `Durante un viaggio lungo potresti cercare lavanderia, barbiere o piccoli servizi. Oggi impari richieste pratiche per la vita quotidiana.`,
      grammar: `“ tayari” significa “pronto”. “Lini?” ti aiuta a chiedere quando sarà pronto qualcosa. “Kukata nywele” significa “tagliare i capelli”, una frase pratica se resti a lungo in città.`,
      vocab: [
        {tgt:`kufua`,src:`lavare vestiti`,pron:`[ku-fù-a]`},
        {tgt:`nguo`,src:`vestiti`,pron:`[ŋ-gù-o]`},
        {tgt:`sabuni`,src:`sapone`,pron:`[sa-bù-ni]`},
        {tgt:`huduma`,src:`servizio`,pron:`[hu-dù-ma]`},
        {tgt:`kinyozi`,src:`barbiere`,pron:`[ki-ɲò-zi]`},
        {tgt:`saluni`,src:`salone`,pron:`[sa-lù-ni]`},
        {tgt:`leo`,src:`oggi`,pron:`[lè-o]`},
        {tgt:`kesho`,src:`domani`,pron:`[kè-ʃo]`},
        {tgt:`safi`,src:`pulito`,pron:`[sà-fi]`},
        {tgt:`chafu`,src:`sporco`,pron:`[tʃà-fu]`},
      ],
      phrases: [
        {tgt:`Nahitaji kufua nguo.`,src:`Ho bisogno di lavare i vestiti.`,pron:`[na-hi-tà-dʒi ku-fù-a ŋ-gù-o]`},
        {tgt:`Nguo zitakuwa tayari lini?`,src:`Quando saranno pronti i vestiti?`,pron:`[ŋ-gù-o zi-ta-kù-wa ta-yà-ri lì-ni]`},
        {tgt:`Naomba huduma hii.`,src:`Vorrei questo servizio.`,pron:`[na-òm-ba hu-dù-ma hì-i]`},
        {tgt:`Kuna kinyozi karibu?`,src:`C’è un barbiere vicino?`,pron:`[kù-na ki-ɲò-zi ka-rì-bu]`},
        {tgt:`Nataka kukata nywele.`,src:`Voglio tagliare i capelli.`,pron:`[na-tà-ka ku-kà-ta ɲwè-le]`},
        {tgt:`Ni safi sasa.`,src:`È pulito adesso.`,pron:`[ni sà-fi sà-sa]`},
      ],
      conversation: [
      ],
    },
    {
      day: 27,
      title: `Banca, soldi e pagamenti`,
      titleNative: `Benki, pesa na malipo`,
      focus: `Devi cambiare denaro, prelevare o pagare con carta. Oggi impari frasi per banche, bancomat e ricevute.`,
      grammar: `“Kulipa” significa “pagare”, ma nella frase diventa “ninalipa” al presente. “Kwa” significa “con” o “tramite”: “kwa kadi” è “con carta”. Per transazioni, parla lentamente e conferma sempre l’importo.`,
      vocab: [
        {tgt:`benki`,src:`banca`,pron:`[bèn-ki]`},
        {tgt:`ATM`,src:`bancomat`,pron:`[ei-ti-èm]`},
        {tgt:`pesa`,src:`soldi`,pron:`[pè-sa]`},
        {tgt:`kadi`,src:`carta`,pron:`[kà-di]`},
        {tgt:`risiti`,src:`ricevuta`,pron:`[ri-sì-ti]`},
        {tgt:`kubadilisha`,src:`cambiare`,pron:`[ku-ba-dì-li-ʃa]`},
        {tgt:`dola`,src:`dollaro`,pron:`[dò-la]`},
        {tgt:`shilingi`,src:`scellino`,pron:`[ʃi-lìn-gi]`},
        {tgt:`lipa`,src:`pagare`,pron:`[lì-pa]`},
        {tgt:`toa pesa`,src:`prelevare`,pron:`[tò-a pè-sa]`},
      ],
      phrases: [
        {tgt:`Benki iko wapi?`,src:`Dov’è la banca?`,pron:`[bèn-ki ì-ko wà-pi]`},
        {tgt:`ATM iko karibu?`,src:`C’è un bancomat vicino?`,pron:`[ei-ti-èm ì-ko ka-rì-bu]`},
        {tgt:`Nataka kubadilisha dola.`,src:`Voglio cambiare dollari.`,pron:`[na-tà-ka ku-ba-dì-li-ʃa dò-la]`},
        {tgt:`Ninalipa kwa kadi.`,src:`Pago con carta.`,pron:`[ni-na-lì-pa kwa kà-di]`},
        {tgt:`Naomba risiti.`,src:`Vorrei una ricevuta.`,pron:`[na-òm-ba ri-sì-ti]`},
        {tgt:`Nataka kutoa pesa.`,src:`Voglio prelevare soldi.`,pron:`[na-tà-ka tò-a pè-sa]`},
      ],
      conversation: [
      ],
    },
    {
      day: 28,
      title: `Problemi e reclami cortesi`,
      titleNative: `Matatizo na malalamiko kwa heshima`,
      focus: `A volte una camera, un ordine o un servizio non va bene. Oggi impari a spiegare un problema con calma e chiedere una soluzione.`,
      grammar: `Per chiedere aiuto in modo personale, usa “kunisaidia”: “aiutarmi”. “Unaweza kunisaidia?” è una delle frasi più utili in assoluto. Con reclami, inizia con “samahani” per mantenere un tono rispettoso.`,
      vocab: [
        {tgt:`tatizo`,src:`problema`,pron:`[ta-tì-zo]`},
        {tgt:`samahani`,src:`mi scusi`,pron:`[sa-ma-hà-ni]`},
        {tgt:`haribika`,src:`essere rotto`,pron:`[ha-rì-bi-ka]`},
        {tgt:`fanya kazi`,src:`funzionare`,pron:`[fà-nya kà-zi]`},
        {tgt:`maji`,src:`acqua`,pron:`[mà-dʒi]`},
        {tgt:`umeme`,src:`elettricità`,pron:`[u-mè-me]`},
        {tgt:`baridi`,src:`freddo`,pron:`[ba-rì-di]`},
        {tgt:`moto`,src:`caldo`,pron:`[mò-to]`},
        {tgt:`badilisha`,src:`cambiare`,pron:`[ba-dì-li-ʃa]`},
        {tgt:`saidia`,src:`aiutare`,pron:`[sa-ì-di-a]`},
      ],
      phrases: [
        {tgt:`Kuna tatizo.`,src:`C’è un problema.`,pron:`[kù-na ta-tì-zo]`},
        {tgt:`Maji hayafanyi kazi.`,src:`L’acqua non funziona.`,pron:`[mà-dʒi ha-ya-fà-nyi kà-zi]`},
        {tgt:`Umeme haupo.`,src:`Non c’è elettricità.`,pron:`[u-mè-me hà-u-po]`},
        {tgt:`Chumba ni baridi sana.`,src:`La camera è troppo fredda.`,pron:`[tʃù-mba ni ba-rì-di sà-na]`},
        {tgt:`Naomba kubadilisha chumba.`,src:`Vorrei cambiare camera.`,pron:`[na-òm-ba ku-ba-dì-li-ʃa tʃù-mba]`},
        {tgt:`Unaweza kunisaidia?`,src:`Puoi aiutarmi?`,pron:`[u-na-wè-za ku-ni-sa-ì-di-a]`},
      ],
      conversation: [
      ],
    },
    {
      day: 29,
      title: `Raccontare cosa hai fatto`,
      titleNative: `Kusema ulichofanya`,
      focus: `Dopo un tour o una giornata in città, vuoi raccontare dove sei stato e cosa hai visto. Oggi impari forme semplici al passato.`,
      grammar: `“Ni-li-” indica spesso il passato per “io”: “nilienda”, “niliona”, “nilikula”. È una struttura molto regolare e utile. Per raccontare una giornata, inizia con “jana” o “leo” e poi aggiungi il verbo al passato.`,
      vocab: [
        {tgt:`nilienda`,src:`sono andato`,pron:`[ni-li-è-nda]`},
        {tgt:`niliona`,src:`ho visto`,pron:`[ni-li-ò-na]`},
        {tgt:`nilikula`,src:`ho mangiato`,pron:`[ni-li-kù-la]`},
        {tgt:`nilinunua`,src:`ho comprato`,pron:`[ni-li-nu-nù-a]`},
        {tgt:`jana`,src:`ieri`,pron:`[dʒà-na]`},
        {tgt:`leo`,src:`oggi`,pron:`[lè-o]`},
        {tgt:`safari`,src:`safari, viaggio`,pron:`[sa-fà-ri]`},
        {tgt:`soko`,src:`mercato`,pron:`[sò-ko]`},
        {tgt:`bahari`,src:`mare`,pron:`[ba-hà-ri]`},
        {tgt:`marafiki`,src:`amici`,pron:`[ma-ra-fì-ki]`},
      ],
      phrases: [
        {tgt:`Jana nilienda sokoni.`,src:`Ieri sono andato al mercato.`,pron:`[dʒà-na ni-li-è-nda so-kò-ni]`},
        {tgt:`Niliona bahari.`,src:`Ho visto il mare.`,pron:`[ni-li-ò-na ba-hà-ri]`},
        {tgt:`Nilikula chakula kizuri.`,src:`Ho mangiato buon cibo.`,pron:`[ni-li-kù-la tʃa-kù-la ki-zù-ri]`},
        {tgt:`Nilinunua zawadi.`,src:`Ho comprato un regalo.`,pron:`[ni-li-nu-nù-a za-wà-di]`},
        {tgt:`Safari ilikuwa nzuri.`,src:`Il safari è stato bello.`,pron:`[sa-fà-ri i-li-kù-wa n-zù-ri]`},
        {tgt:`Nilikutana na marafiki.`,src:`Ho incontrato amici.`,pron:`[ni-li-ku-tà-na na ma-ra-fì-ki]`},
      ],
      conversation: [
      ],
    },
    {
      day: 30,
      title: `Revisione per il viaggio reale`,
      titleNative: `Marudio kwa safari halisi`,
      focus: `Oggi unisci saluti, hotel, cibo, trasporti e problemi pratici. È una revisione finale per muoverti con più sicurezza in un paese di lingua swahili.`,
      grammar: `Hai imparato presente, futuro e passato in frasi pratiche: “ninataka”, “nitaenda”, “nilienda”. Non serve parlare perfettamente per viaggiare bene; saluti, cortesia e chiarezza contano moltissimo. Quando sei incerto, usa “samahani”, “tafadhali” e “sielewi”.`,
      vocab: [
        {tgt:`safari`,src:`viaggio`,pron:`[sa-fà-ri]`},
        {tgt:`hoteli`,src:`hotel`,pron:`[ho-tè-li]`},
        {tgt:`chakula`,src:`cibo`,pron:`[tʃa-kù-la]`},
        {tgt:`maji`,src:`acqua`,pron:`[mà-dʒi]`},
        {tgt:`teksi`,src:`taxi`,pron:`[tèk-si]`},
        {tgt:`bei`,src:`prezzo`,pron:`[bè-i]`},
        {tgt:`msaada`,src:`aiuto`,pron:`[m-sà-a-da]`},
        {tgt:`salama`,src:`sicuro`,pron:`[sa-là-ma]`},
        {tgt:`leo`,src:`oggi`,pron:`[lè-o]`},
        {tgt:`kesho`,src:`domani`,pron:`[kè-ʃo]`},
      ],
      phrases: [
        {tgt:`Habari? Nzuri, asante.`,src:`Come va? Bene, grazie.`,pron:`[ha-bà-ri n-zù-ri a-sàn-te]`},
        {tgt:`Nahitaji msaada kidogo.`,src:`Ho bisogno di un po’ di aiuto.`,pron:`[na-hi-tà-dʒi m-sà-a-da ki-dò-go]`},
        {tgt:`Nataka kwenda hotelini.`,src:`Voglio andare in hotel.`,pron:`[na-tà-ka kwè-nda ho-te-lì-ni]`},
        {tgt:`Bei ni ngapi?`,src:`Quanto costa?`,pron:`[bè-i ni ŋ-gà-pi]`},
        {tgt:`Naomba maji ya chupa.`,src:`Vorrei acqua in bottiglia.`,pron:`[na-òm-ba mà-dʒi ya tʃù-pa]`},
        {tgt:`Kesho nitaenda sokoni.`,src:`Domani andrò al mercato.`,pron:`[kè-ʃo ni-ta-è-nda so-kò-ni]`},
      ],
      conversation: [
      ],
    },
  ]
};