// course-sw-sq.js
// Source: Swahili | Target: Albanian
const COURSE_DATA = {
  src: 'sw',
  tgt: 'sq',
  srcName: 'Swahili',
  tgtName: 'Albanian',
  srcFlag: '🇰🇪',
  tgtFlag: '🇦🇱',
  days: [
    {
      day: 1,
      title: `Salamu za kwanza na adabu ya msingi`,
      titleNative: `Përshëndetjet e para`,
      focus: `Leo unajifunza kusalimia watu kwa heshima ukiwa Tirana au Prishtina. Haya ni maneno ya kwanza utakayotumia hotelini, dukani, au unapokutana na mtu mtaani.`,
      grammar: `Kwa Kialbania, “ju” hutumika kumwambia mtu “wewe” kwa heshima, hasa kwa mtu usiyemjua au mfanyakazi wa huduma. “Si jeni?” ni njia ya heshima kuuliza “Habari yako?” Katika mazungumzo yasiyo rasmi unaweza kusikia “Si je?”, lakini kwa msafiri ni salama kuanza na “Si jeni?”`,
      vocab: [
        {tgt:`përshëndetje`,src:`habari / salamu`,pron:`/pər-ʃən-det-je/`},
        {tgt:`mirë`,src:`vizuri / mzuri`,pron:`/mir/`},
        {tgt:`faleminderit`,src:`asante`,pron:`/fa-le-min-de-rit/`},
        {tgt:`ju lutem`,src:`tafadhali`,pron:`/ju lu-tem/`},
        {tgt:`po`,src:`ndiyo`,pron:`/po/`},
        {tgt:`jo`,src:`hapana`,pron:`/jo/`},
        {tgt:`mirëmëngjes`,src:`habari za asubuhi`,pron:`/mir-mən-gjes/`},
        {tgt:`mirëmbrëma`,src:`habari za jioni`,pron:`/mir-mbrə-ma/`},
        {tgt:`natën e mirë`,src:`usiku mwema`,pron:`/na-tən e mir/`},
        {tgt:`mirupafshim`,src:`tutaonana / kwaheri`,pron:`/mi-ru-paf-ʃim/`},
      ],
      phrases: [
        {tgt:`Përshëndetje!`,src:`Habari!`,pron:`/pər-ʃən-det-je/`},
        {tgt:`Si jeni?`,src:`Habari yako?`,pron:`/si je-ni/`},
        {tgt:`Jam mirë.`,src:`Niko vizuri.`,pron:`/jam mir/`},
        {tgt:`Faleminderit shumë.`,src:`Asante sana.`,pron:`/fa-le-min-de-rit ʃum/`},
        {tgt:`Ju lutem.`,src:`Tafadhali.`,pron:`/ju lu-tem/`},
        {tgt:`Mirupafshim!`,src:`Kwaheri!`,pron:`/mi-ru-paf-ʃim/`},
      ],
      conversation: [
      ],
    },
    {
      day: 2,
      title: `Kujitambulisha`,
      titleNative: `Prezantimi`,
      focus: `Leo unajifunza kusema jina lako, unatoka wapi, na kuwa wewe ni msafiri. Hii ni muhimu unapokutana na wenyeji Tirana, Shkodër, Prizren, au Durrës.`,
      grammar: `“Kujitambulisha” mara nyingi hutumia “jam” kwa maana ya “niko” au “mimi ni.” “Quhem” maana yake ni “ninaitwa,” na ni njia ya kawaida kusema jina lako. Ukiuliza mtu kwa heshima, tumia “Nga jeni?” badala ya “Nga je?”`,
      vocab: [
        {tgt:`emër`,src:`jina`,pron:`/e-mər/`},
        {tgt:`unë`,src:`mimi`,pron:`/u-nə/`},
        {tgt:`ti`,src:`wewe`,pron:`/ti/`},
        {tgt:`jam`,src:`niko / mimi ni`,pron:`/jam/`},
        {tgt:`nga`,src:`kutoka`,pron:`/ŋga/`},
        {tgt:`Shqipëri`,src:`Albania`,pron:`/ʃki-pə-ri/`},
        {tgt:`Kosovë`,src:`Kosovo`,pron:`/ko-so-və/`},
        {tgt:`turist`,src:`mtalii`,pron:`/tu-rist/`},
        {tgt:`mik`,src:`rafiki`,pron:`/mik/`},
        {tgt:`vend`,src:`nchi / mahali`,pron:`/vend/`},
      ],
      phrases: [
        {tgt:`Unë jam turist.`,src:`Mimi ni mtalii.`,pron:`/u-nə jam tu-rist/`},
        {tgt:`Quhem Jimmy.`,src:`Ninaitwa Jimmy.`,pron:`/tʃu-hem Jimmy/`},
        {tgt:`Nga jeni?`,src:`Unatoka wapi?`,pron:`/ŋga je-ni/`},
        {tgt:`Jam nga Tanzania.`,src:`Ninatoka Tanzania.`,pron:`/jam ŋga tan-za-ni-a/`},
        {tgt:`Gëzohem që ju njoh.`,src:`Nafurahi kukufahamu.`,pron:`/gə-zo-hem tʃə ju njoh/`},
        {tgt:`Ky është miku im.`,src:`Huyu ni rafiki yangu.`,pron:`/ki əʃt mi-ku im/`},
      ],
      conversation: [
      ],
    },
    {
      day: 3,
      title: `Nambari 0 hadi 20`,
      titleNative: `Numrat nga zero deri në njëzet`,
      focus: `Leo unajifunza nambari za msingi kwa kununua tiketi, kuuliza bei, na kuelewa namba za vyumba hotelini. Nambari hizi zitakusaidia sana sokoni na kwenye usafiri wa ndani.`,
      grammar: `Nambari za Kialbania huwekwa kabla ya nomino mara nyingi, kama “dy kafe” kwa “kahawa mbili.” Kwa vitu vingi vya kila siku, unaweza kutumia nambari bila kubadilisha sana muundo wa sentensi. Sikiliza tofauti kati ya “një” na “dy,” kwa sababu zitatumika sana kwenye maagizo.`,
      vocab: [
        {tgt:`zero`,src:`sifuri`,pron:`/ze-ro/`},
        {tgt:`një`,src:`moja`,pron:`/ɲə/`},
        {tgt:`dy`,src:`mbili`,pron:`/dy/`},
        {tgt:`tre`,src:`tatu`,pron:`/tre/`},
        {tgt:`katër`,src:`nne`,pron:`/ka-tər/`},
        {tgt:`pesë`,src:`tano`,pron:`/pe-sə/`},
        {tgt:`gjashtë`,src:`sita`,pron:`/gjaʃt/`},
        {tgt:`shtatë`,src:`saba`,pron:`/ʃtat/`},
        {tgt:`tetë`,src:`nane`,pron:`/te-tə/`},
        {tgt:`dhjetë`,src:`kumi`,pron:`/ðje-tə/`},
      ],
      phrases: [
        {tgt:`Një biletë, ju lutem.`,src:`Tiketi moja, tafadhali.`,pron:`/ɲə bi-le-t ju lu-tem/`},
        {tgt:`Dy kafe, ju lutem.`,src:`Kahawa mbili, tafadhali.`,pron:`/dy ka-fe ju lu-tem/`},
        {tgt:`Sa kushton?`,src:`Inagharimu kiasi gani?`,pron:`/sa kuʃ-ton/`},
        {tgt:`Kushton dhjetë euro.`,src:`Inagharimu euro kumi.`,pron:`/kuʃ-ton ðje-tə eu-ro/`},
        {tgt:`Kam tre çanta.`,src:`Nina mabegi matatu.`,pron:`/kam tre tʃan-ta/`},
        {tgt:`Dhoma numër pesë.`,src:`Chumba namba tano.`,pron:`/ðo-ma nu-mər pe-sə/`},
      ],
      conversation: [
      ],
    },
    {
      day: 4,
      title: `Maneno muhimu ya kuishi safarini`,
      titleNative: `Fjalë të rëndësishme për udhëtim`,
      focus: `Leo unajifunza maneno ya dharura na maombi rahisi ukiwa katika miji ya Albania au Kosovo. Haya yanakusaidia kuomba msaada bila kuhitaji sentensi ndefu.`,
      grammar: `“Më duhet” ni muundo muhimu sana unaomaanisha “ninahitaji” au “inanihitajia.” Unaweza kusema “Më duhet ujë,” “Më duhet telefon,” au “Më duhet hotel.” Kwa dharura, sentensi fupi na wazi ni bora kuliko kujaribu kuongea kwa urefu.`,
      vocab: [
        {tgt:`ndihmë`,src:`msaada`,pron:`/ndi-hmə/`},
        {tgt:`ujë`,src:`maji`,pron:`/u-jə/`},
        {tgt:`ushqim`,src:`chakula`,pron:`/uʃ-tʃim/`},
        {tgt:`tualet`,src:`choo`,pron:`/tu-a-let/`},
        {tgt:`telefon`,src:`simu`,pron:`/te-le-fon/`},
        {tgt:`hotel`,src:`hoteli`,pron:`/ho-tel/`},
        {tgt:`spital`,src:`hospitali`,pron:`/spi-tal/`},
        {tgt:`polici`,src:`polisi`,pron:`/po-li-tsi/`},
        {tgt:`humbur`,src:`kupotea`,pron:`/hum-bur/`},
        {tgt:`urgjencë`,src:`dharura`,pron:`/ur-gjen-tsə/`},
      ],
      phrases: [
        {tgt:`Kam nevojë për ndihmë.`,src:`Nahitaji msaada.`,pron:`/kam ne-vo-jə pər ndi-hmə/`},
        {tgt:`Ku është tualeti?`,src:`Choo kiko wapi?`,pron:`/ku əʃt tu-a-le-ti/`},
        {tgt:`Kam humbur.`,src:`Nimepotea.`,pron:`/kam hum-bur/`},
        {tgt:`Ju lutem, telefononi policinë.`,src:`Tafadhali, wapigie polisi.`,pron:`/ju lu-tem te-le-fo-no-ni po-li-tsi-nə/`},
        {tgt:`Ku është spitali?`,src:`Hospitali iko wapi?`,pron:`/ku əʃt spi-ta-li/`},
        {tgt:`Më duhet ujë.`,src:`Nahitaji maji.`,pron:`/mə du-het u-jə/`},
      ],
      conversation: [
      ],
    },
    {
      day: 5,
      title: `Kuuliza lugha na kuelewa polepole`,
      titleNative: `Gjuha dhe të kuptuarit ngadalë`,
      focus: `Leo unajifunza kuomba mtu azungumze polepole au kurudia. Hii ni muhimu sana unapozungumza na wahudumu, madereva, au wenyeji ambao hawazungumzi Kiswahili.`,
      grammar: `“Nuk” huwekwa kabla ya kitenzi kufanya sentensi kuwa ya kukanusha, kama “Nuk kuptoj” kwa “Sielewi.” Kwa heshima, vitenzi mara nyingi huishia na “-ni,” kama “flisni” na “përsërisni.” Kwa msafiri, “Më falni” ni maneno ya kuanza ombi kwa upole.`,
      vocab: [
        {tgt:`gjuhë`,src:`lugha`,pron:`/gju-hə/`},
        {tgt:`shqip`,src:`Kialbania`,pron:`/ʃtʃip/`},
        {tgt:`anglisht`,src:`Kiingereza`,pron:`/an-gliʃt/`},
        {tgt:`pak`,src:`kidogo`,pron:`/pak/`},
        {tgt:`ngadalë`,src:`polepole`,pron:`/ŋga-da-lə/`},
        {tgt:`përsëri`,src:`tena`,pron:`/pər-sə-ri/`},
        {tgt:`kuptoj`,src:`ninaelewa`,pron:`/kup-toj/`},
        {tgt:`flas`,src:`ninazungumza`,pron:`/flas/`},
        {tgt:`më falni`,src:`samahani`,pron:`/mə fal-ni/`},
        {tgt:`nuk`,src:`si / hapana katika kukanusha`,pron:`/nuk/`},
      ],
      phrases: [
        {tgt:`A flisni anglisht?`,src:`Je, unazungumza Kiingereza?`,pron:`/a flis-ni an-gliʃt/`},
        {tgt:`Flas pak shqip.`,src:`Ninazungumza Kialbania kidogo.`,pron:`/flas pak ʃtʃip/`},
        {tgt:`Nuk kuptoj.`,src:`Sielewi.`,pron:`/nuk kup-toj/`},
        {tgt:`Mund ta përsërisni?`,src:`Unaweza kurudia?`,pron:`/mund ta pər-sə-ris-ni/`},
        {tgt:`Ju lutem, më ngadalë.`,src:`Tafadhali, polepole zaidi.`,pron:`/ju lu-tem mə ŋga-da-lə/`},
        {tgt:`Më falni.`,src:`Samahani.`,pron:`/mə fal-ni/`},
      ],
      conversation: [
      ],
    },
    {
      day: 6,
      title: `Siku, muda, na ratiba`,
      titleNative: `Ditët, ora dhe orari`,
      focus: `Leo unajifunza kuzungumza kuhusu siku na muda ukiwa unapanga safari kutoka Tirana kwenda Durrës au Prishtina. Hii inasaidia kwenye mabasi, mikutano, na tiketi za makumbusho.`,
      grammar: `Kwa muda, Kialbania hutumia “ora” kumaanisha saa. “Është ora...” huanza sentensi ya kutaja saa. Kwa ratiba, “sot,” “nesër,” na “dje” mara nyingi huwekwa mwanzoni mwa sentensi ili kufanya maana iwe wazi.`,
      vocab: [
        {tgt:`sot`,src:`leo`,pron:`/sot/`},
        {tgt:`nesër`,src:`kesho`,pron:`/ne-sər/`},
        {tgt:`dje`,src:`jana`,pron:`/dje/`},
        {tgt:`ditë`,src:`siku`,pron:`/di-tə/`},
        {tgt:`orë`,src:`saa`,pron:`/o-rə/`},
        {tgt:`mëngjes`,src:`asubuhi`,pron:`/mən-gjes/`},
        {tgt:`pasdite`,src:`alasiri`,pron:`/pas-di-te/`},
        {tgt:`mbrëmje`,src:`jioni`,pron:`/mbrəm-je/`},
        {tgt:`tani`,src:`sasa`,pron:`/ta-ni/`},
        {tgt:`vonë`,src:`kuchelewa`,pron:`/vo-nə/`},
      ],
      phrases: [
        {tgt:`Sa është ora?`,src:`Saa ngapi?`,pron:`/sa əʃt o-ra/`},
        {tgt:`Është ora nëntë.`,src:`Ni saa tatu asubuhi / saa tisa kulingana na mfumo.`,pron:`/əʃt o-ra nən-tə/`},
        {tgt:`Sot shkoj në Durrës.`,src:`Leo ninaenda Durrës.`,pron:`/sot ʃkoj nə du-rəs/`},
        {tgt:`Nesër kam një rezervim.`,src:`Kesho nina nafasi iliyohifadhiwa.`,pron:`/ne-sər kam ɲə re-zer-vim/`},
        {tgt:`Autobusi është në mëngjes.`,src:`Basi liko asubuhi.`,pron:`/au-to-bu-si əʃt nə mən-gjes/`},
        {tgt:`Jam vonë.`,src:`Nimechelewa.`,pron:`/jam vo-nə/`},
      ],
      conversation: [
      ],
    },
    {
      day: 7,
      title: `Familia na watu unaosafiri nao`,
      titleNative: `Familja dhe njerëzit në udhëtim`,
      focus: `Leo unajifunza kutaja watu ulio nao safarini. Hii ni muhimu unapoweka nafasi hotelini, unaponunua tiketi za kikundi, au unapoongea na mwenyeji.`,
      grammar: `“Kjo” hutumika kwa “huyu/hili” kwa nomino za kike, na “ky” kwa nomino za kiume. “Im” na “ime” humaanisha “yangu,” lakini hubadilika kulingana na jinsia ya nomino. Kwa sasa, kariri mifano kama “vëllai im” na “motra ime.”`,
      vocab: [
        {tgt:`familje`,src:`familia`,pron:`/fa-mil-je/`},
        {tgt:`nënë`,src:`mama`,pron:`/nə-nə/`},
        {tgt:`baba`,src:`baba`,pron:`/ba-ba/`},
        {tgt:`vëlla`,src:`kaka / ndugu wa kiume`,pron:`/və-la/`},
        {tgt:`motër`,src:`dada / ndugu wa kike`,pron:`/mo-tər/`},
        {tgt:`fëmijë`,src:`mtoto / watoto`,pron:`/fə-mi-jə/`},
        {tgt:`grua`,src:`mwanamke / mke`,pron:`/gru-a/`},
        {tgt:`burrë`,src:`mwanaume / mume`,pron:`/bu-rə/`},
        {tgt:`shok`,src:`rafiki wa kiume`,pron:`/ʃok/`},
        {tgt:`shoqe`,src:`rafiki wa kike`,pron:`/ʃo-tʃe/`},
      ],
      phrases: [
        {tgt:`Jam me familjen time.`,src:`Niko na familia yangu.`,pron:`/jam me fa-mil-jen ti-me/`},
        {tgt:`Ky është vëllai im.`,src:`Huyu ni kaka yangu.`,pron:`/ki əʃt və-lai im/`},
        {tgt:`Kjo është motra ime.`,src:`Huyu ni dada yangu.`,pron:`/kjo əʃt mo-tra i-me/`},
        {tgt:`Kemi dy fëmijë.`,src:`Tuna watoto wawili.`,pron:`/ke-mi dy fə-mi-jə/`},
        {tgt:`Udhëtoj me një shok.`,src:`Ninasafiri na rafiki wa kiume.`,pron:`/u-ðə-toj me ɲə ʃok/`},
        {tgt:`Udhëtoj vetëm.`,src:`Ninasafiri peke yangu.`,pron:`/u-ðə-toj ve-təm/`},
      ],
      conversation: [
      ],
    },
    {
      day: 8,
      title: `Uwanja wa ndege na kuwasili`,
      titleNative: `Aeroporti dhe mbërritja`,
      focus: `Leo unajifunza maneno ya uwanja wa ndege unapowasili Tirana International Airport au Prishtina International Airport. Utatumia haya kwa mizigo, pasipoti, na usafiri wa kwenda mjini.`,
      grammar: `“Dua” maana yake ni “nataka,” na ni kitenzi muhimu sana kwa msafiri. Unaweza kusema “Dua një taksi,” “Dua ujë,” au “Dua një biletë.” Neno “për në” linaonyesha mwelekeo wa kwenda mahali, kama “për në qendër.”`,
      vocab: [
        {tgt:`aeroport`,src:`uwanja wa ndege`,pron:`/a-e-ro-port/`},
        {tgt:`pasaportë`,src:`pasipoti`,pron:`/pa-sa-port/`},
        {tgt:`bagazh`,src:`mzigo`,pron:`/ba-gaʒ/`},
        {tgt:`valixhe`,src:`sanduku la safari`,pron:`/va-li-dʒe/`},
        {tgt:`fluturim`,src:`safari ya ndege`,pron:`/flu-tu-rim/`},
        {tgt:`mbërritje`,src:`kuwasili`,pron:`/mbə-rit-je/`},
        {tgt:`nisje`,src:`kuondoka`,pron:`/nis-je/`},
        {tgt:`doganë`,src:`forodha`,pron:`/do-ga-nə/`},
        {tgt:`taksi`,src:`teksi`,pron:`/tak-si/`},
        {tgt:`qendër`,src:`kituo / katikati ya mji`,pron:`/tʃen-dər/`},
      ],
      phrases: [
        {tgt:`Ku është bagazhi?`,src:`Mzigo uko wapi?`,pron:`/ku əʃt ba-ga-ʒi/`},
        {tgt:`Kjo është valixhja ime.`,src:`Hili ni sanduku langu.`,pron:`/kjo əʃt va-li-dʒja i-me/`},
        {tgt:`Kam pasaportën këtu.`,src:`Nina pasipoti hapa.`,pron:`/kam pa-sa-port-ən kə-tu/`},
        {tgt:`Dua një taksi për në qendër.`,src:`Nataka teksi kwenda katikati ya mji.`,pron:`/du-a ɲə tak-si pər nə tʃen-dər/`},
        {tgt:`Fluturimi im është vonë.`,src:`Ndege yangu imechelewa.`,pron:`/flu-tu-ri-mi im əʃt vo-nə/`},
        {tgt:`Ku është dalja?`,src:`Njia ya kutoka iko wapi?`,pron:`/ku əʃt dal-ja/`},
      ],
      conversation: [
      ],
    },
    {
      day: 9,
      title: `Hoteli na kuweka nafasi`,
      titleNative: `Hoteli dhe rezervimi`,
      focus: `Leo unajifunza kuingia hotelini Tirana, Vlorë, au Prizren. Utajifunza kusema una rezervim, kuuliza kuhusu chumba, na kuelewa huduma za msingi.`,
      grammar: `“A ka...?” ni njia rahisi kuuliza kama kitu kipo, kama “A ka internet?” au “A ka mëngjes?” “Për dy netë” maana yake ni “kwa usiku mbili.” Hoteli nyingi hutumia maneno ya kimataifa kama “recepsion” na “internet,” hivyo ni rahisi kuyatambua.`,
      vocab: [
        {tgt:`rezervim`,src:`nafasi iliyohifadhiwa`,pron:`/re-zer-vim/`},
        {tgt:`dhomë`,src:`chumba`,pron:`/ðo-mə/`},
        {tgt:`çelës`,src:`ufunguo`,pron:`/tʃe-ləs/`},
        {tgt:`recepsion`,src:`mapokezi`,pron:`/re-tsep-sion/`},
        {tgt:`natë`,src:`usiku`,pron:`/na-tə/`},
        {tgt:`krevat`,src:`kitanda`,pron:`/kre-vat/`},
        {tgt:`dush`,src:`bafu la kuoga`,pron:`/duʃ/`},
        {tgt:`internet`,src:`intaneti`,pron:`/in-ter-net/`},
        {tgt:`mëngjes`,src:`kifungua kinywa`,pron:`/mən-gjes/`},
        {tgt:`ashensor`,src:`lifti`,pron:`/a-ʃen-sor/`},
      ],
      phrases: [
        {tgt:`Kam një rezervim.`,src:`Nina nafasi iliyohifadhiwa.`,pron:`/kam ɲə re-zer-vim/`},
        {tgt:`Rezervimi është në emrin Cannon.`,src:`Nafasi iko kwa jina Cannon.`,pron:`/re-zer-vi-mi əʃt nə em-rin Cannon/`},
        {tgt:`Dua një dhomë për dy netë.`,src:`Nataka chumba kwa usiku mbili.`,pron:`/du-a ɲə ðo-mə pər dy ne-tə/`},
        {tgt:`A ka internet?`,src:`Kuna intaneti?`,pron:`/a ka in-ter-net/`},
        {tgt:`Ku është dhoma ime?`,src:`Chumba changu kiko wapi?`,pron:`/ku əʃt ðo-ma i-me/`},
        {tgt:`Mund të kem çelësin?`,src:`Naweza kupata ufunguo?`,pron:`/mund tə kem tʃe-lə-sin/`},
      ],
      conversation: [
      ],
    },
    {
      day: 10,
      title: `Mwelekeo na maeneo mjini`,
      titleNative: `Drejtimet dhe vendet në qytet`,
      focus: `Leo unajifunza kuuliza mwelekeo katika mitaa ya Tirana, Prishtina, au Gjirokastër. Hii itakusaidia kufika sokoni, makumbusho, kituo cha basi, au hoteli.`,
      grammar: `Katika maelekezo, vitenzi vya heshima mara nyingi huishia “-ni,” kama “shkoni” na “kthehuni.” Unaweza kuunganisha maneno rahisi: “drejt, pastaj majtas” maana yake “moja kwa moja, halafu kushoto.” “Nga këtu” maana yake “kutoka hapa.”`,
      vocab: [
        {tgt:`majtas`,src:`kushoto`,pron:`/maj-tas/`},
        {tgt:`djathtas`,src:`kulia`,pron:`/djaθ-tas/`},
        {tgt:`drejt`,src:`moja kwa moja`,pron:`/drejt/`},
        {tgt:`afër`,src:`karibu`,pron:`/a-fər/`},
        {tgt:`larg`,src:`mbali`,pron:`/larg/`},
        {tgt:`rrugë`,src:`barabara`,pron:`/rru-gə/`},
        {tgt:`shesh`,src:`uwanja / plaza`,pron:`/ʃeʃ/`},
        {tgt:`stacion`,src:`kituo`,pron:`/sta-tsion/`},
        {tgt:`muze`,src:`makumbusho`,pron:`/mu-ze/`},
        {tgt:`hartë`,src:`ramani`,pron:`/har-tə/`},
      ],
      phrases: [
        {tgt:`Ku është stacioni?`,src:`Kituo kiko wapi?`,pron:`/ku əʃt sta-tsio-ni/`},
        {tgt:`Shkoni drejt.`,src:`Nendeni moja kwa moja.`,pron:`/ʃko-ni drejt/`},
        {tgt:`Kthehuni majtas.`,src:`Geukeni kushoto.`,pron:`/kthe-hu-ni maj-tas/`},
        {tgt:`Është afër?`,src:`Iko karibu?`,pron:`/əʃt a-fər/`},
        {tgt:`Është larg nga këtu?`,src:`Iko mbali kutoka hapa?`,pron:`/əʃt larg ŋga kə-tu/`},
        {tgt:`Mund ta shihni në hartë?`,src:`Unaweza kuonyesha kwenye ramani?`,pron:`/mund ta ʃih-ni nə har-tə/`},
      ],
      conversation: [
      ],
    },
    {
      day: 11,
      title: `Teksi na usafiri wa mjini`,
      titleNative: `Taksi dhe transporti në qytet`,
      focus: `Leo unajifunza kuzungumza na dereva wa teksi au gari la programu katika Tirana na Prishtina. Lengo ni kueleza unakoenda, kuuliza bei, na kuthibitisha njia.`,
      grammar: `“Dua të shkoj” maana yake “nataka kwenda.” Baada ya “dua,” mara nyingi unaweka “të” kabla ya kitenzi kingine. Kwa teksi, “Ndaloni këtu” ni sentensi muhimu sana ukitaka kushuka mahali fulani.`,
      vocab: [
        {tgt:`shofer`,src:`dereva`,pron:`/ʃo-fer/`},
        {tgt:`adresë`,src:`anwani`,pron:`/a-dre-sə/`},
        {tgt:`çmim`,src:`bei`,pron:`/tʃmim/`},
        {tgt:`metër`,src:`mita / taximeter`,pron:`/me-tər/`},
        {tgt:`makinë`,src:`gari`,pron:`/ma-ki-nə/`},
        {tgt:`trafik`,src:`foleni`,pron:`/tra-fik/`},
        {tgt:`ndalesë`,src:`kituo cha kusimama`,pron:`/nda-le-sə/`},
        {tgt:`këtu`,src:`hapa`,pron:`/kə-tu/`},
        {tgt:`atje`,src:`kule`,pron:`/a-tje/`},
        {tgt:`pagesë`,src:`malipo`,pron:`/pa-ge-sə/`},
      ],
      phrases: [
        {tgt:`Dua të shkoj në këtë adresë.`,src:`Nataka kwenda kwenye anwani hii.`,pron:`/du-a tə ʃkoj nə kə-tə a-dre-sə/`},
        {tgt:`Sa kushton deri atje?`,src:`Inagharimu kiasi gani mpaka kule?`,pron:`/sa kuʃ-ton de-ri a-tje/`},
        {tgt:`Ju lutem, përdorni metrin.`,src:`Tafadhali, tumia mita.`,pron:`/ju lu-tem pər-dor-ni me-trin/`},
        {tgt:`Ndaloni këtu, ju lutem.`,src:`Simama hapa, tafadhali.`,pron:`/nda-lo-ni kə-tu ju lu-tem/`},
        {tgt:`A ka shumë trafik?`,src:`Kuna foleni nyingi?`,pron:`/a ka ʃum tra-fik/`},
        {tgt:`Mund të paguaj me kartë?`,src:`Naweza kulipa kwa kadi?`,pron:`/mund tə pa-gu-aj me kar-tə/`},
      ],
      conversation: [
      ],
    },
    {
      day: 12,
      title: `Basi, treni, na tiketi`,
      titleNative: `Autobusi, treni dhe biletat`,
      focus: `Leo unajifunza kununua tiketi za basi au treni kwa safari kati ya miji kama Tirana, Durrës, Shkodër, Prishtina, na Peja. Hii ni siku muhimu kwa kusafiri kwa bajeti.`,
      grammar: `“Për në” hutumika kuonyesha marudio ya safari, kama “për në Shkodër.” “Kur” maana yake ni “lini,” na hutumika kuuliza muda wa kuondoka au kufika. Katika vituo, unaweza kusikia “niset” kwa kuondoka na “mbërrin” kwa kufika.`,
      vocab: [
        {tgt:`autobus`,src:`basi`,pron:`/au-to-bus/`},
        {tgt:`tren`,src:`treni`,pron:`/tren/`},
        {tgt:`biletë`,src:`tiketi`,pron:`/bi-le-tə/`},
        {tgt:`stacion autobusësh`,src:`kituo cha mabasi`,pron:`/sta-tsion au-to-bu-səʃ/`},
        {tgt:`orari`,src:`ratiba`,pron:`/o-ra-ri/`},
        {tgt:`niset`,src:`inaondoka`,pron:`/ni-set/`},
        {tgt:`mbërrin`,src:`inafika`,pron:`/mbə-rrin/`},
        {tgt:`vonesë`,src:`kuchelewa`,pron:`/vo-ne-sə/`},
        {tgt:`vajtje`,src:`kwenda`,pron:`/vaj-tje/`},
        {tgt:`vajtje-ardhje`,src:`kwenda na kurudi`,pron:`/vaj-tje ard-je/`},
      ],
      phrases: [
        {tgt:`Një biletë për në Shkodër, ju lutem.`,src:`Tiketi moja kwenda Shkodër, tafadhali.`,pron:`/ɲə bi-le-t pər nə ʃko-dər ju lu-tem/`},
        {tgt:`Kur niset autobusi?`,src:`Basi linaondoka lini?`,pron:`/kur ni-set au-to-bu-si/`},
        {tgt:`Kur mbërrin në Prishtinë?`,src:`Linafika Prishtina lini?`,pron:`/kur mbə-rrin nə priʃ-ti-nə/`},
        {tgt:`Dua biletë vajtje-ardhje.`,src:`Nataka tiketi ya kwenda na kurudi.`,pron:`/du-a bi-le-t vaj-tje ard-je/`},
        {tgt:`A ka vonesë?`,src:`Kuna kuchelewa?`,pron:`/a ka vo-ne-sə/`},
        {tgt:`Ku është platforma?`,src:`Jukwaa liko wapi?`,pron:`/ku əʃt plat-for-ma/`},
      ],
      conversation: [
      ],
    },
    {
      day: 13,
      title: `Kahawa na vinywaji`,
      titleNative: `Kafeja dhe pijet`,
      focus: `Leo unajifunza kuagiza kahawa na vinywaji katika kafene za Tirana, Prishtina, au Korçë. Utamaduni wa kahawa ni muhimu sana katika eneo la Balkani.`,
      grammar: `“Me” maana yake “na,” na “pa” maana yake “bila.” Hivyo unaweza kubadilisha agizo lako kwa urahisi: “me qumësht,” “pa sheqer,” “pa gaz.” Katika kafene, “A keni...?” ni njia ya kuuliza kama wanacho kitu.`,
      vocab: [
        {tgt:`kafe`,src:`kahawa`,pron:`/ka-fe/`},
        {tgt:`çaj`,src:`chai`,pron:`/tʃaj/`},
        {tgt:`ujë`,src:`maji`,pron:`/u-jə/`},
        {tgt:`birrë`,src:`bia`,pron:`/bi-rə/`},
        {tgt:`lëng`,src:`juisi`,pron:`/ləng/`},
        {tgt:`qumësht`,src:`maziwa`,pron:`/tʃu-məʃt/`},
        {tgt:`sheqer`,src:`sukari`,pron:`/ʃe-tʃer/`},
        {tgt:`pa`,src:`bila`,pron:`/pa/`},
        {tgt:`me`,src:`na / pamoja na`,pron:`/me/`},
        {tgt:`gotë`,src:`glasi`,pron:`/go-tə/`},
      ],
      phrases: [
        {tgt:`Një kafe, ju lutem.`,src:`Kahawa moja, tafadhali.`,pron:`/ɲə ka-fe ju lu-tem/`},
        {tgt:`Dua çaj pa sheqer.`,src:`Nataka chai bila sukari.`,pron:`/du-a tʃaj pa ʃe-tʃer/`},
        {tgt:`A keni ujë pa gaz?`,src:`Mna maji yasiyo na gesi?`,pron:`/a ke-ni u-jə pa gaz/`},
        {tgt:`Me qumësht, ju lutem.`,src:`Na maziwa, tafadhali.`,pron:`/me tʃu-məʃt ju lu-tem/`},
        {tgt:`Një gotë ujë, ju lutem.`,src:`Glasi moja ya maji, tafadhali.`,pron:`/ɲə go-tə u-jə ju lu-tem/`},
        {tgt:`Sa kushton kafja?`,src:`Kahawa inagharimu kiasi gani?`,pron:`/sa kuʃ-ton kaf-ja/`},
      ],
      conversation: [
      ],
    },
    {
      day: 14,
      title: `Chakula cha mgahawani`,
      titleNative: `Ushqimi në restorant`,
      focus: `Leo unajifunza kuagiza chakula katika mgahawa wa Albania au Kosovo. Utatumia maneno haya kwa menyu, sahani, na kuuliza mapendekezo.`,
      grammar: `“Çfarë” maana yake “nini.” Kwa kuuliza mapendekezo, “Çfarë rekomandoni?” ni sentensi bora na ya heshima. “Pa” ni muhimu kwa kubadilisha chakula, hasa kama hutaki kitu kama jibini, nyama, au sukari.`,
      vocab: [
        {tgt:`ushqim`,src:`chakula`,pron:`/uʃ-tʃim/`},
        {tgt:`restorant`,src:`mgahawa`,pron:`/res-to-rant/`},
        {tgt:`menu`,src:`menyu`,pron:`/me-nu/`},
        {tgt:`supë`,src:`supu`,pron:`/su-pə/`},
        {tgt:`mish`,src:`nyama`,pron:`/miʃ/`},
        {tgt:`peshk`,src:`samaki`,pron:`/peʃk/`},
        {tgt:`perime`,src:`mboga`,pron:`/pe-ri-me/`},
        {tgt:`bukë`,src:`mkate`,pron:`/bu-kə/`},
        {tgt:`djathë`,src:`jibini`,pron:`/djaθ/`},
        {tgt:`ëmbëlsirë`,src:`kitindamlo`,pron:`/əm-bəl-si-rə/`},
      ],
      phrases: [
        {tgt:`A mund të shoh menunë?`,src:`Naweza kuona menyu?`,pron:`/a mund tə ʃoh me-nu-nə/`},
        {tgt:`Çfarë rekomandoni?`,src:`Unapendekeza nini?`,pron:`/tʃfa-rə re-ko-man-do-ni/`},
        {tgt:`Dua mish me perime.`,src:`Nataka nyama na mboga.`,pron:`/du-a miʃ me pe-ri-me/`},
        {tgt:`A ka peshk sot?`,src:`Kuna samaki leo?`,pron:`/a ka peʃk sot/`},
        {tgt:`Pa djathë, ju lutem.`,src:`Bila jibini, tafadhali.`,pron:`/pa djaθ ju lu-tem/`},
        {tgt:`Ishte shumë e shijshme.`,src:`Kilikuwa kitamu sana.`,pron:`/iʃ-te ʃum e ʃij-ʃme/`},
      ],
      conversation: [
      ],
    },
    {
      day: 15,
      title: `Vyakula vya kienyeji na ladha`,
      titleNative: `Ushqime tradicionale dhe shije`,
      focus: `Leo unajifunza kuzungumza kuhusu ladha na vyakula maarufu kama byrek, tavë kosi, na flija. Hii itakusaidia kujaribu vyakula vya ndani bila hofu.`,
      grammar: `Vivumishi vya Kialbania mara nyingi huja baada ya nomino au baada ya “është.” Unaweza kusema “Është i shijshëm” kwa kitu cha kiume, na mara nyingine “e shijshme” kwa kitu cha kike. Kwa msafiri, kueleweka ni muhimu zaidi kuliko ukamilifu wa kisarufi.`,
      vocab: [
        {tgt:`byrek`,src:`pai ya kienyeji / byrek`,pron:`/by-rek/`},
        {tgt:`tavë kosi`,src:`chakula cha kondoo na mtindi`,pron:`/ta-və ko-si/`},
        {tgt:`flija`,src:`chakula cha tabaka cha Kosovo`,pron:`/fli-ja/`},
        {tgt:`i shijshëm`,src:`kitamu`,pron:`/i ʃij-ʃəm/`},
        {tgt:`i kripur`,src:`chenye chumvi`,pron:`/i kri-pur/`},
        {tgt:`i ëmbël`,src:`tamu`,pron:`/i əm-bəl/`},
        {tgt:`pikant`,src:`kali`,pron:`/pi-kant/`},
        {tgt:`i nxehtë`,src:`moto`,pron:`/i ndze-ht/`},
        {tgt:`i ftohtë`,src:`baridi`,pron:`/i ftoht/`},
        {tgt:`porosi`,src:`agizo`,pron:`/po-ro-si/`},
      ],
      phrases: [
        {tgt:`Dua të provoj byrek.`,src:`Nataka kujaribu byrek.`,pron:`/du-a tə pro-voj by-rek/`},
        {tgt:`A është pikant?`,src:`Je, ni kali?`,pron:`/a əʃt pi-kant/`},
        {tgt:`Është shumë i shijshëm.`,src:`Ni kitamu sana.`,pron:`/əʃt ʃum i ʃij-ʃəm/`},
        {tgt:`Nuk dua shumë kripë.`,src:`Sitaki chumvi nyingi.`,pron:`/nuk du-a ʃum kri-pə/`},
        {tgt:`A është ushqim tradicional?`,src:`Je, ni chakula cha jadi?`,pron:`/a əʃt uʃ-tʃim tra-di-tsio-nal/`},
        {tgt:`Mund të porosis tani?`,src:`Naweza kuagiza sasa?`,pron:`/mund tə po-ro-sis ta-ni/`},
      ],
      conversation: [
      ],
    },
    {
      day: 16,
      title: `Kulipa bili na fedha`,
      titleNative: `Pagesa dhe paratë`,
      focus: `Leo unajifunza kulipa kwenye mgahawa, duka, au hoteli. Utajifunza kuuliza bili, kutumia pesa taslimu au kadi, na kuelewa risiti.`,
      grammar: `“Mund të...” maana yake “naweza...” au “unaweza...” kulingana na muktadha. Ni muundo wa heshima na rahisi sana: “Mund të paguaj,” “Mund të marr,” “Mund të shoh.” Katika malipo, “me kartë” ni kwa kadi na “cash” ni pesa taslimu.`,
      vocab: [
        {tgt:`para`,src:`pesa`,pron:`/pa-ra/`},
        {tgt:`euro`,src:`euro`,pron:`/eu-ro/`},
        {tgt:`lek`,src:`lek ya Albania`,pron:`/lek/`},
        {tgt:`kartë`,src:`kadi`,pron:`/kar-tə/`},
        {tgt:`cash`,src:`pesa taslimu`,pron:`/kash/`},
        {tgt:`faturë`,src:`bili / ankara`,pron:`/fa-tu-rə/`},
        {tgt:`kupon`,src:`risiti`,pron:`/ku-pon/`},
        {tgt:`ndryshim`,src:`chenji`,pron:`/ndry-ʃim/`},
        {tgt:`pagoj`,src:`ninalipa`,pron:`/pa-goj/`},
        {tgt:`bankomat`,src:`ATM`,pron:`/ban-ko-mat/`},
      ],
      phrases: [
        {tgt:`Faturën, ju lutem.`,src:`Bili, tafadhali.`,pron:`/fa-tu-rən ju lu-tem/`},
        {tgt:`Mund të paguaj me kartë?`,src:`Naweza kulipa kwa kadi?`,pron:`/mund tə pa-gu-aj me kar-tə/`},
        {tgt:`Kam vetëm cash.`,src:`Nina pesa taslimu tu.`,pron:`/kam ve-təm kash/`},
        {tgt:`Ku është bankomati?`,src:`ATM iko wapi?`,pron:`/ku əʃt ban-ko-ma-ti/`},
        {tgt:`A mund të marr kuponin?`,src:`Naweza kupata risiti?`,pron:`/a mund tə marr ku-po-nin/`},
        {tgt:`Më duhet ndryshim.`,src:`Nahitaji chenji.`,pron:`/mə du-het ndry-ʃim/`},
      ],
      conversation: [
      ],
    },
    {
      day: 17,
      title: `Ununuzi sokoni na dukani`,
      titleNative: `Pazari dhe dyqani`,
      focus: `Leo unajifunza kufanya ununuzi katika soko la Tirana au Prizren. Utajifunza kuuliza bei, ukubwa, rangi, na kupunguza au kuongeza kitu kwenye agizo.`,
      grammar: `“Kjo” maana yake “hiki/hili,” na “këtë” hutumika kama “hiki” kinapokuwa kitu unachotaka. “Më” hutumika kufanya ulinganisho: “më i lirë” nafuu zaidi, “më i madh” kubwa zaidi. Sokoni, tabasamu na “ju lutem” hufanya mazungumzo yawe laini.`,
      vocab: [
        {tgt:`dyqan`,src:`duka`,pron:`/dy-tʃan/`},
        {tgt:`pazar`,src:`soko`,pron:`/pa-zar/`},
        {tgt:`çmim`,src:`bei`,pron:`/tʃmim/`},
        {tgt:`i lirë`,src:`nafuu`,pron:`/i li-rə/`},
        {tgt:`i shtrenjtë`,src:`ghali`,pron:`/i ʃtrenjt/`},
        {tgt:`ngjyrë`,src:`rangi`,pron:`/ŋgjy-rə/`},
        {tgt:`madhësi`,src:`ukubwa`,pron:`/ma-ðə-si/`},
        {tgt:`i vogël`,src:`ndogo`,pron:`/i vo-gəl/`},
        {tgt:`i madh`,src:`kubwa`,pron:`/i mað/`},
        {tgt:`çantë`,src:`begi`,pron:`/tʃan-tə/`},
      ],
      phrases: [
        {tgt:`Sa kushton kjo?`,src:`Hiki kinagharimu kiasi gani?`,pron:`/sa kuʃ-ton kjo/`},
        {tgt:`Është shumë e shtrenjtë.`,src:`Ni ghali sana.`,pron:`/əʃt ʃum e ʃtrenjt/`},
        {tgt:`A keni madhësi më të madhe?`,src:`Mna ukubwa mkubwa zaidi?`,pron:`/a ke-ni ma-ðə-si mə tə ma-ðe/`},
        {tgt:`Dua këtë ngjyrë.`,src:`Nataka rangi hii.`,pron:`/du-a kə-tə ŋgjy-rə/`},
        {tgt:`A ka diçka më të lirë?`,src:`Kuna kitu cha bei nafuu zaidi?`,pron:`/a ka ditʃ-ka mə tə li-rə/`},
        {tgt:`Do ta marr.`,src:`Nitakichukua.`,pron:`/do ta marr/`},
      ],
      conversation: [
      ],
    },
    {
      day: 18,
      title: `Mavazi na vitu binafsi`,
      titleNative: `Rrobat dhe sendet personale`,
      focus: `Leo unajifunza maneno ya mavazi na vitu vya kusafiri. Hii inasaidia ukihitaji kununua koti, viatu, au kuchukua kitu ulichosahau.`,
      grammar: `“Kërkoj” maana yake “natafuta,” na ni muhimu sana dukani. “A mund ta provoj?” ni sentensi ya kuomba kujaribu nguo au viatu. Kumbuka kwamba vivumishi kama “e vogël” na “e madhe” vinaweza kubadilika, lakini mifano hii itaeleweka vizuri.`,
      vocab: [
        {tgt:`rroba`,src:`nguo`,pron:`/rro-ba/`},
        {tgt:`këmishë`,src:`shati`,pron:`/kə-miʃ/`},
        {tgt:`pantallona`,src:`suruali`,pron:`/pan-ta-llo-na/`},
        {tgt:`këpucë`,src:`viatu`,pron:`/kə-pu-tsə/`},
        {tgt:`xhaketë`,src:`jaketi`,pron:`/dʒa-ke-tə/`},
        {tgt:`kapelë`,src:`kofia`,pron:`/ka-pe-lə/`},
        {tgt:`orë`,src:`saa`,pron:`/o-rə/`},
        {tgt:`syze`,src:`miwani`,pron:`/sy-ze/`},
        {tgt:`çantë shpine`,src:`begi la mgongoni`,pron:`/tʃan-tə ʃpi-ne/`},
        {tgt:`pasaportë`,src:`pasipoti`,pron:`/pa-sa-port/`},
      ],
      phrases: [
        {tgt:`Më duhen këpucë të reja.`,src:`Nahitaji viatu vipya.`,pron:`/mə du-hen kə-pu-tsə tə re-ja/`},
        {tgt:`A mund ta provoj?`,src:`Naweza kujaribu?`,pron:`/a mund ta pro-voj/`},
        {tgt:`Është shumë e vogël.`,src:`Ni ndogo sana.`,pron:`/əʃt ʃum e vo-gəl/`},
        {tgt:`Është shumë e madhe.`,src:`Ni kubwa sana.`,pron:`/əʃt ʃum e ma-ðe/`},
        {tgt:`Kam humbur syzet.`,src:`Nimepoteza miwani.`,pron:`/kam hum-bur sy-zet/`},
        {tgt:`Kërkoj një xhaketë.`,src:`Natafuta jaketi.`,pron:`/kər-koj ɲə dʒa-ke-tə/`},
      ],
      conversation: [
      ],
    },
    {
      day: 19,
      title: `Hali ya hewa na mipango`,
      titleNative: `Moti dhe planet`,
      focus: `Leo unajifunza kuzungumza kuhusu hali ya hewa unapopanga kutembea Durrës, Sarandë, au milimani karibu na Theth. Hii itakusaidia kupanga nguo na shughuli.`,
      grammar: `“Do të” hutumika kuonyesha wakati ujao, kama “Do të bjerë shi?” maana yake “Itanyesha mvua?” Unaweza pia kutumia “Dua të...” kupanga shughuli: “Dua të shkoj në plazh.” Hali ya hewa mara nyingi huanza na “Është...” kwa “ni/kuna.”`,
      vocab: [
        {tgt:`mot`,src:`hali ya hewa`,pron:`/mot/`},
        {tgt:`diell`,src:`jua`,pron:`/di-ell/`},
        {tgt:`shi`,src:`mvua`,pron:`/ʃi/`},
        {tgt:`erë`,src:`upepo`,pron:`/e-rə/`},
        {tgt:`borë`,src:`theluji`,pron:`/bo-rə/`},
        {tgt:`nxehtë`,src:`joto`,pron:`/ndzeht/`},
        {tgt:`ftohtë`,src:`baridi`,pron:`/ftoht/`},
        {tgt:`re`,src:`wingu`,pron:`/re/`},
        {tgt:`plazh`,src:`ufukwe`,pron:`/plaʒ/`},
        {tgt:`mal`,src:`mlima`,pron:`/mal/`},
      ],
      phrases: [
        {tgt:`Si është moti sot?`,src:`Hali ya hewa ikoje leo?`,pron:`/si əʃt mo-ti sot/`},
        {tgt:`Është shumë nxehtë.`,src:`Kuna joto sana.`,pron:`/əʃt ʃum ndzeht/`},
        {tgt:`Do të bjerë shi?`,src:`Je, mvua itanyesha?`,pron:`/do tə bje-rə ʃi/`},
        {tgt:`Dua të shkoj në plazh.`,src:`Nataka kwenda ufukweni.`,pron:`/du-a tə ʃkoj nə plaʒ/`},
        {tgt:`Është ftohtë në mal.`,src:`Kuna baridi mlimani.`,pron:`/əʃt ftoht nə mal/`},
        {tgt:`Kam nevojë për xhaketë.`,src:`Nahitaji jaketi.`,pron:`/kam ne-vo-jə pər dʒa-ke-tə/`},
      ],
      conversation: [
      ],
    },
    {
      day: 20,
      title: `Afya na duka la dawa`,
      titleNative: `Shëndeti dhe farmacia`,
      focus: `Leo unajifunza kuomba msaada katika duka la dawa au kliniki. Hii ni muhimu ukiumwa kichwa, tumbo, au unahitaji dawa rahisi ukiwa safarini.`,
      grammar: `Kwa maumivu, tumia “Kam dhimbje...” ikifuatiwa na sehemu ya mwili, kama “koke” kwa kichwa au “stomaku” kwa tumbo. “Më duhet” tena ni muhimu kwa mahitaji ya afya. Ukiwa na dharura, tumia sentensi fupi na uonyeshe kwa ishara pale inapohitajika.`,
      vocab: [
        {tgt:`farmaci`,src:`duka la dawa`,pron:`/far-ma-tsi/`},
        {tgt:`ilaç`,src:`dawa`,pron:`/i-latʃ/`},
        {tgt:`dhimbje`,src:`maumivu`,pron:`/ðim-bje/`},
        {tgt:`kokë`,src:`kichwa`,pron:`/ko-kə/`},
        {tgt:`stomak`,src:`tumbo`,pron:`/sto-mak/`},
        {tgt:`alergji`,src:`mzio`,pron:`/a-ler-gji/`},
        {tgt:`mjek`,src:`daktari`,pron:`/mjek/`},
        {tgt:`recetë`,src:`cheti cha dawa`,pron:`/re-tse-tə/`},
        {tgt:`temperaturë`,src:`homa / joto la mwili`,pron:`/tem-pe-ra-tu-rə/`},
        {tgt:`sëmurë`,src:`mgonjwa`,pron:`/sə-mu-rə/`},
      ],
      phrases: [
        {tgt:`Ku është farmacia?`,src:`Duka la dawa liko wapi?`,pron:`/ku əʃt far-ma-tsi-a/`},
        {tgt:`Kam dhimbje koke.`,src:`Nina maumivu ya kichwa.`,pron:`/kam ðim-bje ko-ke/`},
        {tgt:`Kam dhimbje stomaku.`,src:`Nina maumivu ya tumbo.`,pron:`/kam ðim-bje sto-ma-ku/`},
        {tgt:`A më duhet recetë?`,src:`Je, ninahitaji cheti cha dawa?`,pron:`/a mə du-het re-tse-tə/`},
        {tgt:`Kam alergji.`,src:`Nina mzio.`,pron:`/kam a-ler-gji/`},
        {tgt:`Më duhet një mjek.`,src:`Nahitaji daktari.`,pron:`/mə du-het ɲə mjek/`},
      ],
      conversation: [
      ],
    },
    {
      day: 21,
      title: `Dharura na usalama`,
      titleNative: `Urgjenca dhe siguria`,
      focus: `Leo unajifunza lugha ya dharura kwa hali kama kupotea, kuibiwa, au kuhitaji polisi. Haya ni maneno muhimu lakini unatumaini hutayatumia.`,
      grammar: `Kwa dharura, amri za heshima kama “Thirrni...” zinaweza kutumika kwa watu waliokuzunguka. “Kam humbur...” ni “nimepoteza,” lakini “Më kanë vjedhur...” ni “wameniibia.” Usijali sana sarufi katika dharura; sema neno kuu kwa sauti wazi.`,
      vocab: [
        {tgt:`urgjencë`,src:`dharura`,pron:`/ur-gjen-tsə/`},
        {tgt:`siguri`,src:`usalama`,pron:`/si-gu-ri/`},
        {tgt:`rrezik`,src:`hatari`,pron:`/rre-zik/`},
        {tgt:`polici`,src:`polisi`,pron:`/po-li-tsi/`},
        {tgt:`ambulancë`,src:`ambulensi`,pron:`/am-bu-lan-tsə/`},
        {tgt:`zjarr`,src:`moto`,pron:`/zjarr/`},
        {tgt:`vjedhur`,src:`kuibiwa`,pron:`/vje-ður/`},
        {tgt:`humbur`,src:`kupotea`,pron:`/hum-bur/`},
        {tgt:`pasaportë`,src:`pasipoti`,pron:`/pa-sa-port/`},
        {tgt:`ndal`,src:`simama`,pron:`/ndal/`},
      ],
      phrases: [
        {tgt:`Është urgjencë.`,src:`Ni dharura.`,pron:`/əʃt ur-gjen-tsə/`},
        {tgt:`Thirrni policinë!`,src:`Waiteni polisi!`,pron:`/thirr-ni po-li-tsi-nə/`},
        {tgt:`Kam humbur pasaportën.`,src:`Nimepoteza pasipoti.`,pron:`/kam hum-bur pa-sa-port-ən/`},
        {tgt:`Më kanë vjedhur çantën.`,src:`Wameniibia begi.`,pron:`/mə ka-nə vje-ður tʃan-tən/`},
        {tgt:`Kam nevojë për ambulancë.`,src:`Nahitaji ambulensi.`,pron:`/kam ne-vo-jə pər am-bu-lan-tsə/`},
        {tgt:`Ka zjarr!`,src:`Kuna moto!`,pron:`/ka zjarr/`},
      ],
      conversation: [
      ],
    },
    {
      day: 22,
      title: `Kutembelea vivutio na makumbusho`,
      titleNative: `Vizita në atraksione dhe muze`,
      focus: `Leo unajifunza lugha ya utalii kwa makumbusho, majumba ya kale, na maeneo ya kihistoria kama Berat, Gjirokastër, na Krujë. Utajifunza kuuliza saa za kufunguliwa na tiketi.`,
      grammar: `“Lejohen” maana yake “zinaruhusiwa,” na ni muhimu kwa kuuliza kuhusu picha au kuingia sehemu fulani. “Hyrja” linaweza kumaanisha mlango wa kuingia au ada ya kuingia kulingana na muktadha. Katika maeneo ya kihistoria, “A lejohen fotot?” ni swali la heshima kabla ya kupiga picha.`,
      vocab: [
        {tgt:`muze`,src:`makumbusho`,pron:`/mu-ze/`},
        {tgt:`kala`,src:`ngome`,pron:`/ka-la/`},
        {tgt:`kishë`,src:`kanisa`,pron:`/ki-ʃə/`},
        {tgt:`xhami`,src:`msikiti`,pron:`/dʒa-mi/`},
        {tgt:`biletë hyrjeje`,src:`tiketi ya kuingia`,pron:`/bi-le-t hy-rje-je/`},
        {tgt:`orë hapjeje`,src:`saa za kufunguliwa`,pron:`/o-rə hap-je-je/`},
        {tgt:`udhërrëfyes`,src:`mwongoza watalii`,pron:`/u-ðə-rrə-fyes/`},
        {tgt:`histori`,src:`historia`,pron:`/his-to-ri/`},
        {tgt:`foto`,src:`picha`,pron:`/fo-to/`},
        {tgt:`e ndaluar`,src:`limekatazwa`,pron:`/e nda-lu-ar/`},
      ],
      phrases: [
        {tgt:`Sa kushton hyrja?`,src:`Kuingia kunagharimu kiasi gani?`,pron:`/sa kuʃ-ton hyr-ja/`},
        {tgt:`Kur hapet muzeu?`,src:`Makumbusho yanafunguliwa lini?`,pron:`/kur ha-pet mu-ze-u/`},
        {tgt:`A lejohen fotot?`,src:`Je, picha zinaruhusiwa?`,pron:`/a le-jo-hen fo-tot/`},
        {tgt:`Dua një udhërrëfyes.`,src:`Nataka mwongoza watalii.`,pron:`/du-a ɲə u-ðə-rrə-fyes/`},
        {tgt:`Kjo kala është shumë e bukur.`,src:`Ngome hii ni nzuri sana.`,pron:`/kjo ka-la əʃt ʃum e bu-kur/`},
        {tgt:`Ku është hyrja?`,src:`Mlango wa kuingia uko wapi?`,pron:`/ku əʃt hyr-ja/`},
      ],
      conversation: [
      ],
    },
    {
      day: 23,
      title: `Pwani, milima, na shughuli`,
      titleNative: `Plazhi, mali dhe aktivitetet`,
      focus: `Leo unajifunza kuzungumza kuhusu shughuli za burudani Albania na Kosovo, kama kwenda ufukweni Sarandë, kutembea milimani Theth, au kuona ziwa Ohrid. Hii inakusaidia kupanga siku zako za mapumziko.`,
      grammar: `“Dua të bëj...” hutumika kwa shughuli, kama “Dua të bëj ecje” kwa kutembea. “Me qira” maana yake “kwa kukodi,” na hutumika kwa magari, mashua, au vifaa. Kwa usalama, “A është e sigurt këtu?” ni swali muhimu katika sehemu mpya.`,
      vocab: [
        {tgt:`plazh`,src:`ufukwe`,pron:`/plaʒ/`},
        {tgt:`det`,src:`bahari`,pron:`/det/`},
        {tgt:`liqen`,src:`ziwa`,pron:`/li-tʃen/`},
        {tgt:`mal`,src:`mlima`,pron:`/mal/`},
        {tgt:`ecje`,src:`matembezi`,pron:`/e-tsje/`},
        {tgt:`not`,src:`kuogelea`,pron:`/not/`},
        {tgt:`varkë`,src:`mashua`,pron:`/var-kə/`},
        {tgt:`qira`,src:`kukodi`,pron:`/tʃi-ra/`},
        {tgt:`diell`,src:`jua`,pron:`/di-ell/`},
        {tgt:`pushim`,src:`mapumziko`,pron:`/pu-ʃim/`},
      ],
      phrases: [
        {tgt:`Dua të shkoj në plazh.`,src:`Nataka kwenda ufukweni.`,pron:`/du-a tə ʃkoj nə plaʒ/`},
        {tgt:`A mund të marr një varkë me qira?`,src:`Naweza kukodi mashua?`,pron:`/a mund tə marr ɲə var-kə me tʃi-ra/`},
        {tgt:`Ku mund të notoj?`,src:`Ninaweza kuogelea wapi?`,pron:`/ku mund tə no-toj/`},
        {tgt:`Dua të bëj ecje në mal.`,src:`Nataka kutembea mlimani.`,pron:`/du-a tə bəj e-tsje nə mal/`},
        {tgt:`A është e sigurt këtu?`,src:`Je, hapa ni salama?`,pron:`/a əʃt e si-gurt kə-tu/`},
        {tgt:`Sot dua pushim.`,src:`Leo nataka kupumzika.`,pron:`/sot du-a pu-ʃim/`},
      ],
      conversation: [
      ],
    },
    {
      day: 24,
      title: `Kualika na kupanga kukutana`,
      titleNative: `Ftesa dhe takime`,
      focus: `Leo unajifunza kupanga kukutana na mtu kwa kahawa au matembezi. Hii ni muhimu kwa marafiki wapya, wenyeji, au watu unaokutana nao safarini.`,
      grammar: `“Do të” hapa hutumika kwa wakati ujao: “do të takohemi” maana yake “tutakutana.” “Dakord” ni neno rahisi la kusema “sawa” au “imekubaliwa.” Kwa kupanga muda, “Në çfarë ore?” ni swali la moja kwa moja na muhimu.`,
      vocab: [
        {tgt:`takim`,src:`mkutano / kukutana`,pron:`/ta-kim/`},
        {tgt:`kafe`,src:`kahawa`,pron:`/ka-fe/`},
        {tgt:`së bashku`,src:`pamoja`,pron:`/sə bash-ku/`},
        {tgt:`sot`,src:`leo`,pron:`/sot/`},
        {tgt:`nesër`,src:`kesho`,pron:`/ne-sər/`},
        {tgt:`ora`,src:`saa`,pron:`/o-ra/`},
        {tgt:`vend`,src:`mahali`,pron:`/vend/`},
        {tgt:`dakord`,src:`sawa`,pron:`/da-kord/`},
        {tgt:`mundem`,src:`naweza`,pron:`/mun-dem/`},
        {tgt:`pres`,src:`ninasubiri`,pron:`/pres/`},
      ],
      phrases: [
        {tgt:`A do të pimë kafe?`,src:`Je, tunywe kahawa?`,pron:`/a do tə pi-mə ka-fe/`},
        {tgt:`Mund të takohemi nesër?`,src:`Tunaweza kukutana kesho?`,pron:`/mund tə ta-ko-he-mi ne-sər/`},
        {tgt:`Në çfarë ore?`,src:`Saa ngapi?`,pron:`/nə tʃfa-rə o-re/`},
        {tgt:`Ku do të takohemi?`,src:`Tutakutana wapi?`,pron:`/ku do tə ta-ko-he-mi/`},
        {tgt:`Dakord, shihemi atje.`,src:`Sawa, tutaonana kule.`,pron:`/da-kord ʃi-he-mi a-tje/`},
        {tgt:`Po të pres këtu.`,src:`Nitakusubiri hapa.`,pron:`/po tə pres kə-tu/`},
      ],
      conversation: [
      ],
    },
    {
      day: 25,
      title: `Mazungumzo madogo na wenyeji`,
      titleNative: `Biseda të shkurtra me vendasit`,
      focus: `Leo unajifunza kuongea kwa upole na wenyeji kuhusu safari, mji, na hisia zako. Hii inafanya mazungumzo yawe ya kirafiki zaidi katika Albania na Kosovo.`,
      grammar: `“Më pëlqen” maana yake “napenda,” lakini kihalisi muundo wake ni kama “kinanipendeza.” Unaweza kusema “Më pëlqen Tirana” au “Më pëlqen ushqimi.” Kwa kuonyesha heshima, “Faleminderit për...” hutumika kusema asante kwa kitu fulani.`,
      vocab: [
        {tgt:`vendas`,src:`mwenyeji`,pron:`/ven-das/`},
        {tgt:`qytet`,src:`mji`,pron:`/tʃy-tet/`},
        {tgt:`i bukur`,src:`mzuri`,pron:`/i bu-kur/`},
        {tgt:`interesant`,src:`ya kuvutia`,pron:`/in-te-re-sant/`},
        {tgt:`udhëtim`,src:`safari`,pron:`/u-ðə-tim/`},
        {tgt:`kulturë`,src:`utamaduni`,pron:`/kul-tu-rə/`},
        {tgt:`muzikë`,src:`muziki`,pron:`/mu-zik/`},
        {tgt:`mirësevini`,src:`karibu`,pron:`/mir-se-vi-ni/`},
        {tgt:`më pëlqen`,src:`napenda`,pron:`/mə pəl-tʃen/`},
        {tgt:`faleminderit`,src:`asante`,pron:`/fa-le-min-de-rit/`},
      ],
      phrases: [
        {tgt:`Më pëlqen ky qytet.`,src:`Ninapenda mji huu.`,pron:`/mə pəl-tʃen ki tʃy-tet/`},
        {tgt:`Njerëzit janë shumë të sjellshëm.`,src:`Watu ni wakarimu sana.`,pron:`/ɲje-rə-zit ja-nə ʃum tə sjell-ʃəm/`},
        {tgt:`Kultura është interesante.`,src:`Utamaduni unavutia.`,pron:`/kul-tu-ra əʃt in-te-re-san-te/`},
        {tgt:`Është hera ime e parë këtu.`,src:`Ni mara yangu ya kwanza hapa.`,pron:`/əʃt he-ra i-me e pa-rə kə-tu/`},
        {tgt:`Nga jeni ju?`,src:`Wewe unatoka wapi?`,pron:`/ŋga je-ni ju/`},
        {tgt:`Faleminderit për mikpritjen.`,src:`Asante kwa ukarimu.`,pron:`/fa-le-min-de-rit pər mik-prit-jen/`},
      ],
      conversation: [
      ],
    },
    {
      day: 26,
      title: `Simu, intaneti, na mawasiliano`,
      titleNative: `Telefoni, interneti dhe komunikimi`,
      focus: `Leo unajifunza kununua SIM, kuuliza Wi-Fi, na kushughulikia mawasiliano ukiwa safarini. Hii ni muhimu sana kwa ramani, teksi, na ujumbe.`,
      grammar: `“Cili është...?” hutumika kuuliza “ni ipi?” kwa vitu kama nenosiri au namba. “Nuk kam...” maana yake “sina,” kama “Nuk kam internet.” Kwa msaada wa kiufundi, “Mund të më ndihmoni...” ni njia ya heshima kusema “Unaweza kunisaidia...”`,
      vocab: [
        {tgt:`telefon`,src:`simu`,pron:`/te-le-fon/`},
        {tgt:`kartë SIM`,src:`SIM kadi`,pron:`/kar-tə sim/`},
        {tgt:`internet`,src:`intaneti`,pron:`/in-ter-net/`},
        {tgt:`Wi-Fi`,src:`Wi-Fi`,pron:`/wai-fai/`},
        {tgt:`fjalëkalim`,src:`nenosiri`,pron:`/fja-lə-ka-lim/`},
        {tgt:`mesazh`,src:`ujumbe`,pron:`/me-saʒ/`},
        {tgt:`numër`,src:`namba`,pron:`/nu-mər/`},
        {tgt:`karikues`,src:`chaja`,pron:`/ka-ri-ku-es/`},
        {tgt:`bateri`,src:`betri`,pron:`/ba-te-ri/`},
        {tgt:`dyqan telefoni`,src:`duka la simu`,pron:`/dy-tʃan te-le-fo-ni/`},
      ],
      phrases: [
        {tgt:`A keni Wi-Fi?`,src:`Mna Wi-Fi?`,pron:`/a ke-ni wai-fai/`},
        {tgt:`Cili është fjalëkalimi?`,src:`Nenosiri ni lipi?`,pron:`/tsi-li əʃt fja-lə-ka-li-mi/`},
        {tgt:`Dua një kartë SIM.`,src:`Nataka SIM kadi.`,pron:`/du-a ɲə kar-tə sim/`},
        {tgt:`Më duhet karikues.`,src:`Nahitaji chaja.`,pron:`/mə du-het ka-ri-ku-es/`},
        {tgt:`Nuk kam internet.`,src:`Sina intaneti.`,pron:`/nuk kam in-ter-net/`},
        {tgt:`Mund të më ndihmoni me telefonin?`,src:`Unaweza kunisaidia na simu?`,pron:`/mund tə mə ndi-hmo-ni me te-le-fo-nin/`},
      ],
      conversation: [
      ],
    },
    {
      day: 27,
      title: `Nyumba ya kupanga na kukaa kwa muda mfupi`,
      titleNative: `Apartamenti dhe qëndrimi i shkurtër`,
      focus: `Leo unajifunza lugha ya Airbnb, nyumba ya wageni, au apartamenti ya muda mfupi. Utajifunza kuuliza kuhusu mlango, ufunguo, jiko, na sheria za nyumba.`,
      grammar: `“Si” maana yake “vipi,” kama “Si hapet dera?” kwa “Mlango unafunguliwaje?” “Cilat janë...?” huuliza “zipi?” kwa vitu vingi, kama sheria. Katika nyumba za kupanga, elewa vizuri muda wa “dalja” ili usichelewe kutoka.`,
      vocab: [
        {tgt:`apartament`,src:`apartamenti`,pron:`/a-par-ta-ment/`},
        {tgt:`shtëpi`,src:`nyumba`,pron:`/ʃtə-pi/`},
        {tgt:`derë`,src:`mlango`,pron:`/de-rə/`},
        {tgt:`çelës`,src:`ufunguo`,pron:`/tʃe-ləs/`},
        {tgt:`kuzhinë`,src:`jiko`,pron:`/ku-zhi-nə/`},
        {tgt:`banjë`,src:`bafu / choo`,pron:`/ba-njə/`},
        {tgt:`rregull`,src:`sheria`,pron:`/rre-gull/`},
        {tgt:`hyrje`,src:`kuingia / mlango`,pron:`/hy-rje/`},
        {tgt:`dalje`,src:`kutoka`,pron:`/dal-je/`},
        {tgt:`qëndrim`,src:`kukaa`,pron:`/tʃən-drim/`},
      ],
      phrases: [
        {tgt:`Ku është çelësi?`,src:`Ufunguo uko wapi?`,pron:`/ku əʃt tʃe-lə-si/`},
        {tgt:`Si hapet dera?`,src:`Mlango unafunguliwaje?`,pron:`/si ha-pet de-ra/`},
        {tgt:`A mund të përdor kuzhinën?`,src:`Naweza kutumia jiko?`,pron:`/a mund tə pər-dor ku-zhi-nən/`},
        {tgt:`Cilat janë rregullat?`,src:`Sheria ni zipi?`,pron:`/tsi-lat ja-nə rre-gu-llat/`},
        {tgt:`Në çfarë ore është dalja?`,src:`Kutoka ni saa ngapi?`,pron:`/nə tʃfa-rə o-re əʃt dal-ja/`},
        {tgt:`Qëndrimi im është për tri netë.`,src:`Kukaa kwangu ni kwa usiku tatu.`,pron:`/tʃən-dri-mi im əʃt pər tri ne-tə/`},
      ],
      conversation: [
      ],
    },
    {
      day: 28,
      title: `Hisia, maoni, na matatizo madogo`,
      titleNative: `Ndjenja, mendime dhe probleme të vogla`,
      focus: `Leo unajifunza kueleza kama kitu kiko sawa, hakifanyi kazi, au unahitaji kubadilisha mpango. Hii ni muhimu hotelini, mgahawani, na wakati wa safari.`,
      grammar: `“Nuk punon” ni sentensi fupi muhimu kwa vifaa, Wi-Fi, funguo, au mashine. “Ka një problem” ni njia ya heshima kuanza kueleza tatizo. Ukisema “A mund ta ndryshoj...?” unaomba kubadilisha kitu bila kusikika mkali.`,
      vocab: [
        {tgt:`problem`,src:`tatizo`,pron:`/pro-blem/`},
        {tgt:`mirë`,src:`vizuri`,pron:`/mir/`},
        {tgt:`keq`,src:`vibaya`,pron:`/ketʃ/`},
        {tgt:`lodhur`,src:`kuchoka`,pron:`/lo-ður/`},
        {tgt:`i lumtur`,src:`mwenye furaha`,pron:`/i lum-tur/`},
        {tgt:`i shqetësuar`,src:`mwenye wasiwasi`,pron:`/i ʃtʃe-tə-su-ar/`},
        {tgt:`punon`,src:`inafanya kazi`,pron:`/pu-non/`},
        {tgt:`prishur`,src:`imeharibika`,pron:`/pri-ʃur/`},
        {tgt:`ndryshoj`,src:`ninabadilisha`,pron:`/ndry-ʃoj/`},
        {tgt:`zgjidhje`,src:`suluhisho`,pron:`/zgjidh-je/`},
      ],
      phrases: [
        {tgt:`Ka një problem.`,src:`Kuna tatizo.`,pron:`/ka ɲə pro-blem/`},
        {tgt:`Nuk punon.`,src:`Haifanyi kazi.`,pron:`/nuk pu-non/`},
        {tgt:`Jam shumë i lodhur.`,src:`Nimechoka sana.`,pron:`/jam ʃum i lo-ður/`},
        {tgt:`A mund ta ndryshoj rezervimin?`,src:`Naweza kubadilisha rezervim?`,pron:`/a mund ta ndry-ʃoj re-zer-vi-min/`},
        {tgt:`Gjithçka është mirë.`,src:`Kila kitu kiko sawa.`,pron:`/gjiθ-tʃka əʃt mir/`},
        {tgt:`Më duhet një zgjidhje.`,src:`Nahitaji suluhisho.`,pron:`/mə du-het ɲə zgjidh-je/`},
      ],
      conversation: [
      ],
    },
    {
      day: 29,
      title: `Kuondoka, kuaga, na safari inayofuata`,
      titleNative: `Largimi, lamtumira dhe udhëtimi tjetër`,
      focus: `Leo unajifunza lugha ya kuondoka hotelini, kusema kwaheri, na kupanga safari inayofuata. Hii itakusaidia kufunga safari yako kwa heshima na uwazi.`,
      grammar: `“Nisem” ni “ninaondoka,” na “kthehem” ni “ninarudi.” Kwa siku za mwisho za safari, “Faleminderit për gjithçka” ni sentensi yenye heshima na joto. “Do të kthehem” hutumia wakati ujao kusema “nitarudi.”`,
      vocab: [
        {tgt:`largim`,src:`kuondoka`,pron:`/lar-gim/`},
        {tgt:`nisem`,src:`ninaondoka`,pron:`/ni-sem/`},
        {tgt:`kthehem`,src:`ninarudi`,pron:`/kthe-hem/`},
        {tgt:`lamtumirë`,src:`kwaheri`,pron:`/lam-tu-mi-rə/`},
        {tgt:`faleminderit`,src:`asante`,pron:`/fa-le-min-de-rit/`},
        {tgt:`udhëtim`,src:`safari`,pron:`/u-ðə-tim/`},
        {tgt:`aeroport`,src:`uwanja wa ndege`,pron:`/a-e-ro-port/`},
        {tgt:`kontroll`,src:`ukaguzi`,pron:`/kon-troll/`},
        {tgt:`bagazh`,src:`mzigo`,pron:`/ba-gaʒ/`},
        {tgt:`kujtime`,src:`kumbukumbu`,pron:`/kuj-ti-me/`},
      ],
      phrases: [
        {tgt:`Nisem nesër në mëngjes.`,src:`Ninaondoka kesho asubuhi.`,pron:`/ni-sem ne-sər nə mən-gjes/`},
        {tgt:`Dua të shkoj në aeroport.`,src:`Nataka kwenda uwanja wa ndege.`,pron:`/du-a tə ʃkoj nə a-e-ro-port/`},
        {tgt:`Faleminderit për gjithçka.`,src:`Asante kwa kila kitu.`,pron:`/fa-le-min-de-rit pər gjiθ-tʃka/`},
        {tgt:`Ishte një udhëtim i bukur.`,src:`Ilikuwa safari nzuri.`,pron:`/iʃ-te ɲə u-ðə-tim i bu-kur/`},
        {tgt:`Do të kthehem përsëri.`,src:`Nitarudi tena.`,pron:`/do tə kthe-hem pər-sə-ri/`},
        {tgt:`Lamtumirë dhe mirupafshim.`,src:`Kwaheri na tutaonana.`,pron:`/lam-tu-mi-rə dhe mi-ru-paf-ʃim/`},
      ],
      conversation: [
      ],
    },
    {
      day: 30,
      title: `Mapitio ya safari kamili`,
      titleNative: `Përsëritje për gjithë udhëtimin`,
      focus: `Leo unarudia lugha muhimu ya siku zote 29 na kujiandaa kwa safari halisi katika nchi zinazozungumza Kialbania. Lengo ni kuweza kusalimia, kuuliza, kuagiza, kulipa, na kuomba msaada kwa ujasiri.`,
      grammar: `Kwa safari, si lazima ujue kila kanuni ya sarufi; unahitaji miundo inayofanya kazi. “Dua...,” “Kam...,” “Ku është...,” “Sa kushton...,” na “Mund të...” zinaweza kutengeneza mazungumzo mengi ya kila siku. Kumbuka kutumia “ju lutem” na “faleminderit” ili sauti yako iwe ya heshima.`,
      vocab: [
        {tgt:`përshëndetje`,src:`habari`,pron:`/pər-ʃən-det-je/`},
        {tgt:`faleminderit`,src:`asante`,pron:`/fa-le-min-de-rit/`},
        {tgt:`ju lutem`,src:`tafadhali`,pron:`/ju lu-tem/`},
        {tgt:`ku`,src:`wapi`,pron:`/ku/`},
        {tgt:`sa`,src:`kiasi gani`,pron:`/sa/`},
        {tgt:`kur`,src:`lini`,pron:`/kur/`},
        {tgt:`dua`,src:`nataka`,pron:`/du-a/`},
        {tgt:`kam`,src:`nina`,pron:`/kam/`},
        {tgt:`mund`,src:`naweza / unaweza`,pron:`/mund/`},
        {tgt:`ndihmë`,src:`msaada`,pron:`/ndi-hmə/`},
      ],
      phrases: [
        {tgt:`Përshëndetje, si jeni?`,src:`Habari, ukoje?`,pron:`/pər-ʃən-det-je si je-ni/`},
        {tgt:`Dua një biletë, ju lutem.`,src:`Nataka tiketi moja, tafadhali.`,pron:`/du-a ɲə bi-le-t ju lu-tem/`},
        {tgt:`Ku është hoteli?`,src:`Hoteli iko wapi?`,pron:`/ku əʃt ho-te-li/`},
        {tgt:`Sa kushton kjo?`,src:`Hiki kinagharimu kiasi gani?`,pron:`/sa kuʃ-ton kjo/`},
        {tgt:`Nuk kuptoj, ju lutem më ngadalë.`,src:`Sielewi, tafadhali polepole zaidi.`,pron:`/nuk kup-toj ju lu-tem mə ŋga-da-lə/`},
        {tgt:`Kam nevojë për ndihmë.`,src:`Nahitaji msaada.`,pron:`/kam ne-vo-jə pər ndi-hmə/`},
      ],
      conversation: [
      ],
    },
  ]
};