var COURSE_TR_NL = [
  {
    title: "Selamlaşma ve tanışma",
    titleNative: "Begroeten en kennismaken",
    focus: "Amsterdam’a yeni vardığında insanlarla kibarca selamlaşmayı ve kendini tanıtmayı öğrenirsin. Bu ders, otel lobisi, tren istasyonu veya küçük bir dükkân gibi ilk temas anları için temel oluşturur.",
    vocab: [
      {nl: "hallo", tr: "merhaba", ipa: "ha-lo"},
      {nl: "goedemorgen", tr: "günaydın", ipa: "hud-mor-hın"},
      {nl: "goedemiddag", tr: "tünaydın", ipa: "hud-mi-dah"},
      {nl: "goedenavond", tr: "iyi akşamlar", ipa: "hu-dın-a-vont"},
      {nl: "dag", tr: "merhaba / hoşça kal", ipa: "dah"},
      {nl: "ik", tr: "ben", ipa: "ik"},
      {nl: "jij", tr: "sen", ipa: "yey"},
      {nl: "u", tr: "siz", ipa: "ü"},
      {nl: "naam", tr: "isim", ipa: "naam"},
      {nl: "Turkije", tr: "Türkiye", ipa: "tür-ki-yı"},
    ],
    phrases: [
      {nl: "Hallo, ik ben Ali.", tr: "Merhaba, ben Ali.", ipa: "ha-lo, ik ben a-li"},
      {nl: "Hoe heet u?", tr: "Adınız ne?", ipa: "hu heyt ü"},
      {nl: "Ik kom uit Turkije.", tr: "Türkiye’den geliyorum.", ipa: "ik kom öyt tür-ki-yı"},
      {nl: "Aangenaam.", tr: "Memnun oldum.", ipa: "aan-hı-naam"},
      {nl: "Tot ziens.", tr: "Görüşmek üzere.", ipa: "tot ziyns"},
      {nl: "Fijne dag.", tr: "İyi günler.", ipa: "fey-nı dah"},
    ],
    grammar: "Felemenkçede “ik” ben demektir ve basit tanıtımlarda çok kullanılır. “U” resmi ve kibar “siz” anlamındadır; otelde, restoranda veya yaşça büyük biriyle konuşurken güvenli seçimdir. “Jij” ise samimi “sen” anlamına gelir. Hollanda’da kısa ve doğrudan konuşmak normaldir; kibarlık için “alstublieft” ve “dank u wel” eklemek yeterlidir.",
    practice: [
      "1. Kendi adını kullanarak “Merhaba, ben …” cümlesini Felemenkçe söyle.",
      "2. Bir otel görevlisine kibarca “Adınız ne?” diye sor.",
      "3. “Türkiye’den geliyorum” cümlesini üç kez yüksek sesle tekrar et.",
      "4. “U” ve “jij” arasındaki farkı Türkçe olarak açıkla.",
      "5. Bir tanışma diyaloğu kur: selam, isim, ülke, veda.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Temel nezaket ifadeleri",
    titleNative: "Basis beleefdheid",
    focus: "Rotterdam’da bir kafede, müzede veya markette kibarca konuşmak için en gerekli ifadeleri öğrenirsin. Günlük seyahatte küçük nezaket kelimeleri iletişimi çok daha kolaylaştırır.",
    vocab: [
      {nl: "alstublieft", tr: "lütfen / buyurun", ipa: "als-tü-bliift"},
      {nl: "dank u wel", tr: "çok teşekkür ederim", ipa: "dank ü vel"},
      {nl: "dank je wel", tr: "teşekkür ederim", ipa: "dank yı vel"},
      {nl: "sorry", tr: "pardon", ipa: "so-ri"},
      {nl: "geen probleem", tr: "sorun değil", ipa: "heyn pro-bleym"},
      {nl: "ja", tr: "evet", ipa: "yaa"},
      {nl: "nee", tr: "hayır", ipa: "ney"},
      {nl: "misschien", tr: "belki", ipa: "mis-hiyn"},
      {nl: "goed", tr: "iyi", ipa: "hut"},
      {nl: "slecht", tr: "kötü", ipa: "sleht"},
    ],
    phrases: [
      {nl: "Ja, graag.", tr: "Evet, lütfen.", ipa: "yaa hrah"},
      {nl: "Nee, dank u wel.", tr: "Hayır, teşekkür ederim.", ipa: "ney dank ü vel"},
      {nl: "Sorry, ik begrijp het niet.", tr: "Pardon, anlamıyorum.", ipa: "so-ri ik bı-hreyp hıt niyt"},
      {nl: "Kunt u dat herhalen?", tr: "Bunu tekrar edebilir misiniz?", ipa: "künt ü dat hır-haa-lın"},
      {nl: "Geen probleem.", tr: "Sorun değil.", ipa: "heyn pro-bleym"},
      {nl: "Dank u wel voor uw hulp.", tr: "Yardımınız için teşekkür ederim.", ipa: "dank ü vel vor üw hülp"},
    ],
    grammar: "“Graag” kelimesi Türkçedeki “memnuniyetle” veya “lütfen” anlamına yakın kullanılır. “Ja, graag” bir teklif kabul ederken çok doğal bir cevaptır. “Nee, dank u wel” ise kibarca reddetmenin en güvenli yoludur. Felemenkçede kısa cevaplar normaldir; uzun açıklama yapmak zorunda değilsin.",
    practice: [
      "1. Bir kafede teklif edilen suyu kabul etmek için “Ja, graag” de.",
      "2. Bir satış teklifini kibarca reddet.",
      "3. “Anlamıyorum” cümlesini Felemenkçe yaz.",
      "4. Birinden cümleyi tekrar etmesini iste.",
      "5. “Teşekkür ederim” ifadesinin resmi ve samimi iki hâlini karşılaştır.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Sayılar ve fiyatlar",
    titleNative: "Cijfers en prijzen",
    focus: "Utrecht’te bilet alırken, pazarda alışveriş yaparken veya menüde fiyat okurken sayılar gerekir. Bu derste 0’dan 100’e temel sayıları ve fiyat sormayı öğrenirsin.",
    vocab: [
      {nl: "nul", tr: "sıfır", ipa: "nül"},
      {nl: "een", tr: "bir", ipa: "eyn"},
      {nl: "twee", tr: "iki", ipa: "tvey"},
      {nl: "drie", tr: "üç", ipa: "dri"},
      {nl: "vier", tr: "dört", ipa: "viyr"},
      {nl: "vijf", tr: "beş", ipa: "veyf"},
      {nl: "zes", tr: "altı", ipa: "zes"},
      {nl: "zeven", tr: "yedi", ipa: "zey-vın"},
      {nl: "acht", tr: "sekiz", ipa: "aht"},
      {nl: "tien", tr: "on", ipa: "tiyn"},
    ],
    phrases: [
      {nl: "Hoeveel kost dit?", tr: "Bu ne kadar?", ipa: "hu-vel kost dit"},
      {nl: "Het kost vijf euro.", tr: "Beş avro tutuyor.", ipa: "hıt kost veyf ö-ro"},
      {nl: "Ik heb twee kaartjes nodig.", tr: "İki bilete ihtiyacım var.", ipa: "ik hep tvey kaart-yıs no-dıh"},
      {nl: "Dat is te duur.", tr: "Bu çok pahalı.", ipa: "dat is tı dür"},
      {nl: "Heeft u wisselgeld?", tr: "Bozuk paranız var mı?", ipa: "heyft ü vis-sıl-helt"},
      {nl: "Ik betaal met kaart.", tr: "Kartla ödeyeceğim.", ipa: "ik bı-taal met kaart"},
    ],
    grammar: "Felemenkçede fiyatlarda “euro” kelimesi çoğu zaman aynı kalır: “vijf euro”, “tien euro”. “Hoeveel kost dit?” tek bir şeyin fiyatını sormak için kullanılır. “Dit” Türkçedeki “bu” demektir ve elindeki ürünü veya yakındaki bir şeyi gösterirken işe yarar.",
    practice: [
      "1. 1’den 10’a kadar sayıları sırayla söyle.",
      "2. Bir bilet için “Bu ne kadar?” diye sor.",
      "3. “İki bilete ihtiyacım var” cümlesini Felemenkçe yaz.",
      "4. 5, 8 ve 10 avroluk üç fiyat söyle.",
      "5. Kartla ödeyeceğini belirten kısa bir cümle kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Temel sorular",
    titleNative: "Basisvragen",
    focus: "Lahey’de bir turistik bilgi noktasında soru sormayı öğrenirsin. Nerede, ne zaman, kim ve nasıl gibi kelimeler seyahatin her anında işine yarar.",
    vocab: [
      {nl: "waar", tr: "nerede", ipa: "vaar"},
      {nl: "wanneer", tr: "ne zaman", ipa: "va-neyr"},
      {nl: "wie", tr: "kim", ipa: "vi"},
      {nl: "wat", tr: "ne", ipa: "vat"},
      {nl: "hoe", tr: "nasıl", ipa: "hu"},
      {nl: "waarom", tr: "neden", ipa: "va-rom"},
      {nl: "welke", tr: "hangi", ipa: "vel-kı"},
      {nl: "hier", tr: "burada", ipa: "hiir"},
      {nl: "daar", tr: "orada", ipa: "daar"},
      {nl: "nu", tr: "şimdi", ipa: "nü"},
    ],
    phrases: [
      {nl: "Waar is het station?", tr: "İstasyon nerede?", ipa: "vaar is hıt sta-siyon"},
      {nl: "Wanneer vertrekt de trein?", tr: "Tren ne zaman kalkıyor?", ipa: "va-neyr vır-trekt dı treyn"},
      {nl: "Wat is dit?", tr: "Bu nedir?", ipa: "vat is dit"},
      {nl: "Hoe gaat het?", tr: "Nasılsınız?", ipa: "hu haat hıt"},
      {nl: "Welke bus gaat naar het centrum?", tr: "Hangi otobüs merkeze gider?", ipa: "vel-kı büs haat naar hıt sen-trüm"},
      {nl: "Is het hier dichtbij?", tr: "Burası yakın mı?", ipa: "is hıt hiir diht-bey"},
    ],
    grammar: "Felemenkçe soru cümlelerinde fiil çoğu zaman ikinci pozisyondadır. “Waar is het station?” cümlesinde “waar” soru kelimesi, “is” fiildir. Ezberlenmiş kalıplarla başlamak en pratik yoldur. Turist olarak kısa ve net soru sormak gayet doğaldır.",
    practice: [
      "1. “Nerede?” kelimesini kullanarak üç soru kur.",
      "2. Bir trenin ne zaman kalktığını sor.",
      "3. “Bu nedir?” cümlesini bir müzede kullanıyormuş gibi söyle.",
      "4. “Hangi otobüs merkeze gider?” cümlesini yaz.",
      "5. “Burada” ve “orada” kelimeleriyle iki kısa cümle kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Yönler ve yer tarifleri",
    titleNative: "Richtingen en de weg vragen",
    focus: "Haarlem sokaklarında yürürken yön sormayı ve basit tarifleri anlamayı öğrenirsin. Sağ, sol, düz git gibi ifadeler şehir gezilerinde çok kullanılır.",
    vocab: [
      {nl: "links", tr: "sol", ipa: "links"},
      {nl: "rechts", tr: "sağ", ipa: "rehts"},
      {nl: "rechtdoor", tr: "dümdüz", ipa: "reht-dor"},
      {nl: "straat", tr: "sokak", ipa: "straat"},
      {nl: "plein", tr: "meydan", ipa: "pleyn"},
      {nl: "brug", tr: "köprü", ipa: "brüh"},
      {nl: "hoek", tr: "köşe", ipa: "huk"},
      {nl: "centrum", tr: "merkez", ipa: "sen-trüm"},
      {nl: "dichtbij", tr: "yakın", ipa: "diht-bey"},
      {nl: "ver", tr: "uzak", ipa: "fer"},
    ],
    phrases: [
      {nl: "Ga rechtdoor.", tr: "Dümdüz gidin.", ipa: "ha reht-dor"},
      {nl: "Sla linksaf.", tr: "Sola dönün.", ipa: "sla links-af"},
      {nl: "Sla rechtsaf.", tr: "Sağa dönün.", ipa: "sla rehts-af"},
      {nl: "Het is op de hoek.", tr: "Köşede.", ipa: "hıt is op dı huk"},
      {nl: "Is het ver van hier?", tr: "Buradan uzak mı?", ipa: "is hıt fer fan hiir"},
      {nl: "Kunt u mij de weg wijzen?", tr: "Bana yolu gösterebilir misiniz?", ipa: "künt ü mey dı veh vey-zın"},
    ],
    grammar: "Yön tariflerinde emir kipleri genellikle kısa verilir: “Ga”, “Sla”, “Loop”. Bu ifadeler kaba değildir; pratik ve doğaldır. “Van hier” “buradan” anlamına gelir. Birine yön sorarken cümlenin başına “Sorry” eklemek konuşmayı daha kibar yapar.",
    practice: [
      "1. “Sağa dönün” ve “sola dönün” ifadelerini karşılaştır.",
      "2. Haritada hayali bir rota çizip Felemenkçe tarif et.",
      "3. Birine “Bana yolu gösterebilir misiniz?” diye sor.",
      "4. “Merkez yakın mı?” cümlesini kur.",
      "5. “Köprüden sonra sağa dönün” anlamına yakın kısa bir tarif üret.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Tren istasyonunda",
    titleNative: "Op het treinstation",
    focus: "Amsterdam Centraal veya Utrecht Centraal gibi büyük istasyonlarda bilet almak, peron bulmak ve tren saatlerini sormak için gerekli kelimeleri öğrenirsin.",
    vocab: [
      {nl: "trein", tr: "tren", ipa: "treyn"},
      {nl: "station", tr: "istasyon", ipa: "sta-siyon"},
      {nl: "perron", tr: "peron", ipa: "pe-ron"},
      {nl: "kaartje", tr: "bilet", ipa: "kaart-yı"},
      {nl: "retour", tr: "gidiş-dönüş", ipa: "rı-tur"},
      {nl: "enkele reis", tr: "tek yön", ipa: "en-kı-lı reys"},
      {nl: "vertrek", tr: "kalkış", ipa: "vır-trek"},
      {nl: "aankomst", tr: "varış", ipa: "aan-komst"},
      {nl: "vertraging", tr: "gecikme", ipa: "fır-traa-hıng"},
      {nl: "overstappen", tr: "aktarma yapmak", ipa: "o-vır-sta-pın"},
    ],
    phrases: [
      {nl: "Een kaartje naar Utrecht, alstublieft.", tr: "Utrecht’e bir bilet, lütfen.", ipa: "eyn kaart-yı naar ü-treht als-tü-bliift"},
      {nl: "Is dit de trein naar Amsterdam?", tr: "Bu Amsterdam treni mi?", ipa: "is dit dı treyn naar am-stır-dam"},
      {nl: "Vanaf welk perron vertrekt de trein?", tr: "Tren hangi perondan kalkıyor?", ipa: "fa-naf vel k pe-ron vır-trekt dı treyn"},
      {nl: "Moet ik overstappen?", tr: "Aktarma yapmam gerekiyor mu?", ipa: "mut ik o-vır-sta-pın"},
      {nl: "De trein heeft vertraging.", tr: "Tren gecikmeli.", ipa: "dı treyn heyft fır-traa-hıng"},
      {nl: "Hoe laat komt de trein aan?", tr: "Tren saat kaçta varıyor?", ipa: "hu laat komt dı treyn aan"},
    ],
    grammar: "“Moet ik…” yapısı “... yapmam gerekiyor mu?” anlamına gelir. Seyahatte çok işe yarar: “Moet ik betalen?”, “Moet ik overstappen?” gibi. “Naar” yön belirtir ve Türkçedeki “-e/-a” anlamını taşır. Şehir adlarından önce çoğu zaman ekstra ek gerekmez.",
    practice: [
      "1. Amsterdam’a tek yön bilet istediğini söyle.",
      "2. Bir trenin hangi perondan kalktığını sor.",
      "3. “Aktarma yapmam gerekiyor mu?” cümlesini ezberle.",
      "4. Tren gecikmeli olduğunda ne duyabileceğini yaz.",
      "5. “Naar” kelimesiyle üç şehir cümlesi kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Otobüs, tramvay ve metro",
    titleNative: "Bus, tram en metro",
    focus: "Rotterdam, Amsterdam ve Den Haag’da şehir içi ulaşımı kullanırken bilet, durak ve hat numarası sormayı öğrenirsin. Toplu taşıma Felemenkçe konuşulan şehirlerde düzenli ve yaygındır.",
    vocab: [
      {nl: "bus", tr: "otobüs", ipa: "büs"},
      {nl: "tram", tr: "tramvay", ipa: "tram"},
      {nl: "metro", tr: "metro", ipa: "me-tro"},
      {nl: "halte", tr: "durak", ipa: "hal-tı"},
      {nl: "lijn", tr: "hat", ipa: "leyn"},
      {nl: "kaart", tr: "kart", ipa: "kaart"},
      {nl: "inchecken", tr: "giriş yapmak", ipa: "in-çe-kın"},
      {nl: "uitchecken", tr: "çıkış yapmak", ipa: "öyt-çe-kın"},
      {nl: "chauffeur", tr: "şoför", ipa: "şo-för"},
      {nl: "richting", tr: "yön", ipa: "rih-ting"},
    ],
    phrases: [
      {nl: "Welke tram gaat naar het museum?", tr: "Hangi tram müzeye gider?", ipa: "vel-kı tram haat naar hıt mü-zey-üm"},
      {nl: "Waar is de dichtstbijzijnde halte?", tr: "En yakın durak nerede?", ipa: "vaar is dı dihtst-bey-zeyn-dı hal-tı"},
      {nl: "Moet ik hier inchecken?", tr: "Burada giriş yapmam gerekiyor mu?", ipa: "mut ik hiir in-çe-kın"},
      {nl: "Ik wil naar het centrum.", tr: "Merkeze gitmek istiyorum.", ipa: "ik vil naar hıt sen-trüm"},
      {nl: "Deze bus gaat niet naar het station.", tr: "Bu otobüs istasyona gitmiyor.", ipa: "dey-zı büs haat niyt naar hıt sta-siyon"},
      {nl: "Hoeveel haltes zijn het?", tr: "Kaç durak var?", ipa: "hu-vel hal-tıs zeyn hıt"},
    ],
    grammar: "“Deze” “bu” anlamına gelir ama genellikle belirli ve yakın bir isimle kullanılır: “deze bus”, “deze tram”. “Niet” olumsuzluk yapar ve çoğu zaman fiilden sonra gelir: “gaat niet”. Bilet veya kart sisteminde “inchecken” ve “uitchecken” kelimelerini tabelalarda sık görebilirsin.",
    practice: [
      "1. En yakın durağı sor.",
      "2. “Bu otobüs merkeze gitmiyor” cümlesini kur.",
      "3. Tramvay, otobüs ve metro için üç ayrı soru yaz.",
      "4. “Kaç durak var?” ifadesini yüksek sesle tekrar et.",
      "5. “Niet” kullanarak iki olumsuz ulaşım cümlesi kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Otelde giriş yapmak",
    titleNative: "Inchecken in het hotel",
    focus: "Brugge veya Amsterdam’da otele giriş yaparken rezervasyon, pasaport ve oda bilgilerini konuşmayı öğrenirsin. Bu ders resepsiyon konuşmaları için pratik kalıplar verir.",
    vocab: [
      {nl: "hotel", tr: "otel", ipa: "ho-tel"},
      {nl: "reservering", tr: "rezervasyon", ipa: "re-zır-vey-ring"},
      {nl: "paspoort", tr: "pasaport", ipa: "pas-port"},
      {nl: "kamer", tr: "oda", ipa: "kaa-mır"},
      {nl: "sleutel", tr: "anahtar", ipa: "slöy-tıl"},
      {nl: "lift", tr: "asansör", ipa: "lift"},
      {nl: "ontbijt", tr: "kahvaltı", ipa: "ont-beyt"},
      {nl: "receptie", tr: "resepsiyon", ipa: "rı-sep-si"},
      {nl: "nacht", tr: "gece", ipa: "naht"},
      {nl: "bagage", tr: "bagaj", ipa: "ba-haa-jı"},
    ],
    phrases: [
      {nl: "Ik heb een reservering.", tr: "Rezervasyonum var.", ipa: "ik hep eyn re-zır-vey-ring"},
      {nl: "Mijn naam is Ali Yılmaz.", tr: "Adım Ali Yılmaz.", ipa: "meyn naam is a-li yıl-maz"},
      {nl: "Mag ik uw paspoort zien?", tr: "Pasaportunuzu görebilir miyim?", ipa: "mah ik üw pas-port ziyn"},
      {nl: "Hoe laat is het ontbijt?", tr: "Kahvaltı saat kaçta?", ipa: "hu laat is hıt ont-beyt"},
      {nl: "Waar is de lift?", tr: "Asansör nerede?", ipa: "vaar is dı lift"},
      {nl: "Kan ik mijn bagage hier laten?", tr: "Bagajımı burada bırakabilir miyim?", ipa: "kan ik meyn ba-haa-jı hiir laa-tın"},
    ],
    grammar: "“Mijn” Türkçedeki “benim” anlamına gelir. “Mijn naam”, “mijn kamer”, “mijn bagage” gibi çok kullanılır. “Mag ik…” izin istemek için nazik bir yapıdır. Otelde “Kan ik…” de kullanılabilir, ama “Mag ik…” biraz daha kibar duyulur.",
    practice: [
      "1. Kendi adınla “Rezervasyonum var” cümlesi kur.",
      "2. Kahvaltının saatini sor.",
      "3. Asansörün nerede olduğunu sor.",
      "4. “Benim odam” ve “benim bagajım” ifadelerini yaz.",
      "5. Bagajını resepsiyonda bırakmak için izin iste.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Odada sorunlar",
    titleNative: "Problemen op de kamer",
    focus: "Otel odasında klima, Wi-Fi, sıcak su veya anahtar problemi olduğunda resepsiyona durumu anlatmayı öğrenirsin. Seyahatte sorunları sakin ve net ifade etmek önemlidir.",
    vocab: [
      {nl: "probleem", tr: "sorun", ipa: "pro-bleym"},
      {nl: "wifi", tr: "Wi-Fi", ipa: "vay-fay"},
      {nl: "warm water", tr: "sıcak su", ipa: "varm vaa-tır"},
      {nl: "koud", tr: "soğuk", ipa: "kaut"},
      {nl: "kapot", tr: "bozuk", ipa: "ka-pot"},
      {nl: "lawaai", tr: "gürültü", ipa: "laa-vay"},
      {nl: "handdoek", tr: "havlu", ipa: "hant-duk"},
      {nl: "bed", tr: "yatak", ipa: "bet"},
      {nl: "deur", tr: "kapı", ipa: "dör"},
      {nl: "airco", tr: "klima", ipa: "eyr-ko"},
    ],
    phrases: [
      {nl: "De wifi werkt niet.", tr: "Wi-Fi çalışmıyor.", ipa: "dı vay-fay werkt niyt"},
      {nl: "Er is geen warm water.", tr: "Sıcak su yok.", ipa: "er is heyn varm vaa-tır"},
      {nl: "De sleutel werkt niet.", tr: "Anahtar çalışmıyor.", ipa: "dı slöy-tıl werkt niyt"},
      {nl: "Mijn kamer is te koud.", tr: "Odam çok soğuk.", ipa: "meyn kaa-mır is tı kaut"},
      {nl: "Kunt u iemand sturen?", tr: "Birini gönderebilir misiniz?", ipa: "künt ü iy-mant stü-rın"},
      {nl: "Ik wil graag een andere kamer.", tr: "Başka bir oda istiyorum.", ipa: "ik vil hrah eyn an-dı-rı kaa-mır"},
    ],
    grammar: "“Werkt niet” “çalışmıyor” anlamına gelir ve cihazlar, kartlar, anahtarlar için çok pratik bir kalıptır. “Er is geen…” ise “... yok” demektir. “Geen” isimlerle olumsuzluk yapar: “geen water”, “geen handdoek”. Sorun anlatırken kısa cümleler daha kolay anlaşılır.",
    practice: [
      "1. Wi-Fi’nin çalışmadığını söyle.",
      "2. Sıcak su olmadığını resepsiyona bildir.",
      "3. Odanın çok soğuk olduğunu söyle.",
      "4. Birini göndermelerini rica et.",
      "5. “Geen” kelimesiyle üç otel sorunu yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kafede sipariş vermek",
    titleNative: "Bestellen in een café",
    focus: "Amsterdam’da bir kahve barında ya da Rotterdam’da küçük bir kafede içecek ve atıştırmalık sipariş etmeyi öğrenirsin. Hollanda ve Belçika’da kafeler sosyal hayatın önemli parçasıdır.",
    vocab: [
      {nl: "koffie", tr: "kahve", ipa: "ko-fi"},
      {nl: "thee", tr: "çay", ipa: "tey"},
      {nl: "water", tr: "su", ipa: "vaa-tır"},
      {nl: "melk", tr: "süt", ipa: "melk"},
      {nl: "suiker", tr: "şeker", ipa: "söy-kır"},
      {nl: "broodje", tr: "sandviç", ipa: "broo-cı"},
      {nl: "taart", tr: "pasta", ipa: "taart"},
      {nl: "menu", tr: "menü", ipa: "me-nü"},
      {nl: "tafel", tr: "masa", ipa: "taa-fıl"},
      {nl: "rekening", tr: "hesap", ipa: "rey-kı-ning"},
    ],
    phrases: [
      {nl: "Een koffie, alstublieft.", tr: "Bir kahve, lütfen.", ipa: "eyn ko-fi als-tü-bliift"},
      {nl: "Mag ik de menukaart?", tr: "Menüyü alabilir miyim?", ipa: "mah ik dı me-nü-kaart"},
      {nl: "Zonder suiker, graag.", tr: "Şekersiz olsun, lütfen.", ipa: "zon-dır söy-kır hrah"},
      {nl: "Met melk, graag.", tr: "Sütlü olsun, lütfen.", ipa: "met melk hrah"},
      {nl: "Mag ik afrekenen?", tr: "Hesabı ödeyebilir miyim?", ipa: "mah ik af-rey-kı-nın"},
      {nl: "Dat was lekker.", tr: "Çok lezzetliydi.", ipa: "dat vas lek-kır"},
    ],
    grammar: "“Met” “ile”, “zonder” “-siz” anlamına gelir. Kafede “met melk” ve “zonder suiker” çok kullanışlıdır. “Mag ik…” kalıbı sipariş ve ödeme anında kibar bir şekilde istek belirtir. Hollanda’da kafelerde hesabı masada veya kasada ödeyebilirsin; emin değilsen sorabilirsin.",
    practice: [
      "1. Şekersiz bir kahve sipariş et.",
      "2. Sütlü çay istediğini söyle.",
      "3. Menüyü kibarca iste.",
      "4. “Hesabı ödeyebilir miyim?” cümlesini ezberle.",
      "5. “Met” ve “zonder” kullanarak dört içecek tercihi yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Restoranda yemek seçmek",
    titleNative: "Eten kiezen in een restaurant",
    focus: "Gent veya Amsterdam’da bir restoranda menüyü anlamayı, yemek sormayı ve sipariş vermeyi öğrenirsin. Alerji ve vejetaryen seçenekleri gibi pratik konulara da giriş yaparsın.",
    vocab: [
      {nl: "restaurant", tr: "restoran", ipa: "res-to-rant"},
      {nl: "eten", tr: "yemek", ipa: "ey-tın"},
      {nl: "drinken", tr: "içmek / içecek", ipa: "dring-kın"},
      {nl: "vlees", tr: "et", ipa: "vleys"},
      {nl: "vis", tr: "balık", ipa: "fis"},
      {nl: "kip", tr: "tavuk", ipa: "kip"},
      {nl: "groente", tr: "sebze", ipa: "hrun-tı"},
      {nl: "soep", tr: "çorba", ipa: "sup"},
      {nl: "salade", tr: "salata", ipa: "sa-la-dı"},
      {nl: "vegetarisch", tr: "vejetaryen", ipa: "ve-hı-taa-ris"},
    ],
    phrases: [
      {nl: "Wat raadt u aan?", tr: "Ne tavsiye edersiniz?", ipa: "vat raat ü aan"},
      {nl: "Ik ben vegetarisch.", tr: "Vejetaryenim.", ipa: "ik ben ve-hı-taa-ris"},
      {nl: "Heeft u iets zonder vlees?", tr: "Etsiz bir şeyiniz var mı?", ipa: "heyft ü iets zon-dır vleys"},
      {nl: "Ik neem de soep.", tr: "Çorbayı alayım.", ipa: "ik neym dı sup"},
      {nl: "Kan ik water krijgen?", tr: "Su alabilir miyim?", ipa: "kan ik vaa-tır krey-hın"},
      {nl: "De rekening, alstublieft.", tr: "Hesap, lütfen.", ipa: "dı rey-kı-ning als-tü-bliift"},
    ],
    grammar: "“Ik neem…” restoranda “... alayım” anlamında çok doğal bir sipariş kalıbıdır. “Heeft u iets…” ise “... bir şeyiniz var mı?” demektir. “Zonder vlees” gibi ifadelerle yemek tercihini hızlıca açıklayabilirsin. Belçika ve Hollanda’da menülerde vejetaryen seçenekler sık görülür.",
    practice: [
      "1. Garsona tavsiye sor.",
      "2. Vejetaryen olduğunu söyle.",
      "3. Etsiz bir seçenek iste.",
      "4. Çorba sipariş et.",
      "5. “Ik neem…” kalıbıyla üç yemek seç.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kahvaltı ve fırın",
    titleNative: "Ontbijt en de bakkerij",
    focus: "Utrecht’te bir fırında kahvaltılık almak veya otelde kahvaltı büfesini anlamak için gerekli kelimeleri öğrenirsin. Ekmek, peynir ve kruvasan gibi günlük yiyecekler bu derste öne çıkar.",
    vocab: [
      {nl: "bakkerij", tr: "fırın", ipa: "ba-kı-rey"},
      {nl: "brood", tr: "ekmek", ipa: "broot"},
      {nl: "kaas", tr: "peynir", ipa: "kaas"},
      {nl: "ei", tr: "yumurta", ipa: "ey"},
      {nl: "boter", tr: "tereyağı", ipa: "bo-tır"},
      {nl: "croissant", tr: "kruvasan", ipa: "kroa-san"},
      {nl: "jam", tr: "reçel", ipa: "yem"},
      {nl: "sap", tr: "meyve suyu", ipa: "sap"},
      {nl: "ontbijt", tr: "kahvaltı", ipa: "ont-beyt"},
      {nl: "vers", tr: "taze", ipa: "fers"},
    ],
    phrases: [
      {nl: "Is het brood vers?", tr: "Ekmek taze mi?", ipa: "is hıt broot fers"},
      {nl: "Ik wil graag twee croissants.", tr: "İki kruvasan istiyorum.", ipa: "ik vil hrah tvey kroa-sans"},
      {nl: "Heeft u kaasbroodjes?", tr: "Peynirli poğaça var mı?", ipa: "heyft ü kaas-broo-cıs"},
      {nl: "Voor hier of om mee te nemen?", tr: "Burada mı, paket mi?", ipa: "vor hiir of om mey tı ney-mın"},
      {nl: "Om mee te nemen, graag.", tr: "Paket olsun, lütfen.", ipa: "om mey tı ney-mın hrah"},
      {nl: "Voor hier, alstublieft.", tr: "Burada olsun, lütfen.", ipa: "vor hiir als-tü-bliift"},
    ],
    grammar: "“Voor hier” “burada yemek için”, “om mee te nemen” ise “paket / al götür” anlamına gelir. Fırın ve kafelerde bu soru çok sık gelir. “Ik wil graag…” nazik bir istek cümlesidir. “Graag” eklemek cümleyi daha yumuşak yapar.",
    practice: [
      "1. İki kruvasan sipariş et.",
      "2. Ekmeğin taze olup olmadığını sor.",
      "3. Paket istediğini söyle.",
      "4. Burada yemek istediğini söyle.",
      "5. “Ik wil graag…” ile üç kahvaltılık sipariş yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Market alışverişi",
    titleNative: "Boodschappen doen",
    focus: "Hollanda’da Albert Heijn veya yerel bir markette temel alışveriş yapmayı öğrenirsin. Sepet, kasa, fiş ve ürün isimleri günlük hayat için önemlidir.",
    vocab: [
      {nl: "supermarkt", tr: "süpermarket", ipa: "sü-pır-markt"},
      {nl: "mandje", tr: "sepet", ipa: "mant-yı"},
      {nl: "kassa", tr: "kasa", ipa: "kas-sa"},
      {nl: "bonnetje", tr: "fiş", ipa: "bon-yı-cı"},
      {nl: "tas", tr: "çanta", ipa: "tas"},
      {nl: "appels", tr: "elmalar", ipa: "a-pıls"},
      {nl: "bananen", tr: "muzlar", ipa: "ba-na-nın"},
      {nl: "kaas", tr: "peynir", ipa: "kaas"},
      {nl: "melk", tr: "süt", ipa: "melk"},
      {nl: "fles", tr: "şişe", ipa: "fles"},
    ],
    phrases: [
      {nl: "Waar zijn de appels?", tr: "Elmalar nerede?", ipa: "vaar zeyn dı a-pıls"},
      {nl: "Heeft u een tas nodig?", tr: "Poşete ihtiyacınız var mı?", ipa: "heyft ü eyn tas no-dıh"},
      {nl: "Ja, een tas alstublieft.", tr: "Evet, bir poşet lütfen.", ipa: "yaa eyn tas als-tü-bliift"},
      {nl: "Mag ik het bonnetje?", tr: "Fişi alabilir miyim?", ipa: "mah ik hıt bon-yı-cı"},
      {nl: "Ik zoek melk.", tr: "Süt arıyorum.", ipa: "ik zuk melk"},
      {nl: "Kan ik hier betalen?", tr: "Burada ödeme yapabilir miyim?", ipa: "kan ik hiir bı-taa-lın"},
    ],
    grammar: "“Ik zoek…” “... arıyorum” anlamına gelir. Market içinde görevliye ürün sorarken en basit ve etkili kalıptır. “Nodig” ihtiyaç anlamı verir: “een tas nodig” poşete ihtiyaç duymak. Hollanda’da poşetler genellikle ücretlidir, bu yüzden kasada poşet isteyip istemediğin sorulabilir.",
    practice: [
      "1. Süt aradığını söyle.",
      "2. Poşet istediğini belirt.",
      "3. Fişi kibarca iste.",
      "4. Elmaların nerede olduğunu sor.",
      "5. “Ik zoek…” ile beş ürün cümlesi yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Açık pazar ve pazarlık değil, sohbet",
    titleNative: "Op de markt",
    focus: "Leiden veya Rotterdam’daki açık pazarda sebze, peynir ve atıştırmalık almayı öğrenirsin. Hollanda’da pazarlık her yerde beklenmez; ama ürün sormak ve miktar belirtmek önemlidir.",
    vocab: [
      {nl: "markt", tr: "pazar", ipa: "markt"},
      {nl: "verkoper", tr: "satıcı", ipa: "fır-ko-pır"},
      {nl: "fruit", tr: "meyve", ipa: "fröyt"},
      {nl: "groenten", tr: "sebzeler", ipa: "hrun-tın"},
      {nl: "aardbeien", tr: "çilek", ipa: "aard-bey-ın"},
      {nl: "tomaten", tr: "domates", ipa: "to-maa-tın"},
      {nl: "kilo", tr: "kilo", ipa: "ki-lo"},
      {nl: "half", tr: "yarım", ipa: "half"},
      {nl: "vers", tr: "taze", ipa: "fers"},
      {nl: "lekker", tr: "lezzetli", ipa: "lek-kır"},
    ],
    phrases: [
      {nl: "Een halve kilo tomaten, alstublieft.", tr: "Yarım kilo domates, lütfen.", ipa: "eyn hal-vı ki-lo to-maa-tın als-tü-bliift"},
      {nl: "Zijn deze aardbeien vers?", tr: "Bu çilekler taze mi?", ipa: "zeyn dey-zı aard-bey-ın fers"},
      {nl: "Mag ik proeven?", tr: "Tadabilir miyim?", ipa: "mah ik pru-vın"},
      {nl: "Dat ziet er lekker uit.", tr: "Lezzetli görünüyor.", ipa: "dat ziit er lek-kır öyt"},
      {nl: "Hoeveel is het samen?", tr: "Toplam ne kadar?", ipa: "hu-vel is hıt saa-mın"},
      {nl: "Ik neem dit.", tr: "Bunu alıyorum.", ipa: "ik neym dit"},
    ],
    grammar: "“Deze” çoğul veya ortak cins isimlerle “bu/bunlar” anlamına gelebilir. “Zijn deze aardbeien vers?” cümlesinde “zijn” çoğul fiildir. “Een halve kilo” pazarda çok kullanışlı bir miktar ifadesidir. Hollanda pazarlarında satıcıyla kısa sohbet etmek normaldir, ama sert pazarlık beklenmez.",
    practice: [
      "1. Yarım kilo domates iste.",
      "2. Çileklerin taze olup olmadığını sor.",
      "3. Bir şeyi tatmak için izin iste.",
      "4. Toplam fiyatı sor.",
      "5. Pazarda kullanabileceğin üç kısa cümle yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Mağazada kıyafet almak",
    titleNative: "Kleding kopen",
    focus: "Antwerp veya Amsterdam’da bir mağazada beden, renk ve deneme kabini sormayı öğrenirsin. Alışverişte kibar istekler ve basit tanımlar çok işe yarar.",
    vocab: [
      {nl: "winkel", tr: "mağaza", ipa: "vin-kıl"},
      {nl: "kleding", tr: "kıyafet", ipa: "kley-ding"},
      {nl: "maat", tr: "beden", ipa: "maat"},
      {nl: "kleur", tr: "renk", ipa: "klör"},
      {nl: "broek", tr: "pantolon", ipa: "bruk"},
      {nl: "shirt", tr: "tişört", ipa: "şört"},
      {nl: "jas", tr: "ceket / mont", ipa: "yas"},
      {nl: "schoenen", tr: "ayakkabılar", ipa: "s-hu-nın"},
      {nl: "paskamer", tr: "deneme kabini", ipa: "pas-kaa-mır"},
      {nl: "korting", tr: "indirim", ipa: "kor-ting"},
    ],
    phrases: [
      {nl: "Heeft u deze in een andere maat?", tr: "Bunun başka bedeni var mı?", ipa: "heyft ü dey-zı in eyn an-dı-rı maat"},
      {nl: "Waar is de paskamer?", tr: "Deneme kabini nerede?", ipa: "vaar is dı pas-kaa-mır"},
      {nl: "Ik zoek een jas.", tr: "Bir mont arıyorum.", ipa: "ik zuk eyn yas"},
      {nl: "Deze kleur vind ik mooi.", tr: "Bu rengi güzel buluyorum.", ipa: "dey-zı klör fint ik moy"},
      {nl: "Het is te klein.", tr: "Çok küçük.", ipa: "hıt is tı kleyn"},
      {nl: "Is er korting?", tr: "İndirim var mı?", ipa: "is er kor-ting"},
    ],
    grammar: "“Te” sıfatlardan önce “çok fazla” anlamı verir: “te klein”, “te duur”, “te koud”. Alışverişte beden ve fiyat için çok kullanılır. “Ik zoek…” mağazada da markette olduğu gibi doğal bir kalıptır. “Mooi” güzel anlamına gelir ve renkler, şehirler veya kıyafetler için kullanılabilir.",
    practice: [
      "1. Bir mont aradığını söyle.",
      "2. Deneme kabininin yerini sor.",
      "3. Bir kıyafetin çok küçük olduğunu belirt.",
      "4. İndirim olup olmadığını sor.",
      "5. “Te” ile üç alışveriş cümlesi kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Saat ve günlük plan",
    titleNative: "Tijd en dagplanning",
    focus: "Müze saatlerini, tren kalkışını ve buluşma zamanını konuşmayı öğrenirsin. Amsterdam’da Rijksmuseum’a gitmeden veya Brugge’de tekne turu planlarken saat ifadeleri çok önemlidir.",
    vocab: [
      {nl: "tijd", tr: "zaman / saat", ipa: "teyt"},
      {nl: "uur", tr: "saat", ipa: "ür"},
      {nl: "vandaag", tr: "bugün", ipa: "fan-daah"},
      {nl: "morgen", tr: "yarın", ipa: "mor-hın"},
      {nl: "gisteren", tr: "dün", ipa: "his-tı-rın"},
      {nl: "vroeg", tr: "erken", ipa: "fruh"},
      {nl: "laat", tr: "geç", ipa: "laat"},
      {nl: "middag", tr: "öğlen / öğleden sonra", ipa: "mi-dah"},
      {nl: "avond", tr: "akşam", ipa: "aa-vont"},
      {nl: "open", tr: "açık", ipa: "o-pın"},
    ],
    phrases: [
      {nl: "Hoe laat is het?", tr: "Saat kaç?", ipa: "hu laat is hıt"},
      {nl: "Het is drie uur.", tr: "Saat üç.", ipa: "hıt is dri ür"},
      {nl: "Wanneer gaat het museum open?", tr: "Müze ne zaman açılıyor?", ipa: "va-neyr haat hıt mü-zey-üm o-pın"},
      {nl: "Ik kom om tien uur.", tr: "Saat onda geliyorum.", ipa: "ik kom om tiyn ür"},
      {nl: "Is het vandaag open?", tr: "Bugün açık mı?", ipa: "is hıt fan-daah o-pın"},
      {nl: "Dat is te laat voor mij.", tr: "Bu benim için çok geç.", ipa: "dat is tı laat vor mey"},
    ],
    grammar: "Saat söylerken “om” belirli zamanı belirtir: “om tien uur” saat onda. “Hoe laat” saat sormak için kullanılır. “Vandaag”, “morgen” ve “gisteren” zaman planı yaparken temel kelimelerdir. Turistik yerlerde açılış saatlerini sormak için “Wanneer gaat het open?” çok işe yarar.",
    practice: [
      "1. Saat üç olduğunu söyle.",
      "2. Müzenin ne zaman açıldığını sor.",
      "3. Saat onda geleceğini belirt.",
      "4. Bugün açık olup olmadığını sor.",
      "5. Yarın için basit bir gezi planı yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Hava durumu ve kıyafet",
    titleNative: "Het weer en kleding",
    focus: "Hollanda’da hava hızlı değişebilir; yağmur, rüzgâr ve serinlik için hazırlıklı olmak gerekir. Bu derste hava durumunu sormayı ve planını buna göre anlatmayı öğrenirsin.",
    vocab: [
      {nl: "weer", tr: "hava durumu", ipa: "veer"},
      {nl: "regen", tr: "yağmur", ipa: "rey-hın"},
      {nl: "wind", tr: "rüzgâr", ipa: "vint"},
      {nl: "zon", tr: "güneş", ipa: "zon"},
      {nl: "koud", tr: "soğuk", ipa: "kaut"},
      {nl: "warm", tr: "sıcak", ipa: "varm"},
      {nl: "bewolkt", tr: "bulutlu", ipa: "bı-volkt"},
      {nl: "paraplu", tr: "şemsiye", ipa: "pa-ra-plü"},
      {nl: "jas", tr: "mont", ipa: "yas"},
      {nl: "nat", tr: "ıslak", ipa: "nat"},
    ],
    phrases: [
      {nl: "Hoe is het weer vandaag?", tr: "Bugün hava nasıl?", ipa: "hu is hıt veer fan-daah"},
      {nl: "Het regent.", tr: "Yağmur yağıyor.", ipa: "hıt rey-hınt"},
      {nl: "Het is koud en winderig.", tr: "Hava soğuk ve rüzgârlı.", ipa: "hıt is kaut en vin-dı-rıh"},
      {nl: "Ik heb een paraplu nodig.", tr: "Bir şemsiyeye ihtiyacım var.", ipa: "ik hep eyn pa-ra-plü no-dıh"},
      {nl: "Morgen wordt het warm.", tr: "Yarın hava sıcak olacak.", ipa: "mor-hın vort hıt varm"},
      {nl: "Mijn jas is nat.", tr: "Montum ıslak.", ipa: "meyn yas is nat"},
    ],
    grammar: "Hava durumunda “het” öznesi kullanılır: “Het regent”, “Het is koud”. Türkçede özne kullanmasak da Felemenkçede cümlede genellikle özne gerekir. “Nodig hebben” ihtiyaç duymak anlamına gelir. “Ik heb een paraplu nodig” seyahatte çok pratik bir kalıptır.",
    practice: [
      "1. Bugünkü havayı Felemenkçe tarif et.",
      "2. Yağmur yağdığını söyle.",
      "3. Şemsiyeye ihtiyacın olduğunu belirt.",
      "4. “Hava soğuk ve rüzgârlı” cümlesini yaz.",
      "5. Hava durumuna göre üç kıyafet cümlesi kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Müzeler ve turistik yerler",
    titleNative: "Musea en bezienswaardigheden",
    focus: "Amsterdam, Delft veya Brugge’de müze, kanal turu ve tarihi yerleri gezerken bilet, giriş ve fotoğraf kurallarını sormayı öğrenirsin.",
    vocab: [
      {nl: "museum", tr: "müze", ipa: "mü-zey-üm"},
      {nl: "kaartje", tr: "bilet", ipa: "kaart-yı"},
      {nl: "ingang", tr: "giriş", ipa: "in-hang"},
      {nl: "uitgang", tr: "çıkış", ipa: "öyt-hang"},
      {nl: "rondleiding", tr: "rehberli tur", ipa: "ront-ley-ding"},
      {nl: "foto", tr: "fotoğraf", ipa: "fo-to"},
      {nl: "verboden", tr: "yasak", ipa: "fır-bo-dın"},
      {nl: "toegestaan", tr: "izinli", ipa: "tu-hı-staan"},
      {nl: "schilderij", tr: "tablo", ipa: "s-hil-dı-rey"},
      {nl: "kanaal", tr: "kanal", ipa: "ka-naal"},
    ],
    phrases: [
      {nl: "Waar is de ingang?", tr: "Giriş nerede?", ipa: "vaar is dı in-hang"},
      {nl: "Mag ik hier foto’s maken?", tr: "Burada fotoğraf çekebilir miyim?", ipa: "mah ik hiir fo-tos maa-kın"},
      {nl: "Is er een rondleiding?", tr: "Rehberli tur var mı?", ipa: "is er eyn ront-ley-ding"},
      {nl: "Hoeveel kost een kaartje?", tr: "Bilet ne kadar?", ipa: "hu-vel kost eyn kaart-yı"},
      {nl: "Is dit toegestaan?", tr: "Buna izin var mı?", ipa: "is dit tu-hı-staan"},
      {nl: "Waar begint de kanaaltocht?", tr: "Kanal turu nerede başlıyor?", ipa: "vaar bı-hint dı ka-naal-toht"},
    ],
    grammar: "“Mag ik…” izin istemek için temel kalıptır. “Foto’s maken” kelimesi kelimesine “fotoğraflar yapmak” gibi görünür ama doğal anlamı fotoğraf çekmektir. “Verboden” ve “toegestaan” tabelalarda sık görülür. Müzelerde sessiz ve kısa soru sormak genellikle daha uygundur.",
    practice: [
      "1. Girişin nerede olduğunu sor.",
      "2. Fotoğraf çekmek için izin iste.",
      "3. Rehberli tur olup olmadığını sor.",
      "4. Bilet fiyatını sor.",
      "5. “Yasak” ve “izinli” kelimeleriyle iki tabela cümlesi yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Sağlık ve eczane",
    titleNative: "Gezondheid en de apotheek",
    focus: "Seyahatte baş ağrısı, mide sorunu veya küçük bir rahatsızlık olduğunda eczanede kendini ifade etmeyi öğrenirsin. Hollanda ve Belçika’da eczane için “apotheek” kelimesi kullanılır.",
    vocab: [
      {nl: "apotheek", tr: "eczane", ipa: "a-po-teyk"},
      {nl: "dokter", tr: "doktor", ipa: "dok-tır"},
      {nl: "pijn", tr: "ağrı", ipa: "peyn"},
      {nl: "hoofdpijn", tr: "baş ağrısı", ipa: "hoft-peyn"},
      {nl: "buikpijn", tr: "karın ağrısı", ipa: "böyk-peyn"},
      {nl: "koorts", tr: "ateş", ipa: "korts"},
      {nl: "medicijn", tr: "ilaç", ipa: "me-di-seyn"},
      {nl: "allergie", tr: "alerji", ipa: "a-ler-hi"},
      {nl: "ziek", tr: "hasta", ipa: "zik"},
      {nl: "pleister", tr: "yara bandı", ipa: "pley-stır"},
    ],
    phrases: [
      {nl: "Ik heb hoofdpijn.", tr: "Başım ağrıyor.", ipa: "ik hep hoft-peyn"},
      {nl: "Ik voel me ziek.", tr: "Kendimi hasta hissediyorum.", ipa: "ik vul mı zik"},
      {nl: "Heeft u iets tegen buikpijn?", tr: "Karın ağrısına karşı bir şeyiniz var mı?", ipa: "heyft ü iets tey-hın böyk-peyn"},
      {nl: "Ik heb een allergie.", tr: "Alerjim var.", ipa: "ik hep eyn a-ler-hi"},
      {nl: "Waar is de dichtstbijzijnde apotheek?", tr: "En yakın eczane nerede?", ipa: "vaar is dı dihtst-bey-zeyn-dı a-po-teyk"},
      {nl: "Moet ik naar een dokter?", tr: "Doktora gitmem gerekiyor mu?", ipa: "mut ik naar eyn dok-tır"},
    ],
    grammar: "Ağrı anlatırken “Ik heb…” kullanılır: “Ik heb hoofdpijn”, “Ik heb buikpijn”. “Tegen” ilaç bağlamında “... karşı” anlamına gelir. “Iets tegen hoofdpijn” baş ağrısına karşı bir şey demektir. Ciddi durumda kısa ve net konuşup yardım istemek en iyisidir.",
    practice: [
      "1. Başın ağrıdığını söyle.",
      "2. En yakın eczaneyi sor.",
      "3. Alerjin olduğunu belirt.",
      "4. Karın ağrısı için bir şey iste.",
      "5. “Moet ik…” ile sağlıkla ilgili iki soru kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Acil durumlar",
    titleNative: "Noodsituaties",
    focus: "Kaybolma, hırsızlık veya acil sağlık durumunda yardım istemeyi öğrenirsin. Bu ifadeler umarım gerekmez, ama seyahatte bilmek çok önemlidir.",
    vocab: [
      {nl: "help", tr: "yardım", ipa: "help"},
      {nl: "politie", tr: "polis", ipa: "po-li-si"},
      {nl: "ambulance", tr: "ambulans", ipa: "am-bü-lans"},
      {nl: "nood", tr: "acil durum", ipa: "not"},
      {nl: "gevaar", tr: "tehlike", ipa: "hı-vaar"},
      {nl: "gestolen", tr: "çalınmış", ipa: "hı-sto-lın"},
      {nl: "kwijt", tr: "kayıp", ipa: "kveyt"},
      {nl: "paspoort", tr: "pasaport", ipa: "pas-port"},
      {nl: "telefoon", tr: "telefon", ipa: "te-le-fon"},
      {nl: "adres", tr: "adres", ipa: "a-dres"},
    ],
    phrases: [
      {nl: "Help, alstublieft!", tr: "Yardım edin, lütfen!", ipa: "help als-tü-bliift"},
      {nl: "Bel de politie!", tr: "Polisi arayın!", ipa: "bel dı po-li-si"},
      {nl: "Ik ben mijn telefoon kwijt.", tr: "Telefonumu kaybettim.", ipa: "ik ben meyn te-le-fon kveyt"},
      {nl: "Mijn tas is gestolen.", tr: "Çantam çalındı.", ipa: "meyn tas is hı-sto-lın"},
      {nl: "Ik heb hulp nodig.", tr: "Yardıma ihtiyacım var.", ipa: "ik hep hülp no-dıh"},
      {nl: "Waar is het politiebureau?", tr: "Polis merkezi nerede?", ipa: "vaar is hıt po-li-si-bü-ro"},
    ],
    grammar: "“Ik ben … kwijt” bir şeyi kaybettiğini söylemek için kullanılır: “Ik ben mijn paspoort kwijt.” “Gestolen” çalınmış anlamına gelir. Acil durumda uzun cümle kurmaya çalışma; “Help”, “Politie”, “Ambulance” gibi kelimeler bile işe yarar. Hollanda ve Belçika’da acil yardım için Avrupa genelinde 112 aranır.",
    practice: [
      "1. Telefonunu kaybettiğini söyle.",
      "2. Çantanın çalındığını belirt.",
      "3. Yardıma ihtiyacın olduğunu söyle.",
      "4. Polis merkezinin nerede olduğunu sor.",
      "5. Acil durumda kullanacağın üç kısa Felemenkçe ifade yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "İnsanlarla sohbet başlatmak",
    titleNative: "Een praatje maken",
    focus: "Bir kafede, hostelde veya tren yolculuğunda yerel biriyle kısa sohbet başlatmayı öğrenirsin. Felemenkçe konuşulan ülkelerde küçük sohbetler kısa, samimi ve doğrudan olabilir.",
    vocab: [
      {nl: "praatje", tr: "kısa sohbet", ipa: "praat-yı"},
      {nl: "leuk", tr: "hoş / güzel", ipa: "lök"},
      {nl: "stad", tr: "şehir", ipa: "stat"},
      {nl: "reis", tr: "seyahat", ipa: "reys"},
      {nl: "vakantie", tr: "tatil", ipa: "va-kan-si"},
      {nl: "werk", tr: "iş", ipa: "verk"},
      {nl: "student", tr: "öğrenci", ipa: "stü-dent"},
      {nl: "muziek", tr: "müzik", ipa: "mü-zik"},
      {nl: "film", tr: "film", ipa: "film"},
      {nl: "vriend", tr: "arkadaş", ipa: "friynt"},
    ],
    phrases: [
      {nl: "Komt u uit deze stad?", tr: "Bu şehirden misiniz?", ipa: "komt ü öyt dey-zı stat"},
      {nl: "Ik ben hier op vakantie.", tr: "Burada tatildeyim.", ipa: "ik ben hiir op va-kan-si"},
      {nl: "Wat een leuke stad!", tr: "Ne güzel bir şehir!", ipa: "vat eyn lö-kı stat"},
      {nl: "Spreekt u Engels?", tr: "İngilizce konuşuyor musunuz?", ipa: "spreyk t ü en-hıls"},
      {nl: "Ik leer Nederlands.", tr: "Felemenkçe öğreniyorum.", ipa: "ik leyr ney-dır-lants"},
      {nl: "Kunt u langzaam spreken?", tr: "Yavaş konuşabilir misiniz?", ipa: "künt ü lang-zaam sprey-kın"},
    ],
    grammar: "“Wat een…” hayranlık belirtmek için kullanılır: “Wat een leuke stad!” “Spreekt u…” resmi soru yapısıdır ve dil sorarken çok işe yarar. “Langzaam” yavaş anlamına gelir. Öğrenen biri olarak “Ik leer Nederlands” demek çoğu kişiyi daha sabırlı yapar.",
    practice: [
      "1. Felemenkçe öğrendiğini söyle.",
      "2. Birinin İngilizce konuşup konuşmadığını sor.",
      "3. Yavaş konuşmasını rica et.",
      "4. “Ne güzel bir şehir!” cümlesini söyle.",
      "5. Tatilde olduğunu belirten kısa bir sohbet başlangıcı yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Kendinden bahsetmek",
    titleNative: "Over jezelf vertellen",
    focus: "Yeni tanıştığın birine nereli olduğunu, ne iş yaptığını ve ne sevdiğini basitçe anlatmayı öğrenirsin. Hostelde, turda veya sosyal bir etkinlikte çok kullanışlıdır.",
    vocab: [
      {nl: "land", tr: "ülke", ipa: "lant"},
      {nl: "stad", tr: "şehir", ipa: "stat"},
      {nl: "familie", tr: "aile", ipa: "fa-mi-li"},
      {nl: "werk", tr: "iş", ipa: "verk"},
      {nl: "beroep", tr: "meslek", ipa: "bı-rup"},
      {nl: "hobby", tr: "hobi", ipa: "ho-bi"},
      {nl: "taal", tr: "dil", ipa: "taal"},
      {nl: "Nederlands", tr: "Felemenkçe", ipa: "ney-dır-lants"},
      {nl: "Turks", tr: "Türkçe", ipa: "türks"},
      {nl: "interessant", tr: "ilginç", ipa: "in-tı-re-sant"},
    ],
    phrases: [
      {nl: "Ik kom uit Istanbul.", tr: "İstanbul’dan geliyorum.", ipa: "ik kom öyt is-tan-bul"},
      {nl: "Ik woon in Turkije.", tr: "Türkiye’de yaşıyorum.", ipa: "ik von in tür-ki-yı"},
      {nl: "Ik werk in de horeca.", tr: "Hizmet sektöründe çalışıyorum.", ipa: "ik verk in dı ho-re-ka"},
      {nl: "Mijn hobby is reizen.", tr: "Hobim seyahat etmek.", ipa: "meyn ho-bi is rey-zın"},
      {nl: "Ik spreek Turks en een beetje Nederlands.", tr: "Türkçe ve biraz Felemenkçe konuşuyorum.", ipa: "ik spreyk türks en eyn bıey-cı ney-dır-lants"},
      {nl: "Dat vind ik interessant.", tr: "Bunu ilginç buluyorum.", ipa: "dat fint ik in-tı-re-sant"},
    ],
    grammar: "“Ik woon in…” yaşadığın yeri söylemek için kullanılır. “Ik werk in…” çalıştığın alanı anlatır. “Een beetje” biraz demektir ve dil becerini açıklarken çok işe yarar. “Ik spreek een beetje Nederlands” cümlesi hem dürüst hem de konuşmayı sürdürmek için güzel bir başlangıçtır.",
    practice: [
      "1. Nereden geldiğini söyle.",
      "2. Nerede yaşadığını belirt.",
      "3. Bir hobini Felemenkçe anlat.",
      "4. “Biraz Felemenkçe konuşuyorum” cümlesini yaz.",
      "5. Kendini tanıtan dört cümlelik kısa bir paragraf oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Davetler ve plan yapmak",
    titleNative: "Uitnodigingen en plannen maken",
    focus: "Yerel biriyle kahve içmek, bir müzeye gitmek veya akşam buluşmak için plan yapmayı öğrenirsin. Saat, yer ve uygunluk sormak bu dersin temelidir.",
    vocab: [
      {nl: "plan", tr: "plan", ipa: "plan"},
      {nl: "afspraak", tr: "randevu / buluşma", ipa: "af-spraak"},
      {nl: "samen", tr: "birlikte", ipa: "saa-mın"},
      {nl: "koffie", tr: "kahve", ipa: "ko-fi"},
      {nl: "vanavond", tr: "bu akşam", ipa: "fan-aa-vont"},
      {nl: "morgen", tr: "yarın", ipa: "mor-hın"},
      {nl: "vrij", tr: "boş / müsait", ipa: "frey"},
      {nl: "druk", tr: "meşgul", ipa: "drük"},
      {nl: "misschien", tr: "belki", ipa: "mis-hiyn"},
      {nl: "gezellig", tr: "keyifli / samimi", ipa: "hı-zel-lıh"},
    ],
    phrases: [
      {nl: "Zullen we koffie drinken?", tr: "Kahve içelim mi?", ipa: "zül-lın vı ko-fi dring-kın"},
      {nl: "Ben je vanavond vrij?", tr: "Bu akşam müsait misin?", ipa: "ben yı fan-aa-vont frey"},
      {nl: "Ik ben morgen druk.", tr: "Yarın meşgulüm.", ipa: "ik ben mor-hın drük"},
      {nl: "Misschien later.", tr: "Belki sonra.", ipa: "mis-hiyn laa-tır"},
      {nl: "Dat klinkt gezellig.", tr: "Kulağa keyifli geliyor.", ipa: "dat klink hı-zel-lıh"},
      {nl: "Waar zullen we afspreken?", tr: "Nerede buluşalım?", ipa: "vaar zül-lın vı af-sprey-kın"},
    ],
    grammar: "“Zullen we…” birlikte bir şey teklif etmek için kullanılır: “Zullen we gaan?” “Ben je…” samimi “müsait misin?” yapısıdır; resmi durumda “Bent u…” kullanılır. “Gezellig” Felemenkçede çok kültürel bir kelimedir; sıcak, keyifli, samimi ortamları anlatır ve Türkçeye tek kelimeyle çevirmek zordur.",
    practice: [
      "1. Birine kahve içmeyi teklif et.",
      "2. Bu akşam müsait olup olmadığını sor.",
      "3. Yarın meşgul olduğunu söyle.",
      "4. Nerede buluşacağınızı sor.",
      "5. “Gezellig” kelimesini anlatan Türkçe bir cümle yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Telefonda ve mesajda konuşmak",
    titleNative: "Bellen en berichten sturen",
    focus: "Bir restoranı aramak, oteli bilgilendirmek veya arkadaşına mesaj atmak için kısa telefon ve mesaj ifadelerini öğrenirsin. Felemenkçe mesajlarda kısa ve net dil yaygındır.",
    vocab: [
      {nl: "bellen", tr: "aramak", ipa: "bel-lın"},
      {nl: "bericht", tr: "mesaj", ipa: "bı-riht"},
      {nl: "telefoon", tr: "telefon", ipa: "te-le-fon"},
      {nl: "nummer", tr: "numara", ipa: "nü-mır"},
      {nl: "wachten", tr: "beklemek", ipa: "vah-tın"},
      {nl: "laat", tr: "geç", ipa: "laat"},
      {nl: "onderweg", tr: "yolda", ipa: "on-dır-veh"},
      {nl: "bereikbaar", tr: "ulaşılabilir", ipa: "bı-reyk-baar"},
      {nl: "sms", tr: "SMS", ipa: "es-em-es"},
      {nl: "appje", tr: "kısa mesaj", ipa: "ap-yı"},
    ],
    phrases: [
      {nl: "Ik bel later terug.", tr: "Sonra geri arayacağım.", ipa: "ik bel laa-tır trüh"},
      {nl: "Ik ben onderweg.", tr: "Yoldayım.", ipa: "ik ben on-dır-veh"},
      {nl: "Ik kom tien minuten later.", tr: "On dakika geç geliyorum.", ipa: "ik kom tiyn mi-nü-tın laa-tır"},
      {nl: "Kunt u mij bellen?", tr: "Beni arayabilir misiniz?", ipa: "künt ü mey bel-lın"},
      {nl: "Wat is uw telefoonnummer?", tr: "Telefon numaranız nedir?", ipa: "vat is üw te-le-fon-nü-mır"},
      {nl: "Stuur mij een bericht, alstublieft.", tr: "Bana bir mesaj gönderin, lütfen.", ipa: "stür mey eyn bı-riht als-tü-bliift"},
    ],
    grammar: "“Terug” geri anlamına gelir ve “terugbellen” geri aramak demektir. “Ik kom tien minuten later” randevuya geç kalacağını söylemek için basit ve nazik bir cümledir. Felemenkçede zaman miktarı doğrudan cümleye girer: “tien minuten later”. Mesajlarda kısa cümleler kullanmak doğal kabul edilir.",
    practice: [
      "1. Yolda olduğunu mesajla bildir.",
      "2. On dakika geç geleceğini söyle.",
      "3. Birinden seni aramasını iste.",
      "4. Telefon numarası sor.",
      "5. “Later” ve “terug” kelimeleriyle iki cümle kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Para, kart ve ödeme sorunları",
    titleNative: "Geld, kaart en betalen",
    focus: "Kasa, restoran veya bilet makinesinde ödeme yaparken kart, nakit ve ödeme sorunu hakkında konuşmayı öğrenirsin. Hollanda’da kartla ödeme çok yaygındır.",
    vocab: [
      {nl: "geld", tr: "para", ipa: "helt"},
      {nl: "contant", tr: "nakit", ipa: "kon-tant"},
      {nl: "pinpas", tr: "banka kartı", ipa: "pin-pas"},
      {nl: "creditcard", tr: "kredi kartı", ipa: "kre-dit-kaart"},
      {nl: "betalen", tr: "ödemek", ipa: "bı-taa-lın"},
      {nl: "bonnetje", tr: "fiş", ipa: "bon-yı-cı"},
      {nl: "machine", tr: "makine", ipa: "ma-şi-nı"},
      {nl: "saldo", tr: "bakiye", ipa: "sal-do"},
      {nl: "betaling", tr: "ödeme", ipa: "bı-taa-ling"},
      {nl: "mislukt", tr: "başarısız", ipa: "mis-lükt"},
    ],
    phrases: [
      {nl: "Kan ik met kaart betalen?", tr: "Kartla ödeyebilir miyim?", ipa: "kan ik met kaart bı-taa-lın"},
      {nl: "Neemt u contant geld?", tr: "Nakit kabul ediyor musunuz?", ipa: "neymt ü kon-tant helt"},
      {nl: "De betaling is mislukt.", tr: "Ödeme başarısız oldu.", ipa: "dı bı-taa-ling is mis-lükt"},
      {nl: "Ik probeer het nog een keer.", tr: "Bir kez daha deneyeyim.", ipa: "ik pro-beyr hıt noh eyn keyr"},
      {nl: "Mag ik het bonnetje?", tr: "Fişi alabilir miyim?", ipa: "mah ik hıt bon-yı-cı"},
      {nl: "Mijn kaart werkt niet.", tr: "Kartım çalışmıyor.", ipa: "meyn kaart werkt niyt"},
    ],
    grammar: "“Met kaart betalen” kartla ödemek anlamına gelir. “Nog een keer” bir kez daha demektir ve ödeme, tekrar söyleme veya tekrar deneme durumlarında kullanılır. “Werkt niet” kalıbı kart, makine, anahtar veya uygulama için kullanılabilir. Hollanda’da bazı yerler nakit kabul etmeyebilir, bu yüzden önceden sormak iyidir.",
    practice: [
      "1. Kartla ödeme yapıp yapamayacağını sor.",
      "2. Nakit kabul edilip edilmediğini sor.",
      "3. Kartının çalışmadığını söyle.",
      "4. Bir kez daha denemek istediğini belirt.",
      "5. Ödeme sorunu yaşayan kısa bir diyalog yaz.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Postane, paket ve adres",
    titleNative: "Post, pakket en adres",
    focus: "Kartpostal göndermek, paket almak veya adres yazmak için gerekli kelimeleri öğrenirsin. Turistik seyahatlerde postane ve kargo işlemleri hâlâ işe yarayabilir.",
    vocab: [
      {nl: "post", tr: "posta", ipa: "post"},
      {nl: "postkantoor", tr: "postane", ipa: "post-kan-tor"},
      {nl: "pakket", tr: "paket", ipa: "pa-ket"},
      {nl: "brief", tr: "mektup", ipa: "briyf"},
      {nl: "kaart", tr: "kart", ipa: "kaart"},
      {nl: "adres", tr: "adres", ipa: "a-dres"},
      {nl: "postcode", tr: "posta kodu", ipa: "post-ko-dı"},
      {nl: "stempel", tr: "damga", ipa: "stem-pıl"},
      {nl: "verzenden", tr: "göndermek", ipa: "fır-zen-dın"},
      {nl: "ontvangen", tr: "almak / teslim almak", ipa: "ont-fang-ın"},
    ],
    phrases: [
      {nl: "Waar is het postkantoor?", tr: "Postane nerede?", ipa: "vaar is hıt post-kan-tor"},
      {nl: "Ik wil een kaart versturen.", tr: "Bir kart göndermek istiyorum.", ipa: "ik vil eyn kaart fır-stü-rın"},
      {nl: "Hoeveel kost verzending naar Turkije?", tr: "Türkiye’ye gönderim ne kadar?", ipa: "hu-vel kost fır-zen-ding naar tür-ki-yı"},
      {nl: "Dit is mijn adres.", tr: "Bu benim adresim.", ipa: "dit is meyn a-dres"},
      {nl: "Ik verwacht een pakket.", tr: "Bir paket bekliyorum.", ipa: "ik fır-vaht eyn pa-ket"},
      {nl: "Heeft u een stempel?", tr: "Damganız var mı?", ipa: "heyft ü eyn stem-pıl"},
    ],
    grammar: "“Naar Turkije” Türkiye’ye demektir. “Verzenden” göndermek, “ontvangen” almak anlamına gelir. “Ik verwacht…” bekliyorum anlamında kullanılır; paket, misafir veya cevap için söylenebilir. Adres yazarken Felemenkçede posta kodu çok önemlidir ve genellikle sokak adıyla birlikte kullanılır.",
    practice: [
      "1. Postanenin nerede olduğunu sor.",
      "2. Türkiye’ye kart göndermek istediğini söyle.",
      "3. Gönderim ücretini sor.",
      "4. Bir paket beklediğini belirt.",
      "5. Kendi adresini söylemek için kalıp cümle oluştur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Çamaşır ve günlük işler",
    titleNative: "Was doen en dagelijkse zaken",
    focus: "Uzun seyahatte çamaşır yıkamak, kuru temizleme bulmak veya günlük ihtiyaçları anlatmak gerekebilir. Bu ders özellikle apart otel, hostel ve şehir içi yaşam için kullanışlıdır.",
    vocab: [
      {nl: "was", tr: "çamaşır", ipa: "vas"},
      {nl: "wasserette", tr: "çamaşırhane", ipa: "va-sı-ret-tı"},
      {nl: "wasmachine", tr: "çamaşır makinesi", ipa: "vas-ma-şi-nı"},
      {nl: "droger", tr: "kurutma makinesi", ipa: "dro-hır"},
      {nl: "zeep", tr: "sabun", ipa: "zeyp"},
      {nl: "wasmiddel", tr: "deterjan", ipa: "vas-mi-dıl"},
      {nl: "schoon", tr: "temiz", ipa: "s-hon"},
      {nl: "vies", tr: "kirli", ipa: "fiys"},
      {nl: "droog", tr: "kuru", ipa: "droh"},
      {nl: "nat", tr: "ıslak", ipa: "nat"},
    ],
    phrases: [
      {nl: "Waar is de dichtstbijzijnde wasserette?", tr: "En yakın çamaşırhane nerede?", ipa: "vaar is dı dihtst-bey-zeyn-dı va-sı-ret-tı"},
      {nl: "Ik moet mijn kleren wassen.", tr: "Kıyafetlerimi yıkamam gerekiyor.", ipa: "ik mut meyn kley-rın va-sın"},
      {nl: "Heeft u wasmiddel?", tr: "Deterjanınız var mı?", ipa: "heyft ü vas-mi-dıl"},
      {nl: "De machine werkt niet.", tr: "Makine çalışmıyor.", ipa: "dı ma-şi-nı werkt niyt"},
      {nl: "Hoe lang duurt het?", tr: "Ne kadar sürer?", ipa: "hu lang dürt hıt"},
      {nl: "Mijn kleren zijn nog nat.", tr: "Kıyafetlerim hâlâ ıslak.", ipa: "meyn kley-rın zeyn noh nat"},
    ],
    grammar: "“Moeten” gerekmek anlamına gelir; “Ik moet…” günlük zorunluluklar için kullanılır. “Hoe lang duurt het?” süre sormak için çok pratik bir kalıptır. “Nog” hâlâ anlamına gelir: “nog nat”, “nog open”, “nog hier”. Günlük işlerde basit fiillerle çok şey anlatabilirsin.",
    practice: [
      "1. En yakın çamaşırhaneyi sor.",
      "2. Kıyafetlerini yıkaman gerektiğini söyle.",
      "3. Deterjan iste.",
      "4. Makinenin çalışmadığını belirt.",
      "5. “Ne kadar sürer?” sorusunu üç farklı durumda kullan.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Yerel kurallar ve görgü",
    titleNative: "Lokale regels en omgangsvormen",
    focus: "Bisiklet yolları, sessiz alanlar ve sıra bekleme gibi yerel kuralları anlamayı öğrenirsin. Hollanda’da özellikle bisiklet trafiğine dikkat etmek çok önemlidir.",
    vocab: [
      {nl: "regel", tr: "kural", ipa: "rey-hıl"},
      {nl: "fiets", tr: "bisiklet", ipa: "fits"},
      {nl: "fietspad", tr: "bisiklet yolu", ipa: "fits-pat"},
      {nl: "wachten", tr: "beklemek", ipa: "vah-tın"},
      {nl: "rij", tr: "sıra", ipa: "rey"},
      {nl: "stil", tr: "sessiz", ipa: "stil"},
      {nl: "verboden", tr: "yasak", ipa: "fır-bo-dın"},
      {nl: "toegestaan", tr: "izinli", ipa: "tu-hı-staan"},
      {nl: "druk", tr: "kalabalık / yoğun", ipa: "drük"},
      {nl: "voorzichtig", tr: "dikkatli", ipa: "vor-zihtıh"},
    ],
    phrases: [
      {nl: "Is dit toegestaan?", tr: "Buna izin var mı?", ipa: "is dit tu-hı-staan"},
      {nl: "Hier mag u niet fietsen.", tr: "Burada bisiklete binemezsiniz.", ipa: "hiir mah ü niyt fit-sın"},
      {nl: "Waar moet ik wachten?", tr: "Nerede beklemeliyim?", ipa: "vaar mut ik vah-tın"},
      {nl: "Is dit de rij?", tr: "Sıra bu mu?", ipa: "is dit dı rey"},
      {nl: "Sorry, ik wist het niet.", tr: "Pardon, bilmiyordum.", ipa: "so-ri ik vist hıt niyt"},
      {nl: "Ik zal voorzichtig zijn.", tr: "Dikkatli olacağım.", ipa: "ik zal vor-zihtıh zeyn"},
    ],
    grammar: "“Mag” izin anlamı taşır; “mag niet” yasak veya izin yok demektir. “Moet” zorunluluk belirtir. “Ik wist het niet” bir kuralı bilmediğinde nazikçe durumu açıklamak için işe yarar. Hollanda’da bisiklet yolu genellikle yayalar için değildir; yanlış yerde yürürsen uyarılabilirsin.",
    practice: [
      "1. Sıranın nerede olduğunu sor.",
      "2. Bir şeye izin olup olmadığını sor.",
      "3. “Bilmiyordum” cümlesini söyle.",
      "4. Bisiklet yolu ile ilgili bir uyarı cümlesi yaz.",
      "5. “Mag niet” ve “moet” arasındaki farkı açıklayan iki örnek ver.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Fikir belirtmek ve tercih yapmak",
    titleNative: "Mening geven en voorkeuren uitspreken",
    focus: "Restoran, gezi planı veya alışveriş sırasında ne sevdiğini, ne tercih ettiğini ve ne düşündüğünü söylemeyi öğrenirsin. Daha doğal sohbetler için bu yapı çok önemlidir.",
    vocab: [
      {nl: "mening", tr: "fikir", ipa: "mey-ning"},
      {nl: "voorkeur", tr: "tercih", ipa: "vor-kör"},
      {nl: "mooi", tr: "güzel", ipa: "moy"},
      {nl: "lekker", tr: "lezzetli", ipa: "lek-kır"},
      {nl: "interessant", tr: "ilginç", ipa: "in-tı-re-sant"},
      {nl: "saai", tr: "sıkıcı", ipa: "saay"},
      {nl: "duur", tr: "pahalı", ipa: "dür"},
      {nl: "goedkoop", tr: "ucuz", ipa: "hut-kop"},
      {nl: "beter", tr: "daha iyi", ipa: "bey-tır"},
      {nl: "favoriet", tr: "favori", ipa: "fa-fo-riyt"},
    ],
    phrases: [
      {nl: "Ik vind dit mooi.", tr: "Bunu güzel buluyorum.", ipa: "ik fint dit moy"},
      {nl: "Ik vind het lekker.", tr: "Bunu lezzetli buluyorum.", ipa: "ik fint hıt lek-kır"},
      {nl: "Ik heb liever koffie.", tr: "Kahveyi tercih ederim.", ipa: "ik hep li-vır ko-fi"},
      {nl: "Dat is beter voor mij.", tr: "Bu benim için daha iyi.", ipa: "dat is bey-tır vor mey"},
      {nl: "Het is een beetje duur.", tr: "Biraz pahalı.", ipa: "hıt is eyn bıey-cı dür"},
      {nl: "Wat vindt u?", tr: "Siz ne düşünüyorsunuz?", ipa: "vat fint ü"},
    ],
    grammar: "“Ik vind…” fikir belirtmek için temel kalıptır. Türkçeye “bence” veya “... buluyorum” olarak çevrilebilir. “Liever” tercih belirtir: “Ik heb liever thee” çayı tercih ederim. “Een beetje” cümleyi yumuşatır; “een beetje duur” demek doğrudan “çok pahalı” demekten daha nazik olabilir.",
    practice: [
      "1. Bir yemeği lezzetli bulduğunu söyle.",
      "2. Kahveyi tercih ettiğini belirt.",
      "3. Bir şeyin biraz pahalı olduğunu söyle.",
      "4. Birinden fikrini sor.",
      "5. “Ik vind…” ile beş fikir cümlesi kur.",
    ],
    conversationIndex: 0,
    conversationCount: 0,
  },
  {
    title: "Seyahati toparlama ve vedalaşma",
    titleNative: "Reis afronden en afscheid nemen",
    focus: "Seyahatin sonunda otelden çıkış yapmak, teşekkür etmek, iyi dileklerde bulunmak ve vedalaşmak için gerekli ifadeleri öğrenirsin. Bu ders önceki tüm konuları birleştirir.",
    vocab: [
      {nl: "uitchecken", tr: "çıkış yapmak", ipa: "öyt-çe-kın"},
      {nl: "reis", tr: "seyahat", ipa: "reys"},
      {nl: "vakantie", tr: "tatil", ipa: "va-kan-si"},
      {nl: "ervaring", tr: "deneyim", ipa: "er-faa-ring"},
      {nl: "bedankt", tr: "teşekkürler", ipa: "bı-dankt"},
      {nl: "terug", tr: "geri", ipa: "trüh"},
      {nl: "volgende keer", tr: "gelecek sefer", ipa: "fol-hın-dı keyr"},
      {nl: "veilig", tr: "güvenli", ipa: "vey-lıh"},
      {nl: "thuis", tr: "evde", ipa: "töys"},
      {nl: "afscheid", tr: "veda", ipa: "af-sheyt"},
    ],
    phrases: [
      {nl: "Ik wil graag uitchecken.", tr: "Çıkış yapmak istiyorum.", ipa: "ik vil hrah öyt-çe-kın"},
      {nl: "Bedankt voor alles.", tr: "Her şey için teşekkürler.", ipa: "bı-dankt vor al-lıs"},
      {nl: "Het was een mooie reis.", tr: "Güzel bir seyahatti.", ipa: "hıt vas eyn moy-ı reys"},
      {nl: "Ik kom graag terug.", tr: "Memnuniyetle geri gelirim.", ipa: "ik kom hrah trüh"},
      {nl: "Tot de volgende keer.", tr: "Gelecek sefere kadar.", ipa: "tot dı fol-hın-dı keyr"},
      {nl: "Goede reis!", tr: "İyi yolculuklar!", ipa: "hu-dı reys"},
    ],
    grammar: "Geçmiş deneyim anlatırken “Het was…” çok pratik bir başlangıçtır: “Het was leuk”, “Het was mooi”, “Het was gezellig”. “Graag terugkomen” memnuniyetle geri gelmek anlamı taşır. Vedalaşırken “Tot ziens”, “Dag” ve “Tot de volgende keer” doğal seçeneklerdir. Seyahat sonunda kısa bir teşekkür cümlesi iyi bir izlenim bırakır.",
    practice: [
      "1. Otelden çıkış yapmak istediğini söyle.",
      "2. Her şey için teşekkür et.",
      "3. Seyahatin güzel olduğunu belirt.",
      "4. Geri gelmek istediğini söyle.",
      "5. Bir resepsiyon görevlisiyle beş cümlelik veda diyaloğu kur.",
    ],
    conversationIndex: 0,
    conversationCount: 8,
  },
];

var CONVERSATIONS_TR_NL = [
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedemorgen, wat wilt u bestellen?", tr: "Günaydın, ne sipariş etmek istersiniz?"},
      {who: "you", nl: "Goedemorgen, een koffie en een croissant, alstublieft.", tr: "Günaydın, bir kahve ve bir kruvasan, lütfen."},
      {who: "them", nl: "Wilt u melk of suiker in de koffie?", tr: "Kahvenize süt veya şeker ister misiniz?"},
      {who: "you", nl: "Met melk, maar zonder suiker, graag.", tr: "Sütlü olsun ama şekersiz, lütfen."},
      {who: "them", nl: "Voor hier of om mee te nemen?", tr: "Burada mı, paket mi?"},
      {who: "you", nl: "Om mee te nemen, alstublieft.", tr: "Paket olsun, lütfen."},
      {who: "them", nl: "Dat is zes euro vijftig.", tr: "Altı avro elli sent."},
      {who: "you", nl: "Kan ik met kaart betalen?", tr: "Kartla ödeyebilir miyim?"},
      {who: "them", nl: "Ja, dat kan.", tr: "Evet, yapabilirsiniz."},
      {who: "you", nl: "Dank u wel.", tr: "Teşekkür ederim."},
      {who: "them", nl: "Alstublieft, fijne dag!", tr: "Buyurun, iyi günler!"},
      {who: "you", nl: "Dank u, tot ziens.", tr: "Teşekkürler, görüşmek üzere."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedenavond, kan ik u helpen?", tr: "İyi akşamlar, size yardımcı olabilir miyim?"},
      {who: "you", nl: "Goedenavond, ik heb een reservering.", tr: "İyi akşamlar, rezervasyonum var."},
      {who: "them", nl: "Op welke naam staat de reservering?", tr: "Rezervasyon hangi isim adına?"},
      {who: "you", nl: "Mijn naam is Ali Yılmaz.", tr: "Adım Ali Yılmaz."},
      {who: "them", nl: "Mag ik uw paspoort zien?", tr: "Pasaportunuzu görebilir miyim?"},
      {who: "you", nl: "Ja, alstublieft.", tr: "Evet, buyurun."},
      {who: "them", nl: "U heeft kamer 204.", tr: "Odanız 204."},
      {who: "you", nl: "Dank u wel. Waar is de lift?", tr: "Teşekkür ederim. Asansör nerede?"},
      {who: "them", nl: "De lift is rechts, naast de receptie.", tr: "Asansör sağda, resepsiyonun yanında."},
      {who: "you", nl: "Hoe laat is het ontbijt?", tr: "Kahvaltı saat kaçta?"},
      {who: "them", nl: "Het ontbijt is van zeven tot tien uur.", tr: "Kahvaltı saat yediden ona kadar."},
      {who: "you", nl: "Perfect, bedankt voor uw hulp.", tr: "Harika, yardımınız için teşekkürler."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", nl: "Sorry, kunt u mij helpen?", tr: "Pardon, bana yardım edebilir misiniz?"},
      {who: "them", nl: "Ja hoor, wat zoekt u?", tr: "Tabii, ne arıyorsunuz?"},
      {who: "you", nl: "Waar is het station?", tr: "İstasyon nerede?"},
      {who: "them", nl: "Ga rechtdoor en sla dan linksaf.", tr: "Dümdüz gidin ve sonra sola dönün."},
      {who: "you", nl: "Is het ver van hier?", tr: "Buradan uzak mı?"},
      {who: "them", nl: "Nee, ongeveer tien minuten lopen.", tr: "Hayır, yaklaşık on dakika yürüme mesafesi."},
      {who: "you", nl: "Moet ik over de brug?", tr: "Köprüden geçmem gerekiyor mu?"},
      {who: "them", nl: "Ja, na de brug ziet u het station rechts.", tr: "Evet, köprüden sonra istasyonu sağda göreceksiniz."},
      {who: "you", nl: "Kunt u dat herhalen, alstublieft?", tr: "Bunu tekrar edebilir misiniz, lütfen?"},
      {who: "them", nl: "Rechtdoor, linksaf, over de brug, en dan rechts.", tr: "Dümdüz, sola, köprüden geçin ve sonra sağda."},
      {who: "you", nl: "Dank u wel voor uw hulp.", tr: "Yardımınız için teşekkür ederim."},
      {who: "them", nl: "Geen probleem, fijne dag.", tr: "Sorun değil, iyi günler."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedenavond, heeft u al gekozen?", tr: "İyi akşamlar, seçiminizi yaptınız mı?"},
      {who: "you", nl: "Nog niet. Wat raadt u aan?", tr: "Henüz değil. Ne tavsiye edersiniz?"},
      {who: "them", nl: "De vis van de dag is erg goed.", tr: "Günün balığı çok iyi."},
      {who: "you", nl: "Heeft u iets zonder vlees of vis?", tr: "Etsiz veya balıksız bir şeyiniz var mı?"},
      {who: "them", nl: "Ja, we hebben een vegetarische pasta.", tr: "Evet, vejetaryen makarnamız var."},
      {who: "you", nl: "Dat klinkt goed. Ik neem de vegetarische pasta.", tr: "Kulağa iyi geliyor. Vejetaryen makarnayı alayım."},
      {who: "them", nl: "Wilt u iets drinken?", tr: "Bir içecek ister misiniz?"},
      {who: "you", nl: "Water, alstublieft.", tr: "Su, lütfen."},
      {who: "them", nl: "Natuurlijk. Komt er verder nog iets bij?", tr: "Elbette. Başka bir şey ister misiniz?"},
      {who: "you", nl: "Nee, dank u wel.", tr: "Hayır, teşekkür ederim."},
      {who: "them", nl: "Prima, ik kom zo terug.", tr: "Tamam, birazdan dönerim."},
      {who: "you", nl: "Dank u wel.", tr: "Teşekkür ederim."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedemiddag, waar wilt u naartoe?", tr: "Tünaydın, nereye gitmek istiyorsunuz?"},
      {who: "you", nl: "Ik wil naar Utrecht, alstublieft.", tr: "Utrecht’e gitmek istiyorum, lütfen."},
      {who: "them", nl: "Enkele reis of retour?", tr: "Tek yön mü, gidiş-dönüş mü?"},
      {who: "you", nl: "Een enkele reis, graag.", tr: "Tek yön, lütfen."},
      {who: "them", nl: "Dat is twaalf euro.", tr: "On iki avro."},
      {who: "you", nl: "Kan ik met kaart betalen?", tr: "Kartla ödeyebilir miyim?"},
      {who: "them", nl: "Ja, natuurlijk.", tr: "Evet, tabii."},
      {who: "you", nl: "Vanaf welk perron vertrekt de trein?", tr: "Tren hangi perondan kalkıyor?"},
      {who: "them", nl: "Vanaf perron acht.", tr: "Sekizinci perondan."},
      {who: "you", nl: "Moet ik overstappen?", tr: "Aktarma yapmam gerekiyor mu?"},
      {who: "them", nl: "Nee, het is een directe trein.", tr: "Hayır, direkt tren."},
      {who: "you", nl: "Dank u wel, fijne dag.", tr: "Teşekkür ederim, iyi günler."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Hallo, kan ik u helpen?", tr: "Merhaba, size yardımcı olabilir miyim?"},
      {who: "you", nl: "Ja, ik zoek een jas.", tr: "Evet, bir mont arıyorum."},
      {who: "them", nl: "Welke maat heeft u nodig?", tr: "Hangi bedene ihtiyacınız var?"},
      {who: "you", nl: "Heeft u deze in een grotere maat?", tr: "Bunun daha büyük bedeni var mı?"},
      {who: "them", nl: "Ja, ik kijk even voor u.", tr: "Evet, sizin için hemen bakıyorum."},
      {who: "you", nl: "Dank u wel. Deze kleur vind ik mooi.", tr: "Teşekkür ederim. Bu rengi güzel buluyorum."},
      {who: "them", nl: "Hier is een grotere maat.", tr: "İşte daha büyük bir beden."},
      {who: "you", nl: "Waar is de paskamer?", tr: "Deneme kabini nerede?"},
      {who: "them", nl: "De paskamer is daar links.", tr: "Deneme kabini orada solda."},
      {who: "you", nl: "Bedankt.", tr: "Teşekkürler."},
      {who: "them", nl: "Geen probleem.", tr: "Sorun değil."},
      {who: "you", nl: "Als het past, neem ik deze.", tr: "Olursa bunu alacağım."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "them", nl: "Goedemiddag, waarmee kan ik u helpen?", tr: "Tünaydın, size nasıl yardımcı olabilirim?"},
      {who: "you", nl: "Ik heb hoofdpijn.", tr: "Başım ağrıyor."},
      {who: "them", nl: "Heeft u ook koorts?", tr: "Ateşiniz de var mı?"},
      {who: "you", nl: "Nee, geen koorts.", tr: "Hayır, ateşim yok."},
      {who: "them", nl: "Heeft u een allergie?", tr: "Alerjiniz var mı?"},
      {who: "you", nl: "Ja, ik heb een allergie voor aspirine.", tr: "Evet, aspirine alerjim var."},
      {who: "them", nl: "Dan raad ik deze tabletten aan.", tr: "O zaman bu tabletleri tavsiye ederim."},
      {who: "you", nl: "Hoe vaak moet ik ze nemen?", tr: "Ne sıklıkla almalıyım?"},
      {who: "them", nl: "Twee keer per dag, na het eten.", tr: "Günde iki kez, yemekten sonra."},
      {who: "you", nl: "Dank u wel. Hoeveel kost het?", tr: "Teşekkür ederim. Ne kadar?"},
      {who: "them", nl: "Dat is vijf euro.", tr: "Beş avro."},
      {who: "you", nl: "Alstublieft.", tr: "Buyurun."},
    ],
  },
  {
    setting: "",
    lines: [
      {who: "you", nl: "Wat een mooie stad!", tr: "Ne güzel bir şehir!"},
      {who: "them", nl: "Ja, Brugge is heel mooi. Bent u hier op vakantie?", tr: "Evet, Brugge çok güzel. Burada tatilde misiniz?"},
      {who: "you", nl: "Ja, ik ben hier drie dagen.", tr: "Evet, üç günlüğüne buradayım."},
      {who: "them", nl: "Komt u uit Nederland?", tr: "Hollanda’dan mı geliyorsunuz?"},
      {who: "you", nl: "Nee, ik kom uit Turkije.", tr: "Hayır, Türkiye’den geliyorum."},
      {who: "them", nl: "Spreekt u Nederlands?", tr: "Felemenkçe konuşuyor musunuz?"},
      {who: "you", nl: "Een beetje. Ik leer Nederlands.", tr: "Biraz. Felemenkçe öğreniyorum."},
      {who: "them", nl: "U spreekt al goed.", tr: "Şimdiden iyi konuşuyorsunuz."},
      {who: "you", nl: "Dank u wel, maar kunt u langzaam spreken?", tr: "Teşekkür ederim, ama yavaş konuşabilir misiniz?"},
      {who: "them", nl: "Natuurlijk, geen probleem.", tr: "Tabii, sorun değil."},
      {who: "you", nl: "Heeft u een tip voor een goed café?", tr: "İyi bir kafe için öneriniz var mı?"},
      {who: "them", nl: "Ja, er is een gezellig café om de hoek.", tr: "Evet, köşede keyifli bir kafe var."},
    ],
  },
];